### ISSUE TITLE
Autoloader plugin tries to load prism-none.min.js

### ISSUE THREAD

**Issue by mgenware** [PrismJS/prism#1000]
It seems that adding a `language-none` is a preferred way to make code blocks of unknown languages work with prism plugins, like [line numbers](http://prismjs.com/plugins/line-numbers/). but the autoloader plugin will try to load `prism-none.min.js`, which causes 404 errors.

**Comment by Golmote** [comment]
Hi. Thanks for reporting.

You're right, `language-none` is the preferred way to do that. The Autoloader plugin won't try to load the "none" component anymore.
