### ISSUE TITLE
Infinite loop / stuck for asciidoc

### ISSUE THREAD

**Issue by SamyPesse** [PrismJS/prism#1001]
When trying to highlight this file (https://drive.google.com/open?id=0BysUdX0OApHyTm1xV0NvY2V5V00) with Asciidoc, it gets stuck in an infinite loop

Code used: 

```js
var grammar = Prism.languages.asciidoc;
Prism.tokenize(text, grammar);
```

It may be related to an encoding issue in the file since if I copy paste the content in a new file, the issue disappear.

**Comment by SamyPesse** [comment]
It works if I normalize newlines with: `text = text.replace(/\r\n/g, '\n');`

**Comment by Golmote** [comment]
Hi! Thanks for reporting.

The issue should be fixed now. I managed to highlight your file. Feel free to reopen if not ;)
