### ISSUE TITLE
Snippet specific highlighting options or precedent? 

### ISSUE THREAD

**Issue by sheriffderek** [PrismJS/prism#1004]
Hello. I'm trying to use a very minimal theme - and then to highlight specific phrases within that theme to walk through parts of the respective program. This seems pretty tricky. I made a hand classed example and it took me an hour, so that is definitely not an option. HA! 

My first thoughts are that I could pass a string into some `data-highlight-1="assert"`, search the snippet and then add a span with a very specific declaration that would override the theme style. I could possibly use [blast.js](http://velocityjs.org/blast/) to search  - and if I can't get closing parens etc, that would probably be fine.

Does anyone have any ideas or hooks or precedents that may help me on my journey or that I haven't found in the docs? Thanks.  : )

<img width="651" alt="screen shot 2016-07-20 at 2 27 59 pm" src="https://cloud.githubusercontent.com/assets/2066617/17003766/4480dc60-4e86-11e6-85db-585a2e7aa8b9.png">

http://codepen.io/sheriffderek/pen/NAYbJX

**Comment by LeaVerou** [comment]
I would suggest using the Keep Markup plugin, then mark the code that should stand out with `<mark>` tags and use appropriate CSS. That's what I do when I need this!

**Comment by sheriffderek** [comment]
Wonderful. Thank you Lea. That sounds like a good plan. : )

**Comment by LeaVerou** [comment]
Closing this then, let us know if you need any more help and we can reopen it!
