### ISSUE TITLE
Allow disabling "spellcheck" attribute

### ISSUE THREAD

**Issue by Jameskmonger** [PrismJS/prism#1008]
The `spellcheck` attribute on `span` elements is not supported by [AMP](https://www.ampproject.org/).

It would be great to have an option to turn this attribute off for comments.

This block in `prism-core.js` is responsible:

    if (env.type == 'comment') {
        env.attributes['spellcheck'] = 'true';
    }

I would be happy to submit a pull request for this.

**Comment by LeaVerou** [comment]
This can be done with a plugin. I'll let someone comment on which hook.

**Comment by Jameskmonger** [comment]
Thanks @LeaVerou. I solved it :smile:

```
prism.hooks.add('wrap', function(env) {
    if (env.type == 'comment') {
		delete env.attributes.spellcheck;
	}
});
```
