### ISSUE TITLE
Console output correct tag?

### ISSUE THREAD

**Issue by binarygenius** [PrismJS/prism#1010]
Hi,

What is the correct class tag to use to get console output and commands highlighted?

I have previously been using the "bash" keyword since it is a bash console, but this is causing problems when the console output contains a word like "while".

Please see this issue which is the same in my Atom editor.

https://github.com/atom/language-gfm/issues/165

Prism will also highlight the "while" word making the console example look wrong in the HTML page:

![1](https://cloud.githubusercontent.com/assets/15728070/17464008/7eb3fd2a-5cd4-11e6-8b99-1de778f615b2.png)

While the "while" word should get highlighted in a bash script, it should not get highlighted in console output.

Simply using a non-existent language class tag such as "console" works, but is this the way to do it?

Kind regards

**Comment by Golmote** [comment]
Hi @binarygenius. As 50Wliu said in the atom issue, the code you're highlighting is not bash, so it does not get highlighted properly.

If you're looking for a way to get the Prism's theme applied to the code block without any actual highlighting done, you can indeed use any non-existant language. We do advice using the class `language-none` though, to prevent any future conflict.

**Comment by binarygenius** [comment]
Hi @Golmote, thank you very much for the feedback. I have adopted the `language-none` option.
