### ISSUE TITLE
Bug in SCSS data URI highlighting

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#1013]
Just came across [this](http://lucidmoon.co.uk/svg/datauri/sass/compass/embedded/svg-data-uri-scss/):

![image](https://cloud.githubusercontent.com/assets/175836/17738199/000cbac6-6499-11e6-8942-d366c881b342.png)

**Comment by Golmote** [comment]
It looks like the `string` pattern in the CSS components lacks the `greedy` flag.
