### ISSUE TITLE
Show line numbers on server-rendered code

### ISSUE THREAD

**Issue by dawsonbotsford** [PrismJS/prism#1015]
When using the npm module `prismjs`, [it is recommended](http://prismjs.com/extending.html#api) to call `Prism.highlight(<code>, <language>)`. This works fine for styling pure text, but how do we access the full features like **line numbers** for the `pre` element which is wrapping the `code` element?

I'm unable to find any examples of this being accomplished. Thanks!

**Comment by Golmote** [comment]
Hi @dawsonbotsford. As far as I can tell, this can not been accomplished right now, since most plugins rely on the DOM, and on the code being put inside an HTML tag. For that reason, Prism is unable to run those plugins server-side.

**Comment by dawsonbotsford** [comment]
Is there no way to mock the dom and then detect newlines within that?

**Comment by Golmote** [comment]
Feel free to try. If you manage to make it work, maybe you can share the code here to help other people trying to achieve that.

**Comment by dawsonbotsford** [comment]
I appreciate the response but I've not got the ability to contribute to a codebase this large at this time. Thanks for the response 👍
