### ISSUE TITLE
Using non-default Prism languages with Webpack

### ISSUE THREAD

**Issue by jswny** [PrismJS/prism#1020]
I'm trying to use Prism with Webpack. I've installed Prism with NPM, and I am importing Prism in my `entry.js` like so: `import 'prismjs'`. This works fine for highlighting the default languages like JavaScript, however, I have some Scala snippets that I need to highlight, but I cannot figure out how to include the Scala component. I've tried the following in my `entry.js`:

```
import 'prismjs';
import 'prismjs/components/prism-scala.js';
```

However this leaves me with the following error in the browser console: `prism.js:79 Uncaught TypeError: Cannot set property 'keyword' of undefined`. How can I import these other languages so that they can be included with the client-side Prism instance I'm using with Webpack?'

For reference, I'm just importing the resulting Webpack bundle into my page and then using the `language-scala` class on my snippets.

webpack.conf.js:

```
{
  entry: {
    home: './lib/client/js/pages/home.js',
    projects: './lib/client/js/pages/projects.js',
    post: './lib/client/js/pages/post.js'
  },
  output: {
    filename: '[name].js',
    publicPath: '/webpack/'
  },
  devtool: 'source-map',
  module: {
    loaders: [
      { test: /\.css$/, loader: 'style!css?sourceMap' },
      { test: /\.scss$/, loaders: ['style', 'css?sourceMap', 'sass'] },
      { test: /\.(eot|svg|ttf|woff(2)?)(\?v=\d+\.\d+\.\d+)?/, loader: 'url' },
      {
        test: /\.js$/,
        exclude: /(node_modules)/,
        loader: 'babel',
        query: {
          presets: ['es2015', 'stage-2']
        }
      }
    ]
  },
  sassLoader: {
    sourceMap: true
  },
  plugins: [
    new commons('commons.js', ['home', 'projects', 'post'])
  ]
}
```

**Comment by getsnoopy** [comment]
You can require the languages you need as dependencies directly in the file that specifies Prism as a dependency. For example:
```
var prism = require('prismjs');
require('prismjs/components/prism-scala');
```

**Comment by jswny** [comment]
@getsnoopy Using Webpack with 
```
var prism = require('prismjs');
require('prismjs/components/prism-scala');
```
in my `entry.js` and then using the resulting bundle in my page I still cannot get syntax highlighting to work with Scala. JS syntax highlighting works fine, however my Scala snippets do not.

Additionally, the page is completely broken when I try to use your suggestion in the ES6 syntax style with Babel like so:
```
import 'prismjs';
import 'prismjs/components/prism-scala';
```
or
```
import prism from 'prismjs';
import 'prismjs/components/prism-scala';
```
in my `entry.js` file.

**Comment by mAAdhaTTah** [comment]
Use:

```
import Prism from 'prismjs/components/prism-core';
```

**Comment by jswny** [comment]
@mAAdhaTTah That seems to work fine in terms of getting Prism loaded into my pages. However, when I try to put either

```
require('prismjs/components/prism-scala');
```
or
```
import 'prismjs/components/prism-scala';
```
After I import Prism into my `entry.js` so that I can include the Scala syntax highlighting I get the following error: `prism-core.js:74 Uncaught TypeError: Cannot set property 'keyword' of undefined`.

**Comment by mAAdhaTTah** [comment]
`scala` has a depdency on `java`, as per the [`components.js`](https://github.com/PrismJS/prism/blob/gh-pages/components.js#L486). Make sure you import `java` first.

**Comment by jswny** [comment]
@mAAdhaTTah Thanks but that still doesn't work. Using

```
import 'prismjs/themes/prism-okaidia.css';
import Prism from 'prismjs/components/prism-core';
import 'prismjs/components/prism-java';
import 'prismjs/components/prism-scala';
```
my css breaks, while using
```
import 'prismjs/themes/prism-okaidia.css';
import Prism from 'prismjs/components/prism-core';
require('prismjs/components/prism-java');
require('prismjs/components/prism-scala');
```
my CSS doesn't break but nothing is highlighted. In both instances I still get the same error: `rism-core.js:74 Uncaught TypeError: Cannot set property 'keyword' of undefined`.

**Comment by getsnoopy** [comment]
Hmm...the code I posted works for me. It seems like it can't find the reference to the global `Prism`. One thing you might want to check is what the transpiled code looks like. The Babel preset treats modules as ES6 modules where top-level `this` resolves to `undefined`. This affects UMD-style libraries which try to use `this` as a reference to the global scope. You might be able to get around this by using an `imports-loader` on your modules, or by allowing top-level `this` explicitly: https://github.com/babel/babelify/issues/37

**Comment by otakustay** [comment]
I find a solution using the [val-loader](https://webpack.js.org/loaders/val-loader) to "build" a custom prism, here is the `prism.js` code:

```js
const {readFileSync} = require('fs');
const {flatMap} = require('lodash');

const createResolver = transform => name => {
    const path = require.resolve(transform(name));
    const content = readFileSync(path, 'utf-8');

    return {path, content};
};
const resolveMain = createResolver(() => 'prismjs/components/prism-core');
const resolvePlugin = createResolver(name => `prismjs/plugins/${name}/prism-${name}`);
const resolveLanguage = createResolver(name => `prismjs/components/prism-${name}`);
// 把配置文件读出来，去掉前面的`var components = `和最后的`;`，中间的部分是个JSON
const prismComponentsCode = readFileSync(require.resolve('prismjs/components'), 'utf-8');
const prismComponents = JSON.parse(/(\{[\w\W]+\});/.exec(prismComponentsCode)[1]);

const resolveLanguageDependencies = language => {
    const requires = prismComponents.languages[language].require;

    if (!requires) {
        return [];
    }

    const dependencies = [].concat(requires);

    return [
        ...flatMap(dependencies, resolveLanguageDependencies),
        ...dependencies
    ];
};

const sortLanguages = languages => {
    const result = languages.reduce(
        (result, current) => {
            const requires = resolveLanguageDependencies(current);
            requires.forEach(language => result.add(language));

            return result.add(current);
        },
        new Set()
    );
    return Array.from(result);
};

const config = {
    plugins: [
        'keep-markup'
    ],
    languages: [
        'actionscript',
        'applescript',
        'aspnet'
    ]
};

module.exports = () => {
    const main = resolveMain();
    const plugins = config.plugins.map(resolvePlugin);
    const languages = sortLanguages(config.languages).map(resolveLanguage);
    const modules = [...plugins, ...languages];

    const code = [
        'const global = {};',
        'const self = global;',
        'const window = global;',
        main.content,
        ...modules.map(result => result.content)
    ];
    const dependencies = [
        main.path,
        ...modules.map(result => result.path)
    ];

    return {
        code: code.join('\n'),
        dependencies: dependencies,
        cacheable: true
    };
};
```

Set this file to use `['babel-loader', 'val-loader']` in `webpack.config.js`, then by `import Prism from 'xxx'` you can get a prism object with configured plugins and languages

**Comment by felixhao28** [comment]
I figured it out by using this:

```js
import Prism from 'prismjs/components/prism-core'
import 'prismjs/components/prism-clike'
import 'prismjs/components/prism-java'
import 'prismjs/themes/prism.css'
```

Prism is pretty stupid on resolving dynamic dependencies. First prism-core set Prism object to global.Prism, then it's used in language definition files. The definition files have dependencies with each other. In this case, "scale" depends on "java" which depends on "clike".

My webpack.config.js is very standard:

```js
const path = require('path');

module.exports = {
    entry: './src/index.js',
    // devtool: 'sourcemap',
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist')
    },
    module: {
        rules: [{
            test: /\.js$/,
            exclude: /(node_modules|bower_components)/,
            use: {
                loader: 'babel-loader',
                options: {
                    presets: ['@babel/preset-env']
                }
            }
        }, {
            test: /\.css$/,
            use: ['style-loader', 'css-loader']
        }]
    }
};
```

**Comment by Golmote** [comment]
I assume [the solution to #972](https://github.com/PrismJS/prism/issues/972#issuecomment-374736957) will also work for this issue.

**Comment by Volmarg** [comment]
I also use webpack but the solution above didn't worked fully for me, so this is how I solved it:

````
import * as $ from 'jquery';

import Prism from 'prismjs';
import 'prismjs/components/prism-markup-templating';
import 'prismjs/components/prism-php';
import 'prismjs/components/prism-javascript';
import 'prismjs/components/prism-markup';
import 'prismjs/components/prism-css';
import 'prismjs/components/prism-bash';
import 'prismjs/themes/prism.css';

export default (function () {
    window.prismjs = {};
    prismjs = {
        init: function(){
            this.highlightCode();
        },
        highlightCode: function(){
            let $codeElements = $('code[class^="language-"]');
            $.each($codeElements, function(index, codeElement){
                Prism.highlightElement(codeElement);
            });
        }
    };
}())
````
