### ISSUE TITLE
problem with json

### ISSUE THREAD

**Issue by Megafarm** [PrismJS/prism#1025]
Hi,
i wnat to highlight a json multi array but only the last value is green and the other are red. i want to have all values in green! is there a way to do this ?

example: {"key1":"value1","key2":"value2","key3":"value3"}
--> just value3 is green (edit!! - before: red)

PLEASE HELP ME! :D

**Comment by Golmote** [comment]
Hi, could you show us your code so we can investigate this issue?

Also, shouting is not necessary ;)

**Comment by Megafarm** [comment]
Thanks for replying,
here is the code:

HTML formated:
`<pre class=" language-json"><code class=" language-json"><span class="token punctuation">{</span><span class="token property">"message"</span><span class="token operator">:</span><span class="token property">"created new file -all-, value inserted;created new file -24h-, value inserted;created new file -168h-, value inserted;created new file -current-, value inserted;","data"</span><span class="token operator">:</span><span class="token property">"DEIN TEMPERATURWERT","ip"</span><span class="token operator">:</span><span class="token property">"DEINE IP-ADRESSE","appid"</span><span class="token operator">:</span><span class="token property">"DEINE APPID","lastinsert"</span><span class="token operator">:</span><span class="token string">"ZEITPUNKT DES DATENUPLOADES"</span><span class="token punctuation">}</span></code>
</pre>`

HTML unformated:
`<pre>
<code class="language-json">{"message":"created new file -all-, value inserted;created new file -24h-, value inserted;created new file -168h-, value inserted;created new file -current-, value inserted;","data":"YOUR TEMPERATURE VALUE","ip":"YOUR IP-ADDRESS","appid":"YOUR APPID","lastinsert":"TIME OF UPLOADING"}</code>
</pre>
`
Just the "TIME OF UPLOADING" is green, other red

**Comment by LeaVerou** [comment]
Yeah, this looks like a bug on our end. Note that if the JSON was formatted properly, the highlighting works.

**Comment by Golmote** [comment]
Thanks for the code sample. It should be fixed now.

**Comment by Megafarm** [comment]
Yes, @Golmote 

thanks it works now :D
