### ISSUE TITLE
Highlighting doesn't work with lookbehind

### ISSUE THREAD

**Issue by DerpfacePython** [PrismJS/prism#1026]
I'm making a custom syntax highlighter for my new language, [Logicode](https://github.com/LogicodeLang/Logicode), and here is what I have so far:

(`lgc-highlight.js`)
```js
Prism.languages.logicode = {
  "comment": /\#(.*)/,
  "keyword": /(.*)(cond|circ|var|out)/,
  "number": /[01]+/,
  "symbol": /(->)/,
  "builtin": /([\\+!&\|\/<~@>]|[ab]inp|[^-]>)/,
  "function": [{
    pattern: /([\+=\/&!\|,\(]|out|cond)([ \w]+)(?=\(.*\))/,
    lookbehind: true
  }, {
    pattern: /(circ )(\w+)(?=\()/,
    lookbehind: true
  }],
  "variable": {
    pattern: /(var )(.*?)(?= *=)/,
    lookbehind: true
  }
}
```

My `prism.js` and `prism.css` is the most recent version, I downloaded it yesterday.

Here is the HTML stuff:

```html
<pre class="language-logicode"><code class="language-logicode">
  circ asdf(n) -> [
      var jk = 1011
      jk&n
  ]
  out asdf(100)
</code></pre>
```

This is the result:
![bug](https://cloud.githubusercontent.com/assets/14177193/18854299/bd64c21c-848d-11e6-8298-1efae4ecfbd7.PNG)

I expected the:

- `asdf` in the first line to highlight
- `jk` in the second line to highlight
- `asdf` in the fifth (last) line to highlight

I'm guessing the problem is with `lookbehind`, which doesn't work for some reason. Is there anything I'm doing wrong?

**Comment by Golmote** [comment]
Hi!
The `lookbehind` cannot work if the part being matched behind has already been highlighted. The patterns are processed in the order they are defined in, so I guess you need to move the `function` and `variable` patterns up, above the `keyword` pattern.

**Comment by DerpfacePython** [comment]
Oh yeah, I forgot about the `keyword` matching everything.

Well, thanks for the quick reply @Golmote, everything works!
