### ISSUE TITLE
change language title name

### ISSUE THREAD

**Issue by flashpixx** [PrismJS/prism#1027]
Hello,

I'm using Prim's "show language name" structure. I have defined my own language definition within an own JS file and my definition works well with the current structure. But I would like to change the title of my language, which is shown by "show language name". I would like to add like cpp a C++ definition. How I can put this individual title name to the main structure?

**Comment by Golmote** [comment]
Hi!

You should be able to override the name displayed by adding a `data-language` attribute on the `<pre>` element containing your code. This is the easiest solution.

Alternatively, you could add you language definition to the `components.js` file, give it a proper `title` and then run the `gulp` command to regenerate the map used by the Show Language plugin.

**Comment by flashpixx** [comment]
Thanks I'm using the ```data-language``` attribute
