### ISSUE TITLE
Remove Dead Link on Tutorials

### ISSUE THREAD

**Issue by snakeman21** [PrismJS/prism#1028]
This tutorial doesn't work anymore http://davidpea.ch/articles/287.

Also, I created a tutorial on how to use Markdown in conjunction with PrismJS https://websitebeaver.com/escape-html-inside-code-or-pre-tag-to-entities-to-display-raw-code-with-prismjs. This is an important tutorial to add as it is very common to use the two together.

**Comment by Golmote** [comment]
@LeaVerou I won't add any new links in the Third-party tutorials on my own choice. So if you wish to add the proposed one, feel free to do so (or say so and I'll do it).

**Comment by snakeman21** [comment]
@LeaVerou Sorry, don't mean to be annoying, but would it be possible to add my tutorial? Or are you guys not adding third-party tutorials anymore?

**Comment by LeaVerou** [comment]
@snakeman21 We typically don't just add tutorials on our own, someone sends a pull request and we merge it. Feel free to send a pull request to remove the dead link and add your tutorial :)

**Comment by snakeman21** [comment]
Thank you so much, you're the best! Will do so. @Golmote already did actually.
