### ISSUE TITLE
[File Highlight] support adding a link in some corner of the code block for downloading

### ISSUE THREAD

**Issue by xuhdev** [PrismJS/prism#1030]
It would be nice if File Highlight can insert an additional download link for readers to download the original file that prism.js displays.

**Comment by mAAdhaTTah** [comment]
@Golmote I'm not seeing the download link on the linked page.

**Comment by Golmote** [comment]
@mAAdhaTTah On the last example? I can see it working properly...

**Comment by mAAdhaTTah** [comment]
Yeah, looks like this in the Chrome devtools:

<img width="311" alt="banners_and_alerts_and_developer_tools_-_http___prismjs_com_plugins_file-highlight_" src="https://user-images.githubusercontent.com/4371429/38867837-3099e890-4213-11e8-980c-63a586bf7254.png">

Toolbar doesn't have anything in it. :/

**Comment by Golmote** [comment]
@mAAdhaTTah I've just fixed an issue in cd22499c363bcdc6a290b77d271516886dad130f, but it seems totally unrelated to the issue you're showing there.
I don't get it, I can't reproduce the issue on neither Firefox nor Chrome. Are you sure you don't have some sort of browser cache or something?

**Comment by mAAdhaTTah** [comment]
Weird... let me clone the repo locally and dig into it.

**Comment by Golmote** [comment]
@mAAdhaTTah Did you find anything? :worried:

**Comment by mAAdhaTTah** [comment]
Haven't had a chance to dig into it–just moved into a new place. It's on my todo list tho.
