### ISSUE TITLE
Move the webworker to the highlight function

### ISSUE THREAD

**Issue by XVincentX** [PrismJS/prism#1031]
Actually the webworker code is done basically in the `highlightElement` function - thous leaving the raw `highlight` method to be alway executed in the browser.

What do you think about moving the webworker code in the inner `highlight` function?
It would help who's using that function for custom purposes.

**Comment by mAAdhaTTah** [comment]
If this is something you're interested in pursuing, we'd welcome a PR! Otherwise, I'm closing as we probably won't address this ourselves.
