### ISSUE TITLE
Encoded entity reference breaks Prism with language-xml.

### ISSUE THREAD

**Issue by garretwilson** [PrismJS/prism#1034]
Very odd: the presence of a character reference (properly encoded!) completely breaks Prism for the rest of the document. Take this simple example in the coy theme:

``` html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="UTF-8" />
    <title>prism.js entity reference bug</title>
    <link type="text/css" rel="stylesheet" href="../../css/lesson.css" />
  </head>
  <body>
    <pre class="line-numbers"><code class="language-java">&lt;foo&gt;bar&lt;/foo&gt;</code></pre>
    <pre class="line-numbers"><code class="language-java">&lt;foo&gt;bar&lt;/foo&gt;</code></pre>
    <script src="../../js/prism.js"></script>
  </body>
</html>
```

That formats as you would expect. Now look what happens when we add this one line:

``` html
    <p>This <code class="language-xml">&amp;eacute;</code> confuses prism.js.</p>
```

Prism stops working after that point:

``` html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="UTF-8" />
    <title>prism.js entity reference bug</title>
    <link type="text/css" rel="stylesheet" href="../../css/lesson.css" />
  </head>
  <body>
    <pre class="line-numbers"><code class="language-java">&lt;foo&gt;bar&lt;/foo&gt;</code></pre>
    <p>This <code class="language-xml">&amp;eacute;</code> confuses prism.js.</p>
    <pre class="line-numbers"><code class="language-java">&lt;foo&gt;bar&lt;/foo&gt;</code></pre>
    <script src="../../js/prism.js"></script>
  </body>
</html>
```

If you take out the "language-xml" it works:

``` html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="UTF-8" />
    <title>prism.js entity reference bug</title>
    <link type="text/css" rel="stylesheet" href="../../css/lesson.css" />
  </head>
  <body>
    <pre class="line-numbers"><code class="language-java">&lt;foo&gt;bar&lt;/foo&gt;</code></pre>
    <p>This <code>&amp;eacute;</code> confuses prism.js.</p>
    <pre class="line-numbers"><code class="language-java">&lt;foo&gt;bar&lt;/foo&gt;</code></pre>
    <script src="../../js/prism.js"></script>
  </body>
</html>
```

**Comment by Golmote** [comment]
Hi, sorry for the late answer.
Can you provide a screenshot of the actual result versus the expected result? I can't reproduce the issue myself.

**Comment by Golmote** [comment]
Please reopen if you can provide a screeenshot or (better) an online example reproducing the issue.

**Comment by garretwilson** [comment]
It's odd that you couldn't reproduce it. I gave exactly the files needed to reproduce it. In fact I couldn't even find the original files, so I created them by copying from my own issue. Here's a screen shot. You'll see the second code block is _not_ formatted, even though it's the same as the first. It's the presence of that single line.

![prism-issue-96](https://cloud.githubusercontent.com/assets/627125/24535116/f11d1a0c-1586-11e7-93d7-c47b90b602bb.png)

Prism gets confused by an `&amp;` followed by `eacute;`. You'll notice that this is an `&eacute;`, but encoded. Because the ampersand is encoded, it shouldn't be recognized as an HTML entity reference. I wouldn't doubt someone is just recursively decoding entities---which would be completely incorrect (and would produce a bug like this). The whole point of encoding the `&amp;` is so that it _won't_ be recognized as a delimiter.

But maybe I'm guessing wrong about the source of the problem. Whatever the case... there is a problem!

**Comment by zeitgeist87** [comment]
I cannot reproduce this issue either. I used this HTML:

```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="UTF-8" />
    <title>prism.js entity reference bug</title>
    <link rel="stylesheet" href="themes/prism-coy.css" data-noprefix />
    <link rel="stylesheet" href="plugins/line-numbers/prism-line-numbers.css" data-noprefix />
  </head>
  <body>
    <pre class="line-numbers"><code class="language-java">&lt;foo&gt;bar&lt;/foo&gt;</code></pre>
    <p>This <code class="language-xml">&amp;eacute;</code> confuses prism.js.</p>
    <pre class="line-numbers"><code class="language-java">&lt;foo&gt;bar&lt;/foo&gt;</code></pre>

    <script src="prism.js"></script>
    <script src="components/prism-java.js"></script>
    <script src="plugins/line-numbers/prism-line-numbers.js"></script>
  </body>
</html>
```

This is the result:

![bug](https://cloud.githubusercontent.com/assets/1210795/24537995/b62656ec-15e6-11e7-8593-8c9933c7faca.png)

Maybe a CSS class from your `../../css/lesson.css` is conflicting with a class that is used by `language-xml`.

**Comment by garretwilson** [comment]
No, it's Prism. In Chrome Prism is giving me the exception:

> Uncaught DOMException: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.
    at Object.highlightElement (file:///.../prism.js:2:2874)
    at XMLDocument.highlightAll (file:///.../prism.js:2:1846)

I'm running the minified version. I don't have time right now to download the full one, although I'll try to get to it some day.

I'm running Prism with the "coy" theme, all languages, and the following plugins:
* Line Numbers
* Keep Markup
* Command Line

**Comment by garretwilson** [comment]
I note that you're not including all the plugins I mentioned.

But an even bigger issue I see is that you're parsing the file as HTML, even though the test file you're using is clearing trying to be XML. (It has an XML header, and it uses namespaces.) Yet the file is not well-formed XML, because you have an attribute `data-noprefix` with no value!

Do the following and I can almost guarantee you'll the the problem.

1. Copy exactly the non-working example I gave:

```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="UTF-8" />
    <title>prism.js entity reference bug</title>
    <link type="text/css" rel="stylesheet" href="../../css/lesson.css" />
  </head>
  <body>
    <pre class="line-numbers"><code class="language-java">&lt;foo&gt;bar&lt;/foo&gt;</code></pre>
    <p>This <code class="language-xml">&amp;eacute;</code> confuses prism.js.</p>
    <pre class="line-numbers"><code class="language-java">&lt;foo&gt;bar&lt;/foo&gt;</code></pre>
    <script src="../../js/prism.js"></script>
  </body>
</html>
```

2. Replace the stylesheet links with the appropriate links to Prism with the "coy" theme and the plugins I mention above. (Obviously update the JavaScript link as well.)
3. **Save the file with an `.xhtml` extention** and load it in Chrome.
