### ISSUE TITLE
a combination of // and * in a JS string template produce bad highlighting

### ISSUE THREAD

**Issue by gre** [PrismJS/prism#1043]
<img width="357" alt="screen shot 2016-10-27 at 11 19 19" src="https://cloud.githubusercontent.com/assets/211411/19761696/4b9aedde-9c37-11e6-93ec-141cac3f8ab1.png">

**Comment by gre** [comment]
here is another example

**Prism**

<img width="168" alt="screen shot 2016-10-27 at 11 25 15" src="https://cloud.githubusercontent.com/assets/211411/19761904/144a38d4-9c38-11e6-9a0d-ce1e58ec9582.png">

**Atom**

<img width="214" alt="screen shot 2016-10-27 at 11 25 26" src="https://cloud.githubusercontent.com/assets/211411/19761905/145c2b3e-9c38-11e6-8deb-b46454f6a88f.png">

**Comment by gre** [comment]
any workaround or idea of where the bug is ?

**Comment by Golmote** [comment]
Hi, sorry for the late answer. Can you reproduce this issue on the [test page](http://prismjs.com/test.html)?

**Comment by gre** [comment]
mmh, no I can't, is it running a special version? mmh I'm using version 1.5.1 published on npm.

I can still reproduce it if I paste this:

```
document.write(`<link rel="stylesheet" href="https://rawgit.com/PrismJS/prism/gh-pages/themes/prism.css" />`);


var Prism = require('prismjs');
var code = [
"const c = `",
"// do something",
"float a = p.x * p.y;",
"",
"// do something else",
"float b = a * 2.0;",
"`;"
].join("\n");      

var html = Prism.highlight(code, Prism.languages.javascript);
document.write('<pre>'+html+'</pre>');  
```

in http://requirebin.com/

**Comment by mAAdhaTTah** [comment]
The version on npm is often behind the version on GitHub & the download page. I usually install prism from GitHub using npm for this reason.
