### ISSUE TITLE
language-reason support

### ISSUE THREAD

**Issue by kennetpostigo** [PrismJS/prism#1046]
Hey,

I wanted to reach out to see if you guys could add syntax highlighting for code written in [reason](http://facebook.github.io/reason). For highlighting and grammar support for reason in editors the reason team created [this](https://github.com/facebook/reason/blob/master/editorSupport/language-reason/grammars/reason.json).  Do you think it would be possible to add reason to the list of supported languages?

**Comment by Golmote** [comment]
Hi! Well, the JSON grammar you linked to could be helpful, but it definitely requires some work, since it appears to be far more specific than what Prism would require, and it also seems to use POSIX character classes that JavaScript doesn't support. I might give a try anytime soon, though.

**Comment by Golmote** [comment]
Support for Reason has been added.
I mostly based the component on the [documentation](http://facebook.github.io/reason). It looks quite partial, though... So I took the list of keywords directly from the [lexer](https://github.com/facebook/reason/blob/master/src/reason_lexer.mll) and added some stuff I found in the [test files](https://github.com/facebook/reason/tree/master/formatTest/unit_tests/expected_output).

Hopefully I did not miss too many features. If you encounter issues using it, feel free to open some issues so we can improve the support.
