### ISSUE TITLE
groovy language highlighter transforms &amp;lt; to &lt;

### ISSUE THREAD

**Issue by Rob--W** [PrismJS/prism#1049]
1. Visit http://prismjs.com/test.html.
2. Paste`"&lt;"`
3. Set language to Groovy.

Expected:

- Result: `"&lt;"`

Actual:

- Result: `"<"`

**Comment by Golmote** [comment]
I can't reproduce this issue on the Test page...

![https://puu.sh/sbplT/24b861700b.png](https://puu.sh/sbplT/24b861700b.png)

**Comment by Rob--W** [comment]
@Golmote You forgot to copy the quotes (those quotation marks in my steps-to-reproduce are required for the test case).

**Comment by Golmote** [comment]
Oh, sorry, I didn't realize they were part of the code block! Issue confirmed! ;)
