### ISSUE TITLE
Handlebar syntax highlighting modifies rendered result

### ISSUE THREAD

**Issue by Rob--W** [PrismJS/prism#1052]
Syntax highlighting is not supposed to change output. But with trivial examples I am able to hide the code in a handlebars template.

Try the following examples at http://prismjs.com/test.html with language = handlebars.

### Test case 1
Input (=expected output too):
```
{{}} <-- This is not a valid handlebar template
}} <-- Not special
```
Unexpected output:
```
___HANDLEBARS1___ <-- Not special
```

### Test case 2
Input (=expected output too):
```
<a>{{var}}</a>
```
Unexpected output:
```
<a>___HANDLEBARS1___</a>
```

**Comment by Golmote** [comment]
I can't reproduce this issue on the test page...

![https://puu.sh/sbuA2/da38ca8775.png](https://puu.sh/sbuA2/da38ca8775.png)

**Comment by Rob--W** [comment]
I refreshed the test page, repeated the above steps, and indeed: the issue no longer shows up.

**Comment by Golmote** [comment]
I remember the Handlebars component was broken not so long ago. I guess you had the broken file cached in your browser or something.
