### ISSUE TITLE
Can't use a language- and copy-to-clipboard plugins

### ISSUE THREAD

**Issue by craigharman** [PrismJS/prism#1056]
Enabling an extension language as a class such as language-php breaks the toolbar/copy functionality from working.

For example, this will show the copy button:
<pre class="line-numbers" data-src="/deployFiles/deploy/{{ $app_id }}/existing"><code></code></pre>

while this will not:

<pre class="line-numbers" data-src="/deployFiles/deploy/{{ $app_id }}/existing"><code class="language-php"></code></pre>

**Comment by mAAdhaTTah** [comment]
Are there supposed to be images? I don't see anything in those spaces.

**Comment by craigharman** [comment]
Apologies, not, images but code:

`<pre id="code-deploy-existing" class="line-numbers"><code></code></pre>`

this will not:

`<pre id="code-deploy-existing" class="line-numbers"><code class="language-php"></code></pre>`

The only difference being the language-php class. If you mouse over the prism code block using the first one you see the "copy" button. But with the second it doesn't show. All other code remains the same.

**Comment by Golmote** [comment]
Hi! I can't reproduce the issue. Could you provide an online example?

**Comment by Golmote** [comment]
Please reopen if you can provide on online example reproducing the issue.
