### ISSUE TITLE
The tag br isn't visible in PHP language and the empty is broken in numbers 1 and 10

### ISSUE THREAD

**Issue by gusbemacbe** [PrismJS/prism#1057]
Hello

I added the tag `br` inside PHP code in a code body and the tag isn't visible in the result and I jumped the tags pre and code, causing a line breaker in the numbers 1 and 10, then if there's no tags `br`:

![Code editor](https://cloud.githubusercontent.com/assets/2257024/20243472/98f40786-a93f-11e6-8432-6ccd48d24408.png)

![Result](https://cloud.githubusercontent.com/assets/2257024/20243474/a763a9e8-a93f-11e6-9976-e6621668baf9.png)

**Comment by Golmote** [comment]
You must encode the opening bracket as `&lt;`, i.e. `&lt;br>`.

**Comment by Golmote** [comment]
Regarding the empty lines, you might want to use the [Normalize Whitespace plugin](http://prismjs.com/plugins/normalize-whitespace/).

**Comment by gusbemacbe** [comment]
Thank you! It is fixed.
