### ISSUE TITLE
Prism not working with &lt;

### ISSUE THREAD

**Issue by runemadsen** [PrismJS/prism#1060]
I've been struggling with this for a few hours. When I run this:

```js
Prism.highlight("1 &lt; 2", Prism.languages.javascript)
```

I get this:

```html
<span class="token number" >1</span> <span class="token operator" >&amp;</span>lt<span class="token punctuation" >;</span> <span class="token number" >2</span>
```

The documentation says that I need to escape `<`, but it seems like Prism is not handling that input? Or am I doing something wrong?

**Comment by Golmote** [comment]
You need to escape it only when it appears inside HTML (e.g. inside a &lt;code> tag). When you call Prism directly from JS, you don't need to do any escaping. ;)

**Comment by runemadsen** [comment]
Ah cool, thanks for the quick reply. For the record, this string actually came from a DOM element like this:

```js
ar pres = document.getElementsByTagName('pre');
for(var i = 0; i < pres.length; i++) {
  pres[i].firstChild.innerHTML = Prism.highlight(pres[i].firstChild.innerHTML, Prism.languages.javascript)
}
```

So I changed `.innterHTML` to `.textContent` and that solved it. THX!
