### ISSUE TITLE
JSX spread operator breaks highlighting

### ISSUE THREAD

**Issue by markerikson** [PrismJS/prism#1061]
If the JSX spread operator is used inside a tag, highlighting breaks starting at that point.  Example code to be highlighted:

```js
class MyComponent extends Component
    render() {
        const {tabs, ...otherProps} = this.props;
        const {currentTab} = this.state;
        
        return (
            <TabBar
                {...otherProps}
                currentTab={currentTab}
                onTabClick={this.onTabClick}
                tabs={tabs}
            />
        )
    }
```

If `{...otherProps}` is there, the props after that are not highlighted.  If `{...otherProps}` is removed, they highlight correctly:

![prism-jsx-broken](https://cloud.githubusercontent.com/assets/1128784/20507946/38511d9e-b02c-11e6-8e05-3444ed1ba314.png)
![prism-jsx-correct](https://cloud.githubusercontent.com/assets/1128784/20507947/385b6d1c-b02c-11e6-865f-1b3ba490186b.png)

**Comment by gre** [comment]
:+1:

I was about to raise something similar for JSX and comments:

<img width="576" alt="screen shot 2016-11-22 at 09 27 09" src="https://cloud.githubusercontent.com/assets/211411/20516249/f2a6be74-b095-11e6-87a9-acf00855d6a0.png">

<img width="578" alt="screen shot 2016-11-22 at 09 26 47" src="https://cloud.githubusercontent.com/assets/211411/20516253/f6b99824-b095-11e6-8287-75a120225d82.png">

tell me if you prefer to create another issue, but there are multiple ways like this that breaks highlighting.

**Comment by Golmote** [comment]
@vkbansal: Can you investigate this?

**Comment by vkbansal** [comment]
@Golmote I'll try it over the weekend
