### ISSUE TITLE
Line Numbers Not Working

### ISSUE THREAD

**Issue by judia** [PrismJS/prism#1062]
I can't seem to get line numbers working. I'm working on a class project, and I have to get it working. I have the prism css and prism js linked up properly. (I'm building this on laravel.) Any idea why it's not working? 

Here is the working code: http://phplaravel-26135-59902-180621.cloudwaysapps.com/

**Comment by Golmote** [comment]
You need to add the class name `line-numbers` to your `<pre>` tag. http://prismjs.com/plugins/line-numbers/
