### ISSUE TITLE
My own theme doesn't show the scrollbars and has problem with media queries

### ISSUE THREAD

**Issue by gusbemacbe** [PrismJS/prism#1063]
Hello,

I'm developing a Dracula theme for Prism.js, but I have still three problems:
* The vertical scrollbars aren't shown or enabled when you use on your mobile phones or tablets.
* The `pre` width in media queries doesn't resize the `pre` or `code` body. 
* I have already set Prism Normalize Space in a `JavaScript` script, but it doesn't remove the indent and the space. 

Please, visit my Github pages , test and analyse the issues:
https://gusbemacbe.github.io/draucla-prism/

You can clone and merge if you want and want to contribute with me too:
https://github.com/gusbemacbe/draucla-prism

Thank you for your attention, help, patience and understanding!

Gustavo
From Brazil

**Comment by Golmote** [comment]
Hi! If you still need to report actual issues regarding Prism, please create a new issue describing a single problem at a time.

**Comment by gusbemacbe** [comment]
@Golmote 

I have fixed all the bugs yesterday after I saw somebody wanted to use my theme for Prism.js, now it is finished and it works and the theme is official on Dracula Themes.

**Comment by mAAdhaTTah** [comment]
Maybe PR it to [`prism-themes`](https://github.com/prismjs/prism-themes) ;)

**Comment by gusbemacbe** [comment]
@mAAdhaTTah, ready. Reference: https://github.com/PrismJS/prism-themes/issues/74.
