### ISSUE TITLE
Copy to Clipboard Plugin Unavailable via Bower

### ISSUE THREAD

**Issue by WhatIsHeDoing** [PrismJS/prism#1067]
The Copy to Clipboard [plugin](http://prismjs.com/plugins/copy-to-clipboard/) is currently unavailable via Bower, i.e. it is not included with other plugins.

**Comment by Golmote** [comment]
The Copy to Clipboard plugin was merged the 09/11/2016, but the next version of Prism (1.6.0) was only released the 03/12/2016. Considering the date of your comment, I'll assume this was the reason. Hopefully it is available via Bower now, as I can't see why it wouldn't.
