### ISSUE TITLE
Code annotations (remarks, comments, etc)

### ISSUE THREAD

**Issue by jsight** [PrismJS/prism#1068]
Would it be possible to add a feature to support annotating code. This would basically just create a block of arbitrary HTML within the code that could be used to add hints and remarks about the code itself.

Example:
http://imgur.com/a/IzPxc

**Comment by Golmote** [comment]
Hi! I think this could be achieved by inserting this content dynamically after highlighting. The [Keep Markup plugin](http://prismjs.com/plugins/keep-markup/) should help.
See http://codepen.io/anon/pen/VmQpYz for a quick attempt.

Note that this might not be super easy to combine with the Line Numbers plugin, though.

**Comment by LeaVerou** [comment]
Yup, the Keep Markup plugin does what you want!

**Comment by jsight** [comment]
Oh, wow, somehow I missed that it could do this. I'll try it out, thank you!
