### ISSUE TITLE
Version 1.6.0 is not published on NPM

### ISSUE THREAD

**Issue by SamyPesse** [PrismJS/prism#1069]
The latest version on NPM is [1.5.1](https://www.npmjs.com/package/prismjs).

**Comment by Golmote** [comment]
I asked @LeaVerou to publish it. She will surely be able to do it anytime soon.

**Comment by SamyPesse** [comment]
Thanks 🍻 

You can also setup NPM deployment with travis to automate this: https://docs.travis-ci.com/user/deployment/npm/

**Comment by Golmote** [comment]
Yup, we do have an open issue for that: #661

**Comment by LeaVerou** [comment]
I published manually, and tried to configure Travis to publish automatically from now on, but I doubt that will work…

**Comment by SamyPesse** [comment]
Thanks @LeaVerou 👍
