### ISSUE TITLE
JSPM failure due to missing package jspm:clipboard

### ISSUE THREAD

**Issue by patrickmichalina** [PrismJS/prism#1071]
Upgrading to version 1.6 fails when using JSPM.

```
err  Repo jspm:clipboard not found. Perhaps try jspm install npm:clipboard.
```

Current workaround is to not upgrade and sticking with `"prism": "github:PrismJS/prism@1.5.1"`

**Comment by mAAdhaTTah** [comment]
`clipboard` is an optional dependency for Prism, as it's only required if you use the copy-to-clipboard plugin. How does jspm handle optional deps?

**Comment by Golmote** [comment]
The reaction on the last comment in https://github.com/jspm/jspm-cli/issues/1441 makes me think this issue has been solved. I'm closing it. Feel free to reopen if I'm wrong.
