### ISSUE TITLE
JSX close tags look weird

### ISSUE THREAD

**Issue by jadekler** [PrismJS/prism#1073]
See the weird red highlighting on `>`:

![screen shot 2016-12-21 at 9 40 38 am](https://cloud.githubusercontent.com/assets/3584893/21399718/976ef994-c761-11e6-900f-7fb8cc1799d0.png)

**Comment by Golmote** [comment]
I could not reproduce the issue on the [Test drive page](http://prismjs.com/test.html). Can you provide an online example reproducing it?

![https://puu.sh/tcStG/b7fd63df04.png](https://puu.sh/tcStG/b7fd63df04.png)

**Comment by jadekler** [comment]
@Golmote Huh, weird. I'll see if I can provide you something

**Comment by Golmote** [comment]
Feel free to reopen if you can provide an actual example reproducing the issue ;)
