### ISSUE TITLE
Cannot see scrollbar in any situation !

### ISSUE THREAD

**Issue by ghost** [PrismJS/prism#1076]
Hi, when the code is a bit large I want to have scrollbar for it. but it does not appear in any situation.

this is a part of my source code :
![image](https://cloud.githubusercontent.com/assets/19874993/21656811/e0c866d8-d2d4-11e6-8fd1-aa5307eef140.png)

but in the browser I don't see scrollbar for source code.

**Comment by Golmote** [comment]
Hi! Can you provide an online example reproducing this issue, please?

**Comment by Golmote** [comment]
There's not much we can do to help without an online example reproducing this issue. I'm closing it.
