### ISSUE TITLE
Make PrimsJS return multiple lines front a given single line 

### ISSUE THREAD

**Issue by calebeaires** [PrismJS/prism#1081]
I implemented PrismJS on an Angular 2 app, but I was not able to make the code be more complexed organized. Is there some plugin that prettify the code like the example above (especially on SQL language)?

If I give to prismjs this single line code

```sql
select `title`, `author`, `year` from `books` group by `title`, `author` limit 10
```

PrismJS will print this

```sql
select `title`, `author`, `year` 
from `books` 
group by `title`, `author` 
limit 10
```

**Comment by Golmote** [comment]
Hi @calebeaires.
No, PrismJS has no formatting ability, and AFAIK this is not on the agenda.
