### ISSUE TITLE
Combine csharp and diff

### ISSUE THREAD

**Issue by vlellouche** [PrismJS/prism#1088]
Hi,
Is it possible to combine the language diff and csharp
In the block code i would like the style of csharp and if i have some line with + or - the same behavior if i use language-diff.
thanks you for your help

**Comment by Golmote** [comment]
Hi! I guess you could create your own hybrid component by extending the `diff` component with the `csharp` one. Something like this : http://codepen.io/anon/pen/zNPpdb

**Comment by vlellouche** [comment]
thanks you
