### ISSUE TITLE
Wrong highlighting in C# mode : 3 slashes within a string rendered as comment

### ISSUE THREAD

**Issue by sdkcarlos** [PrismJS/prism#1091]
Using the following code snippet and highlight mode C# (`language-csharp`):
```csharp
string HTML_FILEPATH = "C:/Users/sdkca/Desktop/example.html";

// and set it up using fluent notation too
configuration
.SetAllowLocalContent(true)
.SetPageUri(@"file:///" + HTML_FILEPATH);
```
Will produce the following result:

![bad_highlighting](https://cloud.githubusercontent.com/assets/11634719/22431358/8b464918-e711-11e6-8895-549548018502.png)

The 2 slashes are interpreted as a comment although it's within a string in the `SetPageUri` method. Neither using `.SetPageUri("file://////" + HTML_FILEPATH);` (without `@` and escaped slashes) seems to help.

It happens in the Test drive website too.

**Comment by Golmote** [comment]
Hi! Thanks for reporting. It should be fixed now.
