### ISSUE TITLE
Language names are not provided

### ISSUE THREAD

**Issue by byron-hawkins** [PrismJS/prism#1096]
For example, if I download the "C-like" language highlighter, nowhere on your website is it ever mentioned that the language name for this highlighter is "language-clike". It is not "language-C-like", nor "language-C", nor "language-c", nor "language-c-like", nor any other similar token. It must be PRECISELY "language-clike". Since it must be exact, and since it differs from what you printed on your website, you need to add a specification table that clearly indicates the EXACT spelling of the languages.

**Comment by Golmote** [comment]
All supported languages with their associated alias are listed on the [homepage](http://prismjs.com/#languages-list) of the website. Those aliases can also be found on the [Examples](http://prismjs.com/examples.html) page. Is it what you were looking for?
