### ISSUE TITLE
JSX attributes with spaces not handled properly

### ISSUE THREAD

**Issue by fatfisz** [PrismJS/prism#1103]
![image](https://cloud.githubusercontent.com/assets/6004414/22985187/fef05686-f3a7-11e6-9cbc-2b668e8df2a7.png)

As you can see, when the attribute contains a space the coloring gets a little weird. Here's the string I used:
```jsx
<Tab name="Only the first word" />
```

**Comment by Golmote** [comment]
Thanks for reporting. This should be fixed now, see 867ea42877cbdfb8b8d3645b1ccbf93308157d9f.
