### ISSUE TITLE
line_numbers. js doesn't work with white-space

### ISSUE THREAD

**Issue by windowsair** [PrismJS/prism#1109]
If the white - space attribute is added in the CSS, then when using line number statistics typesetting chaos problems will occur.
Hope you can solve the problem of the plugin, thank you.

**Comment by LeaVerou** [comment]
What value of `white-space` causes this? Could you define what "chaos" is? Even better, could you provide a testcase that reproduces the issue?

**Comment by windowsair** [comment]
> Chaos....  I mean there may be some problems with typography.

Like this:
![2017-03-14_230029](https://cloud.githubusercontent.com/assets/17078589/23906711/c54c0200-0909-11e7-907f-6485c777fb93.png)

You can clearly see the problems. When the `white-space` is removed, the normal situation is like this :
![2017-03-14_225528](https://cloud.githubusercontent.com/assets/17078589/23906840/2f1e3e82-090a-11e7-9e04-3c8fbee60ea9.png)

**Comment by windowsair** [comment]
By the way, this problem does not occur only if the value of `white-space` is **`pre`**. However, the effect here is equivalent to not add `white-space`. 
   
Look forward to your favourable reply.

**Comment by windowsair** [comment]
Uh..... The This picture may be more obvious ...
![2017-03-14_232209](https://cloud.githubusercontent.com/assets/17078589/23907674/db2c2f84-090c-11e7-8180-70debccb52a8.png)

**Comment by windowsair** [comment]
@LeaVerou Do you see it?:-)

**Comment by Golmote** [comment]
It this related to this issue? https://github.com/PrismJS/prism/issues/666

**Comment by windowsair** [comment]
@Golmote :smile:LGTM.That's what I want
