### ISSUE TITLE
Plugin Usage and exporting language grammars and plugins

### ISSUE THREAD

**Issue by kennetpostigo** [PrismJS/prism#1111]
I've been using prism for a little while and mixing it with react.  I made a code highlighting component and everything has been going smoothly for some time. Until I want to start adding plugins. I ran into an issue with `line-numbers` plugin where some lines of code would not receive a line number. 

![image](https://cloud.githubusercontent.com/assets/8888991/23878287/e59d2982-081c-11e7-9701-82d3b5486724.png)

I've tried to understand exactly why this happens but I came up empty. Heres the code for the component:

```js
import React, { PureComponent } from 'react';
import Prism from 'prismjs';

class Codehighlighter extends PureComponent {
  props: CodehighlighterProps;
  prismNode: any;

  componentDidMount() {
    this.hightlight();
  }

  componentDidUpdate() {
    this.hightlight();
  }

  hightlight() {
    Prism.highlightElement(this.prismNode, this.props.async);
    if (this.props.plugins) {
      this.props.plugins.map(plugin => plugin.func(Prism));
    }
  }

  render() {
    return (
      <pre
        className={
          `language-${this.props.language} 
          ${this.props.plugins ? this.props.plugins
                .map(plugin => plugin.title)
                .join(' ') : 'codehighlighter'}`
        }
        data-line={this.props.dataLine || ''}
        data-dependecies={this.props.dataDependecies || ''}
        data-user={this.props.dataUser || ''}
        data-host={this.props.dataHost || ''}
        data-prompt={this.props.dataPrompt || ''}
        data-output={this.props.dataOutput || ''}
      >
        <code
          ref={prismNode => this.prismNode = prismNode}
          className={`language-${this.props.language}`}
        >
          {this.props.children}
        </code>
      </pre>
    );
  }
}

// Here we use it:
import React, { PureComponent } from 'react';
import CodeHighlighter from './myModule';
import Prism from 'prismjs';
import 'prismjs/plugins/line-numbers/prism-line-numbers.css';
import './styles/CodeBlock.css';

(Prism.languages.reason = ... ), delete Prism.languages.reason.function;  // copy and past reason language grammer

function CodeBlock(props) {
  return (
    <Codehighlighter
      language="reason"
      plugins={[
        {
          title: 'line-numbers',
          func: lineNumbers
        }
      ]}
    >
      {props.literal}
    </Codehighlighter>
  );
}

function lineNumbers(Prism) {
 ... // Here I simply copy and paste the line-numbers plugin js code
}
```

The `Codehighlighter` component takes an array of plugin objects. These objects are have 2 fields a `title` and a `func`, where the `title` is placed as a class on the pre element and the `func` is passed the prism instance and is applied. Seems like standard stuff. I am not sure if I am doing something wrong here, if I am please point it out because I'm not too knowledgable about `prismjs` In the example above and in the project I'm using this in I'm using the reason language grammar and the line numbers function. 

I am consuming the `prismjs` library from `npm`, but I notice the library seems to be more geared towards the script tag workflow. It would be useful to expose the language grammars from the components folder and plugins from the plugins folder as modules because they are not being exported from the files they exist in, as in they are just iife and not being exposed as modules. It would make the workflow a lot nicer instead of copy and pasting code:
```js
import Prism, { languageReason, lineNumbers } from 'prismjs';
```
Where the language and line numbers are actually exported instead of just iife.

I would appreciate any help I can get 🙃

**Comment by windowsair** [comment]
You seem to forget to add a class called `line-numbers`. I'm not sure if you have the correct write. Of course, I may be wrong, please point out ....

**Comment by kennetpostigo** [comment]
@windowsair the `line-numbers` class name is being added onto the `pre` element, it is grabbed from the plugin object `title` field.

**Comment by windowsair** [comment]
Could you let me have a look at your web page code?

**Comment by kennetpostigo** [comment]
Do think we can chat on discord? Because the highlighter module is in one repo and the webpage in another repo. I can send you an invite to both if you would like.

**Comment by windowsair** [comment]
Can you give me a copy of the output page file (js, css, html)?

**Comment by Golmote** [comment]
This was apparently fixed in https://github.com/kennetpostigo/rdn/pull/10.
