### ISSUE TITLE
Wrong SQL comment highlighting

### ISSUE THREAD

**Issue by peterremec** [PrismJS/prism#1114]
There's a bug in highlighting SQL comment. If I use Prism on that code:

`-- AND k.field1 IS NOT NULL AND k.field2 IS NOT NULL `

it generates the following HTML:

`<span class="token comment" spellcheck="true">-- AND k.field1 IS NOT </span><span class="token boolean">NULL</span> <span class="token operator">AND</span> k<span class="token punctuation">.</span>field2 <span class="token operator">IS</span> <span class="token operator">NOT</span> <span class="token boolean">NULL</span>`

The second part of the comment is being highlighted as a regular SQL code (I believe that the whole comment should be greyed out). 

edit: I think that 'NULL' keyword in a comment makes the highlighting wrong, comments without 'NULL' keyword are fully colored in grey

**Comment by Golmote** [comment]
I can't reproduce your issue on the [Test page](http://prismjs.com/test.html).

![https://puu.sh/v2Kub/a60a3e04bc.png](https://puu.sh/v2Kub/a60a3e04bc.png)

Please reopen this issue if there is more to it.
