### ISSUE TITLE
How to install jsx

### ISSUE THREAD

**Issue by kopax** [PrismJS/prism#1116]
I have seen an example online that use `language-jsx` nicely. I have also found this PR #479.

However, I don't have any coloration for my jsx. Is jsx supposed to work out of the box?

__edit__

On the list on the site there is also `json`, but json work only with `js`

**Comment by abhisheksoni27** [comment]
Any news on this?

**Comment by Golmote** [comment]
Can you provide an example reproducing your issue, please. The JSX component is supposed to work just as properly as any other.

**Comment by kopax** [comment]
@Golmote could you try to display correctly using prism the following JSX code 

```jsx
import React from 'react';

import {
  Alert,
  Button,
} from 'bootstrap-styled';

export default class AlertDismissExample extends React.Component {

  state = {
    visible: true,
  };

  onDismiss = () => {
    this.setState({ visible: false });
  };

  render() {
    return (
      <div>
        <Alert color="info" isOpen={this.state.visible} toggle={this.onDismiss}>
          I am an alert and I can be dismissed!
        </Alert>
        <Button className="btn btn-primary" onClick={this.resetCloseAlert}>Reset alert</Button>
      <div>
    )
  }
}
```

When I am using the class `language-js` it can be displayed with color, but if I use `language-jsx`, it seems to be not working at all.

I have imported prism like in webpack 2 like this : 

    import '../node_modules/prismjs/themes/prism-okaidia.css';
    import Prism from 'prismjs';

**Comment by kopax** [comment]
Solved by importing : 

    import PrismJsx from 'prismjs/components/prism-jsx.min';

**Comment by jlmakes** [comment]
The source of `components/prism-jsx` shows an IIFE that's passed a global `Prism` variable; it simply extends that global variable—yet, this global variable doesn't exist during my gulp build process.

**Comment by JulienDemarque** [comment]
Is that a bug? It is seems other language option do not need to be imported this way?

**Comment by infoxicator** [comment]
According to the Docs the recommended way if using webpack is to use the babel-plugin https://github.com/mAAdhaTTah/babel-plugin-prismjs and configure .babelrc like this

 ```{
  "plugins": [
    ["prismjs", {
      "languages": ["javascript", "css", "html"],
      "plugins": ["line-numbers", "show-language"],
      "theme": "okaidia",
      "css": true
    }]
  ]
}
```

**Comment by iamsupercharged** [comment]
Hey!

Installing works perfectly but **none of the JSX is displayed, only the JS**.

Anybody else have that problem? I've installed the right languages on top of my .babelrc config.

Thank you! 

<img width="664" alt="Screenshot 2020-05-12 at 00 11 11" src="https://user-images.githubusercontent.com/56723055/81624194-21146500-93e5-11ea-9644-33a39ed739c9.png">

**Comment by iamsupercharged** [comment]
Found the solution if anyone's looking, I was dynamically setting the content inside of <code> through innerHtml which suppresses the tags:

`document.getElementById("codeContainer").innerHTML 
`
instead of

` document.getElementById("codeContainer").textContent`
