### ISSUE TITLE
Avoid using generic CSS classes

### ISSUE THREAD

**Issue by Xaviju** [PrismJS/prism#1119]
Using generic CSS classes like `tag` or `token` will easily conflict with internal CSS project classes. 
A good practice for this cases is to prepend the library classes with something like `prism-tag` or similar. It will avoid this kind of conflicts.

In the image below, the code in html looks like this because the CSS class tag was already widely used in the project and confilcts with prism generated `tag`class.

![captura de pantalla de 2017-03-24 12-49-34](https://cloud.githubusercontent.com/assets/1343702/24293169/c01b85ec-1090-11e7-9efc-15af1386d538.png)

If there is anything I can do to help, let me know. 

Thanks for the work, is awesome.

**Comment by LeaVerou** [comment]
Don’t we have a plugin that allows a custom prefix for classes @Golmote @zeitgeist87? Changing the default classes is impossible at this point for backwards compat. Even if it wasn't for backwards compat, one of the things people love about Prism is its sensible class names, and as long as there's a way to optionally add a prefix, I don't think we should change that.

**Comment by Golmote** [comment]
http://prismjs.com/plugins/custom-class/

**Comment by LeaVerou** [comment]
Excellent! Thanks @Golmote, closing.

**Comment by Xaviju** [comment]
Sorry, missed that. 
Thanks a lot for your help @Golmote @LeaVerou !
