### ISSUE TITLE
Color/opacity contrast (accessibility)

### ISSUE THREAD

**Issue by jina** [PrismJS/prism#1120]
We're using the Coy theme — I noticed that some things (like `.namespace`) have opacities lowered, which brings the text below the contrast ratio. Also noticed many of the other themes have contrast issues, too.

**Comment by Golmote** [comment]
Hi! Don't hesitate to override Prism's themes styles if they don't fit your requirements. Or provide a PR so that we can include this improvement in the project, if every maintainer agrees.
