### ISSUE TITLE
CSS @rule highlighting: Why do we need rest?!

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#1123]
I was looking at the CSS definition today and noticed [this](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-css.js#L22):

```js
Prism.languages.css['atrule'].inside.rest = Prism.util.clone(Prism.languages.css);
```

Why do we need that? From what I see in the atrule definition, it only matches the beginning part of the `@rule`, not the part inside the braces, which would be highlighted like normal CSS. See:

```js
'atrule': {
		pattern: /@[\w-]+?.*?(;|(?=\s*\{))/i,
```

cc @Golmote

**Comment by Golmote** [comment]
We need to highlight what's inside the parentheses: e.g. min-width: 960px, etc. Don't we?

**Comment by LeaVerou** [comment]
I think that's overkill, and these are technically not properties anyway. No strong opinion though…

**Comment by Golmote** [comment]
I think I remember there were issues with media queries highlighting at some point. We fixed it that way. Can't search commits history right now to confirm though.

**Comment by Golmote** [comment]
Well, back on my computer, I've found [the commit](https://github.com/PrismJS/prism/commit/e25408898e247646d26d23bc7b744d822d427c5b), but there is no mention of any PR or issue. So maybe this was just an issue I noticed on my own.

Nevertheless, any improvement you can think of are welcome, as always ;)
