### ISSUE TITLE
Performance issue in Chrome 56 ad 57

### ISSUE THREAD

**Issue by guruxu** [PrismJS/prism#1125]
We have recently discovered a severe performance issue when calling `Prism.highlightElement`. Massive amount of CPU is being spent on [this line](https://github.com/PrismJS/prism/blob/gh-pages/prism.js#L383). For a very small block of text, it's taking minutes to highlight, comparing to Chrome 55 and earlier or other major browsers taking a second or less. See attached Chrome profile comparison.

Can you shed some light on how to solve this problem? Thanks!

![chrome57](https://cloud.githubusercontent.com/assets/2684354/24735013/a9b269d4-1a4e-11e7-8f62-0bcbe773e07c.png)
![chrome55](https://cloud.githubusercontent.com/assets/2684354/24735014/b034e9f8-1a4e-11e7-952c-a5c9874798ab.png)

**Comment by Golmote** [comment]
Hi! Chrome releases are really fast: Chrome 58 is already out. Can you still reproduce the issue on that last version? I took a look at Prism's website using it and couldn't notice any obvious performance issue.

**Comment by gre** [comment]
I'm experiencing something somewhat similar on a **specific** code snippet (I have like 30 different code, but a specific snippet trigger the bug)
going to investigate a bit more the source of the problem but it's a regression to me (don't know if it's a regression of browser or libs)

<img width="955" alt="screen shot 2017-07-05 at 12 43 20" src="https://user-images.githubusercontent.com/211411/27861597-c2d6662a-6181-11e7-86bb-30e25704b0cb.png">

**Comment by Golmote** [comment]
Hi @gre! Can you please open a new issue with said code snippet so we can investigate?
