### ISSUE TITLE
"Keep Markup" plugin doesn't work with Autoloader

### ISSUE THREAD

**Issue by malaire** [PrismJS/prism#1127]
When "Keep Markup" plugin is used with Autoloader, markup is not kept.

Tested with downloaded minified version (Core, no languages, Autoloader, Keep Markup).

Two non-working examples:
```
<pre><code class='language-php'>
echo <mark>"Hello World!"</mark>;
</code></pre>

<pre><code class='language-markup'>
&lt;a <mark>href</mark>="...">
</code></pre>
```

**Comment by Golmote** [comment]
Thanks for reporting.
The Keep markup plugin should now handle those cases properly.
