### ISSUE TITLE
Using plugin at TinyMCE Cloud version

### ISSUE THREAD

**Issue by Carogato** [PrismJS/prism#1130]
Hello. 
It's any way to use this plugin at Cloud version? (without installation).

Thanks.

**Comment by Golmote** [comment]
Hi! I'm not exactly sure what you're trying to achieve. But released versions of Prism are available at [cdnjs](https://cdnjs.com/libraries/prism). Maybe you can use those files?

**Comment by Carogato** [comment]
Hello. 
TinyMCE has a no installable version: https://www.tinymce.com/docs/get-started-cloud/ 

Then, I use it in my web but I have no repositories.
External plugins works with this setup:
```
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  external_plugins: {
    'testing': 'http://www.testing.com/plugin.min.js',
    'maths': 'http://www.maths.com/plugin.min.js'
  }
});
```

Since Prism hasn't got this facilities, I'm unable to use it... Or there are any way?

Thanks.

**Comment by LeaVerou** [comment]
IIRC there's a syntax for init that lets you specify plugins by id and fetches their URL from the cloud.

**Comment by Carogato** [comment]
Thanks, LeaVerou, but I don't know how get this ID... sorry I'm lost :(

**Comment by Golmote** [comment]
There is already a plugin for tinyMCE using Prism. It's called [Code Sample](https://www.tinymce.com/docs/plugins/codesample/). I guess you just need to include it in the plugins list, as shown in the linked documentation. You'll need to add the Prism's scripts and stylesheets in you page, too. As I said earlier, you could grab those directly from CDNJS if you want.
