### ISSUE TITLE
Latest Prism JavaScript removes all my in-code markup.

### ISSUE THREAD

**Issue by garretwilson** [PrismJS/prism#1134]
I'm using the "coy" theme, all languages, and the following plugins:
* Line Numbers
* Keep Markup
* Command Line

The last version seems to have been from around 2016-11-24. I had certain code for a format I'm developing --- let's call it `"foobar"`. There is not yet a Prism language plugin for it. Still I'm preparing for the future, so I'm marking up all my code like this:

```html
<pre class="line-numbers"><code class="language-foobar">
  blah <mark>blah</mark> <em>blah</em>
```

Even though Prism doesn't understand the "foobar" language, I still get a nice coy theme and I get may highlights and emphasis.

Until today, 2017-05-07, when I decided to upgrade to the latest Prism CSS and JavaScript. Just because the latest is always better, right?

Luckily I looked at my site before I published it. My page loads and I can see the highlights and emphasis briefly, then Prism (it seems to be the JavaScript) removes it all in a flash, and I'm looking at a plain code segment. The other pages that have languages Prism recognizes (e.g. `html`, `java`) still show `<mark>` and such.

I'm having to revert to the earlier Prism.

Why is Prism now removing markup from my code, just because it doesn't recognize the language? What does one have to do with the other? If I said I want markup, I want markup; the language is irrelevant.

Must be a bug.

**Comment by LeaVerou** [comment]
Any chance you could make an online testcase for this? Thanks!

**Comment by Golmote** [comment]
Thanks for reporting. I was able to reproduce the issue. It should be fixed now.

**Comment by garretwilson** [comment]
Thank you.
