### ISSUE TITLE
Error downloading custom class plugin

### ISSUE THREAD

**Issue by garretwilson** [PrismJS/prism#1136]
I tried to download Prism with the "coy" theme, all languages, and the following plugins:

* Line Numbers
* Custom Class
* Keep Markup
* Command Line

The web pages displayed the following error:

> An error occurred while fetching the file "plugins/custom-class/prism-custom-class.css".

**Comment by LeaVerou** [comment]
That probably happens because the Custom Class plugin doesn't come with any CSS. Is there any actual issue?

**Comment by garretwilson** [comment]
I haven't tried it yet --- I assumed a big error message meant that there was an error. I didn't want to waste my time when the site clearly told me that something was wrong.

**Comment by LeaVerou** [comment]
Technically, the site told you nothing. It's not the site's fault you were peeking at the console. AFAIK there's actually no way to client-side check if a file exists without a 404 showing up in the console.
So, as long as there's no actual issue, I'm closing this. Feel free to reopen if there is!

**Comment by garretwilson** [comment]
Er, @LeaVerou, I'm not talking about the console. I'm talking about HTML message right there on the page.

Did you try to reproduce this?

**Comment by garretwilson** [comment]
![prism-issue-1136](https://cloud.githubusercontent.com/assets/627125/26022397/77efa880-3759-11e7-840e-6282369ba93f.png)

**Comment by garretwilson** [comment]
> Feel free to reopen if there is!

I don't seem to have permissions on this project to reopen this issue. But don't you agree that the message above sure looks like there was a real error, and that something went wrong?

**Comment by garretwilson** [comment]
> Technically, the site told you nothing.

Technically... I need to drink some tequila. It's been a long, frustrating day. But I'm going to bed and save the tequila for tomorrow. Good night.

**Comment by zeitgeist87** [comment]
It should be fixed with ba64f8dcfbb914f93d2ad9c94f64a790726d0ac9. The property `noCSS: true` was missing for the Custom Class plugin in `components.js`. By default the downloader assumes, that there is a CSS file.

**Comment by LeaVerou** [comment]
Yeah, sorry for the misunderstanding, this does look like a bug. Probably a bug with the site though, not with your bundle, so still try downloading, I bet there won't be any issue.

**Comment by garretwilson** [comment]
Thanks @zeitgeist87 and @LeaVerou; it seems I was able download the custom class plugin.

But the plugin seems completely broken; see #1137.

Please, could someone go to https://github.com/PrismJS/prism/issues/1055#issuecomment-301209192 and tell me why I have to go through this whole rigmarole in the first place? Why can't Prism simply prefix all its classes with something (anything!) by default, to avoid intercepting my own classes?
