### ISSUE TITLE
html code in python code

### ISSUE THREAD

**Issue by bojone** [PrismJS/prism#1138]
for example, the following code
`<pre class="line-numbers"><code class="language-python">re.findall('<a>.*?</a>', page)</code></pre>`
can not be show normally because there is some HTML code in python code.
How can I solve this problem?

**Comment by uranusjr** [comment]
#259 #373 #572 #984

**Comment by Golmote** [comment]
Thanks @uranusjr for digging out those issues ;)

@bojone The solutions explained in those will fix your current problem. You might also wanna check the [Unescaped markup plugin](http://prismjs.com/plugins/unescaped-markup/).
