### ISSUE TITLE
Doesn't highlight URLs with certain hash fragments correctly

### ISSUE THREAD

**Issue by prtksxna** [PrismJS/prism#1142]
If the following code is higlighted:

```javascript
// See documentation at: 
// https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.ButtonWidget
new OO.ui.ButtonWidget( {
	"label": "Normal"
} )
```

The URL in the second line is only highlighted (and turned into a link) till the `#` that is - ` https://doc.wikimedia.org/oojs-ui/master/js/#` which takes the user to the wrong place.

### Workaround

prism-autolinker supports Markdown syntax, so we can work around it like this:

```javascript
url = 'https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.ButtonWidget';
out = '// See documentation at: \n// [' + url + '](' + url + ')\n' + out;
```

### Details

This was discovered while creating the following patch - https://gerrit.wikimedia.org/r/#/c/356398

**Comment by Golmote** [comment]
Thanks for reporting! It should be fixed now.

**Comment by prtksxna** [comment]
Thanks @Golmote :)
