### ISSUE TITLE
Using prism.js in SharePoint works only when hard refreshing

### ISSUE THREAD

**Issue by Lcjng** [PrismJS/prism#1148]
Hello Community,
I want to use prism.js as the code highlighter in the SharePoint environment of my company, but unfortunately, it doesnt seem to work. The css gets applied, but the Javascript file seems to only load when hard refreshing the site with Ctrl+F5. I've tested this in all major browsers. Features like line numbers, color highlighting (together with all the token-classes) and the copy button are only there when hard refreshing. And even then not 100% of the time.
I've gone so far to load the file inside the aspx-Page and not with content editors (people who use sharepoint will know, what I mean by that) but that didn't work either.

Does somebody have an idea what could cause this? Other JavaScript files work.

Regards,
Luca

**Comment by LeaVerou** [comment]
If you type `Prism` in the console and press enter, what do you get?
That will help distinguish Prism not actually loading vs Prism loading but not running.

**Comment by Lcjng** [comment]
@LeaVerou There are no Error Messages in the "Console"-Tab of the Developer Tools in Chrome, but the js and css files are listed in the "Sources."-Tab So I assume it gets loaded, but just doesnt run properly?

**Comment by Lcjng** [comment]
I solved it.
For everyone that has the same issue:
It was because I created the necessary <pre>'s and <code>'s inside a jquery $.each function, which doesnt seem to work.
Create them in another function

**Comment by LeaVerou** [comment]
I don't think that was the problem. Perhaps you were adding them to the page after Prism had run, in which case calling `Prism.highlightAll()` manually should solve it.
