### ISSUE TITLE
Bug with JSON extension

### ISSUE THREAD

**Issue by stephenkeable** [PrismJS/prism#1150]
Hi @CupOfTea696,
Firstly thanks for creating a JSON extension, we have been using it on our dev docs site for a while now. 

However we recently came across an odd bug where the snippet below caused the browser window to crash.

Despite the JSON contained within the code block is valid.

Page we were using it on for context - https://developers.alliescomputing.com/postcoder-web-api/webhooks

```
<pre><code class="language-json">[
    {
        "message": {
            "type_id": "1",
            "type_name": "Security",
            "event_id": 3,
            "subject": "PostCoder Web - IP Address restricted by the public access security setting",
            "message": "Account:  Allies Computing\r\n\r\n\r\nHello,\r\n\r\nAn IP address using your service via the public access security settings has been restricted by the '5 lookup in a 5 minute period' setting,  12 times today.\r\n\r\nThe IP address is:  12.34.56.78\r\n\r\nIf this IP is known to you and should be granted unrestricted access to your service, it should be associated with your account.\r\n\r\nReview and edit your settings at https:\/\/admin.postcoder.com\/web\/security\r\n\r\nView all account errors at https:\/\/admin.postcoder.com\/user\/stats\r\n\r\nIf you have any questions, please let us know.\r\n           \r\nThe Allies Team\r\n\r\n\r\nFor help and support:\r\n\r\n01508 494488\r\nsupport@alliescomputing.com\r\nhttp:\/\/www.alliescomputing.com\/support\r\n",
            "priority": 3
        }
    }
]         
</code></pre>
```

**Comment by CupOfTea696** [comment]
I did this ages ago and haven't really actively contributed on Prism since. But maybe I can help out.

You say your browser crashes? Have you tried using a different browser and checking if the console shows any error messages?

**Comment by stephenkeable-allies** [comment]
Chrome would sit stuck for a while, then eventually declare the tab has crashed and ask if you want to kill it. Without any messages in console.

However awkwardly, when I tried switching the highlighting back on to get a screen recording, the problem has resolved itself, we had made a couple of changes to some invalid HTML elsewhere on our template. So that might have been the real cause.

Feel free to close this issue and thanks for the response @CupOfTea696

**Comment by CupOfTea696** [comment]
From the looks of it, seems like it got in an infinite loop somewhere. The invalid HTML might've indeed been the culprit.

**Comment by stephenkeable-allies** [comment]
The odd thing was the invalid tags we fixed, existed on all other pages of the site as in header and footer.
Not that it matters now as can't seem to reproduce, if it comes up again will let you know.
Thanks

**Comment by Golmote** [comment]
Please let us know if you happen to reproduce it again ;)
