### ISSUE TITLE
PrismJS doesn't highlight with VueJS

### ISSUE THREAD

**Issue by Sjoerrdd** [PrismJS/prism#1153]
Hi, prism does not work when the content is loading async. (As with VueJS)
``` 
<pre id="editor">
  <code class="language-css">{{ paste.content }}</code>
</pre>

```

**Comment by LeaVerou** [comment]
You can use the API! http://prismjs.com/extending.html#api

**Comment by Sjoerrdd** [comment]
That doesn't work :/
(https://gyazo.com/b56294adf1375aed6156ee056da3ad21)

**Comment by haryratsimba** [comment]
Hello, 

someone had a similar [issue](https://forum-archive.vuejs.org/topic/3514/getting-highlightjs-to-work-with-vue-router/6), using highlightjs which does a similar job as Prism.

I don't know if it's your case, but I guess you are updating your model (paste.content) from your Vue / Component instance and you expect the DOM to be updated and highlighted in the same time.

The problem is that Prism will take your model value (raw string), then apply a lot of HTML transformations. Then VueJS is not able to update the DOM. This is well described in the link I mentionned above : 

> Either it's real HTML DOM elements, and Vue handles them (then {{content}} works),
or it's supposed to be highlighted HTML markup, and highlightjs handles them underlying DOM elements that it needs to print it's highlighted text (then {{content}} won't work because highlightJS controls that DOM, not Vue).

One possible dirty solution is to update manually the DOM : 

- When your model changes, replace your code element content with your model value
- Highlight your element on VueJS next tick

An exemple of code is : 

```
watch: {
  paste.content: function(value) {
    let editor = document.querySelector('#editor code');
    editor.innerHTML = value;
    this.$nextTick(()=> Prism.highlightElement(editor));
  }
}
```

Hope it will help you

**Comment by Sjoerrdd** [comment]
It doesn't work for me, the [dot] between paste and content (paste.content) is unexpected.

**Comment by haryratsimba** [comment]
Sorry, I bring some corrections. Please check the previous edited answer.

**Comment by Sjoerrdd** [comment]
@haryratsimba thank You so much! It works :)

**Comment by LeaVerou** [comment]
I wonder if something like [this](https://github.com/PrismJS/prism/issues/1115) would help, but where the mutation observer tracks the content of the `<code>` elements, not just new ones. Then every time Vue updates the `<code>` element, Prism automatically highlights it.

**Comment by morissette** [comment]
Solved using updated property on component:
```javascript
  var Post = {
    data: function() {
      var postData = {
        post: ''
      };   
      var articleTitle = this.$route.path.replace('/', '');
      fetch(getPostUrl + articleTitle, {method: "GET", cache: "default"}).then(
        function(response) { 
          if (!response.ok) {
            console.log("bad response from server");
          }                  
          return response.json()
        }).then(
          function(responseData) {
            postData.post = responseData;
        }).catch(function(err) {
          console.log(err);
        });
      return postData
    },     
    template: `
      <div class="uk-card uk-card-body uk-card-default">
        <article class="uk-article">
          <h1 class="uk-article-title uk-text-center uk-text-uppercase">{{post.title}}</h1>
          <p class="uk-article-metadata uk-text-center" v-show="post.author">Written by {{post.author}} on {{post.timestamp}}</p>
          <hr class="uk-divider-icon" v-show="post.author">
          <p v-html="post.content"></p>
          <div class="uk-text-center">
            <div uk-spinner="ratio: 5" v-show="!post.author"></div>
          </div>
        </article>
      </div>
    `,     
    updated: function() {
      Prism.highlightAll();
    }      
  };  
```

**Comment by ShoorDay** [comment]
@morissette I had the same problem. Do you know why it is ok to use updated property, but watch property isn't?

**Comment by akhmadsyarif04** [comment]
> Solved using updated property on component:
> 
> ```js
>   var Post = {
>     data: function() {
>       var postData = {
>         post: ''
>       };   
>       var articleTitle = this.$route.path.replace('/', '');
>       fetch(getPostUrl + articleTitle, {method: "GET", cache: "default"}).then(
>         function(response) { 
>           if (!response.ok) {
>             console.log("bad response from server");
>           }                  
>           return response.json()
>         }).then(
>           function(responseData) {
>             postData.post = responseData;
>         }).catch(function(err) {
>           console.log(err);
>         });
>       return postData
>     },     
>     template: `
>       <div class="uk-card uk-card-body uk-card-default">
>         <article class="uk-article">
>           <h1 class="uk-article-title uk-text-center uk-text-uppercase">{{post.title}}</h1>
>           <p class="uk-article-metadata uk-text-center" v-show="post.author">Written by {{post.author}} on {{post.timestamp}}</p>
>           <hr class="uk-divider-icon" v-show="post.author">
>           <p v-html="post.content"></p>
>           <div class="uk-text-center">
>             <div uk-spinner="ratio: 5" v-show="!post.author"></div>
>           </div>
>         </article>
>       </div>
>     `,     
>     updated: function() {
>       Prism.highlightAll();
>     }      
>   };  
> ```

thank mr.
i try like this : 
 
```javascript
import prism from "prismjs/prism";

computed: {
    highlightedCode() {
      return this.dataArtikel;
    },
  },
  updated: function () {
    prism.highlightAll();
  },
```


and my template : 
```html
<span v-html="highlightedCode"> </span>
```

sucsess, highlight code in v-html..

**Comment by istomyang** [comment]
Sorry I don't read PrismJS src, but I have some experience.

I think `{{content}}` is damaged when PrismJS handle this line code, which causes vue can't update data.
~~~html
<pre><code>{{content}}</code></pre>
~~~
This is a solution, Vuejs can get `<code>` all along:

~~~html
<pre><code class="language-html" v-text="content"></code></pre>
~~~
~~~javascript
export default {
  computed: {
    content() {
      // this is async or mutable
      return `<script>console.log('Hey!')<\/script>`
    },
  },
  updated() {
    // first rendering doesn't need it.
    Prism.highlightAll()
  },
}
~~~
