### ISSUE TITLE
Syntax Highlight Errors With Glob Patterns for JavaScript

### ISSUE THREAD

**Issue by grayghostvisuals** [PrismJS/prism#1155]
JavaScript syntax halted when it encounters the following glob pattern.

![screenshot 2017-07-06 21 56 33](https://user-images.githubusercontent.com/934322/27939976-fd603f5e-6295-11e7-8640-483d0ac7b69a.png)

**Comment by LeaVerou** [comment]
@grayghostvisuals are you using a recent version of Prism? @Golmote @zeitgeist87 Didn't one of you push a fix for this ages ago?

**Comment by grayghostvisuals** [comment]
It's hard for me to tell which version is in use because it's a custom download and the version number is not in the output.

**Comment by Golmote** [comment]
@LeaVerou Indeed, I can't reproduce the issue on the [Test page](http://prismjs.com/test.html). @grayghostvisuals, can you try updating your version of Prism? http://prismjs.com/download.html

**Comment by LeaVerou** [comment]
Could you try redownloading to see if the bug is fixed? You can find a link at the top of your source file that will maintain all parameters.

**Comment by grayghostvisuals** [comment]
Ok great. Thanks for the quick attention. All good. 🏖
