### ISSUE TITLE
Snippet crashes browser

### ISSUE THREAD

**Issue by GutzC** [PrismJS/prism#1159]
Haven't been able to narrow down the exact segment of code that is causing the browser to crash, but when attempting to paste the attached snippet into the prism test page as **Javascript**, it causes the page to become unresponsive and have to manually force quit the tab.

[broken_snippet.txt](https://github.com/PrismJS/prism/files/1137110/broken_snippet.txt)

**Comment by Golmote** [comment]
Hi! Thanks for reporting. I tracked the performance issue down to the `/` char in the string `"Mismatched closing tag (expected </"`. Prism was checking for a regexp starting from this point and had a really hard time backtracking. It should be fixed now.
