### ISSUE TITLE
cURL language

### ISSUE THREAD

**Issue by Viiruus** [PrismJS/prism#1160]
Hello :-)

Is there a way to highlight cURL language?

Thanks!

**Comment by Golmote** [comment]
Could you give an example of what you mean by "cURL language" ? AFAIK it's not a language...

**Comment by Viiruus** [comment]
Hello @Golmote :-) thanks for your quick answer!
I would like to highlight cURL request like Stripe does [here](https://stripe.com/docs/charges).

**Comment by Golmote** [comment]
I see. The closest we have would probably be the Bash component. But I'm afraid it won't do such a great job. :/

**Comment by Viiruus** [comment]
Yes, I was testing with the bash language and you're right, it doesn't seem to be good enough.
Look at my screenshot.
<img width="683" alt="capture d ecran 2017-07-11 13 10 44" src="https://user-images.githubusercontent.com/6850261/28065779-765e6eba-663a-11e7-9d68-f4953ed0d548.png">

**Comment by Golmote** [comment]
Well, actually I expected something worse. The easy thing we can do to improve highlighting is to add the `curl` keyword to the list of common bash functions.

**Comment by Golmote** [comment]
As previously stated, I've added `curl` to the list of common functions in the Bash component.

If you really want to highlight cURL the way Stripe does it, you can still take a look at their custom language definition: https://stripe.com/assets/compiled/js/sprockets-js-documentation-c4b3ec3ed7e62075f018.min.js.

```js
// Prism curl
Prism.languages.curl = {
  'curl': /\bcurl\b/,
  'url': /https?:[a-zA-Z0-9:.?=\/\-_{}]*/,
  'parameter': {
    pattern: /[A-Za-z0-9\[\]-_]+ *(?=[=])/,
  },
  'value': [{
    pattern: /([=])([A-Za-z0-9-_.]*)/,
    lookbehind: true,
  }, {
    pattern: /(["'])(\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/,
  }, {
    pattern: /(\-u )([A-Za-z0-9-_.{}]*)/,
    lookbehind: true,
  }],
  'option': / *-[a-zA-Z]*\b/,
};
```

**Comment by Viiruus** [comment]
@Golmote I took a look at my previous code and I found a solution for the Bash language:
I added this part of code to the prism.js library:

```
Prism.languages.insertBefore("bash", "operator", {
  "api-key": {
    pattern: /(?:-u )([a-zA-Z0-9_]+)/g,
    inside: {
      "request-flag": /(^-u)/g
    }
  },
  "request-param": {
    pattern: /(?:-d )([a-zA-Z0-9]+)/g,
    inside: {
      "request-flag": /(^-d)/g
    }
  },
  "request-value": {
    pattern: /(?:=)(.*?)(?:\n|\\)/g,
    inside: {
      operator: /(^=)|(\\$)/g
    }
  }
})

Prism.languages.insertBefore("bash", "number", {
  "request-url": {
    pattern: /(?:^curl )(.*?)(?:\n|\\)/g,
    inside: {
      operator: /(\\$)/g,
      keyword: /(^curl)/g
    }
  }
});
```

Hope it will help someone 😄

**Comment by chakrihacker** [comment]
Why not add this to PrismJS this would be an amazing PR

**Comment by mAAdhaTTah** [comment]
@chakrihacker If you're interested in opening a PR, we're always open to new language additions.

**Comment by mmoulder** [comment]
This would be awesome to add cURL syntax highlighting. Almost every REST API has cURL examples, it would solve so many issues.
