### ISSUE TITLE
Selectively include copy-to-clipboard

### ISSUE THREAD

**Issue by ibrahimBeladi** [PrismJS/prism#1161]
Hi there,
I would like to ask whether it is possible to have or not have copy-to-clipboard in different snippets.
Is there a way to specify that a given snippet will include a copy-to-clipboard (like a whole code) and another that wont (like the output for example).

Regards

**Comment by mAAdhaTTah** [comment]
Right now, no. How would you like to specify that? I could look into that.

**Comment by ibrahimBeladi** [comment]
`<pre><code class="language-java no-copy"> ... </code></pre>` , where the default is to include copy-to-clipboard
OR
`<pre><code class="language-java copy-to-clipboard"> ... </code></pre>` , where the default is to exclude copy-to-clipboard

Both are equally good, feel free to work out on any of the two

**Comment by ibrahimBeladi** [comment]
I did this small hack on my website 

.no-copy div{
    visibility: hidden;
}

<pre class="no-copy">....
