### ISSUE TITLE
Download does not work on public site.

### ISSUE THREAD

**Issue by rbiggs** [PrismJS/prism#1165]
Sorry, I now this is unrelated, but this issue is regarding your public site: http://prismjs.com/download.html. The download page does not work on Safari 10. Clicking on the download links do nothing, or occasionally I'll get an empty file with no mime type or file extension.

**Comment by Golmote** [comment]
What is your exact Safari version, please?

**Comment by rbiggs** [comment]
Version 10.1.1 (12603.2.4)
