### ISSUE TITLE
Single quotes(') are translated into double quotes(")

### ISSUE THREAD

**Issue by ruanjiayou** [PrismJS/prism#1166]
my input's value need to be translated into json, like this  value='{ "pages": 20, "items": 199}'.
but prism translated the single into double , and the input wasn't rendered.

**Comment by Golmote** [comment]
Hi. Please provide on online example reproducing your issue.

**Comment by Golmote** [comment]
There's not much we can do to help without an online example reproducing this issue. I'm closing it.
