### ISSUE TITLE
Background color for operators is slightly off

### ISSUE THREAD

**Issue by mit-mit** [PrismJS/prism#1167]
For some reason the background color used on operators is different from any other highlighted element. This may be observed on the samples you have on the front page of http://prismjs.com/:

1. ![screen shot 2017-07-21 at 10 26 18](https://user-images.githubusercontent.com/13644170/28455552-b97f7316-6dff-11e7-9247-06f88ace8ae7.png)

1. ![screen shot 2017-07-21 at 10 28 15](https://user-images.githubusercontent.com/13644170/28455501-8d989b88-6dff-11e7-98c7-7d8f6f76ab7b.png)

Is this intentional? I personally think it makes the code harder to read.

**Comment by LeaVerou** [comment]
It is intentional, but you can easily override it with CSS and set `background: none` :)

**Comment by mit-mit** [comment]
OK, thanks!
