### ISSUE TITLE
Using prism within React's dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by florinpop17** [PrismJS/prism#1170]
Is there a way I can highlight the code which is set in React's dangerouslySetInnerHTML?
For some reasons it seems that Prism doesn't see that code. Any advices?

**Comment by Golmote** [comment]
@florinpop17 Can you provide on online example reproducing your issue?

**Comment by oleksii-udovychenko** [comment]
@florinpop17 It worked nicely for me. Make sure you have <pre> and <code> tags rendered with correct classes.

**Comment by Golmote** [comment]
There's not much we can do without an online example, so I'm closing this issue.
