### ISSUE TITLE
Async syntax highlighting in Worker thread will be failed

### ISSUE THREAD

**Issue by falsandtru** [PrismJS/prism#1172]
Could you fix this bug probably the same of #1059 ?

I fixed with this commit: https://github.com/falsandtru/securemark/commit/165b74d90a88169900237a0bf95f5cd9ae05e6e1

---

repro in old version:

1. run `$ npm i && gulp view`
2. Open http://127.0.0.1:4000/securemark/
3. Syntax highlight is succeeded.
4. Remove a trailing backquote as follows.

````
```haskell main.hs
main = putStrLn $ show $ primes !! 5

primes = filterPrime [2..] where
  filterPrime (p:xs) = p : filterPrime [x | x <- xs, x `mod` p /= 0]
`` 
````

5. Fix a trailing backquote.

````
```haskell main.hs
main = putStrLn $ show $ primes !! 5

primes = filterPrime [2..] where
  filterPrime (p:xs) = p : filterPrime [x | x <- xs, x `mod` p /= 0]
```
````

6. That reprocessing will be failed with the following error.

```
prism.js:265 Uncaught TypeError: Cannot read property 'rest' of undefined
    at Object.tokenize (prism.js:265)
    at Object.highlight (prism.js:256)
    at prism.js:476
```

note:
Syntax highlight command is called here: https://github.com/falsandtru/securemark/blob/v0.26.1/src/renderer/render/code.ts#L3

**Comment by Golmote** [comment]
I just merged #1188, fixing #1059. Let use know if you're still encoutering issues.
