### ISSUE TITLE
Creating own language highlighting

### ISSUE THREAD

**Issue by eisbehr-** [PrismJS/prism#1182]
I've created a highlighting for `arduino` language. But I have problems with the operators, like `=`, `&&`, `!` `==` and so on. I don't know how to do this correctly and I found no documentation for creating new languages. I hope I did it right so far.

[I've created an working example recreating my problems.](https://jsfiddle.net/3zthkh5x/)

Later on, is there a way to add this language to the repository, or is this not wished?

**Comment by Golmote** [comment]
Hi! Could you be more specific about the issue you have with the operators?

You can find documentation on language creation on [this page](http://prismjs.com/extending.html).

Regarding the addition of this to the official repo, I'm not sure "Arduino" can be considered as a language. If I understand correctly, this is just C++.

That being said, I think it's great that you're creating your own language extension to have it highlighted as you want it to be.

**Comment by eisbehr-** [comment]
Hello @Golmote 

Basically you're right, it's `c++` (_thats why I'm extending `c++` in my example_), but with other function, keyswords and constants. As you see in my example. Not a decent language, but used very often. If this not suit your needs, I'm fine with it. But other tools like `highlight.js` [supporting it already](https://github.com/isagalaev/highlight.js/blob/master/src/languages/arduino.js).

But back to the problem: if you take a look into my example, you see in the result on the very top, that things like `=` are highlighted with a background color. I don't know why this happens and how I could change this.

**Comment by eisbehr-** [comment]
I made you [a shorter example](https://jsfiddle.net/3zthkh5x/1/), where you should easily see the problem.

**Comment by Golmote** [comment]
That's because you're loading two themes at the same time. Remove `prism.css` ;)

**Comment by eisbehr-** [comment]
Ha. Great. 👍 Typically user problem. 😉 
Thanks for the hint!

So you don't want a PR/to add this to prism, correct? Then I'm hosting it by myself.

**Comment by Golmote** [comment]
@LeaVerou Do you have an opinion on this? Should we add support for this Arduino specific C++?

**Comment by LeaVerou** [comment]
@Golmote it could inherit from C++ and just redefine the parts that are different.

**Comment by Golmote** [comment]
@LeaVerou Yes it's already what it does. I'll take that as a yes. ^^
@eisbehr- Feel free to submit a PR, then!

**Comment by eisbehr-** [comment]
Will do! 😉

**Comment by eisbehr-** [comment]
Done. https://github.com/PrismJS/prism/pull/1184
