### ISSUE TITLE
Highlighting for Property Initializer Syntax (Stage-2)?

### ISSUE THREAD

**Issue by wle8300** [PrismJS/prism#1185]
Hi is there styling available for Property Syntax Initializers? These are class methods defined with an arrow function.

This is stage-2 ECMAScript feature.

We're trying to use it here: https://alligator.io/react/new-way-to-handle-events/
![Screenshot](https://i.imgur.com/Kxpym7W.png)

This is the Babel plugin for this feature: https://babeljs.io/docs/plugins/transform-class-properties/

**Comment by Golmote** [comment]
@wle8300 The updated highlighting for functions should match those two properties.
