### ISSUE TITLE
PHP not  highlighting on page load [bug]

### ISSUE THREAD

**Issue by cferdinandi** [PrismJS/prism#1191]
It looks like there might be a timing issue happening in with PHP in Prism. 

If you [visit this page](https://gomakethings.com/how-i-improved-the-speed-of-my-wordpress-site-by-500/), you'll notice the PHP code is not highlighted. If you run `Prism.highlightAll();` in the Developer Tools Console after the page loads, however, it highlights.

Any idea what might be causing that? Things are working as expected for other languages like JavaScript ([example](https://gomakethings.com/a-vanilla-javascript-clock/))

**Comment by agcolom** [comment]
@cferdinandi The PHP code is highlighted for me when I visit your page. I'm on Mac OS X 10.11.6 Chrome 61, Safari 9.1.2 or Firefox 55.0.3

**Comment by cferdinandi** [comment]
Well this is odd/embarassing. They work for me when I visit in incognito mode, or in a browser I don't typically use. Must be a Chrome caching issue. Apologies. Closing this one out.

Thanks for checking @agcolom!

**Comment by agcolom** [comment]
@cferdinandi You're welcome :-)
