### ISSUE TITLE
Prism only highlights first code segment on web page in Chrome on Android when including copy to clipboard plugin

### ISSUE THREAD

**Issue by aeoril** [PrismJS/prism#1196]
I found this out through trial and error.  If I download PrismJS with the copy to clipboard plugin enabled, it only highlights the first section of code on a page with multiple different sections of code on it.  But it only fails in Chrome for Android.

It works on Firefox for Android and if I remember correctly even the Android native browser, and it works on Firefox, Edge and Chrome on a Windows desktop machine.

This failed on three different android devices - 2 identical tablets and a phone.

I did lots of troubleshooting via trial and error, and finally found that when I did not use that plugin, it worked fine.

**Comment by mAAdhaTTah** [comment]
I'm not sure I follow. It should only copy the current snippet, not all snippets on a page.

**Comment by Golmote** [comment]
@aeoril Do you have an example page online reproducing the issue?

**Comment by aeoril** [comment]
@Golmote Yes:

https://aeoril.github.io/2017-08-19-center-animated-css-3D-cube-in-page-test.html

Github:

https://github.com/aeoril/aeoril.github.io/blob/master/2017-08-19-center-animated-css-3D-cube-in-page-test.html

I am using the Coy theme with it.

**Comment by aeoril** [comment]
@mAAdhaTTah It is not the copy to clipboard functionality that is in question.  The syntax highlighting on the web page itself is the problem.  When I include that plugin, on Chrome on Android and only on Chrome on Android (of the ones I can try), the first code snippet is highlighted on my web page but the others are not.

**Comment by aeoril** [comment]
@mAAdhaTTah @Golmote here is a screenshot:

![image](https://user-images.githubusercontent.com/1267648/30942048-246130a0-a3ae-11e7-9973-3584411875ef.png)

**Comment by mAAdhaTTah** [comment]
I'm able to reproduce this on my phone now. And you're saying this highlights both correctly when not using copy-to-clipboard?

**Comment by mAAdhaTTah** [comment]
Also, what version of Chrome Mobile are you using (Settings -> About Chrome)?

**Comment by mAAdhaTTah** [comment]
Just to eliminate any relationship to #1181, can you add this script tag right before the `prism.js`:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.8/clipboard.min.js"></script>
```

**Comment by aeoril** [comment]
Chrome version 61.0.3163.98 on my phone.

Yes, it works fine when I do not download the copy-to-clipboard plugin from the download page, but that also downloads the toolbar plugin automatically, and I deselected both in my testing to make it work.

Just to be sure, you *are* able to reproduce this problem on your phone?

I will try to get to further testing as you suggest above when I have time, but if you want to alter the code and test it yourself, everything is on my github repo:

https://github.com/aeoril/aeoril.github.io

**Comment by Golmote** [comment]
@aeoril The example page you provided does not work properly in Chrome desktop either.
@mAAdhaTTah I'm pretty sure it's the same error as #1181

**Comment by dutchenkoOleg** [comment]
@mAAdhaTTah thx, That helped

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.8/clipboard.min.js"></script>
```

![alt text](https://image.prntscr.com/image/HLhzf7d4TfeMtzHbng_3jA.png "error screenshot")

**Comment by aeoril** [comment]
@Golmote @mAAdhaTTah It works fine for me on Chrome for Desktop.  What OS are you using for Chrome for Desktop?  What version of Chrome for Desktop?

I can use the copy buttons fine, without any console errors in the dev tools.  Here is a screenshot of Chrome Desktop (Version 60.0.3112.113 (Official Build) (64-bit)) with that page up after a hard refresh (Ctrl-Shift-R):

![image](https://user-images.githubusercontent.com/1267648/30958394-98c48a9c-a402-11e7-9940-9005c5926d8e.png)

**Comment by aeoril** [comment]
@Golmote @mAAdhaTTah Adding the line you suggested above fixed the problem:

https://aeoril.github.io/prism-troubleshooting.html

**Comment by Golmote** [comment]
@aeoril Yes the problem occurs only on Chrome 61+. Refer to #1181 from now on. I'm closing this issue as a duplicate.
