### ISSUE TITLE
Unscaped Markup

### ISSUE THREAD

**Issue by LostInBrittany** [PrismJS/prism#1197]
Hi!

It's my first time posting an issue at Prism, I am not sure about the *etiquette*, so please excuse me if it don't fit :) 

It seems there is a small problem in the [Unescaped Markup doc](http://prismjs.com/plugins/unescaped-markup/). 

It says that you can simply use ` <script type="text/plain"> ` instead of using `<pre><code>` elements. I tried, it didn't work, so I looked at the code and I saw the plugin added some new selectors:

```
	Prism.hooks.add('before-highlightall', function (env) { 
		env.selector += ", .lang-markup script[type='text/plain'], .language-markup script[type='text/plain']" +
		                ", script[type='text/plain'].lang-markup, script[type='text/plain'].language-markup";  
	});
```
So it seems that  `<script type="text/plain"> ` won't work, that you need either `<sometag class="lang-markup"><script type="text/plain">`,  `<sometag class="language-markup"><script type="text/plain">`, 
`<script type="text/plain" class="lang-markup">` or `<script type="text/plain" class="language-markup">`

I tested with them and it worked. 

I was going to do a PR for this, but before I'd like to know which is the intended behavior, the one described in the doc (without added CSS classes) or the one in the code.

Thanks!

**Comment by Golmote** [comment]
Hi! The expected behaviour is the one in the code. The doc might need so clarification indeed.
