### ISSUE TITLE
change the language-javascript to language-js ?

### ISSUE THREAD

**Issue by jipexu** [PrismJS/prism#1199]
Hi
@ first Really nice works !

i just implemented in our CMS (NPDS) and work fine. But i meet some problem with this class name because in our CMS we protect (escaped with !!) the string javascript before the entry in the DB  to avoid some problem especially in the forums and news publications systems ...

So sure i can hack this but why not to change this class name ?
from  language-javascript to language-js
my only argue is that the "javascript" string is more able for malicious use than the "js" string
Thanks

**Comment by Golmote** [comment]
Hi! I can't test it right now, but I'm pretty sure we already alias "javascript" as "js". Have you tried using `language-js`?

**Comment by jipexu** [comment]
yes it's seems to work ...

**Comment by jipexu** [comment]
yes it's work thank !
