### ISSUE TITLE
PHP Tag Problem

### ISSUE THREAD

**Issue by digitalmatter** [PrismJS/prism#1202]
When I write 
```
<?php
echo "Hi;
?>
```
Nothing shows.

Without the `<?php ?>` it works.

Please help with this bug.

**Comment by Golmote** [comment]
You need to escape `<` as `&lt;`.

**Comment by digitalmatter** [comment]
Thank you Golmote. Solved the issue by using <xmp></xmp> tags.

**Comment by ianizaguirre** [comment]
I have this same issue and escaping it does solve the problem. But how come it works without having to escape the code when I test it on the test-drive page: http://prismjs.com/test.html . ?
