### ISSUE TITLE
JSON highlighter mistake

### ISSUE THREAD

**Issue by kvz** [PrismJS/prism#1204]
Hi, thanks so much for Prism, we're loving it at Transloadit.

Think I may have found a bug in the JSON parser in case that's helpful. It appears to me that when a value contains a colon, it's mistaken for a key.

Here's a screenshot where it gets confused when a value is `:original`

<img width="802" alt="screen shot 2017-10-12 at 12 42 34" src="https://user-images.githubusercontent.com/26752/31492334-d834f9f2-af4a-11e7-9d94-162b37b08be9.png">

And here's the full code used, for convenience:

```json
{
  "steps": {
    "imported": {
      "robot": "/s3/import",
      "result": true,
      "key": "xxx",
      "secret": "xxx",
      "bucket_region": "us-east-1",
      "bucket": "demos.transloadit.com",
      "path": "my_folder/snowflake.jpg"
    },
    "exported": {
      "use": ["imported", ":original"],
      "robot": "/s3/store",
      "key": "YOUR_AWS_KEY",
      "secret": "YOUR_AWS_SECRET",
      "bucket_region": "us-east-1",
      "bucket": "demos.transloadit.com"
    }
  }
}
```

Using prismjs via npm, version: `1.8.1` which is the latest version at the time of writing

**Comment by Golmote** [comment]
Thanks for reporting. It should be fixed now. It will be in next release.

**Comment by Golmote** [comment]
Yes, it's `1.8.4`. I just released it now.

**Comment by kvz** [comment]
Awesome! That fixed it: https://transloadit.com/demos/video-encoding/encode-for-ipad/ :tada: :smile:

--
Kevin van Zonneveld (kvz.io)
Co-founder at Transloadit (transloadit.com)
Core-author of tus (tus.io)
