### ISSUE TITLE
Line Numbers don't show with Line Highlight

### ISSUE THREAD

**Issue by wyl320** [PrismJS/prism#1209]
my code
 
 

> <pre

 class="line-numbers" data-line="3"  ><code class="language-css" class="line-numbers-rows">
....

 </code></pre>

My effect

![image](https://user-images.githubusercontent.com/8703754/31854049-c7c103cc-b6c5-11e7-8af7-75272237c213.png)

Did not
![image](https://user-images.githubusercontent.com/8703754/31854077-5634058c-b6c6-11e7-956e-3aebb70148e4.png)

How can I solve it?

**Comment by mAAdhaTTah** [comment]
Do you have a public example we can look at?

**Comment by wyl320** [comment]
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>html第一节课</title> 
<link href="prism.css" rel="stylesheet">   
<script src="prism.js"></script>
</head>
<body>
   <pre class="line-numbers" data-line="6"  ><code class="language-css" class="line-numbers-rows">
    function k(v) {
        return v.replace(/&/gm, "&amp;").replace(/</gm, "&lt;").replace(/>/gm, "&gt;")
    }
    function d(v) {
        return Array.prototype.map.call(v.childNodes,
        function(w) {
            if (w.nodeType == 3) {
                return b.useBR ? w.nodeValue.replace(/\n/g, "") : w.nodeValue
            }
            if (t(w) == "br") {
                return "\n"
            }
            return d(w)
        }).join("")
    }
   </code></pre> 
</body>
</html>

**Comment by Golmote** [comment]
AFAICT this is an intended behaviour. The Line Highlight plugin doesn't add a line number to the highlighted line if the Line Numbers plugin is also loaded.
Please provide an online example if I misunderstood the issue.
