### ISSUE TITLE
Set the data-line= "6", the sixth line of the text can be set color?

### ISSUE THREAD

**Issue by wyl320** [PrismJS/prism#1210]
Set the data-line= "6", the sixth line of the text can be set color?

Now support this effect?
![image](https://user-images.githubusercontent.com/8703754/31854189-c7b0994a-b6c7-11e7-9963-5237b1f2d348.png)
Set this line to the specified color？

![image](https://user-images.githubusercontent.com/8703754/31854256-59e19f94-b6c8-11e7-854d-24db8db17435.png)

**Comment by Golmote** [comment]
No, the way the plugin works, you can not set the color of the highlighted line automatically. But you could use the [Keep Markup plugin](http://prismjs.com/plugins/keep-markup/) to manually achieve this effect.
