### ISSUE TITLE
Syntax Highlighting Not Working on Desktop (WordPress)

### ISSUE THREAD

**Issue by Tynael** [PrismJS/prism#1211]
I've stumbled upon a strange issue lately. The syntax highlighting of PrismJS is not working anymore on my website (https://www.neutrondev.com) on Desktop version, although a few days ago worked flawlessly. Although, the syntax highlighting seems to work ok on the mobile version of the website.

I've spent 5 hours debugging the issue and I couldn't spot it and it's getting on my nerves.

Can you please help me find the issue?

**Comment by mAAdhaTTah** [comment]
Highlighting seems to work fine here: https://neutrondev.com/how-build-first-app-electron/

![how_to_build_your_first_app_with_electron_-_neutron_dev](https://user-images.githubusercontent.com/4371429/32059373-ef71b5d4-ba39-11e7-876a-a89f7caa8ac6.png)

What browser / OS are you seeing this issue on?

**Comment by Tynael** [comment]
I tested on Google Chrome Version 61.0.3163.100 (Official Build) (64-bit) , Mozilla Firefox 56.0.1 (64-bit) on Windows 10.

![no_syntax_highlighting](https://user-images.githubusercontent.com/16559614/32060456-742a52c6-ba77-11e7-965f-5448542cc843.JPG)

On my iPhone 6 on the latest Google Chrome and Mozilla Firefox builds, the syntax highlighting works ok...

**Comment by mAAdhaTTah** [comment]
Do you see any errors in the console? I'm on the same version of Chrome (but for Mac) and don't see any issues, so this is a bit weird.

**Comment by Tynael** [comment]
There are no errors in the console. I even tried different (and the default) WordPress themes but without success, the syntax highlighting is not working on Desktop (at least for me and other people I've asked to also check out this issue).

**Comment by Golmote** [comment]
I do reproduce the issue.
Are you loading Prism asynchronously? If so, you must call `Prism.highlightAll()` manually once it's loaded.

**Comment by Tynael** [comment]
@Golmote I'm a bit newbie here and I'm not quite sure I understand. If the PrismJS loads synchronously, why does it work only on Mobile version of the website and not on Desktop too?
How do I manually call `Prism.highlightAll()` manually once it's loaded?

**Comment by Golmote** [comment]
Prism by default tries to highlight stuff once your page is loaded. If Prism manages to load before your page has finished loading, highlighting should work properly (I guess this scenario happens on mobile somehow). But if it loads after the page is loaded, it might not catch the event, and you'd have to trigger highlighting manually.

It's just a theory though, I don't know how your website works and handles file loading...

**Comment by Tynael** [comment]
Thanks for the clarification.
I am using `add_action()` and `wp_enqueue_scripts` to load the Prism .js and .css file into my child-theme like this:
```
 function add_prism() {
    wp_register_style('prismCSS', get_stylesheet_directory_uri() . '/css/prism.css');
    // Register prism.js file
    wp_register_script('prismJS', get_stylesheet_directory_uri() . '/js/prism.js');
    // Enqueue the registered style and script files
    wp_enqueue_style('prismCSS');
    wp_enqueue_script('prismJS');
}

add_action('wp_enqueue_scripts', 'add_prism'); 
```
I will try and see if I can use Async with enqueue.

**Comment by Tynael** [comment]
All right, thank's to @Golmote comment here is what I've done.
I couldn't find a proper solution to use Async with `wp_enqueue_scripts` and I've done the following:
1. Create a new JS file in my js child-theme folder
2.  Add this JS code to the newly created JS file
`(function($) {
    Prism.highlightAll();
})(jQuery);`
3. Load the newly created JS file with `wp_register_script('testJS', get_stylesheet_directory_uri() . '/js/test.js');`

Now the `Prism.highlightAll();` will be called when the DOM has been loaded.

I don't know if this is the most elegant solution but at least it works for now...

**Comment by GuenniWeb** [comment]
first it is important to have those classes on pre and code before the script is loaded.
Go and load them f.e. in the head area. After that use those "new" methods to load the script asynchronous:
`function add_prism() {
  wp_enqueue_style( 'prism-css',  get_stylesheet_directory_uri() . '/js/prism.css' , array('avia-layout'), $vn, 'all' );
  wp_enqueue_script( 'prism-js', get_stylesheet_directory_uri().'/js/prism.js', array('jquery'), $vn, array('in_footer' => true,'strategy'  => 'async'));
}
add_action( 'wp_enqueue_scripts', 'add_prism' );`

don't know if the prism script needs to beloaded after jQuery so it might be work without setting this array('jquery') and just use ' '
