### ISSUE TITLE
Can ELM be added to Syntax Highlighting?

### ISSUE THREAD

**Issue by fourjr** [PrismJS/prism#1212]
If ELM can be added to https://github.com/PrismJS/prism/tree/gh-pages/components, it'll be great.

ELM examples:
https://github.com/elm-lang/core/blob/master/tests/Main.elm

ELM will also make the `pip` in the following command a different color which is beneficial to the docs I'm making with docsify:
```elm
pip install something
```

I don't know how to create one of those files myself so I can't send a PR

**Comment by Golmote** [comment]
There is already a pending PR (#1174) for this, waiting for changes to be done.

**Comment by fourjr** [comment]
Okay thanks!
