### ISSUE TITLE
Third-party language definitions - prism-ejs-language

### ISSUE THREAD

**Issue by dutchenkoOleg** [PrismJS/prism#1215]
I wrote tiny extend for EJS highlighting  
maybe someone will handy

https://github.com/dutchenkoOleg/prism-ejs-language

Also, it would be great to hear criticism if I did something wrong ))

**Comment by Golmote** [comment]
You could make a PR if you want EJS to be available directly from this repo, and on Prism website.
You'd have to add [tests](https://github.com/PrismJS/prism/tree/gh-pages/tests/languages) ([Test suite](http://prismjs.com/test-suite.html)), though.
