### ISSUE TITLE
Support for flow types

### ISSUE THREAD

**Issue by martinBadin** [PrismJS/prism#1216]
Hello,

please add support for flow types. Webpage is [here](https://flow.org/en/).

Examples
```jsx
type CustomType = {
    n: string,
    n2: Array<string>,
    ...
};

(n: string | boolean | number | Function | Object | any)
(n: { [string]:string })
(n: Array<string>)
(n: CustomType)
```

![image](https://user-images.githubusercontent.com/5845264/32315058-e1712c5a-bfaa-11e7-9f40-2adacd1b6636.png)

![image](https://user-images.githubusercontent.com/5845264/32315073-f13783be-bfaa-11e7-89ac-1163404da0e4.png)

Thank you

**Comment by Golmote** [comment]
Hi. This looks quite tedious... Flow syntax allows many many things, and it appears to be quite hard to highlight those precisely without breaking some of the normal JS highlighting.

The best I managed to come up with is the following:

The component would only highlight these types:

- `number`, `Number`
- `string`, `String`
- `boolean`, `Boolean`
- `Function`
- `any`, `mixed`, `null` and `void`

It would highlight these keywords:

- `type`, `opaque`, `declare`, `Class`
- `$await`, `$Diff`, `$Exact`, `$Keys`, `$ObjMap`, `$PropertyType`, `$Shape`, `$Record`, `$Supertype`, `$Subtype`, `$Enum`

It would highlight `{|` and `|}` as punctuation.

It would *not* highlight generic types, or custom types.

Here is what it would look like (those are examples from the documentation):

![capture d ecran 2017-11-05 a 16 46 56](https://user-images.githubusercontent.com/565460/32416413-f6cc4364-c248-11e7-94ed-e897bd6a0428.png)

Would it be good enough?

**Comment by martinBadin** [comment]
Hi, good, it should be enough.

**Comment by Golmote** [comment]
Just added support for Flow ;)
