### ISSUE TITLE
Keep-markup still strips away all the mark-up

### ISSUE THREAD

**Issue by jan-dh** [PrismJS/prism#1217]
Downloaded a custom build with the following languages:
- markup
- css
- clike
- javascript

And the plugins 
- line-numbers
- command-line
- normalize-whitespace
- keep-markup 

All the plugins are working, except for the keep-markup. Can send you the build file if you like.

<img width="404" alt="screenshot 2017-11-05 14 08 19" src="https://user-images.githubusercontent.com/5801781/32415037-d396fc88-c232-11e7-85a4-c40bac5f5650.png">
<img width="445" alt="screenshot 2017-11-05 14 09 19" src="https://user-images.githubusercontent.com/5801781/32415042-f42b97b0-c232-11e7-9d36-8ae1c43d694a.png">

**Comment by Golmote** [comment]
The Keep Markup plugin is used to do exactly what your screenshot describes: keep the markup _and let the browser interpret it_.
I think what you're looking for is the [Unescaped Markup plugin](http://prismjs.com/plugins/unescaped-markup/), which allows you to write HTML code without having to manually escape `<` as `&lt;`.

**Comment by jan-dh** [comment]
Aha, i see, any way to combine this with the line-numbers and command-line plugins? The first way "Instead of using <pre><code> elements, use <script type="text/plain">" doesn't seem to work with the line-numbers. The second way: Use a HTML-comment to escape your code doesn't seem to output anything

**Comment by Golmote** [comment]
It seems to work just fine on my side:

```html
<link type="text/css" rel="stylesheet" href="themes/prism.css" />
<link type="text/css" rel="stylesheet" href="plugins/unescaped-markup/prism-unescaped-markup.css" />
<link type="text/css" rel="stylesheet" href="plugins/command-line/prism-command-line.css" />
<link type="text/css" rel="stylesheet" href="plugins/line-numbers/prism-line-numbers.css" />

<pre><code class="language-markup line-numbers"><!--<div class="foo">
	<span class="bar"></span>
</div>--></code></pre>

<pre><code class="language-markup command-line"><!--<div class="foo">
	<span class="bar"></span>
</div>--></code></pre>

<script type="text/plain" class="language-markup line-numbers"><div class="foo">
	<span class="bar"></span>
</div></script>

<script type="text/plain" class="language-markup command-line"><div class="foo">
	<span class="bar"></span>
</div></script>

<script src="prism.js"></script>
<script src="plugins/unescaped-markup/prism-unescaped-markup.js"></script>
<script src="plugins/line-numbers/prism-line-numbers.js"></script>
<script src="plugins/command-line/prism-command-line.js"></script>
```

![https://i.imgur.com/EQjEHbZ.png](https://i.imgur.com/EQjEHbZ.png)

**Comment by jan-dh** [comment]
Was markup-issue on my side, thx for the examples
