### ISSUE TITLE
Support new JavaScript syntax

### ISSUE THREAD

**Issue by mxstbr** [PrismJS/prism#1219]
This is what I get when I highlight a JavaScript snippet with some new syntax:

![screen shot 2017-11-13 at 12 53 16 pm](https://user-images.githubusercontent.com/7525670/32724478-c3015342-c871-11e7-8bb3-dd2de91666a4.png)

([Live demo](https://spectrum.chat/thread/3baad948-1fc1-491a-8198-3730ea5e288e))

This snippet is using ES6 JavaScript `class`es and some Stage 2 or 3 syntax for class properties. (`update = info => this.setState({ info })`) While I understand not supporting non-standard JavaScript features it'd be awesome if there was support for `class`es since they are now a proper vanilla JavaScript feature. 👌

**Comment by Golmote** [comment]
I just tested the code linked on the [Test drive page](http://prismjs.com/test.html) and it works ok with language set to "JavaScript", or language set to "React JSX". So I suspect this is an issue on your side.

**Comment by Golmote** [comment]
Even more, if I go on the Live demo and run the following code in the console:

```js
document.querySelector('code').classList.add('language-javascript');
Prism.highlightElement(document.querySelector('code'));
```
the highlighting works as expected.

**Comment by mxstbr** [comment]
Hm, interesting. Sorry for the noise then, must be an issue on my side!
