### ISSUE TITLE
clipboard don't use the latest version of clipboard.js

### ISSUE THREAD

**Issue by bazooka07** [PrismJS/prism#1220]
The latest version of clipboard.js is 1.7.1, not 1.5.8
https://cdnjs.com/libraries/clipboard.js
Update this page please :
https://github.com/PrismJS/prism/blob/gh-pages/plugins/copy-to-clipboard/prism-copy-to-clipboard.js

**Comment by Golmote** [comment]
Thank you for reporting. The version used has been updated.
