### ISSUE TITLE
Issue with commented code (underline on wrong position)

### ISSUE THREAD

**Issue by acegilz** [PrismJS/prism#1221]
I am having issues displaying the code correctly. When it contains commented code it displays a white bar below text:

https://www.cleverti.com/news/how-to-set-a-symfony-based-rest-api-with-oauth

`<pre>
<code class="language-php">&lt;?php

namespace cleverti\MySuperRestBundle\Controller;

use FOS\RestBundle\Controller\FOSRestController;
use Symfony\Component\HttpFoundation\Request;
use FOS\RestBundle\Controller\Annotations\Get;

class RestController extends FOSRestController
{
    /**
     * Here goes our route
     * @Get("/get/cleverti")
     */
    public function restGetAction(Request $request)
    {
        // Do something with your Request object
        $data = array(
            "name" =&gt; "cleverti",
            "extra" =&gt; "Is awesome!"
        );
        $view = $this-&gt;view($data, 200);
        return $this-&gt;handleView($view);
    }
}</code></pre>

`

<img width="781" alt="screenshot 2017-11-13 19 01 29" src="https://user-images.githubusercontent.com/4284362/32743793-63c78354-c8a5-11e7-8059-d2bda59cb8b4.png">

**Comment by Golmote** [comment]
Indeed you do have the following CSS somewhere on your page:

![https://i.imgur.com/TeSdGla.png](https://i.imgur.com/TeSdGla.png)

**Comment by acegilz** [comment]
Thanks @Golmote .

It worked :)
