### ISSUE TITLE
Visual editor showing no formatting

### ISSUE THREAD

**Issue by xRDK** [PrismJS/prism#1222]
Hello,

I use the text editor for prism within the Jira comments section to preserve spacing as the visual one removes it.
However formatting the below code within the "text" editor results in it being unformatted in the visual editor... very strange;
```
0490.00 c                   eval      #irc=rename(%addr(#tempfilename):
0491.00 c                             %addr(#fullfilename))  
```

Screenshot;

![image](https://user-images.githubusercontent.com/33686741/32830740-1b135120-c9ee-11e7-93de-7ddbe181a13a.png)

This is true for whatever language I pick and whether the manual line numbers are present or not (I'm aware you can put lines numbers in and start them off manually)

Thought I'd raise this.

Thanks,
Ryan

**Comment by Golmote** [comment]
Hi. This sounds more like a Jira issue than a Prism issue.
