### ISSUE TITLE
Coy theme: height CSS tag creates design issues.

### ISSUE THREAD

**Issue by FlipperPA** [PrismJS/prism#1223]
The `height=100%` CSS tag in the coy theme - which doesn't seem to exist in other theme CSS definitions - is causing the code block to render as the browser's height:

Broken:

![image](https://user-images.githubusercontent.com/68164/32969259-5fdfb972-cbb2-11e7-9fad-ea1bd349eb78.png)

Fixed:

![image](https://user-images.githubusercontent.com/68164/32969299-8974d8ee-cbb2-11e7-88c1-068ebf30d5c6.png)

Since it is such a minor change, I will propose a code change via GitHub to remove this single line from the Coy theme. Thanks for your efforts, they are widely appreciated!

**Comment by Golmote** [comment]
I'm not sure what it was for... But I couldn't find any explicit browser issue without the `height` property, so I guess it's ok to remove it. Thanks!
