### ISSUE TITLE
Add support for ASP.NET Razor to languages

### ISSUE THREAD

**Issue by hades200082** [PrismJS/prism#1225]
Razor views mix HTML with a specialised C# or VB.NET style syntax.

This would need two languages to be supported:

- cshtml
- vbhtml

**Comment by lukewhitmore** [comment]
Would be very useful for .NET FE projects

**Comment by hades200082** [comment]
This has been around for a while now... is there any solution yet?

**Comment by laura-rodriguez** [comment]
Hi! any plans to fix this soon?

**Comment by hades200082** [comment]
Either the coming of razor pages and blazor this is getting more important

**Comment by mAAdhaTTah** [comment]
We are happy to accept PRs for new language definitions! Let us know if you have any questions about the documentation.
