### ISSUE TITLE
Issue with Highlight Keywords

### ISSUE THREAD

**Issue by Ma-XX-oN** [PrismJS/prism#1226]
Ok, well this might no be exactly an "issue" as this actually relates to items that are not keywords.  However, what I'd like to do is highlight a token that isn't a keyword.

The language I selected was C++ and there are macros in my code.  I want to highlight those macro names.  How would I do that?

Another thing I noticed with Highlight Keywords is the [documentation](http://prismjs.com/plugins/highlight-keywords/).  I was looking at it and it showed the following:

```
 	.token.keyword.keyword-return, .token.keyword.keyword-if{
 		color: #f92672;
 	}
```

Well, I tried this and it didn't work.  It took some time in reading and debugging as to what this actually did and I found out what was wrong.  I don't know why **.token.keyword** were prefixed to the style selector, but that is what the issue was.  It should be:

```
 	.keyword-return, .keyword-if{
 		color: #f92672;
 	}
```
As a side note.  I find this library very nice.  Thanks to all who are involved in this project.  It makes it easy to style code snippets and is fairly easy to use.  Thanks again.

**Comment by mAAdhaTTah** [comment]
If you can write regex, best bet, I think, would be to modify the language definition at runtime, or create an extended language definition. You can see [here](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-cpp.js) how C++ extends the C language. You can extend C++ w/ like a "C++ Extras" that includes the keywords you want highlighted, then highlight your code snippets with your new language.

**Comment by Ma-XX-oN** [comment]
Hmmm. Ok, looks like extending the language is pretty easy.  I'll give it a go.  The doc should be fixed though.

**Comment by Golmote** [comment]
> The doc should be fixed though.

Do you have an online example reproducing the issue please?

**Comment by Ma-XX-oN** [comment]
I've been testing this out with my blog.  While trying to make a smaller test case, it would seem that I'm getting inconsistent results.  Does the code that I have downloaded refer to code outside that which I downloaded?  Sometimes it is working and sometimes it isn't.  Just refreshing is causing this behaviour to be random.

**Comment by Golmote** [comment]
This sounds very inconsistent indeed. But the code you downloaded should be just fine. And without an example that can reproduce the issue consistently, we won't be able to fix the problem if any.

**Comment by Ma-XX-oN** [comment]
So it doesn't reference anything outside?  Then I'm at a loss.  Now seems to be working with what was documented and doesn't work with what I'm saying.  Very weird.
