### ISSUE TITLE
Is there a way I can tell prism to ignore my template variables?

### ISSUE THREAD

**Issue by aolin480** [PrismJS/prism#1232]
I am using the Markup grammar in my code, but I don't want prism to touch my template tags (example: {#templateTag}) 

Before the pound sign Prism is extracting the `{` and the ending `}` and putting it into a punctuation span. Are there any custom rules I can use that will ignore these? Here is the regex I have to search for them in the code `({\#(.*?)})`. and I tried defining my own grammar for those, but Prism seems to be stepping right over it.

Any help would be awesome! Thanks!

I am thankful for Prism :)

Kind regards

**Comment by aolin480** [comment]
I was actually able to get this going using the following code below. I had to turn off the greedy variable in the string object in Prism.languages.javascript because it was only highlighting the first template tag and not the others. Not too sure what repercussions are to doing that, but it works.

Here's the code I used to get it to work
```
    Prism.languages.insertBefore('javascript', 'comment', {
        'mergetag':  {
            pattern: /({#.*?})/g
        }
    });
    
    Prism.languages.javascript.string.greedy = false;
```

Now it wraps my custom template tags with a mergetag token.

**Comment by Golmote** [comment]
Removing the `greedy` option on strings will likely lead to wrong highlighting on code like `"foo // bar"` where it will be interpreted as a comment instead of a string.

Regarding you initial issue, aren't those tags meants to be replaced with something else, if there are not part of the actual code you want to highlight?

**Comment by aolin480** [comment]
The template tags are getting replaced later, however I am building an interface which shows code and the merge tags, a user has input(s) which when typed it changes out the merge tag with the typed out value. It kind of shows them in real time what variables they are replacing

**Comment by Golmote** [comment]
Ok I see. Well, I can't think of a native option that would make Prism just ignore those tags. So I the workaround you found works, it's probably your best bet here.

**Comment by aolin480** [comment]
Thanks @Golmote! Yeah, this is what I am using Prism for. I love it, and it's super simple. Was just a small hurdle, and I think I am good now. Great library! http://recordit.co/x4EiNSrNwz
