### ISSUE TITLE
PHP multiline strings fail

### ISSUE THREAD

**Issue by landzup** [PrismJS/prism#1233]
PHP allows multiline strings.
That means including newlines and carriage returns into single quote or double quote delimited strings will not break them.

Example:
```
<?php
$test = "This multiline string should
not break";

$msg = 'Happy coding to everybody,
welcome to the Prism.js project!';
?>
```

In Prism.js multiline strings break, either delimited with single or double quotes:
[Demo on jsfiddle](https://jsfiddle.net/landzup/3q79qb3a/)

**Comment by Golmote** [comment]
Thanks for reporting! Should be fixed now.

**Comment by landzup** [comment]
I tested it and works perfectly, thanks very much!
