### ISSUE TITLE
[question] Applying imperatively plugins

### ISSUE THREAD

**Issue by xliiv** [PrismJS/prism#1234]
I'm wondering how to apply plugin
http://prismjs.com/plugins/line-numbers/
on imperative code like:

```
        var myNode = document.querySelector("#myNode");
        var html = Prism.highlight(code, Prism.languages[lang]);
        myNode.innerHTML = html;
```

**Comment by Golmote** [comment]
It's a bit hacky, but assuming `myNode` is a `<code>` element inside a `<pre>` element, and one of them has the `line-numbers` CSS class, you should be able to trigger the line numbers plugin with:

```js
Prism.hooks.run('complete', {
	code: html,
	element: myNode
});
```

**Comment by xliiv** [comment]
I did this..
```
      update(code, lineNumber, lang) {
        var myNode = this.shadowRoot.querySelector('code');
        var html = Prism.highlight(code, Prism.languages[lang]);
        Prism.hooks.run('complete', {
          code: html,
          element: myNode
        });
        myNode.innerHTML = html;
     }
```
but still fails.. However some shade appeard. Am i doing it ok?

Here's the visual effect..
![image](https://user-images.githubusercontent.com/298994/33342981-270a493e-d484-11e7-8865-a05644decf29.png)

**Comment by Golmote** [comment]
You need to run the hook after having set innerHTML.

**Comment by xliiv** [comment]
Final version:
```
      update(code, lineNumber, lang) {
        var myNode = this.shadowRoot.querySelector('code');
        var html = Prism.highlight(code, Prism.languages[lang]);
        this.$['formatted-src'].innerHTML = html
        Prism.hooks.run('complete', {
          code: html,
          element: myNode
        });
      }
```
which works.
Thanks :)

How can I add to the current code another plugin: [line-highlighting](http://prismjs.com/plugins/line-highlight/)

**Comment by Golmote** [comment]
I think you can keep the same code. Just make sure you have a proper `data-line` attribute on the `<pre>`.

**Comment by xliiv** [comment]
The gray box is caused by `line-highlighting` or my code using it :)
Here's picture
![image](https://user-images.githubusercontent.com/298994/33345403-8f790368-d48c-11e7-9939-00dd736dbfbf.png)

**Comment by xliiv** [comment]
This line gives me
`var lineHeight = parseMethod(getComputedStyle(pre).lineHeight);`
`NaN`
because
`getComputedStyle(pre).lineHeight` == `normal`

**Comment by xliiv** [comment]
I don't. However It's present in my project.
To be specific.. if I remove this shameful code:
https://github.com/xliiv/callspect/blob/master/viewer/callspect/static/src-code.html#L32-L34
I'll get `NaN`, I'll bet it's related to `shadowDom`.

**Comment by mAAdhaTTah** [comment]
I _think_ this is resolved but feel free to reopen if there's still an issue here.
