### ISSUE TITLE
JSX: Bug highlighting inline object literal props

### ISSUE THREAD

**Issue by jlmakes** [PrismJS/prism#1235]
### Reproducing The Issue

Use an object literal for a prop value inline, such as `options={{ track: true }}` below:

```jsx
const Component = () =>
    <Child options={{ track: true }}>
        <div>foo</div>
        <div>bar</div>
        <div>jam</div>
    </Child>
```

. . .

### Test Drive Results

![screen shot 2017-11-29 at 5 50 54 am](https://user-images.githubusercontent.com/2044842/33358504-4a971748-d4c9-11e7-910e-24b0041b9902.png)

The highlighting for the line `<Child options={{ track: true }}>` is a bit off.

. . .

Just by pulling the object literal out into a variable, we can see how the highlighting kicks back in:

![screen shot 2017-11-29 at 5 51 51 am](https://user-images.githubusercontent.com/2044842/33358687-5c80fe32-d4ca-11e7-87a5-e92c559056ef.png)

. . .

_Related: #1236_

**Comment by Golmote** [comment]
Thanks for reporting. It should be fixed now. Also take a look at https://github.com/PrismJS/prism/issues/1236#issuecomment-347778525.
