### ISSUE TITLE
JSX: Bug highlighting object spread with object property access

### ISSUE THREAD

**Issue by jlmakes** [PrismJS/prism#1236]
### Reproducing The Issue

Spread over a nested object as component props, such as `{...this.props}` below:

```jsx
const Component = () =>
    <Child {...this.props} option={400}>
        <div>foo</div>
        <div>bar</div>
        <div>jam</div>
    </Child>
```

. . .

### Test Drive Results

![screen shot 2017-11-29 at 6 18 28 am](https://user-images.githubusercontent.com/2044842/33359094-28926504-d4cd-11e7-827a-537c8c862d3d.png)

The highlighting for the line `<Child {...this.props} option={400}>` is a bit off.

. . .

If we don't use the object property access operator, and replace `this.props` with `somePropsObj` for example, we can see how the highlighting kicks back in:

![screen shot 2017-11-29 at 6 15 19 am](https://user-images.githubusercontent.com/2044842/33359030-b50e3f40-d4cc-11e7-81fd-e3cb27e310a9.png)

. . .

_Related: #1235_

**Comment by jlmakes** [comment]
I spy `{\.{3}\w+\}` in [`/components/prism-jsx.js` on line 6](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-jsx.js#L6)

Looks like the regex for object spread to me. I’ll take a stab at a fix.

**Comment by Golmote** [comment]
Thanks for reporting. It should be fixed now.

Note, though, that Prism will still fail on other cases. AFAIK JSX can contain almost all JS has to offer in those tags, and matching everything would be really complicated with just regexps.

Examples that will fail, and I think we won't fix, include:
```jsx
// Spread with anything other than a variable or a simple property access
<Child {...{foo: 'bar', bar: 'baz'}}>
```
```jsx
// Nested objects in attribute value
<Child foo={{ foo: { bar: 'baz'}}}>
```
I'm not even sure those are valid JSX example, but I do know they would fail.

**Comment by jlmakes** [comment]
Really appreciate the fix @Golmote, hyper merci
