### ISSUE TITLE
HTML Support Inside of PHP

### ISSUE THREAD

**Issue by benjaminBrownlee** [PrismJS/prism#1238]
I noticed that this library did an excellent job at supporting CSS and JavaScript markup inside of an HTML document when placed between the appropriate tags (`<style>` and `<script>`). I was wondering if the same support could come with HTML inside of PHP files, since many of my PHP pages largely involve writing HTML tags, which turn out rather ugly.

For example, one of my current pages looks like this:
![image](https://user-images.githubusercontent.com/29786277/33470986-51225a04-d628-11e7-82ec-1b4a6df026ef.png)

I actually want to also note that, since some files had less PHP than HTML, I tried overwriting the default from the file type, which worked for formatting, but oddly removed my toolbar.

**Comment by benjaminBrownlee** [comment]
I realize that this is an already open issue here: #1218.

**Comment by zeitgeist87** [comment]
It does work perfectly for PHP. There has to be at least one `<?php ?>` tag in the source code, for Prism to detect if it is a HTML page with PHP tags included or simple plain PHP code. So if you add `<?php ?>` and make sure that the Markup, Javascript and HTML languages are loaded before PHP, it should work.

You can try it on the test page: http://prismjs.com/test.html
