### ISSUE TITLE
Wrong embedded language detection

### ISSUE THREAD

**Issue by uhyo** [PrismJS/prism#1240]
Hi. I'm not sure this is actually a bug or a kind of "edge cases",
but the following HTML snippet is wrongly highlighted by Prism.js. It reproduces at the [test page](http://prismjs.com/test.html) for now.
```html
<script>
  let str = `
    <p>hello</p>
    <style>
      .foo { color: blue; }
    </style>
  `;
</script>
```
It seems that it fails to detect the embedded JavaScirpt code due to a style tag in a string literal.
Thanks.

**Comment by Golmote** [comment]
Nice catch! Thanks for reporting!
