### ISSUE TITLE
Cannot install via jspm

### ISSUE THREAD

**Issue by kwesterfeld** [PrismJS/prism#1243]
This is likely a jspm bug, but if you were able to help me work around this I'd love to start using prismjs.   I want to ditch hljs and codemirror in my app.

Here's the issue:
```
 % jspm i npm:prismjs
     Updating registry cache...

err  Repo jspm:clipboard not found. Perhaps try jspm install npm:clipboard.

warn Installation changes not saved.
```

I tried installing clipboard first, no dice.

Perhaps you can submit prismjs and clipboard to the jspm registry?

jspm issue: https://github.com/jspm/jspm-cli/issues/2384

**Comment by kwesterfeld** [comment]
It may be the case that the prismjs package.json should not specify the jspm registry, when itself is not in the jspm registry:

```
  "jspm": {
    "main": "prism",
    "registry": "jspm",
```

**Comment by aluanhaddad** [comment]
Thanks @kwesterfeld I added a mapping in the JSPM registry for clipboard. PrismJS is now installing without incident for me.
