### ISSUE TITLE
react virtual dom is not shown

### ISSUE THREAD

**Issue by ShawnBaek** [PrismJS/prism#1248]
I'm using prismjs on my react website.

I uses dangerouslySetInnerHTML.

The results are working fine but look at return code...

It only shows without virtual dom tags...

return (
                     
                              {postTitle}
                               
);

<pre><code class="language-jsx">

render(){
            
                    const postTitle =  _.result(this.props.posts, 'title.rendered');
                    const postContents = _.result(this.props.posts, 'content.rendered');
                    const postStatus = _.result(this.props.posts, 'status');
                    const date = _.result(this.props.posts, 'date');
                    const postId = _.result(this.props.posts, 'id');
            
                    const landing_img =  _.result(this.props.posts, 'acf.landing_image.url');
                    const landingStyle = {
                        
                        backgroundImage: 'url(' + landing_img + ')'
                    };
            
                   
            
                    return (
                        <div>
                            <section className="section-landing" style={landingStyle}>
                            </section>
            
                            <div className="container bottom-medium-spacing">
                                <h1>{postTitle}</h1>
                                <article 
                                    dangerouslySetInnerHTML={ { __html: postContents } }>
                                </article>
            
                            </div>
                        </div>
                    );
            
                }

</code></pre>

**Comment by Golmote** [comment]
Hi! Your post is really messy, I can't even understand your problem. I'm closing this issue: if you still have a problem, please open a new one, providing an online example reproducing this issue, and appropriate code blocks (if needed), properly formatted.
