### ISSUE TITLE
Support for Terraform

### ISSUE THREAD

**Issue by howdoicomputer** [PrismJS/prism#1252]
Support for Terraform: 

https://www.terraform.io/

**Comment by Golmote** [comment]
I assume you're talking about the configuration syntax for Terraform, known as HashiCorp Configuration Language (HCL). For future reference, here are the [syntax documentation](https://www.terraform.io/docs/configuration/syntax.html) and the [interpolation documentation](https://www.terraform.io/docs/configuration/interpolation.html).
