### ISSUE TITLE
Recursive highlighting ?

### ISSUE THREAD

**Issue by Banou26** [PrismJS/prism#1258]
Hey, i made a small extends that basically allow me to highlight the html inside my template litteral tag ```
html`<my-html></my-html>` ```

So i basically took the <script> tag extends and modified it for my purpose which resulted in: 
```
Prism.languages.insertBefore('javascript', 'template-string', {
  'html-template-string': {
    pattern: /html`(?:\\[\s\S]|[^\\`])*`/,
    inside: {
      'interpolation': {
        pattern: /\$\{[^}]+\}/,
        inside: {
          'interpolation-punctuation': {
            pattern: /^\$\{|\}$/,
            alias: 'punctuation'
          },
          rest: Prism.languages.javascript
        }
      },
      rest: Prism.languages.markup
    }
  })
```
And it works great until i try to use backticks inside the interpolation:
[exampe1](https://puu.sh/yRRhT/ec64efab4d.png) or [example2](https://puu.sh/yRRjG/24c82a4d50.png)
[Result without the backticks](https://puu.sh/yRRkv/9a4e20f961.png)

Any idea if this can be fixed or if it's a limitation due to the use of regexes ?

**Comment by Golmote** [comment]
Your pattern for `html-template-string` does not allow backticks except for the surrounding ones. You could change your regexp to allow one or two levels of nesting, but you can hardly make it infinite, because JS regexps aren't recursive indeed.

**Comment by Banou26** [comment]
Yeah, that's what i thought so too, thanks
