### ISSUE TITLE
Support: Cannot determine how to change theme

### ISSUE THREAD

**Issue by ORESoftware** [PrismJS/prism#1261]
I have looked through the docs a couple of times, and I cannot figure out how to change the highlighting theme! Looks like all the main themes are in a single css file, so how do I work with that?

**Comment by ORESoftware** [comment]
From this NPM repo

https://www.npmjs.com/package/prism-themes

it looks like you have to import a different theme (a different css file)

**Comment by Golmote** [comment]
All the main themes are in a different stylesheet each. Just load the one you want. https://github.com/PrismJS/prism/tree/gh-pages/themes

**Comment by the1mills** [comment]
Ok thank you
