### ISSUE TITLE
Best way to to get unescaped HTML working?

### ISSUE THREAD

**Issue by iwasherefirst2** [PrismJS/prism#1262]
Hello,

I am looking for a good way to use the `class="language-php"` so that I can use HTML snippets without having to escape the characters `<` and `>`.

I have read already https://github.com/PrismJS/prism/issues/572 and understand that most people here think the replacement should be done serverside and not be part of the plugin. I respect that, but I would still like to find a solution.

I found that for the class `language-markup` there exists already a plugin (http://prismjs.com/plugins/unescaped-markup/) but I found that this is only working for the class "language-markup" and unfortunately not for "language-php".

I found another solution  which suggests to put a script tag inside the code tag to show the actual HTML: https://stackoverflow.com/a/27495949/2311074

Is that the recommended way?

And as a suggestion: Wouldn't it be nice if the "unescaped markup" plugin also works for `language-php` since you often have mixed PHP and HTML code?

**Comment by Golmote** [comment]
Hi!
There was discussion about not restricting the plugin to the Markup component in #892. But it appears no one had a chance to work on this yet.
The trick used in the SO answer you linked is smart too. It can be a workaround for the time being.

I'll try to dig into this issue in the near future.
