### ISSUE TITLE
The downloads page would be even better if it had updating #args in its URL

### ISSUE THREAD

**Issue by paul-hammant** [PrismJS/prism#1263]
The page in question: https://github.com/PrismJS/prism/blob/gh-pages/download.html

What I'm suggesting is it should have URLs like: https://prismjs.com/download.html#Java+Scala+Clojure+Funky+LineHighligher+Toolbar

And that as you select or deselect items from the huge amount of choices, the URL changes automagically.

## Tech thoughts

Items to the right of the # are rewritable in page w/o a page-reload of course. This can be done with vanilla JavaScript (I note there's no react, vuejs in that page). It's all perfectly compatible with a static gh-pages deployment.

## Benefits

1. People can email links to each other saying "this is what you want" - say on portals like stackoverflow.  
2. Most important of all though - when **I** upgrade my fine-grained selection of components of PrismJS a year from now, I don't have to refer to a screen shot of my selection, I can just WGET a URL that I stored and commit/push those CSS & JS puppies.

**Comment by paul-hammant** [comment]
OK, I see that it is halfway there already - http://prismjs.com/download.html?themes=prism&languages=markup+clike+javascript+csharp+ruby+java+python&plugins=line-highlight+file-highlight+toolbar+highlight-keywords - but "?"  implies a server-side operation, whereas "#" can mutate safely on the client side as the end user clicks - right?

**Comment by Golmote** [comment]
Hi @paul-hammant! I like this idea.
The query string version of this already exists indeed. The URL is included at the first line of the generated JS and CSS files, for easy redownload. I guess an hash version should be ok too (and would allow for a nice onhashchange event handling), as long as we keep backward compatibility for the query-string version on page load.
Would you like to give it a try and make a PR for this?

**Comment by paul-hammant** [comment]
Good work, @Golmote :)
