### ISSUE TITLE
Support for SURF format: language-surf (USD$200 bounty)

### ISSUE THREAD

**Issue by garretwilson** [PrismJS/prism#1264]
I would like Prism to support SURF, a new file format I've created. SURF is part of a framework I've been working on for over 10 years; I didn't just throw it together on the spur of the moment. 😉 

You can find a (very) quick overview here: https://urf.io/surf/#quick-start

For a complete introductory lesson on SURF, read: https://urf.io/surf/learn . If that's too much to read, check out the presentations at https://urf.io/surf/present/ .

The complete specification draft is available at https://urf.io/surf/spec

Note that the entire SURF site above already uses Prism! In fact the pages are ready for SURF --- all the code blocks already use `language-surf`, just waiting for support to be added.

Yes, I am aware that at the moment I am perhaps the only person in the world using SURF. I am aware that some may not see the need for SURF. (For more of the context, see https://urf.io/ .) I also understand that I could write this plugin myself, but as you might have guessed I already have a gazillion things to write.

**I am willing to pay someone to add SURF language syntax formatting support for Prism.** I would be happy to create a bounty at [BountySource](https://www.bountysource.com/), or I could pay someone via PayPal directly. Questions/comments on payment, please contact me.

Thank you!!!!

**Comment by Golmote** [comment]
Hi @garretwilson. I don't think we would include the SURF format support directly inside Prism, since as you say it, there might not be a huge demand for it at the moment.
I'll let this issue open, though, and I might take a look at it at some point.

**Comment by garretwilson** [comment]
So what is the alternative? I have sites and lessons and presentations all using Prism, waiting for Prism format support for SURF. Is it possible to create a Prism plugin for the SURF format separate from the main Prism distribution? Fine. I'll pay for that.

It's a chicken-and-egg problem. No one will adopt a new format if there are no tools support. But you're saying that we don't want tools support until lots of people have adopted the format, so we're in a circle.

I'll have to admit that I'm a tiny bit skeptical at your reasoning. Prism already has support for formats I've never heard of, including `inform7`, `j`, `mel, `,mizar`, and `parigp`. Remember that users get to choose which of these formats they download, so I'm not sure I understand the problem.

As I said I need this support now, and I'm willing to pay for it. It doesn't have to be part of the main Prism distribution yet, but I need it done. It can be part of a completely different repository if you want, but I thought I'd post it here because here are where the Prism experts are hanging out. And if you _do_ want it as part of Prism, you benefit for free. Is anyone interested?

**Comment by Golmote** [comment]
Wow I must have failed miserably to explain myself because you completely misunderstood my answer apparently.
All you need to highlight SURF is a grammar definition. It does not need to be part of the official Prism repo to work properly.
So, even if we probably won't add it to the official repo, I will let this issue open so that I (or someone else) can make said grammar file so that you can use it to highlight SURF on your website.
Hope it makes more sense now.

**Comment by garretwilson** [comment]
I've just placed a USD $200 bounty on this ticket.

https://www.bountysource.com/issues/53722666-support-for-surf-format-language-surf

Hopefully someone here knows how to write grammar definitions and is interested in doing the work. Let me know if some other amount is more reasonable. Thanks in advance.

**Comment by Golmote** [comment]
@garretwilson Here, give this grammar a try. You can obviously change/remove the aliases if you want to adjust the styling.
Note that I'm not willing to do any kind of maintenance for this. Also, I do not ask for any money. This is just to lend a hand.
If SURF becomes somewhat popular at some point, I'd be glad to reconsider adding it to the main Prism repo.

```javascript
Prism.languages.surf = {
	'comment': /!.*/,
	'uuid': {
		// &5623962b-22b1-4680-ae1c-7174a46144fc
		pattern: /&[\da-f]{8}-(?:[\da-f]{4}-){3}[\da-f]{12}/i,
		alias: 'number'
	},
	'email': {
		// ^jdoe@example.com
		pattern: /\^[\w-]+@[\w-]+\.[a-z]{2,6}/i,
		alias: 'string'
	},
	'phone': {
		// +12015550123
		pattern: /\B\+\d+/,
		alias: 'number'
	},
	'binary': {
		// %Zm9vYmFy
		pattern: /%[a-z\d+/]+/i,
		alias: 'string'
	},
	'string': {
		pattern: /(["'])(?:\\[^\r\n]|(?!\1)[^\\\r\n])*\1/,
		greedy: true
	},
	'regex': {
		pattern: /\/(?!\/)(\[[^\]\r\n]+]|\\.|[^/\\\[\r\n])+\/[gimyu]{0,5}/,
		greedy: true
	},
	'label': {
		// |label| <|tags|> |"Ids"|
		pattern: /\|[^|]+\|/,
		greedy: true,
		alias: 'variable'
	},
	'iri': {
		/*
		<http://example.com/>
		<&5623962b-22b1-4680-ae1c-7174a46144fc>
		<urn:uuid:5623962b-22b1-4680-ae1c-7174a46144fc>
		<^jdoe@example.com>
		<mailto:jdoe@example.com>
		<+12015550123>
		<tel:+12015550123>
		*/
		pattern: /<[^>]+>/,
		greedy: true,
		alias: 'variable'
	},
	'datetime': {
		/*
		@2017-02-12T23:29:18.829Z
		@2017-02-12T15:29:18.829-08:00[America/Los_Angeles]
		@2017-02-12T15:29:18.829-08:00
		@2017-02-12T15:29:18.829
		@2017-02-12-08:00
		@2017-02-12
		@2017-02
		@2017
		@--02-12
		@15:29:18.829-08:00
		@15:29:18.829
		*/
		/*
		instant |
		year[-month[-day[Ttime[.prec]][+-offset[tz]]]] |
		--month-day |
		time[.prec[+-offset]]
		*/
		pattern: /@(?:\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d+)?Z|\d{4}(?:-\d\d(?:-\d\d(?:T\d\d:\d\d:\d\d(?:\.\d+)?)?(?:[+-]\d\d:\d\d(?:\[[^\]]+])?)?)?)?|\d{4}(?:-\d\d)?|--\d\d-\d\d|\d\d:\d\d:\d\d(?:\.\d+(?:[+-]\d\d:\d\d)?)?)/,
		alias: 'number'
	},
	'type': {
		pattern: /(\*)(?:[a-z\xA0-\uFFFF][\w\xA0-\uFFFF]*-)*[a-z\xA0-\uFFFF][\w\xA0-\uFFFF]*(?=:)/i,
		lookbehind: true,
		greedy: true,
		alias: 'variable'
	},
	'boolean': /\b(?:true|false)\b/,
	'number': /[#$]?-?\d*\.?\d+(?:e[+-]?\d+)?/i,
	'operator': /\*/,
	'punctuation': /[=:;,[\](){}]/
};
```

If it fits your needs, feel free to close this issue.

**Comment by garretwilson** [comment]
Woohoo! Thank you, @Golmote . I'm anxious to try it out. So I can just include this as JavaScript in my pages? Does it need to be before or after the main Prism include, or does it matter?

This will be a huge help! I'm sure we can tweak this. The biggest step is just getting started, which would have taken a lot of time and research for how to create Prism templates. This gives us a great head start, and I really appreciate it.

Lastly, is there a page with official documentation and explanation of Prism plugin programming if we have questions and when we tweak/extend this?

**Comment by Golmote** [comment]
Yes you just need to include it after the main Prism script. 
For documentation, you can take a look at this page: http://prismjs.com/extending.html
