### ISSUE TITLE
show tables

### ISSUE THREAD

**Issue by JarboU** [PrismJS/prism#1270]
How can the table be displayed on the front end?

**Comment by Golmote** [comment]
Hi. Could you be more specific? Maybe add an online example reproducing the issue?

**Comment by JarboU** [comment]
| Date  |  Name |  Pay |  $ |
| ------------ | ------------ | ------------ | ------------ |
| 2017-11-09  | Dawei| WEIXIN  |  18.8 |

Like this Markdown syntax, the output is a table；

**Comment by JarboU** [comment]
```
| Date|  Name |  Pay |  $ |
| ------------ | ------------ | ------------ | ------------ |
| 2017-11-09  | Dawei  | WEIXIN  |  18.8 |
```

**Comment by JarboU** [comment]
How to use prism.js implementation one？

**Comment by Golmote** [comment]
I'm sorry, Prism is a syntax highlighter, not a markup language nor a Markdown interpreter. We do not provide such a feature.
