### ISSUE TITLE
Prism.js doesn't highlight some code blocks

### ISSUE THREAD

**Issue by wrayzheng** [PrismJS/prism#1279]
Before I use prism.js, the `<pre>` code block looks like:

    <pre class="line-numbers prism-highlight" data-start="1">
        <code class="language-xml">...</code>
    </pre>

After I use prism.js to render the code block, normally it looks like:

    <pre class="line-numbers prism-highlight language-xml" data-start="1" style="counter-reset: linenumber 0;">
        <code class=" language-xml">...</code>
    </pre>

However, the problem comes when I insert a `<pre>` code block without specifying language, or rather `language-null`. All `<pre>` block after this block with `language-null` will be wrongly rendered without `language-xxx` class in the `pre` tag:

    <pre class="line-numbers prism-highlight" data-start="1">
        <code class="language-xml">...</code>
    </pre>

And those blocks before the `language-null` block are still correctly rendered.

It's so weird. Any help will be appreciated!

**Comment by Golmote** [comment]
Hi! Could you provide us with on online example reproducing the issue so we can investigate?

**Comment by wrayzheng** [comment]
Of course. [Check out this post](http://www.codebelief.com/article/2018/02/java-multi-thread-race-condition-mutual-exclusion-and-synchronization/). You can also find such problems in other posts as well.

**Comment by Golmote** [comment]
I think this is a bug with the Line Numbers plugin, that has already been fixed. Please update your Prism version from http://prismjs.com/download.html?themes=prism&languages=markup+css+clike+javascript+c+bash+cpp+java+python&plugins=line-numbers

**Comment by wrayzheng** [comment]
It works. Thanks a lot!
