### ISSUE TITLE
C-Like Single Line Comment Regex Matches Double Slash in Strings

### ISSUE THREAD

**Issue by markcaron** [PrismJS/prism#1286]
The single line comment pattern `/(^|[^\\:])\/\/.*/` incorrectly matches the double slash in the string:

`final String rcal = "ejb:jboss-ejb-multi-server-app-main/ejb//" + ("MainAppBean") + "!" + MainApp.class.getName();`

**Comment by markcaron** [comment]
https://www.regexpal.com/?fam=102376

**Comment by Golmote** [comment]
Hi! Thanks for reporting. I don't reproduce the issue on the [test page](http://prismjs.com/test.html). Can you make sure you're using the last version of Prism please?

**Comment by markcaron** [comment]
I will update to make sure. I couldn't replicate it on the test page either. When I compared the new version with my version (which is older), the comment regex for "clike" was identical, so it appeared--to me at least--like this was still an issue.

Thanks for helping out. I'll update and test to make sure it was just me!

**Comment by Golmote** [comment]
The key difference would probably be the addition of the `greedy` key on the `string` pattern, rather than a change in the `comment` pattern. Please keep us informed if the issue is fixed.

**Comment by markcaron** [comment]
@Golmote that was the issue. Thanks for the heads up!
