### ISSUE TITLE
Bash syntax doesn't highlight commands in quoted command substitution with $()

### ISSUE THREAD

**Issue by moqmar** [PrismJS/prism#1287]
When I have e.g. `x="$(echo "y")"`, everything inside `$()` should be a completely independent command (`"y"` should be highlighted as a string).
Prism.js incorrectly highlights `"$(echo "` and `")"` as a string instead, and doesn't highlight commands inside like with `` x=`echo "y"` `` (which is working as expected).

**Comment by Golmote** [comment]
Thanks for reporting! It should be fixed now.
