### ISSUE TITLE
[Question] Support for Moodle Website

### ISSUE THREAD

**Issue by ol69130** [PrismJS/prism#1293]
Hi,

Your plugin seems to be great ! I would like implement it on our Moodle Website for sharing scripts with our developers, users... We use the last version of Moodle. The Text Editor is Atto. We already use syntaxhighlighter plugin (Prism is better) and it works fine (this is a specific moodle plugin).
My question is the Prism compatibility with Moodle ? How integrate it on this Framework (i have difficulties with this) ?
thanks !

Quentin

**Comment by Golmote** [comment]
Hi. I guess this could be made the same way the [syntaxhighlighter plugin was made](https://github.com/sharpchi/moodle-filter_syntaxhighlighter). The thing that might be tricky is that Prism does not autodetect languages.
