### ISSUE TITLE
no syntax highlighting when in a modal

### ISSUE THREAD

**Issue by eman1986** [PrismJS/prism#1299]
I'm using the bootstrap modal with prism and when in a modal, the code will not highlight.

heres an example:

https://jsfiddle.net/2uyj5ykg/5/

**Comment by Golmote** [comment]
Hi. You need to [call the highlighting manually](http://prismjs.com/extending.html#api) after your modal is open and its content is set.

https://jsfiddle.net/2uyj5ykg/12/
