### ISSUE TITLE
Unescaped Plugin breaks js, and works incorrectly in IE & Edge

### ISSUE THREAD

**Issue by aaronstezycki** [PrismJS/prism#1302]
Using the plugin to generate some pug/jade content using the unescaped plugin. 

When viewing the output on Mac OS Safari, Chrome etc the plugin works fine. However when viewing the page on Windows 10, (or lower) in IE and Edge gives a console error and breaks js on the page.

It seems to fall over element.matches. :

<img width="452" alt="screen shot 2018-02-20 at 09 35 40" src="https://user-images.githubusercontent.com/5744600/36416636-80891b82-1621-11e8-891b-e7b9570c0cc6.png">

<img width="586" alt="screen shot 2018-02-20 at 09 31 35" src="https://user-images.githubusercontent.com/5744600/36416640-85284028-1621-11e8-952c-95d27845c53d.png">

Unsure exactly why it's falling over, as I've discovered that Edge supports `matches()`.
https://caniuse.com/#search=matches

¯\_(ツ)_/¯

**Comment by Golmote** [comment]
Hi! I could not reproduce your issue on Edge 16.
But I reproduced it in IE11 and lower, where `matches` is not supported in its unprefixed form. We should probably use `msMatchesSelector` as a fallback for those browsers (IE9-11).

**Comment by aaronstezycki** [comment]
Hi @Golmote, was this issue fixed and a PR merged? I could do with this plugin working for IE. Sorry if it has 👍

**Comment by Golmote** [comment]
Hi! I fixed it in a direct commit (not a PR). It should work properly on `gh-pages` and I'll make an official this week.
