### ISSUE TITLE
Disable automatically created WebWorker message handler

### ISSUE THREAD

**Issue by mikehardenize** [PrismJS/prism#1303]
I have a web worker which looks like this:

```javascript
import Prism from 'prismjs';

self.addEventListener('message', function(event) {
    let { language, code } = event.data;
    // Do some stuff
    code = Prism.highlight(code, Prism.languages[language]);
    self.postMessage(code);
});
```

It works, however the mere act of opening Prism inside a web worker causes it to create it's own "message" handler. One which expects a `String` as input. So I'm constantly getting errors in my console like:

```
JSON.parse: unexpected character
```

I *could* just use the automatically created "message" handler, but that prevents me from doing the extra processing that I wanted to happen in my web worker.

Is there a way of disabling the automatic creation of this message handler? I can see multiple references to `disableWorkerMessageHandler` in the code, but I can't figure out a way of leveraging it. Maybe that's not even possible?

**Comment by Golmote** [comment]
You should be able to make it work with something like:

```js
var Prism = {
	disableWorkerMessageHandler: true
};
import Prism from 'prismjs';
// or self.importScripts('prism.js');
```

**Comment by mikehardenize** [comment]
This doesn't work. I get: `Module build failed: SyntaxError: "Prism" is read-only`. So I tried:

```javascript
var Prism = { disableWorkerMessageHandler: true };
import 'prismjs';
```

This also didn't work as the import doesn't merge stuff into the Prism object. So I tried:

```javascript
Prism = {
	disableWorkerMessageHandler: true,
};
import PrismLib from 'prismjs';
Prism = {
    ...PrismLib,
    ...Prism,
}
```

This also didn't work as the unwanted message handler was still created.

**Comment by mAAdhaTTah** [comment]
@Golmote You can't do it in that order, `import` statements are hoisted. If you swapped `import` for `require`, that would work if you changed `var Prism` to `global.Prism`.

@mikehardenize Are you using a bundler of some kind here?

**Comment by mikehardenize** [comment]
I'm using webpack with babel-loader. I've tried various combinations of loading the module using require and using global.Prism and it's making no difference.

**Comment by mikehardenize** [comment]
After further investigation, the existing web worker functionality is actually broken. If you `postMessage` two pieces of code for highlighting at the same'ish time, the response order is unpredictable. You don't know if the first code you get back was the first code you submitted or the second.

**Comment by tvooo** [comment]
I managed to achieve this the following way:

```js
global.Prism = { disableWorkerMessageHandler: true };
const Prismjs = require('prismjs');
```

I load the worker using webpack's `worker-loader` like this:

```js
const Worker = require('worker-loader?inline=true!./worker');

const worker = new Worker();
worker.onmessage = ...
```

Hope that helps :)

**Comment by Golmote** [comment]
@tvooo's answer looks like an appropriate solution to this problem. I'm closing this issue.

**Comment by masylum** [comment]
I'm struggling to make this work together with `vite-plugin-prism`. Did anyone successfully managed to do so?
