### ISSUE TITLE
Question: Is there a way to change the default language-xxxx

### ISSUE THREAD

**Issue by akshaybabloo** [PrismJS/prism#1312]
I am using Squarespace for hosting the website and for some reason the code block they generate has a default class `lang-` and when I put, say, `language-python` it comes out as `lang-language-python` :tired_face:. 

Is there any way I could allow prism to look at `lang-python` instead `language-python`? I know that I could just replace the class name with `language-python` buy before I start experimenting I just wanted to know this.

**Comment by benkimball** [comment]
Can you add a class name to a parent element? For example if you add `class=“language-ruby”` to your body tag, it will be inherited by any code blocks it contains.

**Comment by Golmote** [comment]
Hi! Prism does supports `lang-xxx` too. So you should be able to use `lang-python` directly!

**Comment by akshaybabloo** [comment]
@benkimball Can't do that in Squarespace, unfortunately.

@Golmote Thanks, I didn't know that. Is it documented somewhere?

**Comment by Golmote** [comment]
@akshaybabloo I don't think so... This behaviour has been here for a very long time. I traced it back to this commit https://github.com/PrismJS/prism/commit/de85c1ae7b7c1c32d730ecba1d259bb891746bbf.

I agree it should appear somewhere in the docs.
