### ISSUE TITLE
Support auto detecting language

### ISSUE THREAD

**Issue by paladox** [PrismJS/prism#1313]
Hi, could support for auto detecting the language be added please?

Also would it be possible to support this type of language

var html = Prism.highlight(code, language);

(language as in mime types php, etc).

Like highlight.js usage. As they are now unmaintained, prime.js is a better alternative but needs support for Prism.highlight(code, lanaguage); so that it auto loads the language it needs.

**Comment by uhafner** [comment]
Is there at least a mapping of file extensions to class names available? I would like to use it in an application where the actual visualized file is not known in advance.

**Comment by Golmote** [comment]
@uhafner Take a look at the [File Highlight plugin](http://prismjs.com/plugins/file-highlight/).

**Comment by uhafner** [comment]
Thanks, that did the trick!

**Comment by Golmote** [comment]
I don't get how this would solve the issue of auto-detection. AFAIK highlight.js does it by testing the code (or part of it?) with every language. Each test returns a relevance score, based on specific caracteristics of the language (mainly keywords, but also special syntaxes). Sometimes a test can return early with a relevance of 0 if it detects an invalid syntax.

This is a smart approach, but it still requires to test every language and it's something I'm not happy about it. Yet, Prism _could_ probably support this by adding these concepts (relevancy and invalid syntaxes).

**Comment by HarryCaveMan** [comment]
Trying to train some sort of statistical classifier with a training set could be a viable option. Something like [this](https://github.com/nemo/natural-synaptic) , which can just load the trained model.

**Comment by izelnakri** [comment]
Any updates on this? This would really enhance the developer experience if the code block doesn't have a language class.

**Comment by mAAdhaTTah** [comment]
Honestly, I think this is unlikely to be supported / implemented by the core team, but we'd accept a PR for a plugin.

**Comment by asbjornu** [comment]
[highlight.js](https://highlightjs.org/) supports language auto-detection. Perhaps some inspiration can be drawn from there?

**Comment by RunDevelopment** [comment]
As @Golmote said [before](https://github.com/PrismJS/prism/issues/1313#issuecomment-388634112): Highlight.js' approach while quite inefficient might be usable.

But to support illegal tokens and relevance, we would probably have to adjust every language definition.

**Comment by mAAdhaTTah** [comment]
Not gonna lie, 4 downvotes from people who want others to do work for things they want is frustrating. As stated, if this is desired, we will happily accept a PR, but we will not be implementing this.

**Comment by andrewjmead** [comment]
If you're interested, you can use the auto detect from highlight.js but then use the syntax highlighting from prism. 

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js"></script>
<script>
	document.addEventListener("DOMContentLoaded", function () {
		hljs.highlightAll();
	})
</script>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.28.0/themes/prism.min.css" integrity="sha512-tN7Ec6zAFaVSG3TpNAKtk4DOHNpSwKHxxrsiw4GHKESGPs5njn/0sMCUMl2svV4wo4BK/rCP7juYz+zx+l6oeQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.28.0/plugins/line-numbers/prism-line-numbers.min.css" integrity="sha512-cbQXwDFK7lj2Fqfkuxbo5iD1dSbLlJGXGpfTDqbggqjHJeyzx88I3rfwjS38WJag/ihH7lzuGlGHpDBymLirZQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.28.0/components/prism-core.min.js" integrity="sha512-9khQRAUBYEJDCDVP2yw3LRUQvjJ0Pjx0EShmaQjcHa6AXiOv6qHQu9lCAIR8O+/D8FtaCoJ2c0Tf9Xo7hYH01Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.28.0/plugins/autoloader/prism-autoloader.min.js" integrity="sha512-fTl/qcO1VgvKtOMApX2PdZzkziyr2stM65GYPLGuYMnuMm1z2JLJG6XVU7C/mR+E7xBUqCivykuhlzfqxXBXbg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.28.0/plugins/line-numbers/prism-line-numbers.min.js" integrity="sha512-BttltKXFyWnGZQcRWj6osIg7lbizJchuAMotOkdLxHxwt/Hyo+cl47bZU0QADg+Qt5DJwni3SbYGXeGMB5cBcw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```

**Comment by abulka** [comment]
A tip to those using the code above: ensure the two script tags involving the `highlight.js` library **precede** the prism link and script tags, just as the example shows, otherwise prism doesn't run at the correct time.

Whilst the technique works, I'm not that impressed with the `highlight.js` library's detection of  languages:
- markdown files I'm getting `language-csharp` 
- plain text files e.g. `requirements.txt` I'm getting `language-undefined`, which causes an import error `https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-undefined.min.js net::ERR_ABORTED 404`. 
- `.gitignore` I'm getting `language-bash` 
- some bash scripts I'm getting `language-css`

I'm building a file preview tool, I wish there was some way of passing the file extension which would be a massive hint as to which language to switch to.

**Comment by Nantris** [comment]
@andrewjmead that sure seems expensive on multiple levels. I don't understand why Prism can't implement a language guesser like highlight.js does.

**Comment by masylum** [comment]
I'm using https://github.com/teknologi-umum/flourite

**Comment by Ray-D-Song** [comment]
Maybe you can checkout my project.  
https://github.com/Ray-D-Song/guesslang-js  
This is a fork of guesslang, use tensorflow.js to detect code block language. I made esm and Web Worker support for it.
