### ISSUE TITLE
PowerShell namespace matching is strange when namespace contains square brackets

### ISSUE THREAD

**Issue by CoenraadS** [PrismJS/prism#1317]
Input:

```
function foo {
    [string[]]$thing 
}
```

![image](https://user-images.githubusercontent.com/5593825/36856924-826cbca8-1d77-11e8-806c-fa5e91f28616.png)

I would expect:

```
[string[]] - Namespace
```

Another example is:

`[OutputType([System.Collections.Generic.List[int]])]` => `[OutputType([System.Collections.Generic.List[int]`

**Comment by CoenraadS** [comment]
Here is a regex that matches equal []'s: `\[([^[\]]|(?R))*\]`

But I read at https://github.com/PrismJS/prism/blob/7035d4ef55c219e4ebcc5f91507f9c9be589a68a/components/prism-powershell.js#L29 something about not matching array indices

**Comment by Golmote** [comment]
Hi! Thanks for reporting. The example regexp you provide is not a feature supported by regexps in JS.

But we can surely add support for one level of nested brackets to fix this issue.

**Comment by CoenraadS** [comment]
Could two levels be added to support attributes with generic lists, i.e. `[OutputType([System.Collections.Generic.List[int]])]`

Thanks for this great project
