### ISSUE TITLE
Add support for shell

### ISSUE THREAD

**Issue by paladox** [PrismJS/prism#1320]
Hi, could support for the shell language be added please?

**Comment by Golmote** [comment]
Isn't it the same thing as `bash`?

**Comment by paladox** [comment]
@Golmote Kind of, but looking at https://github.com/isagalaev/highlight.js/blob/master/src/languages/shell.js#L14 it may have slightly different syntax for some things

So this lang could extend bash.

**Comment by paladox** [comment]
@Golmote actually, it seems it checks for #/bin/bash and /bin/sh in the bash file so i will just add shell as the alias for bash.

see https://github.com/PrismJS/prism/pull/1321

**Comment by juancampa** [comment]
@paladox, highlight's `shell` is not just `bash`. It's to highlight interactive shell sessions where commands lines start with `$`. Like so:
```bash
$ cd dir
$ ls
file1/ file2
```
If a file starts with `$` it's a bash line, otherwise, it's plain text (e.g. the output of `ls`)

**Comment by mAAdhaTTah** [comment]
@juancampa There's a [command-line](https://prismjs.com/plugins/command-line/) plugin that may suit your needs.

**Comment by whitemuu** [comment]
> @juancampa There's a [command-line](https://prismjs.com/plugins/command-line/) plugin that may suit your needs.

That looks great. The sad thing is that it can't be used in node. Still wanting a special lang named shell-session or command-line.

**Comment by FranklinYu** [comment]
@whitemuu I created an issue for it. I don’t think the plugin is a valid replacement for language definition.
