### ISSUE TITLE
Compatibility to bulma.io css framework

### ISSUE THREAD

**Issue by fahu** [PrismJS/prism#1324]
At the moment, both prism and Bulma are using the same CSS class 'number'. This causes that numbers within a code block are displayed wrong formatted.

I think the number class should be renamed to something less generic or a prefix should be added to the class (e.g.: prism-number).

Quick fix for bulma.io users with jQuery:
```
    $( document ).ready(function() {
        removeNumberClassFromCode();
    });

    function removeNumberClassFromCode() {
        $('.token').each(function () {
            $(this).removeClass('number');
        });
    }
```

**Comment by Golmote** [comment]
Hi!
We do have [a plugin](http://prismjs.com/plugins/custom-class/) to add prefix to all classes added on tokens. You'll have to change the theme's stylesheet yourself, though.
