### ISSUE TITLE
Scheme systax mark first argument as function even it's list with numbers

### ISSUE THREAD

**Issue by jcubic** [PrismJS/prism#1331]
If you defined sheme code like this:

```
'(1 2 3)
```

or

```
(defmacro (foo x) `(1 2 ,@(car x) 3 4))
```

prism is showing 1 in different color, you can see the issue on this page https://jcubic.github.io/lips/docs.html

**Comment by Golmote** [comment]
Thanks for reporting! Should be fixed now.

**Comment by jcubic** [comment]
Thanks, just going through GitHub notifications in my spam folder.
