### ISSUE TITLE
Doesn't recoganize jsx in attribute value

### ISSUE THREAD

**Issue by supnate** [PrismJS/prism#1333]
For example, below jsx element is not correctly parsed:
```
<CodeView title={<h1>Title</h1>}>for of as</CodeView>
```
See below for the parsed tokens:
![image](https://user-images.githubusercontent.com/481738/37038142-f6735560-218e-11e8-8cba-f91c4b89be85.png)

**Comment by Golmote** [comment]
Hi! Thanks for reporting. This was fixed in https://github.com/PrismJS/prism/commit/05bf67dc45422d45ee8e4a364a7761ad2d2dddee when investigating https://github.com/PrismJS/prism/issues/1335.

**Comment by supnate** [comment]
Thanks for the quick fix! I will verify it soon.
