### ISSUE TITLE
JSX: Certain inline expressions containing curly braces don't parse correctly

### ISSUE THREAD

**Issue by ericgio** [PrismJS/prism#1335]
It looks like the JSX parser breaks when it encounters curly braces inside an inline function. This is true even if the braces are commented out.

#### Repro code:
```jsx
<Button onClick={(e) => this.setState({clicked: true})}>
  Click Me!
</Button>
```

#### Screenshot from test page:
![image](https://user-images.githubusercontent.com/2978513/37062080-48a404dc-214a-11e8-89ae-b67dadaad6c2.png)

**Comment by ericgio** [comment]
Other examples:

#### Passing an array of objects
```jsx
<Component
  data={[
    {id: 0, name: 'Joe'},
    {id: 1, name: 'Sue'},
  ]}
/>
```

![image](https://user-images.githubusercontent.com/2978513/37062953-c8bac794-214c-11e8-9b68-47962b4319d2.png)

#### Template literals (in some cases)
```jsx
// This works
<Component title={`${name}`} />

// This does not
<Component title={`${name}'s page`} />
```

![image](https://user-images.githubusercontent.com/2978513/37063196-77317f3e-214d-11e8-99fd-b9d1f24ddfa5.png)

**Comment by Golmote** [comment]
Thanks for reporting! Should be fixed now.
