### ISSUE TITLE
Javascript // comments are not greedy

### ISSUE THREAD

**Issue by CoenraadS** [PrismJS/prism#1337]
```
if (1 == 1) {
    // gulp.watch('./src/**/*.js', ['move']); 
}
```

It stops the comment after `*/`

![image](https://user-images.githubusercontent.com/5593825/37076832-7359a73e-21d8-11e8-93c7-d3aa475b8795.png)

It is getting confused by `/**/` inside of `//`

**Comment by CoenraadS** [comment]
I wonder if the solution is as simple as flipping the order of this array: https://github.com/PrismJS/prism/blob/gh-pages/components/prism-clike.js#L2-L11

Because the second one works fine, so if it was parsed first maybe the problem would be resolved.

**Comment by CoenraadS** [comment]
I really appreciate your work man!

**Comment by Golmote** [comment]
Happy to help when I can! ;)

**Comment by Golmote** [comment]
I reverted cebacdfa195b298ee6046e4d6a5c06058cb54090. Because the use-case for single line comment inside multi-line comment is more common than the opposite.

At the moment, we can't have both this and #1340. So we'll stick with the previous behaviour for now, while I try to find a way.

**Comment by Golmote** [comment]
Hopefully both will stay fixed now!
