### ISSUE TITLE
// comment inside /* */ comment breaks parsing for javascript

### ISSUE THREAD

**Issue by CoenraadS** [PrismJS/prism#1340]
Using v1.12.0

Language javascript:

```
/*
 * ([{}]) 
 * //  <= double slash comment
 * ([{}]) <= punctuation
 */
```

**Comment by Golmote** [comment]
I reverted cebacdfa195b298ee6046e4d6a5c06058cb54090 to fix this issue. Because the use-case for single line comment inside multi-line comment is more common than the opposite.
