### ISSUE TITLE
Switch on travis ci on prism

### ISSUE THREAD

**Issue by paladox** [PrismJS/prism#1341]
Hi, we have the travis ci file, but i doint see any tests ran (nothing is ran on travis when creating pulls either).

https://docs.travis-ci.com/user/getting-started/

**Comment by paladox** [comment]
https://docs.travis-ci.com/user/getting-started/

**Comment by Golmote** [comment]
CI tests only occur when `master` branch is updated and when tags are pushed (i.e. a new release is made).

**Comment by paladox** [comment]
hmm, should we also enable it on the gh-pages branch?

**Comment by Golmote** [comment]
Ah, you're right, the PR I was looking at was for the master branch.

So I guess we could [add the `gh-pages` branch explicitely](https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches). Since
> By default, the gh-pages branch is not built unless you add it to the safelist.

As long as we don't change the deployment rules, it should be ok.

**Comment by paladox** [comment]
Thank you :)
