### ISSUE TITLE
Nested script inside jsx tag is not parsed

### ISSUE THREAD

**Issue by supnate** [PrismJS/prism#1342]
```javascript
<CodeView title={<span title={123}>2</span>}>for of as</CodeView>
```
![image](https://user-images.githubusercontent.com/481738/37189397-1f0f3bb8-238f-11e8-84a1-ebbecaa07d5b.png)

**Comment by Golmote** [comment]
Hi! Thanks for reporting.
I don't think we're gonna fix this one, though. Prism can't (at the moment anyway) handle infinitely deep recursions of patterns.

We might handle it at some point, but this is really not on agenda for the near future.

**Comment by supnate** [comment]
That's fine. Thanks.

**Comment by Golmote** [comment]
I reopen this issue, since it _should_ actually be fixable.

**Comment by supnate** [comment]
Thanks @Golmote ! Can't wait to try it!

**Comment by supnate** [comment]
By the way, just for your information, I'm using prismjs for syntax highlighting with Monaco Editor. See the live demo at: http://demo.rekit.org/element/src%2Ffeatures%2Fcommon%2Fmonaco%2Fworkers%2FsyntaxHighlighter.js/code .  Did some job on finding jsx text elements.

**Comment by Golmote** [comment]
I accidently closed the issue when #1345 was merged. But it was actually fixed in the next commit (cc80ccda8a2ec5565750ce67a2135b109748b5cd). A test for this specific use case was added in f0e6249e4f4417a7497792c0b9b8fcd133e9564e.

So it should be fixed now! :tada: 

Note that we probably still won't be able to handle infinite recursion (since JS regexps are not recursive), but at least this use case is handled!

**Comment by Golmote** [comment]
> By the way, just for your information, I'm using prismjs for syntax highlighting with Monaco Editor. See the live demo at: http://demo.rekit.org/element/src%2Ffeatures%2Fcommon%2Fmonaco%2Fworkers%2FsyntaxHighlighter.js/code . Did some job on finding jsx text elements.

You mean to handle plain text (#1304 and #1294)? That's interesting! Unfortunately, this looks too complicated to be included in Prism like this... I'd love to find a lighter solution to this issue.

**Comment by supnate** [comment]
Yes exactly! Both for the problem and code complication.. Hope it would be resolved from prismjs side finally some day!

Thanks for your effort on making such a  great tool!
