### ISSUE TITLE
Line numbers aren't showing when <pre> is hidden by default

### ISSUE THREAD

**Issue by slz** [PrismJS/prism#1343]
I'm using prism to format source code for a quiz, and I hide the code until a button is pressed to check the answer.

When the code is hidden through CSS by default (with display: none), the line numbers don't show when the code is made visible. It works fine if the &lt;pre&gt; blocks aren't hidden during page load.

Edit:
I got it working by calling: Prism.highlightAllUnder(answer) after the code is made visible.

However, it would be nice if this wasn't necessary. Thanks for the great plugin either way.

**Comment by Golmote** [comment]
Hi! Indeed, the Line numbers plugin, only when used with line wrapping, requires the code block to be visible (or at least to have dimensions) so the height for each line can be computed. In your case, rehighlighting manually seems to be the appropriate solution.
