### ISSUE TITLE
Highlight class name in java

### ISSUE THREAD

**Issue by paladox** [PrismJS/prism#1346]
Hi, in java it dosent seem to highlight the class name or the one after extends too

<img width="723" alt="screen shot 2018-03-11 at 19 39 30" src="https://user-images.githubusercontent.com/5727000/37257628-f60f43c6-2563-11e8-9f84-338089046ef0.png">

See ^^

**Comment by Golmote** [comment]
I think it's tokenized, but no theme handle it. You should try adding a CSS rule for `.token.class-name` to add the styling you want to them.

**Comment by paladox** [comment]
I wonder what a good colour would be to use for this? :)

**Comment by Golmote** [comment]
The same as the `function` names should be fine. In the default theme, that's `#DD4A68`.

**Comment by paladox** [comment]
thank you :). I will create a patch to add that to prism.css
