### ISSUE TITLE
Token operator should not have a background

### ISSUE THREAD

**Issue by paladox** [PrismJS/prism#1347]
Like the other tokens, token operator should not have a background, make things look a little wierd.

<img width="677" alt="screen shot 2018-03-11 at 22 48 44" src="https://user-images.githubusercontent.com/5727000/37259452-6056a228-257e-11e8-9d74-82019cbe8c43.png">

See ^^

**Comment by Golmote** [comment]
Since you decided to change the background color of the theme, you should probably change or remove the background color of the operators, indeed.

This is ok as part of the original theme, tho.

**Comment by paladox** [comment]
I didn't change the colour of it though :)

**Comment by Golmote** [comment]
The background color of the code block, I meant. This greenish background isn't the original background of the default theme is it?

**Comment by paladox** [comment]
Ah i see, yeh.

**Comment by Golmote** [comment]
So I consider you did some customization, and so you might also need to customize more to make it look less weird.

**Comment by paladox** [comment]
Yeh, we are using the highlight function so it dosen't implement the language-<lang> class. (well not really we are as i am trying to implement this in gerrit https://gerrit-review.googlesource.com/c/gerrit/+/160034/ but need #1325 to be resolved :))

**Comment by paladox** [comment]
@Golmote im wondering if we could remove it offically from the token or is it needed?

**Comment by Golmote** [comment]
IMO no we should not. It looks good on the theme and the author did it like this, I won't discuss it.
This is theme customization, and theme customization should be in your own CSS.
