### ISSUE TITLE
in java highlight text within <> as a  class

### ISSUE THREAD

**Issue by paladox** [PrismJS/prism#1351]
Hi, would we be able to update the regex to highlight within <> as a class please?

```java
public class AllChangesIndexer extends SiteIndexer<Change.Id, ChangeData, ChangeIndex> {
```

AllChangesIndexer is highlighted as a class and SiteIndexer too, but <Change.Id, ChangeData, ChangeIndex> is not.

**Comment by Golmote** [comment]
Thanks for reporting.
