### ISSUE TITLE
When using markup mode it should also highlight php code

### ISSUE THREAD

**Issue by paladox** [PrismJS/prism#1352]
in highlight.js it highlights php code in html, but in prism.js it dosen't.

Reference https://github.com/isagalaev/highlight.js/blob/master/src/languages/xml.js#L60

Tested here http://prismjs.com/test.html using markup mode

example code is

```php
<?php

echo "test";
```

**Comment by Golmote** [comment]
In Prism, you _have_ to use the PHP component to highlight PHP in Markup. Please remember that Prism is not HighlightJS and that we have no intention to align perfectly the behaviours of the two libraries.
