### ISSUE TITLE
JSX tag is not recognized if attribute value starts with "//"

### ISSUE THREAD

**Issue by supnate** [PrismJS/prism#1356]
Below jsx code is not recognized as a tag, it seems attribute value can't start with "//":
```
<a href="//localhost">link</a>
```
![image](https://user-images.githubusercontent.com/481738/37420548-fd74d21c-27f1-11e8-8904-011daac21f57.png)

**Comment by Golmote** [comment]
Thanks for reporting! Should be fixed now.
