### ISSUE TITLE
Wrong highlighting on PHP strings with simple comma

### ISSUE THREAD

**Issue by Karmac** [PrismJS/prism#136]
Hi!

There's another bug on PHP. When working with simple commas and HTML strings don't get highlighted as expected. I attach two images showing the problem:

![](http://s23.postimg.org/tf1ojcmpn/Captura_de_pantalla_2013_07_13_a_la_s_17_08_04.png)

![](http://s12.postimg.org/rnge17b8d/Captura_de_pantalla_2013_07_13_a_la_s_17_08_16.png)

PS: the second image could be right (I don't know how it was designed), but the first one must be a bug because the interpolated variable doesn't get highlighted.

Thanks really much for your help. I really appreciate you offer such a beautiful solution for syntax highlighting.

**Comment by javatlacati** [comment]
@Karmac Can u provide a fiddle to test further into my [Fiddle](http://jsfiddle.net/javatlacati/jby1afc2/)?

**Comment by apfelbox** [comment]
@javatlacati did you notice that you are gravedigging this thread? I think in the last two years a lot has changed. :wink:

**Comment by Golmote** [comment]
The behaviour of the php component must not have changed that much, though. =/

**Comment by javatlacati** [comment]
@apfelbox code still made the highlighting process crash I'd like to close all bugs either old or new. Cheers

**Comment by foo123** [comment]
Check [prism-grammar](https://github.com/foo123/prism-grammar) external parsing add-on for Prism, which uses a grammar to highlight solving all these issues (and more)

**Comment by Golmote** [comment]
I think the greedy feature (#779) and/or its improvement (#967) fixed this issue. Both codes in the first message now highlight properly.
