### ISSUE TITLE
How to automatically add language support

### ISSUE THREAD

**Issue by wdao7** [PrismJS/prism#1362]
The HTML code I returned from the compiler like this：
![qq 20180321193108](https://user-images.githubusercontent.com/34474826/37707589-9c9bc5b6-2d3e-11e8-9226-639297105256.png)
How can I distinguish them？And add them to the corresponding class in  tag  'pre' or 'code'

**Comment by Golmote** [comment]
At the moment there is no auto-detection of the language. This feature has been asked already in issue #1313.

You have to set the right class yourself.
