### ISSUE TITLE
highlight "if @test" in erb syntax

### ISSUE THREAD

**Issue by paladox** [PrismJS/prism#1363]
Hi, please could "if @test" be highlighted? <% and %> is highlighted but "if @test" is not.

**Comment by Golmote** [comment]
Can you provide more details about this? Do you reproduce the issue on the [Test page](http://prismjs.com/test.html)?

![b26zqtl](https://user-images.githubusercontent.com/565460/37756062-56cefd0e-2da8-11e8-8bd8-bac75ddd64cd.png)

**Comment by Golmote** [comment]
Are you using the `highlight()` function directly? Could this be related to https://github.com/PrismJS/prism/pull/1367 ?

**Comment by paladox** [comment]
ah, yes i am using highlight() directly (sorry for late reply) and possibly yes that one.

**Comment by paladox** [comment]
@Golmote yep, i wrote this https://codepen.io/anon/pen/EEvyXj

**Comment by Golmote** [comment]
@paladox Ruby needs to be included before ERB: https://codepen.io/anon/pen/eMEgNo

So I confirm this will be fixed by #1367 when it's merged.

**Comment by paladox** [comment]
ah thanks, that works.

**Comment by Golmote** [comment]
#1367 is now merged, so this issue should be fixed. Thanks for reporting!
