### ISSUE TITLE
C# classes not properly highlighted

### ISSUE THREAD

**Issue by maulwuff** [PrismJS/prism#1365]
Class names in parameters and base classes are not hightlighted, nor tokenized for C#
![grafik](https://user-images.githubusercontent.com/4960210/37829707-5ef22904-2ea0-11e8-93b4-f759cda9aa4a.png)

"SomeClass" and "BaseClass" should be colored, too. In Html output I see, that they are not put into spans. 

The example code
```
interface ILogger {
    void Init(SomeClass file); 
	void LogInfo(string message);
}
public class SomeClass : BaseClass {}
```

**Comment by Golmote** [comment]
Hi! Thanks for reporting.

We currently match class names based on the preceding keyword (`class`, `interface`, etc.).
Are class names mandatorily capitalized in C#? Would this a viable enough way to match them?

**Comment by Golmote** [comment]
Should be fixed now!
