### ISSUE TITLE
global.Prism causes conflict between PrismJs versions

### ISSUE THREAD

**Issue by CoenraadS** [PrismJS/prism#1366]
Hi

My vscode extension is using `PrismJs ^1.13.0`, while another extension is using `PrismJs ^1.6.0`.

Unfortunately they cannot run together, due to the global.Prism hack

**Comment by CoenraadS** [comment]
I fixed it by loading prism inside the class rather then globally, will close this issue since its an edge case

**Comment by Golmote** [comment]
Hi. We are aware of this issue. Unfortunately, this won't likely be fixed before the next major release of Prism, since this would be quite BC breaking. Refer to https://github.com/PrismJS/prism/issues/470 for a temporary "wrapper" solution that might fit your need.
