### ISSUE TITLE
Upload prism 1.13.0 to cdnjs

### ISSUE THREAD

**Issue by paladox** [PrismJS/prism#1368]
Hi, when going to https://cdnjs.cloudflare.com/ajax/libs/prism/1.13.0/components/prism-javascript.js it is throwing 404 but there was a release a few days ago

please could you upload it to cdnjs?

**Comment by paladox** [comment]
Seems someone did it, thanks.

**Comment by Golmote** [comment]
AFAIK, this is automatic. I don't know the update frequency though.
