### ISSUE TITLE
Cannot read property 'tokenizePlaceholders' of undefined

### ISSUE THREAD

**Issue by wispyoureyes** [PrismJS/prism#1395]
Hi！I used to  highlight python codes in my web pages, but recently there apears an error like the following screenshoot shows
![image](https://user-images.githubusercontent.com/22863222/38808515-16a20c7a-41b3-11e8-8224-fe2ddbdee3b5.png)
I've no idea about this error, could you do me a favor?

**Comment by Golmote** [comment]
The dependency for PHP has changed in https://github.com/PrismJS/prism/pull/1367. You need to include the component `markup-templating` in addition to `c-like` (and probably `markup` depending on your use case).

**Comment by wispyoureyes** [comment]
Ah, it worked! Thanks a lot!
