### ISSUE TITLE
loadLanguages utility causes bloat with webpack

### ISSUE THREAD

**Issue by brian-kephart** [PrismJS/prism#1403]
I'm seeing lots of bloat when using the `loadLanguages` utility in webpack.

~30k:
```js
var Prism = require ('prismjs')
require('prismjs/components/prism-ruby')
```
~755k:
```js
var Prism = require ('prismjs')
var loadLanguages = require('prismjs/components/index')
loadLanguages(['ruby'])
```

Numbers are in development mode, non-gzipped. I checked a couple other languages to make sure it wasn't a dependency loading issue with `prism-ruby.js`, but results were similar with other languages.

**Comment by mAAdhaTTah** [comment]
`loadLanguages` is intended for using in Node specifically. We should probably make this clear in the documentation. It imports dynamically, so Webpack sees that as "import everything that could possibly go here", which is all the languages.

I don't know as we have a good "story" for bundlers, tbh. Maybe a babel plugin?

**Comment by Golmote** [comment]
For future reference, see related #1409.

**Comment by HarryCaveMan** [comment]
Would loading a few dependencies up front and then using ynamic imports to specific files possibly avert this bloat? Something like this:
    import Prism from "prismjs/components/prism-core";
    //other languages depend on these
    import "prismjs/components/prism-clike";
    import "prismjs/components/prism-c";
    import "prismjs/components/prism-java";
    //include javascript as default fallback
    import "prismjs/components/prism-javascript";
    .
    .
    .
    //try to load prism component for language
    import("prismjs/components/prism-"+props.language);

**Comment by Golmote** [comment]
The dependency graph can be inferred from the data from [`components.js`](https://github.com/PrismJS/prism/blob/gh-pages/components.js) or [`components.json`](https://github.com/PrismJS/prism/blob/gh-pages/components.json). Here is a quick'n'dirty example of the dependency graph in latest release 1.14: https://codepen.io/anon/pen/mLKqPN Note that this does not take "peer dependencies" into account (discussed in #1393).

**Comment by mAAdhaTTah** [comment]
Just to be clear, to anyone who wants to pick this up, the "good first issue" here is to add documentation.

**Comment by mAAdhaTTah** [comment]
The babel plugin is ready here: https://www.npmjs.com/package/babel-plugin-prismjs
