### ISSUE TITLE
Support for Solidity?

### ISSUE THREAD

**Issue by twleung** [PrismJS/prism#1404]
It would be great to have support for solidity... https://solidity.readthedocs.io/en/v0.4.23/

**Comment by Fi1osof** [comment]
Any progress?

**Comment by mAAdhaTTah** [comment]
Open PR for Solidity is here: #1406 – it currently requires changes if you want to pick it up.

**Comment by Fi1osof** [comment]
Run gulp
AssertionError [ERR_ASSERTION]: Task function must be specified
Have no this error on master branch.
