### ISSUE TITLE
Problem highlighting Eiffel when using "[ and ]" within quoted strings

### ISSUE THREAD

**Issue by finnianr** [PrismJS/prism#1414]
PrismJS is getting confused highlighting this particular Eiffel class
[CLASS_DESCENDANTS_COMMAND](http://www.eiffel-loop.com/tool/eiffel/source/command/class_descendants_command.html). See line containing "file_out.put_lines". It has something to do with the special meaning of "\[ and \]" which indicate an unescaped string manifest, similar to Pythons triple quoted strings. But in this class I am actually outputting these characters to a file.

**Comment by Golmote** [comment]
Hi, thanks for reporting.

Can you reproduce the issue on the [Test page](http://prismjs.com/test.html) ? I couldn't so you might just need to upgrade Prism to the latest version.

**Comment by finnianr** [comment]
It seems I was using an out of date version of one of prism.css or prism.js. I installed the latest versions and the problem went away.
