### ISSUE TITLE
Line Numbers Plugin Not Working

### ISSUE THREAD

**Issue by neilchaudhuri** [PrismJS/prism#1420]
I have downloaded a Prism bundle with Scala language support and the Copy-to-Clipboard and Line Numbers plugins. The first plugin works; the second doesn't. It is quite possible I am doing something silly, so here is a [JSFiddle](https://jsfiddle.net/neilac333/0474cdhd/) to look at.

Thanks.

**Comment by neilchaudhuri** [comment]
I'm actually not using `data-src` in my real code, but all the examples used it, so I thought I'd try it on the JSFiddle. Also, I know I was mixing code types, but since I was using `data-src`, I needed a publicly available resource. I didn't think the plugin would know the difference between JS and Scala to any degree relevant to this question.

Anyway, your response and further experimentation showed me that it is a loading issue. What I didn't mention is that I am doing all this in the context of a [Reveal.JS presentation](https://github.com/hakimel/reveal.js). I am loading Prism in a fairly obvious way:

```
$( document ).ready(function() {
                Reveal.initialize({
                    dependencies: [
                        {
                            src: 'https://s3.amazonaws.com/com.vidyasource.spark-online/js/prism.min.js',
                            async: true,
                            callback: function () {
                                Prism.highlightAll();
                            }
                        }
                    ]
                });
            });
```

This highlights the code, and the Copy-to-Clipboard works. Line Numbers doesn't. What do I need to do here?

**Comment by Golmote** [comment]
> I didn't think the plugin would know the difference between JS and Scala to any degree relevant to this question.

It does not (in that case).

So, I managed to reproduce the issue on JSFiddle with an example actually using Reveal.JS.

AFAICT, the line numbers are not visible, due to some styles Reveal.JS adds on `<code>` elements. You can easily override them to make the numbers reappear:

```css
.reveal pre.line-numbers > code {
  overflow: visible;
  padding: 0;
}
```

See example: https://jsfiddle.net/d3L2ro9e/

**Comment by neilchaudhuri** [comment]
That is indeed the issue--not a loading problem but rather a hiding problem. Thanks for the help.
