### ISSUE TITLE
Whitespace Normalizer doesn't do anything if there is no whitespace after code element.

### ISSUE THREAD

**Issue by hades200082** [PrismJS/prism#1425]
My code block:

```
        <pre class="language-csharp"><code>class MyTestClass
            {
                public void Execute()
                {
                    var test = true;
                }
            }
        </code></pre>
```

Note the tabs before the majority of the code. This gets rendered like this:

```cs
class MyTestClass
            {
                public void Execute()
                {
                    var test = true;
                }
            }
```

I would expect it to be rendered like this:

```cs
class MyTestClass
{
    public void Execute()
    {
        var test = true;
    }
}
```

This renders as expected:

```
        <pre class="language-csharp"><code>
            class MyTestClass
            {
                public void Execute()
                {
                    var test = true;
                }
            }
        </code></pre>
```

It seems that a newline is required immediately after the `<code>` tag in order to trigger the plugin.

**Comment by Golmote** [comment]
Hi, thanks for reporting. I understand your use case, yet I'm not sure this can be considered a bug.

In your first example, the first line is not indented at all, so this will be the starting reference for the plugin... Since your lowest indentation is 0, it will consider everything is indented correctly.

Note that this plugin does not provide automatic indentation, it can only remove extra indentation applied to the whole code. Yet again, your first line has no extra indentation...

**Comment by DM2489** [comment]
I've just spent hours trying to get this to work, only to find out here that it doesn't provide indentation!

Is there any way to automatically indent?

**Comment by hades200082** [comment]
@DM2489 That's exactly why I reported it.

I understand now though that it might be semantically outside the scope of this plugin. It would be nice to have a "pretty print" plugin however that did this.

**Comment by mAAdhaTTah** [comment]
We're open to PRs, if you want to attempt it, but I suspect writing a "pretty-printer" that works for all the languages we have is going to be impossible.

**Comment by mAAdhaTTah** [comment]
I have no idea, I didn't write it, sorry. That said, it's Hacktoberfest, so I'd encourage you to take a stab at it!

**Comment by DM2489** [comment]
HTML/XML markup shouldn't be too difficult. Other languages such as JS of C# will be much harder.

**Comment by hades200082** [comment]
@DM2489 Do you think this would work for all languages...

Compare first and last line, if indent of last line is greater than that of first line adjust all lines except first by the negative difference.

Then pass the result to the rest of the process this plugin uses.

**Comment by DM2489** [comment]
Maybe in  some cases that could work.
My use case would be using it programatically in JavaScript, parsing large
strings, which would be much more complicated.
