### ISSUE TITLE
[language-support] Add support for `ObjectPascal`

### ISSUE THREAD

**Issue by pakLebah** [PrismJS/prism#1426]
I know PrismJS already supports Pascal language. However, modern Pascal language –that's being used by [Delphi](http://embarcadero.com/products/delphi), [Free Pascal](http://freepascal.org/), [Oxygene](http://elementscompiler.com/elements/oxygene/default.aspx), etc– tend to call itself as [Object Pascal](https://en.wikipedia.org/wiki/Object_Pascal), instead of just simple [Pascal](https://en.wikipedia.org/wiki/Pascal_(programming_language)). Because the latter is mostly known as and associated to the old school Wirth's Pascal of the 70's.

So, I propose either PrismJS renames its `Pascal` language into `ObjectPascal`, or create a duplicate of `Pascal` language and name it as `ObjectPascal`.

Why the name is important? Because I'm using VS Code to write Object Pascal programs with [OmniPascal](https://marketplace.visualstudio.com/items?itemName=Wosi.omnipascal) extension. I'm also using [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) extension. The problem is… OmniPascal extension only supports `ObjectPascal` language, while Bracket Pair extension only support `Pascal` language. Bracket Pair extension is using PrismJS as [its language definition tool](https://github.com/CoenraadS/BracketPair#user-defined-matching-characters), so I have to ask PrismJS if I want Bracket Pair extension to [support a new language](https://github.com/CoenraadS/BracketPair/issues?utf8=✓&q=is%3Aissue+label%3A%22unsupported+language+by+prismJs%22+). 

Yes, I know it's a bit complicated relationship that I have to live on if I want to write Object Pascal programs using those extensions. Hopefully you'll understand.

Thank you. 😊

**Comment by Golmote** [comment]
Hi! Thanks for reporting.

If we were to add `ObjectPascal` to Prism, it would be added as an `alias` to the `pascal` component, along with `TurboPascal` and `FreePascal`. But I'm not even sure Bracket Pair Colorizer can use aliases at the moment, seeing it already has custom language name associations: https://github.com/CoenraadS/BracketPair/blob/master/src/documentDecorationManager.ts#L129

It appears that @CoenraadS already had to deal with language name mappings for its extension in the past (https://github.com/CoenraadS/BracketPair/issues/99, https://github.com/CoenraadS/BracketPair/issues/128, https://github.com/CoenraadS/BracketPair/issues/131...). Maybe this issue should be fixed the same way here. Thoughts, @CoenraadS?

**Comment by CoenraadS** [comment]
Is there a better way? I would like to be able to pass an alias to the loadLanguages function and have it choose the correct parameters, so I don't have to do so myself.

**Comment by pakLebah** [comment]
@Golmote: The language are `Pascal` (the classic one) and `ObjectPascal` (the modern one). `Delphi`, `TurboPascal`, `FreePascal`, and `Oxygene` are the names of compilers that implement Pascal language in various dialects. Along with those popular Pascal compilers, there are many other Pascal compilers out there with its own dialect e.g. NewPascal, Turbo51, PascalABC, etc. but even those are still using either `Pascal` or `ObjectPascal` language. So, PrismJS should only support `Pascal` and `ObjectPascal`, not the compiler names.

**Comment by Golmote** [comment]
@CoenraadS I think `loadLanguages` can't work with aliases at the moment. But it definitely could, so I just created #1427. Yet, I don't know if Prism would add all the aliases you defined in your `getPrismLanguageID` function (like `scad` or `apex` which seem to be actual languages, even if they might look like existing ones, or `javascriptreact` and `typescriptreact` which are really weird names for JSX and TSX IMO).

@pakLebah You seem to know your stuff, so i'll trust you on this ^^. We could then add only `objectpascal` as an alias to the `pascal` component.

**Comment by mAAdhaTTah** [comment]
@Golmote You've added ObjectPascal as an alias for Pascal. Is there any other action item here?

**Comment by Golmote** [comment]
@mAAdhaTTah Yes, we need to make `loadLanguages()` work with aliases.

**Comment by mAAdhaTTah** [comment]
@Golmote Can we close this one in favor of #1427?

**Comment by Golmote** [comment]
We can.

**Comment by shaunroselt** [comment]
Maybe add an alias for 'Delphi' also?

**Comment by RunDevelopment** [comment]
@shaunroselt As [@pakLebah pointed out](https://github.com/PrismJS/prism/issues/1426#issuecomment-391612171): Delphi is merely the name of a compiler for a Pascal/ObjectPascal dialect and therefore shouldn't be classified as its own language.
