### ISSUE TITLE
`loadLanguages()` should work with aliases

### ISSUE THREAD

**Issue by Golmote** [PrismJS/prism#1427]
The `loadLanguages()` function defined in [`components/index.js`](https://github.com/PrismJS/prism/blob/gh-pages/components/index.js) should resolve aliases.

```js
loadLanguages('js');
```

**Comment by mAAdhaTTah** [comment]
Also, I think implementing that logic would be easier if the aliases were keyed in `components.js`, so we would add `"js": { "alias": "javascript" }` and then we know to go look at `"javascript": { ... }` for details.

**Comment by Golmote** [comment]
You're very welcome to start a PR if you want 😉
