### ISSUE TITLE
Invalid JS object highlighting

### ISSUE THREAD

**Issue by kvz** [PrismJS/prism#1428]
It appears that this JS object isn't correctly highlighted:

```js
nonmute_video_filtered: {
  use: [':original'],
  robot: '/file/filter',
  condition_type: 'and',
  declines: [['${file.meta.video_codec}','!=', '],['${file.meta.audio_codec}','=', ']],
  error_on_decline: false,
}
```

See:

![](https://cl.ly/171l3926003T/Image%202018-05-25%20at%201.14.20%20pm.png)

**Comment by mAAdhaTTah** [comment]
This isn't a highlighting but, but a code bug. This:

```
['${file.meta.video_codec}','!=', ']
```

The last element in the array is missing a closing quote. So the highlighter is treating `'],['` as a string. If you run this, it would error.

**Comment by kvz** [comment]
Oops!! Very sorry about wasting your time!!
