### ISSUE TITLE
php single quote issue

### ISSUE THREAD

**Issue by CoenraadS** [PrismJS/prism#1431]
```
if ($sysType == '') {
  return $c['view']->render($response->withStatus(404), '/error/404.php', [
    "myMagic" => "Let's roll"
  ]);
} else {
  return $c['response']
        ->withStatus(404)
        ->withHeader('Content-Type', 'text/html')
                                                ^ no punctuation token
        ->write('Page not found!');
}
```

Note the single quote in `Let's roll` affects `'text/html')` later on

`Let's roll` 
![image](https://user-images.githubusercontent.com/5593825/40626669-551b502e-62ba-11e8-8267-e710c4f2777c.png)

`Lets roll`  (no apostrophe)
![image](https://user-images.githubusercontent.com/5593825/40626685-6fcab194-62ba-11e8-880a-1a02f37edd1e.png)

**Comment by RunDevelopment** [comment]
Fixed by #2032.
