### ISSUE TITLE
Prism.languages['markup-template'] is undefined in 1.14.0

### ISSUE THREAD

**Issue by carlovirtucio** [PrismJS/prism#1432]
1. Run `create-react-app`
2. Add `prismjs` v1.14.0 to dependencies
3. Import `prismjs` in App.js
4. Try outputting if `Prism.languages['markup-template']` exists

Issue:
`Prism.languages['markup-template']` is undefined even though it is being accessed in `prism-php.js`

Test repo:
https://github.com/carlovirtucio/prismjs-bug-test

This is being used in `prism-php.js`, which was somehow being used when I generate code snippets in a proprietary project I'm working on. I can't share the code so I made the simple test app. For Prism JS v1.14.0, this causes a crash in **line 121** of `prism-php.js`

**Comment by mAAdhaTTah** [comment]
The PHP language has a dependency on `markup-templating`, which you'd previously have to import manually. However, I recently put together a [babel plugin](https://github.com/mAAdhaTTah/babel-plugin-prismjs) to manage these internal dependencies for you. If you're using `create-react-app`, you should be able to use it pretty easily. Check out the documentation and open up any issues you find on that repo.

**Comment by fulopattila122** [comment]
For those who are also having difficulties figuring out how to actually import `markup-templating`, the correct syntax is:

```js
import 'prismjs/components/prism-markup-templating';
```
