### ISSUE TITLE
Question: plugin in a separate file?

### ISSUE THREAD

**Issue by Darker** [PrismJS/prism#1433]
I downloaded Prism but now I realize I need one of the plugins. But I don't remember what did I exactly check when downloading Prism for the first time. Why can't I get the plugin as a separate file? Why don't you link to plugin's repositories?

**Comment by mAAdhaTTah** [comment]
The prism.js file you downloaded should have a link to the download page with the options you selected preconfigured. The link is in a comment at the top of the file.

Plugins can be found [in this repository](https://github.com/PrismJS/prism/tree/gh-pages/plugins). You can download them and include them as separate files if you choose; they will work fine that way.

All the plugins are in this repository, so there isn't another repository to link to. We try to make the download page the easiest way to get Prism, which includes bundling it into a single JS file. The download link the file you downloaded makes it easy to add additional plugins to your bundle, so there's not really a need to link to the plugins separately.

Going to close, as there isn't an issue to address here, but feel free to ask additional questions if you need.
