### ISSUE TITLE
Allow copy-to-clipboard texts to be translated

### ISSUE THREAD

**Issue by mAAdhaTTah** [PrismJS/prism#1438]
The [Copy to clipboard](https://prismjs.com/plugins/copy-to-clipboard/) plugin can show 3 _English_ messages to the user. There is no way to replace these messages with localized versions right now.

The goal of this issue is to add a mechanism to allow these messages to be translated.

---

See #1307 for details / approach.

**Comment by edukisto** [comment]
I’ve made a tweaked version of `copy-to-clipboard`, which uses [this approach](https://github.com/PrismJS/prism/blob/master/prism.js#L167-L175) to inherit a couple of `data-` attributes for localization. Of course, I can combine all these `data-` attributes into one and implement [LeaVerou’s idea](https://github.com/PrismJS/prism/pull/1307#issuecomment-368661039). However, I haven’t done any changes to the Prism core, so no mechanism exist to handle these settings on Prism’s level. At the same time, my code does not prevent an implementation of such a global mechanism in the future. The amendment is really simple, but might be useful for non-English speakers. Does it make sense to make a PR?

**Comment by mAAdhaTTah** [comment]
We would definitely be interested in a PR!

> However, I haven’t done any changes to the Prism core

I think the idea is to implement the mechanism in the plugin itself. If it would be useful to extract into core for other plugins, we can discuss that on the PR. But to start, you can put all the code in the plugin.
