### ISSUE TITLE
Any instructions how to set up PHP with HTML highlight correctly?

### ISSUE THREAD

**Issue by Sylphony** [PrismJS/prism#1439]
Related to #1238.  Using Prism v1.14.0.

I'm trying to highlight PHP code which has HTML in it.  More specifically, this is what I am trying to highlight.

```php
<link rel="stylesheet" href="<?php echo $this->getStaticUrl('css/styles.css'); ?>">
```

I included the PHP component and its dependencies and executed `Prism.highlight()`.  However, the result I'm getting is similar to C-like syntax.

![image](https://user-images.githubusercontent.com/1796078/41130506-e5e52d42-6a6b-11e8-8a5c-f48777a4c5a7.png)

From the Test Drive page, PHP should be working correctly so I have no clue what I'm doing wrong.  I'm trying to look for instructions to set it up correctly but I see none so I assume it should be simple.

Here's the code:

```js
import Prism from "prismjs";
import "prismjs/components/prism-markup-templating.js";
import "prismjs/components/prism-php.js";

const hl = Prism.highlight(snippet, Prism.languages["php"]);

// Output hl to DOM
```

The parsed HTML is as follows:

```html
<span class="token operator">&lt;</span>
link rel
<span class="token operator">=</span>
<span class="token double-quoted-string string">"stylesheet"</span>
href
<span class="token operator">=</span>
<span class="token double-quoted-string string">"&lt;?php echo 
  <span class="token interpolation">
    <span class="token variable">$this</span>
    <span class="token operator">-</span>
    <span class="token operator">&gt;</span>
    <span class="token property">getStaticUrl</span>
  </span>
  ('css/styles.css'); ?&gt;"
</span>
<span class="token operator">&gt;</span>
```

**Comment by mAAdhaTTah** [comment]
The parsed HTML looks basically correct. Do you have a reproducible test case we can look at?

**Comment by Golmote** [comment]
@Sylphony You also need to import `prismjs/components/prism-markup.js`, before `prismjs/components/prism-markup-templating.js`.

**Comment by Sylphony** [comment]
@Golmote Prism includes `markup` by default so that won't change anything.  For the record, I did try doing that though - it doesn't change anything.

@mAAdhaTTah Here's a [small repo](https://github.com/Sylphony/docsify-php-highlighting) test case.  Load index.html through a server.

One thing I neglected to mention is that I'm actually writing the code snippet in a markdown file, which is then passed through a markdown parser prior to outputting the DOM.  This is done through the [Marked](https://github.com/markedjs/marked) library.  How the library outputs markdown to HTML to the DOM I'm not sure.

[Standalone, the PHP highlight does work as expected](https://codepen.io/anon/pen/YvpNrj).  When comparing the differences between the standalone and the repo example, the only difference I can tell is in the standalone, Prism does one more routine to apply additional PHP tokens after it gets inserted into the DOM, presumably by a hook.  I'm not sure how hooks work though and I'm not sure if there needs to be a specific way for the Prism parsed results to be inserted into the DOM for the hook to work.

**Comment by mAAdhaTTah** [comment]
Based on the repo test case, it appears docsify is bundling an older version of Prism vs the one you're loading via CDN. It doesn't include the `{before/after}-tokenize` hooks required to make the markup-templating work. You'll want to ask them to update to the latest version.

Also, if you're using Prism with a bundler, you want want to look at the new [babel plugin](https://github.com/mAAdhaTTah/babel-plugin-prismjs) for handling language dependencies.
