### ISSUE TITLE
Negative lookbehind

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#1445]
It would be great the have a negative lookbehind for language definitions.

**Comment by RunDevelopment** [comment]
I'd like to suggest the following system:

```js
'positive-number': {
    pattern: /(-)?\d+/,
    lookbehind: true,
    lookbehinddirection: false
}
```

The default value for `lookbehinddirection` is `true`, representing a positive lookbehind. `false` will represent a negative lookbehind.

The first group will be considered a match, if it matches anything (including the empty string), whatever `lookbehinddirection` may be. The rest of the expression will be considered a match will if `firstGroupMatches ^ !lookbehinddirection` is true. (This of course assumes that the whole expression matches in the first place.)

This is somewhat different from the current implementation, as a non-matching first group of a positive lookbehind will currently cause the whole expression to be a match.


(As a less verbose alternative for `lookbehinddirection: false`, one could use `lookbehind: -1`)

**Comment by Golmote** [comment]
@RunDevelopment I like this idea. Regarding the wording, I'd prefer something like `lookbehingNegative: true` (defaults to `false`) rather than any of you propositions.
Apart from this, your implementation concept looks quite straightforward. Would you be interested in submitting a PR for this?

**Comment by RunDevelopment** [comment]
Sure, I can take a shot at implementing this. 
Also: Yes, `lookbehingNegative` is better.

**Comment by RunDevelopment** [comment]
I will now close this for similar reasons as #1465.

1. It will add a lot of complexity and will only ever be used by a small number of languages.
2. I can not think of any way to implement this efficiently.
3. I have written dozens of languages and never needed it because...
4. Current positive lookbehinds can already do negation. To go with my motivating example: Using only positives lookbehinds, positive numbers can be matched using: `/(^|[^-])?\d+/`. This is a trick I regularly use.

    More general: To get the Prism lookbehind of `(?<!R)` for any regular expression `R`, you have to find the complement of `^[\s\S]*R`. This isn't easy but it is always possible.
    E.g. `(?<!a)` ~= `(^|[^a])`, `(?<!#\s*)` ~= `((?:^|[^#\s])\s*)`
