### ISSUE TITLE
First line has a 1 character indent. 

### ISSUE THREAD

**Issue by alexisdrakopoulos** [PrismJS/prism#1447]
```
<pre><code class="language-python">import subprocess

anotherdownload = ''</code></pre>
```

This is my code for example, and this is the output:

![firstline](https://user-images.githubusercontent.com/33128441/41669772-7f01be3a-74aa-11e8-9bfb-a98069a74823.png)

EDIT: With further testing this issue occurs when I use the remove first line or remove white space plugin only.

**Comment by mAAdhaTTah** [comment]
Can you provide an online reproducible test case? I've seen this type of thing before, and it's been another css file applying padding to the `code` element.
