### ISSUE TITLE
plsql extend sql.But plsql before sql to define.

### ISSUE THREAD

**Issue by jaune162** [PrismJS/prism#1448]
My npm package is 1.15.0. I install prism package used `cnpm`.

In `prism.js`, the line 5392 is the code what plsql language extend sql start define.
![image](https://user-images.githubusercontent.com/10142624/41771076-8872adba-7646-11e8-9665-e15e4bc1ef9b.png)

but the sql language defined by line 6912
![image](https://user-images.githubusercontent.com/10142624/41771353-6fefd4b0-7647-11e8-8c66-5dc5b21365cc.png)

So when I import prism to my code. I will get this error in console.
![image](https://user-images.githubusercontent.com/10142624/41771164-ce002e34-7646-11e8-9dbb-281f78e6abd1.png)
![image](https://user-images.githubusercontent.com/10142624/41771200-e725f47a-7646-11e8-9154-4f8dd2163525.png)

How to resolve this problem.

**Comment by mAAdhaTTah** [comment]
How are you bundling prism?

**Comment by mAAdhaTTah** [comment]
Based on the linked ticket, this appears to be build-related. Ideally, you should be using [`babel-plugin-prism`](https://github.com/mAAdhaTTah/babel-plugin-prismjs) to bundle prism, but without more information, I don't think this is a bug on our end.

**Comment by jaune162** [comment]
I test this bug start at v1.11.0.

I commont all my code in `index.js` except `import PrismJs from 'prismjs';`. Then start my project and open my home page.
It always throw this exception when the version above '1.11.0'.

**Comment by mAAdhaTTah** [comment]
@jaune162 We would need the above question answered or a reproducible test case to look at before we can help you.

**Comment by colshacol** [comment]
I seem to be having a similar issue.

[(CodeSandbox to reproduce found here.)](https://codesandbox.io/s/j40n13jmow)

When using `prismjs/components/prism-javascript` and `prismjs/components/prism-jsx`, I receive two different errors. (At random. Never know which one will happen.)

```
# Most commonly:
"Cannot set property 'comment' of undefined"
# And sometimes:
"Cannot read property 'tag' of undefined"
```

It seems like the `comment` error happens more often when `prism-jsx` is imported _after_ `prism-javascript`.

Here are a handful of screenshots to give you a quick glance at it:

<img width="1575" alt="screen shot 2018-11-23 at 12 46 11 am" src="https://user-images.githubusercontent.com/19484365/48931063-0c26d780-eeba-11e8-8dad-3484b7003988.png">
<img width="1577" alt="screen shot 2018-11-23 at 12 44 56 am" src="https://user-images.githubusercontent.com/19484365/48931067-10eb8b80-eeba-11e8-8238-6ea1e5160f7e.png">
<img width="1569" alt="screen shot 2018-11-23 at 12 44 47 am" src="https://user-images.githubusercontent.com/19484365/48931069-12b54f00-eeba-11e8-80ae-781a30bc3f9e.png">
<img width="1581" alt="screen shot 2018-11-23 at 12 44 00 am" src="https://user-images.githubusercontent.com/19484365/48931070-12b54f00-eeba-11e8-90b6-294311f37800.png">
<img width="1571" alt="screen shot 2018-11-23 at 12 43 45 am" src="https://user-images.githubusercontent.com/19484365/48931071-12b54f00-eeba-11e8-961b-b512b400e4dd.png">
<img width="910" alt="screen shot 2018-11-23 at 12 41 47 am" src="https://user-images.githubusercontent.com/19484365/48931072-12b54f00-eeba-11e8-91f3-1d14d15da8b5.png">
<img width="1920" alt="screen shot 2018-11-23 at 12 40 57 am" src="https://user-images.githubusercontent.com/19484365/48931073-12b54f00-eeba-11e8-94c0-3817ff23447b.png">
<img width="1915" alt="screen shot 2018-11-23 at 12 40 44 am" src="https://user-images.githubusercontent.com/19484365/48931074-12b54f00-eeba-11e8-8520-0a377894b46d.png">
<img width="1920" alt="screen shot 2018-11-23 at 12 40 32 am" src="https://user-images.githubusercontent.com/19484365/48931076-12b54f00-eeba-11e8-83f1-3aa419d647d5.png">

**Comment by RunDevelopment** [comment]
@colshacol 
You have to import `import "prismjs/components/prism-markup";` markup before JSX (and change the highlight language to `jsx`) and it will work.

**Comment by cuongdaovan** [comment]
hi everyone, please tell me the solution of this issue

**Comment by RunDevelopment** [comment]
@cuongdaovan This cause of the issue was that Prism languages can depend on other languages, so it might not be obvious what languages have to be loaded in what order. The solution for this issue is to not import language files directly yourself. Either use a build from our [download page](https://prismjs.com/download.html) or import Prism via [another support way](https://prismjs.com/#basic-usage).
