### ISSUE TITLE
scheme language issues

### ISSUE THREAD

**Issue by jcubic** [PrismJS/prism#1451]
So I found few issues:
* [x] string don't start with `'` in scheme `'` is for quote (you can quote names, which become symbols or lists) (#2263)
   solution: remove `|'[^('\s]*` from string regex
* [x] lambda,define have first parameter mark as function invocation `(lambda (foo bar) (concat foo bar))` foo is mark as function, I've try to came up with regex but was not able to find one. (#2263)
* [x] function without argument is not marked as function
   solution: `/(\()[^\s()]*(?=[\s)])/,` added `(?=[\s)])` instead of `(?=\s)` (#1463)
* [x] ~numbers that don't have space before them are not marked as numbers
  solution: optional space in the beginning of number regex `(\s?|[()])`~

Wanted to create PR but don't know how to fix function with define and lambda.

**Comment by Golmote** [comment]
Hi @jcubic. You can definitely submit a PR fixing 3 bugs out of 4, and you are very welcome to do so!

Regarding the `lambda` case, it might be tricky. The negative lookbehind suggested in #1445 might come in handy to solve such a case.

**Comment by jcubic** [comment]
It seems that numbers are correct and string regex don't match single quote string but symbols, so only function without arguments is not marked as function, will create PR.

**Comment by jcubic** [comment]
Found another issue. In scheme there are no operators only functions and if you're adding function `**` it's marked as operator and nothing (span without `*&nbsp;`). will create PR for this as well.

**Comment by jcubic** [comment]
Found another 2 issues with scheme mode:
* strings in scheme can be multiline
* function name that start as keyword like define is not mark as function (to fix this the regex first need to check for function name and after if fail it need to check for keyword like define or lambda)

Example:
```scheme
(display (list->array '(1 2 3 "foo
bar
baz")))
(list 1 2 3)
```
on GitHub multiline strings works and list->array don't have list highlighted (on GitHub scheme syntax function names are black)

**Comment by jcubic** [comment]
I can create PR with the fix last one was not merged, @Golmote did you notice it?

**Comment by RunDevelopment** [comment]
@jcubic 
Number 2 is already addessed in #1556.
(And Prism doesn't split the code by lines before processing.)

**Comment by jcubic** [comment]
@RunDevelopment does this PR fixes function names like `==` that is marked as operator?

**Comment by jcubic** [comment]
Found another issue:
```scheme
(define 1+2 10)
```

1 in `1+2` is mark as number but this is symbol, in lisp I think that tokens are delimited only by `/[ ()]/`, and probably also by special symbols like `,` `` ` `` `,@` and `'`

**Comment by jcubic** [comment]
I think that this do the trick for last number issue:
```
/([\s()])[-+]?\d*\.?\d+(?:\s*[-+]\s*\d*\.?\d+i)?([\s()])/
```
`([\s()])` instead of `\b` same as at the begining, but I need to run the tests to be sure that this don't break anything.

**Comment by RunDevelopment** [comment]
@jcubic I want to close this issue with #2263 but I have two questions:

> `lambda`, `define` have first parameter mark as function invocation [...]

Can you please give an example with `define`?

> numbers that don't have space before them are not marked as numbers

An example of this one as well, please.

---

Also, I changed your comments a bit, so that I could track which parts of the issue were already done. Please tell me in case I missed anything.

**Comment by RunDevelopment** [comment]
I forgot to mention this: [`case-lambda`](https://srfi.schemers.org/srfi-16/srfi-16.html).
I don't think that we will ever find a way to not mark these variables(?) as functions. I'll make an entry on the known failures page.

**Comment by jcubic** [comment]
The for numbers the regex need to be `/([\s()])[-+]?\d*\.?\d+(?:\s*[-+]\s*\d*\.?\d+i)?(?=[\s()])/.

I have no idea what the issue was with numbers without space. Numbers always need to have space, maybe this "(number? `10)" biwascheme return true for this even that it's quote. I think this can be ignored.

**Comment by RunDevelopment** [comment]
Maybe [rational numbers](https://github.com/PrismJS/prism/pull/1964)? Anyway, I'll just ignore it.

**Comment by jcubic** [comment]
Found another issue, rational numers literals are ok but not complex one:

Some of them are marked as numbers other not:
```scheme
(list 10i +10i -10i 10.10i 10+10i 10.10+10.10i 10-10i 10e+10i 10+10e+10i)
```

it can be ("+" "-") number ("+" "-") number "i", where number can be float or integer, float can use scientific notation and first 3 items are optional.

**Comment by RunDevelopment** [comment]
Fixed this in #2263.

I also removed the optional spaces around the [+-] linking the rational and imaginary parts of a complex number. `2 + 4i` should be interpreted as 3 symbols, right?

**Comment by RunDevelopment** [comment]
Also, I found this [grammar of Scheme numbers](https://www.scheme.com/tspl3/grammar.html#./grammar:s17). Should Prism support this as well or is the current pattern sufficient?

**Comment by jcubic** [comment]
Those works in Kawa and Guile:
```scheme
(list #xAFD #b1110011 #o777)
```

Guile is more compilant it have:

```
#i#x10
```
as inexact (float) hex,

or
``scheme
#i#x10+10i
```
float hex complex

Guile also works with this:
```scheme
#b10+10i
```
binary complex number. I think since Prism is not a parser I think that it would be ok to add:

`(?:#[bxieo]){1,2}` in front of number (and digits need to be `[0-9A-F]`), it will mach what it should but simply will not check if the value is `#b` (binary) and only `0 1` I think that this simplification is ok.

**Comment by jcubic** [comment]
I think I know what was the issue with numbers "10" is not marked as number. so beginning of regex need to be `([(\s]|^)` to match beginning of the strings same probability need to be done at the end.

I can try update the regex and create unit tests.

**Comment by RunDevelopment** [comment]
Binary, octal, and hexadecimal numbers are now supported in #2263.

**Comment by RunDevelopment** [comment]
#2263 is merged and I think it addresses all issues here. Feel free to reopen this in case I missed something.
