### ISSUE TITLE
Line wrap in PrismJS doesn't work

### ISSUE THREAD

**Issue by whs-dot-hk** [PrismJS/prism#1453]
e.g. this javascript code `document.querySelector('#like_button_container')` won't break into lines

lead to something like https://github.com/reactjs/reactjs.org/issues/1006

thank you

**Comment by mAAdhaTTah** [comment]
I'm not seeing that behavior at the page (https://reactjs.org/docs/add-react-to-a-website.html) in the linked issue. Regardless, I don't think this is something we would change by default since it would be breaking for current users and can be adjusted with some custom CSS if you need.
