### ISSUE TITLE
SQL comment yields wrong highlighting

### ISSUE THREAD

**Issue by fabsenet** [PrismJS/prism#1454]
I have the following sql. Yes, I have sql queries in database tables. Do not judge me 🐇 

This is the code i want to highlight:
```sql
INSERT INTO MESSAGESEARCHPATTERN (name, query)
VALUES ('a','select ''hello world'' from a')

-- this is a comment

INSERT INTO MESSAGESEARCHPATTERN (name, query)
VALUES ('a','select ''hello world'' from a')
```

this is, what the test page/prismjs makes from it (language is SQL):
![grafik](https://user-images.githubusercontent.com/2065705/42027132-81a56bbe-7ab8-11e8-9aa6-d0691623080b.png)

**Comment by yakov116** [comment]
@fabsenet me too :grinning:

I however use it more for documentation.

**Comment by Golmote** [comment]
From a really quick look at it, it appears to be more about the `''` part of the string than about the comment. I think our component does not handle "quote-escaped quotes" (is there a name for this?) in [the string pattern](https://github.com/PrismJS/prism/blob/master/components/prism-sql.js#L7) at the moment.
