### ISSUE TITLE
How do I change the theme of the code block?

### ISSUE THREAD

**Issue by Omar-Aziz** [PrismJS/prism#1455]
I'm currently using prismJS with a CDN, what is the syntax to change the theme?

**Comment by mAAdhaTTah** [comment]
The theme is determined by the CSS file. You'll need to add / update that to change themes.

**Comment by Omar-Aziz** [comment]
thank you. Would I be able to control the size of the box too from the CSS file?

**Comment by mAAdhaTTah** [comment]
You'll need to write some custom CSS for that, as I don't think our built-in themes set a max-width on them.

**Comment by Omar-Aziz** [comment]
Perfect. Thank you.
