### ISSUE TITLE
Generic classes in C# are not highlighted

### ISSUE THREAD

**Issue by mikhailshilkov** [PrismJS/prism#1458]
Generic classes in C# are not highlighted:

![image](https://user-images.githubusercontent.com/1454008/42224876-6e32efbc-7edb-11e8-8a8a-bbd34c96b2d6.png)

Desired result (Visual Studio screenshot):

![image](https://user-images.githubusercontent.com/1454008/42224793-3e068f10-7edb-11e8-8701-a0ab0600537c.png)

**Comment by RunDevelopment** [comment]
#1444 covers both generic classes and return type (generic or not).

**Comment by RunDevelopment** [comment]
Fixed in #1444.
