### ISSUE TITLE
F# computation expressions are not highlighted

### ISSUE THREAD

**Issue by mikhailshilkov** [PrismJS/prism#1459]
F# computation expressions are not highlighted (`async` in this example):

![image](https://user-images.githubusercontent.com/1454008/42225716-7e58671c-7edd-11e8-89f6-e46e16e2355c.png)

Desired result (VS Code screenshot):

![image](https://user-images.githubusercontent.com/1454008/42225758-96ce0bf8-7edd-11e8-9b53-26fcf3f18fb7.png)

**Comment by mikhailshilkov** [comment]
It would help for `async`, but that can actually be any literal:

![image](https://user-images.githubusercontent.com/1454008/42226084-50e00712-7ede-11e8-94f8-d47144bb1c4e.png)

**Comment by mAAdhaTTah** [comment]
What other keywords can go there? I'm not entirely sure we can handle this in a generic way with regexes.

**Comment by mAAdhaTTah** [comment]
To put it more generically, what's the grammar for computation expressions?

**Comment by mikhailshilkov** [comment]
I can be any valid F# literal, because they are also user-defined.

Interestingly, VS Code does hightlight `async`, `task`, `seq` and `maybe`, but doesn't highlight some others.

Visual Studio highlights anything:

![image](https://user-images.githubusercontent.com/1454008/42226994-b8ce8e78-7ee0-11e8-9477-d7b234734531.png)
