### ISSUE TITLE
CoffeeScript Strings, Comments and String Interpolation

### ISSUE THREAD

**Issue by gonsfx** [PrismJS/prism#147]
```coffeescript
# this is a comment with a "string" inside
str = "an #{expression} is interpolated in this string"
```

Githubs Linguist gets this right (see above).
Prism doesn't.

Changing the order of the tokens will probably not be enough due to the nature of being able to embed any expression in `#{}` in double-quoted strings.

**Comment by Golmote** [comment]
This looks fixed with the current version of the component.

![http://puu.sh/iVo9Q/07caac8d09.png](http://puu.sh/iVo9Q/07caac8d09.png)
