### ISSUE TITLE
Documentation highlighting

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#1475]
Many languages have an (at least somewhat) standardized syntax for code documentation like [JavaDoc](http://www.oracle.com/technetwork/java/javase/tech/index-137868.html), [JSDoc ](http://usejsdoc.org/index.html), [PHPDoc ](https://docs.phpdoc.org/guides/docblocks.html), [.Net XML doc](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments) (for C#, F# and VB.Net) and others.

Similar to most IDEs, the inline documentation comment should be displayed in a different color than normal comments. Also keywords, type and parameter references, examples and similar should be highlighted.

This means that every the themes will have to be changed to reflect the new syntax highlighting.
I am no designer, so it would be great to get some help.

Because the documentation of many languages is inspired by JavaDoc, it should not be too hard to write an abstract base of doc comment highlighting which is then extended by  different languages.

## Examples

PrismJS
![image](https://user-images.githubusercontent.com/20878432/42592247-3f2b6568-8549-11e8-92fa-0abbad424ff2.png)

GitHub
```js
/**
 * Trims a given string.
 * 
 * @param {string} [str=""] the string.
 * @returns {string} something.
 * @throws {TypeError} if the argument is not a string.
 * @example trim(" hello ")
 */
function trim(str = "") {
	if (typeof str !== "string")
		throw new TypeError("str has to be a string");
	return str.trim();
}
```

Notepad++
![image](https://user-images.githubusercontent.com/20878432/42591957-8195fae0-8548-11e8-9c03-c4ef1139d8cb.png)

VS Code
![image](https://user-images.githubusercontent.com/20878432/42591930-6e97ca86-8548-11e8-9963-81b3bc4b791b.png)

**Comment by mAAdhaTTah** [comment]
I could see this being provided as an additional language; maybe a "language" that enhances existing languages?

**Comment by RunDevelopment** [comment]
I originally imagined this as an extension of existing languages, but making them into their languages might be better idea. 
Like this we could also support wildly different styles, which might be necessary if we ever wanted to support a language where there is no one dominating standard.

Using this approach we could do it like this:

```js
// Prism.languages.java
'doc-comment': {
    pattern: /\/\*\*[\s\S]*?\*\//,
    greedy: true
},
...
```

Something like `Prism.languages.javadoc` would then add itself as `inside`.

**Comment by mAAdhaTTah** [comment]
Yeah, my thought is we could have a single `docblock` language (or whathaveyou) that modifies all of the languages that can use JavaDoc-style documentation.
