### ISSUE TITLE
Generics in Java not displayed properly

### ISSUE THREAD

**Issue by FabienTregan** [PrismJS/prism#1481]
I downloaded prism css / js from the website, making sur I include java language, and made this test :
```
<!DOCTYPE html>
<html>
<head>
	<link href="prism.css" rel="stylesheet" />
</head>
<body>
	<pre><code class="language-java">
		private Function<String[], List<String>> x = x -> x;
	</code></pre>
	<script src="prism.js"></script>
</body>
</html>
```

Generics does not seems to be handled and I get this output :
```
private Function> x = x -> x;
```

**Comment by RunDevelopment** [comment]
That's because the browser will interpret `<String[], List<String>` as an HTML tag.

Just escape all `<` with `&lt;` and it will work as expected.
