### ISSUE TITLE
"Previewers" plugin dont work correctly with the "Line Numbers"

### ISSUE THREAD

**Issue by Alxndr6eo1yG8Lv8AJ0TkliH6** [PrismJS/prism#1496]
The tooltip isnt aligned vertically.

![prism js bug](https://user-images.githubusercontent.com/41586163/43088845-dd5e7264-8eab-11e8-97a7-40c611023c8e.png)

[link to CodePen](https://codepen.io/Alxndr6eo1yG8Lv8AJ0TkliH6/pen/bjqPpX)

**Comment by RunDevelopment** [comment]
Which browser are you using?

I can confirm this bug on FireFox, but not on Chrome.

**Comment by Alxndr6eo1yG8Lv8AJ0TkliH6** [comment]
i use Firefox Developer Edition.

**Comment by Alxndr6eo1yG8Lv8AJ0TkliH6** [comment]
Now it works thanks!

This is my 1st time on githab. Do I need to click something because the problem is solved to me?

**Comment by RunDevelopment** [comment]
How did you solve it?

**Comment by Alxndr6eo1yG8Lv8AJ0TkliH6** [comment]
I downloaded a new script "Previewers"

**Comment by RunDevelopment** [comment]
The one from my commit?

**Comment by Alxndr6eo1yG8Lv8AJ0TkliH6** [comment]
Yes (  Fixed bug #1496  )

**Comment by RunDevelopment** [comment]
Ok, thanks for the clarification.

This commit is not the final version yet, so I would like to ask you to wait until I publish the final version.
You can still use that commit, but be sure to update to the latest version of Prism once the final version has been included. (Likely in a few days)

**Comment by Alxndr6eo1yG8Lv8AJ0TkliH6** [comment]
Thank you very much =)

**Comment by RunDevelopment** [comment]
We will close the issue once the final bug fix has been include, so you can leave it open.

You're welcome ^^
