### ISSUE TITLE
Specify version of node / npm needed to run tests

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [PrismJS/prism#1502]
when i try to run only a subset of the tests ( eg. the language im currently working on, described here: https://prismjs.com/test-suite.html ) i get this error:

```
easteregg@x12 ~/Coding/prism (master *) $ npm test -- --language=plsql
npm ERR! Error: ENOENT: no such file or directory, open '/home/easteregg/Coding/prism/node_modules/--language=plsql/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.17.6-towo.1-siduction-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "test" "--" "--language=plsql"
npm ERR! cwd /home/easteregg/Coding/prism
npm ERR! node -v v8.11.2
npm ERR! npm -v 1.4.21
npm ERR! path /home/easteregg/Coding/prism/node_modules/--language=plsql/package.json
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/easteregg/Coding/prism/npm-debug.log
npm ERR! not ok code 0
```

i can run all tests without any problems, but since my machine is a bit old, this takes over 3 min, which is a little cumbersome.

**Comment by RunDevelopment** [comment]
I can reproduce this error with neither the Prism master branch nor your fork on Windows 10.

Could this be a Linux specific problem?
What Linux distribution are you using?

**Comment by verfriemelt-dot-org** [comment]
debian unstable, nothing to fancy about it.
its quite rare that i use node at all, so there is no additional config done to the system with regards to node or npm

**Comment by RunDevelopment** [comment]
You might want to give updating npm a try. 
The current version 6.1.0. Your version seems to be 1.4.21.

**Comment by verfriemelt-dot-org** [comment]
```
 $ npm test

> prismjs@1.15.0 test /home/easteregg/Coding/prism
> mocha tests/testrunner-tests.js && mocha tests/run.js



  The token stream transformer
    ✓ should handle all kinds of simple transformations
    ✓ should handle nested structures
    ✓ should strip empty tokens
[ ... ]
```

i noticed the output of the commands invoked and used the mocha module directly:

` ./node_modules/mocha/bin/mocha tests/run.js`

when i invoke that script with the argument `--languages=plsql` i get the expected results.

as you pointed out, it might have something to do, with that old npm version shipped with debian sid.
it seems only newer versions pass off that argument.

**Comment by mAAdhaTTah** [comment]
So is this still a valid issue or no?

**Comment by verfriemelt-dot-org** [comment]
depends, i would suggest updating the documentation and stating the npm version supporting this feature

**Comment by mAAdhaTTah** [comment]
Updated title to match. Thanks for the suggestion!
