### ISSUE TITLE
[request] Page(s) with reference snippets for each supported languages

### ISSUE THREAD

**Issue by opatry** [PrismJS/prism#151]
Hi,

it would be awesome if a set of reference pages (or single one if not too much supported languages?) were available.

It could be used as pseudo testsuite (a real testsuite may be even better!) and, at least for me, a great tool to add new theme.

Currently, I have a theme idea that I would write but I have no idea of how/where to find exhaustive snippets for each languages :(

I assume, using the file highlight plug-in, the integration flow would be easy.

**Comment by loganfranken** [comment]
I think this can be closed, right? The Examples page is up and running and it's working great.
