### ISSUE TITLE
C and C++: backslash-newline continues comments

### ISSUE THREAD

**Issue by zackw** [PrismJS/prism#1511]
In C, C++, Objective-C, and Objective-C++, the official parser specification requires backslash-newline to be removed from the input stream before comments are handled, which means it can extend comments.  The most important case of this is

``` c
// this line is a comment \
this line is also part of the comment
this line is outside the comment
```

where both the first and second lines, but not the third, should be highlighted as a comment.  Other cases include

``` c
/\
/ this line is a comment
this line is outside the comment
```

and

``` c
/\
* this is a block comment *\
/ outside the comment
```

https://prismjs.com/test.html currently gets all of these wrong.  I would forgive you for not bothering to handle the second and third cases.

And of course \-newline can also be spelled ??/-newline, but again, I'd forgive you for not bothering with that one.

**Comment by mAAdhaTTah** [comment]
I suspect this one is going to be tough to get right with a regex.

**Comment by zackw** [comment]
\/(?:|\\\n|\?\?\/\n)\/.*?(?:\\\n.*)*?[^\\]$

**Comment by mAAdhaTTah** [comment]
Ok cool, would you be able to open a PR with that change + tests? Thanks!

**Comment by zackw** [comment]
I'm sorry, I will not have time to do that for at least two months.  (Throwing together regexes is easy.  Writing tests is hard.)
