### ISSUE TITLE
rust keyword/string precedence issue

### ISSUE THREAD

**Issue by durka** [PrismJS/prism#1514]
Migrated from rust-lang/crates.io#1468.

This code is incorrectly highlighted:

```markdown
    ```rust
    let repo = github.repo("user", "repo");
    ```
```


![badly highlighted code](https://alexburka.com/tmp/Screen%20Shot%202018-07-31%20at%209.41.40%20PM.png)

There should be two strings, but somehow the `use` keyword gets picked out (?).

**Comment by RunDevelopment** [comment]
Cannot reproduce using [Test drive](https://prismjs.com/test.html).

![image](https://user-images.githubusercontent.com/20878432/43545431-2cbd946c-95d6-11e8-9723-a2dd18dae53f.png)

The rust language definition your using seems to be outdated (or modified).

**Comment by mAAdhaTTah** [comment]
@durka Can you double check if this issue is still valid?

**Comment by durka** [comment]
It is indeed fixed in the latest release.
