### ISSUE TITLE
handlebars templates highlighting doesn't work

### ISSUE THREAD

**Issue by neginbasiri** [PrismJS/prism#1515]
`  

    import $ from 'jquery';

    import Prism from 'prismjs/components/prism-core';
    import 'prismjs/components/prism-markup';
    import 'prismjs/components/prism-markup-templating';

    import 'prismjs/components/prism-handlebars';
    import loadLanguages from 'prismjs/components/index.js';

    export class StyleHighlighter {

      constructor(){

          loadLanguages(['handlebars']);
          Prism.highlightAll();

      }

    }

    new StyleHighlighter();
`

The error is showing:
`Uncaught Error: Cannot find module './prism-markup'`

Do you have a working version of latest handlbars template highlighting?

**Comment by mAAdhaTTah** [comment]
`loadLanguages` is intended for node usage. We recommend the babel plugin for usage with webpack and other bundlers. Please see the documentation for more details: https://prismjs.com/#basic-usage

We've gotten this issue a lot; where did you see the suggestion to use `loadLanguages`?

**Comment by neginbasiri** [comment]
I am using node and webpack

**Comment by mAAdhaTTah** [comment]
By "node", do you mean "I'm running a node server and need to highlight on the server" or "I'm using node to run my build tools"?

**Comment by neginbasiri** [comment]
node to run my build tools,
node/webpack4/es6/React

**Comment by mAAdhaTTah** [comment]
This is probably a result of how your webpack is configured. If the css loaders only include css files within the project (e.g. Ignoring node_modules), it'll ignore css dependencies and throw this error.

**Comment by agm1984** [comment]
I found a solution for stubbing CSS files: https://stackoverflow.com/a/41851815/6141025

You can use `moduleNameMapper` to map `*.css` to the stub:

``` javascript
{
  "jest": {
    "moduleNameMapper": {
      "\\.(css|scss)$": "<rootDir>/__mocks__/styleMock.js"
    }
  }
}
```

**./__mocks__/styleMock.js**
``` javascript
module.exports = {};
```
