### ISSUE TITLE
Why only first error shown in file highlight?

### ISSUE THREAD

**Issue by opatry** [PrismJS/prism#152]
Hi,

the file highlight plug-in only shows the first error on page.

It would be better to fail for each error, no?

**Comment by loganfranken** [comment]
@opatry, are you still able to reproduce this?

I *swear* I reproduced this last night, but I can no longer get it to occur:
https://jsfiddle.net/eyu3xo7r/

Even though I *think* I was able to reproduce this under *some* conditions, I'm guessing it must be a rare edge case (maybe I had setting off in Chrome Dev Tools or something), so I would vote to close this unless you're able to reproduce this, @opatry.
