### ISSUE TITLE
`catch` should not be a keyword when used in a Promise chain

### ISSUE THREAD

**Issue by phortuin** [PrismJS/prism#1526]
Currently, when parsing javascript, `catch` will be rendered as a keyword. Since ES6, `catch` is also a method on the Promise prototype, which is probably best rendered as a `function` in Prism:

```
fetch('some-resource.json')
    .then(response => response.json())
    .catch(console.error)
```

Hopefully, there is an easy way to test for this. Thanks!

**Comment by RunDevelopment** [comment]
In JS, `catch` is only used in try-catch blocks so we could say, that it will only a keyword if it's preceded by `/\}\s*/`. (Same for finally.)
Like this, we should also be able to eliminate most false positives from other identifiers.

Or am I forgetting something?
