### ISSUE TITLE
JSON Incorrectly Highlighted

### ISSUE THREAD

**Issue by grayghostvisuals** [PrismJS/prism#153]
Here's a few screenshots from an article I wrote where I used a Gruntfile as an example. It appears from the output anything caught in JSON that has a comment is completely wrapped in a comment span even though subsequent lines are not commented. This is using the current release of the Prism Core.

![screen shot 2013-08-05 at 8 54 56 am](https://f.cloud.github.com/assets/934322/909918/cb9c47c2-fdce-11e2-89e8-1078dddeb3a7.png)

![screen shot 2013-08-05 at 8 56 49 am](https://f.cloud.github.com/assets/934322/909919/cdeaa992-fdce-11e2-93ce-2e9e8cf00cfe.png)

**Comment by grayghostvisuals** [comment]
@apfelbox Can you reopen this issue please? The error I've posted initially above still remains.

**Comment by vkbansal** [comment]
@grayghostvisuals see #307
