### ISSUE TITLE
The minified code is not working for me...

### ISSUE THREAD

**Issue by hilja** [PrismJS/prism#154]
...but the unminified works fine. If I minify the code with CodeKit it also doesn't work.

And: "JSHint found 125 issues in the file", I have no idea if it has any significance to this issue.

Lovely highlighter though. Thanks!

**Comment by loganfranken** [comment]
Hey @hilja, I know it's been awhile, but do you have an example of this?

The minified code works just fine for me, so maybe this got fixed?

**Comment by loganfranken** [comment]
@Golmote I think this one can be closed

**Comment by Golmote** [comment]
Unable to reproduce the bug. I close the issue.
