### ISSUE TITLE
Command Line plugin alignment problems

### ISSUE THREAD

**Issue by DavinaLeong** [PrismJS/prism#1564]
Hi, I've just downloaded `PrismJS`, using the **command line** plugin.

The original `PrismJS` works like a charm, but there are alignment issues when attempting to use the **command line** plugin. This is used in conjuction with other popular packages like **Bootstrap 4** and **Font Awesome**.

Screenshot:
![2018-09-19](https://user-images.githubusercontent.com/35887372/45721509-e55ad500-bbda-11e8-825e-f0973a6c7a1e.png)

Here's my code:
```
<link rel="stylesheet" href="./vendor/prismjs/themes/prism.css">
<link rel="stylesheet" href="./vendor/prismjs/plugins/command-line/prism-command-line.css">
<script src="./vendor/prismjs/prism.js"></script>
<script src="./vendor/prismjs/plugins/command-line/prism-command-line.min.js"></script>
```

```
<p>To view the pages as they are, simply run this command in your console/terminal:</p>
<pre class="command-line-prompt"><code class="language-bash">npm start</code></pre>
<p>And navigate to <code>http://localhost:3000/index.html</code> in your web browser.</p>

<p>To update the vendor packages, run this command in your terminal/console:</p>
<pre class="command-line-prompt"><code class="language-bash">gulp</code></pre>
```

**Comment by bennycooly** [comment]
I think you are supposed to use the class `command-line`, not `command-line-prompt`.

**Comment by RunDevelopment** [comment]
@DavinaLeong

@bennycooly Is correct. It is also stated in the [how to use section](https://prismjs.com/plugins/command-line/) of the command line plugin:

> Add class `command-line` to your `<pre>`.

The `command-line-prompt` class is used internally by the command line plugin and it should not be possible to enable command lines via this class. 
This is a bug.
