### ISSUE TITLE
Default to highlight the common functional words without set language type.

### ISSUE THREAD

**Issue by ursulashan** [PrismJS/prism#1565]
Thank you for providing this wonderful highlighting library. 
=============

Please think about to highlight some special words and puncuations without set language type.
such like `var`, `function`, `=`, `{}` etc.

**Comment by RunDevelopment** [comment]
[Syntax highlighting](https://en.wikipedia.org/wiki/Syntax_highlighting) is supposed to improve readability by using different styles according to the category of terms.

I don't see how highlighting words which have a special meaning in some programming languages is improving the readability of plain text. Not highlighting anything is a better choice than highlighting randomly IMO.

---

You can, however, use inheritance to define a quasi default language.
Prism will go up the DOM tree if the `<pre>` or `<code>` don't have a `language-xxxx` class until it finds such a class or reaches the root. So you can define a `language-xxxx` class for `<body>` to have a quasi default language. (This only works if the `<pre>`/`<code>` is actually part of the DOM tree of course.)

The quasi default language can then be your favorite functional language or a [new custom language](https://prismjs.com/extending.html#language-definitions) which highlights these common functional keywords.
