### ISSUE TITLE
request: gcode highlighting

### ISSUE THREAD

**Issue by marc-medley** [PrismJS/prism#1571]
Request: add "G-code" syntax highlighting to prism with the language identifier of `gcode`.

G-code is the common name for the most widely used numerical control (NC) programming language.  see [Wikipedia: G-code](https://en.wikipedia.org/wiki/G-code)

The implementation is really small and already exists in https://github.com/kmoser77/prismjs-reprap-gcode.

``` javascript
Prism.languages.reprap_gcode = {
	comment: /;.*/,
	keyword: /\b(G[\d]+|M[\d]+)\b/g,
	property: /\b(X|Y|Z|E|F|S|P|T|I|J|D|H|R|Q|N|\*)/g
};
```

![gcode-syntax-highlight](https://user-images.githubusercontent.com/15098151/45931843-8a9de200-bf28-11e8-93af-8ccf6709a68b.png)

**Comment by RunDevelopment** [comment]
@marc-medley 
May I ask what the `*` property refers to? I can't find it in the linked Wikipedia page.

**Comment by marc-medley** [comment]
`.*` all characters after the semicolon where `;` denotes the beginning of a comment.

**Comment by marc-medley** [comment]
`/;.*/` is comment string wildcard 

`property…\*)…` is for a checksum field that may appear at the end of the executable portion of the line:

```
N3 T0*57 ; This is a comment
N4 G92 E0*67
; So is this
N5 G28*22
```
see https://reprap.org/wiki/G-code#.2A:_Checksum

**Comment by marc-medley** [comment]
> … also add strings before they destroy our comments.

good catch.

**Comment by RunDevelopment** [comment]
@marc-medley 
Maybe we should also style the checksum differently. Frankly, I don't think it looks good. 
What do you think?

As `property` like before:

![image](https://user-images.githubusercontent.com/20878432/45932771-e9437a00-bf81-11e8-9623-d53400c59e8d.png)

As `punctation`:

![image](https://user-images.githubusercontent.com/20878432/45932775-ed6f9780-bf81-11e8-87f6-29630b12ea60.png)
