### ISSUE TITLE
When can we drop IE11 support?

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#1578]
Once we can drop IE11, we will be able to depend on CSS variables.
This means we can finally get rid of the whole problem "how do all themes work with all languages?". Themes would just define variables, language definitions would just use these variables.

What do you think?

**Comment by mAAdhaTTah** [comment]
I'm personally OK w/ dropping IE11 support, but I know projects I work on generally still support it as MSFT is still supporting that browser. Additionally, IE11 still works w/ Windows 10, so MSFT may continue to support it for a while.

This is also definitely a breaking change, so we should release as a 2.0. If we drop IE11 support, we could probably go all-in on ES6 as well, if that helps the code at all.

Just some thoughts. Not really sure where I stand, tbh.

**Comment by ExE-Boss** [comment]
We could maybe support CSS variables and use [`postcss-custom-properties`](https://github.com/postcss/postcss-custom-properties) for rudimentary IE11&nbsp;support.

**Comment by LeaVerou** [comment]
I'm wondering if we could start using CSS variables without completely dropping IE11 support. We could use PostCSS or something to add fallbacks, and IE11 would just use those fallbacks. So people on IE11 would still get highlighting, just not customized highlighting. Would that make sense?

**Comment by RunDevelopment** [comment]
[Microsoft is retiring IE11 in June **2022**](https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/).

**Comment by joshgoebel** [comment]
Are you planning to support it until then?

**Comment by RunDevelopment** [comment]
Given the current progress on v2, I can't blame you for thinking that but no :)

**Comment by mAAdhaTTah** [comment]
Technically, dropping IE11 support is a breaking change, so we really _should_ support it until then, unfortunately.

**Comment by mAAdhaTTah** [comment]
Unless I misunderstood the comment/question. To rephrase, v1 should support IE11. v2 was never intended to. So really, we'll support IE11 until whenever v2 gets out. Or at least, that's what I think we should do.

**Comment by RunDevelopment** [comment]
> To rephrase, v1 should support IE11. v2 was never intended to.

Yup, that's pretty much it. We'll support IE11 for the whole of v1.x and then drop it in v2.0.0.

**Comment by ljharb** [comment]
"users stop using it" is a date that is not tightly correlated to "a company stops supporting it".

**Comment by LeaVerou** [comment]
Yup, agreed too. Whoever needs IE11 support can just stay on v1.

**Comment by RunDevelopment** [comment]
IE11 is dropped in v2.

**Comment by xjArea** [comment]
I don't think it's a problem to delete IE11 in V2, but I recently updated Prism.js and found that V1 can't be used in IE11. Check the error and find that it's a RexExp problem. In V1.25.0, IE11 still OK, but V1.26.0 will report an error, so is it not supported in advance ? 😭

**Comment by LeaVerou** [comment]
> I don't think it's a problem to delete IE11 in V2, but I recently updated Prism.js and found that V1 can't be used in IE11. Check the error and find that it's a RegExp problem. In V1.25.0, IE11 still OK, but V1.26.0 will report an error, so is it not supported now ? 😭

Can you please file this as a new bug? This is not intentional.

**Comment by xjArea** [comment]
file this as a new bug : <https://github.com/PrismJS/prism/issues/3558>
