### ISSUE TITLE
Wrong single quote

### ISSUE THREAD

**Issue by bilalmalkoc** [PrismJS/prism#1580]
When i put a php code ie.:

`<?php echo 'hello world'; ?>`

It shows like this with wrong quotes.

`<?php echo ‘hello world’; ?>`

**Comment by RunDevelopment** [comment]
Could you please explain the issue?
All I can see is Prism not highlighting incorrect syntax, which is to expected.

![image](https://user-images.githubusercontent.com/20878432/46665052-f5a31600-cbc2-11e8-9c40-29aa2b10bfec.png)

**Comment by Templarian** [comment]
@bilalmalkoc You probably need to disable smart quotes in your CMS (not sure what one you're using but a few have this feature).

**Comment by bilalmalkoc** [comment]
It can be related my cms. Idk. It is wordpress. But i put normal and italic quotes. All way to out italic. But i am glad to it is not prism error.

**Comment by RunDevelopment** [comment]
@bilalmalkoc @mAAdhaTTah Can this issue be closed?
