### ISSUE TITLE
Highlighting issue with PHP when code contains xml snippet

### ISSUE THREAD

**Issue by nterray** [PrismJS/prism#1582]
Hello,

With the following code:

```php
<?php

  echo '<?xml version="1.0" encoding="UTF-8"?><tracker />';
  echo PHP_EOL;

```
PrismJS does not syntax highlight the second statement (and the following ones, if any).

Tested on PrismJS 1.15.0

Best regards,
Nicolas

**Comment by mAAdhaTTah** [comment]
"Second statement" in the above example is the `echo PHP_EOL;` line?

**Comment by nterray** [comment]
Yes

**Comment by nterray** [comment]
Thanks for the fix!

Do you have any approximation date when it will be released?

**Comment by RunDevelopment** [comment]
You can create your own bundle on the [download page](https://prismjs.com/download.html) to get it right now.

We don't have a date for the new release yet (#1713).
