### ISSUE TITLE
Support for comments in JSON

### ISSUE THREAD

**Issue by mariusschulz** [PrismJS/prism#1590]
What's your take on supporting single-line and block comments in JSON? Several popular projects (e.g. TypeScript) allow comments in JSON configuration files:

```json5
{
  "compilerOptions": {
    "target": "es5",      /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */
    "module": "commonjs", /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    // "lib": [],         /* Specify library files to be included in the compilation. */
    // "allowJs": true,   /* Allow javascript files to be compiled. */
    // "checkJs": true,   /* Report errors in .js files. */
    // "jsx": "preserve", /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */

    // ...
}
```

Although the JSON spec doesn't include comments, I think it would be helpful to have support for them in Prism; comments can be particularly helpful in technical blog posts.

What do you think? I'll be happy to send a PR! :)

**Comment by mAAdhaTTah** [comment]
I don't know as we need to modify JSON; if you want comments, couldn't you use the JS language instead? I also find most of the editors I use don't highlight comments in JSON files correctly.

That said, I'm open to being convinced otherwise.

**Comment by mariusschulz** [comment]
That's exactly what I did to unblock myself for now. I highlighted my code example using the JS language, but the results aren't great since quoted properties and string literals use the same color:

![A JSON object that was highlighted using the JS language](https://i.imgur.com/5XrmF7h.png)

If you feel uncomfortable extending JSON directly, we could introduce a new [JSON5](https://json5.org/) language that extends the existing JSON language. However, I'd prefer to add comments to JSON directly so that we can use comments to indicate that some parts have been omitted:

```json5
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    // ...
}
```

**Comment by mariusschulz** [comment]
For further consideration, here's what the above screenshot would look like if the JSON language supported comments. I think it looks much better! 

![A JSON object that was highlighted using the JSON language with support for comments](https://i.imgur.com/yYH89Ed.png)

We could reuse the comment patterns from the `clike` language:

```diff
Prism.languages.json = {
+  comment: [
+    {
+      pattern: /(^|[^\\])\/\*[\s\S]*?(?:\*\/|$)/,
+      lookbehind: true
+    },
+    {
+      pattern: /(^|[^\\:])\/\/.*/,
+      lookbehind: true,
+      greedy: true
+    }
+  ],
  property: /"(?:\\.|[^\\"\r\n])*"(?=\s*:)/i,
  string: {
    pattern: /"(?:\\.|[^\\"\r\n])*"(?!\s*:)/,
    greedy: true
  },
  number: /-?\d+\.?\d*([Ee][+-]?\d+)?/,
  punctuation: /[{}[\],]/,
  operator: /:/g,
  boolean: /\b(?:true|false)\b/i,
  null: /\bnull\b/i
};
```

**Comment by RunDevelopment** [comment]
Using the comments pattern from C-like will work but since JS (and therefore JSON) does not have all syntactical features of C, we can simplify the pattern. This should also work:

```js
'comment': /\/\/.*|\/\*[\s\S]*?(?:\*\/|$)/
```

Also, `property` has to be greedy because it is not the first pattern anymore.

**Comment by mariusschulz** [comment]
Closing this issue, now that support has landed in https://github.com/PrismJS/prism/pull/1595.
