### ISSUE TITLE
Julia: number pattern captures non-numbers such as a, b, dad, deadbeef

### ISSUE THREAD

**Issue by bit-player** [PrismJS/prism#1614]
In the Julia code snippet (x + y) / (a - b), the 'x' and 'y' are correctly left unstyled but the 'a' and 'b' are treated as numbers:

`<code class=" language-julia">
<span class="token punctuation">(</span>
 x 
<span class="token operator">+</span>
 y
<span class="token punctuation">)</span> 
<span class="token operator">/</span> 
<span class="token punctuation">(</span>
<span class="token number">a</span> 
<span class="token operator">-</span> 
<span class="token number">b</span>
<span class="token punctuation">)`

The problem appears to lie in the pattern fragment (?:0[box])?(?:[\da-f]+\.?\d*|\.\d+). Because of the question mark at the end of (?:0[box])?, the pattern matches not only '0xa' (which is a genuine number literal in Julia) but also 'a' (which is not a Julia number). Indeed, any string made up of the first six characters of the alphabet will be classified as a number. The simpler pattern (?:0[box][\da-f]+\.?\d*|\.\d+) should fix this error, but I'm not yet sure it doesn't introduce other problems.

I would also point out that the present regex allows various syntactic impossibilties to be recognized as numbers, such as 0b789abc, but perhaps that's an issue for another issue.

**Comment by mAAdhaTTah** [comment]
Thanks for raising the issue. If you've got a fix, would you be willing to open a PR with it? You can confirm if it introduces other issues with the test suite.

**Comment by RunDevelopment** [comment]
@bit-player I cannot reproduce your issue. It works perfectly fine on my side (using [Prism test drive](https://prismjs.com/test.html)) because the pattern fragment you showed is preceded by [`(?:\b(?=\d)|\B(?=\.))`](https://github.com/PrismJS/prism/blob/master/components/prism-julia.js#L9), so it is guaranteed that the first character of a number is a decimal digit or a decimal dot.

Is your version of Prism up to date?

**Comment by bit-player** [comment]
@RunDevelopment Right you are! The copy of Prism I updated was not the copy loaded into the page. Sorry for the distraction.
