### ISSUE TITLE
not supporting '<' operator

### ISSUE THREAD

**Issue by suvamkundu** [PrismJS/prism#1621]
No language is supporting < operator. Whenever prism is executing it is breaking the code from the place '<' is used. I have tried Python, Javascript, and C#. All of them working the same way and I have used the unescaped markup plugin for HTML also. But at the end, the code is not showing after '<' operator. Can you please give me any hint on this?

**Comment by suvamkundu** [comment]
@RunDevelopment I have done that too. Not helping.

**Comment by suvamkundu** [comment]
![hjghjghjghj](https://user-images.githubusercontent.com/26181202/48713989-ae835880-ec37-11e8-9cbc-aef5440c1344.png)
As you can see here, the content inside code block is that.

**Comment by RunDevelopment** [comment]
You seem to be using some kind of UI/CMS (I don't recognize it). 
Prism itself works (I use it myself) and said utility function is definitely executed. So what you are using to add the code or some steps afterward cause the problem.

**Comment by suvamkundu** [comment]
thanks for responding @RunDevelopment. If util is replacing it then why should I do it again? and the current content inside the HTML is this -

  <pre class="line-numbers language-javascript" contenteditable="false" id="ateu489fdc63bd5501d00f74f85e6ced">
     <code class="language-javascript" id="luilc9934f747a7932bd37221ac3cd62" style="white-space: pre-wrap !important;">
	       jQuery("#setRowsModal").find(".grid-vals").each(function() { //check if inputs are valid
           var thisVal = jQuery(this).val();
           if (thisVal &amp;&amp; thisVal &lt; 12) { //Value cannot be equal to 12 as atleast 2 rows are required
				  var val = parseInt(thisVal);
				  vals.push(val);
				  var cls = "col-md-" + val; //Create class name from the input value
            } else {
                  valid = false;
                  return false;
            })
	 </code>
  </pre>

**Comment by abulka** [comment]
I too noticed swathes of code being lost when viewed using Prism, till I stumbled across this Github issue and realised that I had to always replace the `<` character of source code being displayed in html.  For example the following Python code gets prematurely chopped:
  <pre>
        <code class="language-python">
    class Automaton:
        kernel_core = {
            0: lambda r: (4 * r * (1-r))**4,  # polynomial (quad4)
            3: lambda r, q=1/4: (r>=q)*(r<=1-q) + (r&lt;q)*0.5 # staircase (life)
        }
    
        def __init__(self, world):
            pass
        </code>
    </pre>
unless I first run the javascript on the source code code fragment `data` before injecting it into my html

    data.replace(/\</g, '&lt;') ;

which fixed the problem for me.

**Comment by ExE-Boss** [comment]
@abulka Are you using `element.innerHTML` instead of `element.textContent` to insert visual code into the document?

**Comment by abulka** [comment]
My html

    <div id="source_code_preview">
    </div>

My javascript dynamically inserting the prism highlighted source code.  All works ok.

    var preview = $("#source_code_preview")
    preview.empty()

      preview.append(
        '<div class="prism_wrapper""><pre><code class="language-python" id="' +
          id +
          '">' +
          data.replace(/\</g, '&lt;') +
          "</code></pre></div>"
      )

**Comment by ExE-Boss** [comment]
@abulka You need to do:

```js
let preview = $("#source_code_preview");
preview.empty();

let wrapper = $('<div class="preview_wrapper"><pre><code class="language-python"></code></pre></div>');
let code = wrapper.find("code");
code.attr("id", id);
code.text(data);

preview.append(wrapper);
```

**Comment by volado** [comment]
@ExE-Boss is [right](https://github.com/PrismJS/prism/issues/1621#issuecomment-447618154).

The only correction is that you have to wrap `$.parseHTML()` in `$()`:

```javascript
let wrapper = $($.parseHTML('<div class="preview_wrapper"><pre><code class="language-python"></code></pre></div>'));
```

Additionally, `code.text(data)` relies on `textContent`, which [helps to prevent XSS](https://www.owasp.org/index.php/DOM_based_XSS_Prevention_Cheat_Sheet#RULE_.236_-_Populate_the_DOM_using_safe_JavaScript_functions_or_properties). `append(data)` and `data.replace(/\</g, '&lt;')` don’t do the trick.

**Comment by ExE-Boss** [comment]
I&nbsp;would’ve thought that jQuery would pre&#x2011;wrap the result of&nbsp;`$.parseHTML(…)`.

**Comment by volado** [comment]
It would be logical. But [`$.parseHTML()`](https://api.jquery.com/jQuery.parseHTML/) returns an array of DOM nodes.

**Comment by RunDevelopment** [comment]
I'm going to close this now, as it's not an issue caused by Prism.
