### ISSUE TITLE
How to prevent highlighting automatically on import?

### ISSUE THREAD

**Issue by vai0** [PrismJS/prism#1641]
This immediately initializes Prism and starts highlighting all code blocks on my page.
```
import Prism from "prismjs";
```

Is there a way to explicitly enable highlighting rather than having it highlight automatically on import?

**Comment by mAAdhaTTah** [comment]
Couple options:

1. Add `data-manual` to the script tag.
2. Manually remove the highlighting with `document.removeEventListener('DOMContentLoaded', Prism.highlightAll);`.

We need to document this still (#1402). That issues includes a link to the original PR where we discussed this.

**Comment by mAAdhaTTah** [comment]
I'm going to close as not an issue, but feel free to ask follow-up questions if you still need help.

**Comment by vai0** [comment]
That does it, thanks!
