### ISSUE TITLE
Any plans to put Mathematica highlighting in?

### ISSUE THREAD

**Issue by ben18785** [PrismJS/prism#1647]
Thanks for the great software by the way -- really useful!

**Comment by mAAdhaTTah** [comment]
We're always open to pull requests if you're interested. Happy to answer any questions if you need help.

**Comment by msollami** [comment]
@mAAdhaTTah I've added basic support for this language on a local branch, how does your team do PRs?

**Comment by msollami** [comment]
@RunDevelopment Done, thanks!

**Comment by RunDevelopment** [comment]
Thanks to @msollami (#2921), this can finally be close! 🎉
