### ISSUE TITLE
Build actual releases

### ISSUE THREAD

**Issue by apfelbox** [PrismJS/prism#165]
Hi,

since there already are quite a lot of external libraries or tools which build on or include prism, it would be nice, if there were actual releases with release version numbers (preferably semver of course ;-) ).

Tools which build on prism:
* bower or other package managers (declare dependency by version number)
* Tools like [Prism Detached](https://github.com/apfelbox/Prism-Detached) (which includes prism in wordpress)

etc...

**Comment by apfelbox** [comment]
We now have a v1.0 :balloon:

**Comment by franz-josef-kaiser** [comment]
@apfelbox why the `v`? [Semver](http://semver.org) does not have the `v`. 

_(Still a big win as most package manager will recognize that as valid)_

**Comment by apfelbox** [comment]
@franz-josef-kaiser I didn't create the tag, I am just the announcer. ;)

I currently prefer it without the "v", but as practically all package manager handle both cases quite well, it is up to the personal taste of the maintainer.
