### ISSUE TITLE
Handlebars won't compile

### ISSUE THREAD

**Issue by thec0keman** [PrismJS/prism#1661]
Hi, I've been using a build from the [homepage](https://prismjs.com/download.html#themes=prism-okaidia&languages=markup+clike+javascript+markup-templating+handlebars+pug) that includes handlebars in a web browser.  When I run any markup through it, HTML comes through just fine, but Handlebars is replaced with placeholders.

JS:
```
  get highlighted() {
    return Prism.highlight(this.code, Prism.languages.handlebars, 'handlebars');
  }
```

Handlebars:
```
{{my-form name=(mut model.name)}}
<button class="large {{foo}}">
  x
</button>
```

Output:
```
___HANDLEBARS0___
<button class="large ___HANDLEBARS1___">
  x
</button>
```

When I try this same code in the [test tool](https://prismjs.com/test.html) it works just fine, so I'm at a loss as to what is different from my code.

Are there any ways of debugging this, or any possible differences between the downloaded build and the test tool?

Thanks!

**Comment by mAAdhaTTah** [comment]
Make sure you have the latest version. [This](https://github.com/PrismJS/prism/pull/1367) may have fixed the issue.

**Comment by thec0keman** [comment]
The bundle does say it is running 1.15, but I was thinking of building manually and see if that is any different.

**Comment by RunDevelopment** [comment]
There is a difference between the test page and the download link you provided.
The test page uses the unminified Prism files and the download page uses the minified ones by default, so there could be a problem with the minification process but this is _highly_ unlikely. 
(I just tested the minified files using you [download link](https://prismjs.com/download.html#themes=prism-okaidia&languages=markup+clike+javascript+markup-templating+handlebars+pug) and everything worked.)

Can you please verify that the [`after-tokenize` hook](https://github.com/PrismJS/prism/blob/master/components/prism-handlebars.js#L34) is run. (You will find this function somewhere in you `prism.js` file.)

Are you using any plugins?

**Comment by thec0keman** [comment]
I realize my mistake, thanks for helping me debug!

I had all of the pieces I mentioned above, but I forgot I also had a WIP ES6 import that was stomping on the `after-tokenize` hook.

Thanks again!
