### ISSUE TITLE
How to match the beginning of each line in language js file?

### ISSUE THREAD

**Issue by sgon00** [PrismJS/prism#1675]
# My solution

I figured out the following works (I added a new language called `prism-shell.js`):

```
Prism.languages.shell = {
    'promptString': {
      pattern: /(^|\n)[\w\d\[(@-]*((?!^)\ )?[\])~\/\w\d]*[>%$#]/,
      lookbehind: true
},
```

Is this `(^|\n)` the right way to match the beginning of each line for Prismjs? So far it works well. ^_^

I did many modifications, my complete code is at https://gist.github.com/sgon00/836386ba8b16e95297e4e5aa0a7089ae.

# Old Story

Hi, I am using [MacDown](https://github.com/MacDownApp/macdown) which uses Prism for language syntax highlight. Because of markdown limitation, I can not use the prism plugin [command-line](https://prismjs.com/plugins/command-line/), so I am trying a workaround to modify the `prism-bash.min.js` to work with terminal shell. I have the following modification:

```js
Prism.languages.bash = {
    'namespace': {
      pattern: /^\s{0,3}[\w\d\[\]()@-]*[>%$#]/,
      alias: 'important',
    },
    'comment': {
      pattern: /(^|[^"{\\])#.*/,
      lookbehind: true
    },
```

I added the new `namespace` token (learnt from `prism-powershell.js`). <s>But the problem is, it's working with `$ ls`, but it dosn't work with `# ls`. `# ls` will match comment first before matching the namespace. How can I let `# ls` matches my `namespace` instead of the comment? Thanks a lot. </s>

Btw, I know the workaround is not the right/best way to handle this situation. But I am OK to use this workaround for now. Thanks. 

**Edited:**

Actually, I was wrong. the `namespace` I gave only matches the first `$` or `#` in the first line. so

```
$ ls
```

```
# ls
```

work, but the following does not work:

```
$ ls
$ ls
```

I have no idea why...

**Edited 2:**

It seems this is because `^` matches the beginning of the entire block instead of the beginning of each line. How to match the beginning of each line? Thanks a lot.

**Comment by RunDevelopment** [comment]
> Is this (^|\n) the right way to match the beginning of each line for PrismJS?

No, use `^` in combination with the [`m` flag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Parameters). This flag changes the meaning of `^` and `$` from _start of text_ and _end of text_ to _start of line_ and _end of line_.

That should solve all of your other problems as well.

And one hint: `^\s{0,3}[\w\d\[\]()@-]*[>%$#]` can include up to 3 line breaks (even with the `m` flag), meaning that `"\n\n\n#"` will match. [`\s`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#character-classes) also includes line breaks, so `^[ \t]{0,3} ...` will probably serve you better.

**Comment by sgon00** [comment]
@RunDevelopment Thank you very much for your reply. After your comment, I have changed my pattern to be `pattern: /^[\w\d\[(@-]*((?!^)\ )?[\])~\/\w\d]*[>%$#].*/m` now. It works well so far. My complete js code is at https://gist.github.com/sgon00/836386ba8b16e95297e4e5aa0a7089ae. I did many modifications. I am new to all of these. So I am not sure if my solution is the proper way to handle it or not. but so far, it works well. Just one more weird behavior. I don't know why I need to add `\n` to `'cmdOut': /\n.*/,`. I thought `.*` should work, but it doesn't. Thanks a lot and closing this issue.
