### ISSUE TITLE
npm publish anytime soon?

### ISSUE THREAD

**Issue by jiantosca** [PrismJS/prism#1713]
Howdy - Any plans to get a newer version published to npm? I love the update in http lang from Dec and hope to see it on npm.

**Comment by mAAdhaTTah** [comment]
Yeah, we should do this soon. I've been meaning to take a pass over @RunDevelopment's PRs as well–definitely some good things in there. I'll see about doing that and cutting a release soon.

In the meantime, you can always download the latest version of Prism from the download page: https://prismjs.com/download

**Comment by jiantosca** [comment]
Cool, sounds good!

**Comment by pgilad** [comment]
In the meantime, as it seems the `npm` release is taking forever, I use this receipt in my `package.json`:

`"prismjs": "PrismJS/prism#master"`.

It's annoying because it makes the `install` step slower, but it works directly from git.

**Comment by mAAdhaTTah** [comment]
🎉 [1.16.0](https://github.com/PrismJS/prism/releases/tag/v1.16.0) is finally released! 🎉
