### ISSUE TITLE
`insertBefore` should check that `before` exists

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#1717]
[Details](https://github.com/PrismJS/prism/pull/1677#discussion_r249607614)

**Comment by mAAdhaTTah** [comment]
**Summary:**

The issue I had is shipping code to users that will never execute if the languages are coded up correctly.

Potential suggestions:

1. ESLint plugin to make sure those values are valid.
2. External test to validate param exists.

**Comment by ExE-Boss** [comment]
I think it should print a&nbsp;warning or&nbsp;an&nbsp;error in&nbsp;the&nbsp;development console.
