### ISSUE TITLE
Greedy rule not working

### ISSUE THREAD

**Issue by sourabhv** [PrismJS/prism#1720]
I added a rule in prism to parse anything like `@@@something here@@@` as a custom token but in some cases it doesn't work. I am using prism in react-native through https://github.com/FormidableLabs/prism-react-renderer

```javascript
  Object.values(defaultProps.Prism.languages).forEach(lang => {
    lang['gap'] = {
      pattern: /\?\?\?/,
      greedy: true,
    };
    lang['delim'] = {
      pattern: /(?:@{3})((?:(?!@{3}).)*)(?:@{3})/,
      greedy: true,
    };
  });
```

But for this line the rule doesn't work. 

    let line = `Stay @@@${attr2}@@@ Stay ???`

It does work though if I remove ` and change line to 

    let line = Stay @@@${attr2}@@@ Stay ???

I guess this is happening because the rule for string in first case is also greedy? Is there a way to make this work? Here's the tokenised line for first case, if it's helpful:

<details><summary>Tokens</summary><p>

```
[
  {
    "types": [
      "plain"
    ],
    "content": ""
  },
  {
    "types": [
      "keyword"
    ],
    "content": "let"
  },
  {
    "types": [
      "plain"
    ],
    "content": " line "
  },
  {
    "types": [
      "operator"
    ],
    "content": "="
  },
  {
    "types": [
      "plain"
    ],
    "content": " "
  },
  {
    "types": [
      "variable"
    ],
    "content": "`"
  },
  {
    "types": [
      "variable"
    ],
    "content": "Stay @@@$"
  },
  {
    "types": [
      "variable",
      "punctuation"
    ],
    "content": "{"
  },
  {
    "types": [
      "variable"
    ],
    "content": "attr2"
  },
  {
    "types": [
      "variable",
      "punctuation"
    ],
    "content": "}"
  },
  {
    "types": [
      "variable"
    ],
    "content": "@@@ Stay ???"
  },
  {
    "types": [
      "variable"
    ],
    "content": "`"
  }
]
```

</p></details>

&nbsp;

**EDIT:**

It also works for 

        let line = `Stay @@@${attr2}@@@ Stay @@@${attr2}@@@`

but instead captures `@@@ Stay @@@` as a group

**Comment by RunDevelopment** [comment]
What language are you using to tokenize the code snippets?

Also, is that token stream something from prism-react-renderer?

**Comment by sourabhv** [comment]
I'm using `javascript`, and not sure where the token stream is coming from.

I just tried using this and it worked:

```javascript
      Prism.languages.insertBefore('javascript', 'keyword', {
        'question-gap': {
          pattern: /\?\?\?/,
          greedy: true,
        },
        'question-delim': {
          pattern: /(?:@{3})((?:(?!@{3}).)*)(?:@{3})/,
          greedy: true,
        },
      });
```

I picked `keyword` randomly because I saw it in the token stream above. Is there a way to insert my rule as the very first rule?

**Comment by RunDevelopment** [comment]
What really bugs me is that the token stream you posted for the first example does not contain `template-string` tokens. The `variable` tokens are also very strange, mainly because the JS grammar does not contain a `variable` pattern.

That tells me one of two things: Either you are using the wrong grammar to highlight your code (unlikely but maybe) or something modifies the JS grammar beside you.

What other languages do you have for Prism?
Could you please tell me the result of this: `Object.keys(Prism.languages.javascript)`?

> Is there a way to insert my rule as the very first rule?

Yes, using `insertBefore`:

```js
Prism.languages.insertBefore('javascript', Object.keys(Prism.languages.javascript)[0], {
        // tokens
});
```

But if you want to highlight things inside of template strings like here

```js
let line = `Stay @@@${attr2}@@@ Stay @@@${attr2}@@@`
```

then you should insert these pattern in `Prism.languages.javascript['template-string'].inside`.

**Comment by sourabhv** [comment]
Maybe prism-react-renderer is changing them or it's possible I logged something internal to their library and not prism's.

So I wanted that rule to work before every other rule in every language and tried this snipped and it seems like it's working.

```javascript
const rules = {
  gap: {
    pattern: /\?\?\?/,
    greedy: true,
  },
  delim: {
    pattern: /(?:@{3})((?:(?!@{3}).)*)(?:@{3})/,
    greedy: true,
  },
};
Object.keys(Prism.languages)
// there are 3 funcs in every lang definition. This is to remove them
.filter(lang => typeof Prism.languages[lang] === 'object')
.forEach(lang => {
  const language = Prism.languages[lang];
  const firstRule = Object.keys(language)[0];
  Prism.languages.insertBefore(lang, firstRule, { ...rules });
  Object.keys(language)
    .filter(ruleKey => {
      const rule = language[ruleKey];
      return (
        rule.inside &&
        typeof rule.inside === 'object' &&
        Object.keys(rule.inside).length > 0
      );
    })
    .forEach(ruleKey => {
      language[ruleKey].inside = {
        ...rules,
        ...language[ruleKey].inside,
      };
    });
});
```

**Comment by RunDevelopment** [comment]
To handle the `inside` properties, I recommend using `Prism.languages.DFS`, which can be used to also modify nested `inside`s like so:

```js
Prism.languages.DFS(Prism.languages, function (key, value) {
    if (key === 'inside') {
        this[key] = { ...rules, ...value };
    }
});
```

This snippet will handle all languages at once, so you can remove the `Object.keys(language)` chain and insert this after `.forEach(lang => ...)`.

**Comment by sourabhv** [comment]
Works like a charm. Thanks for all the help :) I'll close this issue now.
