### ISSUE TITLE
What about providing a CDN ?

### ISSUE THREAD

**Issue by RomainSauvaire** [PrismJS/prism#174]
It can help us to keep the latest version possible in sync on our servers and reduce the load while parallelizing.
The guys from CDNJS could do that easily : https://github.com/cdnjs/cdnjs

**Comment by loganfranken** [comment]
As mentioned in #158, this is done:
https://github.com/PrismJS/prism/issues/158

So I agree with @apfelbox that we should close this.

**Comment by loganfranken** [comment]
@Golmote I think we can close this; #158 has the discussion on releasing a new version out to CDN JS (which is the next step for this)

**Comment by Golmote** [comment]
Yup. Discussion goes on in #158.
