### ISSUE TITLE
Smalltalk empty string not handled correctly

### ISSUE THREAD

**Issue by bencoman** [PrismJS/prism#1746]
Smalltalk empty strings are not handled correctly. Case example...
```
anObject withEmptyString: ''  shouldNotBeGreenHere: 'shouldBeGreenHere'
```

https://prismjs.com/test.html shows incorrect...
![image](https://user-images.githubusercontent.com/1713447/52901770-94f7aa00-3242-11e9-9f2d-b09b0dac1ad2.png)

http://rouge.jneen.net/ shows correct...
![image](https://user-images.githubusercontent.com/1713447/52901757-772a4500-3242-11e9-87cf-f4b7c5f423b6.png)

**Comment by bencoman** [comment]
I'm guessing this is the pertinent test file...
https://github.com/PrismJS/prism/blob/master/tests/languages/smalltalk/string_feature.test

which should maybe be like this...
```
''
'foobar'
'foo''bar
baz'
----------------------------------------------------
[
	["string", "'''"],
	["string", "'foobar'"],
	["string", "'foo''bar\r\nbaz'"]
]
```

**Comment by RunDevelopment** [comment]
I hope that #1747 works for you!

If you were to find any other incorrectly highlighted code snippets, please feel free to open another issue!

**Comment by bencoman** [comment]
@RunDevelopment thankyou for the fix.
