### ISSUE TITLE
Highlight for Dockerfile

### ISSUE THREAD

**Issue by SilencerWeb** [PrismJS/prism#1749]
You seem to have it but it is definetly something wrong with it

![image](https://user-images.githubusercontent.com/20713191/52912941-5a415080-32da-11e9-93a7-2385f1f80e0a.png)

I downloaded a full version of Prismjs with plugins Line Numbers and Highlight Keywords.

Code from the screenshot:
```Dockerfile
kind: pipeline
steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test
services:
- name: database
  image: mysql
  ports:
  - 3306
```

**Comment by RunDevelopment** [comment]
Isn't that [YAML](https://yaml.org/) and not a [docker file](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)?

**Comment by SilencerWeb** [comment]
@RunDevelopment, you are right, I'm sorry for this, I mixed up file extensions :(
