### ISSUE TITLE
Known failures page?

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#1750]
Right now, known failures are documented on the examples page of the language. (So languages also have comments in their definitions. E.g. Less)

Wouldn't it be good to have __one__ page where all known failures are documented?

Thoughts?

**Comment by ExE-Boss** [comment]
I&nbsp;agree with this, because when I&nbsp;wanted to&nbsp;see all known failures, I&nbsp;had to&nbsp;load all language examples and&nbsp;use&nbsp;<kbd>ctrl+F</kbd>.

**Comment by Golmote** [comment]
Agreed. Do remember, though, that currently each language has its own simple HTML page for examples and failures. We lack a standard way of providing those.
