### ISSUE TITLE
groovy highlight issue(jenkinsfile)

### ISSUE THREAD

**Issue by nealwon** [PrismJS/prism#1751]
This block are in quote`/bin/cp -a -f ${env.WORKSPACE}/* ${env.GOPATH}/${env.PROJECT_PATH}/`, but separated by '/*', before this are in quote, others are highlighted as comments!

![image](https://user-images.githubusercontent.com/643826/52983915-2a07c800-3428-11e9-973e-c90fa3d35e21.png)

**Comment by RunDevelopment** [comment]
Cannot reproduce.

![image](https://user-images.githubusercontent.com/20878432/53010924-6bf03880-343f-11e9-982f-bb5429c96dca.png)

Test code:

```groovy
// copy code to the dir
sh "/bin/cp -a -a ${env.WORKSPACE}/* ${env.GOPATH}/${env.PROJECT_PATH}/"
// highlighting error, so here must add an '*/'
```

Are you using the latest version of Prism? Are you using any plugins?
Could you please provide the full example, if possible. Maybe the _cause_ of the error lies somewhere else in the code.

**Comment by nealwon** [comment]
OK!

But I still have this issue, maybe my develop environment is damaged.
