### ISSUE TITLE
Don’t remove HTML from unknown languages

### ISSUE THREAD

**Issue by ExE-Boss** [PrismJS/prism#1761]
Older Prism releases (circa&nbsp;1.2) keep all in&#x2011;code markup, thus allowing statically written syntax&nbsp;highlighting, like what can&nbsp;be&nbsp;seen in&nbsp;the&nbsp;source of&nbsp;the&nbsp;https://developer.mozilla.org/en-US/docs/MDN/Contribute/Tools/KumaScript$revision/1455355 page.

After the&nbsp;upgrade to&nbsp;Prism&nbsp;1.15, this&nbsp;broke and&nbsp;HTML is&nbsp;now always stripped.

**Comment by RunDevelopment** [comment]
Check out the [Keep Markup plugin](https://prismjs.com/plugins/keep-markup/) for this.

**Comment by ExE-Boss** [comment]
But **Keep&nbsp;Markup** doesn’t do&nbsp;what I&nbsp;want which is to remove all `<span class="token *">` markup for known languages, but&nbsp;keep it&nbsp;for&nbsp;unknown languages.

**Comment by RunDevelopment** [comment]
Ok, I see your issue but I don't think that Prism should just ignore element with languages it doesn't know.

How about a CSS class which makes Prism ignore the element in `highlightAllUnder` and `highlightAll`? Something like `prism-ignore`?

**Comment by RunDevelopment** [comment]
Another way would be to use hooks to basically "get around" highlighting, but that's a little hacky.

**Comment by ExE-Boss** [comment]
A good default would be&nbsp;to&nbsp;automatically skip highlighting elements which have an&nbsp;unknown language inside `highlightAll` (but&nbsp;still add&nbsp;line&nbsp;numbers).

**Comment by RunDevelopment** [comment]
```js
Prism.hooks.add('before-insert', function (env) {
	env.highlightedCode = env.element.innerHTML;
});
```

This will still execute all plugins (might have problems with command line) AND keep the markup.
With a bit of overhead tho.

**Comment by RunDevelopment** [comment]
> A good default would be to automatically skip the `highlightElement` call for elements which have an unknown language inside `highlightAll` and `highlightAllUnder` (but still add line numbers).

The hooks of plugins like line numbers are executed by `highlightElement`, so we can't just skip them (unfortunately).

**Comment by Golmote** [comment]
I remember that, at some point, we indeed added missing hooks calls on unknown language code blocks, cause their absence was considered an issue. Also it feels more predictable to handle all code blocks the same way.
I believe the current behaviour is the proper one. So you'll want to find a way around it using hooks or something, as RunDevelopment said. We can probably still add hooks or hook properties or even actual features, if need be, to make this possible though.

**Comment by RunDevelopment** [comment]
I will close this issue since we now have the [Filter highlightAll plugin](https://prismjs.com/plugins/filter-highlight-all/) which can be used to ignore code blocks with an unknown language, solving the issue.
