### ISSUE TITLE
JSDoc: Generated documentation

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#1777]
Why don't we use [JSDoc](https://github.com/jsdoc3/jsdoc) to add generated code documentation to the [prismjs.com](https://prismjs.com/index.html) website? I'm thinking about something like `prismjs.com/docs/`.

The generated documentation will include all _documented variables/functions_ of `components/prism-core.js`. Functions that aren't documented won't show up in the doc.
I already tested this a little and it works quite well.

This is intended to replace the API section of [extending Prism](https://prismjs.com/extending.html#api) to keep Core and its documentation more in sync to avoid issues like #1774.

(We can also use this include API docs for plugins and components like markup templating in the future.)

Thoughts?
@mAAdhaTTah @Golmote @LeaVerou

**Comment by RunDevelopment** [comment]
I will gladly setup JSDoc and document `prism-core.js`.
Just tell me if we want this.

**Comment by LeaVerou** [comment]
No strong opinions, but is our API large enough to warrant something like this?
On the other hand, keeping things DRY is always a good argument.

**Comment by Gahen** [comment]
I gave a look at the #1782 PR thread and saw that JSDoc may not be coming soon. As a user of this library I would love to have a bit more throughtfull documentation.

Maybe until that is done we can compile a list of things to improve on the doc and push that forward? Just having a complete documentation of the main API methods, probably in a separate page, would be enough IMO.

Maybe on top of something like https://docsify.js.org/ with a couple of `.md` files? Looking at the `prism-core.js` file it doesn't seem to be a lot of work, I can make a PR with an initial version (doc folder with some .md files) if you think it would make sense.

**Comment by RunDevelopment** [comment]
@Gahen I re-did #1782 and we might be able to merge it within the next few days.

**Comment by Gahen** [comment]
Thank you @RunDevelopment :heart:
