### ISSUE TITLE
List of language types

### ISSUE THREAD

**Issue by brendanfalkowski** [PrismJS/prism#178]
Is there a list of supported class="language-xxx" values?

I spent about 15 minutes looking through the site and GitHub issues, but couldn't find this anywhere.

Namely, ran into this issue trying to use "language-html" which is actually "language-markup". Seems like an odd choice given that every other language uses its abbreviation.

**Comment by loganfranken** [comment]
This is done here:
http://prismjs.com/#languages-list

So I think this can be closed?

**Comment by brendanfalkowski** [comment]
Yep, that works. Thanks!

**Comment by imabot2** [comment]
For those who are looking for a drop-down (`<select><option>`) list of supported languages, it can be found here : [https://ans.wiki/q/ou-trouver-une-liste-deroulante-des-languages-supportes-par-prism/](https://ans.wiki/q/ou-trouver-une-liste-deroulante-des-languages-supportes-par-prism/)

**Comment by loopmode** [comment]
I think I will have a prebuild script in my project, read node_modules/prismjs/components and writes it to a file module. Especially with typescript and `export const supportedLanguages = [...theLanguages] as const;` it's very useful to have such list explicitly. Too bad there is none "at the core".

**Comment by loopmode** [comment]
..created a module for that.. https://www.npmjs.com/package/create-prism-list

**Comment by suin** [comment]
I created the viewer of the list of supported languages. 

I hope this helps developers who are looking up it.

<img width="751" alt="List_of_supported_languages_by_Prism" src="https://user-images.githubusercontent.com/855338/81637559-a3d30980-9451-11ea-96f3-8ccebffd1bbc.png">

→ [List of supported languages by Prism](https://codepen.io/suin/full/XWmYZXz)

**Comment by clementohNZ** [comment]
I have written a small script that you can paste directly into your browser's console to get a full list of the most up to date languages.

It will output all the data as a JSON stringified array in a new tab, which you can copy and paste directly into your own files.

Hope it helps 😊

```js
const languageBlocks = document.querySelectorAll(`li[data-id]`)

const languages = []

languageBlocks.forEach((languageBlock) => {
  const langName = languageBlock.getAttribute(`data-id`)
  const langValue = languageBlock.querySelector(`code`).innerText

  languages.push({ name: langName, value: langValue })
})

const tab = window.open(`Prism Languages Array`, `_blank`)
tab.document.write(JSON.stringify(languages))
tab.document.close()
```

**Comment by webcog-pk** [comment]
http://prismjs.com/#languages-list

List o all Supported Languages by Prism.
