### ISSUE TITLE
Wrong GraphQL tokenization

### ISSUE THREAD

**Issue by 19majkel94** [PrismJS/prism#1786]
First of all, the GraphQL Support (#971) focus only on the client queries side, not the schema definition in SDL.

So there are a lot of missing keywords:

> schema, type, input, scalar, union, enum, interface, implements 

https://graphql.org/learn/schema/

Also, it tokenize the fields names as `attr-name` and not tokenize the field names with args:

![image](https://user-images.githubusercontent.com/10618781/53683231-b48cd900-3cfe-11e9-8332-1a6e761ed37e.png)

![image](https://user-images.githubusercontent.com/10618781/53683235-c1a9c800-3cfe-11e9-95e0-4c5b4aca4aa7.png)

It would be great if you could add support for it @Golmote 💪

**Comment by RunDevelopment** [comment]
Thank you for reporting!
