### ISSUE TITLE
Add buildsize bot

### ISSUE THREAD

**Issue by mAAdhaTTah** [PrismJS/prism#1787]
I'd love to be able to see the impact on the output size of various PRs. E.g. #1776 has some minor improvements that suggest it could be good for the build size but would be nice to have a bot confirm that for us, especially as build size is something we're generally concerned about overall.

**Comment by ExE-Boss** [comment]
https://github.com/PrismJS/prism/pull/1778 improved the&nbsp;code size&nbsp;too.

**Comment by mAAdhaTTah** [comment]
https://github.com/siddharthkp/bundlesize

**Comment by RunDevelopment** [comment]
That would be nice to have.
