### ISSUE TITLE
How can I unleash all supported code languages?

### ISSUE THREAD

**Issue by SetTrend** [PrismJS/prism#1789]
This is not a true issue, I'm afraid, but I didn't find help in the documentation nor did I receive an answer at [StackOverflow](https://stackoverflow.com/questions/54898260/prismjs-only-a-limited-number-of-code-languages-seem-available-how-to-unleash) to my question. So my last resort is to ask my question here:
<hr/>

I wanted to syntax highlight "c", but that doesn't seem to work with PrismJS. I only get syntax highlighting for "clike", but not for "c".

Examining the PrismJS object I can see that only 9 languages seem to be available:

![code languages supported by PrismJS](https://user-images.githubusercontent.com/9283914/53732102-2559ff80-3e7d-11e9-8195-5e9cf8e73602.png)

How can I access/unleash the other languages advertised?

**Comment by RunDevelopment** [comment]
These are all the default languages of the `prism.js` file.

To get other languages, go to the [download page](https://prismjs.com/download.html) and select the languages you need. You can then download your personal bundle which contains everything Prism needs to work and the languages you want.

For more details, see the [basic usage](https://prismjs.com/index.html#basic-usage) section.

**Comment by SetTrend** [comment]
I actually did.

I called `$ npm install prismjs --save-dev` and `import Prism from 'prismjs';` Still I am only getting these nine languages.

What am I doing wrong?

**Comment by RunDevelopment** [comment]
So you are using NodeJS to generate your website?

In that case, you can use the `loadLanguages` function to get the languages you want, as described in the [basic usage](https://prismjs.com/index.html#basic-usage) section.

**Comment by SetTrend** [comment]
Yes. I'm using [webpack](https://webpack.js.org/). It checks for dependencies and creates a single, bundled, JS file.

**Comment by SetTrend** [comment]
How would I get PrismJS load all the languages if I'd be using the CDN version instead of bundling PrismJS?

**Comment by mAAdhaTTah** [comment]
@SetTrend Under [Basic Usage](https://prismjs.com/#basic-usage) see the section on Webpack.

**Comment by SetTrend** [comment]
Yes, but as I wrote, it *doesn't* unleash all the languages.

**Comment by mAAdhaTTah** [comment]
Right now, the babel plugin doesn't have an "all" functionality. I filed https://github.com/mAAdhaTTah/babel-plugin-prismjs/issues/7 to track.

**Comment by deepak311997** [comment]
@SetTrend got any solution to load all languages?

**Comment by SetTrend** [comment]
No, unfortunately I'm still working on it. Though I didn't have an opportunity to work on the project until yesterday, incidentally.

I've set up a webpack project, but webpack's dynamic import functionality seems to fail with the PrismJS>Components>indesx.js>`loadLanguages()` function.

Currently I've filed an issue at StackOverflow on how to have webpack create `bundle.js` files for all the languages:
[stackoverflow.com/how-can-i-have-webpack-create-bundles-for-all-dynamically-imported-files](https://stackoverflow.com/questions/55485380/how-can-i-have-webpack-create-bundles-for-all-dynamically-imported-files)

If I won't get a solution there, I'll simply copy the PrismJS/components folder to my dist folder and have `loadLanguages()` require the files from there.

**Comment by Badlapje** [comment]
Neither the loadlanguages, nor the .babelrc approach, nor a combination of both worked for me.  I solved it by simply copying the language files i wanted from the components section and manually importing them ¯\_(ツ)_/¯

**Comment by firavoyage** [comment]
> Neither the loadlanguages, nor the .babelrc approach, nor a combination of both worked for me. I solved it by simply copying the language files i wanted from the components section and manually importing them ¯_(ツ)_/¯

same. i dont feel good...
