### ISSUE TITLE
Wrong line height with prism-coy.css theme in Microsoft Edge

### ISSUE THREAD

**Issue by logiclink** [PrismJS/prism#1790]
The coy theme doesn't have the right line height when rendered with Microsoft Edge 44.17763.1.0 (Microsoft EdgeHTML 18.17763) and the alternating blue and white background doesn't fit to text rows.
This bug doesn't occur in Forefox or Chrome.

![coy](https://user-images.githubusercontent.com/24712700/53807419-ca450d00-3f4f-11e9-9dc0-6704e75be7f2.png)

The reason is the missing unit of the line-height in "code[class*="language-"], pre[class*="language-"]" in line 17 of prism-coy.css. If changed from "line-height: 1.5;" to "line-height: 1.5em;" the Edge browser works fine.

**Comment by mAAdhaTTah** [comment]
Can you provide an online reproducible example?

**Comment by logiclink** [comment]
see helloworld_coy.html in the zip archive [helloworld_coy.zip](https://github.com/PrismJS/prism/files/2931455/helloworld_coy.zip), please open with Edge.

**Comment by RunDevelopment** [comment]
Seems like Edge doesn't calculate `line-height` correctly.
 
But isn't the real question why the Coy theme works on the prismjs.com website?
[Answer](https://github.com/PrismJS/prism/blob/master/style.css#L31): The indirect `font-size: 100%` saves Edge.
