### ISSUE TITLE
prism cant work

### ISSUE THREAD

**Issue by m4p1e** [PrismJS/prism#1797]
i just include prism
```html
<script type="text/javascript" src ="/prism/prism.js"></script>
```
but when i opened   the page ，in chrome console it show error 
`Uncaught TypeError: Cannot set property 'inside' of undefined`

the error part is

```javascript
Prism.languages.django.script.inside.string.inside = _django_template
```
i dont know why ， pls help me

**Comment by RunDevelopment** [comment]
Thank you for reporting!

This seems to be caused by #1660. I will fix this soon.
