### ISSUE TITLE
Without master branch, bower doesn't work

### ISSUE THREAD

**Issue by kud** [PrismJS/prism#180]
```
bower install prism --save-dev
bower not-cached    git://github.com/LeaVerou/prism.git#*
bower resolve       git://github.com/LeaVerou/prism.git#*
bower ENORESTARGET  Tag/branch master does not exist
```

**Comment by synapticism** [comment]
Prism is great! I also look forward to when it can be consumed via Bower without a workaround :+1:

**Comment by Robdel12** [comment]
Makes this hard to use with Ember CLI.

**Comment by brunobatista** [comment]
Need make a tag with the version `0.0.1` :+1:

**Comment by HarleyKwyn** [comment]
Would love to use this but I would love to not have to use the gh-pages branch. It's not semantic and makes it a pain to manage. Also proper semver would be great on bower distribution. You can do it with git-tags and if you need to you can also use an interactive rebase on a master branch to tag appropriately. I know it's a lot of work but it'll make your project much more successful.

**Comment by vkbansal** [comment]
@LeaVerou what @HarleyKwyn says is true. And its a huge public demand.
I'll be happy to help in maintaining the semver for this repo

**Comment by johnwilliams713** [comment]
Hi all. I'm seeing this error when trying to install with this:
bower install git@github.com:LeaVerou/prism.git\#gh-pages --save

Error:
Failed to execute "git ls-remote --tags --heads git@github.com:LeaVerou/prism.git", exit code of #128

**Comment by foxx** [comment]
Has this now been resolved as part of #25?

**Comment by Golmote** [comment]
There is still no "master" branch. So Bower will still require you to specify the "gh-pages" branch.

**Comment by foxx** [comment]
I can see a "master" branch on this repo, which was last updated approx 1 month ago, could you explain what you mean by there is "no master branch", given that there is one?

Also bower seems to work without problem for me lol.

Am I missing something here?

```
$ bower install prism
? May bower anonymously report usage statistics to improve the tool over time? No
bower prism#*               not-cached git://github.com/LeaVerou/prism.git#*
bower prism#*                  resolve git://github.com/LeaVerou/prism.git#*
bower prism#*                 checkout master
bower prism#*                 resolved git://github.com/LeaVerou/prism.git#6dbe885142
bower prism#*                  install prism#6dbe885142

prism#6dbe885142 bower_components/prism
 ls -lah bower_components/prism/
total 56K
drwxr-xr-x 1 vagrant vagrant  544 May  4 13:17 .
drwxr-xr-x 1 vagrant vagrant  136 May  4 13:17 ..
-rw-rw-r-- 1 vagrant vagrant  750 May  4 13:17 .bower.json
-rw-rw-r-- 1 vagrant vagrant  503 May  4 13:17 bower.json
drwxr-xr-x 1 vagrant vagrant 4.4K May  4 13:17 components
-rw-rw-r-- 1 vagrant vagrant 6.0K May  4 13:17 components.js
drwxr-xr-x 1 vagrant vagrant   68 May  4 13:17 examples
-rw-rw-r-- 1 vagrant vagrant 4.5K May  4 13:17 examples.js
-rw-rw-r-- 1 vagrant vagrant 1.4K May  4 13:17 gulpfile.js
-rw-rw-r-- 1 vagrant vagrant 1.1K May  4 13:17 LICENSE
-rw-rw-r-- 1 vagrant vagrant  635 May  4 13:17 package.json
drwxr-xr-x 1 vagrant vagrant  374 May  4 13:17 plugins
-rw-rw-r-- 1 vagrant vagrant  16K May  4 13:17 prism.js
-rw-rw-r-- 1 vagrant vagrant 2.3K May  4 13:17 README.md
drwxr-xr-x 1 vagrant vagrant  306 May  4 13:17 themes
drwxr-xr-x 1 vagrant vagrant  102 May  4 13:17 vendor
```

**Comment by LeaVerou** [comment]
There didn’t use to be a master branch in the past, to prevent the inevitable syncing issues between the two. I don’t quite remember when one was added, @Golmote do you?

**Comment by foxx** [comment]
Tbh merging changes to the master branch, and then only pushing to gh-pages
upon release is probably a better way of doing things anyway. You could use
a CI service such as Travis to only push to gh-pages if the tests are
successful, ensuring tested code only ever makes release. I'd be happy to
contribute some time to make that happen, it's a pipe work task I've done
for several other GitHub projects.

**Comment by Golmote** [comment]
Crap! I didn't realize there were a master branch! I have no idea who created it and when. I don't know how to get the info...

I might even have created it by mistake... I think my local branch is named "master"...

**Comment by callumacrae** [comment]
I'd guess it was created on March 21st by you, because that's the last commit!

If you delete the master branch now, you could break any site that's started using prism between March and now. Could I suggest that now would be a good time to start using the master branch?

[npm weekly](http://us9.campaign-archive1.com/?u=077dfd41302a71310cef619e5&id=7182533a81) had a couple links this week on how you can use npm scripts to speed this up.

**Comment by hastebrot** [comment]
> Tbh merging changes to the master branch, and then only pushing to
gh-pages
> upon release is probably a better way of doing things anyway. You could
use
> a CI service such as Travis to only push to gh-pages if the tests are
> successful, ensuring tested code only ever makes release.

That's a good idea. It prevents the GitHub page being broken and reduces
branch synchronisation to a no-op administratively.

**Comment by foxx** [comment]
@LeaVerou Majority of this I can do in a PR, but some will require you to setup up hooks and accounts, which I can talk you through on Skype with screenshare etc. Travis CI will also give us all those lovely integrations we see on other projects, such as a build status logo on the README and a test build hook on every commit/PR, and most importantly it will give this project CI, which should be an absolute minimum imho.

Also the general rule of the thumb is that no one should be committing to master directly, all changes should happen within a feature branch and all merges to master should be done via a PR. If you haven't already, I'd strongly recommend reading [Github Flow][1].

Anyway, my skype is cal.leeming. I'm free tonight after 8pm GMT, and 

[1]: https://guides.github.com/introduction/flow/

**Comment by Golmote** [comment]
A test build hook would be useful... if we actually had tests.

**Comment by foxx** [comment]
Heh, so TDD is out of the window.. At the absolute very least we can have a
"does it compile/parse" acceptance test. Either way, the original proposal
is still valid.

**Comment by Golmote** [comment]
Sure, and I agree that this needs to be sorted out. Eventually we'll need tests too.

**Comment by Golmote** [comment]
As we now have a master branch, that is updated on every new official release, I think this issue can be closed.
The current situation is probably not perfect yet, but it works for now.
