### ISSUE TITLE
JavaScript: remove `from` from keywords

### ISSUE THREAD

**Issue by rumkin** [PrismJS/prism#1806]
There is no `from` keyword in JS spec [Keyword section 11.6.2](https://www.ecma-international.org/ecma-262/6.0/#sec-reserved-words) ([Keywords](https://www.ecma-international.org/ecma-262/6.0/#sec-keywords), [Future Reserved Words](https://www.ecma-international.org/ecma-262/6.0/#sec-future-reserved-words)). But it's currently presented in [javascript syntax](https://github.com/PrismJS/prism/blob/master/components/prism-javascript.js#L14).

I think it should be removed.

**Comment by RunDevelopment** [comment]
[`from`](https://www.ecma-international.org/ecma-262/6.0/#sec-imports) is a keyword but can also be used as an identifier. That's why it's not in that list.
[More on imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import).
