### ISSUE TITLE
JavaScript: highlight keyword after dot

### ISSUE THREAD

**Issue by rumkin** [PrismJS/prism#1807]
Keyword after dot should not be highlighted as a keyword. This is already appeared in `.catch` issue #1526. Current found issue is in the next code:

```
Array.from()
Array.forEach()
```

Where `from` and `forEach` highlighted as `keyword` and `function` respectively.

**Comment by RunDevelopment** [comment]
I can see the problem with `from` and other keywords but what's wrong with `forEach`? It's not a keyword AFAIK.

**Comment by rumkin** [comment]
This is an example of different behavior. Highlighting should be the same in both cases.

**Comment by RunDevelopment** [comment]
Agreed.
