### ISSUE TITLE
prism should work with languages it doesn't know

### ISSUE THREAD

**Issue by butesa** [PrismJS/prism#181]
I just wanted to write some Windows-Batch-Code on a website, and I used class="language-batch". But prism doesn't do anything with that code. I think it should add line numbers and the grey background anyway (and all the other things it could do without having a language definition).
So I made this patch (it is for the development version with only clike enabled):

```diff
--- prism.js	2013-11-26 19:20:56.132296407 +0100
+++ prism-b.js	2013-11-26 19:20:48.568258882 +0100
@@ -111,6 +111,11 @@
 		}
 
 		if (!grammar) {
+			language = 'unknown';
+			grammar = _.languages[language];
+		}
+		
+		if (!grammar) {
 			return;
 		}
 		
@@ -377,3 +382,5 @@
 	'punctuation': /[{}[\];(),.:]/g
 };
 ;
+Prism.languages.unknown = {};
+;
```

**Comment by loganfranken** [comment]
We're pretty close this one; styling is done regardless if Prism recognizes the language:
https://jsfiddle.net/c6ao3tb9/1/

Line numbers, however, are a different story.

**Comment by Golmote** [comment]
The line numbers plugin runs during the `after-highlight` hook. Triggering the `after-highlight` hook if no highlighting has been done makes no sense to me.

I'm open to suggestions though.

**Comment by LeaVerou** [comment]
Perhaps we need a new hook? (or, if we have one, to change the hook line numbers uses)

**Comment by Golmote** [comment]
The highlighting function returns early when it can't find the grammar.

So I can think of two options:
* Add a `no-grammar` hook and plug the line numbers plugin on both hooks (`no-grammar` and `after-highlight`)
* or add a `complete` (or `done`?) hook that runs when the highlighting function returns, no matter if it highlighted something or not.

**Comment by Golmote** [comment]
I'm closing this issue now, since the styling is applied even if Prism can't find the grammar. Discussion regarding line-numbers plugins for unrecognized languages goes on in #645.
