### ISSUE TITLE
File highlight plugin: Support line ranges

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#1812]
**Description**
When writing tutorials, it's useful to only display parts of a file, so only line _x_ to line _y_. The [File highlight plugin](https://prismjs.com/plugins/file-highlight/) should support this functionality.

The idea is that you can add an additional `data-range` attribute to the `<pre>` and it will only display the lines in that range. E.g. `data-range="1,5"`.

This should be compatible with [Line numbers](https://prismjs.com/plugins/line-numbers/).

---

Continuation of #1810

**Comment by atomize** [comment]
Hooray! thanks for the infoz on how to build... I think this is good to go: #1813 - seems to be working on the page build and I over commented the additions in the source file  just in case. :nerd_face: 
Note that I changed the File-Highlight plugin index.html to demonstrate it working. You may or may not want to keep this/let me know how you would like it to be if you need me to do that as well.

**Comment by atomize** [comment]
hmm not sure why this time it seems to be failing checks. any insight? #1813

**Comment by jianghong3** [comment]
If the requirement is 1-4 lines are highlighted green and 5-8 lines are highlighted red, what should I do？

**Comment by RunDevelopment** [comment]
Closed by d38592c5bb1582a2fddefd81c9ad98e403b4ce9f,
