### ISSUE TITLE
prism won't work out at built app

### ISSUE THREAD

**Issue by LOGANLEEE** [PrismJS/prism#1821]
**Information:**
- Prism version: [e.g. 1.14, latest from the download page, etc.]"prismjs": "^1.15.0",
- Environment: [e.g. Browser, Node, Webpack] create-react-app( node)

Does the latest version of Prism from the [download page](https://prismjs.com/download.html) also have this issue? ya

If you're using Prism with Node or Webpack, please also see the [usage section](https://prismjs.com/index.html#basic-usage).
ya

**Description**
A clear and concise description of what the bug is and how to reproduce it.

**Example**
An example which reproduces the bug. This can be a link to a website, a [JSFiddle](https://jsfiddle.net/), an attached example project, etc.

i imported prism stuff at index.js(root file) and it works fine on local but
when i published it with gh-pages.

it doesn’t work on it :(  
(https://loganleee.github.io/graphql/tutorial-2)

can i have a help?
Thank for in advance!

**Comment by RunDevelopment** [comment]
@LOGANLEEE Thank you for reporting. Unfortunately, the link you provided doesn't work, so please provide a working example. You can also link to the repository with the source files.

**Comment by LOGANLEEE** [comment]
https://loganleee.github.io/react-git-page/ -> GraphQL ->  tutorial-2 

but i already replace it with highlight.js  :(
