### ISSUE TITLE
SSLSessionTickets is not highlighted in the apacheconf language.

### ISSUE THREAD

**Issue by raulfraile** [PrismJS/prism#1822]
**Information**
- Language: Apacheconf
- Plugins: [what plugin you are using]

Does the problem still occur in the latest version of Prism? Yes.

**Description**
`SSLSessionTickets` is not highlighted in the `apacheconf` language.

**Code snippet**

<details>

```
SSLSessionTickets off
```

</details>

**Comment by RunDevelopment** [comment]
Thanks for reporting!
