### ISSUE TITLE
gulp: Compress keyword lists?

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#1826]
## Motivation

Almost every language definition has some kind of keyword list. With _keyword list_ I mean a list of words (usually keywords) with are concatenated via alternations and surrounded by a word boundary. Example: [C keywords](https://github.com/PrismJS/prism/blob/master/components/prism-c.js#L6), [Python built-ins](https://github.com/PrismJS/prism/blob/master/components/prism-python.js#L55), [C-like class-name prefixes](https://github.com/PrismJS/prism/blob/master/components/prism-clike.js#L18).

Especially long keyword lists tend to contain a fair amount of redundancy. This can be used to compress the keyword list to decrease the overall files.

## Description

The idea is to use common prefixes and suffixes of the keywords to compress the regex. 
I.e. `return|returns` can be compressed to `returns?` and `get|let|set` can be compressed to `[gls]et`.

We could then use gulp to detect such keywords lists and automatically compress them to further decrease the size of minified files.

By leaving the compression to gulp we can enjoy readable keyword list regexes while also keeping the size of the minified files small.

## Current progress

I actually [already implemented](https://github.com/RunDevelopment/prism/tree/keyword-compression) most of the necessaries of this to work. The average compression rate is about 85-90%, so not very good but most keyword lists only contain ~100 keywords. The compression works best for really long list >500 words. With a lot of words, compression rates of up to 50-60% are possible.

I'm currently implementing more advanced compression strategies, so the compression rate will probably go down by 2-5%.

The only problem is that this is quite slow. It will probably add another 30s to the current build process.

---

So do we even want this?
It takes quite some time and the average compression rate isn't too good but language definitions which mostly consist of keyword lists profit immensely.

**Comment by Golmote** [comment]
Ouch 30s is _a lot_ though! You said this improved code size, but have you had the chance to check the performance? If we were to implement such a compression, we need to make sure it does not hurt the performance of the regexps.

**Comment by RunDevelopment** [comment]
I forgot to close this.

As suggested, I made a few performance tests and my results showed the compressed patterns are about 2x slower than uncompressed ones. At a compression of only ~85% it's not worth it.
