### ISSUE TITLE
Can't load language plugins via aliases even when they are officially provided

### ISSUE THREAD

**Issue by falsandtru** [PrismJS/prism#1827]
**Information:**
- Prism version: 1.15
- Environment: Browser

**Description**
Prism fails to load language plugins via aliases because of use of aliases for plugin path resolving.

**Example**
TypeScript language plugin has `ts` alias by default but isn't loadable.

https://falsandtru.github.io/securemark/#%60%60%60ts%0Aconst%20a%20%3D%200%3B%0A%60%60%60

```
cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/components/prism-ts.min.js:1 Failed to load resource: the server responded with a status of 404 ()
```

**Comment by RunDevelopment** [comment]
Just to be clear: You are using the [Autoloader plugin](https://prismjs.com/plugins/autoloader/) and it can't handle aliases (e.g. `ts`)?

**Comment by falsandtru** [comment]
Yes, I mean it.
