### ISSUE TITLE
/* breaks JSON tokenization

### ISSUE THREAD

**Issue by Nikaple** [PrismJS/prism#1852]
**Information**
- Language: [JSON]
- Plugins: [none]

Does the problem still occur in the latest version of Prism? Yes

**Description**
I'm logging server response as JSON. The HTTP header `Accept: */*` triggers this problem.

![broken_tokenization](https://user-images.githubusercontent.com/24775744/55315159-55a5b580-549e-11e9-9789-1c0e7ac3356f.png)

**Code snippet**

<details>
<summary>The code being highlighted incorrectly.</summary>

```
{
  "A": "/*",
  "B": "B",
  "C": "C"
}
```

</details>

**Comment by Nikaple** [comment]
Redefining `Prism.languages.json.comment` solves my problem, but I'm still posting the issue to see if this was intended or not.

**Comment by RunDevelopment** [comment]
This is definitely a bug which is probably caused by #1492.

> Redefining Prism.languages.json.comment solves my problem

What does 'redefining' mean? Do you change or delete `comment`?

**Comment by Nikaple** [comment]
> What does 'redefining' mean? Do you change or delete `comment`?

Yes, I changed `comment` as all of my code are standard `json` without comment.
