### ISSUE TITLE
markup removed from json value

### ISSUE THREAD

**Issue by adsim** [PrismJS/prism#1854]
I don't know if this is intended (and if I would want to know how to get around this ;)), but I have a JSON that includes HTML like this
`"description": "<section><p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. </p></section>",`
the HTML is removed.
I tried the KeepMarkup plugin, which prevents the HTML from being removed, but it's not visible. 
I want it to be visible as part of the string.

https://advanced-simple.de/test.html

**Comment by RunDevelopment** [comment]
You have to escape all `<` with `&lt;`.

Prism uses `textContent` to get the text of a `<code>` element meaning that all non-escaped HTML tags are lost.

**Comment by adsim** [comment]
Oh ... thanks. 
Seems I have failed to spot it when reading.
