### ISSUE TITLE
Prism.languages.markup.tag.addInlined is not a function

### ISSUE THREAD

**Issue by xiaomiwujiecao** [PrismJS/prism#1855]
**Information**
- Language:Javascript
- Plugins: javascript plugin

Does the problem still occur in the latest version of Prism? 

YES

**Description**
when i load  javascript plugin ,
 one error printed  on console when i use javascript plugin in  docsify,
**Code snippet**

<details>
<summary>Uncaught TypeError: Prism.languages.markup.tag.addInlined is not a function
    at prism-javascript.js:83</summary>

```
<script src="//unpkg.com/prismjs/components/prism-javascript.js"></script>

```

</details>

**Comment by RunDevelopment** [comment]
Docsify hasn't updated to Prism 1.16.0 yet, so it's still using Prism 1.15.0 including the 1.15.0 version of Markup.
Your UNPKG link will resolve to the Prism 1.16.0 version of Javascript which also requires the 1.16.0 version of Markup which defines the `addInlined` function.

Use the 1.15.0 version of Javascript (and any other language for that matter) and everything should work. `https://unpkg.com/prismjs@1.15.0/components/prism-javascript.js`

**Comment by xiaomiwujiecao** [comment]
ok thank you
