### ISSUE TITLE
fix regular expressions in components

### ISSUE THREAD

**Issue by arnehormann** [PrismJS/prism#186]
a lot of the regular expressions in components seem to be wrong.
Partially due to misunderstanding of regexps, partially concerning their content.

Examples:
* `[+-]{1,2}` in operators, which should be `++?|--?` so it does not match `+-` or `-+`, too.
* `&lt;{1,2}` should be `(&lt;){1,2}` so the repetition does not apply to the semicolon only
* nearly everything should be surrounded by word boundaries (`\b`)
* some usages of identifiers only match lower case, the include section also capital case

I started rewriting them, but I gave up when I reached coffeescript because I don't know the language and can't make anything of most of the regexps - what is the intended match of `[_?a-z-|A-Z-]+`?
I'll probably still submit a PR later, but it will only be a partial fix.

**Comment by Golmote** [comment]
Now we have tests, most of the regexps have been rewritten (or at least checked). I can't assure you there are no more issues in them but if there are, they'll have to be fixed on a case-by-case basis.
