### ISSUE TITLE
Saving to MYSQL

### ISSUE THREAD

**Issue by paulmaloney** [PrismJS/prism#1863]
I'm trying to save the content from a user input into a MYSQL database. Given Prism changes the textarea to a pre  and the name attribute doesn't seem to work within a pre, how would I go about saving out to a database?

**Comment by RunDevelopment** [comment]
@paulmaloney Could you please explain your issue in more detail? (Some actual code of your setup or a before-and-after also helps.)

If I understood you correctly, you have a `<textarea>` from which you want to extract the text (supposedly code) the user entered. You use Prism to highlight `<textarea>` but after highlighting, the `<textarea>` was removed and replaced with a `<pre>`, correct?

**Comment by paulmaloney** [comment]
Hey! OK for example my textarea:
<textarea id="html" name="html" class="language-html"></textarea>

But when you open in inspector you see: 
<pre id="html" name="html" class=" language-html" contenteditable="true"></pre>

The name attribute I'm trying to post to MYSQL but it's not grabbing the text in the textarea, it's just posting nothing to the database

**Comment by RunDevelopment** [comment]
Are you using Prism through some other library? Because Prism by itself **does not** replace `textarea`s with `pre`s.
Also, how are you calling `Prism.highlightElement`?

**Comment by paulmaloney** [comment]
I'm using prism-highlight.js

editorHTML = bililiteRange.fancyText(editorHTML, Prism.highlightElement);
editorCSS = bililiteRange.fancyText(editorCSS, Prism.highlightElement);
editorJS = bililiteRange.fancyText(editorJS, Prism.highlightElement);

**Comment by RunDevelopment** [comment]
As the doc of [`bililiteRange.fancyText`](http://bililite.com/blog/2013/12/16/simple-syntax-highlighting-editor-with-prism/) states:

> Replaces `textarea` with a `<pre>`, calls Prism.editor on that, and returns it. The original `textarea` is deleted.

So your issue is not a problem of Prism but intended behavior of the [library](https://github.com/dwachss/bililiteRange) you are using.

A simple solution would probably be to use `<pre>`s instead of `textarea`s but I can't really help you with a library I don't know about.
