### ISSUE TITLE
Stop giving new line numbers in one line after line break

### ISSUE THREAD

**Issue by michalmicpaw** [PrismJS/prism#1880]
**Motivation**
Hi. PrimeJS gives new line number to line, which is broken in case of being too long. (**Normalize Whitespace** + Line **Numbers plugins**)

**Description**
When I put a line of code to highlight, which is a little long, and I use **Normalize Whitespace** plugin to break lines, when they are too long, the **Line Numbers** plugin gives numbers to every lines, even those broken. 

**Alternatives**
I would line to get exactly as many line numbers counted as it is in source code. If line has to be broken, the broken part shouldnt get new number (no line number)

**Comment by RunDevelopment** [comment]
The line numbers plugin has a [soft-wrap feature](https://prismjs.com/plugins/line-numbers/#examples) which does exactly what you want. (It's documented in the last example)

**Comment by michalmicpaw** [comment]
Thank you for response.

Actually, I do it, but it doesn't work. Maybe it doesn't because of other plugins?

I do this:
```
<script src="prism.js"></script>
		<script>
		Prism.plugins.NormalizeWhitespace.setDefaults({
		'remove-trailing': true,
		'remove-indent': true,
		'left-trim': true,
		'right-trim': true,
		'break-lines': 40/*,
		'indent': 2,
		'remove-initial-line-feed': false,
		'tabs-to-spaces': 4,
		'spaces-to-tabs': 4*/
		});
		</script>
		<div style="width:500px;">
		<pre class="line-numbers" style="white-space:pre-wrap;"><code class="language-cpp">cout << "Hello honey" << abc<< " " << sqrt(75.5) << endl;
int babe = 123;
return babe / 2 + 1;</code></pre></div>
```

It breakes first line into two lines, but new line gets new number. How can I fix it?

**Comment by RunDevelopment** [comment]
> Actually, I do it, but it doesn't work.

That's because you still have Normalize Whitespace break your lines. Comment out `'break-lines': 40` as well and your example will work.

Note: Your example will no longer break at 40c but at the width of the `<pre>` instead.

**Comment by michalmicpaw** [comment]
Thank you, it works :)
