### ISSUE TITLE
JavaScript numeric separators

### ISSUE THREAD

**Issue by mathiasbynens** [PrismJS/prism#1893]
**Information**
- Language: JavaScript
- Plugins: none

Does the problem still occur in the latest version of Prism? You can check using the [test page](https://prismjs.com/test.html) or get the latest version at the [download page](https://prismjs.com/download.html).

Yes

**Description**
A clear and concise description of what is being highlighted incorrectly and how it should be highlighted instead. Add screenshots to illustrate the problem.

The use of [numeric separators](https://github.com/tc39/proposal-numeric-separator) causes numeric literals to be highlighted incorrectly.

<details>
<summary>The code being highlighted incorrectly.</summary>

```
1_000_000_000_000
    1_019_436_871.42
```

</details>

Screenshot from <https://v8.dev/blog/v8-release-75#numeric-separators>:

![](https://user-images.githubusercontent.com/81942/57871547-eed72400-77df-11e9-9ccd-cde8ce4b32f8.png)

**Comment by RunDevelopment** [comment]
Thank you for reporting this issue!
