### ISSUE TITLE
The $# variable is highlighted as a comment in bash

### ISSUE THREAD

**Issue by DaveJarvis** [PrismJS/prism#1901]
**Information**
- Language: bash
- Plugins: none

**Description**
The `$#` variable has a `#` symbol that is treated as a comment:

![bash](https://user-images.githubusercontent.com/2131950/58132692-d64b7d00-7bd6-11e9-8b07-dfc571b34730.png)

This styles the remainder of the line as a comment, which is unexpected.

**Code snippet**
The GitHub markdown, on the other hand, appears to highlight the variable as expected:

``` bash
parse_commandline() {
  POSITIONAL=()
  while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
      -d|--debug)
      ARG_DEBUG="true"
      shift
      ;;
      -h|-\?|--help)
      ARG_HELP="true"
      shift
      ;;
      *)
      # Skip argument
      shift
      ;;
    esac
  done
  set -- "${POSITIONAL[@]}"
}
```

**Work Around**
Introduce double quotes:

``` bash
  while [[ "$#" -gt "0" ]]; do
```

**Comment by RunDevelopment** [comment]
This will also be resolved by #1443.
