### ISSUE TITLE
The esac keyword is not highlighted in bash

### ISSUE THREAD

**Issue by DaveJarvis** [PrismJS/prism#1902]
**Information**
- Language: bash
- Plugins: none

**Description**
 The `esac` keyword does not appear to be highlighted:

![bash](https://user-images.githubusercontent.com/2131950/58135188-5e815080-7bde-11e9-81a6-bf84c20b0a0e.png)

**Code snippet**
 The GitHub markdown appears to highlight the keyword as expected:

``` bash
parse_commandline() {
  while (( "$#" )); do
    local key="$1"
    local consume=1

    case $key in
      -d|--debug)
      ARG_DEBUG="true"
      ;;
      -h|-\?|--help)
      ARG_HELP="true"
      ;;
      *)
      # Skip argument
      ;;
    esac

    shift $consume
  done
}
```

**Comment by RunDevelopment** [comment]
This will be solved by #1443.
