### ISSUE TITLE
The local keyword is not highlighted in bash

### ISSUE THREAD

**Issue by DaveJarvis** [PrismJS/prism#1903]
**Information**
- Language: bash
- Plugins: none

**Description**
The `local` keyword does not appear to be highlighted:

![bash](https://user-images.githubusercontent.com/2131950/58137214-48778e00-7be6-11e9-9c1d-74e718ddfcce.png)

**Code snippet**
GitHub markdown appears to highlight the keyword as expected:

``` bash
parse_commandline() {
  while [[ "$#" -gt "0" ]]; do
    local key="$1"
    local consume=1

    case $key in
      -d|--debug)
      ARG_DEBUG="true"
      ;;
      -h|-\?|--help)
      ARG_HELP="true"
      ;;
      *)
      # Skip argument
      ;;
    esac

    shift $consume
  done
}
```

**Comment by RunDevelopment** [comment]
This will be solved by #1443.
