### ISSUE TITLE
COBOL

### ISSUE THREAD

**Issue by bushidocodes** [PrismJS/prism#1906]
**Language**
A short description of the language.

COBOL is the original high-level language, invented by Grace Hopper in the 1950s. General info at https://www.bushido.codes/cobol-lang. This blog is powered by Gatsby and uses a PrimsJS via a plugin. I noticed the language was missing

**Additional resources**

COBOL is an ISO standard. The latest version was released in 2014.
https://www.iso.org/obp/ui/#iso:std:iso-iec:1989:ed-2:v1:en

GitHub does successfully perform COBOL syntax highlighting.

They seem to use this Sublime Text plugin.
https://bitbucket.org/bitlang/sublime_cobol/src/master/

This VSCode plugin has several COBOL syntaxes expressed as regexes in JSON:
https://github.com/spgennard/vscode_cobol

**Comment by gusfaria** [comment]
Is this being considered?

**Comment by RunDevelopment** [comment]
All language requests are being considered. However, implementing (and testing) new languages isn't trivial. Especially for unfamiliar languages, the research for language features alone can take the better part of a day (or longer depending on the language and the quality of its documentation).

It's not that we don't consider or don't want a language, quite the opposite. This is purely a question of manpower. So pull requests are always appreciated.
