### ISSUE TITLE
TeX, ConTeXt, and LaTeX

### ISSUE THREAD

**Issue by DaveJarvis** [PrismJS/prism#1913]
**Motivation**
While writing a document on [ConTeXt](https://www.contextgarden.net/Main_Page), a monolithic TeX-based typesetting engine, I'd like to apply syntax highlighting. The syntax for ConTeXt, being built on TeX, is very similar to LaTeX.

**Description**
Currently, the language indicator must be `language-latex`.

**Alternatives**
The simplest solution to support plain TeX and ConTeXt languages would be to add a synonym for both that refer to LaTeX. That way we can use `language-tex`, `language-latex`, and `language-context`.

Since LaTeX and ConTeXt are both TeX engines, it might make more sense to create a base "TeX" language with LaTeX and ConTeXt having their own synonyms, based off of TeX.

**Additional Details**
ConTeXt source code can be intermingled with [MetaPost](https://www.tug.org/docs/metapost/mpman.pdf) and Lua code; however, starting with a TeX base would cover a number of use cases.

@adityam may have more to add on this topic.

---
For example:

![context-syntax](https://user-images.githubusercontent.com/2131950/58448015-51230500-80bb-11e9-8047-9c7a4a78aa9c.png)

**Comment by RunDevelopment** [comment]
For now, I added the requested aliases. We can add distinct language definitions for TeX and ConTeXt later on.
