### ISSUE TITLE
Rename the prism.js file to avoid being blocked by AdBlockers

### ISSUE THREAD

**Issue by ekaitz-zarraga** [PrismJS/prism#1929]
**Motivation**
I recently saw that my adblocker is blocking `prism.js` files from any website because it considers them trackers. Changing the default filename would make it not be consider a tracker (it's not!) and avoid this issue.
This is the commit that marks `prism.js` as a tracker. It's not our prism, but it's affecting this project collaterally. This tracker list is imported in many adblockers including uBlock Origin and ABP.
https://github.com/easylist/easylist/commit/e7f657a9b55adabaf44404b549c4edd92f4276a4

**Description**
The default filename can be changed to something different like `prism-hl.js` and it will make everything work like intended.

**Comment by RunDevelopment** [comment]
Thank you for notifying us about this issue!

Renaming `prism.js` is not an option right now. It's a breaking change and all websites which don't immediately update are still left without syntax highlighting.

Instead, we should resolve the [issue](https://github.com/easylist/easylist/issues/3567) at the easylist repo.
