### ISSUE TITLE
scss specific text lasts forever to highlight

### ISSUE THREAD

**Issue by mhosna** [PrismJS/prism#1937]
Example:
/* 16:44:48: -------------------------------------------------- */

in definition you only need to change url regex
FROM: 'url': /(?:[-a-z]+-)*url(?=\()/i
TO: 'url': /(?:[-a-z]+-)?url(?=\()/i,

It should have the same result, just it is much faster in processing dashes.

Thanks

**Comment by RunDevelopment** [comment]
Thanks for reporting! Will fix.

**Comment by mhosna** [comment]
Thank you!
