### ISSUE TITLE
language-px or language-pcaxis

### ISSUE THREAD

**Issue by CSOIreland** [PrismJS/prism#1939]
**Language**
Several statistical organisations around the World are using a data format called "px".
The formatting of this data format works fine by using the "language-clike".
Is it possible to add the alias `language-px` or `language-pcaxis` for `language-clike` so that others can find it?

**Additional resources**
The PX format is maintained by the PcAxis community, led by the Nordic countries.
You can find the PX format documentation in the official website of Statistics Sweden: https://www.scb.se/en/services/statistical-programs-for-px-files/px-file-format/

Thank you!

**Comment by CSOIreland** [comment]
P.S.
Please find attached a sample file. 
I just had to change the extension from `.px` to `.txt` in order to upload it here.
Cheers

[px-sample.txt](https://github.com/PrismJS/prism/files/3275737/px-sample.txt)

**Comment by RunDevelopment** [comment]
@CSOIreland 
Do I see this correctly that your example isn't valid PX because `DATA` doesn't end with a semicolon?

**Comment by CSOIreland** [comment]
That's great, thank you very much!
Sorry to ask, but how can I start using it? I cannot see it in the download page: https://prismjs.com/download.html

Thanks again

**Comment by RunDevelopment** [comment]
You can download a Prism version with PX support as soon as #1940 is merged. 
But it might take up to 2 weeks (at most) until we do so because it needs to be reviewed.

If you need it right now, you can download [my branch](https://github.com/RunDevelopment/prism/tree/px), start a local server, and use the local download page.
