### ISSUE TITLE
Adjoining classes cause css collisions

### ISSUE THREAD

**Issue by MayorUshanka** [PrismJS/prism#1958]
I am running a small custom CMS I built myself to host some articles. The issue is that I have mutliple classes in my own css: .tag, .comment, which have a collision with the way that prism.css renders its tokens: .token.tag, .token.comment.

Some syntax in pre blocks thus get rendered like my comments or tags. I am not willing to change my semantic css. I'm guessing I can't solve it by a simple find-and-replace ".token.tag" -> ".prism-tag"

**Comment by RunDevelopment** [comment]
The [Custom Class](https://prismjs.com/plugins/custom-class/) plugin should solve your issue.
It will prefix everything, so `.token.tag` -> `.prism-token.prism-tag`.
