### ISSUE TITLE
PeopleCode

### ISSUE THREAD

**Issue by neelambar** [PrismJS/prism#1982]
**Language**
PeopleCode is proprietary scripting language for PeopleSoft ERP.

**Additional resources**
PeopleCode Syntax Highlighting for Notepad++
https://github.com/cache117/peoplecode-npp/blob/master/PeopleCodeUDL.xml

**Comment by RunDevelopment** [comment]
To the one implementing this: Here's [a little guide](https://docs.oracle.com/cd/E99483_01/pt857pbr1/eng/pt/tpcd/concept_PeopleCodeLanguageStructure-074b54.html?pli=ul_d61e34_tpcd) to PeopleCode.
