### ISSUE TITLE
New Release anytime soon?

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#1988]
It has been 4 months and ~60 commits since the last release.
(I screwed up and used _Merge commit_ instead of _Squash and merge_, so I don't know the exact number.)

With #1835, the changelog can be mostly generated, so I'll make a new branch with the updated changelog in the next few days.

Regarding the open PR. I made a new milestone and add all of the PR I think should definitely be in the new release.

Is there anything else which needs to be prepared?
@mAAdhaTTah @Golmote

**Comment by mAAdhaTTah** [comment]
Appreciate the housekeeping. I'll take a pass through the labeled PRs with an eye towards cutting a release this weekend.

**Comment by mAAdhaTTah** [comment]
Oh, we will need a CHANGELOG prepared, if you wanna start getting that together.

**Comment by RunDevelopment** [comment]
This weekend sounds good.

> Oh, we will need a CHANGELOG prepared

I'll do that tomorrow.

**Comment by mAAdhaTTah** [comment]
I'll take a pass through the new languages as well, but I'll caveat that an approval from me mostly means things seem ok (e.g. has tests, components.json, code is well-formatted, etc.) but none of the regexes will be reviewed cuz I don't have a lot to offer there. After I approve, def take another pass through them before you merge them (which I think you do anyway).

**Comment by RunDevelopment** [comment]
> def take another pass through them

Will do.

**Comment by RunDevelopment** [comment]
@mAAdhaTTah Do you have administrator rights for this repo?

GitHub keeps forgetting that the last merge method I used was _Squash_ after a few merges and reverts to the default method of _merge commits_. It's really annoying because I forget to check and unwillingly use the wrong merge method.

Could you please disable all other merge buttons in the settings of this repo? It's the only method we use AFAIK and it would help me more I'd like to admit.

**Comment by mAAdhaTTah** [comment]
@RunDevelopment I do not. @LeaVerou Is this something you could change?

**Comment by mAAdhaTTah** [comment]
Publish 1.17.0 then immediately published 1.17.1 to keep my `.DS_Store` files from being published https://github.com/PrismJS/prism/commit/c2229ec2d2a719d059c547343c5daa90f680200d
