### ISSUE TITLE
Add support to Sass too, not just SCSS.

### ISSUE THREAD

**Issue by oscarmarcelo** [PrismJS/prism#199]
You added support to SCSS and that is awesome, but some of us still prefer to use the original Sass syntax (without brackets and semi-colons and those many @ aliases).

Is there any plan to add support to it?

I would do a pull request if I could, but I'm not that familiar with Regular Expressions...

**Comment by labo-css** [comment]
I hate to necropost but. Is this issue somewhat resolved? I have a hard time to found any syntax highlighter that support the sass syntax. Only pygments is doing it but... python.

**Comment by Golmote** [comment]
Here you go.

![prism-sass](https://cloud.githubusercontent.com/assets/565460/8143763/b30494ae-11bc-11e5-87af-f32fe331fe75.png)

**Comment by labo-css** [comment]
Thanx but where is the online version of this screenshot?

**Comment by Golmote** [comment]
This is a screenshot of the [Examples page](http://prismjs.com/examples.html) of the website.

**Comment by labo-css** [comment]
Thanx!
