### ISSUE TITLE
Standardize templating logic

### ISSUE THREAD

**Issue by mAAdhaTTah** [PrismJS/prism#1991]
**Motivation**
See #1931 – we have a couple of ways that we handle highlighting languages inside of other languages. It would be awesome if there was a single, unified way to do this.

**Description**
Simplify the code of the current implementations and make adding future embedding languages easier. Code weight reduction is a hard requirement, imo, otherwise, the individual implementations can stay the way they are.

**Alternatives**
Leave the code alone. If it ain't broke, don't fix it.

**Comment by RunDevelopment** [comment]
Implemented in v2.
