### ISSUE TITLE
Standardize dependency logic

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#1992]
**Motivation**
We have how many different implementations for loading and handling dependencies? 
The following components all have their own distict logic:

- Download page
- Examples & test page (#1936)
- Autoloader
- Testing suite
- [loadLanguages](https://github.com/PrismJS/prism/blob/master/components/index.js)
- [babel-plugin-prismjs](https://github.com/mAAdhaTTah/babel-plugin-prismjs) (external)

**Description**
Standardize the dependency logic. 

It should be able to handle both languages and plugins so that we can use it at the download page. This also includes reloading and support for required CSS files.

It would also be nice if it could deal with aliases, but that's optional.

**Info**
I already implemented something similar [here](https://github.com/RunDevelopment/prism/blob/deps/component-manager.js) so that should be a good starting point.

**Comment by mAAdhaTTah** [comment]
Yeaaaaah, I had to write an implementation for the [babel plugin](https://github.com/mAAdhaTTah/babel-plugin-prismjs/blob/master/src/getComponents.js) too.
