### ISSUE TITLE
GDScript highlighting

### ISSUE THREAD

**Issue by woubuc** [PrismJS/prism#2001]
**Language**
GDScript is the scripting language used in the Godot game engine. It would be very useful for things like tutorials and gamedev blogs to have support for this language.

**Additional resources**
Godot website: https://godotengine.org

**Comment by RunDevelopment** [comment]
[Here](https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_basics.html#language) is a language introduction:
