### ISSUE TITLE
Support for Monaco editor syntax highlighting

### ISSUE THREAD

**Issue by fabiospampinato** [PrismJS/prism#2003]
I think the best way to explain this would be to illustrate my use case:

I have an app called [Notable](https://github.com/notable/notable) which is basically a Markdown editor. It uses [Monaco editor](https://github.com/microsoft/monaco-editor) as its editor of choice, which is the cool one these days as it's the one used by VSCode.

I want code blocks to be syntax highlighted consistently both inside the editor and when rendering the Markdown, so I need to use one syntax highlighter (just Monaco) rather than two (Monaco + Prism).

The problem is that the languages Monaco provides syntax-highlighting for are quite limited in comparison to the ones supported by Prism.

So do you think it would be possible to automatically convert Prism's syntax highlighting definitions to Monaco-compatible definitions? Monaco uses the [Monarch](https://microsoft.github.io/monaco-editor/monarch.html) syntax highlighter under the hood.

**Comment by fabiospampinato** [comment]
Converting Prism's syntax definitions to TextMate might be a more portable option which should also probably solve my use case 🤔

**Comment by mAAdhaTTah** [comment]
I think your best bet would be to submit a theme to [prism-themes](https://github.com/PrismJS/prism-themes/) and use that. I doubt Monaco-compatible syntax definitions is feasible from both a technical as well as effort perspective.

**Comment by fabiospampinato** [comment]
I don't think a custom theme would solve my issue as the underlying tokenizers will be different so there will always be some, perhaps subtle, differences.

I'm closing this as after some more investigation this seems indeed infeasible.
