### ISSUE TITLE
CSS extras combined with markup templating retains placeholders

### ISSUE THREAD

**Issue by wooorm** [PrismJS/prism#2008]
**Information:**
- Prism version: 1.17.1 (probably since markup templating was introduced a year ago)
- Environment: Browser, Node

**Does the latest version of Prism from the [download page](https://prismjs.com/download.html) also have this issue?**

Yes

**Description**

Markup templating injects placeholders: stuff like `___PHP0___`.
If this is injected inside CSS, CSS Extras picks up on the number and creates a number token for it.
Because the placeholder is no longer a single text token, the placeholder can no longer be tokenised and remains in the resulting text instead of being replaced.

**Example**

Say we want to highlight this code as php:

```php
<img style="width:<?php echo (80 / count($images)) ?>%"/>
```

Wrapped in HTML like so:

```html
<!DOCTYPE html>
<html>
  <head>
    <link href="./prism.css" rel="stylesheet" />
  </head>
  <body>
    <pre><code class="language-php">&lt;img style="width:&lt;?php echo (80 / count($images)) ?>%"/></code></pre>
    <script src="./prism.js"></script>
  </body>
</html>
```

...where `prism.css` refers to any theme, and `prism.js` refers to a Prism build including php, markup-templating, and css-extras.

Yields:

![result](https://user-images.githubusercontent.com/944406/62303640-cd9be080-b47c-11e9-93e4-8450d7cb123c.png)

**More info**

The problematic line is here:

https://github.com/PrismJS/prism/blob/3af5d744fd7359086c4a1fc5ac4b66fe4001c935/components/prism-css-extras.js#L75

It was changed in https://github.com/PrismJS/prism/pull/1450 8 months ago. But it may have been around for at least 6 years (checking blames up to get to the initial commit). It’s more likely that this was introduced through markup templating in https://github.com/PrismJS/prism/pull/1367

**Comment by RunDevelopment** [comment]
Thank you for reporting!

**Comment by wooorm** [comment]
Thanks @RunDevelopment for solving this!
