### ISSUE TITLE
Python string with 3 quotes not working

### ISSUE THREAD

**Issue by QuentiumYT** [PrismJS/prism#2024]
**Information:**
- Language: Python
- Prism version: Latest
- Environment: Browser (webpage bug)

Does the latest version of Prism from the [download page](https://prismjs.com/download.html) also have this issue? Yes

**Description**
Small bug with string interpretation with 3 quotes string. This results in the rest of the page in the same color as usual strings.

**Preview**
![Capture](https://user-images.githubusercontent.com/35229942/63588777-9914d380-c5a7-11e9-8614-2161623fee01.PNG)

**Comment by RunDevelopment** [comment]
If I were to guess, this is probably caused by #1492. Could you please provide the full code (or a link to it) for more context?

**Comment by QuentiumYT** [comment]
Yeah you're right, every language with this kind of quotes seems to be affected (I just searched Python for issues so I haven't found this page).
If you want my code, here it is https://quentium.fr/discord/sourcecode/ , just search line 434 and it's starting there.

**Comment by RunDevelopment** [comment]
@QuentiumYT I think there's a problem with your code on line 292, which causes the whole problem.

Interestingly, it's valid Python.
TIL that Python interprets `"some content"""` as `"some content"` and `"a""b""c"""` as `"abc"`.

**Comment by QuentiumYT** [comment]
Oh thank you! I didn't notice this mistake, I fixed it and it seems to work perfectly again! I wonder how you found that and I feel sorry to post a Github issue for my bad... Anyway, thank you for your time and help. Keep this library up because it's a very nice one!

**Comment by RunDevelopment** [comment]
> I feel sorry to post a Github issue

You don't have to. Your valid python code was highlighted incorrectly, so it's a good that you filed a report.

That being said, let's keep this closed because there are already a few issues being kept open because of #1492.
