### ISSUE TITLE
Incorrect string highlighting for D

### ISSUE THREAD

**Issue by bkhl** [PrismJS/prism#2027]
**Information:**
- Prism version: Current at https://prismjs.com/test.html
- Environment: Test drive at https://prismjs.com/test.html

_Does the latest version of Prism from the [download page](https://prismjs.com/download.html) also have this issue?_

Don't know, discovered it using https://exercism.io (https://github.com/exercism/bugs/issues/22)

**Description**

For the D language, using single quotes in a double quoted string leads to this undesired behaviour:

![image](https://user-images.githubusercontent.com/34634/63638148-b54f6800-c6ae-11e9-9ce8-320ebc623e15.png)

In D, strings in backticks are WYSIWYG-strings, equivalent to strings enclosed in `r""` (https://dlang.org/spec/lex.html#wysiwyg)

**Example**

Go to https://prismjs.com/test.html#language=d and paste in:

```d
string foo = "It's";
foo = "It's";
foo = "It's";

string bar = `It's`;
bar = `It's`;
bar = `It's`;
bar = `It's`;
```

**Comment by RunDevelopment** [comment]
Thank you @bkhl for reporting!
