### ISSUE TITLE
Bug in COY theme

### ISSUE THREAD

**Issue by mahnunchik** [PrismJS/prism#203]
![2014-01-28 14 18 46](https://f.cloud.github.com/assets/780935/2016986/3530e5d2-87ed-11e3-9621-15c43f96314a.png)
```
Google Chrome	32.0.1700.77 (Официальная сборка 244503) 
ОС	Linux 
Blink	537.36 (@164518)
JavaScript	V8 3.22.24.10
```
![2014-01-28 14 26 34](https://f.cloud.github.com/assets/780935/2016989/715f7b36-87ed-11e3-8ff4-9278524cfc53.png)
Firefox 26

**Comment by loganfranken** [comment]
I might be missing something, but I don't think I see the bug in the actual theme above?

**Comment by mahnunchik** [comment]
Bug was unnecessary scrollbars.

**Comment by loganfranken** [comment]
Ahh, thanks @mahnunchik!

Looks fixed on the Examples page now:
http://prismjs.com/index.html#examples

Does it seem fixed to you too, @mahnunchik?

**Comment by mahnunchik** [comment]
@loganfranken yep :+1:

**Comment by loganfranken** [comment]
Awesome, @mahnunchik!

I think we can close this one!
