### ISSUE TITLE
Smalltalk: single-quote-character is not a string

### ISSUE THREAD

**Issue by bencoman** [PrismJS/prism#2039]
**Information**
- Language: Smalltalk
- Plugins: none

**Description**
The current prism test site is operating correctly but I noticed a missing test.
The single-quote character used to define literal-strings...  e.g. 'foobar' 
can also be defined as a literal-character... e.g.  $'
This causes a problem on the Exercism site https://github.com/exercism/exercism/issues/5011
I presume this was incidentally fixed by changes since the version they are using.
It would still be good to explicitly capture this as a test case.

**Code snippet**

Running...
 **npm run test:languages -- --language=smalltalk --pretty**

<details>
<summary> The following passes... </summary> 

string_character_feature.test
```
$a
'foobar'                                                                                                                
----------------------------------------------------
[
        ["character", "$a"],
        ["string", "'foobar'"],
]
----------------------------------------------------
Checks string parsing not confused after string-character-literal. 
```
</details>
<details>
<summary>The following doesn't... </summary>

string_character_feature.test
```
$'
'foobar'                                                                                                                
----------------------------------------------------
[
        ["character", "$'"],
        ["string", "'foobar'"],
]
----------------------------------------------------
Checks string parsing not confused after string-character-literal.  
```

</details>

**Comment by bencoman** [comment]
What is the semantic of "alias" with the definition of Character here?... https://github.com/PrismJS/prism/blob/master/components/prism-smalltalk.js#L23

In Smalltalk, Characters and Strings are distinct. 
` 'a' className ` ==> ByteString - a subclass of String
` $a className ` ==> Character
Snapshot using https://pharo.org
![image](https://user-images.githubusercontent.com/1713447/64225440-01e83e00-cf0e-11e9-8415-c31367d8924b.png)

**Comment by bencoman** [comment]
This was the error...
![image](https://user-images.githubusercontent.com/1713447/64226005-48d73300-cf10-11e9-9e04-e76c0e3b5193.png)

I got my test case to work by raising the priority of Character above String.  PR incoming.

**Comment by RunDevelopment** [comment]
> What is the semantic of "alias" with the definition of Character here?... 

Aliases are used for styling. Prism will give the output token a few CSS classes `.token`, then the name of the token (in your case `.character`), and all aliases (there might be more than one but in this case just `.string`). In your case, the token will get the class `.token.character.string`.
Aliases are a trick to give tokens a more specific name without needing to modify any themes to support the name.

> In Smalltalk, Characters and Strings are distinct.

Prism usually highlights characters and strings in the same color but you can modify Prism's themes on your website to change that. Add a `.token.character` rule and give it a different color.
