### ISSUE TITLE
Ignore npm-debug.log

### ISSUE THREAD

**Issue by bencoman** [PrismJS/prism#2042]
**Information:**
- Prism version: cloned latest HEAD
- Environment: bash

Not being a Javascript programmer, I almost gave up on trying solving myself issue https://github.com/PrismJS/prism/issues/2039 which I logged, because `npm run test:languages -- --language=smalltalk --pretty`
was giving an error I couldn't understand.

Turns out my changes were correct but I didn't notice a previous error had created file **npm-debug.log** in my working directory and that was trying to be parsed as input.  Urgh!  Only lucky it worked out.   To avoid others' frustration it would be good to exclude file that from input.

**Comment by RunDevelopment** [comment]
I'm pretty sure that this is because of #2040, so I'll close this for now. If the problem still persists, feel free to reopen this.
