### ISSUE TITLE
Request: Freemarker language syntax highlighting

### ISSUE THREAD

**Issue by pitxels** [PrismJS/prism#2051]
Really need to have the FTL (Freemarker language) be supported in Prism.

I tried myself but this is too complex for me. Any help is appreciated.

**Comment by RunDevelopment** [comment]
Some additional resources: [Manual](https://freemarker.apache.org/docs/dgui_quickstart.html).

Just so you know. When implementing this, I wouldn't handle [deprecated syntax](https://freemarker.apache.org/docs/ref_depr_oldsyntax.html).
