### ISSUE TITLE
Using "Prism.highlight()" with plugins

### ISSUE THREAD

**Issue by Opsse** [PrismJS/prism#2057]
**Motivation**
For dynamic code change with Vuejs I need to generate the highlighted code with low-level function. This way :

```js
this.formattedCode = Prism.highlight(this.code, Prism.languages['custom'], 'custom')
```

**Description**
The code highlight works as expected but the plugin `line-numbers` doesn't enable.

I expect this : 
![image](https://user-images.githubusercontent.com/3708059/65053911-0597ae00-d96d-11e9-9d95-63a920c5a6b5.png)

But I got this : 

![image](https://user-images.githubusercontent.com/3708059/65053976-1d6f3200-d96d-11e9-9aee-94e4a31aa070.png)

I assume that it because the `line-numbers` code is missing.  
I'm looking for a way to generate the highlighted with some plugins. For example : `Prism.highlight(text, grammar, language, plugins)`

**Alternatives**
Any workaround is welcome but I didn't find one so far.

**Comment by RunDevelopment** [comment]
[Line numbers](https://prismjs.com/plugins/line-numbers/) (like most plugins) requires the hooks from the `Prism.highlightElement` function.

As a rule of thumb: Everything that interacts with the DOM needs `Prism.highlightElement`. This includes adding new DOM nodes but also reading the classes of elements (`line-numbers`).
