### ISSUE TITLE
Perf issue in newer chrome versions

### ISSUE THREAD

**Issue by jiantosca** [PrismJS/prism#2062]
**Information:**
- Prism version: I first noticed the issue in 1.16, I upgraded to 1.17.1 and still see the issue. 
- Environment: Browser (chrome extension)

**Does the latest version of Prism from the [download page](https://prismjs.com/download.html) also have this issue?**
Yes ...just tested a freshly downloaded one. 

**Description**
CPU goes out of control when the mouse is moving over prism highlighted content. I was able to reproduce the issue on https://prismjs.com/ as you can see in [the video I put below](https://www.youtube.com/watch?v=9DDlmuVY3pU) for chrome version 77.0.3865.90. You'll see the cpu go to 100% in the task manager as the mouse is moving in the highlighted area, and then the mouse moves out of highlighted area and the cpu drops right back down. 

This was not happening in prior chrome versions. I got my hands on chrome 74 and did the [same test](https://www.youtube.com/watch?v=OM-MMdDejfw) to confirm, and no issues as expected... not sure what changed in chrome, but it aint helping prismjs :). 

I included a screenshot of my app that's using prism.. it's a simple rest client that using prism for response formatting. That particular response below is 2000+ lines and as soon as the mouse goes over it the cpu spikes much worse than the video example, and it renders all my ui components useless until it recovers. And if the user keeps the mouse over it (as they usually would) it never recovers. 

I did my tests on a 2018 macbook pro, but I did see the same behavior start happening on a windows 10 machine that just had chrome 76 pushed to it.

**Example**
Chrome 77 (cpu issue): https://www.youtube.com/watch?v=9DDlmuVY3pU
Chrome 74 (no issues): https://www.youtube.com/watch?v=OM-MMdDejfw

<img width="1184" alt="cREST" src="https://user-images.githubusercontent.com/442367/65562320-f4721280-df13-11e9-9595-8e9f58f6c060.png">

**Comment by Golmote** [comment]
I can reproduce the issue on Chrome 77 on Windows 7 too.
Performance report seems to indicate the native Hit Test tasks take a long time to run when the code blocks are hovered.

![LsrmPdy](https://user-images.githubusercontent.com/565460/65576166-b4da1380-df71-11e9-8856-87eed70254c6.png)

I assume this open issue on Chromium is related: https://bugs.chromium.org/p/chromium/issues/detail?id=428083

**Comment by jiantosca** [comment]
Thanks ...and it doesn't looks like they're in any rush to fix it, ugh.

**Comment by Golmote** [comment]
@jiantosca Can you try adding the following CSS to your use case?

```css
pre[class*="language-"] code {
    display: block;
}
```

For some reason it seems to at least reduce the issue on the Prism website.

**Comment by RunDevelopment** [comment]
@Golmote's fix seems to work. It reduces the time a single hit test from 320ms to <2ms on my PC (Win 10 + Chrome 77).
I also confirmed the bug on Chrome 76 on Win 10.

**Comment by jiantosca** [comment]
Interesting, it didn't seem to work for me on my mac. I double checked the CSS via devtools and can see the expected style. I'll dig deeper on this and see if I'm overlooking something. 

![Screen Shot 2019-09-25 at 3 11 32 PM](https://user-images.githubusercontent.com/442367/65636133-b62a3100-dfaf-11e9-8b25-32b6a1818812.png)

**Comment by Golmote** [comment]
@jiantosca Would you be able to provide us with an online example or a full code that reproduces the issue as closely as possible to your actual use case? That way we might be able to investigate deeper.

**Comment by jiantosca** [comment]
@Golmote Sure, I whipped up something simple to run locally below. It includes the style you suggested above. I gave this a shot on my win 10 machine and the cpu maxes out for me. It recovers faster (compared to my mac) when the mouse moves out of the highlighted part, but something as simple as trying to select text within the code element is near impossible. 

```html
<html>

<head>
    <script src="https://prismjs.com/prism.js"></script>
    <script src="https://prismjs.com/components/prism-http.js"></script>
    <script src="https://prismjs.com/components/prism-json.js"></script>
    <script src="https://prismjs.com/plugins/line-numbers/prism-line-numbers.js"></script>
    <link rel="stylesheet" href="https://prismjs.com/themes/prism.css">
    <link rel="stylesheet" href="https://prismjs.com/plugins/line-numbers/prism-line-numbers.css">
    <style>
        div {
            max-width: 800px;
            margin: auto;
            text-align: center;
        }
        pre {
            max-height: 500px;
        }
        
        pre[class*="language-"] code {
            display: block;
        }
        
    </style>
</head>

<body>
    <div>
        <h2>Prism Test:</h2>
        <pre class="line-numbers"><code class="language-http"></code></pre>
    </div>
</body>

<script>
    let headers = [
        'date: Wed, 25 Sep 2019 22:22:53 GMT',
        'content-type: application/json',
        'content-encoding: gzip',
    ].join('\n');

    let jsonObjects = [];
    for (let i = 0; i < 300; i++) {
        jsonObjects.push({
            id: i, 
            fname: `FirstName${i}`, 
            lname: `LastName${i}`, 
            email: `email${i}@whocares.xyz`
        });
    }

    document.querySelector('code').textContent = 
        `${headers}\n\n${JSON.stringify(jsonObjects, undefined, 3)}`;
</script>

</html>
```

**Comment by Golmote** [comment]
@jiantosca Thanks!

I found another trick that seems to leverage the issue in Chrome:

```css
pre[class*="language-"] code {
    display: block;
    position: relative;
}
pre[class*="language-"] code:before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

One of the drawbacks is that it prevents the selection of the code in Firefox (and maybe other browsers). If your use case is limited to Chrome, this might be a fix for the time being, while the bug in Chromium is being fixed.

**Comment by jiantosca** [comment]
@Golmote major improvement! I tested it on both mac and win7 and it's really fast now. My app is a chrome extension, so no worries with other browsers.

**Comment by jiantosca** [comment]
Hey Folks ...just wanted to let you know that i logged a new chrome bug that will hopefully get some traction. The issue appears to be related to LayoutNG released in chrome 76. Thanks for getting me pointed in the right direction.  

https://bugs.chromium.org/p/chromium/issues/detail?id=1008523

**Comment by jiantosca** [comment]
That bug got some traction and they they put in a fix. I tested on a dev build (79.0.3938.0) and it's looking much better.

**Comment by mAAdhaTTah** [comment]
So this sounds like it's an issue in Chrome, so nothing for us to do here. Going to close unless you think there's something we should do on our end.

Thanks for bringing this to our attention and filing the bug with Chrome!

**Comment by frantic1048** [comment]
Workaround from https://github.com/PrismJS/prism/issues/2062#issuecomment-535344324 works on Chrome 77.

> One of the drawbacks is that it prevents the selection of the code in Firefox (and maybe other browsers). 

This sounds like another issue in Chrome, however, in this case, this keeps the text inside `<code>` still selectable and reduced freezing. With essential browser version checks to apply the workaround only on Chrome >=76 makes it a practical solution. 🤨

**Comment by RunDevelopment** [comment]
Just using this should also work without the selection issue.

```css
pre[class*="language-"] code {
    display: block;
}
```

**Comment by frantic1048** [comment]
> Just using this should also work without the selection issue.

This does not have the selection issue, also not solving perf issue in my case :thinking:

**Comment by RunDevelopment** [comment]
It doesn't? This works on my machine; Chrome 78, Win 10. It also worked when I still had Chome 77.
Could you please share an example setup where you reproduce the perf issue with the fix in place?

**Comment by frantic1048** [comment]
I didn't found an easy way to construct a reproduction, but the sample in https://github.com/PrismJS/prism/issues/2062#issuecomment-535272804 is very similar to my case.

**Comment by MattOpen** [comment]
> 
> 
> @jiantosca Thanks!
> 
> I found another trick that seems to leverage the issue in Chrome:
> 
> ```css
> pre[class*="language-"] code {
>     display: block;
>     position: relative;
> }
> pre[class*="language-"] code:before {
>     content: '';
>     position: absolute;
>     top: 0;
>     left: 0;
>     width: 100%;
>     height: 100%;
> }
> ```
> 
> One of the drawbacks is that it prevents the selection of the code in Firefox (and maybe other browsers). If your use case is limited to Chrome, this might be a fix for the time being, while the bug in Chromium is being fixed.

great answer, thanks.
You can overcome the copy issue in other browser by adding z-index:-1;

`pre[class*="language-"] code {
    display: block;
    position: relative;
}

pre[class*="language-"] code:before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index:-1;
}`

**Comment by arigoldx** [comment]
Thanks y'all, this was really helpful.

I couldn't get the css workaround to work, maybe because we're highlighting too much? 🤷‍♂We decided to just remove highlighting until Chrome is fixed. Fascinating use of a pseudo element tho! Anyone know the mechanism there?

Lastly, may I suggest expanding "perf" into "performance" in the issue's title? It took me a sec to realize the true meaning of the abbreviation 😅

**Comment by arigoldx** [comment]
It's fixed in the latest version of Chrome!

Specifically, `Version 79.0.3945.130 (Official Build) (64-bit)`

:)

**Comment by MattOpen** [comment]
Since now Chrome version is 79.0.3945.117 it goes more weird and for those who have further scrolling perfomance issues like me, only add this more or less one-liner to your css, no pseudo class necessary.

`pre[class*="language-"] span {
    display: inline-flex;
}
`

**Comment by RunDevelopment** [comment]
@MattOpen 
AFAIK, #1131 and this issue are similar issues with completely different causes. Put simply the cause of this issue was that Chrome's cursor [hit test](https://github.com/PrismJS/prism/issues/2062#issuecomment-534881943) did not scale for a large number of DOM elements which was fixed in Chrome 79. 
#1131 seems to be unrelated to Chrome's hit test.

**Comment by MattOpen** [comment]
> 
> 
> @MattOpen
> AFAIK, #1131 and this issue are similar issues with completely different causes. Put simply the cause of this issue was that Chrome's cursor [hit test](https://github.com/PrismJS/prism/issues/2062#issuecomment-534881943) did not scale for a large number of DOM elements which was fixed in Chrome 79.
> #1131 seems to be unrelated to Chrome's hit test.

thanks for pointing this out. I wasn`t aware that our company rolled out a new version but not the newest version of chrome. Next time I will read the comments more carefully. :)

**Comment by jiantosca** [comment]
I came across another performance issue in the latest chrome update I got a couple days ago (88.0.4324.96). Same symptom ...spiked cpu with hit test when prism highlights large amounts.

Here's the chrome issue for anyone interested:

https://bugs.chromium.org/p/chromium/issues/detail?id=1170075

**Comment by zafernci** [comment]
> @jiantosca Can you try adding the following CSS to your use case?
> 
> ```css
> pre[class*="language-"] code {
>     display: block;
> }
> ```
> 
> For some reason it seems to at least reduce the issue on the Prism website.

Thanks buddy, it worked!
