### ISSUE TITLE
What language for CSV?

### ISSUE THREAD

**Issue by damienderoistecso** [PrismJS/prism#2065]
What language should I use for highlighting CSV data?

**Comment by RunDevelopment** [comment]
Seems like Prism doesn't have a language for CSV yet.

Do we also want to add support for [DSV](https://en.wikipedia.org/wiki/Delimiter-separated_values) and [TSV](https://en.wikipedia.org/wiki/Tab-separated_values)?

Spec:
https://tools.ietf.org/html/rfc4180

**Comment by mAAdhaTTah** [comment]
Any examples of syntax highlighting for CSVs? I'm honestly not sure I've seen that.

**Comment by RunDevelopment** [comment]
Well, there's not much to highlight.

```js
Prism.languages.csv = {
	'value': /[^\r\n",]|"(?:[^"]|"")"(?!")/,
	'separator': /,/
};
```

That would be the whole grammar, or did I forget some feature?
