### ISSUE TITLE
Random operator characters are highlighted

### ISSUE THREAD

**Issue by ZacSweers** [PrismJS/prism#2066]
**Information:**
- Prism version: 1.17.1
- Environment: Chrome, Ghost

Does the latest version of Prism from the [download page](https://prismjs.com/download.html) also have this issue? 

Yes

**Description**
A clear and concise description of what the bug is and how to reproduce it.

I'm using Prism in a Ghost blog, and certain characters are oddly highlighted (easier to show in the screenshot below). This happens with multiple languages, kotlin and json in my examples with colons/angle brackets/equals. This also happens with different themes, so it's not theme-specific.

Ghost code injection

Header: none

Footer:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/prism.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/themes/prism.min.css" />
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/themes/prism-okaidia.min.css" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-java.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-javadoc.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-kotlin.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-markup.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-json.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-graphql.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-markdown.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-diff.min.js"></script>
```

**Example**
An example which reproduces the bug. This can be a link to a website, a [JSFiddle](https://jsfiddle.net/), an attached example project, etc.

Example post: https://www.zacsweers.dev/exploring-moshis-kotlin-code-gen/

![image](https://user-images.githubusercontent.com/1361086/65635710-d3aacb00-dfae-11e9-8d58-a11cffbb3a33.png)

![image](https://user-images.githubusercontent.com/1361086/65635797-0785f080-dfaf-11e9-8976-bc1ee087f31c.png)

**Comment by RunDevelopment** [comment]
The problem is that you include both the Prism default theme (`.../themes/prism.min.css`) and the Okaidia theme (`.../themes/prism-okaidia.min.css`). You can only have one theme at a time.

Remove the default theme and everything should work as intended.

**Comment by ZacSweers** [comment]
Ah! Thanks for that
