### ISSUE TITLE
PrismJS fails to tokenize operators, calls them "punctuation" (reproducable on prismjs.com)

### ISSUE THREAD

**Issue by MattMcFarland** [PrismJS/prism#2072]
This can be reproduced on Prism.js main site: 

https://prismjs.com/test.html#language=javascript

Simply this snippet here fails to be properly highlighted by prismJs
```js
const a = b ? 0 : 1
```
The colon should have the token "operator", but instead gets the token "punctuation"

PrismJS will find the `=` to be an operator, and the `?` to be an operator, but fails to see `:` as an operator and says it is "punctuation" - which causes a different color to be present on the `:` 

![Imgur](https://i.imgur.com/r69Hz8Z.png)

There are other cases as well, I'll see if I can dig them up.

**Comment by mAAdhaTTah** [comment]
This is solely an issue with the `:`. Because prismjs is regex-based, it'll be tough to find a solution that tokenizes the `:` as an operator in a ternary but punctuation everywhere else.

**Comment by mAAdhaTTah** [comment]
Please join us on #2073. It's not clear we can even fix this, tbh, and I'm not sure I understand your use case enough to figure how we could solve this for you, if at all.

**Comment by MattMcFarland** [comment]
Hey, thanks for the replies.  There are a few other areas where punctuation is used incorrectly, that is the one I'm mostly aware of (I'll have to dig up the others)

My use case is that our UX designer wants our syntax highlighting to follow theme guidelines, and sadly because it gets tokenized as punctuation, the coloring is off.   

I'll take a look at #2073 - but I do think this is fixable, if you look at github syntax highlighting for example, they color the colons correctly.

**Comment by MattMcFarland** [comment]
Just saw that prismjs is regex based.  That definitely makes things more difficult.  I was assuming it was reading each token.
