### ISSUE TITLE
Cannot find window.Prism object after loading css and script

### ISSUE THREAD

**Issue by kuworking** [PrismJS/prism#2118]
Trying to load the `css` and `js` of Prism, I cannot find the `Prism` object (or `window.Prism`) to be able to run the `Prism.highlightAll()`

I load it from Gatsby dynamically by injecting the css first and the js after (local versions), and I can check that both are loaded in the Developer Tools from Chrome

![image](https://user-images.githubusercontent.com/4474004/69380596-13421a80-0cb3-11ea-9e08-cfc9b96a0444.png)

The script is loaded with the manual label inserted

![image](https://user-images.githubusercontent.com/4474004/69380653-353b9d00-0cb3-11ea-8a5d-d80f938a95ea.png)

But no matter what, checking the window object, `Prism` is not there

![image](https://user-images.githubusercontent.com/4474004/69380761-7764de80-0cb3-11ea-9a43-aaede3b8bd39.png)

I have also tried without the manual label, but nothing happens

What is going wrong here?

**Comment by kuworking** [comment]
*Not related to prism but to importing files with gatsby-themes and static folders, closing the issue

**Comment by mAAdhaTTah** [comment]
I'm assuming you solved this?

**Comment by kuworking** [comment]
> I'm assuming you solved this?

Yes, completely, and totally unrelated to Prism, I'd have deleted the issue (if I knew how)
