### ISSUE TITLE
Support for DAX (Data Analysis Expressions)

### ISSUE THREAD

**Issue by epieters** [PrismJS/prism#2121]
**Language**
Data Analysis Expressions (DAX) is a library of functions and operators that can be combined to build formulas and expressions in Power BI Desktop, Azure Analysis Services, SQL Server Analysis Services, and Power Pivot in Excel.

**Additional resources**
[https://docs.microsoft.com/en-us/dax/](https://docs.microsoft.com/en-us/dax/)

**Comment by bstuddard** [comment]
I would love to see this as well! @epieters - have you found any other way to render DAX as a code (```) markdown syntax?
