### ISSUE TITLE
Autoloader looks for grammars in wrong jsDelivr directory/path

### ISSUE THREAD

**Issue by Aathish04** [PrismJS/prism#2124]
**Information:**
- Prism version: 1.17 [ from jsDelivr]
- Plugins: Autoloader, Line-Numbers,Autolinker
- Environment: Browser 

**Description**
When using autolinker with jsDelivr, it looks for language grammars in the `/plugins/autolinker/components/` directory, even though the directory doesn't exist. This leaves all languages unhighlighted. The plugin should probably look for grammars in the `/components` directory instead.

**Example**
An example which reproduces the bug:
https://jsfiddle.net/Aathish04/8gwxut2s/9/

**Comment by RunDevelopment** [comment]
Autoloader tries to detect its own file path to infer the path of the `components` directory.
The problem, in this case, is that Autoloader doesn't know the semantics of a `cdn.jsdelivr.net/combine/` path (frankly, I didn't either until today) and infers the `components` path incorrectly. The full path of the 404 confirms this:

```
https://cdn.jsdelivr.net/combine/npm/prismjs@1,npm/prismjs@1/plugins/line-numbers/prism-line-numbers.min.js,npm/prismjs@1/plugins/autoloader/prism-autoloader.min.js,npm/prismjs@1/plugins/autolinker/components/prism-python.min.js
```

But that's not the end of the world as this auto-detect is mainly for convenience in trivial cases. In all other cases, you can set the path from which [Autoloader](https://prismjs.com/plugins/autoloader/#how-to-use) gets languages manually.

[Here](https://jsfiddle.net/0w9yeu82/)'s a fixed version of your fiddle.

**Comment by Aathish04** [comment]
Oh Cool! Thanks for the help!
