### ISSUE TITLE
Support for Speech Synthesis Markup Language (SSML) 

### ISSUE THREAD

**Issue by Osuka42g** [PrismJS/prism#2132]
**Language**
Text to speech markup. Each provider implements some standards plus extra features per their conveniences.
Personally more interested in Amazon's one.

**Additional resources**
https://docs.aws.amazon.com/en_us/polly/latest/dg/supportedtags.html
https://developers.google.com/assistant/actions/reference/ssml
https://docs.microsoft.com/en-us/cortana/skills/speech-synthesis-markup-language

**Comment by RunDevelopment** [comment]
Closed with [`eb70070`](https://github.com/PrismJS/prism/commit/eb70070de8027462635b4ae1ae8f8cda428ecf49).
