### ISSUE TITLE
Custom class plugin broken again.

### ISSUE THREAD

**Issue by garretwilson** [PrismJS/prism#2152]
This is a follow-up from #1137.

1. I downloaded `prism.css` and `prism.js` from https://prismjs.com/download.html#themes=prism-coy&languages=markup+css+clike+javascript+apacheconf+bash+diff+git+http+ini+java+json+markdown+powershell+properties+regex+shell-session+sql+yaml&plugins=line-numbers+custom-class+keep-markup+command-line .
2. I added the line `Prism.plugins.customClass.prefix('prism-');` at the end of `prism.js`.
3. In `prism.css` I did a search for `.token.` and replaced it with `.token.prism-`

Now my e.g. Markdown and HTML code blocks are not styled at all. The Markdown code block shows the Coy theme, but no line numbers or styling. The HTML code block doesn't even show the Coy theme. When I remove the `Prism.plugins.customClass.prefix('prism-');` line from the end of `prism.js`, the styles come back.

You can see a test document at https://github.com/PrismJS/prism/issues/1137#issuecomment-304545468, although I haven't tried that one with this bug reappearance.

I'm using Chrome 79.0.3945.88 on Windows.

**Comment by RunDevelopment** [comment]
The prefix also applies to the `.token` class, so it has to be `.prism-token.prism-{name}`.

See [examples](https://prismjs.com/plugins/custom-class/#example).
