### ISSUE TITLE
Language request, sort of: Jenkinfiles

### ISSUE THREAD

**Issue by g1ps** [PrismJS/prism#2183]
**Language**
Jenkinsfiles. Jenkins Pipeline build configuration scripts. These are written in Groovy so it's not clear why this doesn't work for them unless you're looking for file suffices i.e. `.groovy`. Jenkinsfiles are named `Jenkinsfile`.

**Additional resources**
https://jenkins.io/doc/book/pipeline/

**Comment by RunDevelopment** [comment]
> this doesn't work for them unless you're looking for file suffices i.e. `.groovy`

So I can assume that you're using the [File Highlight plugin](https://prismjs.com/plugins/file-highlight/) for your `Jenkinsfile` files?

If that's the case, then you can manually set the language to Groovy without adding a file extension like this:

```html
<pre class="language-groovy" data-src="path/to/Jenkinsfile"></pre>
```

**Comment by g1ps** [comment]
No, I'm using the Bracket Pair Colorizer plugin for VSCode. That doesn't have configuration like this. I looked for it first, so it sounds like I need that plugin to use this option in the background. I'll pass that on to the author.

Thanks.

**Comment by RunDevelopment** [comment]
I assumed that you used Prism for your website. I didn't know people used Prism for VSCode plugins. 
Interesting.

But, yes. In this case, you have to ask the author of the VSCode plugin.

**Comment by RunDevelopment** [comment]
It says so on the [plugin page](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer). I didn't actually check the project.
