### ISSUE TITLE
Prismjs with Nextjs... getting webpack loader errors

### ISSUE THREAD

**Issue by danboyle8637** [PrismJS/prism#2186]
I am building my first NextJS blog. But I can't get Prismjs to work for me. I am using Typescript... just incase this matters.

I installed the npm package and the types from npmjs. 

I installed the babel-plugin-prismjs. 

I created a .babelrc file that looks like this:

```
{
  "presets": ["next/babel"],
  "plugins": [
    [
      "prismjs",
      {
        "languages": ["javascript", "css", "jsx", "tsx"],
        "plugins": ["line-numbers"],
        "theme": "twilight",
        "css": true
      }
    ]
  ]
}
```

In my component, I wrote this:

```
import React, { useEffect, useRef } from 'react'
import Prism from 'prismjs'

const Code = () => {
  const codeBlockRef = useRef<HTMLDivElement | null>(null)

  useEffect(() => {
    if (typeof document !== undefined && codeBlockRef.current !== null) {
      Prism.highlightAllUnder(codeBlockRef.current)
    }
  }, [])

  return (
    <>
      <div ref={codeBlockRef}>
        <pre className="language-javascript">
          <code className="language-javascript">alert(it works!)</code>
        </pre>
      </div>
    </>
  )
}

export default Code
```

And I keep getting these errors:

```
./node_modules/prismjs/themes/prism-twilight.css 6:10
Module parse failed: Unexpected token (6:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  * @author Remy Bach
|  */
> code[class*="language-"],
| pre[class*="language-"] {
| 	color: white;
```

When I set css to false in the babelrc file, it works but then none of the styles show, defeating the purpose.

All of my research has not pointed me to making any webpack changes.

Thanks for any help!

**Comment by RunDevelopment** [comment]
@mAAdhaTTah

**Comment by mAAdhaTTah** [comment]
You need to configure Next.js to be able to import .css files. Look like something [like this](https://github.com/zeit/next-plugins/tree/master/packages/next-css) would do it.

**Comment by danboyle8637** [comment]
@mAAdhaTTah I did try that. But then one of the head Next guys said you don’t need this anymore with Next 9. I might head over to their repo and ask. Thanks for answer though!

**Comment by mAAdhaTTah** [comment]
It's possible their css loaders exclude files in node_modules. How to fix that depends what hooks they have available. I'm not terribly familiar with Next.js, but that would be where I'd start.

**Comment by danboyle8637** [comment]
@mAAdhaTTah Cool thanks so much!

**Comment by catb0t** [comment]
closeable...

**Comment by stfenjobs** [comment]
https://frendly.dev/posts/using-prism-js-in-next-js
