### ISSUE TITLE
Language request:cshtml

### ISSUE THREAD

**Issue by WuHaaaaa** [PrismJS/prism#2187]
**Language**
A short description of the language.
It is a language in asp.net mvc, also known as razor, detailed address: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.1
**Additional resources**
E.g. The official website, documentation or language specification.
detailed address: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.1

Thank you for everything ：)

**Comment by RunDevelopment** [comment]
Duplicate of #1225.
