### ISSUE TITLE
Code highlighting is showing white background

### ISSUE THREAD

**Issue by PR4M** [PrismJS/prism#2188]
Hello, I've an issue while using Prism.js, it's showing white background.
(See the screenshot below)

![tutorial-php-4-update-variabel](https://i.imgur.com/zAnZUvr.png)

How to fix them?

Thank you

**Comment by RunDevelopment** [comment]
This seems like a CSS issue of your website (or custom Prism theme) which affects the `.variable` and `.operator` tokens.

I can't really help you any further since you didn't provide a way to reproduce your issue (like a link to your website or your project files or a small sample setup).

**Comment by PR4M** [comment]
@RunDevelopment 

Thanks for helping, if you really need a link to my website, here it is https://kodekativ.com/id/tutorial/tutorial-php-xElo/variabel-pada-php-9AzP

Thank you

**Comment by PR4M** [comment]
@RunDevelopment 

Ah actually you are right,
There's a css code that affects the `.variable` in my https://kodekativ.com/css/components.min.css

I'll try to fix that now, thanks!

**Comment by PR4M** [comment]
@RunDevelopment It fixed

Thank you!

**Comment by RunDevelopment** [comment]
Glad I could help.

This is just a guess but could it be that you based your theme on [Prism's default theme](https://github.com/PrismJS/prism/blob/master/themes/prism.css)? If that's the case, then you might want to choose a different base theme for your dark theme.
