### ISSUE TITLE
Language Bar styling similar to Stripe?

### ISSUE THREAD

**Issue by TylerYep** [PrismJS/prism#2204]
**Motivation**
I saw a few examples of websites that use Prism such as Stripe or [BetterStack](https://betterstack.dev/blog/code-highlighting-in-react-using-prismjs/)

Both have a language bar and some very beautiful styling. I was wondering if this was already a Prism theme/other, and if not, will it be added?

**Description**
The language bar allows clear readability of the language and has much more space to add download, copy, or other commands. If not already present, I think it would be a great theme or functionality addition.

**Alternatives**
N/a

**Comment by mAAdhaTTah** [comment]
This looks like a custom design. We have a [show-language](https://prismjs.com/plugins/show-language/) plugin that looks different from that one but serves a similar purpose. It _may_ be doable with custom CSS, if you want to produce their result, but I haven't looked into it.

**Comment by RunDevelopment** [comment]
Yes, it's definitely possible. The [Toolbar plugin](https://prismjs.com/plugins/toolbar/) (used by Show language) creates the following structure to add a toolbar:

```html
<div class="code-toolbar"> <!-- toolbar wrapper -->
    <pre><code>...</code></pre> <!-- code block -->
    <div class="toolbar"> <!-- actual toolbar -->
        <div class="toolbar-item">...</div> <!-- button 1 -->
        <div class="toolbar-item">...</div> <!-- button 2 -->
    </div>
</div>
```

So you "just" have to [move the `.toolbar` at the top](https://stackoverflow.com/questions/7425665/switching-the-order-of-block-elements-with-css) and make it a block. Maybe some extras styles for the buttons, so everything looks nice and that should do it.
Not trivial but definitely doable.

**Comment by TylerYep** [comment]
Sounds good, thank you!
