### ISSUE TITLE
lang-console alias for lang-shell-session

### ISSUE THREAD

**Issue by stdedos** [PrismJS/prism#2207]
**Motivation**
In Markdown (no idea on which flavors), the "Shell Session" equivalent is called "Console".

**Description**
Could "Console" be added as an alias for "Shell Session"?

**Comment by mAAdhaTTah** [comment]
`console` sounds to generic to be bash. Is there a reason you can't use `shell-session` or `bash`? If it's a problem with that particular implementation, it should probably be solved upstream.

I'm going close this, but feel free to ask any questions you may have.

**Comment by stdedos** [comment]
> `console` sounds to generic to be bash.

No-one said that _console is bash_. In the aforelinked issue, I said that _using bash could get you some syntax highlighting_. You know, as a workaround.

> Is there a reason you can't use `shell-session` or `bash`?

It's not "a problem", but you are going against a norm that is widely used. Even e.g. here in Github:
https://github.com/simov/markdown-viewer/issues/108#issuecomment-584306738

![image](https://user-images.githubusercontent.com/133706/87767558-80e31e00-c823-11ea-8180-d802c5aa6532.png)

I get your reasoning, but from my point of view, I don't think it is so problematic given that it is an established alias.

**Comment by huyz** [comment]
Can we reopen this?

This is a problem for me. I have markdown files in Github that I'd like Github to render properly.  And I want these markdown files to also be rendered properly by GatsbyJS whose Remark plugin uses PrismJS.  Unfortunately, the language identifiers don't match.  So right now, one of these two scenarios won't work for the same Markdown source.

[Github Markdown](https://github.com/jmm/gfm-lang-ids/wiki/GitHub-Flavored-Markdown-%28GFM%29-language-IDs) supports `console`, `sh-session`, `shellsession`.  And [PrismJS](https://prismjs.com/#supported-languages) supports `shell-session`.

It doesn't have to be `console`, but could one of the 3 Github-supported identifiers be added as an alias?

**Comment by RunDevelopment** [comment]
I'll add `sh-session` and `shellsession` aliases.
