### ISSUE TITLE
Question: Highlighting later instances of an identified token

### ISSUE THREAD

**Issue by peterbud** [PrismJS/prism#2247]
I'm working on adding [DAX language](https://docs.microsoft.com/en-us/dax/) highlighting.

I have one issue where I'm struggling to find a good solution, and where I'd need some advice/help:

In DAX variables are defined with a `VAR `keyword, but later are used without this, just by name. I'm able to identify the variable definition, but I'm not able to highlight later instances.

Example:

```
TEST :=
VAR MYVARIABLE =
    SELECTEDVALUE ( 'CURRENCY'[CURRENCY CODE], "USD" )

RETURN
    MYVARIABLE

```
I can easily highlight the definition (at line `VAR MYVARIABLE` with lookbehind) but what is the best way to highlight the instance(s) later (very last row in this example)?

**Comment by RunDevelopment** [comment]
Unfortunately, it's not possible. In your case, Prism would have to _remember_ the name of the variable at its declaration to highlight below which isn't possible with Prism.

We usually only highlight variables in languages with a special syntax for variables (e.g. PHP, SQL).
Where this is not possible, we usually don't highlight variables (e.g. C/C++, JS) and I'd recommend you do the same here to keep the highlighting of variables consistent.
