### ISSUE TITLE
Assembly support

### ISSUE THREAD

**Issue by jbremer** [PrismJS/prism#225]
I'd be quite interested in Assembly listing support in Prism.js - is anything like this on planning? Given assembly's nature it'd be the best to have a "base" assembly language plugin, so specific architectures can be forked from it.

The base assembly language would be like.. one instruction per line, comments, labels, and special annotation. From there on we can have a plugin for x86, x64, etc, I think, in which the various instructions and registers are listed as keywords or so.

Please let me know what you think about this. I'd be happy to define the specific assembly language(s) on an as-needed basis for myself, but it'd be very nice to get some help with the base plugin, as the core developers are surely much more familiar with the kinky regex queries used in prism.js than me ;)

Again, thanks for the plugin, it looks great, and, unlike other similar projects, only has a very small footprint :-)

**Comment by mutex36** [comment]
Hey. It's been 3 years now. Is there support for x86 assembly (at least) planned?

**Comment by sshine** [comment]
See #482 for nasm as a fallback.
