### ISSUE TITLE
Plugin only works once in single page application

### ISSUE THREAD

**Issue by jakobrosenberg** [PrismJS/prism#2251]
**Information**
- Language: any
- Plugins: prismjs/plugins/normalize-whitespace/prism-normalize-whitespace

**Description**
On page visit the plugin works correctly. If I navigate to another page and come back, the plugin no longer does anything. (Console.logging Prism shows that the plugin is still loaded in the ``plugins`` and ``hooks`` prop.)

Here's the implementation
https://github.com/jakobrosenberg/svelte-prism/blob/master/src/Prism.svelte

**Comment by mAAdhaTTah** [comment]
If you're going to integrate with a SPA, you'll need to call `Prism.highlight` or `highlightAll` (depending on how you integrate it) after every render, cuz most modern view frameworks will put the DOM back into its pre-highlighted state. Prism by default only highlights on initial page load.
