### ISSUE TITLE
PrismJS collapses all SlateJS codelines in a code block into single string in one line

### ISSUE THREAD

**Issue by ScottAgirs** [PrismJS/prism#2253]
**Information**
- Language: JavaScript
- Plugins: none

**Does the problem still occur in the latest version of Prism?**
yes

**Description**
Before the Prism.highlightAll() is applied, the markup looks like this
![image](https://user-images.githubusercontent.com/11737572/77033725-73557e80-697e-11ea-871d-f425fc941f73.png)

once it's `highlightAll()` is run it collapses all into this
![image](https://user-images.githubusercontent.com/11737572/77033816-a26bf000-697e-11ea-8c8b-3fddcabfdf53.png)

**Code snippet**
```javascript
  useEffect(() => {
    Prism.highlightAll();
  }, []);
```
I've spent lots of time trying to figure out how to make PrismJS work with SlateJS, please help fellow people in (or not-in) self-isolation. 🤞🙏 🙏 🤞

**Comment by mAAdhaTTah** [comment]
Can you provide a reproducible example?

**Comment by RunDevelopment** [comment]
I can already see the problem in the markup.

SlateJS will split the code by lines and put each line in its own `div.codeLine` element, right? The problem is that Prism will remove all markup inside the element it is highlighting (the `code` element).

I don't kown if it'll work, but try the [Keep markup plugin](https://prismjs.com/plugins/keep-markup/). It _should_ solve your problem.

**Comment by ScottAgirs** [comment]
> I can already see the problem in the markup.
> 
> SlateJS will split the code by lines and put each line in its own `div.codeLine` element, right? The problem is that Prism will remove all markup inside the element it is highlighting (the `code` element).
> 
> I don't kown if it'll work, but try the [Keep markup plugin](https://prismjs.com/plugins/keep-markup/). It _should_ solve your problem.

@RunDevelopment thanks and you are right- that's exactly what Slate does and indeed it feels like this could be the solution.

A real dummy question - I'm not sure I understand how to use PrismJS plugins in React, cannot find proper docs for this either (sorry if i'm bluntly missing something that's right in front of my eyes, hah)

Currently, I import Prism and use it inside a `useEffect()`. How can I activate/add Prism's plugin(s)?

```javascript
import Prism from 'prismjs';
...

const MyEditor = props => {
  useEffect(() => {
    Prism.highlightAll();
    Prism.plugins.keepMarkUp(); // would something like this work? (this in particular doesn't work) 
  }, []);

...
```
if I add it in babel configs like so
```
{
...
 "plugins": [
                "line-numbers",
                "show-language",
                "keep-markup"
              ],
...
}
```
I get this: 

![image](https://user-images.githubusercontent.com/11737572/77080653-ecc98d00-69cf-11ea-825a-f851a842ebd2.png)

**Comment by RunDevelopment** [comment]
You don't have to call the Keep markup plugin at all. It will do its magic automatically.

Regarding the babel plugin: I feel like @mAAdhaTTah is more qualified to answer your question.

**Comment by mAAdhaTTah** [comment]
The babel plugin appears to be configured correctly, since the `keep-markup` plugin is getting pulled in.

**Comment by ScottAgirs** [comment]
> The babel plugin appears to be configured correctly, since the `keep-markup` plugin is getting pulled in.

I felt the same way! so how could I troubleshoot this? Could it have something to do with the fact that it's a Next.js app?

**Comment by mAAdhaTTah** [comment]
Best way to troubleshoot is share a reproducible example.

**Comment by ScottAgirs** [comment]
@mAAdhaTTah please see this - https://github.com/ScottAgirs/playground-istyled-nextjs/tree/prismjs-slatejs

**Comment by ScottAgirs** [comment]
@mAAdhaTTah did the reproduction help?

**Comment by ScottAgirs** [comment]
Closing in favour of https://github.com/PrismJS/prism/issues/2257

**Comment by Sarfinaa** [comment]
![image](https://user-images.githubusercontent.com/52121542/122668386-6eacf500-d1d5-11eb-9d4b-a99d05ee70a7.png)
whenever i click on editor this happens-
![image](https://user-images.githubusercontent.com/52121542/122668408-8c7a5a00-d1d5-11eb-81ca-a9aeeac3643e.png)
I dont know to solve this issue please help me out.
