### ISSUE TITLE
Add support for prefers-color-scheme: dark

### ISSUE THREAD

**Issue by Stanzilla** [PrismJS/prism#2254]
**Motivation**
Ideally you will want to switch between a dark and a light theme depending on users preferences

**Description**
Add a way to load a different theme/css file based on prefers-color-scheme

**Comment by RunDevelopment** [comment]
I don't think that Prism should deal with this. I think that it's the responsibility of the site to load an appropriate theme.

That being said, if you really need this feature, then this will work:
```html
<head>
<!-- the usual stuff -->
<script>
(function(){
var light = 'https://path.to/light-theme.css';
var dark  = 'https://path.to/dark-theme.css';
// if the media query isn't supported, the light theme will be used
var theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? dark : light;

var link  = document.createElement('link');
link.rel  = 'stylesheet';
link.type = 'text/css';
link.href = theme;
document.head.appendChild(link); 
})();
</script>
</head>
```
