### ISSUE TITLE
ReferenceError: self is not defined - prism-keep-markup

### ISSUE THREAD

**Issue by ScottAgirs** [PrismJS/prism#2257]
**Information:**
- Prism version: "prismjs": "^1.19.0"
- Plugins: `.babelrc` `{ ... ["line-numbers", "show-language", "keep-markup"]`
- Environment: [Next.js]

**Does the latest version of Prism from the [download page](https://prismjs.com/download.html) also have this issue?**
Yes

**Description**
After adding `"keep-markup"` to the plugins list, the app fails:
![image](https://user-images.githubusercontent.com/11737572/77228576-ba9a6580-6b5e-11ea-8227-5d669fd70f01.png)

**Example**
Reproduction available below
_PS you can stop the app from crashing by disabling `"keep-markup"` in .babelrc_
https://codesandbox.io/s/nextjs-prismjs-slate-u5rmz

**Comment by mAAdhaTTah** [comment]
What browser is this in? When I pull this up in Chrome, `self` definitely exists. It also exists in FF. Maybe this is server-side...?

**Comment by RunDevelopment** [comment]
Why do we [pass `self` as a parameter](https://github.com/PrismJS/prism/blob/8119e57b7b921f97936ffdd2c7d0fa632f14dce2/plugins/keep-markup/prism-keep-markup.js#L1) and then check inside the function whether it will cause a reference error?

**Comment by ScottAgirs** [comment]
@mAAdhaTTah I use Chrome, also tested on Safari and Brave. I did, however, try adding the following:
```javascript
const isBrowser = typeof window !== 'undefined';
if (isBrowser) {
   Prisma.highlightAll();
}
```
yields same result. That said, it looks like the error occurs not on the call, but on the `Prism` instance import itself

@RunDevelopment - I'm guessing this question is not for me(?)

**Comment by RunDevelopment** [comment]
No, it wasn't. Sorry for not clarifying.

**Comment by mAAdhaTTah** [comment]
@RunDevelopment Yeah, we're pretty inconsistent on how we check what the global variable is, looking at our plugins.

---

> That said, it looks like the error occurs not on the call, but on the Prism instance import itself

That makes sense, because that's when `self` is first referenced. That said, it _looks_ like the error is on the server-side, rather than in the browser. Or maybe it's both? Pretty odd...

**Comment by mAAdhaTTah** [comment]
Ok. So removing the passing-in of `self` & `document` seems to resolve the issue locally for me. That's the only plugin that passes in those variables, oddly enough. Will PR shortly.

That said, there are some other underlying issues uncovered by this. `line-numbers` does not look good, and I'm getting `Uncaught Error: Cannot resolve a Slate node from DOM node: [object HTMLDivElement]` errors trying to type into the Slate editor. If Slate is wrapping each line in its own DOM node, I don't think we can guarantee that Prism will behave correctly.
