### ISSUE TITLE
PrismJS doesn't detect/highlight properly JSX 

### ISSUE THREAD

**Issue by ScottAgirs** [PrismJS/prism#2259]
**Information**
- Language: [JavaScript-React]
- Plugins (configs): 
```js
"plugins": [
          [
            "prismjs",
            {
              "languages": [
                "jsx",
                "css",
                "html"
              ],
              "plugins": [
                "show-language",
                "keep-markup"
              ],
              "theme": "okaidia",
              "css": true
            }
          ],
          [
            "styled-components",
            {
              "ssr": true,
              "displayName": true
            }
          ]
        ]
```
<img width="611" alt="Screen Shot 2020-03-21 at 2 20 36 PM" src="https://user-images.githubusercontent.com/11737572/77233634-25f42f80-6b7f-11ea-8542-f0770328ede6.png">

**Does the problem still occur in the latest version of Prism?
You can check using the [test page](https://prismjs.com/test.html) or get the latest version at the [download page](https://prismjs.com/download.html).**
Yes

**Description**
The JSX markup is not working.

**Code snippet**
<details>
<summary>The code being highlighted incorrectly (doesn't detect JSX).</summary>

```
    "languages": [
                // I have also tried adding/removing "javascript" from this array
                "jsx",
                "css",
                "html"
              ],
```

</details>

**Comment by RunDevelopment** [comment]
I tried your code on the [test page](https://prismjs.com/test.html#language=javascript).

Are you sure you're using the `jsx` language to highlight your code because the tokenization is identical to `javascript`?

**Comment by ScottAgirs** [comment]
@RunDevelopment hey, thanks for trying it out! 

I hope I'm using it right - the way I'm should be specifying it is by adding "jsx" in the babel config, right?
My configs are below:
```javascript
 "plugins": [
          [
            "prismjs",
            {
              "languages": [
                "jsx",
                "css",
                "html"
              ],
              "plugins": [
                "keep-markup",
                "copy-to-clipboard"
              ],
              "theme": "okaidia",
              "css": true
            }
          ],
```

**Comment by RunDevelopment** [comment]
No, I mean the `language-xxxx` class of the element you're trying to highlight is probably set to `language-javascript` instead of `language-jsx`.

**Comment by RunDevelopment** [comment]
Judging from the screenshot in #2260, it seems I'm correct.

**Comment by ScottAgirs** [comment]
> Judging from the screenshot in #2260, it seems I'm correct.

ohh shocks!! what a goof! :D I tried changing back and forth in both - in languages, .babelrc, and in the element markup, but looks like I changed back the markup at one point, lol.

Thanks so much @RunDevelopment !!! this solved!
