### ISSUE TITLE
Extra <br /> being inserted with an empty string Slate node

### ISSUE THREAD

**Issue by ScottAgirs** [PrismJS/prism#2260]
**Information:**
- Prism version: latest
- Plugins:   ["keep-markup",  "copy-to-clipboard"],
- Environment: Next.js

**Description**
An extra line is added after Prism processes the code block generated by SlateJS.
It looks like the part that throws Prism off is this
```javascript
      {
        "type": "code-line",
        "children": [
          {
            "text": ""
          }
        ]
      },
```
where for the empty node 2 different `<span />` are generated - one with an escaped character `&#65279;` (**the desired outcome**) and one with an extra `<br />` (**should be removed**).

I tried looking at the source code and couldn't figure out what could be doing this - any help?

![image](https://user-images.githubusercontent.com/11737572/77236113-cfdcb780-6b91-11ea-8169-54912c5ce875.png)

```javascript
[
  {
    "type": "code-block",
    "children": [
      {
        "type": "code-line",
        "children": [
          {
            "text": "const variable = \"made of string\";"
          }
        ]
      },
      {
        "type": "code-line",
        "children": [
          {
            "text": ""
          }
        ]
      },
      {
        "type": "code-line",
        "children": [
          {
            "text": "function goGetIt() {  "
          }
        ]
      },
      {
        "type": "code-line",
        "children": [
          {
            "text": "  return <h1>I am a JSX title</h1>"
          }
        ]
      },
      {
        "type": "code-line",
        "children": [
          {
            "text": "}"
          }
        ]
      }
    ]
  }
]

```

**Comment by RunDevelopment** [comment]
I don't quite understand the problem. Keep markup doesn't add any elements, so what do you want the outcome to be?

Also, what's the input markup for Prism and does this happen for all empty lines?

**Comment by ScottAgirs** [comment]
@RunDevelopment you are right, from looking at non-Prism'ed markup it appears that this is related to SlateJS - will work with that.
![image](https://user-images.githubusercontent.com/11737572/77236540-e553e080-6b95-11ea-97d7-411896b8f6ac.png)

Thanks again!! 🙌🤘

**Comment by alex-calderwood** [comment]
This is closed but I am still running into the issue...
