### ISSUE TITLE
Global CSS cannot be imported from files a component

### ISSUE THREAD

**Issue by ScottAgirs** [PrismJS/prism#2261]
**Information:**
- Prism version: latest
- Environment: Next.js (SSR)

**Description**
PrismJS is importing .css together with Prism instance. 
This breaks the latest Next.js built-in css imports.

<img width="1055" alt="Screen Shot 2020-03-23 at 11 18 12 PM" src="https://user-images.githubusercontent.com/11737572/77384754-9310ec00-6d5c-11ea-929c-c35656f8a0b0.png">

This could be resolved if the .css were imported explicitly (the user would be importing the .css with a separate import statement). For example:

```import 'prismjs/plugins/toolbar/prism-toolbar.css'```

Have I missed a part of docs (🤞) which explains how to disable auto css-imports and do it manually or is this currently not supported?

While it's nice and elegant the abstraction it would be nice to have control over this.

**Comment by mAAdhaTTah** [comment]
If this is with the babel plugin, you can configure whether css is imported via the plugin configuration. I don't think it's imported by default so you may have copied the config from the README.

Otherwise, how are you handling Prism?

**Comment by ScottAgirs** [comment]
@mAAdhaTTah thanks for that, I'm not sure actually ... Does the below shed any light on how I am doing it? :))
**babel**
```javascript
 [
            "prismjs",
            {
              "languages": [
                "jsx",
                "css",
                "html"
              ],
              "plugins": [
                "keep-markup",
                "copy-to-clipboard"
              ],
              "theme": "okaidia",
              "css": true
            }
          ],
```

**MyComponent.js**
```javascript
import Prism from 'prismjs';

const MyComponent = () => (...)
```

**Comment by ScottAgirs** [comment]
Ahhh, this was silly...
@mAAdhaTTah thanks!

removing the "css": true from babel config did the trick!

Cheers!
