### ISSUE TITLE
PrismJS markup broken with Next.js in production environment

### ISSUE THREAD

**Issue by ScottAgirs** [PrismJS/prism#2262]
**Information:**
- Prism version: ^1.19.0
- Plugins: [keep-markup]
- Environment: Next.js

**Description**
`keep-markup` and Prism works in development, but is broken in the production environment, or if built and started locally.

### Example
**Deployed app:**
https://prism-slate-next-issue.now.sh/

**For Reproduction locally:**
https://github.com/ScottAgirs/playground-istyled-nextjs

**Comment by RunDevelopment** [comment]
In your deployed app, Keep Markup isn't loaded.

```
Prism.plugins.KeepMarkup // should be `true`
```

**Comment by ScottAgirs** [comment]
Ahhh, thanks @RunDevelopment !

If anyone runs into a similar situation - check .babelrc plugin options, make sure you are not separating environments, and if you are, make sure the plugins are enabled in all environments you want the plugins to work :)
