### ISSUE TITLE
language request: treeview

### ISSUE THREAD

**Issue by muescha** [PrismJS/prism#2264]
**Language**

format code blocks which is the result of the `tree` command shout be included in the core.

example of treeview:

```
root_folder/
|-- a first folder/
|   |-- holidays.mov
|   |-- javascript-file.js
|   `-- some_picture.jpg
|-- documents/
```

**Additional resources**

https://www.npmjs.com/package/tree-cli
https://github.com/Golmote/prism-treeview/ from @Golmote
https://codepen.io/anon/pen/GWxyNj

**Comment by RunDevelopment** [comment]
@Golmote 
Looks really cool, gotta admit. If you want to, I can turn this into a plugin.

@muescha 
Thanks for providing the codepen.

**Comment by Golmote** [comment]
@RunDevelopment Oh, a plugin would be a good idea, probably! I might be more difficult for people to find it, but the additional required stylesheet does not leave many more possibilities I assume.

**Comment by RunDevelopment** [comment]
Well, we _could_ make it a language definition and a plugin, so that the language (containing the grammar) requires the plugin (containing the stylesheet).
Will work, but... it kinda goes against the idea of Prism's languages and plugins.

**Comment by Golmote** [comment]
Yeaaah, that sounds hacky... A plugin would be good enough I think.

**Comment by muescha** [comment]
PS: The CodePen comes from @Golmote ( https://github.com/Golmote/prism-treeview/issues/1#issuecomment-288247628 )
