### ISSUE TITLE
Wrapping any code line in a parent

### ISSUE THREAD

**Issue by tommywalkie** [PrismJS/prism#2278]
**Motivation**
Currently using `gatsby-remark-prismjs`. Sometimes Prismjs leave un-highlighted code as plain text. Taking `diff` language for example, we end up with something like this :
```
<pre class="language-git">
   <code class="language-git">
       Some line
       <span class="token deleted">- Some deleted line</span>
       <span class="token inserted">+ Some added line</span>
       Some line
   </code>
</pre>
```
As far as I understand how Prismjs works it tokenizes and wrap things into `<span>` only where it matters.
Without going too much into details I would like to handle un-tokenized code as well but when it is left as plain text without parent tag, it becomes quite tricky to do so. It would have been nice if each line was wrapped in a parent `<span>` or something else.

**Description**
I once used [`react-syntax-highlighter`](https://www.npmjs.com/package/react-syntax-highlighter) which had this useful `wrapLines` prop.

> - `wrapLines` - a boolean value that determines whether or not each line of code should be wrapped in a parent element. defaults to false, when false one can not take action on an element on the line level. You can see an example of what this enables here
> - `lineProps` - props to be passed to the span wrapping each line if wrapLines is true. Can be either an object or a function that receives current line number as argument and returns props object.

I think **I should maybe switch from** `gatsby-remark-prismjs` **to** `react-syntax-highlighter` **in my use case**. But just to be sure, is it planned to add `wrapLines` prop-_like_ option or plugin to Prismjs in the future ? Or is there an available feature that could sort of help with this use case ?

**Comment by RunDevelopment** [comment]
Sorry, but Prism doesn't have any feature which splits tokens into lines and AFAIK we don't plan on adding anything of the sorts. It's simply a feature that isn't necessary for highlighting and even line-based processing (which some of our plugins do).

Using [Keep Markup](https://prismjs.com/plugins/keep-markup/), it shouldn't be too hard to implement. But since you can, I'd also suggest switching to a library which does that for you.
