### ISSUE TITLE
Line numbers visibility toggling

### ISSUE THREAD

**Issue by SamuelCabralCruz** [PrismJS/prism#2284]
**Information:**
- Prism version: [1.20.0]
- Plugins: [line-numbers]
- Environment: [Browser]

**Description**
Line numbers are not recomputed after toggling pre element visibility.

**Example**
Render the pre element with display: none. 
Then, toggle the visibility.
All numbers are stacked one over another.

![Screenshot from 2020-04-05 11-54-45](https://user-images.githubusercontent.com/15621634/78503404-510c8080-7734-11ea-853c-5befc7d9272e.png)

**Comment by mAAdhaTTah** [comment]
I think this is something that would need to be handled userland. If you know when the `pre` is toggled, after it's been toggled, you can rehighlight the element, which should put everything correctly into place.
