### ISSUE TITLE
Make it easier to download non-bundled files

### ISSUE THREAD

**Issue by falconair** [PrismJS/prism#229]
Just started experimenting with prism, so far it looks great. 
I think it will be very nice to download the prism core (compressed), separate from plugins and themes. For example, I am trying to deicide between a dark theme and light one. Right now, I have a single prism.js and a single prism.css. Once I've settled on a configuration, I can come back to the prismjs site and download the bundle exactly as I want it. If I'm writing something, I may only need the syntax highlighter for java or ruby, not both. I'd like to be able to pick the right syntax highlighter for a specific blog post.

**Comment by loganfranken** [comment]
The download page does an awesome job of this:
http://prismjs.com/download.html

I think this can be closed?

**Comment by Golmote** [comment]
And individual components can be found (minified and not minified) in the [components folder](https://github.com/PrismJS/prism/tree/gh-pages/components) on GitHub.
