### ISSUE TITLE
Scheme missing special keywords

### ISSUE THREAD

**Issue by jcubic** [PrismJS/prism#2303]
Found another missing features in Scheme syntax:

```scheme
(syntax-case x)
(letrec-syntax x)
(let-syntax x)
```
They are special syntax for hygienic macro system, they are documented on [Wikipedia](https://en.wikipedia.org/wiki/Scheme_(programming_language)).

**Comment by jcubic** [comment]
syntax-case is optional it's part of R6RS, GitHub don't highlight but Prism can support it, it's minor chnage.

**Comment by jcubic** [comment]
I'm wondering it's worth adding `define-macro` maybe multiple variants like `/(def(ine)?-?macro)/`

that will match:
```
define-macro
def-macro
defmacro
definemacro
```
this will make sure that different scheme implementations will have macro as keyword, I think that only `defmacro`  and `define-macro` are needed, define-macro is more Scheme like (even that they are lisp macros) and `defmacro` is Common Lisp keyword.

**Comment by RunDevelopment** [comment]
Lisp has its own language definition independent of Scheme, so we don't need to add keywords to Scheme that aren't part of Scheme.

**Comment by jcubic** [comment]
`define-macro` is supported by lot of implementations, I think that it's not standard to have always given name, https://www.biwascheme.org/ supports `define-macro` the same as my interpreter, but it's not part of the standard.

**Comment by RunDevelopment** [comment]
In that case, I'll add it. I thought it was Lisp-specific.
