### ISSUE TITLE
Split up release package & gh-pages build

### ISSUE THREAD

**Issue by franz-josef-kaiser** [PrismJS/prism#231]
The whole repo really needs a `master` and `gh-pages` branch with different contents:

 * `gh-pages` -> build for the actual docs page
 * `master` -> development source + `dist` directory that holds the `gh-pages` branch

Short intro on how to split this one up:

 1. Add a `master` branch: `git branch -b master`
 2. Add the branch to the GitHub repo: `git push origin master` (in case the remote repo is locally named `origin` - one can check that by using `git remote -v`).
 3. Switch to `master` branch: `git checkout master`
 4. Add a `dist` folder: `mkdir dist`
 5. Add the folder to the repo: `git add dist && git commit -m "distribution folder added"`
 6. Point the subtree from the `dist` folder to the `gh-pages` branch: `git subtree push --prefix origin gh-pages`

Done.

Now development can get split up between the actual releases and the page.

**Comment by loganfranken** [comment]
As I've been looking through the issues, this is a pretty hot topic (the whole `gh-pages` as the main branch over `master` debate): I think we might want to try and keep the discussion in one place.

I think #180 is where most of this talk is happening right now.

Maybe we can close this issue as a duplicate?

**Comment by Golmote** [comment]
You're right. See #180 for discussion about this.
