### ISSUE TITLE
Use pipe attribute selector

### ISSUE THREAD

**Issue by valtlai** [PrismJS/prism#2323]
Currently, Prism uses selectors like `[class*="lang-"]`. It works but it also selects classes like `foolang-css`.

That doesn’t usually matter, but there’s more correct selector which looks like this: `[class|="lang"]`. It selects the class `lang-css` but not `foolang-css` or even `foo-lang-css`!

Could we use it?

**Comment by RunDevelopment** [comment]
That won't work with Prism because there may be any number of classes before the `lang-xxxx` (or `language-xxxx`) class. With `[class|="lang-"]`, elements like `<pre class="line-numbers lang-html"><code></code></pre>` will not be selected.
