### ISSUE TITLE
Line numbers aren't in the right line - mobile devices

### ISSUE THREAD

**Issue by hakan-x** [PrismJS/prism#2329]
If I publish about 20 lines code and choose a few of them with line numbers, those chosen line numbers within the background colours are not in the right line height. The first line numbers are in the right position, but the line numbers after approx. 10th line aren't in the right position. This happens on mobile devices (Safari and Chrome). You can see this behaviour also on the Website -> Prismjs -> Line Highlight -> How to use -> Examples -> Line 43, starting from line 41. Maybe someone has a solution. Thank you.

**Comment by RunDevelopment** [comment]
Maybe #1678 helps. 
There's also an issue with zooming. If you zoom the page, line numbers might start to drift go out of sync with the actual lines.

That being said, I cannot reproduce the issue you described. I don't own any Apple products, so a screenshot of [the page](https://prismjs.com/plugins/line-numbers/) would be nice. 
Also, what about [Responsive view](http://responsiv.eu/)?
