### ISSUE TITLE
PrismJS Live

### ISSUE THREAD

**Issue by sergwx** [PrismJS/prism#2339]
**Information:**
- Prism version: 1.20
- Plugins: none
- Environment: Firefox

**Description**
Wrong render of code when x-scroll is visible. Behavior present on https://live.prismjs.com/ using Firefox but is present on Chrome too with other code but less disturbing.

**Example**
![firefox_oQ8knUgfAh](https://user-images.githubusercontent.com/9361205/80557830-e53ed000-89e0-11ea-8a31-fb1575ed3a3d.jpg)

**Comment by RunDevelopment** [comment]
Please report this in [PrismJS/live](https://github.com/PrismJS/live/issues).
