### ISSUE TITLE
PureBasic

### ISSUE THREAD

**Issue by HeX0R101** [PrismJS/prism#2362]
**Language**
A language based on Basic (BlitzBasic to be precise) with inline assembler also and direct API calls. Can compile on Windows, Linux and MacOS

**Additional resources**
web site: https://www.purebasic.com
Documentation: https://www.purebasic.com/documentation/

I already started to create it on my own, but I'm a real moron, when talking about regex, and I also borroght some parts from a resource I found.
So it is far away from being perfect, but on the test side it works quite good.
npm run test:languages -- --language=purebasic --pretty also didn't show any problems, but npm test errors our, and I have no idea why.
I've attached all I have done so far.

Thanks!

BR
Tom
[prism_purebasic.zip](https://github.com/PrismJS/prism/files/4574221/prism_purebasic.zip)

**Comment by RunDevelopment** [comment]
> `npm run test:languages -- --language=purebasic --pretty` also didn't show any problems, but `npm test` errors our, and I have no idea why.

`npm run test:languages` basically just ensure that your language works and that it's correct. `npm test` also includes some really strict tests for regexes, patterns, and names. I added these in because they are all things that can be potential errors and I will them point out in review anyway.
Could you please tell me what error you got? (I want to add a more descriptive error message.)

**Comment by HeX0R101** [comment]
Please see attached
![npm_test_errorscreen](https://user-images.githubusercontent.com/64781117/80976241-7cfa4f00-8e23-11ea-8e5c-085f24209ff6.png)
[2020-05-04T10_15_45_316Z-debug.log](https://github.com/PrismJS/prism/files/4575215/2020-05-04T10_15_45_316Z-debug.log)

**Comment by RunDevelopment** [comment]
Is this error message clearer?

<details>

![image](https://user-images.githubusercontent.com/20878432/80985715-de281f80-8e2f-11ea-8268-559c239263fb.png)

</details>

(I'm sorry that I don't just tell you what to do here but I really want that you and others are able to understand why this error is there and how to fix it.)

**Comment by HeX0R101** [comment]
No need to apologize, I'm fine with showing me the door and letting me walk through alone.
Yes, that description should help indeed!
Let me see, if I can make it shut-up now.
Any chance to make the red color of the error messages a little lighter? It's quite hard to read...

**Comment by RunDevelopment** [comment]
The was just a little screenshot. #2364 is now in master, so you can get the changes and read the errors in your favorite color 😄.

If you have any other questions or can't make some errors disappear, feel free to ask. My little experiment is now over.

**Comment by HeX0R101** [comment]
I'm not very familar with git... but I think I made the language description work.
I've cloned the master, and integrated the changes to my local copy.
Can I just "push" the changes to the master, or will I somehow destroy your master then?

**Comment by RunDevelopment** [comment]
I will take "integrated" as committed. You can push the master branch to your fork, that will work. (Not ideal but simple)

**Comment by RunDevelopment** [comment]
Also, you generally can't destroy (as in lose data) anything with git. (Technically, you can but you have to try really hard for that.)

**Comment by RunDevelopment** [comment]
#2369
