### ISSUE TITLE
comment inside code is not working

### ISSUE THREAD

**Issue by suvamkundu** [PrismJS/prism#2380]
I am using the commenting feature for markup languages, suggested in the doc. It is working fine with usual contents. But whenever there is a commented line (  ) inside the content, the content is breaking. it is some thing like this,

markup language content
--> 

is there any workaround for this?

**Comment by RunDevelopment** [comment]
Cannot reproduce.

Please provide an actual code example that reproduces your issue.

**Comment by suvamkundu** [comment]
The content I am using is - 

     <area shape="rect" coords="517,260,698,440" href="http://example.com" /> </map> -->

note: I am using the commenting method, which is wrapping the entire html with comment syntax, as this is an html ()

and the output it is showing is
![image](https://user-images.githubusercontent.com/26181202/81939752-5ce14180-9614-11ea-8e06-8a5bda24f499.png)

**Comment by RunDevelopment** [comment]
> note: I am using the commenting method, which is wrapping the entire html with html comment syntax, as this is an html code.

Do you mean [Unescaped Markup](https://prismjs.com/plugins/unescaped-markup/)?

I _think_ I understand your problem now. The comment inside the Markup you want to highlight prevents Unescaped Markup from working. Your content gets commented like this, right:

![image](https://user-images.githubusercontent.com/20878432/81950089-d02e8780-9603-11ea-8ba2-98d5207dac3b.png)

Here, Prism will ignore all tags and is left the text: "-->" (and some spaces). Unescaped Markup will only look for comments if there is no text, but the "-->" is text, so it won't do anything.

Ok, that's _why_ we only see "-->". What can we do to fix it? Not much.
HTML doesn't support nested comments, so any "-->" in your Markup text will end the outer comment. You could try `<script>` tags instead but then your Markup text cannot contain the text "</script>".

The easiest solution is to escape all `<` in your text with `&lt;`. It's tedious but it will always work.

**Comment by suvamkundu** [comment]
Hi,
We have tried implementing your suggestion. We have replaced all the '<' character with '&lt;'.
![content](https://user-images.githubusercontent.com/26181202/85520102-15d96980-b620-11ea-8de0-34f056011474.png)
This is the content we're providing right now to prism.js.
![result](https://user-images.githubusercontent.com/26181202/85520237-3e616380-b620-11ea-9f9a-2a053da6a1a5.png)
But still it is showing only this.

 We need a solution where we can have nested comments in our markup codes.

**Comment by RunDevelopment** [comment]
Hmmm. That `&lt;`-escaping should work. Maybe there's some double unescaping going on?

Do you insert the text to highlight into the `<code>` element manually via JS or is it a simple static page? 
Also, what is the first screenshot? That's Chrome dev tools, right? What string did you print?

**Comment by suvamkundu** [comment]
Yes we insert the code snippet into <code> tag via JS, dynamically.
Yes, that is chrome dev tools screenshot. That is the exact string that we are inserting inside <code> tag, after replacing '<' characters.

**Comment by RunDevelopment** [comment]
Then why don't you set the `textContent` of the `<code>` elements? This way you don't have to worry about escaping at all.

**Comment by suvamkundu** [comment]
Okay we will trying doing that and get back. Thanks.

**Comment by suvamkundu** [comment]
Hi, we have tried setting the textContent to the 'code' tage. But still gives us the same output.
after setting the textContent it looks like this
![content](https://user-images.githubusercontent.com/26181202/86601189-a0c24880-bfbe-11ea-95e4-95d1e9b597ff.png)

But after the prism conversion it still looks same as before 
![output](https://user-images.githubusercontent.com/26181202/86601263-b899cc80-bfbe-11ea-8dbc-72e4e1c968a4.png)
 Seems like it does not support nested comments for HTML codes.

**Comment by RunDevelopment** [comment]
Prism supports any kind of text ([try it out](https://prismjs.com/test.html#language=markup)).

Could you please provide an example that reproduces your issue? A [JSFiddle](https://jsfiddle.net/) or example project is fine.

**Comment by suvamkundu** [comment]
Hi
[html_code_snippet.txt](https://github.com/PrismJS/prism/files/4994977/html_code_snippet.txt)

This is the code snippet in the above file that we are trying to use. and we are using HTML language here. Note that we have wrapped the entire code block with html comment syntax (). That is the prism's commenting feature that's used for markup type language.

**Comment by suvamkundu** [comment]
here is the [jsfiddle](https://jsfiddle.net/suvamkundu/rthv0myb/4/)

**Comment by RunDevelopment** [comment]
> We need a way to use that nested comment in html type languages.

We don't. These comments are just a convenient workaround for not escaping `<` and `&` characters in your code.

```html
&lt;!--
&lt;map name="map">
&lt;!-- #$-:Image map file created by GIMP Image Map plug-in -->
&lt;!-- #$-:GIMP Image Map plug-in by Maurits Rijk -->
&lt;!-- #$-:Please do not edit lines starting with "#$" -->
-->
```

I know it's a bit annoying but that's just how HTML/XML works. As a JS library, we can't change the HTML language.

However, if you really must, you can use `<script>` tags with the [Unescpaed Markup plugin](https://prismjs.com/plugins/unescaped-markup/#how-to-use). It's another workaround, so it can't contain the text `</script>` (for obvious reasons).
