### ISSUE TITLE
unclean work with class names (adding unneeded spaces during DOM manipulations)

### ISSUE THREAD

**Issue by galaxy4public** [PrismJS/prism#2383]
**Information:**
- Prism version: latest (from the master branch)
- Plugins: none
- Environment: Browser

**Description**

The way how PrismJS works with class attributes for languages (See: https://github.com/PrismJS/prism/blob/master/components/prism-core.js#L260) is unclean since it introduces unnecessary leading white space, e.g. if the original HTML was:
```
<pre class="highlight">
  <code class="language-css">
     some code
  </code>
</pre>
```

After PrismJS.highlightAll() it would become (there are two spaces in front of `language-XXX` instead of one:
```
<pre class="highlight  language-css">
  <code class="  language-css">
     some code
  </code>
</pre>
```

It is a minor, mostly cosmetic issue, but it would be nice if PrismJS did the right thing and introduced the leading white space only if there is something in the class line already (and definitely use one space in that case :) )

**Comment by RunDevelopment** [comment]
As you said, it's cosmetic. And if it ain't broken, why fix it?

That being said, if we wanted to fix it, we'd also have to go through all plugins because some of them also have this problem. And instead of throwing in a few `.trim()`s to solve this, we should take the chance to switch to [`classList`](https://github.com/PrismJS/prism/issues/1815).

**Comment by galaxy4public** [comment]
Well, I am of an opinion that "if you do it, do it right" :).  Perhaps, I am in the minority who strives to create beautiful code I am proud to share.  There so many people who just trying to Get Stuff Done, and as the result we are getting Stuffy software all around us: software on our phones, at work, etc.

Anyway, it is your call, but I thought one of PrismJS'es highlights was `Prism does its best to encourage good authoring practices.`, so I would expect it would be a bit tidier with DOM :).

P.S. Re: plugins -- I think they are called plugins exactly to be separate from the core.  The core on the other hand should be stricter on conventions.  This was not a call to fix all the plugins, btw, just to fix the core.  Since if I don't like the quality of the plugin I will either replace it or rewrite it, I can't do this same with the core :)  Well, it is possible, but what would be the point?

**Comment by LeaVerou** [comment]
Switching to classList is probably a good idea regardless.

That said, I'm finding the implication behind this quite rude:

> There so many people who just trying to Get Stuff Done, and as the result we are getting Stuffy software all around us: software on our phones, at work, etc.

>  Prism does its best to encourage good authoring practices., so I would expect it would be a bit tidier with DOM :).

Could you cite any respectable source that mentions avoiding leading spaces in class names as a guideline for good authoring practices?

**Comment by RunDevelopment** [comment]
I can see where the perceived untidiness is coming from but it's something that really doesn't matter if it's just one or two spaces more. So I don't think that this could even be considered bad practice because bad practices have to have some kind of negative consequences.

**Comment by mAAdhaTTah** [comment]
We can switch to `classList` if we like, as it is available in IE11. I wouldn't engage in a refactor from `className` -> `classList` just because of the leading space though.

**Comment by galaxy4public** [comment]
@LeaVerou, I am not sure why you decided to take it personally and be offended, it was not the intent of that comment to offend you.  Moreover, you quoted two separate paragraphs - one that was for a generalisation of the current trend in software development (pushed by the business to be "more agile" all the time) and the other is a conversational "want" to have the behaviour of PrismJS to be a bit more tidy in respect to how it works with DOM.

I think this discussion takes much more time than the benefits of fixing or not fixing this -- let's close it as an non issue, perhaps?

**Comment by RunDevelopment** [comment]
> let's close it as a non issue, perhaps?

Sounds good. I'll close this for now.

However, going forward we should keep in mind to use `classList` wherever possible.

**Comment by xjArea** [comment]
@RunDevelopment 

Hi RunDevelopment.

Sometimes, I need to confirm whether the code has been constructed by PrismJS. The method I currently use is to determine whether there are two spaces in the class attribute. I also think the two spaces are weird, but it seems to be the only condition that allows me to achieve this judgment in this scenario, but I also think this is very bad. If the problem of two spaces is fixed in the future, Then this kind of judgment will useless. So, are there any other methods that can help us make judgments?

I searched, but I didn’t find any useful information. I have read the source of the PrismJS plugin, I can make a plugin by myself to judge whether it has been constructed by PrismJS, but I still feel like asking first It will be better.

My English is bad, hope the strange grammar will not confuse you, Sorry and 🌹.

**Comment by RunDevelopment** [comment]
@xjArea You mean, you want to detect whether a code block has been highlighted by Prism, right? Interesting problem.

As you said, it's possible with a plugin but otherwise... I don't think there's anything you could reliably use.

<details>
<summary>Plugin</summary>

```js
Prism.hooks.add('complete', function () {
    // This will add the class to all <code> elements highlighted by Prism
    env.element.classList.add('highlighted');
});
```

</details>

**Comment by xjArea** [comment]
@RunDevelopment 

Oh, thank you very much for your quick reply.
In fact, I was already writing, but I made a mistake in a parameter, so it did not take effect. See your code, I corrected the first parameter of the function, and it was able to run. On this basis, I tried to add the class on the `<pre>`(if it exists), and done.

👏👏👏 😀

```js
Prism.hooks.add('complete', function(env){
	
    function addClass(node){ node.classList.add('prism-highlighted') };
    var parentNode = env.element.parentNode;
	
    if(parentNode && parentNode.nodeName.toLowerCase() === 'pre'){ addClass(parentNode) }
    else{ addClass(env.element) };
	
});
```
