### ISSUE TITLE
set is not a JavaScript keyword

### ISSUE THREAD

**Issue by madx** [PrismJS/prism#2386]
**Information**
- Language: JavaScript
- Plugins: none

**Description**
The JavaScript highlighter incorrectly highlights `set` as a keyword but as per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords it isn't one. This causes weird highlighting when writing such code:

![Syntax highlighting fail example](http://drop.yapok.org/2020-05-16T11:13:09.png)

**Code snippet**

<details>
<summary>The code being highlighted incorrectly.</summary>

```
func(x, y)
set(x, y)
```

</details>

**Comment by madx** [comment]
Note: this is also valid for `get` and I believe this is done to make get and set appear differently when writing ES6 classes getters/setters but it is annoying outside of this context

**Comment by RunDevelopment** [comment]
Prism can't really determine the context of a keyword, so it doesn't know that `get`/`set` is only a keyword inside class declarations. This will be tricky but I'll see what I can do.

**Comment by madx** [comment]
Yeah that's what I figured too, maybe it can check wether the next thing is whitespace followed by an open parenthesis or something else?
