### ISSUE TITLE
shebangs in shell/bash aren't considered as comments

### ISSUE THREAD

**Issue by kud** [PrismJS/prism#2388]
**Information**
- Language: shell/bash
- Plugins: none

**Description**
shebang isn't seen as a comment here.

- prism:

![image](https://user-images.githubusercontent.com/655838/82119699-fe85a180-9780-11ea-8f6d-1f34e4cff848.png)

- sublime text:

![image](https://user-images.githubusercontent.com/655838/82119715-165d2580-9781-11ea-9d99-9deed4a083f6.png)

**Code snippet**

<details>
<summary>#! /usr/bin/env zsh</summary>

```
#! /usr/bin/env zsh

# ex: git contrib git@github.com:gajus/create-index.git

gh repo fork $1 --clone
```
</details>

**Comment by RunDevelopment** [comment]
Bash tokenizes this as `shebang`.

![image](https://user-images.githubusercontent.com/20878432/82161761-bad58980-989f-11ea-8c75-bd0639c122df.png)
![image](https://user-images.githubusercontent.com/20878432/82161764-c45ef180-989f-11ea-9716-2484f84dbca3.png)

---

However, the theme you use doesn't seem to do anything. The `variable` and `important` tokens should be highlighted by every theme, so doesn't the theme you're using do anything?

**Comment by kud** [comment]
Oh! interesting! Thanks @RunDevelopment 

I'm using `import theme from "prism-react-renderer/themes/oceanicNext"`

**Comment by kud** [comment]
You're right. I fixed it by doing:

`    theme.styles[2].types.push("shebang")`

**Comment by kud** [comment]
https://github.com/FormidableLabs/prism-react-renderer/pull/81
