### ISSUE TITLE
Support multiline GraphQL descriptions

### ISSUE THREAD

**Issue by AlexMabry** [PrismJS/prism#2405]
**Information:**
- Prism version: latest from the download page
- Plugins: none
- Environment: Browser

**Description**
GraphQL descriptions, specifically multi-line, as described in [section 3.3 of the GraphQL spec](https://spec.graphql.org/June2018/#sec-Descriptions) are not highlighted correctly.

Also, since the spec calls out that descriptions can be formatted in CommonMark, would it make sense to format the description contents as markdown?

**Example**
https://jsfiddle.net/AlexMabry/5swkjcob/7/

**Comment by RunDevelopment** [comment]
Fixed by #2406.
