### ISSUE TITLE
Does Prism offers the possibility to add a proprietary language or create a custom tokenizer ?

### ISSUE THREAD

**Issue by condrove10** [PrismJS/prism#2424]
Hello everyone, while I was searching for a code editor library to use for my website I found many libraries which makes use of Prism, what I later found out was that many of these support the languages supported by Prism.

So at this point what I had to do is creating a custom tokenizer of this private language and connect it to Prism ( and its css/themes).

All sounds easy and great in my mind, but I'd like to know if such a feature could be implemented and if it's possible I'd like to know how to connect the css and manage it?

Edit#: I'm asking this question mainly because I've seen devs creating and improving official programming languages, like C#,C++,JS,etc... And I was wandering if its possible with custom languages?

Thank you for your time.

**Comment by RunDevelopment** [comment]
It depends.

Prism is designed to be modular, adding new languages is possible. [This guide](https://prismjs.com/extending.html#creating-a-new-language-definition) will tell you how to do it (you can ignore the "add some tests" and "add an example" parts).

After that is done, you start a local server and use your local version of Prism's download page to make a custom build with your language. (Prism will treat your custom language like any other.)

If you (or the library you're using) imports Prism via npm, it's more tricky. 
You could fork this repo, add your language to the fork, and then explicitly tell npm to use your fork's version of Prism. (I _think_ that's possible, but I'm not sure.)

---

Languages themselves don't have any CSS, they just use classes defined by a specific theme, so I don't know what you mean by "its css" but you can change the themes themselves of course.

**Comment by condrove10** [comment]
Thank you so much for all the help. I'm starting right away!
