### ISSUE TITLE
Line numbers on incorrect position

### ISSUE THREAD

**Issue by ArkadiuszNET** [PrismJS/prism#2429]
**Information:**
- Prism version: 1.20
- Plugins: Line Numbers
- Environment: bundling in asp.net mvc5

**Description**
Line numbers are on wrong position. The example right below:
![image](https://user-images.githubusercontent.com/28837469/85338680-086a9500-b4e3-11ea-86eb-facd39379be0.png)

And my usage in code:
![image](https://user-images.githubusercontent.com/28837469/85339034-9fcfe800-b4e3-11ea-9bb2-c80e27ce79fd.png)

In DOM tree, I don't see any element with class ".line-numbers-rows" and probably that missed thing cause error.
![image](https://user-images.githubusercontent.com/28837469/85339441-6d72ba80-b4e4-11ea-8673-85ab95a5a643.png)

After attempts to apply that manualy, produced results was totally strange.
I only downloaded script and css files and added them to my bundles.

It looks proper one when I changed position from relative to absolute, but still isn't close to perfect:
`pre[class*="language-"].line-numbers > code {
	position: absolute;
    /*position: relative;*/
	white-space: inherit;
}`

![image](https://user-images.githubusercontent.com/28837469/85340117-ce4ec280-b4e5-11ea-8c5b-d660ce39b174.png)

**Comment by RunDevelopment** [comment]
That's because of the indentation of the `<code>` block. Make it `<pre class="line-numebrs"><code class="language-css">@Model.Code</code></pre>` and it should work.

Keep in mind that the actual text box is the `pre` element. Those spaces/tabs used to indent the `<code>` element will be visible on your web page.
