### ISSUE TITLE
#pragma #define not keywords (C++) and dspic reserved registers

### ISSUE THREAD

**Issue by blotfi** [PrismJS/prism#2439]
**Language**
C++ for dspic Microchip microcontrollers

**Additional resources**
I would like to add reserved registers names to be displayed with a special colors
Can I put a .json containing these reserved registers (example _LATB15, _LATB12, _PLLPRE, _PLLPOST... which are in a .h file) to be displayed in another color
we can have C++ instruction like:
``` 
       #ifndef __SIMUL_ISIS
        while (OSCCONbits.COSC != 0b011); // Wait for Clock switch to occur
        while (OSCCONbits.LOCK != 1); // Wait for PLL to lock, only if PLL is needed
       #endif
``` 
**compilation directives (#ifndef #endif) should be in a color, its text in another color**
while is a keyword
OSCCONbits.COSC is register reserved keyword

I tried "Highlight Keywords" plugin but #xxxx is not recognised as keyword

**Comment by blotfi** [comment]
```
.token.directive, .token.property {
	color: #F1FA8C;
}

```
but I need to let the property be evaluated as an expression
exactly like **jetbrains CLion** treats its C files

**Comment by RunDevelopment** [comment]
Ok. Basically, you want 2 things:

First. You need to highlight some global constants/variables.

The easiest way to achieve this is by modifying the C++ language definition. Run the following code after you loaded Prism and before you do any highlighting (e.g. by appending it your `prism.js` file form the download page).

```js
Prism.languages.insertBefore('cpp', 'constant', {
    'dspic-register': /\b(?:_LATB15|_LATB12|...)\b/
});
```

The above will highlight all your registers with the `dspic-register` class.

Secondly:

>  I need to let the property be evaluated as an expression exactly like jetbrains CLion treats its C files

What do you mean by "be evaluated", we only do highlighting? 
And how does jetbrains CLion treat C files (I never used the IDE)?

**Comment by RunDevelopment** [comment]
> compilation directives (#ifndef #endif) should be in a color, its text in another color

What do you mean by that? Aren't they already?
![image](https://user-images.githubusercontent.com/20878432/85959727-61807000-b99e-11ea-8ee4-e1308bb60d0a.png)

**Comment by blotfi** [comment]
> > compilation directives (#ifndef #endif) should be in a color, its text in another color
> 
> What do you mean by that? Aren't they already?
> ![image](https://user-images.githubusercontent.com/20878432/85959727-61807000-b99e-11ea-8ee4-e1308bb60d0a.png)

#ifdef in one color
foo in another 
like
.token.property {
	color: #a9b7c6;
}
but here # is not the same color as ifdef whereas in C editors it is:
also some directive, like #pragma have expression like  

    #pragma config BWRP = WRPROTECT_OFF
or

    #define MILLISEC FCY/20000

so the expression should be evalutaed (20000 as number in blue..)

**Comment by blotfi** [comment]
> The above will highlight all your registers with the `dspic-register` class.
> 
> Secondly:
> 
> > I need to let the property be evaluated as an expression exactly like jetbrains CLion treats its C files
> 
> What do you mean by "be evaluated", we only do highlighting?
yes sorry I mean syntax highlighting but as expression (numbers)
> And how does jetbrains CLion treat C files (I never used the IDE)?

see the pdf file here
[cmde_c.pdf](https://github.com/PrismJS/prism/files/4843091/cmde_c.pdf)

**Comment by blotfi** [comment]
> dspic-register

```
    Prism.languages.insertBefore('cpp', 'constant', {
        'dspic-register': /\b(?:_PLLPOST|_LATB15)\b/
    });
    Prism.languages.insertBefore('c', 'constant', {
        'dspic-register': /\b(?:_PLLPOST|_LATB15)\b/
    });

```

this works but not every where for example in the #define property it is not highlighted (see my previous post)

**Comment by RunDevelopment** [comment]
I see. So for directives, we need 2 changes: We need to include the `#`, so it's highlighted as part of the directive's name, and we have to highlight preprocessor expressions. Is that correct?

**Comment by RunDevelopment** [comment]
With #2440, macro expressions are now highlighted.

![image](https://user-images.githubusercontent.com/20878432/85961096-4e729d80-b9a8-11ea-8770-9a7315a661d8.png)

(This will also highlight your registers in macros accordingly.)
(The `#` of directives isn't highlighted by default to preserve the old look, but it's tokenized now, so you can add a CSS rule to give it a different color.) 

After #2440, you should be able to style your C++ code similar to your screenshots (they were very helpful btw!). 

If you want 100% accuracy: With [Custom class](https://prismjs.com/plugins/custom-class/), you can add additional classes to tokens, so you could add a special class just for semicolons:

```js
Prism.plugins.customClass.add(({content, type, language}) => {
	if (content === ';' && type === 'punctuation' && language === 'cpp') {
		return 'semicolon';
	}
});
```

---

It might take some time for #2440 to get merged, so you might want to branch it.

**Comment by blotfi** [comment]
> I see. So for directives, we need 2 changes: We need to include the `#`, so it's highlighted as part of the directive's name, and we have to highlight preprocessor expressions. Is that correct?

yes, that's correct
Can I do it by myself using a .js executed after prismjs load?
or do I have to modify the src version directly

thanks

**Comment by RunDevelopment** [comment]
> Can I do it by myself using a .js executed after prismjs load? 
> or do I have to modify the src version directly

Both will work.

```html
<script src="prism.js"></script>
<script>/* The insertBefore calls */</script> 
```

or

```js
/* PrismJS 1.20.0
https://prismjs.com/download.html#... */
...
/* The insertBefore calls */
```

**Comment by RunDevelopment** [comment]
The issue [seems to have been resolved](https://github.com/PrismJS/prism/pull/2440#issuecomment-651060124) but I forgot to close it.
