### ISSUE TITLE
comments abnormally underlined in Zendesk Guide

### ISSUE THREAD

**Issue by landret** [PrismJS/prism#2452]
**Information**
- Language: C, C++, Arduino, java
- Plugins: none
- latest version of Prism
- usage : in Zendesk Guide articles

**Description**
Hi guys, I integrated Prism.js in Zendesk Guide yesterday (latest version, didn't try with previous version) for highlighting code in Help Center articles. Problem : comments are systematically underlined with a line being drawn at the next code line. Zendesk Support thinks this is a problem with Prism.js

**Code snippet**

<details>
<summary>simple code snippet for Arduino</summary>

```
#include <myLib.h>


// comments for the setup function
void setup()
{
    // initialize library
    init(); 
}


// loop function
void loop()
{
    // do something
    doSomething(); 
}
```

</details>

![code in article](https://user-images.githubusercontent.com/19358486/86398760-d58e7280-bc41-11ea-9a39-eadba369d2fa.png)

**Comment by RunDevelopment** [comment]
This isn't a problem with Prism (after all, it works fine on the [test page](https://prismjs.com/test.html#language=cpp)).

It seems like some other styles sheets on Zendesk interfere with the Coy theme. 

You said you integrated Prism? (I'll assume that you have the ability to add new CSS rules.) In that case, you can look at the CSS rules that apply to comments on Zendesk and the rules that apply to comments on our [test page](https://prismjs.com/test.html#language=cpp). The difference between the two will tell which rule(s) cause(s) the underlining. Then all you have to do is to `!important`-override it.

Unfortunately, I can't help you any further without a reproducible example.

**Comment by landret** [comment]
Indeed, the problem comes from Zendesk.
Many thanks for your help.
