### ISSUE TITLE
Prisms adds white line through the code in php syntax

### ISSUE THREAD

**Issue by sfkazmi** [PrismJS/prism#2453]
***Prisms Adds line through the code and highlight feature does not highlight full line in PHP***

**Description**
Hi, I am using Prism Js to display PHP code and I am facing a strange issue,

 I am using the following plugins 

***Line Highlight***
***Line Number***
***Copy to Clipboard Button***

and the following language supports

***Markup***
***C-LIKE***
***CSS***
***Javascript***
***PHP***
***PHP Doc***
***PHP extra***

**Code snippet**

<details>
<summary>The code being highlighted incorrectly.</summary>

```
<div class="line-numbers">
        <pre>
               <code class="language-php" >
                     Route::get('/', function () {
                              \Illuminate\Support\Facades\Auth::abs();
                               return view('welcome');
                      });
              </code>
       </pre>
 </div>
```

</details>

Here is the [Link](https://ibb.co/K2Bbwn1) how it displays.

**Comment by mAAdhaTTah** [comment]
The code snippet you shared has a bunch of extra whitespace that should be removed. The extra tabs and line between between the `pre` `code & the snippet itself could be causing some of these issues. Additionally, instead of a `div` with a `line-numbers` class, the `pre` should have that class.

Lastly, if none of the above fixes the issue, could you share a reproducible example rather than just a screenshot? It'll make it easier for us to debug the issue.

**Comment by RunDevelopment** [comment]
Also, I do want to point out that the text in the screenshot is not the text you gave in the issue. (Prism doesn't change the text content of an element.)

As already pointed out, a reproducible example (be it a [JSFiddle](https://jsfiddle.net/), the zip of an example project, or the project itself) would help.

> Additionally, instead of a div with a line-numbers class, the pre should have that class.

No, that's fine. While a little strange, the `pre` will "inherit" the `line-numbers` class of the `div`.

**Comment by sfkazmi** [comment]
I have tested it all the way and found out the issue. The issue is with my CSS file. I have a class with the name comment and a custom CSS for that class section. I have figured out that when any code contains comment prisms add comment class to it and my custom CSS was applied to that. Although it is not an issue with prisms js. Thanks for your support and quick answers.

**Comment by sfkazmi** [comment]
The issue was with my custom CSS file. I have defined a class in and added some custom style, latter I figured out that prisms uses same class name. ***comment*** for adding styles.
