### ISSUE TITLE
Class to disable Line Numbers on specific element

### ISSUE THREAD

**Issue by erichlotto** [PrismJS/prism#2454]
I've been using the Line Numbers plugin attached to my `<body>` as suggested in the documentation so I don't need to place this class into every single code block on my website, but recently I've needed to use the Command Line plugin and this is the output I have:

![image](https://user-images.githubusercontent.com/5035883/86485624-93435f00-bd2f-11ea-802c-553eff63f10a.png)

An option to disable the line-number plugin on a specific element would be nice.

Thanks

**Comment by erichlotto** [comment]
Update: I'm currently using `.hide-line-numbers .line-numbers-rows { display: none; }` as a workaround, if someone is having this issue. Just place `hide-line-numbers` in your `<pre>` element.

**Comment by RunDevelopment** [comment]
We actually added a solution for this issue just a week ago with #2434.

You can disable Line numbers for any code element by adding a `no-line-numbers` class that is closer than the closest `line-numbers` class.
The `line-numbers` or `no-line-numbers` class will enable or disable the plugin for the whole subtree.

I'll quickly make a PR that updates the documentation.

**Comment by RunDevelopment** [comment]
Note: This feature is currently only available from the [download page](https://prismjs.com/download.html). If you're getting Prism from npm or any CDN, you'll have to wait until the next version.

**Comment by erichlotto** [comment]
That's awesome! I already had the latest version but was unaware of this feature.
Everything works fine now, thank you very much :)
