### ISSUE TITLE
Leading whitespaces shouldn’t be relevant in EditorConfig

### ISSUE THREAD

**Issue by edukisto** [PrismJS/prism#2472]
**Information**

- Language: EditorConfig
- Plugins: none

**Does the problem still occur in the latest version of Prism?**

[Yes](https://prismjs.com/test.html#language=editorconfig).

**Description**

Contrary to the [specification](https://editorconfig-specification.readthedocs.io/en/latest/#file-format), all leading whitespaces on each line are not considered irrelevant.

**Code snippet**

<details>

<summary>The code being highlighted incorrectly.</summary>

Prism renders

```editor-config
    [Section1]
    key1=value1
```

in this way

```html
<span class="token section keyword">    <span class="token punctuation">[</span>Section1<span class="token punctuation">]</span></span>
<span class="token property">    key1</span><span class="token value string"><span class="token punctuation">=</span>value1</span>
```

</details>

**Comment by RunDevelopment** [comment]
You just want the leading whitespaces trimmed, right?

**Comment by edukisto** [comment]
Right. I’m going to make a pull request.

**Comment by osipxd** [comment]
@edukisto, can you check that it works right now?
