### ISSUE TITLE
Inconcistent layout WP twenty twent

### ISSUE THREAD

**Issue by technbuzz** [PrismJS/prism#2480]
**Information:**
- Prism version: [ latest from the download page]
- Plugins: [line highlight, line numbers]
- Environment: [Mobile Browser]

**Description**
Everything worked well before since I switched to wordpress twenty twenty theme. Things are breaking. On desktop things are okay but on mobile I am getting the data-line are placed wrong. Even on desktop I'm am getting wrongs tabs.

![Screenshot_2020-07-20-16-51-45-674_com android chrome](https://user-images.githubusercontent.com/1523391/87940472-b483a980-caaa-11ea-88f4-49de3e4d23f4.jpg)

**Example**
To reproduce the bug I can only point out to [my blog link](https://www.technbuzz.com/2020/06/28/add-leaflet-markers-popup-and-circle/)

**Comment by RunDevelopment** [comment]
That's because the `code` element is indented. It has to be `<pre ...><code ...>` without any spaces or line breaks in between.

![Screenshot from 2020-07-20 15-27-43](https://user-images.githubusercontent.com/20878432/87942937-9f544e00-ca9d-11ea-8db8-cb2d0ec5c465.png)
