### ISSUE TITLE
Wrong code in PrismJS website

### ISSUE THREAD

**Issue by sksar** [PrismJS/prism#2487]
On the PrismJS website, this page: [https://prismjs.com/plugins/line-numbers/](https://prismjs.com/plugins/line-numbers/)
has the code:
```
<body class="line-number"> <!-- enabled for the whole page -->
	<!-- with line numbers -->
	<pre><code>...</code></pre>
	<!-- disabled for a specific element - without line numbers -->
	<pre class="no-line-numbers"><code>...</code></pre>
	<div class="no-line-numbers"> <!-- disabled for this subtree -->
		<!-- without line numbers -->
		<pre><code>...</code></pre>
		<!-- enabled for a specific element - with line numbers -->
		<pre class="line-number"><code>...</code></pre>
	</div>
</body>
```
The part where it says `<pre class="line-number">` I believe it's wrong because it did not work for me.
When I changed it to `<pre class="line-numbers">` it did work.
So I think maybe the code on the website is wrong, or am I missing something here?

[PrismJs Version 1.20.0]

**Comment by RunDevelopment** [comment]
Thanks for reporting @sksar!
