### ISSUE TITLE
Please add No line break 

### ISSUE THREAD

**Issue by dirkhe1051931999** [PrismJS/prism#2488]
**Motivation**
Please explain the problem you're having/why you propose this feature. Ex. I'm always frustrated when [...]

**Description**

**Alternatives**
A clear and concise description of any alternative solutions or features you've considered, if applicable.

**Comment by RunDevelopment** [comment]
@dirkhe1051931999 I have no idea what "No line break" is supposed to be. Please edit your comment to fill out the issue template and then reopen the issue. A description is the minimum required for us to understand your issue.
