### ISSUE TITLE
Not working with AMP

### ISSUE THREAD

**Issue by SM-Fahim** [PrismJS/prism#2511]
**Information:**
- Prism version: latest from the download page
- Plugins: [AMP, Custom Sidebar, Wordfence Security, WP Rocket, Yoast SEO Premium]
- Environment: [Linux PC, Android Phone, Chrome Browser]

**Description**
I just installed the AMP plugin by Google on WordPress, and the highlighting stopped working in the amp site. The non-amp site working properly, but not the amp site. 

**Example**
Non-amp site where it's working: [Comments in Python - All possible ways](https://www.machinelearningwiki.com/python/comments-in-python-all-possible-ways/)
Amp site where it's not working, although the same site: [Comments in Python - All possible ways](https://www.machinelearningwiki.com/python/comments-in-python-all-possible-ways/amp)

**Comment by RunDevelopment** [comment]
Your AMP page doesn't load Prism at all, so no highlighting. That's not an issue with Prism but with the AMP plugin or its configuration.

You check whether Prism is loaded by trying to get the global `Prism` variable in your browser's dev console.
