### ISSUE TITLE
HTML entities not escaped correctly when highlighting HTML code.

### ISSUE THREAD

**Issue by SukkaW** [PrismJS/prism#2516]
**Information:**
- Prism version: latest from npm (1.21.0)
- Plugins: none
- Environment: Node.js

**Description**

See example below.

**Example**

```js
const Prism = require("prismjs");
const prismLoadLanguages = require('prismjs/components/');
prismLoadLanguages('html');

const str = `<!DOCTYPE html>
<body>
  <!-- here goes the rest of the page -->
</body>`;

console.log(Prism.highlight(str, Prism.languages['html'], 'html'));
```

(https://runkit.com/sukkaw/5f326d2b5c0c00001aed2d5d)

The code above will output:

```
<span class="token doctype"><span class="token punctuation">&lt;!</span><span class="token doctype-tag">DOCTYPE</span> <span class="token name">html</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>body</span><span class="token punctuation">></span></span>
  <span class="token comment">&lt;!-- here goes the rest of the page --></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>body</span><span class="token punctuation">></span></span>
```

As you can see, `<!-- here goes the rest of the page -->` become `&lt;!-- here goes the rest of the page -->` in which `-->` is not escaped correctly.

If I serve the output directly in HTML it would be fine, but it will corrupt `marked.js`.

Related code: https://github.com/PrismJS/prism/blob/388ad996c4b576205de4d4feda69202bd26c1345/prism.js#L72

**Comment by RunDevelopment** [comment]
What's the problem here? It's not necessary to escape `-->`, so we don't do it. The output is valid HTML.

I don't know what `marked.js` is but if the library can't handle valid HTML, then it has to be fixed on their end.

**Comment by SukkaW** [comment]
@RunDevelopment Yeah, you are right. With only `<` is escaped the output **is** indeed valid html. However, it is not only safer to escape both `<` & `>`, but also it will be more robust and be compatible with some bad html parser (as I mentioned, the `marked.js`)

**Comment by RunDevelopment** [comment]
I don't think Prism should have to worry about being compatible with parsers don't comply with the HTML specification.
To be fair: If the parser doesn't comply with the latest version of HTML, then fine. But this feature has been part of HTML since at least version 4.01.

Regarding safety: Not escaping `>` is a non-issue since we escape all `<` characters.

Again, this is something `marked.js` has to fix.

---

However, if you need it working right now, you can use this hack to fix it. You correctly pointed out the util method for encoding token streams. We can just replace that method like this:

```js
const Prism = require("prismjs");

Prism.util.encode = function encode(tokens) {
	if (tokens instanceof Prism.Token) {
		return new Prism.Token(tokens.type, encode(tokens.content), tokens.alias);
	} else if (Array.isArray(tokens)) {
		return tokens.map(encode);
	} else {
		return tokens.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\u00a0/g, ' ');
	}
}
```

Be sure to fix your Prism version. All util functions are for internal use only, so overwriting it like this is very much unstable and may break in the next version.

**Comment by SukkaW** [comment]
> Regarding safety: Not escaping `>` is a non-issue since we escape all `<` characters.

When I said robust, I mean the prismjs should be able to handle any edge cases:

```html
<!--

<pre><code>

<span class="token doctype"><span class="token punctuation">&lt;!</span><span class="token doctype-tag">DOCTYPE</span> <span class="token name">html</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>body</span><span class="token punctuation">></span></span>
  <span class="token comment">&lt;!-- here goes the rest of the page --></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>body</span><span class="token punctuation">></span></span>

</code></pre>
-->
```

Here I first wrap the [html snippet](https://github.com/PrismJS/prism/issues/2516#issue-676748143) into `<pre><code>`, then wrap the whole `<pre>` inside html comment. Guess what will happen?

**Comment by RunDevelopment** [comment]
If arbitrary HTML code is wrapped into an HTML comment, text containing the `-->` sequence won't be the only thing you have to worry about. Attribute values may also contain the string (e.g. `<foo bar="-->"/>`), as can the tag name (e.g. `<foo--></foo-->`) and attribute names (e.g. `<foo data--></foo>`). You actually have to escape all `>` characters to guarantee correctness in that case.

I also want to point out that Prism's generated HTML is not guaranteed to not contain HTML comments. 

Should I add it to [the documentation](https://prismjs.com/docs/Prism.html#.highlight) that we only guarantee to produce valid HTML and nothing more?

**Comment by SukkaW** [comment]
> If arbitrary HTML code is wrapped into an HTML comment, text containing the `-->` sequence won't be the only thing you have to worry about. Attribute values may also contain the string (e.g. `<foo bar="-->"/>`), as can the tag name (e.g. `<foo--></foo-->`) and attribute names (e.g. `<foo data--></foo>`). You actually have to escape all `>` characters to guarantee correctness in that case.

I don't need to worry them at all If prism has `>` escaping inside `util.encode`, as I said.

**Comment by RunDevelopment** [comment]
`util.encode` only affects text. Attribute names/values, tag names, and comments are not affected.

[This](https://github.com/PrismJS/prism/blob/bf115f479947619f806e5cf7c5e31038ed6eb948/components/prism-core.js#L819) is the method that actually generates the HTML. It [takes an already encoded token stream](https://github.com/PrismJS/prism/blob/bf115f479947619f806e5cf7c5e31038ed6eb948/components/prism-core.js#L606) (this means that all text in the token stream is escaped) which is why `util.encode` cannot affect attributes and so on.
(Admittedly, this is bad design which is why we have #1844 but #1844 also won't change the escaping behavior.)

**Comment by RunDevelopment** [comment]
Also, when I said "You actually have to escape all `>` characters", I really meant __all__ `>` characters. Even the ones used to close tags (see attribute and tag name examples).

**Comment by joshgoebel** [comment]
@RunDevelopment 

```
.replace(/\u00a0/g, ' ')
```

Is this purely a visual affordance changing them to potential breaking vs non-breaking (vs security issue)?

**Comment by joshgoebel** [comment]
If the existing behavior is indeed "as intended" can this not be closed as `wont fix` or "behaving an intended" then?

**Comment by RunDevelopment** [comment]
I honestly have no idea why we have `.replace(/\u00a0/g, ' ')`. It's been there since before I even heard of Prism.

> If the existing behavior is indeed "as intended" can this not be closed as wont fix or "behaving an intended" then?

You're right, I forgot.

For the record: It is working as intended.
