### ISSUE TITLE
Support for React

### ISSUE THREAD

**Issue by vjeux** [PrismJS/prism#252]
Hey, thanks for this project!

I've stripped out all the DOM dependencies and made a React component for prism: https://github.com/vjeux/prism-react

I don't plan to integrate it back into the core project, but if you are interested the code is available :)

**Comment by loganfranken** [comment]
This is awesome, @vjeux!

Since there are no plans to integrate this back into the core project, I think we can close this issue.

(Unless you wanted to open a PR for your hard work, @vjeux? :wink:)

**Comment by catamphetamine** [comment]
My variant of a React wrapper:

```js
function Highlight({ lang, children }) {
  return (
    <pre className={`language-${lang}`}>
      <code dangerouslySetInnerHTML={{__html: Prism.highlight(children.trim(), Prism.languages.jsx, 'jsx')}}/>
    </pre>
  )
}
```

```js
<Highlight lang="js">{`
<PageAndMenu>
  <CollapsibleMenu>
    <div>Item 1</div>
    <div>Item 2</div>
  </CollapsibleMenu>
  <Page>
    <MenuButton />
    Page content
  </Page>
</PageAndMenu>
`}</Highlight>
```
