### ISSUE TITLE
Symbols with hex escapes in Scheme

### ISSUE THREAD

**Issue by jcubic** [PrismJS/prism#2521]
**Information**
- Language: Scheme
- Plugins: none

**Description**
R7RS symbols with escapes are handled as comments inside. they should be mark as symbols.

**Code snippet**

<details>
<summary>The code being highlighted incorrectly.</summary>

```
|\x9;\x9;|
```

</details>

Hex escapes `\x9;` can only appear in strings and symbols that use vertical bars `|name|`.

**Comment by RunDevelopment** [comment]
[R7RS](https://small.r7rs.org/attachment/r7rs.pdf) has a few more things that need to be supported starting with nested comments (`#| comment #| nested comment |# comment |#`).

What is the relation between Scheme and R7RS? Is R7RS a superset of Scheme?

**Comment by jcubic** [comment]
R7RS is latest standard of scheme there are few scheme implementations that support it like and Gauche. If you have Scheme language you should support R7RS.

There is also `#;(foo bar)` that is inline comment.

**Comment by RunDevelopment** [comment]
That's good to know.

In that case, we should probably make your Scheme grammar support all of R7RS.

**Comment by jcubic** [comment]
Awesome, good job @RunDevelopment
