### ISSUE TITLE
JavaScript parser is confused by a backtick in a string is wrong

### ISSUE THREAD

**Issue by shenqiuhui** [PrismJS/prism#2536]
`
function fn(name, age) {
    return `I'm ${name}, ${age} years old`;
}
`

**Comment by RunDevelopment** [comment]
Cannot reproduce. Are you using the latest version of Prism? See the [test page](https://prismjs.com/test.html#language=javascript).

(Also, code blocks are done like [this](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).)

**Comment by RunDevelopment** [comment]
Duplicate of #2540.

(#2540 has a better description, so I'm closing this issue.)
