### ISSUE TITLE
How to escape the angled brackets (“<”, “>”) in prism?

### ISSUE THREAD

**Issue by CodAffection** [PrismJS/prism#2543]
Writing my WordPress post including dart code in a `<pre class="language-dart"><code>` block, I found out that, the part in between angle brackets are not showing

```
  Contact.fromMap(Map<String, dynamic> map) {
    id = map[colId];
    name = map[colName];
    mobile = map[colMobile];
  }
```
It's not showing  `<String, dynamic>`. What am I doing wrong?

I have downloaded Prismjs with these settings:https://prismjs.com/download.html#themes=prism-okaidia&languages=markup+css+clike+javascript+aspnet+bash+csharp+dart+kotlin+python+jsx+sql&plugins=line-highlight+remove-initial-line-feed+unescaped-markup+normalize-whitespace+toolbar+copy-to-clipboard+match-braces.

**Comment by RunDevelopment** [comment]
In HTML, `<` and `&` have special meaning and have to be escaped when used in text (`<` -> `&lt;` and `&` -> `&amp;`).
(The reason you can usually use `<` and `&` unescaped in text anyway is that HTML will interpret invalid tags (`<`) and entities (`&`) as text. In your case, `<String, dynamic>` is a valid HTML tag with the tag name `String,` and the attribute `dynamic`.)

```html
<pre class="language-dart"><code>  Contact.fromMap(Map&lt;String, dynamic> map) {
    id = map[colId];
    name = map[colName];
    mobile = map[colMobile];
  }</code></pre>
```

Alternatively, you can use the [Unescaped Markup plugin](https://prismjs.com/plugins/unescaped-markup/#how-to-use) to do the escaping for you. 
(However, using the plugin means that your code cannot contain a substring `-->`.)

```html
<pre class="language-dart"><code><!--  Contact.fromMap(Map<String, dynamic> map) {
    id = map[colId];
    name = map[colName];
    mobile = map[colMobile];
  }--></code></pre>
```

**Comment by CodAffection** [comment]
@RunDevelopment  Still not working, replaced `<` with '&lt;'. I already have unescaped markup plugin.

**Comment by RunDevelopment** [comment]
Could you please link the blog in question or another reproducible example?

**Comment by CodAffection** [comment]
sure. https://www.codaffection.com/flutter-article/complete-sqlite-crud-operations-in-flutter/

**Comment by CodAffection** [comment]
other code block also has `<`, but there I'm enclosing whole code block with `<script type="text/plain" class="language-dart">`. But I'm not able to the code preview in live avada post editor, because wordpress code editor does not allow `<script>` tags

**Comment by CodAffection** [comment]
@RunDevelopment , This `<script>` approach is working fine (because it works in actual post), Is there anything we can do, to make it visible in live post editor.
 Since it works in actual published post, there should extra work from prism.js in actual post. can we explicitly call some functions from prism.js while editing the post ?

**Comment by RunDevelopment** [comment]
Thanks for the link.

From the source of the website, the problem is easy to see:
![image](https://user-images.githubusercontent.com/20878432/92388139-1362b800-f117-11ea-9373-dbc9997e297a.png)

As I said, `<String, dynamic>` is interpreted as a tag, so the `<` has to be escaped with `&lt;`. But that's something you or WordPress have to fix.

> can we explicitly call some functions from prism.js while editing the post ?

No idea how this work in WordPress but you can all [`Prism.highlightAll`](https://prismjs.com/docs/Prism.html#.highlightAll) to re-highlight the whole page or [`Prism.highlightElement(element)`](https://prismjs.com/docs/Prism.html#.highlightElement) to re-highlight a single element.
