### ISSUE TITLE
HTML Markup not working in mobile but works in PC

### ISSUE THREAD

**Issue by CodAffection** [PrismJS/prism#2551]
I 've added few stylesheet ref. inside head tag as below.

```
<script type="text/plain" class="language-html">
<head>
	...
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
...
</head>
</script>
```

It works in desktop not in mobile, 
you could check that here : https://www.codaffection.com/asp-net-core-article/angular-crud-with-asp-net-core-web-api/
2nd lash code block above the sub heading : 'How to Consume .Net Core API from Angular'.

link tags are not showing in mobile.

**Comment by RunDevelopment** [comment]
Cannot reproduce.

The website doesn't have any `link` tags in the code example.
![image](https://user-images.githubusercontent.com/20878432/93073062-9d180580-f682-11ea-8cdc-92a1dfbe290a.png)

And it generally works fine with `link` tags. See [this example project](https://github.com/PrismJS/prism/files/5217676/example.zip).

**Comment by CodAffection** [comment]
Thanks for your replay. 
It was due to a plugin in WordPress.
