### ISSUE TITLE
Line numbering does not sync with wrapped lines

### ISSUE THREAD

**Issue by mikejpoole** [PrismJS/prism#2552]
**Information:**
- Prism version: 1.21.0

**Description**
When `white-space: pre-wrap` is applied to the `pre[class*="language-"].line-numbers > code` selector so that long lines of code  wrap the line numbers get out of sync.

**Example**
I have created a complete Pen at https://codepen.io/mpoo/pen/RwayGBy?editors=1100 

Here is a screenshot where the line numbering is out of sync:

![prism screenshot](https://user-images.githubusercontent.com/9463686/93069323-71425300-f675-11ea-969c-335d8e907fb1.png)

**Comment by RunDevelopment** [comment]
The `white-space` property has to be applied to the `pre` element instead of the `code` element.

**Comment by mikejpoole** [comment]
Many thanks for that @RunDevelopment I will do that instead.
