### ISSUE TITLE
Is it possible to replace 'Copy' text in clipboard button with an icon.

### ISSUE THREAD

**Issue by CodAffection** [PrismJS/prism#2557]
Is it possible to replace 'Copy' text inside the toolbar button with an icon.

**Comment by mAAdhaTTah** [comment]
Currently, no, but that might be a useful enhancement, esp for i18n, so we'd be open to a PR. We could use data attributes for this pretty easily.

**Comment by RunDevelopment** [comment]
[The plugin](https://github.com/PrismJS/prism/blob/master/plugins/copy-to-clipboard/prism-copy-to-clipboard.js) has 3 states it has to display ("Copy", "Copied!", "Press Ctrl+C to copy"). The easiest might be to give the button a `data-` attribute with the current state and wrap the text into a `span` element, so you can just hide the text via a little CSS. How does that sound?

**Comment by DraftProducts** [comment]
Hi!
Sorry for commenting on a closed issue, (I can open another one if it's needed).
I'm not sure that the request of @CodAffection was resolved with this PR.
You can't add an icon with the current code-base of [copy-to-clipboard](https://github.com/PrismJS/prism/blob/master/plugins/copy-to-clipboard/prism-copy-to-clipboard.js).
You can't put an SVG or HTML element into the `textContent` of a `span`.

**Comment by RunDevelopment** [comment]
Hello @DraftProducts!

You can use an SVG and/or icon. You can either use the `background` property of the `span` or use an icon font and [set the copy text](https://prismjs.com/plugins/copy-to-clipboard/#settings). With a little CSS, this should be enough for most use cases.

**Comment by DraftProducts** [comment]
Hello!
Thank you for your quick reaction!
I thought it was a bit hacky but it should be enough 👍
Have a nice day!
