### ISSUE TITLE
WebPack and /prism/plugins/copy-to-clipboard/prism-copy-to-clipboard.js

### ISSUE THREAD

**Issue by sremiger1** [PrismJS/prism#2565]
Webpack is not able to compile\merge **prism-copy-to-clipboard.js** into a single file.
- Prism version: [e.g. 1.14, latest from the download page, etc.]
- Plugins: [prism-copy-to-clipboard.js]
- Environment: [Webpack]

Does the latest version of Prism from the [download page](https://prismjs.com/download.html) also have this issue? **Yes**
If you're using Prism with Node or Webpack, please also see the [usage section](https://prismjs.com/index.html#basic-usage). **Looked but did not solve**

**Description**
Running Webpack produces and error 
```
ERROR in ./wwwroot/lib/prism/plugins/copy-to-clipboard/prism-copy-to-clipboard.js
Module not found: Error: Can't resolve 'clipboard' in 'C:\ws\DocHost\wwwroot\lib\prism\plugins\copy-to-clipboard'
 @ ./wwwroot/lib/prism/plugins/copy-to-clipboard/prism-copy-to-clipboard.js 14:18-38
 @ ./wwwroot/scripts/vendor-index.js
```
**Example**
I used Visual Studio 2019 but I do not think it is a factor.
Attached [vendor-index .txt](https://github.com/PrismJS/prism/files/5269562/vendor-index.txt) is my vendor index file
Command line `webpack --watch --mode=development`

When I comment out line 15
`ClipboardJS = require('clipboard');`
Webpack works

**Comment by RunDevelopment** [comment]
The Copy to Clipboard plugin depends on the [clipboard library](https://www.npmjs.com/package/clipboard) and not [clipboard.js](https://www.npmjs.com/package/clipboard.js). Using the correct library will most likely fix your issue.
