### ISSUE TITLE
Highlight keywords; is it possible to highlight specific attributes in HTML or strings in JS?

### ISSUE THREAD

**Issue by jasonday** [PrismJS/prism#2568]
Specifically, I am attempting to highlight specific accessibility attributes in HTML and any corresponding selectors/strings in javascript. For example, `aria-expanded`, `aria-label="some value"`, `role="button"`, etc. 

Is there a way to define additional matches via javascript config?

**Comment by RunDevelopment** [comment]
There are few ways to do it.

If you just wanted to give existing tokens new aliases to enable special highlighting, then you can use the [Custom Class plugin](https://prismjs.com/plugins/custom-class/). I.e. to give all `aria-*` attributes a special class, you can use this snippet:

```js
Prism.plugins.customClass.add(({content, type, language}) => {
	if (/^aria-/i.test(content) && type === 'attr-name') {
		return 'aria-attribute'; // the special class
	}
});
```

If you need something more powerful (like giving the attribute value a special class depending on the attribute name), then you'll have to change the HTML language definition. The easiest way to do that is to do something similar to what CSS does for `style` attributes. Just include this snippet before highlighting anything:

```js
Prism.languages.insertBefore('inside', 'attr-value', {
	'special-attr': {
		pattern: /(^|["'\s])ATTR_NAME\s*=\s*(?:"[^"]*"|'[^']*')/i,
		lookbehind: true,
		inside: {
			'attr-value': {
				pattern: /=\s*(?:"[^"]*"|'[^']*'|[^\s'">=]+)/,
				inside: {
					'value': {
						pattern: /(["'])[\s\S]+(?=["']$)/,
						lookbehind: true,
						inside: {
							// highlighting for the attribute value
						}
					},
					'punctuation': [
						{
							pattern: /^=/,
							alias: 'attr-equals'
						},
						/"|'/
					]
				}
			},
			'attr-name': /^ATTR_NAME/i,
		}
	}
}, Prism.languages.markup.tag);
```

More complex, yes, but you have complete control of everything. Just keep in mind that whatever pattern you insert for `ATTR_NAME` has to only match valid HTML attribute names.
