### ISSUE TITLE
Open Policy Agent's rego

### ISSUE THREAD

**Issue by ralgozino** [PrismJS/prism#2571]
**Motivation**

We're using Prism in our opensource project [Gatekeeper Policy Agent](https://github.com/sighupio/gatekeeper-policy-manager) to show rego code snippets and yaml/json files. We are using as a workaround the "ruby" highlighter that is somewhat similar to rego, but sadly is not good enough.

**Language**
OPA is purpose built for reasoning about information represented in structured documents. The data that your service and its users publish can be inspected and transformed using OPA’s native query language Rego.

What is Rego?
Rego was inspired by Datalog, which is a well understood, decades old query language. Rego extends Datalog to support structured document models such as JSON.

Rego queries are assertions on data stored in OPA. These queries can be used to define policies that enumerate instances of data that violate the expected state of the system.

**Additional resources**

Official docs
https://www.openpolicyagent.org/docs/latest/policy-language/

There's also a VSCode plugin that adds syntax highlighting, can be useful as starting point:
https://github.com/open-policy-agent/vscode-opa/blob/master/syntaxes/Rego.tmLanguage

Let me know if you need anything else or how can I help to add support for this language 🙂 
Thank you!

**Comment by RunDevelopment** [comment]
Solved by #2624.

**Comment by ralgozino** [comment]
Thank you! <3
