### ISSUE TITLE
[language-jsx][Rendering Bugs] - Functional Components: New Lines, Prop Brackets/Objects, and Component Name Casing

### ISSUE THREAD

**Issue by cor-rine** [PrismJS/prism#2578]
**Information**
- Language: React JSX
- Plugins: React JSX language

Problem occurs on most recent download of Prism on October 10th, 2020

**Description**
React JSX does not render as expected

**Code snippet**
In my IDE (with `<pre><code>` blocks for context):
```
	<pre><code class="language-jsx">
ReactDOM.render(
  <Canvas
  	gl={{ antialias: true }}
  	camera={{ position: [100, 100, 20] }}>
  </Canvas>,
  document.getElementById('root')
);
	</code></pre>
```

Rendered in my presentation:
<img width="1326" alt="Screen Shot 2020-10-10 at 1 43 12 AM" src="https://user-images.githubusercontent.com/1207134/95650702-0af4f880-0a9a-11eb-845b-4372a8293332.png">

The following issues exist:
1. Expected the component to be highlighted as `<Canvas />` and not `<canvas />`
2. Expected the props to follow the line breaks as they are written in my IDE.
3. Expected prop objects `{{...}}` to render without additional/incorrectly added quotation marks.

<details>
<summary>
JSX does not render as expected.
</summary>
</details>

**Comment by mAAdhaTTah** [comment]
Can you provide a reproducible case so we can look into it? My initial reaction is you probably need to HTML escape the code snippet.

**Comment by RunDevelopment** [comment]
Honestly, my guess is that someone modified Prism to use `innerHTML` instead of `textContent` to extract the text of `code` elements. The lower-case tag name, the strange quotes everywhere, and the fact that the added quotes are exactly how a vanilla HTML parser would interpret the tag all bring me to this conclusion.

**Comment by cor-rine** [comment]
> Can you provide a reproducible case so we can look into it? My initial reaction is you probably need to HTML escape the code snippet.

I did include a code snippet above, but what you mentioned about HTML escaping helped me find the working solution!

It turns out that I needed to escape my JSX tags with `&lt;` and `&gt;` in order to view it correctly.

Thanks for the tip!
