### ISSUE TITLE
PureScript missing from components directory in node_modules

### ISSUE THREAD

**Issue by lane-c-wagner** [PrismJS/prism#2581]
**Information:**
- Prism version: 1.21.0
- Plugins: none
- Environment: Webpack

**Description**

I'm trying to use PureScript. The landing page of Prismjs lists it as supported. Supposedly it depends on Haskell. I can't get PureScript to work and can find no examples of how to use it with Webpack. I've confirmed there is no purescript or pure component in the `components` directory.

**Example**

I'm using the following code:

```
import 'prismjs/components/prism-haskell.min';
import 'prismjs/components/prism-purescript.min';
```

Which results in:

```
This dependency was not found:
                                                                                                                         er/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/
* prismjs/components/prism-purescript.min in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/CodeEditor.vue?vue&type=script&lang=js&
```

I've confirmed it doesn't install with the latest release, also can't find it via the CDN.

**Comment by mAAdhaTTah** [comment]
Upgrade to 1.22.0, which was [just released](https://github.com/PrismJS/prism/releases/tag/v1.22.0). That release includes PureScript.
