### ISSUE TITLE
How to change .token.string, .token.selector classes with custom css class of our own in VueJS app for custom color rendering.

### ISSUE THREAD

**Issue by KiranJas** [PrismJS/prism#2589]
Successfully implemented `prismjs` in my vuejs app by importing.

```
<script>
import 'prismjs/prism'
import 'prismjs/themes/prism-okaidia.css' // theme
import 'prismjs/components/prism-swift.min' // swift lang

export default {
}
</script>
```
Which works fine in `<template>` as follows...

```
<template>
  <div>

    <pre><code class="language-swift">
      func checking() {
        let value = "Testing"; let value = "Testing"; let value = "Testing"; let value = "Testing";
      }
    </code></pre>

  </div>
</template>
```

So how is it possible to change the colors of these classes: .token.string, .token.selector 
the requirement is to use custom color instead of the default provided by the theme. Like using red instead of green below.

![Screenshot 2020-10-13 at 7 34 51 PM](https://user-images.githubusercontent.com/68776693/95871569-6d484480-0d8b-11eb-8f1f-c1d3f93e3fcb.png)

I've gone through prismjs plugin feature - [primjs plugin](https://prismjs.com/plugins/custom-class/)
How can we implement this in vue app?

**Comment by RunDevelopment** [comment]
I never used Vue but it should be possible to define some CSS, right? If so, then you can change the color of all `.token.string, .token.selector` like so:

```css
.token.string, .token.selector {
    color: red;
}
```

If you only want to change the color of __one__ specific element (not all elements with some class), then you can use [Keep Markup](https://prismjs.com/plugins/keep-markup/).

**Comment by KiranJas** [comment]
@RunDevelopment 

It's not working by specifying colors externally for specific token classes.
But it did work with the new theme file I've created from a reference to the existing one and used a new one instead of the above approach with the existing one.

Thanks... I'm closing this issue now...
