### ISSUE TITLE
can't display #include <iostream> in c++ code

### ISSUE THREAD

**Issue by likev** [PrismJS/prism#259]
cpp code:

```
    #include <iostream>

    int main()
    {
        std::cout<<"hello prism.js!";
        return 0;
    }
```

display like this with prism
![look like this](https://cloud.githubusercontent.com/assets/3146974/3074531/34986c06-e343-11e3-9992-3b64f75aea38.jpg)

**Comment by kirk-loeten** [comment]
I use python to copy my project files in a folder for the website. Then I replace a placeholder in a html template, while this the '<' where replaced with `&lt;`. It works fine.
