### ISSUE TITLE
Highlighting ERB examples incorrectly

### ISSUE THREAD

**Issue by colebemis** [PrismJS/prism#2602]
**Information**
- Language: ERB
- Plugins: none

**Description**

Prism seems to be having trouble parsing more complicated ERB examples. Here's a [ViewComponents](https://github.com/github/view_component) example that it's parsing incorrectly:

![image](https://user-images.githubusercontent.com/4608155/97037506-3659f780-151e-11eb-89d0-ea4775a2005d.png)

If it helps, here's a link to the PR where I introduced ERB syntax highlighting into my project: https://github.com/primer/doctocat/pull/203

**Code snippet**

<details>
<summary>The code being highlighted incorrectly.</summary>

```
<div style="padding-left: 60px">
  <%= render(Primer::TimelineItemComponent.new) do |component| %>
    <% component.slot(:avatar, src: "https://github.com/github.png", alt: "github") %>
    <% component.slot(:badge, bg: :green, color: :white, icon: :check) %>
    <% component.slot(:body) { "Success!" } %>
  <% end %>
</div>
```

</details>

**Comment by RunDevelopment** [comment]
That's because you are using Ruby to highlight the snippet instead of ERB. With ERB, the snippet is highlighted just fine. See for yourself [here](https://prismjs.com/test.html#language=erb).
