### ISSUE TITLE
Add support for Apex

### ISSUE THREAD

**Issue by lukethacoder** [PrismJS/prism#2604]
**Language**
Apex is a strongly typed, object-oriented programming language that allows developers to execute flow and transaction control statements on Salesforce servers in conjunction with calls to the API. Using syntax that looks like Java and acts like database stored procedures, Apex enables developers to add business logic to most system events, including button clicks, related record updates, and Visualforce pages.

Check out the [official docs](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_intro_what_is_apex.htm)

Is it worth adding what would essentially be an alias of the java language as an entirely new language definition. Noticed you can alias a language (but still displays as the actual language you're aliasing when using the 'display language' addon), but can you go the other way.

![image](https://user-images.githubusercontent.com/13529535/97066080-f2d6ba80-15fd-11eb-8cc3-c22c63e53c2c.png)

Could run this, but seems overkill to add an entire new language definition if its practically the same as the java definition.

```javascript
// prism-apex.js
;(function (Prism) {
  Prism.languages.apex = Prism.languages.java
})(Prism)
```

**Comment by RunDevelopment** [comment]
Prism's Java language definition is specifically made for Java code. Some of the highlighting is even dependent on Java's naming conventions which aren't enforced in Apex. While an alias may work as a temporary workaround, it's not enough for Prism.

> seems overkill to add an entirely new language definition if it's practically the same as the java definition.

I took a look at the doc and the languages seem very different to me. One of the more obvious differences is SOQL and SOSL queries but there are many more besides that.
