### ISSUE TITLE
Scheme function call

### ISSUE THREAD

**Issue by jcubic** [PrismJS/prism#2609]
**Information:**
Tested in https://prismjs.com/test.html#language=scheme

**Description**
first argument inside parentheses not always should be mark as function name

**Example**
```scheme
'(foo bar baz)
`(foo bar baz)
#(foo bar baz)
'#(foo bar baz)
```

(NOTE: GitHub is also wrong about this).

in those cases first token should not be function. I think (not 100% sure) that you only need `(?:$|\s|\()\(` in front of the regex (maybe just in case `(?:$|[()[\]\s])[([]` to support brackets and open close before) that match function call if before parentheses is not space, bracket or beginning of the of the string it should not be marked as function call.

**Comment by RunDevelopment** [comment]
I think the easiest solution here is to just disallow ``['`#]`` characters before the `(`. 

Btw. What are these examples? I know that the first one is a list but I've never seen the other three.

**Comment by jcubic** [comment]
```scheme
'(foo bar baz)  ;; quoted list same as (list 'foo 'bar 'baz)
`(foo bar baz)  ;; backquoted list that allow special tokens , and ,@ that evaluate the expression (unescape)
#(foo bar baz) ;; vector like array in JavaScript
'#(foo bar baz) ;; this is similar as vector but symbols are quoted like with '(foo bar baz) without this foo bar baz need to be variable
```
