### ISSUE TITLE
Danger doesn't work with pull requests

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#2627]
https://github.com/danger/danger-js/issues/918

My disappointment is immeasurable and my day is ruined.

---

So yeah. That's it for my idea of offloading common code review tasks to Danger. 
[Here](https://github.com/PrismJS/prism/runs/1374765045?check_suite_focus=true#step:4:10)'s an example of the bug in action.

**Comment by mAAdhaTTah** [comment]
omfg

**Comment by mAAdhaTTah** [comment]
So it's less a Danger issue and more a GitHub actions issue. Not that it makes me feel any better...

**Comment by RunDevelopment** [comment]
Yeah, forked repos only have [read permission](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token), so they can't add comments or anything. A personal access token won't help either because [no secrets are shared with forks](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#:~:text=forked%20repository) (aside from `GITHUB_TOKEN`). This makes Danger pretty much useless for OSS project.

Technically, it's not Danger's fault but they could at least mention this limitation in their docs.
