### ISSUE TITLE
"TypeError: lang is undefined" when using more than 7 languages

### ISSUE THREAD

**Issue by lobodol** [PrismJS/prism#2637]
**Information:**
- Prism version: 1.22.0
- Babel-plugin-prismjs version: 1.1.1
- Yarn version: 1.17.3
- NodeJS: 10.16.3
- Plugins: "line-numbers", "toolbar", "show-language", "command-line", "normalize-whitespace", "copy-to-clipboard"
- Environment: Webpack Encore

**Description**
Here is my `.babelrc`:

```json
{
	"plugins": [
		["prismjs", {
			"languages": ["arduino", "bash", "c", "csharp", "css", "javascript", "php", "yaml"],
			"plugins": ["line-numbers", "toolbar", "show-language", "command-line", "normalize-whitespace", "copy-to-clipboard"],
			"theme": "okaidia",
			"css": true
		}]
	]
}
```
Here is the import of PrismJS:
```js
import Prism from 'prismjs';

Prism.highlightAll();
```

And here is the markup:
```html
<pre class="line-numbers"><code class="language-css">
.Foo {color: red;}
</code></pre>
```
As a result I get an error message is the console: "TypeError: lang is undefined" linked to file `prism-core.js` line 290.
**But**, if I remove one of the languages (anyone) in the `.babelrc` config file, there is no more error.

Is this a [babel-plugin-prismjs](https://github.com/mAAdhaTTah/babel-plugin-prismjs) issue?

**Comment by mAAdhaTTah** [comment]
Hmm, could be a babel plugin issue, but first, do you have a live example I could look at?

**Comment by mAAdhaTTah** [comment]
Also, is it reproducible w/ removing any language or one language in particular?

**Comment by lobodol** [comment]
@mAAdhaTTah No, I don't have a live example, it happened during development.
The error disappears if I remove a single language, anyone in the list, not a particular one.

**Comment by lobodol** [comment]
Additional information: I run `yarn` in a Docker container:

```bash
docker run -it --rm -v $(pwd):$(pwd) -w $(pwd) node:10.16.3 yarn encore prod
```

**Comment by lobodol** [comment]
I upgraded Babel plugin to 2.0 and it seems working.
