### ISSUE TITLE
Keep Markup plugin has contents shifted

### ISSUE THREAD

**Issue by chriscam85** [PrismJS/prism#2645]
**Information:**
- Prism version: latest from the download page
- Plugins: Keep Markup
- Environment: Chrome

**Description**
I am working in a pre-built cloud tool, so I do not have access to adjust certain things. Within the tool, there is a "global search" page which returns HTML showing where your query text shows up across the tool.
It returns HTML pre tags with the text content of the pre tag being the proprietary language of the tool. Anywhere within that pre tag, your query text shows up wrapped in a span tag with class "highlighted".
example when I search for text "true":
```
<pre>
if(find(showLineGridColumns_t,"List Price")==-1){
    return <span class="highlighted">true</span>;
}
return false;
</pre>
```

What I've done to enhance this tool, is after the page loads, I wrap the inner contents of the pre tags with a code tag and then apply Prism using the highlightAll method. Worked great, but I lost the original highlights for the search query text.
So, I loaded in Keep Markup plugin and tried again. Now, I'm seeing the original highlights shifting to later text in the string, not matching the query text.
example of the shift (I took out the regular "token" tags):
```
if(massApplyFunction_t == "Country"){
    return t<span class="highlighted">rue</span>;
}
return false;
```
This example shows it off by one character, but it varies. Sometimes its many characters off.

![image](https://user-images.githubusercontent.com/7005854/99739388-8080bb00-2a81-11eb-9fcb-a6486e7ab5db.png)
![image](https://user-images.githubusercontent.com/7005854/99739403-8e364080-2a81-11eb-899a-65d468f6f145.png)
![image](https://user-images.githubusercontent.com/7005854/99739501-c50c5680-2a81-11eb-82c8-cf3e50662d29.png)

Any ideas?

**Comment by RunDevelopment** [comment]
Cannot reproduce.

Could please attach a small example project that reproduces the issue? 

Also, the language you're using doesn't seem to highlight `elif` as a keyword. Is this a bug in Prims or did you use the wrong language?

**Comment by YannisDelmas** [comment]
I encountered the same issue with versions 1.17.1 and 1.22.0. It seems that the problem came from an incompatibility with the `remove-initial-line-feed` plugin. I solved this issue by replacing the `remove-initial-line-feed` plugin by the `normalize-whitespace` plugin.

**Comment by mAAdhaTTah** [comment]
Makes sense. If there's any additional issues, let us know and we can reopen but I don't think there's anything actionable here.

**Comment by windymindy** [comment]
> Makes sense. If there's any additional issues, let us know and we can reopen but I don't think there's anything actionable here.

Yep. I reproduced in conjunction with command line plugin.


**Information:**
- Prism version: PrismJS 1.29.0
- Plugins: https://prismjs.com/download.html#themes=prism&languages=markup+css+clike+javascript+bash&plugins=line-numbers+keep-markup+command-line+unescaped-markup+normalize-whitespace+match-braces+treeview
- Environment: browser

**Description**
The preserved html tag is indeed missplaced when multiple plugins interract and text rearrangements take place.

**Example**
https://codepen.io/windymindy/pen/XWqBaBX reproduces the bug
https://codepen.io/windymindy/pen/RwyBZYQ works just fine

**Comment by RunDevelopment** [comment]
@windymindy Could you please open a new issue for this? Since your issue seems to be caused by plugin incompatibility, I think we should treat this as a new bug.
