### ISSUE TITLE
Prism only worked on safari

### ISSUE THREAD

**Issue by draveness** [PrismJS/prism#2646]
**Information:**
- Prism version: 1.22
- Plugins: [a list of plugins you are using or 'none']
- Environment: Browser
- macOS: 11.0.1

**Description**

Can refer to this [page](https://draveness.me/whys-the-design-go-generics/) on different browsers to see the result, it does not work on chrome and edge

![image](https://user-images.githubusercontent.com/6493255/99750463-698ea700-2b1b-11eb-8ce1-f8a752afb7a2.png)

but it works on safari

![image](https://user-images.githubusercontent.com/6493255/99750501-77442c80-2b1b-11eb-98ef-af38afac36e7.png)

**Example**

https://draveness.me/whys-the-design-go-generics/

**Comment by mAAdhaTTah** [comment]
Looks like highlight.js is _also_ on the page? I see the page render w/ one style then switch over to the other, although when it does, it does seem to work for me. Not 100% sure what the problem is, but I don't think it's Prism.

**Comment by RunDevelopment** [comment]
Works in Chrome on my end as well.
