### ISSUE TITLE
Diff highlight plugin does not highlight first and last lines

### ISSUE THREAD

**Issue by jsmolka** [PrismJS/prism#2650]
**Information**
- Language: C++
- Plugins: Diff Hightlight

**Description**
I am using the Diff Highlight plugin to highlight a C++ diff. Some of the first and last lines are ignored during highlighting (the `switch` in the example code is just plain text).

**Code snippet**
<details>
<summary>The code being highlighted incorrectly.</summary>

```diff
switch (state) {  // <- the switch is plain text, not keyword as expected
  case State::InitOne:
-   if (port.cs.low() && port.sck.high())
+   if (port.cs.low())
      setState(State::InitTwo);
    break;

  // ...
}
```

</details>

**Sample**
I attached a small sample project which highlights the problems I have.

[sample.zip](https://github.com/PrismJS/prism/files/5574900/sample.zip).

**Comment by RunDevelopment** [comment]
This is because your example doesn't conform to the [unified diff format](https://en.wikipedia.org/wiki/Diff#Unified_format). Every unchanged line has to start with a single space.

**Comment by jsmolka** [comment]
Thank you!
