### ISSUE TITLE
Language request: DOT (graph description language)

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#2660]
**Language**
"DOT is a graph description language. DOT graphs are typically files with the filename extension gv or dot." - [source](https://en.wikipedia.org/w/index.php?title=Graphviz&oldid=987303523)

**Additional resources**
[Wikipedia](https://en.wikipedia.org/wiki/DOT_(graph_description_language))

**Comment by IronBlood** [comment]
As `DOT` and `gv` are announced officially among [#languages](https://prismjs.com/#languages-list), will there be a new release like v1.24.0?

**Comment by RunDevelopment** [comment]
Yes, DOT will be in the next release soon but you can also get it right now by going to [our download page](https://prismjs.com/download.html#themes=prism&languages=dot).
