### ISSUE TITLE
Incomplete support for CSP

### ISSUE THREAD

**Issue by edukisto** [PrismJS/prism#2663]
**Information**

- Language: CSP
- Plugins: none

**Does the problem still occur in the latest version of Prism?**

[Yes](https://prismjs.com/test.html#language=csp).

**Description**

**_New directives and keywords_**

From the latest (2018-10-15) [working draft](https://www.w3.org/TR/2018/WD-CSP3-20181015/) of CSP3:

- `navigate-to`;
- `prefetch-src`;
- `script-src-attr`;
- `script-src-elem`;
- `style-src-attr`;
- `style-src-elem`;
- `'report-sample'`;
- `'unsafe-allow-redirects'`;
- `'unsafe-hashes'`.

From [Trusted Types](https://w3c.github.io/webappsec-trusted-types/dist/spec/):

- `require-trusted-types-for`;
- `trusted-types`;
- `'allow-duplicates'`;
- `'script'`.

These are partially implemented in Blink (Chromium, Chrome, etc.) and Gecko (Firefox).

Also, Google Cobalt [recognizes](https://github.com/youtube/cobalt/blob/0d1858f87ad39776d3bccd0ec75731daf232e0d3/src/cobalt/csp/content_security_policy.cc#L155-L157) the [`suborigin`](https://metromoxie.github.io/webappsec/specs/suborigins/#the-suborigin-directive) directive.

By the way, there is a bunch of relevant (`input-protection`) and dropped (`input-protection-clip`, `input-protection-selectors`) directives from [User Interface Security and the Visibility API](https://www.w3.org/TR/2016/WD-UISecurity-20160607/), but I don’t know of any software that uses these directives.

**_Old directives and keywords_**

Prism supports some directives and keywords, which are dropped from CSP (see the table below).

|Token                       |Introduced in                                                           |Removed from                                                        |
|----------------------------|------------------------------------------------------------------------|--------------------------------------------------------------------|
|`disown-opener`             |[CSP3. WD. 2016-08-01](https://www.w3.org/TR/2016/WD-CSP3-20160801/)    |[CSP3. WD. 2018-10-15](https://www.w3.org/TR/2018/WD-CSP3-20181015/)|
|`referrer`                  |[CSP 1.1. WD. 2014-02-11](https://www.w3.org/TR/2014/WD-CSP11-20140211/)|[CSP2. CR. 2015-02-19](https://www.w3.org/TR/2015/CR-CSP2-20150219/)|
|`reflected-xss`             |[CSP 1.1. WD. 2012-12-13](https://www.w3.org/TR/2012/WD-CSP11-20121213/)|[CSP2. CR. 2015-02-19](https://www.w3.org/TR/2015/CR-CSP2-20150219/)|
|`'unsafe-hashed-attributes'`|[CSP3. WD. 2016-06-21](https://www.w3.org/TR/2016/WD-CSP3-20160621/)    |[CSP3. WD. 2018-10-15](https://www.w3.org/TR/2018/WD-CSP3-20181015/)|

[Gecko](https://github.com/mozilla/gecko-dev/blob/cd8b8939b911b3c28c13de23fde7201a8452499b/dom/security/nsCSPParser.cpp#L861-L871) still recognizes `reflected-xss` as a directive, albeit ignored.

Here are some directives and keywords, which are also dropped from CSP and have no support in Prism (see the table below).

|Token                     |Introduced in                                                         |Removed from                                                          |
|--------------------------|----------------------------------------------------------------------|----------------------------------------------------------------------|
|`policy-uri`              |[CSP 1.0. WD. 2011-11-29](https://www.w3.org/TR/2011/WD-CSP-20111129/)|[CSP 1.0. WD. 2012-07-10](https://www.w3.org/TR/2012/WD-CSP-20120710/)|
|`'unsafe-hash-attributes'`|[CSP3. WD. 2016-04-25](https://www.w3.org/TR/2016/WD-CSP3-20160425/)  |[CSP3. WD. 2016-06-21](https://www.w3.org/TR/2016/WD-CSP3-20160621/)  |

[Blink](https://github.com/chromium/chromium/blob/004ed837b5ea0e08cc209f36b9f274f43a51d439/third_party/blink/renderer/core/frame/csp/content_security_policy.cc#L1294-L1297) recognizes `policy-uri` as a “removed from the specification” directive. Should `policy-uri` and `'unsafe-hash-attributes'` be added for consistency?

**Code snippet**

<details>

<summary>The code being highlighted incorrectly.</summary>

```
default-src 'report-sample' 'unsafe-hash-attributes' 'unsafe-hashes';
navigate-to 'unsafe-allow-redirects';
prefetch-src;
script-src-attr;
script-src-elem;
style-src-attr;
style-src-elem;

require-trusted-types-for 'script';
trusted-types foo bar 'allow-duplicates';

suborigin;

input-protection;
input-protection-clip;
input-protection-selectors;

policy-uri https://example.com;
```

<del>(`script-src-attr`, `script-src-elem`, `style-src-attr`, `style-src-elem` are partly highlighted due to #2661.)</del>

</details>

**Questions**

1. Should I add new directives and keywords from CSP and Trusted Types?
2. Should I add `suborigin`?
3. Should I add `input-protection`?
4. Should I add `input-protection-clip` and `input-protection-selectors`?
5. Should I **remove** directives and keywords, which are dropped from CSP (`disown-opener`, `referrer`, `reflected-xss`, `'unsafe-hashed-attributes'`)?
6. Should I **add** directives and keywords, which are dropped from CSP (`policy-uri` and `'unsafe-hash-attributes'`)?

**Comment by RunDevelopment** [comment]
Thank you for doing all this research @edukisto!

I think that Prism should support all keywords and directives that it into a WD or RC of CSP. We can't assume that people only use Prism to highlight the latest version of CSP, so we do have to support some older versions as well. To answer your questions:

1. CSP3, yes. Trusted Types, no. TT is only an Editor's draft right now and "is provided for discussion only and may change at any moment."
2. It's not part of the CSP spec, so no.
3. Yes, and...
4. yes. The UI Security and the Visibility API seems to be fairly official, so let's support it.
5. No, people might want to highlight code containing these tokens, so let's keep them.
6. Yes, please.

**Comment by edukisto** [comment]
OK.

I forgot to mention `'unsafe-dynamic'`.

|Token                     |Introduced in                                                       |Removed from                                                        |
|--------------------------|--------------------------------------------------------------------|--------------------------------------------------------------------|
|`'unsafe-dynamic'`        |[CSP3. WD. 2016-04-25](https://www.w3.org/TR/2016/WD-CSP3-20160425/)|[CSP3. WD. 2016-06-21](https://www.w3.org/TR/2016/WD-CSP3-20160621/)|

**Comment by RunDevelopment** [comment]
`'unsafe-dynamic'` can go into Prism as well ;)

**Comment by edukisto** [comment]
Some notes:

- directive values are case insensitive as well as names;
- in [CSP2](https://www.w3.org/TR/2016/REC-CSP2-20161215/#base64_value) hashes and nonces are [base64](https://tools.ietf.org/html/rfc4648#section-4) (`[+/\d=A-Za-z]+`) values. [CSP3](https://www.w3.org/TR/2018/WD-CSP3-20181015/#grammardef-base64-value) also allows [base64url](https://tools.ietf.org/html/rfc4648#section-5) (`[-\d=A-Z_a-z]+`) values.
