### ISSUE TITLE
Line-highlight corrupt print

### ISSUE THREAD

**Issue by yoshigev** [PrismJS/prism#2666]
**Information:**
- Prism version: latest from the download page
- Plugins: toolbar, copy-to-clipboard, line-highlight
- Environment: Browser (chrome)

**Description**
I'm using line-highlight, and when printing the page, the code is partially hidden.

This is caused because the transparent background of the `line-highlight` class is printed as opaque white.

**Workaround**
Set the style of the `line-highlight` class like this:
```css
.line-highlight {
    -webkit-print-color-adjust: exact;
}
```
This works in Chrome. I didn't test with other browsers.

**Example**
```html
<pre class="code-toolbar" data-line="4-8"><code class='language-json'>{


  "channelDat`": {
    "foo": {
      "bar": "bar"
    }
  }
}</code></pre>
```
Produces the following when printing the page:
![image](https://user-images.githubusercontent.com/1838547/101054604-ba79b300-3591-11eb-92f5-125ce771e8fb.png)

**Comment by RunDevelopment** [comment]
Cannot reproduce.

[Here is a minimal example project](https://github.com/PrismJS/prism/files/5637734/project.zip) with your configuration and code. I tested it on Chrome 86 and everything works.

This seems like a problem with the specific CSS used on your site.

**Comment by yoshigev** [comment]
Hi @RunDevelopment.
Thanks for the quick reply.

I forgot to mention on my original post that it only happens when de-selecting the "Background graphics" checkbox on the Print options.
I just tried it with your project and it reproduced (using Chrome 86):
![image](https://user-images.githubusercontent.com/1838547/101091053-4f93a080-35c0-11eb-9553-1ff5b5a3b01d.png)

**Comment by RunDevelopment** [comment]
Sorry. I thought you meant "printed as opaque white" as rendered and literally printed. My bad.

I'll make a PR with your fix.
