### ISSUE TITLE
Syntax Highlighting for ICU message templates

### ISSUE THREAD

**Issue by CrazyChris75** [PrismJS/prism#2675]
The Unicode ICU message templates (see https://unicode-org.github.io/icu/userguide/format_parse/messages) are used in browsers and libraries (for example format.js and react-intl, see https://formatjs.io/docs/intl-messageformat) 

Syntax hightlighting for placeholders and parameters in these kinds of templates would be great:

Maybe there is already a supported language that would include such single curly bracket placeholders
like `{var}`
or `{price, number, ::currency/EUR}`

If not, ICU messages being a standardized templating system, it would be great to include it in supported languages of prism.js and I think it should be based on "markup"

**Comment by bertho-zero** [comment]
https://github.com/PrismJS/prism/pull/2745

**Comment by RunDevelopment** [comment]
I _think_, I forgot to close this after #2745. Please comment if this need to be reopened.
