### ISSUE TITLE
Markdown: Add support for image

### ISSUE THREAD

**Issue by Q-Qplus1s** [PrismJS/prism#2676]
**Motivation**
support image token
**Description**
```markdown
![emoji](https://content.markdowner.net/emoji/g/64/1f44d.png)
```
![emoji](https://content.markdowner.net/emoji/g/64/1f44d.png)

**Comment by RunDevelopment** [comment]
May I ask what exactly you mean by "support"? We already highlight image links correctly, so what more is there to support for a syntax highlighter?

**Comment by Q-Qplus1s** [comment]
extract as image token, so we can get more information from the token (alt, src, title), this can facilitate custom rendering
```markdown
![emoji](https://content.markdowner.net/emoji/g/64/1f44d.png "This is title")
```

**Comment by RunDevelopment** [comment]
Ok. I'll make a PR.
