### ISSUE TITLE
JSON: String with many escaped quotes break highlighting in Safari

### ISSUE THREAD

**Issue by petergp** [PrismJS/prism#2689]
**Information**
- Language: JSON
- Plugins: none

**Description**
Prism fails to tokenise a json text correctly in Safari if one of the values contains a large number (998 or more to be exact) of escaped quotes (\"). This is a problem for me since I'm trying to highlight some JSON where the values contain HTML that has a lot of escaped quotes.

**Code snippet**

The snippet on the test page in the link below show the issue. Notice how things after the large string is highlighted incorrectly. If a single escaped quote is removed then the text is highlighted correctly.
[Test page](https://prismjs.com/test.html#language=json&text=%7B%0A%20%20%221%22%3A%20%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%5C%22%22%2C%0A%20%20%222%22%3A%20%22123%22%0A%7D)

<details>
<summary>The code being highlighted incorrectly.</summary>

```
{
  "1": "\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"",
  "2": "123"
}
```

</details>

**Comment by RunDevelopment** [comment]
What is highlighted incorrectly? I don't see anything wrong with your example.

![image](https://user-images.githubusercontent.com/20878432/103463998-e030de00-4d30-11eb-91ec-02eadd6a854b.png)

**Comment by petergp** [comment]
Looks like it only happens in Safari.

<img width="921" alt="Screenshot 2021-01-02 at 7 32 17 PM" src="https://user-images.githubusercontent.com/390601/103464049-44ec3880-4d31-11eb-85f2-d4e783abb90c.png">

**Comment by RunDevelopment** [comment]
I think I know what the problem is. I don't have access to a machine with Safari, so could you please paste the following into the dev console on the test page:

```js
Prism.languages.json = {
	'property': {
		pattern: /(^|[^\\])"(?:\\.|[^\\"\r\n])*"(?=\s*:)/,
		lookbehind: true,
		greedy: true
	},
	'string': {
		pattern: /(^|[^\\])"(?:\\.|[^\\"\r\n])*"(?!\s*:)/,
		lookbehind: true,
		greedy: true
	},
	'comment': {
		pattern: /\/\/.*|\/\*[\s\S]*?(?:\*\/|$)/,
		greedy: true
	},
	'number': /-?\b\d+(?:\.\d+)?(?:e[+-]?\d+)?\b/i,
	'punctuation': /[{}[\],]/,
	'operator': /:/,
	'boolean': /\b(?:true|false)\b/,
	'null': {
		pattern: /\bnull\b/,
		alias: 'keyword'
	}
};
```

After that, slightly change the text of your example being

**Comment by petergp** [comment]
You are a genius! That fixes it! Impressive that you were able to come up with a solution without a way to test it.

**Comment by RunDevelopment** [comment]
Seems like my guess was correct. Safari's regex engine will stop searching for regex matches after 1million backtracking steps. My guess was that this problem is because our regex to detect properties takes O(n^2) many backtracking steps to reject strings of the form `somePrefix + '\\"'.repeat(n) + someSuffix`. This is why highlighting breaks after repeating `\"` a little less than 1000 times. 

Thanks for the compliment but I wouldn't have been able to deduce that without your excellent error report, so - thank you.

This problem probably isn't unique to JSON. I'll look through our languages and fix this type of problem.

**Comment by petergp** [comment]
Thanks @RunDevelopment. I appreciate your work

**Comment by joshgoebel** [comment]
> Seems like my guess was correct. Safari's regex engine will stop searching for regex matches after 1million backtracking steps

From what I recall from our prior testing Safari and Edge both have this protection while Chrome still just keeps going until it finishes, no matter how long it takes.

**Comment by RunDevelopment** [comment]
@joshgoebel [Indeed](https://github.com/PrismJS/prism/pull/2590#issuecomment-731585801)... kinda... [Our pattern](https://github.com/PrismJS/prism/blob/1506f345b0c917b28047ec6e5b8b8dc81790ad98/components/prism-json.js#L4) doesn't backtrack. The regex describes an effective DFA, there is no way for it to backtrack. The problem is that the regex engine _moves_ the pattern across the string and that Safari actually counts the number of disjunctions it encounters and **not** backtracking steps. I will make an issue about this problem tomorrow and explain it in more detail.

**Comment by joshgoebel** [comment]
I loosely understand what you mean.  Probably good that Safari also includes this protection as well (at least it's being consistent).  I wonder what Edge's behavior is here.

**Comment by RunDevelopment** [comment]
New Edge is built on Chromium, so the same as Chrome and Firefox.

**Comment by joshgoebel** [comment]
> New Edge is built on Chromium, so the same as Chrome and Firefox.

No.  It's back-tracking behavior is *definitely* different than Chrome.  It cuts short after so many millions of iterations, just like Safari does.

**Comment by RunDevelopment** [comment]
New Edge has the same behaviour as other Chromium-based browsers on my machine.

<details>

![image](https://user-images.githubusercontent.com/20878432/103477857-ed96a880-4dc2-11eb-8b37-d28b1946f7b1.png)

</details>

> Didn't we already have this discussion?

[We did](https://github.com/PrismJS/prism/pull/2590#issuecomment-731615826). I just assumed that you were right but I did some testing afterward and found that it wasn't the case. 

What did you do to get different behaviour?

---

_Note:_
IE11 behaves as you described (backtracking limit) and since old Edge is built on the same engine, it probably does too (haven't tested; restoring old Edge is a pain). But as you previously said:

> _[...]_ we don't care about the former _[Edge]_ [pre Chrome engine] (as much).

and I don't either.

**Comment by joshgoebel** [comment]
> What did you do to get different behaviour?

I believe was using one of the first exponential regex examples (I may glance at our earlier thread and it may jog my memory that it was one of those).  I think I was using `exec` rather than `test` and I wasn't using `performance` or a closure... I just ran the variants in the console and noted how long it took to spit out the answer.  No matter how high the repeat got Safari _and Edge_ would always return fast, where-as Chrome would scale as you're seeing in the snap above.

Perhaps the behavior has changed - I was using the most recent Edge at the time (Chrome based), not an early version.   _I'll try it again later locally and see if I get different results than you._
