### ISSUE TITLE
Javascript family leaving 'template' span open after particular earlier syntax

### ISSUE THREAD

**Issue by danopia** [PrismJS/prism#2694]
**Information**
- Language: Javascript, also Typescript
- Plugins: Whatever the test page uses, presumably none

**Description**

I found a highlighting bug in this source code: https://deno.land/std@0.79.0/encoding/toml.ts and when the latest version of PrismJS was tested it showed a different bug. So I'm reporting the bug from latest here, from copying the whole file into Prism's test page.

It seems like particular template literal usage is getting parsed correctly earlier in the file, and then breaking other template tags later in the file. The affected line has its first template tag token ignored which then causes template tag parsing to be inverted for the rest of the file.

It seems there's two different setup lines for this bug that both need to be in a particular order:

1. One line with a regex containing a single quote, and then a single quote in template quotes. This renders fine.
2. Anywhere after that, a comment with a template literal in it. This renders fine.
3. Anywhere after that, a normal basic template literal. This breaks for the rest of the file

**Code snippet**

![Screenshot 2021-01-03 at 18 52 50](https://user-images.githubusercontent.com/40628/103485196-f4d6aa00-4df4-11eb-8cfd-cd59e9995bd7.png)

[Test page](https://prismjs.com/test.html#language=javascript&text=replace(%2F'%2F%2C%20%60'%60)%0A%0Aconst%20var1%20%3D%20%60this%20is%20fine%60%3B%0Aconst%20var2%20%3D%20%60this%20is%20fine%60%3B%0A%0A%2F%2F%20%60load%20bearing%20comment%60%0A%0Aconst%20var3%20%3D%20%60break%20starts%20here%60%3B%0Aconst%20var4%20%3D%20%60break%20ends%20here%60%3B)

<details>
<summary>The code being highlighted incorrectly.</summary>

```javascript
// One line with a pattern containing single quote, and then a single quote in template quotes
replace(/'/, `'`)

// Anywhere after that, a comment with template tags in it:
// `load bearing comment`

// Anywhere after that, normal basic template tags are broken
const var3 = `break starts here`;
const var4 = `break ends here`;
```

</details>

**Comment by RunDevelopment** [comment]
Thanks for reporting this!

This is a bug in Prism's matching algorithm for greedy rules. I'll try to fix it in the next couple of days.
