### ISSUE TITLE
How to enable the copy plugin

### ISSUE THREAD

**Issue by awnawnawn** [PrismJS/prism#2698]
I am using **prism** in using **hexo**, I want to use the **copy plugin** but I don’t know how to **enable** the **copy plugin**
![Snipaste_2021-01-06_01-12-56](https://user-images.githubusercontent.com/47672657/103680766-9b6fa600-4fc1-11eb-88e8-f8527c29710d.jpg)

**Comment by RunDevelopment** [comment]
This seems to be a configuration issue with Hexo. Please read their [documentation](https://hexo.io/docs/syntax-highlight.html#preprocess). This is not an issue with Prism itself.
