### ISSUE TITLE
`flipped` class added multiple times

### ISSUE THREAD

**Issue by xjArea** [PrismJS/prism#2699]
**Information:**
- Prism version: 1.23
- Plugins: Previewers

When tip add `flipped` className, it will add many times, the class name will repeat.

Here is the screenshort  in Chrome : 
![QQ截图20210106225042_r1_c1](https://user-images.githubusercontent.com/35623539/103782143-0a0c3c80-5072-11eb-9b3e-13170738b21b.gif)

**Comment by mAAdhaTTah** [comment]
IE10 is long since EOL'd and unsupported by Prism.

**Comment by xjArea** [comment]
Prism can run on IE10, just need to add the Polyfill of `Element.prototype.matches()`, if has the sub plugins, prevent auto create and manual operate `Prism.highlightAll()`, than we can solve the problem, I've done a lot of tests using Prism on IE10, although there are some small problems, but it really can run, so please don't close this issue, I'm already fixed the BUG and passed the test on IE10... 😂😂😂

**Comment by RunDevelopment** [comment]
@xjArea It's not that we are unable to support IE10. We don't __want__ to support IE10. IE10 already EOL'd and barely has any users left today. It is not rational to focus our development efforts on a browser that close to none of our users have.

**Comment by xjArea** [comment]
OK,  let's forget this IE10 problem, but there is another problem with this plugin. When tip add `flipped` className, it will add many times, the class name will repeat. This is not the IE10 problem. Chrome and Firefox has the same problem, forgive me, I'm a lazy person and I don't want to open an new issue. Could we solve it ? When you solve this problem, maybe you can add the above code by the way, anyway, Hitchhiker ? ha-ha. 🤣

Here is the screenshort  in Chrome : 
![QQ截图20210106225042_r1_c1](https://user-images.githubusercontent.com/35623539/103782143-0a0c3c80-5072-11eb-9b3e-13170738b21b.gif)

**Comment by mAAdhaTTah** [comment]
Edited OP to capture the new issue. Will look into this. We will not be adding the IE10 code as part of that PR though.
