### ISSUE TITLE
URI query string syntax highlighting

### ISSUE THREAD

**Issue by svodnik** [PrismJS/prism#2707]
**Motivation**
I'm building documentation for API requests, and I want to distinguish the parts of the query string in the URI visually.

**Description**
I'd like to be able to use a URI as my code, and have the scheme, path, query, and fragment visually distinguished, as well as the keys and values within the query.

**Alternatives**
I've tried a number of supported languages, but none get to this depth of granularity. Choosing `http` applies distinct formatting to the scheme, but not to any of the other URI parts.

**Comment by RunDevelopment** [comment]
Sounds interesting. I'll implement that tomorrow. Some other languages also have URIs as part of their syntax, so granular URI highlighting will benefit them as well.

> Choosing http applies distinct formatting to the scheme, but not to any of the other URI parts.

HTTP highlights HTTP messages, not URIs.

**Comment by joshgoebel** [comment]
> Sounds interesting. I'll implement that tomorrow. 

To do that does that mean adding new styles to all of the official themes?

**Comment by RunDevelopment** [comment]
> To do that does that mean adding new styles to all of the official themes?

I don't think so. Why would it?

**Comment by joshgoebel** [comment]
> have the scheme, path, query, and fragment visually distinguished

I could be ignorant here.  But I was assuming there is a single color for URL now... so how will you distinguish the scheme, path, query, and fragment without adding 3 different colors, one for each piece?

**Comment by RunDevelopment** [comment]
Now, I get what you mean. I don't intend to add any coloring for now. I will just add a grammar that tokenizes URIs.

Our current themes won't support the new URI tokens and leave them as is. If users (or theme authors) wish to highlights (parts of) URIs, they can modify their theme.

**Comment by svodnik** [comment]
Thanks a bunch for building this! Looking forward to implementing it in my site once it goes live.

**Comment by slavafomin** [comment]
Looking forward for the next release. We would really like to use this new URL syntax highlighting.
