### ISSUE TITLE
more detail in HTTP language

### ISSUE THREAD

**Issue by Jxck** [PrismJS/prism#2718]
**Motivation**

in http language, request-line / response-status are less tokenized for me.

I would like to make PR if it works.

**Description**

### request line

current request-line

```htttp
GET /path HTTP/1.1
```

results in

```html
<span class="token request-line">
    <span class="token property">POST</span>
    /default-endpoint HTTP/1.1
</span>
```

would like to be

```html
<span class="token request-line">
    <span class="token method">POST</span>
    <span class="token string">/default-endpoint</span>
    <span class="token property">HTTP/1.1</span>
</span>
```

### response status

current response status

```http
HTTP/1.1 200 OK
```

results in 

```html
<span class="token response-status">
    HTTP/1.1
    <span class="token property">200 OK</span>
</span>
```

would like to be 

```html
<span class="token response-status">
    <span class="token property">HTTP/1.1</span>
    <span class="token number">200</span>
    <span class="token string">OK</span>
</span>
```

class name are wip, ping me if other choice fit's here.

**Comment by RunDevelopment** [comment]
> I would like to make PR if it works.

PRs are always welcome!

> class names are wip

My suggestion for class names is the following: make the _token name_ specific and use _aliases_ for coloring. 

Example:

```html
<span class="token response-status">
    <span class="token http-version property">HTTP/1.1</span>
    <span class="token status-code number">200</span>
    <span class="token reason-phrase string">OK</span>
</span>
```

The grammar could look like this:

```js
'response-status': {
	pattern: /.../,
	inside: {
		'http-version': {
			pattern: /^HTTP\/[\d.]+/,
			alias: 'property'
		},
		'status-code': {
			pattern: /^(\s)\d+(?=\s)/,
			lookbehind: true,
			alias: 'number'
		},
		'reason-phrase': {
			pattern: /^(\s).+/,
			lookbehind: true,
			alias: 'string'
		}
	}
}
```

(I borrowed those names from the [HTTP 1.1 specification](https://tools.ietf.org/html/rfc2616#section-6.1) but you may also use other names.)

**Comment by Jxck** [comment]
> My suggestion for class names is the following: make the token name specific and use aliases for coloring.

it seems reasonable for me.
I'll fix request-line too refer your suggest, and make PR soon.
Thanks !
