### ISSUE TITLE
Magma (Computer Algebra Systems) 

### ISSUE THREAD

**Issue by gordonfroyle** [PrismJS/prism#2742]
Magma is a computer algebra system that is written by and supported from the University of Sydney.

The Magma language is a straightforward imperative language.

http://magma.maths.usyd.edu.au/magma/

**Comment by RunDevelopment** [comment]
Please request one language per issue. It's more difficult to keep track otherwise :)

I opened a new issue for GAP (#2744) and edited this one to be about Magma only.

**Comment by gordonfroyle** [comment]
> Please request one language per issue. It's more difficult to keep track otherwise :)

Sorry, I am new to this; thanks for fixing it.
