### ISSUE TITLE
Complex RegExp rendering failed

### ISSUE THREAD

**Issue by Whaiy** [PrismJS/prism#2750]
**Information:**
Prism version: 1.14; Environment: [firefox, chrome]

**Description**
Dosen't render after of  `<` 

**Example**
`<pre><code class=language-javascript>let regExp = /(?<!x)y/<code></pre>`  Visible renderring ouput: `let regExp = /(?/`

**Comment by RunDevelopment** [comment]
You need to escape all `<` and `&` characters as browsers will interpret these as HTML tags and escape sequences. In this case, `<!x)y/<code>` is [parsed as a directive](https://astexplorer.net/#/gist/d20a9fd1689b40efdacdb046d26127e2/a7df9ca5cf7004251ee81dfa867522831bf9f07f).
