### ISSUE TITLE
Prism shows the code in one line

### ISSUE THREAD

**Issue by OmidShojaee** [PrismJS/prism#2766]
**Information:**
- Prism version: 1.23.0 from CDN
- Plugins: none
- Environment: Microsoft Edge Dev / Firefox Development

**Description**
I use TinyMCE as my editor. I press "Enter" key at the end of each line. This is how editor shows the code:
![1](https://user-images.githubusercontent.com/31741561/108200478-c823eb00-7133-11eb-9e49-f4e8863aa338.png)

This is correct.

But in the HTML page this is what I see:

![2](https://user-images.githubusercontent.com/31741561/108200536-d83bca80-7133-11eb-8f9e-1d990bbaa994.png)

Two lines are concatenated. 

How to fix this issue?

**Comment by mAAdhaTTah** [comment]
Two questions:

1. Can you provide a reproducible example?
2. Can you try it in an incognito tab with no browser extensions enabled? I ask this second one cuz I sometimes have this issue with code snippets and I'm relatively sure it's a browser extension but I haven't dug into which one.

**Comment by OmidShojaee** [comment]
Hi @mAAdhaTTah ,

I don't know how to provide a reproducible example. I use ```TinyMCE``` and its ```codesample``` plugin. In the editor environment everything looks fine (first picture above) but not in the browser.

I have tested with 2 browsers and incognito mode on both. The result is same.

After looking at HTML page source I noticed that there's a ```<br>``` between the first and second line, and somehow this tag is not rendered properly.

If I go back to the editor and press Enter **two** times at the end of the first line, then there is an empty line between the code in **both** editor and browser.

So:

- One Enter key: one ```<br>``` tag, doesn't work
- Two Enter key: two ```<br>``` tag, both work.

That empty line between two code lines is annoying and increases the height of code block with no benefit.

**Comment by mAAdhaTTah** [comment]
> I don't know how to provide a reproducible example.

A page with the resulting output would be fine.

> After looking at HTML page source I noticed that there's a `<br>` between the first and second line, and somehow this tag is not rendered properly.

Prism will strip those elements from the code snippet. If you want to maintain them, use the Keep Markup plugin. I suspect the reason hitting Enter twice is working is because the second time adds an actual new line, which the `pre` element renders as the expected new line.

**Comment by OmidShojaee** [comment]
@mAAdhaTTah

Thanks. Keep Markup solved the issue.

**Comment by mAAdhaTTah** [comment]
Glad to hear it!
