### ISSUE TITLE
Several highlighting bugs in INI

### ISSUE THREAD

**Issue by edukisto** [PrismJS/prism#2775]
**Information**

- Language: INI
- Plugins: none

**Description**

Does someone still need INI? :)

Anyway, I’ve made several tests with C (using [GetPrivateProfileSectionNames](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprivateprofilesectionnames) and [GetPrivateProfileString](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprivateprofilestring) from Win32 API), [PHP](https://www.php.net/manual/en/function.parse-ini-file.php), and [Python](https://docs.python.org/3.8/library/configparser.html).

1. Comments. The dollar sign is useless in `/^[ \t]*[;#].*$/m`. It is also possible that the dot is harmful, because it matches any character except `\n`, `\r`, `\u2028`, or `\u2029` (the `m` flag doesn’t change the behavior), whereas `\u2028` and `\u2029` can occur inside comments.

    I confirm that `#` and `;` comment operators are allowed only at the beginning of a line (besides PHP).

    **Example 1.1**

    ```ini
    [My#Section;Name]
    my#;key=my#;value
    ```

    - the section name is `My#Section;Name`;
    - the key is `my#;key`;
    - the value is `my#;value`.

2. `selector` should be renamed to `namespace`, because sections act like namespaces.

    **Example 2.1**

    ```ini
    [MySection1]
    mykey=myvalue1

    [MySection2]
    mykey=myvalue2
    ```

    Parsers allows to get `mykey` values from both `MySection1` and `MySection2`. The second key doesn’t override the first one, so these values are `myvalue1` and `myvalue2`, respectively.

3. Outer brackets should not be included in section names. If multiple square brackets are given, only the first one (from the left) should be considered a paired punctuation mark.

    **Example 3.1**

    ```ini
    [foo[bar]
    ```

    The section name is `foo[bar`.

    **Example 3.2**

    ```ini
    [foo]bar]
    ```

    The section name is `foo`.

4. Section names, keys, values can contain **any** whitespaces (`\s`). Beginning and trailing whitespaces (`[ \f\t\v]`, not `[ \t]`) on each line should be considered irrelevant.

    **Example 4.1**

    ```ini
     [   My  Section ]  
       my  key  = my  value   
    ```

    - the section name is `My␣␣Section`, not `␣[␣␣␣My␣␣Section␣]`;
    - the key is `my␣␣key`;
    - the value is `my␣␣value`, not `=␣my␣␣value␣␣␣`.

5. Quotes preserve inner spaces. `"` and `'` are allowed, but they are not interchangeable. Parses remove quotes around values.

    **Example 5.1**

    ```ini
     [  " My  Section   " ]  
      " my  key   " =  "   my  value " 
    ```

    - the section name is `"␣My␣␣Section␣␣␣"`;
    - the key is `"␣my␣␣key␣␣␣"`;
    - **the value is `␣␣␣my␣␣value␣`** (without quotes).

6. If multiple equal signs are given, only the first one (from the left) should be considered a key-value separator. All other equal signs should be included in the value.

    **Example 6.1**

    ```ini
    mykey==myvalue
    ```

    The key is `mykey`. The value is `=myvalue`.

    **Example 6.2**

    ```ini
    foo===bar==baz=qux
    ```

    The key is `foo`. The value is `==bar==baz=qux`.

7. AFAIK, [escaping](https://en.wikipedia.org/wiki/INI_file#Escape_characters) is not implemented in the Win32 API. It is not implemented in Prism too. Should it be implemented?

**Notes**

1. PHP caveats:

    - doesn’t allow `#` as a comment operator;
    - allows inline comments after section names and values;
    - doesn’t allow spaces _before_ `[`;
    - doesn’t trim whitespaces around section names (e. g. `[␣My␣␣Section␣␣␣]` is interpreted as `␣My␣␣Section␣␣␣`; same for quoted section names);
    - doesn’t support quoted keys.

2. Python caveats:

    - doesn’t trim whitespaces around section names;
    - trims the `\s` (not only `[ \f\t\v]`) whitespaces around keys.

**Code snippet**

[Test page](https://prismjs.com/test.html#language=ini&text=%23%20Foo.%20Here%20goes%20U%2B2028%3A%20%E2%80%A8.%20Bar.%20Baz.%0A%3B%20Foo.%20Here%20goes%20U%2B2029%3A%20%E2%80%A9.%20Bar.%20Baz.%0A%0A%23%20The%20name%20of%20the%20section%20is%20My%E2%90%A3%E2%90%A3Section.%0A%23%20Moreover%2C%20it%20is%20not%20a%20selector%2C%20but%20a%20namespace.%0A%20%5B%20%20%20My%20%20Section%20%5D%20%20%0A%0A%23%20The%20name%20of%20the%20section%20is%20%22%E2%90%A3My%E2%90%A3%E2%90%A3Section%E2%90%A3%E2%90%A3%E2%90%A3%22.%0A%23%20Moreover%2C%20it%20is%20not%20a%20selector%2C%20but%20a%20namespace.%0A%20%5B%20%20%22%20My%20%20Section%20%20%20%22%20%5D%20%20%0A%0A%23%20Names%20are%20My%22Section%2C%20My%22Section%22Name%2C%20%22My%22Section%22%2C%20%22My%22Section%22Name%22.%0A%5BMy%22Section%5D%0A%5BMy%22Section%22Name%5D%0A%5B%22My%22Section%22%5D%0A%5B%22My%22Section%22Name%22%5D%0A%0A%23%20Only%20the%20leftmost%20equal%20sign%20should%20be%20considered%20a%20key-value%20separator.%0Amykey%3D%3Dmyvalue%0Afoo%3D%3D%3Dbar%3D%3Dbaz%3Dqux%0A%0A%23%20Keys%20can%20contain%20any%20whitespaces.%0A%20%20%20my%20%20key%20%20%3D%20my%20%20value%20%20%20%0A%20%20%22%20my%20%20key%20%20%20%22%20%3D%20%20%22%20%20%20my%20%20value%20%22%20)

<details>

<summary>The code being highlighted incorrectly.</summary>

```ini
# Foo. Here goes U+2028:  . Bar. Baz.
; Foo. Here goes U+2029:  . Bar. Baz.

# The name of the section is My␣␣Section.
# Moreover, it is not a selector, but a namespace.
 [   My  Section ]  

# The name of the section is "␣My␣␣Section␣␣␣".
# Moreover, it is not a selector, but a namespace.
 [  " My  Section   " ]  

# Names are My"Section, My"Section"Name, "My"Section", "My"Section"Name".
[My"Section]
[My"Section"Name]
["My"Section"]
["My"Section"Name"]

# Only the leftmost equal sign should be considered a key-value separator.
mykey==myvalue
foo===bar==baz=qux

# Keys can contain any whitespaces.
   my  key  = my  value   
  " my  key   " =  "   my  value " 
```

</details>

**Comment by edukisto** [comment]
I’ll make a PR on the weekend.

**Comment by RunDevelopment** [comment]
> I’ll make a PR on the weekend.

Looking forward to it!

---

A few notes:

> The dollar sign is useless in `/^[ \t]*[;#].*$/m`. It is also possible that the dot is harmful, because it matches any character except `\n`, `\r`, `\u2028`, or `\u2029` (the `m` flag doesn’t change the behavior)

The `m` flag only affects the `^` and `$` assertions. The `$` is infact useless (because it's equivalent to `(?!.)` in that context) but the `^` at the beginning is not, so you can't remove the flag.

> `selector` should be renamed to `namespace`, because sections act like namespaces.

I can imagine that `selector` was chosen simply because it looks good in most languages. And that is also why I think that `namespace` is not a good idea. `namespace` isn't colored in most themes and simply made slightly transparent. It won't look good.

I would name the token `section` and give it a `selector` alias to keep the current highlighting.

> AFAIK, [escaping](https://en.wikipedia.org/wiki/INI_file#Escape_characters) is not implemented in the Win32 API. It is not implemented in Prism too. Should it be implemented?

Good question. You pointed out that there are many subtle differences between parsers, so I don't think that we have closely mimic the behavior of one specific parser. I would say that is an optional feature. You can Implement it but I won't reject your work if you don't.

**Comment by edukisto** [comment]
**Tested software**

- PHP 5, 7, 8 ([`parse_ini_file`](https://www.php.net/manual/en/function.parse-ini-file.php));
- Python 3 ([`configparser`](https://docs.python.org/3.9/library/configparser.html));
- C + Win32 API ([`GetPrivateProfileSectionNames`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprivateprofilesectionnames), [`GetPrivateProfileString`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprivateprofilestring)) @ Windows 7, 10.

**Implemented features**

|Feature            |Win32 API|PHP 5  |PHP >= 7  |Python < 3.2|Python >= 3.2|
|-------------------|---------|-------|----------|------------|-------------|
|# comments (at /^/)|Yes      |Yes    |**No** [1]|Yes         |Yes          |
|# comments (inline)|No       |No     |No        |No          |No           |
|; comments (at /^/)|Yes      |Yes    |Yes       |Yes         |Yes          |
|; comments (inline)|No       |**Yes**|**Yes**   |**Yes**     |No           |
|\\-escaping        |No       |No     |No        |No          |No           |

[1] They wrote about it [here](https://www.php.net/manual/en/configuration.file.php#configuration.file.changelog), but not [here](https://www.php.net/manual/en/function.parse-ini-file.php) or [here](https://www.php.net/manual/en/function.parse-ini-string.php).

[Colons instead of equality signs](https://en.wikipedia.org/wiki/INI_file#Name/value_delimiter) are used in the RFC 822 [header fields](https://tools.ietf.org/html/rfc822#section-3.2), not in INI.

**Parsing features**

|Input    |Win32 API|PHP    |Python |Consistent?       |
|---------|---------|-------|-------|------------------|
|[foo     |foo      |∅      |∅      |**No** (Win32 API)|
|[foo]    |foo      |foo    |foo    |Yes               |
|␣[foo]   |foo      |∅      |foo    |**No** (PHP)      |
|[foo]␣   |foo      |foo    |foo    |Yes               |
|[␣foo␣]  |foo      |␣foo␣  |␣foo␣  |**No** (Win32 API)|
|["foo"]  |"foo"    |"foo"  |"foo"  |Yes               |
|[␣"foo"␣]|"foo"    |␣"foo"␣|␣"foo"␣|**No** (Win32 API)|
|["␣foo␣"]|"␣foo␣"  |"␣foo␣"|"␣foo␣"|Yes               |
|bar=     |bar      |bar    |bar    |Yes               |
|␣bar␣=   |bar      |bar    |bar    |Yes               |
|"bar"=   |"bar"    |∅      |"bar"  |**No** (PHP)      |
|␣"bar"␣= |"bar"    |∅      |"bar"  |**No** (PHP)      |
|"␣bar␣"= |"␣bar␣"  |∅      |"␣bar␣"|**No** (PHP)      |
|'bar'=   |'bar'    |'bar'  |'bar'  |Yes               |
|␣'bar'␣= |'bar'    |'bar'  |'bar'  |Yes               |
|'␣bar␣'= |'␣bar␣'  |'␣bar␣'|'␣bar␣'|Yes               |
|=baz     |baz      |baz    |baz    |Yes               |
|=␣baz␣   |baz      |baz    |baz    |Yes               |
|=b"az    |b"az     |b"az   |b"az   |Yes               |
|=b"az"   |b"az"    |b"az"  |b"az"  |Yes               |
|=␣"baz"␣ |baz      |baz    |"baz"  |**No** (Python)   |
|="␣baz␣" |␣baz␣    |baz    |"␣baz␣"|**No**            |
|="b"az"  |b"az     |b"az   |"b"az" |**No** (Python)   |
|="baz"   |baz      |baz    |"baz"  |**No** (Python)   |

“␣” stands for

- `/[ \t]/` in PHP;
- `/\s/` in Python;
- `/[ \f\t\v]/` in Win32 API.

**Comment by edukisto** [comment]
The source code I’ve written for the research:

- [C](https://gist.github.com/edukisto/4ee2143f01f5ab092aef2f41ee80da00);
- [PHP](https://gist.github.com/edukisto/157bd4e51954cce4796a33e1dc2e972e);
- [Python](https://gist.github.com/edukisto/8d01c2b0785c64ee77e2b245583b3966).
