### ISSUE TITLE
How to highlight inline code (a few words of code in a line of text)?

### ISSUE THREAD

**Issue by ankush981** [PrismJS/prism#2776]
I've looked really hard around, and have either missed this or this feature is somehow not supported yet (really hard to believe!). The use case is very simple: I want to replicate the behavior of single backticks (markdown) in an HTML file containing code. 

Example: Highlighting the code part in this sentence: "Using something like `x++ === 0` may not be a great idea." As you can see, there's a grey highlight around the inline code, which I'm okay with (don't need colors for inline code, but would be great).

Now, the documentation mentions "inline code", "inline code", "works with inline code", etc., in many places, but I've failed to find an example even after a couple hours of trying. If I go ahead and wrap my inline code in `<pre><code>`, then some magic kicks in, creates a CodeMirror element, creates a <token> element, and the wrapped code becomes a block-level element. 🤐 

Finally, here's the real text from my project:

`The API expects the token to be present in a request header called <pre><code class="language-json">Authorization</code></pre>, whose value . . .`

I'll paste the rendered output as an image (and please, let's not nitpick that my "class" attribute has a wrong value):

![image](https://user-images.githubusercontent.com/4169691/109283635-09f41600-7845-11eb-98e8-9e11975cb0ba.png)

As you can see, the flow is broken. Manually adding another class (say, "inline") and changing its display property doesn't work because the text _after_ the wrapped code is somehow wrapped in a `<token>` element. So, looks like I might need to tinker with this `<token>` element and then God knows what else.

What's the right and least-effort way to handle situations like this one in Prism?

**Comment by RunDevelopment** [comment]
As [our website](https://prismjs.com/index.html#features-full) says:

> Prism forces you to use the correct element for marking up code: `<code>`. __On its own for inline code__, or inside a `<pre>` for blocks of code.

In your example, it has to be:

```html
The API expects the token to be present in a request header called <code class="language-json">Authorization</code>, whose value . . .
```

(Even though `language-json` is definitely wrong...)

All [inline code elements on Prism's website](https://github.com/PrismJS/prism/blob/e931441537878142adb3020cb1e38aeea9f79430/index.html#L94) are also done like this. (The only difference is that we use Prism's language inheritance, so we don't have to declare the language every time.)

> creates a CodeMirror element

A CodeMirror element? What is that?

**Comment by RunDevelopment** [comment]
That being said, I will add a small example for inline code. We do say how it has to be done but we don't show it.

**Comment by ankush981** [comment]
Ah, so I have to drop the `<pre>` tags for inline code . . . couldn't have guessed in a million years. 😂 😂 Regardless, thanks a lot for your response and help! CodeMirror . . . I don't know if it's a browser thing or not, but it's a CSS class that shows up in the browser inspector and applies some font styles. Don't know if it's because of this or something else, but I'm ending up with serif fonts (at least inside inline code):

![image](https://user-images.githubusercontent.com/4169691/109308186-b21ad680-7867-11eb-9fb2-f8c44d3cadfd.png)

Now that I think about it, I remember seeing this CodeMirror class when using a popular VSCode extension to run a live server. Anyway, I think I'll be able to sort out this font mixup. 🙂

**Comment by RunDevelopment** [comment]
Glad I could help.
