### ISSUE TITLE
Code gets indented with indented HTML

### ISSUE THREAD

**Issue by SiddharthShyniben** [PrismJS/prism#2778]
**Information:**
- Prism version: 1.23.0
- Plugins: Autoloader plugin
- Environment: Browser

**Description**
This bug appeared on my first use of PrismJS. 
The problem is code (javascript in my case) is not getting formatted correctly and gets indented with my html code.
Screenshots: 
![Code (indented)](https://user-images.githubusercontent.com/76640268/109475003-29847c00-7a9b-11eb-9a53-32b1e89f3795.png)
![prism-bug-output](https://user-images.githubusercontent.com/76640268/109475138-56d12a00-7a9b-11eb-8476-4e2d31cb9dbc.png)

**Example**
My HTML Code
```html
<!doctype html>
<html lang="en">

<head>
  ...
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/themes/prism-dark.min.css">
</head>

<body>
  ...
  <div class="container">
    <div class="shadow-lg mt-4 p-3 mb-5 bg-body rounded">
      ...
      <pre>
        <code class="language-javascript">
          let game = new UNO(['player1', 'player2']);
          game.startGame();
          // => { players, playerToMove, deck, discardPile, nextColor }
        </code>
      </pre>
    </div>
  </div>
   ....
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/prism.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/plugins/autoloader/prism-autoloader.min.js"></script>
</body>

</html>
```
You can reproduce this by just indenting the code element.

I eventually fixed it by doing this:
![Fixed bug](https://user-images.githubusercontent.com/76640268/109475722-0b6b4b80-7a9c-11eb-8498-fdf220622ca7.png)

But it just looks ugly. I wish there was a plugin or maybe some core functionality which gives us an option to format the code.

**Comment by RunDevelopment** [comment]
> But it just looks ugly.

This is actually [the recommended way](https://html.spec.whatwg.org/multipage/grouping-content.html#the-pre-element) to do it.

> I wish there was a plugin [...] which gives us an option to format the code.

We do offer the [Normalize Whitespace plugin](https://prismjs.com/plugins/normalize-whitespace/). I never touched it myself but it should be able to do exactly what you're asking for.

You can include the plugin like this:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/prism.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/plugins/normalize-whitespace/prism-normalize-whitespace.min.js"></script>
<script type="text/javascript">
// Optional configuration
Prism.plugins.NormalizeWhitespace.setDefaults({
	'remove-trailing': true,
	'remove-indent': true,
	'left-trim': true,
	'right-trim': true,
});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/plugins/autoloader/prism-autoloader.min.js"></script>
```

Hope this helps.

**Comment by SiddharthShyniben** [comment]
Will check it out later and see

**Comment by SiddharthShyniben** [comment]
> This is actually the recommended way to do it.

Alright if it's in the spec I'll do it like that. 

> We do offer the Normalize Whitespace plugin. 

I'll try it out as soon as I can.

Thanks!
