### ISSUE TITLE
PrismJs flagged for critical security vulnerability

### ISSUE THREAD

**Issue by khrome83** [PrismJS/prism#2780]
Please see https://github.com/advisories/GHSA-h4hr-7fg3-h35w

**Comment by joshgoebel** [comment]
I believe it says this is already resolved in 1.23?

**Comment by khrome83** [comment]
you are correct, i miss read. Sorry!

**Comment by kaelig** [comment]
@RunDevelopment Could you please mention it in https://github.com/PrismJS/prism/security/advisories?

**Comment by RunDevelopment** [comment]
@kaelig I made a draft for this and will talk about this with the rest of the Prism team. The advisory will likely be published before next week.
