### ISSUE TITLE
Command-Line plugin skips end of code block

### ISSUE THREAD

**Issue by borari** [PrismJS/prism#2795]
**Information:**
- Prism version: 1.23.0
- Plugins: line-highlight, command-line, normalize-whitespace, toolbar, copy-to-clipboard
- Environment: Browser

Does the latest version of Prism from the [download page](https://prismjs.com/download.html) also have this issue?
Yes, I am using the latest version of Prism (1.23.0).

**Description**
While using the Command-Line plugin to create code blocks, I am experiencing an issue where some final output lines are not being displayed as a part of the command-line block. They are instead being displayed as what appears to be lines from a regular code block.

It appears that the issue might be due to the alignment of the prompt block, as you can see the alignment of the prompts and final line becoming further offset in the second example below. This tracks with my observation that there does not appear to be a definite line count threshold for triggering this issue, but that the issue is more pronounced in code blocks with higher line counts.

**Example**
Code Block HTML:

```HTML
    <pre class="command-line language-shell" data-output="2-31" data-user="root" data-host="kali">
        <code>
wfuzz -c --hc 200 -z file,&quot;sqli-authbypass.txt&quot; -d &quot;username=FUZZ&amp;password=password123&quot; http://10.10.10.185/login.php 2&gt;&amp;1 | tee -a ./wfuzz-80-sqli-loginphp.txt

Warning: Pycurl is not compiled against Openssl. Wfuzz might not work correctly when fuzzing SSL sites. Check Wfuzz&#x27;s documentation for more information.

********************************************************
* Wfuzz 2.4.5 - The Web Fuzzer                         *
********************************************************

Target: http://10.10.10.185/login.php
Total requests: 191

===================================================================
ID           Response   Lines    Word     Chars       Payload
===================================================================

000000035:   302        117 L    277 W    4221 Ch     &quot;&#x27; or 1=1 -- s&quot;
000000036:   302        117 L    277 W    4221 Ch     &quot;&#x27; or 1=1 # s&quot;
000000038:   302        117 L    277 W    4221 Ch     &quot;&#x27; or 1=1 limit 1 -- s&quot;
000000039:   302        117 L    277 W    4221 Ch     &quot;&#x27; or 1=1 limit 1 # s&quot;
000000072:   302        117 L    277 W    4221 Ch     &quot;admin&#x27; -- s&quot;
000000073:   302        117 L    277 W    4221 Ch     &quot;admin&#x27; # s&quot;
000000075:   302        117 L    277 W    4221 Ch     &quot;admin&#x27; or 1=1 -- s&quot;
000000076:   302        117 L    277 W    4221 Ch     &quot;admin&#x27; or 1=1 # s&quot;
000000078:   302        117 L    277 W    4221 Ch     &quot;admin&#x27; or 1=1 limit 1 -- s&quot;
000000081:   302        117 L    277 W    4221 Ch     &quot;admin&#x27; or &#x27;1&#x27;=&#x27;1&quot;
000000079:   302        117 L    277 W    4221 Ch     &quot;admin&#x27; or 1=1 limit 1 # s&quot;

Total time: 0.500885
Processed Requests: 191
Filtered Requests: 180
Requests/sec.: 381.3248
        </code>
    </pre>
```

Unexpected Display:
<img width="954" alt="image" src="https://user-images.githubusercontent.com/33162660/110363236-4d523f80-8010-11eb-8399-f40ec0149d0e.png">

HTML source for multiple input lines in single block:
```HTML
    <pre class="command-line language-shell" data-output="2-3, 5-9, 11-21" data-user="www-data" data-host="ubuntu">
        <code>
/usr/bin/script -qc /bin/bash /dev/null
/usr/bin/script -qc /bin/bash /dev/null

ls -lAh /var/www
ls -lAh /var/www
total 8.0K
drwxr-xr-x 4 www-data www-data 4.0K Mar 17  2020 Magic
drwxr-xr-x 2 root     root     4.0K Dec  3  2019 html

ls -lAh /var/www/Magic
ls -lAh
total 44K
-rwx---r-x 1 www-data www-data  162 Oct 18  2019 .htaccess
drwxrwxr-x 6 www-data www-data 4.0K Jun  6  2019 assets
-rw-r--r-- 1 www-data www-data  881 Oct 16  2019 db.php5
drwxr-xr-x 4 www-data www-data 4.0K Apr 14  2020 images
-rw-rw-r-- 1 www-data www-data 4.5K Oct 22  2019 index.php
-rw-r--r-- 1 www-data www-data 5.5K Oct 22  2019 login.php
-rw-r--r-- 1 www-data www-data   72 Oct 18  2019 logout.php
-rw-r--r-- 1 www-data www-data 4.5K Oct 22  2019 upload.php
        </code>
    </pre>
```

Misaligned Display:
<img width="954" alt="image" src="https://user-images.githubusercontent.com/33162660/110366751-b0de6c00-8014-11eb-9120-96d960aa090f.png">

**Comment by borari** [comment]
This issue seems to be linked to [Issue #1132](https://github.com/PrismJS/prism/issues/1132). I was able to fix the examples above by adding 'display: block' to the 'pre[class*="language-"]' block in my prism.js file.

Expected display w/ single input line:
<img width="954" alt="image" src="https://user-images.githubusercontent.com/33162660/110369600-9f975e80-8018-11eb-97e0-c0074265ed45.png">

Expected display w/ multiple input lines:
<img width="954" alt="image" src="https://user-images.githubusercontent.com/33162660/110369660-b6d64c00-8018-11eb-82d0-abe987572890.png">

**Comment by RunDevelopment** [comment]
The issue is most likely the spaces between the `<pre>` and `<code>` elements and the newline after the opening `<code>` tag. Could you please try the following:

```html
<pre class="command-line language-shell" data-output="2-3, 5-9, 11-21" data-user="www-data" data-host="ubuntu"><code>/usr/bin/script -qc /bin/bash /dev/null
/usr/bin/script -qc /bin/bash /dev/null

ls -lAh /var/www
ls -lAh /var/www
total 8.0K
drwxr-xr-x 4 www-data www-data 4.0K Mar 17  2020 Magic
drwxr-xr-x 2 root     root     4.0K Dec  3  2019 html

ls -lAh /var/www/Magic
ls -lAh
total 44K
-rwx---r-x 1 www-data www-data  162 Oct 18  2019 .htaccess
drwxrwxr-x 6 www-data www-data 4.0K Jun  6  2019 assets
-rw-r--r-- 1 www-data www-data  881 Oct 16  2019 db.php5
drwxr-xr-x 4 www-data www-data 4.0K Apr 14  2020 images
-rw-rw-r-- 1 www-data www-data 4.5K Oct 22  2019 index.php
-rw-r--r-- 1 www-data www-data 5.5K Oct 22  2019 login.php
-rw-r--r-- 1 www-data www-data   72 Oct 18  2019 logout.php
-rw-r--r-- 1 www-data www-data 4.5K Oct 22  2019 upload.php
</code></pre>
```

> This issue seems to be linked to Issue #1132.

I don't this being related.

**Comment by RunDevelopment** [comment]
I investigated this a bit more and it seems like my initial guess was wrong. In fact, I cannot reproduce this issue at all.

([Example project](https://github.com/PrismJS/prism/files/6115038/Example.zip).)

My new guess is that your custom theme somehow interferes with the Command line plugin. Please provide a simple example project that reproduces your issue.

**Comment by RunDevelopment** [comment]
Closed because of inactivity.
