### ISSUE TITLE
New language request for Bicep

### ISSUE THREAD

**Issue by johnnyreilly** [PrismJS/prism#2816]
**Language**

[Bicep](https://github.com/Azure/bicep) is a Domain Specific Language (DSL) for deploying Azure resources declaratively. It aims to drastically simplify the authoring experience with a cleaner syntax, improved type safety, and better support for modularity and code re-use. Bicep is a transparent abstraction over ARM and ARM templates

**Additional resources**

- Bicep repo in GitHub - https://github.com/Azure/bicep
- Bicep Playground - https://bicepdemo.z22.web.core.windows.net/

Realised I needed it as I was [writing this blog post](https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/28)!

**Comment by danielmackay** [comment]
Would love to see support for bicep also.

**Comment by johnnyreilly** [comment]
This may be useful: https://github.com/Azure/bicep/blob/main/src/textmate/bicep.tmlanguage

**Comment by RunDevelopment** [comment]
Added in #3027.
