### ISSUE TITLE
Keywords should be colored as methods, when used as methods.

### ISSUE THREAD

**Issue by Danon** [PrismJS/prism#2817]
**Information**
- Language: PHP
- Plugins: none

**Description**

In PHP there are keywords, which can't be used as class names or variable names, but they can be used as method names.

For example, `match` and `foreach` are keywords, but they can be used as `$var->match()` and `$var->forEach()` methods. 

For example GitHub and PhpStorm colors this code corectly.

**Code snippet**

[Test page](https://prismjs.com/test.html#language=php&text=%24variable-%3Eforeach()%3B%20%2F%2F%20this%20%22foreach%22%20is%20a%20method%0A%24variable-%3Emethod()%3B%20%20%2F%2F%20this%20is%20also%20a%20method%0A%0Aforeach%20(%24list%20as%20%24value)%20%7B%20%2F%2F%20this%20%22foreach%22%20is%20a%20keyword%0A%7D)

<details>
<summary>The code being highlighted incorrectly.</summary>

```php
$variable->foreach(); // this "foreach" is a method
$variable->method();  // this is also a method

foreach ($list as $value) { // this "foreach" is a keyword
}
```

</details>

**Comment by RunDevelopment** [comment]
Is this the case for __all__ keywords? I.e. can there also be a method:

```php
$variable->if();
```

**Comment by Danon** [comment]
Yes, it can. I believe it's any keyword.

Here's a source: https://www.php.net/manual/en/reserved.keywords.php

> As of PHP 7.0.0 these keywords are allowed as property, constant, and method names of classes, interfaces and traits, except that class may not be used as constant name.

**Comment by Danon** [comment]
The reason behind it is, I believe, since forever you can call any method in PHP, if you monkey-patch/magic-call it.

```php
class A {
  function __call() {}
}

$a = new A();
$a->if(); // it's allowed to call a magic method with keyword since forever in PHP
```

But only since PHP7.0, you can declare it.
```php
class A {
  function if() {}  // error before 7.0, allowed now
}
```
