### ISSUE TITLE
Support to decorators in TypeScript

### ISSUE THREAD

**Issue by lacolaco** [PrismJS/prism#2819]
**Motivation**
I'd like to highlight my code relating [Angular](https://angular.io). Angular uses `@Decorators` often like below:

```ts
@Component({
  selector: 'my-app',
  template: `<div>Hello World!</div>`
})
export class AppComponent {}
```

A decorator is technically a function, but I want to separate its color from normal functions.

Currently, decorators are tokenized as `function` in `language-typescript`

![image](https://user-images.githubusercontent.com/1529180/111899808-12b9bf80-8a72-11eb-9ae8-28a8f0be46f1.png)

**Description**

Adding `.meta`-like class to decorator name token.

**Comment by lacolaco** [comment]
In addition, an object in the decorator is not tokenized correctly. As the below image, `template` and `changeDetection` are property names but not tokenized.

![image](https://user-images.githubusercontent.com/1529180/111899919-ebafbd80-8a72-11eb-8515-45f256626ead.png)

**Comment by RunDevelopment** [comment]
With #2820, decorators will have a dedicated `.decorator` class.

> an object in the decorator is not tokenized correctly

The syntax is too similar to type annotations. We will not able to distinguish between the two correctly. Sorry, but that isn't possible to implement with Prism.
