### ISSUE TITLE
Current Prism version breaks "Copy to Clipboard Button" when used in iFrame without permission "clipboard-write"

### ISSUE THREAD

**Issue by janjonas** [PrismJS/prism#2824]
**Information:**
- Prism version: Current
- Plugins: Copy to Clipboard Button
- Environment: Chrome (in iFrame)

**Description**
After updating to a new version of Prism by using the downloader from https://prismjs.com/download.html the "Copy to Clipboard Button" functionality is broken. The copy button worked with an older version of Prism (1.22.0) that was downloaded some time ago from the same URL.
IMHO, this has to do with the changes in #2784 as this replaces the copy to clipboard logic. The current code only tests if "navigator.clipboard" exists and if yes, it uses navigator.clipboard.writeText() but this could result in the following error if the iFrame does not have the right permissions:

`Uncaught (in promise) DOMException: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.`

In the old implementation https://clipboardjs.com/ was used which seems to either does not rely on navigator.clipboard.writeText() or check if the API is not blocked.

**Comment by superhuai** [comment]
11111111111111111111111111111111
11111111111111111111111111111111

**Comment by RunDevelopment** [comment]
What do you think is the correct fix here? [Clipboard.js only uses the `execCommand` API](https://github.com/zenorocha/clipboard.js/blob/734d36b6ffe3346304904a44f12e4f3f69330101/dist/clipboard.js#L182) but it's [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand). `clipboard.writeText` requires permissions in Chromium but the Permissions API seems to be [experimental](https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query) right now.

Should we try to request permission or should we just use `execCommand` and hope that browsers still support it? Or something else?
