### ISSUE TITLE
the after-higthligth callback doesn't run

### ISSUE THREAD

**Issue by huyinghuan** [PrismJS/prism#283]
I use the prism-line-number plugin on prism.but i find it does not run after call ``` Prism.highlight```

and I do a test just like
```
Prism.hooks.add("after-highlight",function(){console.log("Prism after-hight is runing!!")})
Prism.highlight("public class A{}",Prism.languages.java)
```
and nothing console.

How can i  get a html string after call  ``` Prism.highlight``` and use prism-line-number plugin? 

My English is so bad ,I hope I have described the problem clearly. thank you !

**Comment by loganfranken** [comment]
Based on @thadin's suggestion and @zeitgeist87's working example, it looks like this can be closed.
