### ISSUE TITLE
React, using script file token & rest errors w/ added Prism script file

### ISSUE THREAD

**Issue by AveryTheDev** [PrismJS/prism#2830]
I downloaded a Prism js file from the website with the added language of "rego" to use for syntax highlighting. I'm getting the following errors when I attempt to use a script file downloaded from the site.

<img width="697" alt="Screen Shot 2021-03-25 at 10 53 34 AM" src="https://user-images.githubusercontent.com/23192489/112493328-7127bc00-8d58-11eb-844a-34db79afd002.png">

Here is a [codesandbox](https://codesandbox.io/s/trusting-solomon-kqk0u?file=/src/App.js) to reproduce the issue. This occurs whether I use the minified or development version. These errors are all coming from the script file.

**Comment by AveryTheDev** [comment]
<img width="422" alt="Screen Shot 2021-03-25 at 11 19 58 AM" src="https://user-images.githubusercontent.com/23192489/112497483-0bd5ca00-8d5c-11eb-9571-055d7ebd2c9a.png">

Some reason it says prism, but its pointing to the html file. I thought this might help

**Comment by RunDevelopment** [comment]
[Here](https://codesandbox.io/s/focused-snow-ftpjb) is a fixed version.

I don't know why but you imported Prism from npm instead of using the download file. This probably wasn't the cause for the syntax error but it's wrong either way. 

My best guess as to why the syntax error occurs is that `useScript` causes it. No idea how or why tho.

**Comment by AveryTheDev** [comment]
<img width="1257" alt="Screen Shot 2021-03-25 at 12 03 49 PM" src="https://user-images.githubusercontent.com/23192489/112504466-3165d200-8d62-11eb-9886-a16f5c918c4a.png">

In the code sandbox that works but when I try that locally I get the following errors

**Comment by mAAdhaTTah** [comment]
That's ESLint complaining. You can either update your config to ignore those rules or use `//eslint-disable` comments to hide the complaints.

**Comment by AveryTheDev** [comment]
Thank you I figured that out a little before you commented. Sorry about the trouble
