### ISSUE TITLE
Misinterpretation of PHP string interpolation

### ISSUE THREAD

**Issue by Danon** [PrismJS/prism#2856]
**Information:**
- Prism version:  latest from the download page
- Plugins: none

**Description**

- The code:
  ![image](https://user-images.githubusercontent.com/13367735/114601971-63e65900-9c96-11eb-9f98-5afc1dda69e8.png)
- How Prism.js highlights it:
  ![image](https://user-images.githubusercontent.com/13367735/114602077-7f516400-9c96-11eb-92d9-9621c44ce523.png)
- How it should highlight it:
  ![image](https://user-images.githubusercontent.com/13367735/114602205-a019b980-9c96-11eb-9f4e-7ef5d35a6916.png)

**Example**
https://prismjs.com/test.html#language=php&text=%3C%3Fphp%0A%0A%24value%20%3D%20%22%24this-%3Eproperty-%3Eproperty%22%3B%0A

**Comment by Danon** [comment]
To see, that it infact is the correct interpretation, see the example I've fashioned for you:

![image](https://user-images.githubusercontent.com/13367735/114604731-8ded4a80-9c99-11eb-9e25-5c50150dd18a.png)

You can see that PhpStorm also highlights just the first level.

**Comment by mAAdhaTTah** [comment]
Define "correct". To my mind, Prism is highlighting all of the properties consistently, the same way PHPStorm does when not wrapped in a string. Why would wrapping in a string trigger different highlighting? I'd argue PHPStorm's approach is worse, tbh.

**Comment by Danon** [comment]
> Define "correct". 

"Correct" would be how language (PHP) compiles and runs it. And PHP only runs the first level of properties, when in string interpolation. PHP simply ignores the remaining levels, and treats them as if they were just characters.

**Comment by mAAdhaTTah** [comment]
lol gawd.

Alright, I agree with you, just not with PHP :D. Dunno how complicated this will be to implement correctly with regex but I'll leave that to the experts.
