### ISSUE TITLE
Add language support for MJML

### ISSUE THREAD

**Issue by DylanBourdere** [PrismJS/prism#2857]
**Language**
MJML is a markup language designed to reduce the pain of coding a responsive email.

**Additional resources**
https://documentation.mjml.io/

**Comment by RunDevelopment** [comment]
> MJML is a markup language

This means that one can use Prism's Markup language to highlight it. The MJML doc itself uses an HTML syntax highlighter to highlight code.

I don't think we need to expcitly add support for MJML because Prism already supports any markup language.
