### ISSUE TITLE
Prism toolbar

### ISSUE THREAD

**Issue by vdecree** [PrismJS/prism#286]
Hi there,

Does prism still use prism toolbar plugin so that you can easily get the 'copy to clipboard' button to appear? I've been trying but it doesn't seem to work.

Regards
M

**Comment by geoffreymcgill** [comment]
The following `Copy to Clipboard` sample should be helpful to anyone wanting to implement this functionality within their Prism code sample.

https://gist.github.com/geoffreymcgill/d118939d1d358d2ed5e8

This sample is adapted from a sample originally posted by [Philip Lawrence](http://dev.misterphilip.com/prism/plugins/toolbar/).

Hope this helps.

**Comment by vkbansal** [comment]
@geoffreymcgill Thanks for the link! I was working on something similar. 

@LeaVerou Will it make sense to have a plugin that depends on third party tools in the official repo?

**Comment by LeaVerou** [comment]
Sure, that’s what plugins are for. (of course it’s always better to not depend on 3rd party tools, but we’re not going to reinvent the wheel for no reason — we reinvent the wheel only when it results in shorter/more elegant code :) ).

**Comment by mAAdhaTTah** [comment]
I'm definitely in need of that, @vkbansal; was going to look at tackling it myself but probably not for a while.

**Comment by vkbansal** [comment]
@mAAdhaTTah can you tell what features are commonly required in a toolbar?

**Comment by mAAdhaTTah** [comment]
I mostly need "copy to clipboard," but leaving it open for hooking into would also be great, as I also will need to add an edit button that will take you to the backend (if possible).

**Comment by LeaVerou** [comment]
Is this still only solvable with Flash or does the Clipboard API support this now?

**Comment by Golmote** [comment]
AFAIK, still only Flash. And ZeroClipboard (used in the above example) is the reference for this.

**Comment by santo007** [comment]
@Golmote @mAAdhaTTah @vkbansal <br/>Get the plugin from the public repository i have created <a href="https://github.com/santo007/prism-toolbar">Prism-toolbar</a>

**Comment by vkbansal** [comment]
@santo007 nice!

**Comment by uranusjr** [comment]
For this particular use-case only *copy to clipboard* is needed, and surprisingly (at least to me) support for it [seems pretty decent](http://caniuse.com/#feat=clipboard). It’s mostly only unsupported on mobile browsers, so maybe a Flash-free solution is reasonable?

**Comment by Golmote** [comment]
@uranusjr I'm still pretty sure we can't use it to make a "Copy to clipboard" button, but please show me I'm wrong.

**Comment by uranusjr** [comment]
Yes, you’re right, I misread the support description. Sorry for the mess-up.

**Comment by loganfranken** [comment]
While there is some discussion above of an extensive toolbar, it looks like this issue is mostly about the "Copy to Clipboard" feature: this is also discussed in #280.

I think this a cool feature to pursue, but maybe we should close either this issue or #280 to simplify things?

**Comment by Golmote** [comment]
Alright, let's recap.

For the plugin by Philip Lawrence, see http://dev.misterphilip.com/prism/plugins/toolbar/.
For the repo created by santo007, see https://github.com/santo007/prism-toolbar.
For the "Copy to Clipboard" feature request, see #280.
