### ISSUE TITLE
System horizontall scroll in <pre> tags

### ISSUE THREAD

**Issue by nightadmin** [PrismJS/prism#2876]
**Information**
- Language: python and others
- Plugins: none

**Description**
Prism, when highlighting wide code, exposes a horizontal scrollbar to the user without css design, which looks very ugly. This can be seen in the simple code, the link to the site is left. I ask you to stylize this scroll or at least remove it, as it is very unpleasant to see this in the documentation for the project.

**Code snippet**

[Test page](http://night-admin.byethost16.com/doc/koshka/assets/plugins/prism/test.html)

<details>
<summary>The code being highlighted incorrectly.</summary>

```python
test = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
print(test)
```

</details>

**Comment by RunDevelopment** [comment]
> exposes a horizontal scrollbar to the user without css design

That's the default for HTML `pre` elements. If you want to wrap your code instead, set `white-space: pre-wrap;` for `pre` elements.

Keep in mind that the line wrapping implemented by the browser doesn't look that good. However, implementing smart line wrapping is very difficult, see #2202.
