### ISSUE TITLE
[Log] prism-log.js does not exist in the npm module

### ISSUE THREAD

**Issue by matthewkwong2** [PrismJS/prism#2928]
**Information:**
- Prism version: 1.23.0
- Plugins: N/A
- Environment: Node

**Description**
The title is pretty much self-explanatory. Yes, I have doubled check the files and I even removed the entire `/node_modules` and reinstall it. The file is indeed missing.
The full error message is:
```
Module not found: Can't resolve 'prismjs/components/prism-log' in _<some path>_
```

**Comment by RunDevelopment** [comment]
It's not missing, just not released yet... See #2913.

**Comment by matthewkwong2** [comment]
> It's not missing, just not released yet... See #2913.

So the only way to use the Log syntax highlight is to pull from Github?

Also, if it is unreleased, perhaps it is better NOT to document it or give a sidenote in the documentation until it is released.

**Comment by RunDevelopment** [comment]
> So the only way to use the Log syntax highlight is to pull from Github?

Yes, and no. Pulling from Github is one way to get it. Another is to [download it directly from our website](https://prismjs.com/download.html#themes=prism&languages=log#:~:text=Log%20file).

That's why we document it even though it's not released on npm yet.
