### ISSUE TITLE
Language component makes my page freeze for 20 sec

### ISSUE THREAD

**Issue by chjoergensen** [PrismJS/prism#2954]
I am running a Ruby on Rails app which uses Webpack, but Prism is not loaded through it.

I have an issue with the browser freezing during syntax highlighting.

1. My page loads `prism-core` and `prism-autoloader` from a CDN:

```html
<head>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/components/prism-core.min.js'></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/plugins/autoloader/prism-autoloader.min.js'></script>
  <link href='https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/themes/prism-okaidia.min.css' rel='stylesheet'>
</head>
```

2. A `pre` and `code` element is in the body.

```html
<body>
  <pre><code class="language-json">{"foo": "bar"}</code></pre>
</body>
```

3. I visit my page in a browser. The entire page freezes for about 20 sec, after which the syntax highlighting happens.

4. I now execute `Prism.highlightAll();` in my Google Chrome browser console. This, again, causes the page to freeze for about 20 sec, after which `undefined` is returned by the function. Since highlighting was already applied, nothing visible happens.

5. I now add the following:

```html
<script>
  window.Prism = window.Prism || {};
  window.Prism.manual = true;
</script>
```

6. I reload the page while refreshing the cache. The `code` element is now unstyled (not even a black background), but no freeze. When I run the `Prism.highlightAll();` the generic styling (white text on black background) happens in immediately, and the function return `undefined` right away. But then the freeze kicks in and only 20 secs later the JSON syntax highlighting happens.

- Removing the `pre` and `code` elements turns the page back to normal.
- Switching internet connection seems to have no effect.
- I am unable to reproduce the issue on [jsFiddle](https://jsfiddle.net/gvdo0xmh/).
- Removing the `prism-autoloader` plugin and adding the `prism-json` plugin instead does not change anything. Removing both of them does bring the page back to normal (now with generic styling).

Any help would be much appreciated.

**Comment by RunDevelopment** [comment]
Strange. The text is too short to be a problem, so it's likely some DOM issue. Could you [profile](https://developers.google.com/web/updates/2016/12/devtools-javascript-cpu-profile-migration) the highlighting process, so we get some more information?

**Comment by chjoergensen** [comment]
Your hint towards the text length was very useful. I had replaced the original and very long text with sample code before submitting this issue. Seems this caused the freeze. It may be possible to get more out of this profiling tool, but the most useful I could derive from it was the summary:

```
39 ms  Loading
25597 ms  Scripting
1585 ms  Rendering
29 ms  Painting
172 ms  System
297455 ms  Idle
324878 ms  Total
```

I played around some more, and found an approach that does not cause a freeze, even with the long version text.

```html
<div class="json-pre-container">
  <div class="json-source" style="display: none;">{"long": "text"}</div>
  <pre><code></code></pre>
</div>

<script>
  $(document).on('turbo:load', function() {
    $(".json-pre-container").each(function() {
      var pre_code = $(this).find("pre code");
      var json_source = $(this).find(".json-source").html();
      var source_json = JSON.stringify(JSON.parse(json_source), undefined, 2);
      pre_code.addClass("language-json").html(source_json);
      pre_code.html(source_json);
    });

    return Prism.highlightAll();
  })
</script>
```

Not sure why it helps, or if it's good practice.

**Comment by chjoergensen** [comment]
He, seems it didn't fix it after all. For a while it did. I've been there a few times.

**Comment by RunDevelopment** [comment]
Could you share the profile itself? Please save the profile (see image below) and attach the file to your comment.

![image](https://user-images.githubusercontent.com/20878432/122238266-4add6c80-cec0-11eb-8957-a4f371dcb0fd.png)

**Comment by chjoergensen** [comment]
Seems the file can not be attached. Instead I've made it available [here](dropbox.com/s/2z8wk5zvlurlvqx/Profile-20210616T212538.json?dl=1).

The setup while profiling was as described in the steps 1-2 in the original issue description.

**Comment by RunDevelopment** [comment]
Let me guess: the JSON you highlight has a string like this: `"\"\"\"\"\"\"\"\"...\"\"\""`. 

I now know the problem. I'll fix it.

**Comment by RunDevelopment** [comment]
My apologies, the issue (#2689) has already been fixed and will be released in the next version.

**Comment by chjoergensen** [comment]
Awesome man. And yes you are  absolutely right, the JSON has a key/value pair, where the value is the source code of a website, e.g.:

```json
{"key": "<!DOCTYPE HTML> <!--[if lt IE 7]><html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"lv-lv\"><![endif]--> <!--[if IE 7]><html class=\"no-js lt-ie9 lt-ie8 ie7\" lang=\"lv-lv\"><![endif]--> <!--[if IE 8]><html class=\"no-js lt-ie9 ie8\" lang=\"lv-lv\"><![endif]--> <!--[if gt IE 8]><html class=\"no-js ie9\" lang=\"lv-lv\"><![endif]--><html lang=\"lv-lv\" class=\"menu-effect\"><head><meta charset=\"utf-8\" /><title>..."}
```

Lots of escaped quotes.
