### ISSUE TITLE
Release v1.24.0

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#2963]
@LeaVerou @Golmote @mAAdhaTTah 

We hadn't had a release in 6 months.

The original plan was to let v1.24.0 be the last v1.x version of Prism. However, we hadn't had the time to work on v2.0 yet, so let's revise the plan a little. Let's release v1.24.0 right now (not literally) and make v1.25.0 the last v1.x version.

We had multiple occasions over the last months where people ask when the next version will be released. I was hoping to release v1.24.0 by the end of the week. I believe we can release Prism almost as-is. I only want one current PR to be part of v1.24.0 (see milestone).

Thoughts?

**Comment by LeaVerou** [comment]
I'm fine with that.

**Comment by RunDevelopment** [comment]
Just released v1.24.0.
