### ISSUE TITLE
Keyword "from" is not a valid keyword in some languages

### ISSUE THREAD

**Issue by mrcrow85** [PrismJS/prism#2968]
**Information:**
- Prism version: latest from the CDN.
- Plugins: none
- Environment: Browser

**Description**
Prism incorrectly highlights the "from" word as a keyword in some languages which are not supposed to be highlighted. An example of this is Javascript and C#.

Although in C# is kinda tricky since it is a keyword when using a from-in clause:
```cs
func(from: "America", to: "Asia"); // Prism incorrectly highlights "from" as a keyword

from element in list; // no issues here
```

**Example**
[JSFiddle](https://jsfiddle.net/30shef45/1/)

**Comment by RunDevelopment** [comment]
**JavaScript:**

`from` is a keyword in JavaScript and Prism highlights it as such.

![image](https://user-images.githubusercontent.com/20878432/123506382-2aea3d80-d664-11eb-8c2b-be65928de871.png)
([source](https://prismjs.com/test.html#language=javascript&text=import%20*%20from%20%22mod.js%22%3B%0A%0Avar%20from%20%3D%20%22foo%22%3B%0Afrom.toString()%3B%0Afoo(from%2C%20from%20%2B%20from)%3B))

We use a little trick to only highlight the `from` in imports as a keyword: `from(?=\s*(?:['"]|$))`. The `from` *keyword* is guaranteed to be preceded by a string literal, so our regex checks for that.

**C#:**

As you said, this is tricky. Prism's regex-based highlighting approach is not powerful enough to detect whether `from` is used as a keyword inside a LINQ query or as a regular identifier elsewhere.

However, I think we could use a similar trick as for JS. The `from` keyword is guaranteed to be preceded by [either a type or an identifier](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#query-expressions). I'll make a PR for this trick.
