### ISSUE TITLE
Unable to run in node when using markdown

### ISSUE THREAD

**Issue by Mister-Hope** [PrismJS/prism#2973]
See https://github.com/PrismJS/prism/commit/2b355c98720b7c4f697200d666ddfdcfc3350dbe#diff-12f505384949e8ade50a6337e923bbe2ac037b951fb003617889a165758b4d3c

This commit and other commit include `document`, then it makes prism unable to run under node environment.

This is absolutly a breaking change in prismjs, and should be consider as a bug.

**Comment by RunDevelopment** [comment]
Thanks for the report @Mister-Hope! Will fix asap

**Comment by ongweiloon777** [comment]
l

**Comment by ongweiloon777** [comment]
[https://github.com/atom-material/atom-material-syntax/issues/46#issue-190180050]() #2975
