### ISSUE TITLE
Sass class selectors use inline-color plugin

### ISSUE THREAD

**Issue by benAnima** [PrismJS/prism#2992]
**Information**
- Language: Sass
- Plugins: inline-color

**Description**
When prism renders Sass using `inline-color` plugin, if a class selector has a color name, the inline color preview is displayed.

**Code snippet**
[Test page](https://prismjs.com/test.html#language=sass&text=.lucidagrande-normal-black-14px%20%0A%20%20color%3A%20var(--black)%0A%20%20font-family%3A%20var(--font-family-lucidagrande)%0A%20%20font-size%3A%20var(--font-size-m)) - though it doesn't display usage of plugins.

![image](https://user-images.githubusercontent.com/63534334/125194082-64bc6600-e258-11eb-9655-e538c4d7daba.png)

```
.lucidagrande-normal-
black-14px 
  color: var(--black)
  font-family: var(--font-family-lucidagrande)
  font-size: var(--font-size-m)
```

**Expected behavior**
Class names / any other selector should not use inline-color plugin.

**Comment by RunDevelopment** [comment]
The Inline color plugin simply uses the tokenization provided by Sass. This is a bug with Sass. I'll fix it.

**Comment by benAnima** [comment]
Thanks for your quick response and help!
