### ISSUE TITLE
Diff Highlighting Marking HTML Tags as Line Deletions

### ISSUE THREAD

**Issue by karlhorky** [PrismJS/prism#3015]
**Information:**

- Prism version: Test drive version
- Plugins: 'none'
- Environment: Test drive

**Description**

Hey @RunDevelopment 👋 (if you triage 🙂) Hope you're well!

Prism marks line 2 in the code below as a deleted line in the `diff` language:

```diff
Not in HTML element
<p>Inside HTML element - incorrectly (?) marked as deleted</p>
-<p>Inside HTML element - correctly marked as deleted</p>
```

<img width="698" alt="Screen Shot 2021-07-29 at 14 40 58" src="https://user-images.githubusercontent.com/1935696/127493761-caca3dd1-c2d5-4e59-890d-67482597741e.png">

GitHub doesn't mark it as a deletion (see above).

However, I suppose this could be something that I'm unaware of about diff highlighting - maybe an angle bracket symbol means deletion in some context?

**Example**

https://prismjs.com/test.html#language=diff

**Comment by karlhorky** [comment]
**Workaround:** add a space at the beginning of the line:

```diff
Not in HTML element
 <p>Inside HTML element - incorrectly (?) marked as deleted</p>
-<p>Inside HTML element - correctly marked as deleted</p>
```

<img width="725" alt="Screen Shot 2021-07-29 at 14 46 22" src="https://user-images.githubusercontent.com/1935696/127494296-6d9078a0-dfa1-4230-bb08-8f63facf2bfb.png">

**Comment by RunDevelopment** [comment]
Hi!

> maybe an angle bracket symbol means deletion in some context?

Exactly that. I was also confused by the `<` and `>` when I first looked at Prism's Diff language definition. This is used by a diff format (but I don't remember which one...), so Prism supports it.

> Workaround: add a space at the beginning of the line:

That's not a workaround, you just fixed the diff. The [unified diff format](https://en.wikipedia.org/wiki/Diff) requires unchanged lines to start with a single space. This is to avoid ambiguity (e.g. the diff of a markdown file might contain unchanged lines starting with `-` (lists)).

All lines that don't start with a `[ +-!<>@]` are syntactically invalid AFAIK. 

> GitHub doesn't mark it as a deletion

Seems like GitHub doesn't support the `<>` diff format and just ignores all lines it doesn't understand (we do the same thing), hence no highlighting.

**Comment by karlhorky** [comment]
Wow, super fast and very deep explanation, thanks!!
