### ISSUE TITLE
Uncaught TypeError: Cannot set property 'class-name' of undefined

### ISSUE THREAD

**Issue by ats1999** [PrismJS/prism#3029]
**Information**
- Language: cpp,javascript,jsx
- Plugins: none

**Description**
I am using prismjs to highlight the code, it works for c, java, python, etc. But as i import `import "prismjs/components/prism-cpp.js";` it gives me the error.

<details>
<summary>Error</summary>

```js
ypeError: Cannot set property 'class-name' of undefined
extend
node_modules/prismjs/prism.js:306
  303 | var lang = _.util.clone(_.languages[id]);
  304 | 
  305 | for (var key in redef) {
> 306 | 	lang[key] = redef[key];
      | ^  307 | }
  308 | 
  309 | return lang;
```

</details>

**Comment by RunDevelopment** [comment]
Prism's languages have dependencies. E.g. C++ depends on Prism's C language definition. Please don't import individual language files yourself. Use either [Autoloader](https://prismjs.com/#basic-usage-cdn), [`loadLanguages`](https://prismjs.com/#basic-usage-node), or [our Babel plugin](https://prismjs.com/#basic-usage-bundlers) instead.
