### ISSUE TITLE
JS Highlighting: `'/*'` in string disrupts comment highlighting

### ISSUE THREAD

**Issue by Josh-Cena** [PrismJS/prism#3032]
**Information:**
- Prism version: 1.23.0
- Plugins: none
- Environment: Node (built with [`prism-react-renderer`](https://github.com/FormidableLabs/prism-react-renderer))

**Description**
When a string contains `/*` (which is common in configurations with glob matching), only the directly next line comment directive gets properly highlighted.

If a block comment is inserted somewhere, however, the subsequent line comments are parsed correctly again.

**Example**

![image](https://user-images.githubusercontent.com/55398995/128971154-eafa68ae-378c-40a6-b08d-d73a6064d08b.png)

(I am using the vscode-dark theme provided by `prism-react-renderer`)

**Comment by RunDevelopment** [comment]
This has [been fixed](https://github.com/PrismJS/prism/pull/2680) in 1.24.0. ([live demo](https://prismjs.com/test.html#language=javascript&text=%2F%2F%20Good%20comment%0A%2F%2F%20Good%20comment%0Aconst%20a%20%3D%20'%2F*'%3B%0A%2F%2F%20Still%20good%0A%2F%2F%20Not%20correctly%20parsed!%20(keyword%20like%20return)%0Aconst%20b%20%3D%20true%3B%0A%2F%2F%20Still%20bad%20comment%0A%2F*%20Some%20block%20comment%20*%2F%0Aconst%20c%20%3D%201%3A%0A%2F%2F%20I%20am%20good%20again%0A))

![image](https://user-images.githubusercontent.com/20878432/129015417-1a4137d1-a964-4ab3-8604-02380709992b.png)

**Comment by Josh-Cena** [comment]
Thanks. Turns out it's just that `prism-react-renderer` hasn't bumped its dependencies since two months ago...
