### ISSUE TITLE
Webpack worker not working

### ISSUE THREAD

**Issue by elpaxel** [PrismJS/prism#3034]
**Information:**
- Prism version: latest
- Plugins: none
- Environment: Webpack

**Description**
So basically `highlightElement(el, true, function(){})` is failing to run due to WebPack. Error is "document is not defined" but it seems that WebPack just can't find worker script as it is referring itself.

**Comment by RunDevelopment** [comment]
Could you please tell me the specific line that throws the error?

I _think_ this is a problem with Prism Core itself but it could also be something else.

**Comment by elpaxel** [comment]
Sorry but I can't. WebPack creates a bundle and all I can see that WebPack thows error when loading chunks.

webpack.config.js

    var path = require("path");

    module.exports = {
      cache: false,
      mode: "production",
      entry: {
        index: "./src/index.js"
      },
      output: {
        path: path.resolve(__dirname, "dist"),
        filename: "[name].js"
      },
      module: {
        rules: [
          {
            test: /\.js$/,
            exclude: /node_modules/,
            use: {
              loader: "babel-loader",
              options: {
                presets: ["@babel/preset-env"],
                plugins: ["@babel/plugin-transform-runtime"]
              }
            }
          },
          {
            test: /\.css$/,
            use: ["style-loader", "css-loader"]
          }
        ]
      },
      devServer: {
        writeToDisk: true
      }
    };

index.js

    import Prism from "prismjs/components/prism-core";
    import "prismjs/components/prism-renpy";
    import "prismjs/themes/prism.css";
    import "prismjs/plugins/line-numbers/prism-line-numbers";
    import "prismjs/plugins/line-numbers/prism-line-numbers.css";

    Prism.highlightElement(code, true, function(){
        ...
    });

command

    npx webpack serve

**Comment by RunDevelopment** [comment]
I don't think this is a problem with Prism itself (anymore). Prism also works on NodeJS where `document` isn't available so it's unlikely that Prism is causing the error. This might be some interaction between Prism and some of the other stuff it is bundled with.

I have 4 questions:

1. Is the problem still present when the `line-numbers` imports are removed?
2. Is the problem still present with `Prism.highlightElement(code, false, ...)`?
2. Is the problem still present if you don't call `Prism.highlightElement` at all?
4. Since you didn't know where exactly the error was coming from, what indicated that Prism was the cause?

**Comment by elpaxel** [comment]
1. Yes.
2. No.
3. No.
4. The problem exists only with "true" switch. And I assumed that webpack can't see the worker file. Because as I can see in core.js worker file is coming from error stack or something. In WebPack 5 they using `new Worker(new URL('./worker.js', import.meta.url));` and in core.js there is nowhere near `import.meta.url`. And yes sorry for my eng ;)

**Comment by RunDevelopment** [comment]
Prism async highlighting works by using [the same file](https://github.com/PrismJS/prism/blob/5126d1e118f42e14ff1608e7328c91278f5732d2/components/prism-core.js#L1129) the Prism instance is from [as the worker](https://github.com/PrismJS/prism/blob/5126d1e118f42e14ff1608e7328c91278f5732d2/components/prism-core.js#L1108). 

My guess is that the webpack bundle where Prism is in also contains some other stuff and that stuff then causes the error when used as a worker.

> I assumed that webpack can't see the worker file

In that case, you would get some error from the Worker API and not some generic "document is not defined" error.

> Because as I can see in core.js worker file is coming from error stack or something.

The error stack is just a workaround for IE11.  `currentScript()` is pretty much equivalent to `typeof document === 'undefined' ? null : document.currentScript`.

> all I can see that WebPack thows error when loading chunks.

So you can see the error in your browser dev tools, right? Could you share a screenshot of the error + stack trace from there?

**Comment by elpaxel** [comment]
> Prism async highlighting works by using the same file the Prism instance is from as the worker.

And that is the problem no ? Because now `_.filename` in `var worker = new Worker(_.filename);` is "index.js". So after bundling prismjs trying to start worker with "index.js" instead of "core.js".

![image](https://user-images.githubusercontent.com/45597512/129374764-02ebfb57-e44b-4a8a-aa9d-2dbd83589e13.png)

![image](https://user-images.githubusercontent.com/45597512/129375416-569a960c-1326-4a11-bac9-77d631c10a52.png)

**Comment by mAAdhaTTah** [comment]
As an aside, @RunDevelopment we'll want to revisit/remove the async highlighting in V2 cuz I don't think it plays nice with bundlers in general.

**Comment by RunDevelopment** [comment]
@mAAdhaTTah I agree. It also doesn't work with Autoloader or NodeJS. It also causes problems for some plugins IIRC.

**Comment by RunDevelopment** [comment]
> And that is the problem no ? Because now `_.filename` in `var worker = new Worker(_.filename);` is "index.js". So after bundling prismjs trying to start worker with "index.js" instead of "core.js".

Yes, that is the problem. 

Even using `prism-core.js` as the worker wouldn't be correct. `prism-core` doesn't include any languages, so it wouldn't be able to do any highlighting.

From what I see, Prism's web worker implementation assumes that you use a bundle from our download page. Seems like you won't be able to use web workers in combination with webpack. Sorry.

**Comment by elpaxel** [comment]
Ok. Thanks you for your time. I guess I can wrap prismjs with lang in custom worker then.
