### ISSUE TITLE
Next.js - Highlight Keywords plugin doesn't highlight "if" and "return" keywords correctly (Okaidia theme)

### ISSUE THREAD

**Issue by AlexTechNoir** [PrismJS/prism#3044]
**Information**
- Language: JavaScript
- Plugins: line-numbers, line-highlight, autolinker, highlight-keywords, inline-color, previewers, data-uri-highlight, copy-to-clipboard

prismjs - ^1.24.1
babel-plugin-prismjs - ^1.2.0

**Description**

Good day! 

I code on Next.js and data's loaded from HCMS with CKEditor. I installed `prismjs` and `babel-plugin-prismjs` packages, set up a config with "Okaidia" theme and plugins listed above. All chosen plugins work correctly except "Highlight Keywords". Official example shows "if" and "return" keywords as red, but I have them blue. JS code's been copied from official examples on website.

**.babelrc:**
```
...
    ["prismjs", {
      "languages": ["javascript", "css", "markup", "bash", "git", "graphql", "gitignore", "json", "jsx", "regex" ],
      "plugins": [
        "line-numbers", 
        "line-highlight", 
        "autolinker", 
        "highlight-keywords", 
        "inline-color", 
        "previewers", 
        "data-uri-highlight",
        "copy-to-clipboard"
      ],
      "theme": "okaidia",
      "css": true
    }]
...
```

![0](https://user-images.githubusercontent.com/43852391/130670413-f3ade4d6-4d88-40c4-b5aa-835e0ebe4037.jpg)

**Code snippet**

[Test page](https://prismjs.com/test.html#language=javascript&text=%3Cp%20class%3D%22hey%22%3EType%20some%20code%20here%3C%2Fp%3E%0A%2F**%0A%20*%20Prism%3A%20Lightweight%2C%20robust%2C%20elegant%20syntax%20highlighting%0A%20*%20MIT%20license%20http%3A%2F%2Fwww.opensource.org%2Flicenses%2Fmit-license.php%2F%0A%20*%20%40author%20Lea%20Verou%20http%3A%2F%2Flea.verou.me%0A%20*%20Reach%20Lea%20at%20fake%40email.com%20(no%2C%20not%20really)%0A%20*%20And%20this%20is%20a%20Markdown%20link.%20Sweet%2C%20huh%3F%0A%20*%2F%0Avar%20foo%20%3D%205%3B%0A%2F%2F%20And%20a%20single%20line%20comment%20http%3A%2F%2Fgoogle.com%0A%0Afunction%20do()%20%7B%0A%09const%20something%20%3D%201%0A%09return%20something%0A%7D%0A%0Ado()%0A%0A(function%20()%20%7B%0A%0A%09if%20(typeof%20Prism%20%3D%3D%3D%20'undefined')%20%7B%0A%09%09return%3B%0A%09%7D%0A%0A%09Prism.hooks.add('wrap'%2C%20function%20(env)%20%7B%0A%09%09if%20(env.type%20!%3D%3D%20'keyword')%20%7B%0A%09%09%09return%3B%0A%09%09%7D%0A%09%09env.classes.push('keyword-'%20%2B%20env.content)%3B%0A%09%7D)%3B%0A%0A%7D())%3B)

<details>
<summary>The code being highlighted incorrectly.</summary>

```
/**
 * Prism: Lightweight, robust, elegant syntax highlighting
 * MIT license http://www.opensource.org/licenses/mit-license.php/
 * @author Lea Verou http://lea.verou.me
 * Reach Lea at fake@email.com (no, not really)
 * And this is a Markdown link. Sweet, huh?
 */
var foo = 5;
// And a single line comment http://google.com

function do() {
	const something = 1
	return something
}

do()

(function () {

	if (typeof Prism === 'undefined') {
		return;
	}

	Prism.hooks.add('wrap', function (env) {
		if (env.type !== 'keyword') {
			return;
		}
		env.classes.push('keyword-' + env.content);
	});

}());
```

</details>

**Comment by RunDevelopment** [comment]
> Official example shows "if" and "return" keywords as red, but I have them blue.

The [plugin page](https://prismjs.com/plugins/highlight-keywords/) has an extra line of CSS that adds the red highlighting.

```css
	/*
	 * Custom keyword styles
	 */
	.token.keyword.keyword-return, .token.keyword.keyword-if{
		color: #f92672;
	}
```

Your keywords are blue because that's the color your chosen theme set. All Highlight Keywords is adding the `keyword-<text>` class for each keyword (e.g. `keyword-if` for `if`).

So the Highlight Keywords plugin is working as intended but I do see that the documentation needs some work. I opened #3046 for this.
