### ISSUE TITLE
Lines falsely identified as commands in shell session

### ISSUE THREAD

**Issue by sunknudsen** [PrismJS/prism#3047]
**Information**
- Language: Shell session
- Plugins: none

**Description**

`#` lines are falsely identified as commands.

Only lines that start with `$` (in following example) should be considered commands.

Here are [a](https://sunknudsen.com/privacy-guides/how-to-install-tails-on-usb-flash-drive-or-sd-card-on-macos#step-7-copy-tails-to-usb-flash-drive-or-sd-card) [few](https://sunknudsen.com/privacy-guides/how-to-generate-and-air-gap-pgp-private-keys-using-gnupg-tails-and-yubikey#step-16-rename-veracrypt-encrypted-volume) [examples](https://sunknudsen.com/privacy-guides/how-to-generate-and-air-gap-pgp-private-keys-using-gnupg-tails-and-yubikey#step-5-insert-yubikey-and-import-private-key-stubs) in production (each highlighted word is a separate link).

Issue is likely related to https://github.com/PrismJS/prism/issues/2644.

Thanks for helping out!

**Code snippet**

[Test page](https://prismjs.com/test.html#language=shell-session&text=%24%20diskutil%20list%0A%2Fdev%2Fdisk0%20(internal%2C%20physical)%3A%0A%20%20%20%23%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20TYPE%20NAME%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20SIZE%20%20%20%20%20%20%20IDENTIFIER%0A%20%20%200%3A%20%20%20%20%20%20GUID_partition_scheme%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20*500.3%20GB%20%20%20disk0%0A%20%20%201%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20EFI%20EFI%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20209.7%20MB%20%20%20disk0s1%0A%20%20%202%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Apple_APFS%20Container%20disk1%20%20%20%20%20%20%20%20%20500.1%20GB%20%20%20disk0s2%0A%0A%2Fdev%2Fdisk1%20(synthesized)%3A%0A%20%20%20%23%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20TYPE%20NAME%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20SIZE%20%20%20%20%20%20%20IDENTIFIER%0A%20%20%200%3A%20%20%20%20%20%20APFS%20Container%20Scheme%20-%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2B500.1%20GB%20%20%20disk1%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Physical%20Store%20disk0s2%0A%20%20%201%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20APFS%20Volume%20Macintosh%20HD%20-%20Data%20%20%20%20%20340.9%20GB%20%20%20disk1s1%0A%20%20%202%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20APFS%20Volume%20Preboot%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2085.9%20MB%20%20%20%20disk1s2%0A%20%20%203%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20APFS%20Volume%20Recovery%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20529.0%20MB%20%20%20disk1s3%0A%20%20%204%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20APFS%20Volume%20VM%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%203.2%20GB%20%20%20%20%20disk1s4%0A%20%20%205%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20APFS%20Volume%20Macintosh%20HD%20%20%20%20%20%20%20%20%20%20%20%2011.3%20GB%20%20%20%20disk1s5%0A%0A%2Fdev%2Fdisk2%20(internal%2C%20physical)%3A%0A%20%20%20%23%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20TYPE%20NAME%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20SIZE%20%20%20%20%20%20%20IDENTIFIER%0A%20%20%200%3A%20%20%20%20%20FDisk_partition_scheme%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20*15.9%20GB%20%20%20%20disk2%0A%20%20%201%3A%20%20%20%20%20%20%20%20%20%20%20%20%20Windows_FAT_32%20boot%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20268.4%20MB%20%20%20disk2s1%0A%20%20%202%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Linux%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2015.7%20GB%20%20%20%20disk2s2%0A%0A%24%20sudo%20diskutil%20unmount%20%2Fdev%2Fdiskn%0Adisk2%20was%20already%20unmounted%20or%20it%20has%20a%20partitioning%20scheme%20so%20use%20%22diskutil%20unmountDisk%22%20instead%0A%0A%24%20sudo%20diskutil%20unmountDisk%20%2Fdev%2Fdiskn%20(if%20previous%20step%20fails)%0AUnmount%20of%20all%20volumes%20on%20disk2%20was%20successful%0A%0A%24%20sudo%20dd%20bs%3D1m%20if%3D%24HOME%2FDownloads%2Ftails-amd64-4.18.img%20of%3D%2Fdev%2Frdiskn%0A1131%2B0%20records%20in%0A1131%2B0%20records%20out%0A1185939456%20bytes%20transferred%20in%2044.708618%20secs%20(26525970%20bytes%2Fsec)%0A%0A%24%20sudo%20diskutil%20unmountDisk%20%2Fdev%2Fdiskn%0AUnmount%20of%20all%20volumes%20on%20disk2%20was%20successful)

<details>
<summary>#: lines are falsely identified as commands</summary>

```
$ diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.3 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                 Apple_APFS Container disk1         500.1 GB   disk0s2

/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +500.1 GB   disk1
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh HD - Data     340.9 GB   disk1s1
   2:                APFS Volume Preboot                 85.9 MB    disk1s2
   3:                APFS Volume Recovery                529.0 MB   disk1s3
   4:                APFS Volume VM                      3.2 GB     disk1s4
   5:                APFS Volume Macintosh HD            11.3 GB    disk1s5

/dev/disk2 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *15.9 GB    disk2
   1:             Windows_FAT_32 boot                    268.4 MB   disk2s1
   2:                      Linux                         15.7 GB    disk2s2

$ sudo diskutil unmount /dev/diskn
disk2 was already unmounted or it has a partitioning scheme so use "diskutil unmountDisk" instead

$ sudo diskutil unmountDisk /dev/diskn (if previous step fails)
Unmount of all volumes on disk2 was successful

$ sudo dd bs=1m if=$HOME/Downloads/tails-amd64-4.18.img of=/dev/rdiskn
1131+0 records in
1131+0 records out
1185939456 bytes transferred in 44.708618 secs (26525970 bytes/sec)

$ sudo diskutil unmountDisk /dev/diskn
Unmount of all volumes on disk2 was successful
```

</details>

**Comment by RunDevelopment** [comment]
Commands starting with `#` are a feature, not a bug.

The problem is that there is some ambiguity here. I'll make a PR fixing that.

**Comment by sunknudsen** [comment]
> Commands starting with # are a feature, not a bug.

👍

> The problem is that there is some ambiguity here. I'll make a PR fixing that.

Thanks so much for helping out. 🙌
