### ISSUE TITLE
MAXScript Support

### ISSUE THREAD

**Issue by I-d-as** [PrismJS/prism#3059]
**Language**
MAXScript scripting language for 3ds Max. 
**Additional resources**
https://help.autodesk.com/view/MAXDEV/2022/ENU/

**Comment by I-d-as** [comment]
Hello @RunDevelopment

I hope life is good. I will preface all of this by making it clear that I know you are doing much more important things. But in the situation where you have a moment to reply, I would greatly appreciate it!

First I just wanted to thank you so much for your work getting MAXScript as a supported language!  Today was my first chance to see your work in action, with the new release of Obsidian Mobile. I attached a screenshot from my vault. This app uses Prismjs for syntax highlighting. I am using blue topaz as a theme which appears to show more of the syntax highlighting than the default theme and some of the other themes. For reference, I also attached a screenshot from the documentation for MAXScript showing that same content. I noticed that many of the methods that are highlighted in the documentation are not highlighted in Obsidian. I guess my question is how can I test the MAXScript syntax highlighting out in its pure implementation so that I can figure out whether it is an issue with Obsidian, the css theme, etc. 

I want to again say how much I appreciate what you have done and love the way this is working. But, if those methods are supposed to be highlighted and if there is some way I could tweak the css so that all of the syntax highlighting comes through, I will be the first to dig deep and figure it out because this means a lot to me since I am building a clone of the MAXScript documentation within Obsidian. In the meantime, thanks once more!  I can’t wait for the next release of the desktop version of Obsidian so I can hopefully see the code in all its beautiful colors! Honestly for all I know, the mobile version may just be a work in progress implementation of the updated version of Prismjs, which may explain the discrepancy. 

Anyways, sorry for the long read. Keep up the great work!!!!  👍👍

![6F2F44F1-8390-4111-A141-3B1588EFDB27](https://user-images.githubusercontent.com/84299559/140845040-2c93440f-974b-4cb5-94b5-7c41fa60de49.png)
![31542D19-85D3-43EC-B05F-83B2DD8A7C60](https://user-images.githubusercontent.com/84299559/140845045-552d015f-77bf-4d51-a498-a47de839ca8d.png)

**Comment by RunDevelopment** [comment]
Hi @I-d-as!

> how can I test the MAXScript syntax highlighting out in its pure implementation

You can check the raw output of Prism [here](https://prismjs.com/test.html#language=maxscript). Check the "Show tokens" box to see everything Prism produces regardless of the current theme.

> I noticed that many of the methods that are highlighted in the documentation are not highlighted

Yes, that's because I couldn't find a good way to detect methods, so they aren't highlighted. The function call syntax for MAXScript is quite complex, so I didn't bother reading the reference regarding this topic.

That being said, since there is demand for better highlighting, I'll give it another go.
