### ISSUE TITLE
Language Request: GN

### ISSUE THREAD

**Issue by thunder-coding** [PrismJS/prism#3061]
**Language**
GN is a meta-build system that generates build files for Ninja

**Additional resources**
https://gn.googlesource.com/gn/

GN has some language definition and syntax files for vim and Emacs which might be really helpful for the person working on this

**Comment by RunDevelopment** [comment]
Question: The docs link [Chromium as an example](https://source.chromium.org/chromium/chromium/src/+/master:build/config/BUILDCONFIG.gn) and I can see a bunch of `.gni` files next to the linked `.gn` file. Are `.gni` and `.gn` files related?

**Comment by thunder-coding** [comment]
> By convention, imported files are named with a .gni extension.

So both `.gn` and `.gni` can be treated as GN files!

From https://gn.googlesource.com/gn/+/refs/heads/main/docs/reference.md#func_import
