### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [PrismJS/prism#3069]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by RunDevelopment** [comment]
Hello!

I apologize for the missing security policy. I will get in touch with the other maintainers to set up a contact point for security-related issues. Truthfully, we already have an issue about this (#2642), so I will close this issue as a duplicate.

In the meantime, you can contact me on my private email (see my profile info).
