### ISSUE TITLE
Cant select different themes for different post

### ISSUE THREAD

**Issue by catchsrinivas** [PrismJS/prism#3072]
**Information:**
- Prism version: [latest from the download page, etc.]
- Plugins: [codesyntax]
- Environment: [Browser]

**Description**
There is a bug as I cannot use different themes for different posts. The theme changes globally and also only 1 theme is compitablr for highlighting. If I use other dark themes highlighting will stop as shown below. You can see how bad it will show up if I use dark themes in Wordpress site

![image](https://user-images.githubusercontent.com/9750273/132971833-bd6fa051-0363-4763-80bf-1faf40000aee.png)

**Example**
Currently I have changed it to light theme and modify css manually and itseems working reference site [Itsmycode](https://itsmycode.com/), where you can check by modifying styles.

**Comment by RunDevelopment** [comment]
Prism only supports one theme per page at one time. 

If you want to have 2 code blocks with different themes on the same page **at the same time**, then you have to use iframes, scoped styles, or a shadow DOM.

If you want to implement something like a light-mode-dark-mode switch, then the easiest solution is to remove the `<link>`/`<style>` of the unwanted theme and add the wanted theme.

> If I use other dark themes highlighting will stop as shown below.

It seems like you are having 2 themes loaded at the same time. Prism does not support this.

I think this is a problem with your site's setup and not with Prism.

**Comment by catchsrinivas** [comment]
Ok let me give it a try, I will add the custom styles to my theme and see if I can override the default behaviour and make it work.

**Comment by RunDevelopment** [comment]
Since there haven't been any follow-up questions, I'll assume the issue has been resolved.
