### ISSUE TITLE
Code appears on top of Previewers popup when Twilight theme is used

### ISSUE THREAD

**Issue by hoonweiting** [PrismJS/prism#3074]
**Information:**
- Prism version: Current deployment on prismjs.com
- Plugins: Previewers
- Environment: Browser? I guess? But I think it's anywhere Previewers is used with Twilight. You can see it on https://prismjs.com/plugins/previewers/

**Description**
Using the Previewers plugin with the Twilight theme selected results in the code hovering on top of the preview popup (screenshot below). I have not really extensively tested this, I was just playing around on the Prism website and happened to notice it. Of the default themes, this only happens with the Twilight theme, the others are fine.

**Example**
![image](https://user-images.githubusercontent.com/59229084/133074774-7fa13589-0f38-4572-9217-4e5336c10b43.png)

**Resolution**
I opened DevTools and changed the `z-index` of `.token` to `0`, and the problem was resolved.

https://github.com/PrismJS/prism/blob/d216e602f38e3ff9acec69962b40ada07322e076/themes/prism-twilight.css#L155-L159

![image](https://user-images.githubusercontent.com/59229084/133076520-64b0ccfa-8017-4e6e-91ba-727a7dcba010.png)

Of course, seeing the note that the tokens were purposely assigned a `z-index` of `1` probably means that we shouldn't resolve it by simply changing it to `0`. We can probably set a `z-index` for the popup instead, but I'm not sure what implications it would have down the line, especially for users who assign `z-index` to other things on their site.

I can help to resolve this, but I do want to be sure, because I've been lurking a bit and have seen a lot of mention of "backwards compatibility" and "breaking change" and a possible Prism V2 in future.

Cheers!

**Comment by RunDevelopment** [comment]
Thank you for reporting this.

> I can help to resolve this

Thank you! I think the best way to fix this is to make sure that the popup is above the code. Giving the popup a `z-index: 10` or similar when active should be enough. This gives themes a bit of room to do interesting stuff with `z-index`.

> "backwards compatibility" and "breaking change"

I think fixing this little bug should be ok. Making sure that the Previewers popup is actually visible shouldn't cause anyone problems.
