### ISSUE TITLE
SQL Tick marks not highlighting as a string

### ISSUE THREAD

**Issue by TheColorRed** [PrismJS/prism#3140]
**Information**
- Language: SQL, MySQL
- Plugins: none

![image](https://user-images.githubusercontent.com/1571806/136258553-ac75e2f4-39da-4c7a-97e0-5e63fa19e0f1.png)

**Description**

When using <code>`</code> marks to surround a keyword, the word should be formatted as a string.

Adding a tick to this fixes the issue:

```javascript
Prism.languages.sql = {
	'string': {
		pattern: /(^|[^@\\])("|'|`)(?:\\[\s\S]|(?!\2)[^\\]|\2\2)*\2/,
		greedy: true,
		lookbehind: true
	},
}
```

<details>
<summary>The code being highlighted incorrectly.</summary>

```mysql
select
   `t`.`col1`, `t`.`col2`, `t`.`col3`, `t`.`col4` 
from
   `test_table` as `t`
```

</details>

**Comment by RunDevelopment** [comment]
I'm not sure whether string is the correct token here. Aren't used as identifiers? Can you use backticks and double-quoted strings interchangeably?

**Comment by TheColorRed** [comment]
In mysql, no they can not.

The following code:
```mysql
select * from 'Test'
```

Produces the following output:

>ERROR 1064 (42000) at line 7: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''Test'' at line 1
