### ISSUE TITLE
Highlighting requests

### ISSUE THREAD

**Issue by tjbenton** [PrismJS/prism#315]
In SCSS and CSS can you add the ability to target the following individually.
 - Color values.
 - Additional class for selectors to determine the difference between ids, elements, classes, and special selectors such as input[type="input"]
 - Ability to highlight numbers in values, as well as keywords like `auto`, `inherit`, and all the other keywords. 
 - Support for interpolation `#{$i}` within selectors, properties, and values. 
 - Ability to target the `&` selector in sass is very important because it helps you distinguish the nested selectors from the other selectors.

**Comment by Golmote** [comment]
Most of the request in original message have been included:
* hex colors are handled by CSS Extras component
* ids, classes and attributes in selectors are handled by CSS Extras component
* numbers are highlighted ; keywords are not and won't be
* interpolation is highlighted in selectors, properties and values in SCSS
* parent selector & is highlighted in SCSS

If I missed something, please create a new issue. I'm closing this one.
