### ISSUE TITLE
ARM Assembly Language

### ISSUE THREAD

**Issue by Gerlesh** [PrismJS/prism#3200]
**Language**
ARM Assembly language is use for low level programming on ARM CPUs (most common for desktop + server processors). Honestly kind of surprised that this hasn't already been requested, if it is already included under another name please let me know. (not the same as wasm, asmatmel, or asm6502)

**Additional resources**
[Documentation](https://developer.arm.com/documentation/dui0473/c/writing-arm-assembly-language)

**Comment by LunarLambda** [comment]
Would also love this. Do a lot of embedded development.

highlight.js supports it, and it works pretty well https://github.com/highlightjs/highlight.js/blob/main/src/languages/armasm.js
