### ISSUE TITLE
Line number plugin not working when the last line has no value

### ISSUE THREAD

**Issue by Shank78** [PrismJS/prism#3201]
**Information:**
- Prism version: 1.25.0
- Plugins: [prism-line-numbers]
- Environment: [Node]

**Description**
Last line number is not displaying,  If there is no values on last line.

**Example**
An example which reproduces the bug. This can be a link to a website - https://codepen.io/shank78/pen/yLowwev

**Comment by RunDevelopment** [comment]
There must not be any spaces between opening/closing `<pre>` and `<code>` tags.

This is incorrect:
```html
<pre class="line-numbers">
<code class="language-javascript">var a =10;
var b = 15;
</code>
</pre>
```

This is how it should be:
```html
<pre class="line-numbers"><code class="language-javascript">var a =10;
var b = 15;
</code></pre>
```

Hope this helps @Shank78.

**Comment by Shank78** [comment]
Thanks for quick response. In my case if I enter in the below example URL line no 3 is not showing, once started typing or when it has some value, the line number will be displayed.
Example URL - https://codesandbox.io/s/intelligent-field-96t6o

**Comment by RunDevelopment** [comment]
Your example isn't working for me so I don't know what you're seeing but I can guess. The `<pre>` element has the interesting property that it won't display the last line of text if that line is empty. That's in the HTML standard, it's not something Prism does. That's pretty much your problem, right?

Example: The following code blocks will both display the exact same text (with our without PrismJS):

```html
<pre><code>foo
bar</code></foo>

<pre><code>foo
bar
</code></foo>
```
[See it live here](https://jsfiddle.net/58tye71r/).

The "fix" is to add an additional new line to the code before you display it. So:

```jsx
        <pre id="highlighting" aria-hidden="true" className="line-numbers">
          <code className="language-javascript" id="highlighting-content">
            {code + "\n"}
          </code>
        </pre>
```

**Comment by Shank78** [comment]
Yes. In my case is editor so if I adding "\n" always it will be a extra line and my expectation is need to display the last line number from prism line number if the last line is empty. I saw your example(https://jsfiddle.net/58tye71r/) here also the pre tag is showing empty if there is no value(highlighted as yellow color). The same thing I am expecting. Can we do from prism js with prism line number plugin.
![image](https://user-images.githubusercontent.com/94745370/142748419-c2c4e430-039b-46b8-ba55-5be8e274ed2c.png)

The below hook is working but one issue it is not considering the line height like if we have more rows for 1 line
Modified Example URL - [https://codesandbox.io/s/intelligent-field-96t6o]
First line code : let id = document.getElementByid("main-header-id")
second line code : id.innerHtml("Hello World")

Prism.hooks.add("complete", function (env) {
      // works only for <code> wrapped inside <pre> (not inline)
      var pre = env.element.parentNode;
      var clsReg = /\s*\bline-numbers\b\s*/;
      if (
        !pre ||
        !/pre/i.test(pre.nodeName) ||
        // Abort only if nor the <pre> nor the <code> have the class
        (!clsReg.test(pre.className) && !clsReg.test(env.element.className))
      ) {
        return;
      }

      if (env.element.querySelector(".line-numbers-rows")) {
        // Abort if line numbers already exists
        return;
      }

      if (clsReg.test(env.element.className)) {
        // Remove the class "line-numbers" from the <code>
        env.element.className = env.element.className.replace(clsReg, "");
      }
      if (!clsReg.test(pre.className)) {
        // Add the class "line-numbers" to the <pre>
        pre.className += " line-numbers";
      }

      var linesNum = 1 + env.code.split("\n").length;
      var lineNumbersWrapper;

      var lines = new Array(linesNum);
      lines = lines.join("<span></span>");

      lineNumbersWrapper = document.createElement("span");
      lineNumbersWrapper.className = "line-numbers-rows";
      lineNumbersWrapper.innerHTML = lines;

      if (pre.hasAttribute("data-start")) {
        pre.style.counterReset =
          "linenumber " + (parseInt(pre.getAttribute("data-start"), 10) - 1);
      }

      env.element.appendChild(lineNumbersWrapper);
    });

**Comment by RunDevelopment** [comment]
I'm sorry @Shank78 but I don't understand what you mean.

The empty-line problem is solved by adding an extra `"\n"` (as I said before). Changing [your example](https://codesandbox.io/s/relaxed-dust-lcpx9?file=/src/App.js) does fix the problem.

```diff
@@ -38,7 +38,7 @@
         />
         <pre id="highlighting" aria-hidden="true" className="line-numbers">
           <code className="language-javascript" id="highlighting-content">
-            {code}
+            {code + "\n"}
           </code>
         </pre>
       </div>
```

> can we use the above hooks to add height or any way to achieve?
> Expected like this, Can we achieve this with prism - Sample URL with Prism customization

Sorry, I don't get what you mean. Do want to wrap each line into a `<div>` like [`prism-react-render`](https://github.com/FormidableLabs/prism-react-renderer) (thridparty) does?
