### ISSUE TITLE
Caret not resetting, causing display lag

### ISSUE THREAD

**Issue by e-floran** [PrismJS/prism#3206]
Hello everyone,

**Information :**

- PrismJs version : 1.25.0
- Environment : React
- React version : 17.0.2

**Description :**
When creating a live code editor, with a transparent textarea on top of my Prism colored pre, the caret of my textarea is not "resetting" its blinking cycle when moved with keyboard arrows, unlike the base caret reset in other textareas. Is it somehow due to PrismJs ?
Problem is, when moving multiple times, user needs to wait for the caret to appear again (something like 0.5sec) to have the visual clue of its position.
If I select text in my textarea, using keyboard, everything's going smoothly. Likewise, if I move my cursor with my keyboard arrows and type text instantly, there's no problem neither. It's really just a display issue, due to caret blinking.
My component is built like this : 
```js
import { useState, useEffect } from "react";
import Prism from "prismjs";

export default function EditCode() {
  const [content, setContent] = useState("");

  const handleKeyDown = (e) => {
    let value = content,
      selStartPos = e.currentTarget.selectionStart;

    if (e.key === "Tab") {
      value =
        value.substring(0, selStartPos) +
        " " +
        value.substring(selStartPos, value.length);
      e.currentTarget.selectionStart = selStartPos + 3;
      e.currentTarget.selectionEnd = selStartPos + 4;
      e.preventDefault();

      setContent(value);
    }
  };

  useEffect(() => {
    Prism.highlightAll();
  }, []);

  useEffect(() => {
    Prism.highlightAll();
  }, [content]);
  return (
    <section className="codeGlobalContainer">
      <textarea
        className="codeInput"
        spellCheck="false"
        wrap="off"
        cols="200"
        value={content}
        onChange={(e) => setContent(e.target.value)}
        onKeyDown={(e) => handleKeyDown(e)}
      />
      <pre className="codeOutput">
        <code className={`language-javascript`}>{content}</code>
      </pre>
    </section>
  );
}
```

**Comment by RunDevelopment** [comment]
Hello @e-floran!

> Is it somehow due to PrismJs ?

I don't see how Prism would cause this. 

But to be sure, have you tried disabling the Prism effects? Does the issue still exist even with Prism not doing anything?

**Comment by e-floran** [comment]
I feel dumb for not trying that before. Like you suspected, removing Prism effects didn't change anything. It dissapears only if I remove the pre bloc from underneath my textarea. So I'll search somewhere else I guess !

Thanks @RunDevelopment !
