### ISSUE TITLE
Does autoloader work with URLs?

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#3216]
In the [autoloader docs](https://prismjs.com/plugins/autoloader/) everything is structured around loading local components. But there is no reason not to allow regular URLs as well, is there? That would be very useful for prototyping, and for cases where performance is not that critical.

* If URLs are already allowed, this is merely a documentation issue: it should be mentioned
* If URLs are not allowed, this is a feature request: can they be?

**Comment by RunDevelopment** [comment]
Yes, general URLs are allowed. That's how [Prism's CDN usage](https://prismjs.com/index.html#basic-usage-cdn) works. I'll add a note to Autoloader's doc.
