### ISSUE TITLE
Line numbers alignment problems

### ISSUE THREAD

**Issue by rmzelle** [PrismJS/prism#324]
I'm using Prism with both the Line Highlight and Line Numbers plugins, downloaded a few days ago, and am having several issues with line number alignments.

With Firefox, I get the following alignment:

![image](https://cloud.githubusercontent.com/assets/77951/3882781/7aaa8176-219a-11e4-84ab-79f19d2dee4c.png)

I tried fixing the height of the highlighted number with 

```
    .line-highlight {
    margin-top: 0em;
    }
```

which seemed to do the trick in Firefox:

![image](https://cloud.githubusercontent.com/assets/77951/3882798/beb39ea2-219a-11e4-986c-f999910eecaa.png)

But in Google Chrome, the alignment is wrong no matter what. Without setting "margin-top" to 0em, I get:

![image](https://cloud.githubusercontent.com/assets/77951/3882824/ffe63f06-219a-11e4-9c61-318b98994aea.png)

Setting "margin-top" to 0em lifts the number a little bit, but not enough.

A second issue is that resizing to a smaller window results in line wrapping of the code, but the line numbers don't change to accommodate:

![image](https://cloud.githubusercontent.com/assets/77951/3882892/81ef5aaa-219b-11e4-82a9-d82a893ff1a6.png)

**Comment by Swissa** [comment]
You can add the following css:

pre {
  overflow: auto;
  word-wrap: normal;
  white-space: pre;
}

**Comment by Golmote** [comment]
This should be fixed by #732.
