### ISSUE TITLE
How to properly highlight one-liner (reformat it)

### ISSUE THREAD

**Issue by lukaszlenart** [PrismJS/prism#326]
Quite often we have a XML that doesn't contain any `\n` - isn't properly formatted to be human-readable, ie:
```xml
"<?xml version="1.0" encoding="UTF-8"?><OrderCreate Version="2.0.2"><Header><ThisDocumentIdentifier><DocumentIdentifier>1234567890</DocumentIdentifier></ThisDocumentIdentifier><ThisDocumentDateTime><DateTime DateTimeQualifier="On">22220124T110013Z</DateTime></ThisDocumentDateTime>
```

is there any chance/idea to perform such formatting with Prism?

**Comment by loganfranken** [comment]
Looks like this can be closed now?

**Comment by Golmote** [comment]
I like the idea of a formatter plugin, but I'm not super optimistic about it, since the beautifying will depend on the language used.
Anyway, if anyone ends up with an awesome idea to do it, feel free to submit a PR.
