### ISSUE TITLE
[Feature request] Add code highlighting for String interpolation in Scala 

### ISSUE THREAD

**Issue by jeanmarc** [PrismJS/prism#3284]
I would like to know if it is possible to add highlighting of code that is part of Scala's string interpolation:
```
  val data = lines.map(_.toInt).sliding(2).toList
  println(s"We have ${data.size} pairs")

```
The part between `${` and `}` in a string that starts with `s"` should be highlighted as if it is actual code.

**Comment by jeanmarc** [comment]
Test drive:
![image](https://user-images.githubusercontent.com/2722081/147560232-002880a3-355a-4136-bb33-90601b23f1d2.png)
IntelliJ:
![image](https://user-images.githubusercontent.com/2722081/147560298-f645e813-5798-44c2-bb98-f5eaeff8e9d0.png)

**Comment by RunDevelopment** [comment]
Yes, it's possible. I'll add it next week.

**Comment by jeanmarc** [comment]
That sounds great. Do you know the Scala syntax for string interpolation? The string must be prefixed wits s or f, and then can contain $var and ${expression} parts (plus a formatting suffix in case of an f prefix). More info on https://docs.scala-lang.org/overviews/core/string-interpolation.html
