### ISSUE TITLE
1.26.0 release?

### ISSUE THREAD

**Issue by jamesgpearce** [PrismJS/prism#3290]
The last NPM release was September and there are some new JavaScript improvements (like property handling) that would be great to get without hand-crafting the dependency.

Please could you release v1.26.0 whenever it's convenient? 🙏 @RunDevelopment

Thanks for such an amazing package!

**Comment by RunDevelopment** [comment]
I just finished the changelog for v1.26.0. I'll make a new release after #3292 gets merged.

/cc @mAAdhaTTah

**Comment by RunDevelopment** [comment]
Just published 1.26.0.
