### ISSUE TITLE
Script tag adds ✂prettier:content✂ on save in VSCode

### ISSUE THREAD

**Issue by shinokada** [PrismJS/prism#3322]
**Information:**
- Prism version: [e.g. 1.14, latest from the download page, etc.]: 1.26.0
- Plugins: [a list of plugins you are using or 'none']
- Environment: [e.g. Browser, Node, Webpack]

macOS v 12.2
VSCode 1.64.0

**Description**

When I try to save the following:

```
<script>
  import Prism from "prismjs";
  import "prismjs/themes/prism.css";
  import "prism-themes/themes/prism-duotone-light.css";
  // let language = "html";
</script>
...// more here
 {@html Prism.highlight(
        `
<!DOCTYPE html>
<html lang="en">
<head>
  ...// more here
  </head>
  <body>
   ...//more here
    <script src="https://unpkg.com/flowbite@1.3.2/dist/flowbite.js"></script>
  </body>
</html>
          `,
  Prism.languages["html"]
)}
```

The script part changes:

```
<script src="https://unpkg.com/flowbite@1.3.2/dist/flowbite.js" ✂prettier:content✂="">{}</script>
```

I have disabled Prettier extension, but it still does the same.

<img width="894" alt="image" src="https://user-images.githubusercontent.com/147320/152661097-ee27eb74-f20d-4061-b74c-597c2733ff62.png">

**Comment by RunDevelopment** [comment]
I'm sorry, but I don't see how this is related to Prism at all. Prism simply highlights code and returns a string of HTML source code. Prism will not add or remove any text. Please verify that this is actually a problem with Prism and not with Svelt or any other tooling.

I also want to point you that you are missing a required parameter of [`Prism.highlight`](https://prismjs.com/docs/Prism.html#.highlight).

**Comment by shinokada** [comment]
Thank you for your reply.
In Svelte, I used mdsvex. 
I created a layout called `doc.svelte`.


```
<script>
  import Prism from "prismjs";
  import "prismjs/themes/prism.css";
  import "prism-themes/themes/prism-holi-theme.css";
</script>

<div class="max-w-3xl mx-auto pb-32">
  <div class="container mt-4 flex flex-wrap mx-auto pt-16">
    <slot />
  </div>
</div>
```

In a md file:

```
---
layout: doc
---
.. more here
```

Then it works.
Thanks.
