### ISSUE TITLE
Line highlight: incorrect position with non-100% initial page zoom in Google Chrome

### ISSUE THREAD

**Issue by myfonj** [PrismJS/prism#336]
Steps to reproduce: 
* Open http://prismjs.com/plugins/line-highlight/#examples in Google Chrome
* Zoom page.
* Reload.

Observation:
* Top offsets of line highlights are computed incorrectly, depending on initial zoom factor.

Screenshot:
Google Chrome Version 36.0.1985.143 m with 150% initial zoom:

![line highlight prism plugins - google chrome zoom 150](https://cloud.githubusercontent.com/assets/1761395/3950746/08a22c2e-26cb-11e4-97c4-24383e12eaef.png)

Same with 100% initial zoom (note different lines are highlighted):

![line highlight prism plugins - google chrome zoom 100](https://cloud.githubusercontent.com/assets/1761395/3950747/08a939e2-26cb-11e4-86bd-e4c2c44cf49e.png)

----

Initially spotted at Addy Osmani's http://addyosmani.github.io/prism-js/components/prism-js/demo.html but turned out inherent for prism itself

**Comment by webdev1hcc** [comment]
This seems to be a problem on Google Chrome, but not on Firefox.  It is also a problem on Internet Explorer, but that is not important to me.  However, it is important to me for the line highlighting to work correctly on Google Chrome.  I realize this is not necessarily the fault of Prism, as this line highlighting works correctly on Firefox, but if anyone comes up with a workaround that would be great.

**Comment by Golmote** [comment]
Indeed, this looks like a browser bug (see [here](https://code.google.com/p/chromium/issues/detail?id=277378), [here](https://bugs.webkit.org/show_bug.cgi?id=91091) and [here](https://code.google.com/p/chromium/issues/detail?id=497790))...

**Comment by Golmote** [comment]
I can't reproduce this issue anymore. They must have fixed it somehow.
