### ISSUE TITLE
Clarify what GraphQL formatting you support

### ISSUE THREAD

**Issue by rhetoric101** [PrismJS/prism#3379]
**Motivation**
I see GraphQL listed in your supported languages, but I can't tell if this is the GraphQL SDL language (used to define a GraphQL schema) or the GraphQL query language (used to send a query, e.g. { actor { account() { nrql ... } } }

I would be interested in seeing support for both!

**Comment by RunDevelopment** [comment]
From my understanding, GraphQL (the language itself, not Prism's grammar) is **both** an SDL and query language (similar to SQL). As such, Prism supports both modes. 

I think the first sentence from [GraphQL's docs](https://graphql.org/learn/) also says this:

> GraphQL is a query language for your API, and a server-side runtime for executing queries using a type system you define for your data.

**Comment by mattbaker** [comment]
I think it's kind of fuzzy! The spec does define the grammar for both but you also don't use them together (defining an SDL vs a query are two very different things). 

But if Prisma is accounting for the whole spec (query and schema definition as well) — and I do see references [to](https://github.com/PrismJS/prism/blob/master/tests/languages/graphql/class-name_feature.test) [both](https://github.com/PrismJS/prism/blob/master/tests/languages/graphql/fragment_feature.test) — then we're good to go @rhetoric101 :)
