### ISSUE TITLE
Prism WYSIWYG

### ISSUE THREAD

**Issue by Strandedpirate** [PrismJS/prism#341]
This would be a great project to allow pre-highlighting of code:

Create a page that allows the user to paste their raw code, press a button to get Prism to:
1) escape various characters like less than and greater than
2) tokenize and transform the content as normal
3) allow the end user to manually edit the prism’d code in a WYWIWYG editor to suit their needs and finally the user can copy/paste the pre-prism’d output back into their html page.

![preview](http://i860.photobucket.com/albums/ab161/JoeyBradshaw/jsprism-wysiwyg.png)
Ideas:
- Allow OAuth sign-in through yahoo, gmail, stackechange and other providers in lieu of the traditional user/pass.
- Allow for custom user defined tokens in the WSIWIWYG. The custom tokens don’t have any logic (no regular expressions or anything) behind them they just allow the user to define their name, an optional icon, a foreground and background color, highlight some text, press the button for that custom token, and the editor re-arranges the html to include a new span element with that token name as the class name while highlighting the selection using the defined foreground and background color.
- Allow the end user to have one or more “Prisms” that get saved to a database like how jsfiddle works. Custom tokens should be saved too. Call it jsprism.com.
- Possibly allow custom tokens to be grouped in folders/sub-folders to reduce clutter.

The whole idea is brought about because there are instances were Prism just doesn’t handle mixtures of languages like Asp.Net Razor syntax embedded in JavaScript. I decided to just pre-prism my code for my project, modify it slightly were Prism falls down and then paste the prism’d output directly into the page. I’m essentially NOT running prism on my site for my example code, but I am using the css classes and prism DOM structure to get the same effect.

**Comment by foo123** [comment]
One should use an editor (like codemirror or ace) for that functionality instead of a static synatx highlighter as prism (imo) But then again prism, can be extended to a full live editor

**Comment by Golmote** [comment]
Building a WYSIWYG is not the current purpose of Prism, so I'm closing this issue.

**Comment by LeaVerou** [comment]
FWIW I do have something in the works ;)

**Comment by mAAdhaTTah** [comment]
Do you really?! I'm using Ace as an editor on the back end and would to love an editor that matches the syntax highlighting.

**Comment by LeaVerou** [comment]
Yes, but no promises on when it will be available. I'm doing it as a hack for my talks for now, then will release once it's at a stable stage.

**Comment by LeaVerou** [comment]
For now, you could look at [CodeFlask](https://kazzkiq.github.io/CodeFlask.js/)
