### ISSUE TITLE
Language request: mustache

### ISSUE THREAD

**Issue by andrewnicols** [PrismJS/prism#3414]
**Language**
Logic-less templates for multiple langauges.

**Additional resources**
Official website: https://mustache.github.io/
Language specification: https://mustache.github.io/mustache.5.html

**Comment by mAAdhaTTah** [comment]
We have support for Handlebars, which is a superset of Mustache. You should be able to use that.

**Comment by RunDevelopment** [comment]
Then maybe we should add an alias for Handlebars?
