### ISSUE TITLE
Include documentation for generating prism.js with selected combination like using the download page

### ISSUE THREAD

**Issue by pravi** [PrismJS/prism#3445]
**Information:**
- Prism version: [e.g. 1.14, latest from the download page, etc.]
- Plugins: [a list of plugins you are using or 'none']
- Environment: [e.g. Browser, Node, Webpack]

**Description**
https://viewcomponent.org/ included a version of prism.js with a specific combination of themes, languages and plugins

https://prismjs.com/download.html#themes=prism-tomorrow&languages=markup+clike+erb+haml+markup-templating+ruby&plugins=line-highlight+highlight-keywords+normalize-whitespace 

In debian we would like to build all generated files from source. Please document how to reproduce the bundles created by download page.

**Comment by pravi** [comment]
May be modifying gulpfile.js/paths.js to include only the required components and calling gulp is enough?

**Comment by RunDevelopment** [comment]
> Please document how to reproduce the bundles created by download page.

You can't. This functionality is exclusive to the download page right now.

That being said, v2 will use ESM, so you'll be able to use regular bundlers.
