### ISSUE TITLE
RebeccaPurple is not included in CSS color list

### ISSUE THREAD

**Issue by BartolomeSintes** [PrismJS/prism#3447]
**Information:**
- Prism version: 1.27
- Plugins: none
- Environment: browser

**Description**
RebeccaPurple color is not included in css color list. This color was [included in CSS Color Module Level 4](https://www.w3.org/TR/css-color-4/#valdef-color-rebeccapurple) in 2014. Thisdocument is still a working draft, but this color is supported in [almost all browsers](https://caniuse.com/css-rebeccapurple).
Could/Should this color be included?
Thanking you in advance,
Bartolome Sintes

**Comment by RunDevelopment** [comment]
`rebeccapurple` is literally the only color from that list we don't support, so I think it's okay to add it.

**Comment by BartolomeSintes** [comment]
Thanks!

**Comment by RunDevelopment** [comment]
Let's keep the issue open until #3448 is merged.
