### ISSUE TITLE
New Language Request: Solidity

### ISSUE THREAD

**Issue by anataliocs** [PrismJS/prism#3453]
**Language**
Solidity is an object-oriented, high-level language for implementing smart contracts. Smart contracts are programs which govern the behaviour of accounts within the Ethereum state.

**Additional resources**
[E.g. The official website, documentation or language specification.](https://docs.soliditylang.org/en/v0.8.13/)

**Comment by RunDevelopment** [comment]
We already [support](https://prismjs.com/#supported-languages) this language.

**Comment by anataliocs** [comment]
@RunDevelopment Awesome!  Thanks so much!  🥳 🙇
