### ISSUE TITLE
Language request: WGSL - WebGPU Shading Language

### ISSUE THREAD

**Issue by Dr4gonthree** [PrismJS/prism#3454]
**Language**
WGSL is the Shading language for WebGPU.
WebGPU is a web API for using the GPU.

I created a prism-wgsl.js file which is based on the WGSL Extension for VS Code, but i'm not sure if it works correctly or misses something.

**Additional resources**
W3C Working Draft of WGSL: https://www.w3.org/TR/WGSL/
WebGPU Website: https://web.dev/gpu/
WGSL Extension for VS Code: https://github.com/PolyMeilex/vscode-wgsl
WGSL defintion based on the WGSL extension: https://github.com/Dr4gonthree/prismjs-wgsl-definition

**Comment by RunDevelopment** [comment]
> I created a prism-wgsl.js file which is based on the WGSL Extension for VS Code, but i'm not sure if it works correctly or misses something.

Feel free to make a PR or share it here (user a) so somebody else can make a PR based on it.

**Comment by Dr4gonthree** [comment]
> Feel free to make a PR or share it here (user a) so somebody else can make a PR based on it.

Ok i created a PR for WGSL. Do i have to somehow link it to this issue?

**Comment by RunDevelopment** [comment]
You can use [Github's closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link this issue in your PR description.

**Comment by RunDevelopment** [comment]
Resolved by #3455.
