### ISSUE TITLE
Everything plus the Kitchen Sink

### ISSUE THREAD

**Issue by yankeeinlondon** [PrismJS/prism#3456]
I have found the `loadLanguages()` utility very useful to load in languages "on demand" during build time. This works great but after reading the [Extending Language Definitions](https://prismjs.com/extending.html#language-definitions) section I was hoping I could pass in my own grammars in addition to those which come with the library.

I'm imaging something like this:

```ts
import Prism from 'prismjs'
import loadLanguages from 'prismjs/components/index'
import type { CodeOptions } from '../code-types'

export function getPrismHighlighter(options: CodeOptions) {
  loadLanguages() // loads all languages
  if (options.languageGrammars)
    loadLanguages(options.languageGrammars)

  return Prism.highlight
}
```

> Where `languageGrammars` is a dictionary of `Record<string, Grammar>`

Is something like this possible?

**Comment by RunDevelopment** [comment]
`loadLanguages`'s main job is to resolve dependencies. Prism has a non-trivial dependency system because this project got started before ESM was a thing.

So if your grammars don't have dependencies (or don't need `loadLanguages` to load them), you can just do:
```js
for (const id in options.languageGrammars) {
  Prism.languages[id] = options.languageGrammars[id];
}
```
