### ISSUE TITLE
Line align

### ISSUE THREAD

**Issue by vodkafilm** [PrismJS/prism#3457]
**Information:**
- Prism version: 1.28, latest from the download page
- Plugins: Line Highlight, Line Numbers
- Environment: Browser

**Description**
It's my first ride with Prism, so I do not know if this is by design, if with previous version is correct or not. Aniway, the text is not vertical aligned, the issue is more visible if data-line is set, all seems ok if line-numbers is off..

html snip:
```
<pre data-line="36" class="line-numbers">
<code class="language-js">
```
Tested on Chrome and Firefox.

**Example**
![default](https://user-images.githubusercontent.com/490416/168867595-903794d7-c3b5-4c0e-a3ed-0d5a72d35a4e.png)
![lines](https://user-images.githubusercontent.com/490416/168867755-8b47c066-5f06-4eec-a8d4-5d81ac9950ea.png)
![line](https://user-images.githubusercontent.com/490416/168867787-1344202c-dc76-4268-ad3b-88aa693e7316.png)

**Comment by vodkafilm** [comment]
It's not a whitespace issue (sorry for that, I entered the whitespace by mistake when I copied )

Take a look here: https://prismjs.com/plugins/line-numbers/ the issue is present in home page too.

I think is a theme issue, only `funky` and `coy` have a proper alignment.

**Comment by RunDevelopment** [comment]
> Take a look here: https://prismjs.com/plugins/line-numbers/

This is the most extreme I see:
![image](https://user-images.githubusercontent.com/20878432/168878940-c88f4c1e-a43a-4894-ba1b-9818fc124df9.png)

What I see (literally, I mean the screenshot) is a known issue. Due to the way line numbers are positioned, they are 2~3px too far down. The problem is that we can't fix this right now, because the fix is a breaking change.

**Comment by vodkafilm** [comment]
> This is the most extreme I see:
> ![image](https://user-images.githubusercontent.com/20878432/168878940-c88f4c1e-a43a-4894-ba1b-9818fc124df9.png)

This is not so extreme, but it is annoying:
![Screenshot from 2022-05-17 20-43-07](https://user-images.githubusercontent.com/490416/168887254-de025889-4dbf-4644-912b-b8470a8dab09.png)

For me the numbers are ok, the code line is stick to the top.

The `coy` theme seem to be ok, so I thinks there is something we can do without breaking.
![Screenshot from 2022-05-17 20-42-38](https://user-images.githubusercontent.com/490416/168887238-1aef041b-b1df-46bb-8165-dd1ba28d891c.png)

Just a css trick or something like that.

**Comment by nicodevs** [comment]
@RunDevelopment What would be the fix? Even if it is a breaking change, I would like to apply it in my custom theme.

Thanks!
