### ISSUE TITLE
High CPU load when selecting languages on Prism download page

### ISSUE THREAD

**Issue by GuiTeK** [PrismJS/prism#346]
The more I select languages on [Prism download page](http://prismjs.com/download.html), the more my CPU load increases (see the GIF image below). I have this problem with Google Chrome 36 and Internet Explorer 11. It works flawlessly with Mozilla Firefox 31.
It must be some JavaScript issue with Chrome and IE but I don't know what's exactly causing the problem.

![prismjs_dl](https://cloud.githubusercontent.com/assets/6260786/4021500/2171b7f4-2af6-11e4-8934-9393a0131131.gif)

**Comment by Golmote** [comment]
The optimisation of the regexps in the JavaScript component over the past years seem to have solve this issue. I'm closing it. Please comment if you're still able to reproduce it, so we can reopen.
