### ISSUE TITLE
Error with highlightAllUnder

### ISSUE THREAD

**Issue by gpcottle** [PrismJS/prism#3474]
**Information:**
- Prism version: 1.28
- Plugins: none
- Environment: Visual Studio / Blazor

**Description**
Hello
I am using Prism with Visual Studio and Blazor and liking the output. I already encountered one challenge where the highlighted code is "unrendered" when  the page loads. I found an article for this to add "data-manual" to the JS link and then to call `Prism.highlightAll();` after Blazor has completed the render and this works fine on my public pages.

However, I included an preview on my editor page and called the `highlightAll()` method and it also managed to render the code inside the text editor, which I didn't entirely want as it then changed the entry in the CMS with the rendered version.

I found the `highlightAllUnder` method and have tried to use that. In my page, I have a `<div id='PreviewPost'>` element and want Prism to only render code under that element. There could be multiple code sections of multiple languages in the content. The call I make is  `Prism.highlightAllUnder('PreviewPost');` When this call runs, I get an error on the page with:
```
TypeError: r.container.querySelectorAll is not a function
    at Object.highlightAllUnder (http://localhost:5287/js/prism.js:3:2659)
```

Could you please give me an idea of what I might have missed? Many thanks

**Comment by mAAdhaTTah** [comment]
You need to query the element yourself & pass it in. Passing in a string is not supported.

```js
const el = document.getElementById('PreviewPost');
Prism.highlightAllUnder(el)
```

**Comment by gpcottle** [comment]
Many thanks - this has now solved the challenge I was having
