### ISSUE TITLE
XML & PHP is not rendering correctly.

### ISSUE THREAD

**Issue by StephenMiracle** [PrismJS/prism#3513]
**Information**
- Language: PHP + XML
- Plugins: none

**Description**
I can't get XML to display the elements. It also seems to override the PHP code in the display. I have an if / else statement showing but it only renders the XML tag. The XML not rendering element tags happens throughout page in multiple examples.

**Code snippet**

[sample page]()](https://fuelingphp.com/return-xml-response-in-php/)

<details>
<summary>The code being highlighted incorrectly.</summary>

```
<?php


header("Access-Control-Allow-Origin: *");
header("Content-Type: text/xml; charset=UTF-8");
 
 
if(file_exists('courses.xml')) {
    $courses = file_get_contents('courses.xml');
    echo $courses;
} else {
    echo "<?xml version=\"1.0\"?><Error>404 - File not found!</Error>";
}
   
 
?>
```

</details>

**Comment by RunDevelopment** [comment]
That's because your site's source code is this:

```html
<html>
<body>
<!--StartFragment-->

<pre class="wp-block-code"><code lang="php" class="language-php">
--
  | header(&quot;Access-Control-Allow-Origin: *&quot;);
  | header(&quot;Content-Type: text/xml; charset=UTF-8&quot;);
  |  
  |  
  | if(file_exists(&#x27;courses.xml&#x27;)) {
  | $courses = file_get_contents(&#x27;courses.xml&#x27;);
  | echo $courses;
  | } else {
  | echo &quot;<error>404 - File not found!</error>&quot;;
  | }
  | </code></pre>

<!--EndFragment-->
</body>
</html>
```

Note the syntax highlighting GitHub does. `<error>` is not text, it's an element. Prism strips all elements before highlighting, this is an intended and necessary effect. For more information, see the [basic usage section](https://prismjs.com/#basic-usage) on our website.

**Comment by StephenMiracle** [comment]
THanks for the response, I'm not quite sure that I'm following.
If you scroll down the page, there are pure XML blocks that aren't rendering even though the language type selected is XML.

This content is actually being created from a WP plugin that is using prism. I'd like to reach out to them but could use some guidance on where to direct them.

Are you saying that the XML elements cannot be displayed.. even on the code blocks that are specified as XML? 

Thanks again for assistance.

**Comment by RunDevelopment** [comment]
> there are pure XML blocks that aren't rendering even though the language type selected is XML.

Same problem. This is the HTML of the code block.

```html
<pre class="wp-block-code"><code lang="xml" class="language-xml">&lt; ? xml version=&quot;1.0&quot; ? &gt;
<courses>
    <course id="C-001">
        <title>Fundamentals of Programming</title>
        <credithours>3 + 1</credithours>
        <prerequisites>None</prerequisites>
    </course>
    <course id="C-002">
        <title>Object Oriented Programming</title>
        <credithours>3 + 1</credithours>
        <prerequisites>Fundamentals of Programming</prerequisites>
    </course>
</courses>
</code></pre>
```

Again, all HTML elements inside `<code>` will be removed. 

The reason `&lt; ? xml` is escaped is likely that your CMS (or similar) detected that `< ? xml ...` is not a valid element, and escaped it as text.

To make e.g. the HTML element `<course>` text, it has to be escaped as `&lt;course&gt;`.

> Are you saying that the XML elements cannot be displayed.

Prism can highlight XML code ([example](https://prismjs.com/test.html#language=markup&text=%3Ccourses%3E%0A%20%20%20%20%3Ccourse%20id%3D%22C-001%22%3E%0A%20%20%20%20%20%20%20%20%3Ctitle%3EFundamentals%20of%20Programming%3C%2Ftitle%3E%0A%20%20%20%20%20%20%20%20%3Ccredithours%3E3%20%2B%201%3C%2Fcredithours%3E%0A%20%20%20%20%20%20%20%20%3Cprerequisites%3ENone%3C%2Fprerequisites%3E%0A%20%20%20%20%3C%2Fcourse%3E%0A%20%20%20%20%3Ccourse%20id%3D%22C-002%22%3E%0A%20%20%20%20%20%20%20%20%3Ctitle%3EObject%20Oriented%20Programming%3C%2Ftitle%3E%0A%20%20%20%20%20%20%20%20%3Ccredithours%3E3%20%2B%201%3C%2Fcredithours%3E%0A%20%20%20%20%20%20%20%20%3Cprerequisites%3EFundamentals%20of%20Programming%3C%2Fprerequisites%3E%0A%20%20%20%20%3C%2Fcourse%3E%0A%3C%2Fcourses%3E)), but it will ignore HTML elements. We highlight text and only text. If your XML code is not given as text but as HTML elements, then Prism won't highlight them.

To put it in more technical terms, we use `textContent` to extract text, not `innerHTML`.

One of the reasons no sane syntax highlighter uses `innerHTML` is security. Users would not be able to highlight HTML code containing scripts without those scripts executing.

**Comment by StephenMiracle** [comment]
Awesome. This makes sense. I can get this corrected. Thank you for the explanation.
