### ISSUE TITLE
BQN Support

### ISSUE THREAD

**Issue by yewscion** [PrismJS/prism#3514]
**Language**
[BQN](https://mlochbaum.github.io/BQN/) is a modern, powerful language created by @mlochbaum centered on Ken Iverson's array programming paradigm.

It supports:

- A simple, consistent, and stable array programming language
- A low-dependency C implementation using bytecode compilation: installation
- System functions for math, files, and I/O (including a C FFI)
- Documentation with examples, visuals, explanations, and rationale for features

**Additional resources**
There is a [userscript](https://gist.github.com/dzaima/35ca0ce12b5e215a62460f00e693984f) for highlighting BQN in a browser already written by @dzaima [info](https://aplwiki.com/wiki/Dzaima), who is also the maintainer of the officially-recommended implementation. 

While I'm sure the code in the userscript will need modifying for use in PrismJS, a large part of the work is already therefore done.

Other Links:

[BQN Homepage](https://mlochbaum.github.io/BQN/)
[Official Page Recommending the Above Userscript](https://mlochbaum.github.io/BQN/editors/index.html)

**Comment by RunDevelopment** [comment]
Closed by #3515.
