### ISSUE TITLE
Some lines are not highlighted

### ISSUE THREAD

**Issue by BashkirovN** [PrismJS/prism#3517]
**Information**
- Language: typescript, svelte
- Plugins: Line Highlight

**Description**
I'm using 10-line code slices and wanted to set an offset and highlight certain lines. It works fine until I need to highlight a line number greater than 10, then the line doesn't get highlighted.

For example,
`<pre data-line-offset={6} data-line={'9-12'} ...></pre>`
would highlight lines 9 and 10 but not 11 and 12

<details>
<summary>Line numbers that are greater than the snippet length are not highlighted.</summary>

</details>
<img width="1324" alt="Screen Shot 2022-08-13 at 8 15 23 PM" src="https://user-images.githubusercontent.com/63573283/184520907-e955fad8-a11d-48f4-84f0-c4615aeb9884.png">

**Comment by RunDevelopment** [comment]
Cannot reproduce. It works for [the examples on our website](https://prismjs.com/plugins/line-highlight/#examples).  Could you please provide a minimal example reproducing the issue?

**Comment by BashkirovN** [comment]
I believe it works on your website because the files have more lines. If you try to use a short snippet and the data-line would have a value greater than the number of lines available, it won't work.

Here is a basic project that reproduces the bug:
[bugRepro.zip](https://github.com/PrismJS/prism/files/9334058/bugRepro.zip)

**Comment by RunDevelopment** [comment]
Thank you for the example! I was able to reproduce and fix the bug. I'll make a PR.
