### ISSUE TITLE
next-dev.js?3515:20 Warning: Extra attributes from the server

### ISSUE THREAD

**Issue by sytpb** [PrismJS/prism#3521]
**Information:**

reactJs with next.js 

  "dependencies": {
    "babel-plugin-prismjs": "^2.1.0",
    "next": "12.2.4",
    "prismjs": "^1.28.0",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },

babelrc

    "plugins": [
      [
        "prismjs",
        {
          "languages": ["javascript", "css", "markup"],
          "plugins": ["line-numbers"],
          "theme": "twilight",
          "css": true
        }
      ]
    ]

code as the this blog to setup. 

https://hackernoon.com/using-prismjs-as-a-syntax-highlighter-in-react

**Description**

the result is what want ,but i got a warning . 

![image](https://user-images.githubusercontent.com/12178686/185053602-e9fc90ef-f738-41ab-a973-a55994429a5f.png)

**Example**
An example which reproduces the bug. This can be a link to a website, a [JSFiddle](https://jsfiddle.net/), an attached example project, etc.

**Comment by RunDevelopment** [comment]
Prism directly modifies the DOM, which might cause problems with React SSR. However, that's not a problem with Prism itself.

To get a nice React experience with Prism, I suggest using [`prism-react-renderer`](https://github.com/FormidableLabs/prism-react-renderer).

**Comment by sytpb** [comment]
finally , i got the solution to fix it , as following , code like this in NextJS. 


import dynamic from 'next/dynamic';

const Code = dynamic(() => import("../components/Code"), {
  ssr: false,
});

const wrapper = () => {
  return (
    <div>
      <Code code={JSCode} language="javascript" />
      <Code code={htmlCode} language="html" />
    </div>
  )
};
