### ISSUE TITLE
New project structure

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#3525]
With v2 and ESM, so I also want to make a cleaner project structure.

(Things that I don't explain will be as they are now.)

```sh
.github/
benchmark/
gulpfile.js/
src/
  core/  # this is where everything that makes up Core will live
  languages/  # this will be what is now "components/"
  plugins/  # this contains all plugins (JS+CSS) minus their website
  shared/  # this will contains shared logic between Core, languages, and plugins. "util" might not be the best name.
  components.json
tests/
website/  # will be where everything about the website lives
  assets/
  examples/
  plugins/  # the plugin pages (only the HTML)
  index.html
```

**Comment by JaKXz** [comment]
How about `shared` instead of `util`?

**Comment by binyamin** [comment]
Would it make sense to move the site to a separate repository?
1. If I'm contributing to the website, I'd rather _just_ clone the website.
2. This would cut down on the issue/PR volume.
3. You could give people commit-access to the website without allowing them access to the library. Or vice-versa.

**Comment by RunDevelopment** [comment]
The website includes the generated documentation site of the library as well as library code (demos). Of course, this dependency only goes one way (the library doesn't depend on the website), so it's possible, it just doesn't seem worth the hassle.

**Comment by RunDevelopment** [comment]
This has been implemented in v2.
