### ISSUE TITLE
Change signature of `Prism.highlight{Element,All,AllUnder}`

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#3528]
**Motivation**
Similar to #3416, it would be nice to have all optional arguments of `Prism.highlight{Element,All,AllUnder}` in an options dictionary.

**Description**
So the new signature should be:

(Updated after the below discussion)

```ts
interface HighlightAllOptions {
  root?: Element;
  async?: boolean;
  callback?: (element: Element) => void;
}
function highlightAll(options?: HighlightAllOptions) { ... } 

interface HighlightElementOptions {
  async?: boolean;
  callback?: (element: Element) => void;
}
function highlightElement(element: T, options?: HighlightElementOptions) { ... }
```

Example usage: 
```js
Prism.highlightAll({ root: document.querySelector("#page") })
```

Thoughts? @LeaVerou @Golmote @mAAdhaTTah @JaKXz

**Comment by LeaVerou** [comment]
Yes, agreed with removing `highlightAllUnder()` and making it an option in `highlightAll()`. Wrt naming, I think `container` is more common. Maybe also `root`?

**Comment by JaKXz** [comment]
I think `root` is probably the most ubiquitous / broadly accepted :)

**Comment by RunDevelopment** [comment]
Agreed. `root` sounds good.

**Comment by RunDevelopment** [comment]
Implemented in v2.
