### ISSUE TITLE
highlightElement() not refreshing line-highlighting

### ISSUE THREAD

**Issue by HannesBBR** [PrismJS/prism#356]
Hi,

I'm trying to dynamically change the line that is highlighted (using the line highlight plugin).

What I'm doing is altering the data-line attribute dynamically and then calling the Prism.highlightElement() function to 'refresh' the highlighted source code. The first time I set the data-line attribute dynamically the correct line is highlighted, but when I then 'refresh' the highlighted source code (where now another line should be highlighted) the same line is still highlighted, although the data-line attribute is correctly changed.

Or does the highlightElement function not support the line-highlight plugin?

Thanks!

**Comment by Golmote** [comment]
There is no need to remove the existing line-highlight divs at the beginning of the highlightLines()-function, since the highlighting gets rid of existing markup.

I'm closing this issue.
