### ISSUE TITLE
Syntax highlighting issue with java

### ISSUE THREAD

**Issue by dkanicki** [PrismJS/prism#358]
Using Wordpress prism plugin I get TypeError:
TypeError: pattern.exec is not a function
var match = pattern.exec(str);

The code in not properly highlighted and line numbers don't show up.

In my wordpress post I put:
[prism field=WebMvcConfig language=java class=line-numbers data_line=3]

**Comment by nauzilus** [comment]
I think this can be closed now since #360 is merged.

@dkanicki can you confirm this is fixed?

**Comment by Golmote** [comment]
I consider this fixed.
