### ISSUE TITLE
prettier file missing

### ISSUE THREAD

**Issue by Shubhamsahu19** [PrismJS/prism#3588]
everyone uses prettier code formatter , so everyone has different global prettier configuration, which leads to multiple unnecessary changes in file. So having a local prettierrc and prettierignore can eliminate these unnecessary changes.

**Comment by RunDevelopment** [comment]
> everyone uses prettier code formatter

We don't.

While I also like prettier and use it in all of my project, I don't think that every project must use prettier/be compatible with it. Prettier is just a popular formatter right now. If a different tool gets popular in 2 years from now, must every project add support for that one too? Of course not. 

Assuming that everyone uses your favorite formatter/linter/tool is generally a bad mind set when going into open source. Some people just might not like the tool you love. E.g. prettier is pretty good, but it has a few rough edges, so I can see why people might not want to use it.
