### ISSUE TITLE
Line Breaks Not Working

### ISSUE THREAD

**Issue by Samalander0** [PrismJS/prism#3589]
Using Prism in next.js/react.
![image](https://user-images.githubusercontent.com/51756184/197931859-bf460748-afa0-4ad5-a54c-2369b8adbe96.png)
![image](https://user-images.githubusercontent.com/51756184/197931886-b1c62f79-c964-42ce-b2ba-52695269f92f.png)

Here's my string that I want to be rendered as code: 
![image](https://user-images.githubusercontent.com/51756184/197931932-2a40bc52-3eaf-40ec-b449-2f156c3c347d.png)
Implementation: 
![image](https://user-images.githubusercontent.com/51756184/197931955-de72fbea-f4aa-48d1-9fe0-3839d5a29000.png)

And here's the output:
![image](https://user-images.githubusercontent.com/51756184/197932004-3ce29fc5-7321-4c13-8596-27f2805ebc0e.png)

As you can see, the \n are getting deleted, but the line break isn't line breaking.
How can I make line breaks work?

**Comment by RunDevelopment** [comment]
`<code>foo</code>` is for inline snippets. Use `<pre><code>foo</code></pre>` for code blocks. For more information, see our [basic usage section](https://prismjs.com/#basic-usage).
