### ISSUE TITLE
Cannot read properties of undefined (reading addSupport)

### ISSUE THREAD

**Issue by SamTV12345** [PrismJS/prism#3592]
**Information:**
- Prism version: prismjs 1.29.0
- Plugins: VueLoaderPlugin,StylelintPlugin, Webpack Plugin
- Environment: webpack

**Description**
Clone the repository: https://github.com/SamTV12345/stackedit
If on Windows you need to install besides Python 3.9 and above the Visual Studio Build Tools (C++ for desktop development)
npm install
npm start
Enter the browser localhost:8080
Click on the Start Writing pencil.
Blank page with the error in the console tab of the browser

**Example**
You can find the Stackedit repository here: https://github.com/SamTV12345/stackedit

**Comment by RunDevelopment** [comment]
This error likely has nothing to do with us. Nowhere in our code base do we call an `addSupport` function.

**Comment by c-shubh** [comment]
> Thanks for your info. It just appeared in the stacktrace. https://stackoverflow.com/questions/74252242/uncaught-typeerror-cannot-read-properties-of-undefined-reading-addsupport?noredirect=1#comment131092627_74252242

Hello @SamTV12345, I'm facing the same issue while trying to run stackedit. If you found a workaround / solution, could you post it here?
Thanks!
