### ISSUE TITLE
remove extra new line

### ISSUE THREAD

**Issue by ubuntutest** [PrismJS/prism#3594]
I realized after hundreds of published posts that prism has automatically added a new blank line, when I use the copy key and paste the text in a terminal, the text is automatically pasted and the enter key is triggered, this can lead to several problems .

this is the editor:
![prism-editor](https://user-images.githubusercontent.com/13025037/199131609-13b9ad37-1c23-46a8-a305-5d081a1bc38c.jpg)

this is what I see in the structure of the HTML:
![prism](https://user-images.githubusercontent.com/13025037/199131625-7cb83739-907a-46e5-940a-7849f9c1d65f.jpg)

I can't go and manually edit dozens of lines in hundreds of posts.

Is there a way with prism to delete the new and empty line via javascript?

**Comment by RunDevelopment** [comment]
Could you please provide an example where I can see and test this for myself?

> prism has automatically added a new blank line

We generally don't automatically add new lines.

**Comment by ubuntutest** [comment]
It seems that the result of the investigation reported to a bug in the editor I use, it is not a problem with prismjs.

Can I ask for advice on how to solve the problem perhaps with prism or with js?

I don't know how to get you an example, the site is private and the editor is for authors only

**Comment by RunDevelopment** [comment]
If the editor you use adds the newline, then there isn't much Prism can do about it, I'm afraid. This sounds like something that the editor has to fix.

> it is not a problem with prismjs

Then I'll close this issue now.
