### ISSUE TITLE
Tutorial link is broken again

### ISSUE THREAD

**Issue by I-keep-trying** [PrismJS/prism#3596]
I noticed this same link was broken before in issue #3155 but it's broken again. 

It's under "Third party tutorials" - [Code highlighting in React using Prism.js](https://betterstack.dev/blog/code-highlighting-in-react-using-prismjs/)

![prism](https://user-images.githubusercontent.com/26046173/201433113-b3707565-ad72-44f8-9e23-d355e10206ad.png)

**Comment by Golmote** [comment]
It seems it is now a proper redirect, which leads to https://reemus.dev/article/code-highlighting-in-react-using-prismjs
