### ISSUE TITLE
Prism adding new lines after every space/special character

### ISSUE THREAD

**Issue by williamlmao** [PrismJS/prism#3631]
**Information:**
- Prism version: "^1.29.0"
- Environment: Browser, react

**Description**
You can see how prism is adding a bunch of line breaks below. 
<img width="852" alt="Screenshot 2023-01-10 at 9 59 01 PM" src="https://user-images.githubusercontent.com/55903529/211707716-0f62362f-d2b6-49d5-a02c-c32f8cdf12a6.png">

Removing prism, it is formatted just fine. 

<img width="782" alt="Screenshot 2023-01-10 at 10 00 35 PM" src="https://user-images.githubusercontent.com/55903529/211707916-6183e7c7-2a2c-4999-9170-b613ce1c4dcf.png">

**Example**

```
import { useEffect } from "react";
import React from "react";
import Prism from "prismjs";
import "prismjs/themes/prism-okaidia.css"; // Theme

export const ShowCode = ({
  destructuredProp,
}: {
  destructuredProp: string;
}) => {
  useEffect(() => {
    Prism.highlightAll();
  }, []);
  return (
    <div className="Code">
      <pre>
        <code
          className={`language-js`}
        >{`import React, { useEffect } from "react";
import Prism from "prismjs";
import "prismjs/themes/prism-tomorrow.css";
import "./styles.css";

export default function Code({ code, language }) {
  useEffect(() => {
    Prism.highlightAll();
  }, []);
  return (
    <div className="Code">
      <pre>
        
      </pre>
    </div>
  );
}`}</code>
      </pre>
    </div>
  );
};

```

**Comment by Golmote** [comment]
Hello,

I feel like this has to be a CSS issue. Like maybe having a `.token { display: block; }` somewhere in your stylesheets, or something similar.
