### ISSUE TITLE
C-like function def

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#364]
Regarding: https://github.com/LeaVerou/prism/blob/gh-pages/components/prism-clike.js#L23

Why are we using nested tokens there instead of just lookahead?

**Comment by Golmote** [comment]
I made the change in the C-like component (d4194c93cfec0982a851a8a3dc1e89842ee72a64).
For JS in markup, I'll wait for tests, since the change seems to affect ASP.NET as well.

**Comment by Golmote** [comment]
I just applied the change to `<script>` and `<style>` tags (29643f4e462d2fdac353c44c2d826f0c4c5dc62f).

**Comment by keeping17** [comment]
#364
