### ISSUE TITLE
C# code highlighting doesn't work

### ISSUE THREAD

**Issue by sergeyzwezdin** [PrismJS/prism#367]
Just added prism to my website and trying to highlight csharp code.

Added following HTML:

> &lt;pre&gt;&lt;code class="language-csharp"&gt;public class P1 {
>  await int x = 5;
>  Console.WriteLine(x);
> } &lt;/code&gt;&lt;/pre&gt;

..but it doesn't work. HTML structure didn't changed once I added "language-csharp" class.

Seems bug?

**Comment by SenuraMalaka** [comment]
My problem was that when I am downloading Prism JS, I forgot to tick the CSharp checkbox.

**Comment by karlelmberg** [comment]
I have download prism.js with csharp inncluded but i dont get C# syntax high-lightning. 

<pre><code class="language-css">p { color: red }</code></pre>


<pre class="langauge-csharp">
<code class="langauge-csharp">
        var test = new string();
    </code>
</pre>


<pre class="language-javascript">
<code>
// Deep clone a language definition (e.g. to extend it)
clone: function deepClone(o, visited) {
var clone, id, type = _.util.type(o);
visited = visited || {};

switch (type) {
case 'Object':
id = _.util.objId(o);
if (visited[id]) {
return visited[id];
}
clone = {};
visited[id] = clone;

for (var key in o) {
if (o.hasOwnProperty(key)) {
clone[key] = deepClone(o[key], visited);
}
}
   </code>
</pre>

![image](https://user-images.githubusercontent.com/42864147/56367549-c0245880-61f5-11e9-92b3-0f46cd3cab17.png)

**Comment by RunDevelopment** [comment]
The C# language itself is working (see [here](https://prismjs.com/test.html#language=csharp)).
There is probably something wrong with your setup. Could you provide a link/repo/snippet for your site's HTML?

**Comment by karlelmberg** [comment]
Hi RunDevelopment, 

Please see.
http://elmbergdevelopment.azurewebsites.net/articles/articlessimple-tips-on-css-structure/

**Comment by mAAdhaTTah** [comment]
The HTML structure is quite wrong. Most of these lines are wrapped in... `h5` tags? The entire code snippet needs to be wrapped in `<pre><code>` tags, with the proper `class` attached.

**Comment by RunDevelopment** [comment]
@mAAdhaTTah That's not the part which is not being highlighted (see screenshot).

**Comment by RunDevelopment** [comment]
@karlelmberg I can reproduce your issue and I don't understand why it doesn't work. The cause of the issue is that `document.querySelectorAll('code[class*="language-"], [class*="language-"] code')` doesn't return the C# code element and I don't know why.

**Comment by RunDevelopment** [comment]
Update: Now I know why. Small typo. It has to be `language-csharp` not lang<b>au</b>ge-csharp for both `pre` and `code`.

**Comment by karlelmberg** [comment]
Ohh.....it is the little things.:) I thought it was something wrong with just that language. 

Thank you so much!!
