### ISSUE TITLE
<code> inside <textarea>

### ISSUE THREAD

**Issue by andy-barrette** [PrismJS/prism#3708]
**Motivation**
Currently, this doesn't work. Prism.highlightAll() does not find code blocks inside textarea blocks. Editable code can't be achieved?

**Description**
Editable code that is formatted in realtime

**Alternatives**
div with contentEditable="true" could substitute for some applications, but I couldn't get Prism.highlightAll() to run from an event handler. See sample code below EDIT: Nevermind. Example won't display right. [Here is the example code on my server.](https://polyphys.com/ACDOM/prismtest.html)

`<html>
<head>
    <link href="PrismStuff" rel="stylesheet">
</head>
    
<body class='language-js'>
    <div><code>function newfunc(x){ console.log(x); } // a function that does stuff</code></div> 
    <div id='divedit' contentEditable="true" oninput="updatePrism"><code>function newfunc(x){ console.log(x); } // a function that does stuff</code></div> 
    <textarea readonly rows=10 cols=100><code>function newfunc(x){ console.log(x); } // a function that does stuff</code></textarea> 
    
<script src='PrismStuff'></script>
<script>
    function updatePrism(){
        Prism.highlightAll();
        this.focus(); // necessary to keep focus on element being edited
    }
</script>
</body>
</html>`

**Comment by vdsabev** [comment]
I needed this too - so I wrote it: https://codebedder.com

You can't syntax highlight the text of a textarea, but you can make it transparent, overlay it on top of a syntax highlighted code block, and sync the text content, font, and scroll between the two. I even added an iframe with live preview.

I hope this minimal code editor helps someone else trying to do the same 🤞

![image](https://github.com/PrismJS/prism/assets/1333274/69e37c06-e43e-4d7f-996e-97cda960a130)

**Comment by LeaVerou** [comment]
You cannot include other HTML elements inside a `<textarea>` — that's a browser limitation. Anything inside `<textarea>` is text. But more fundamentally, a textarea is *plain* text, it cannot have highlighted areas and such.

There are many libraries built on top of Prism to enable editable textareas, such as Code bedder above, [CodeFlask](https://kazzkiq.github.io/CodeFlask/) or [Prism Live](https://live.prismjs.com/) (which is very much WIP) and probably many others.
