### ISSUE TITLE
jsx highlighting not working as expected

### ISSUE THREAD

**Issue by BrettGregson** [PrismJS/prism#3744]
**Information:**
- Prism version: PrismJS 1.29.0

**Plugins:**

- markup
- css
- clike
- javascript
- css-extras
- git
- javadoclike
- markup-templating
- php
- phpdoc
- php-extras
- python
- jsx
- tsx
- twig
- typescript
- yaml&plugins=line-numbers
- remove-initial-line-feed
- inline-color

**Environment:** Browser (Google Chrome Version 117.0.5938.132 (Official Build) (x86_64))

**Description**
JSX highlighting does not work as expected, some elements are completely not rendered

**Example**
Input:
`<pre><code class="language-jsx">
function MyComponent() {
  const [count, setCount] = React.useState(0);

  React.useEffect(() => {
    document.title = `You clicked ${count} times`;

    return () => {
      document.title = "React App";
    };
  });

  return (
    <button onClick={() => setCount(count + 1)}>
      Click me
    </button>
  );
}
</pre></code>`

Output:

<img width="642" alt="Screenshot 2023-10-24 at 22 15 26" src="https://github.com/PrismJS/prism/assets/4068025/ae85bd56-32c9-4f6e-baa9-cee37fead1a9">

The button element is not rendered

**Comment by rainboxx** [comment]
@BrettGregson what was your solution? I have a similar issue and I'm not even sure where to continue looking. Everything else works as expected, only the tags are removed in tsx...

**Comment by BrettGregson** [comment]
Hi @rainboxx 

I had to use html entities for the tags, eg:

`&lt;div&gt;Count: {count}&lt;/div&gt;`

rather than

`<div>Count: {count}</div>`
