### ISSUE TITLE
error with webpack5

### ISSUE THREAD

**Issue by XinChou16** [PrismJS/prism#3745]
pattern: /=\s*(?:"[^"]*"|'[^']*'|[^\s'">=]+)/,

compiler error in webpack5

**Comment by gethari** [comment]
+1 facing this issue out of a blue moon on a no change project since yesterday

**Comment by mAAdhaTTah** [comment]
First, I would need a minimal reproduction to investigate this.

Second, this almost certainly isn't on Prism as this code hasn't changed in a while, so there's probably a bug in Webpack itself or a loader you're using.

**Comment by mAAdhaTTah** [comment]
Could be this: https://github.com/webpack/webpack/issues/17769

**Comment by mAAdhaTTah** [comment]
Closing this as as Webpack (specifically Acorn) issue. Follow the suggestion in the linked description.
