### ISSUE TITLE
Don't compile with node 20

### ISSUE THREAD

**Issue by Ludmila06Marques** [PrismJS/prism#3746]
ERROR in ./node_modules/prismjs/components/prism-markup.js 48:17
Module parse failed: Unexpected token (48:17)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|       'special-attr': [],
|       'attr-value': {
>         pattern: /=\s*(?:"[^"]*"|'[^']*'|[^\s'">=]+)/,
|         inside: {
|           'punctuation': [{

webpack compiled with 1 error

How can i fix this? 
Im with the last version of prism js

**Comment by gethari** [comment]
#3745 

actually even in `node 14.x` the app is not compiling this error seems to be coming out randomly since yesterday

**Comment by Samk13** [comment]
On v16.x too

```log
ERROR in ./node_modules/prismjs/prism.js 1321:13
Module parse failed: Unexpected token (1321:13)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

**Comment by mAAdhaTTah** [comment]
This isn't a node version issue, so going to close this in favor of #3745
