### ISSUE TITLE
Google Closure Compiler error

### ISSUE THREAD

**Issue by englishextra** [PrismJS/prism#378]
Number of errors: 1
JSC_CONSTANT_REASSIGNED_VALUE_ERROR: constant self assigned a value more than once. Original definition at http://closure-compiler.appspot.com/externs.js:21322 at line 1 character 0
self=(typeof window!=='undefined')?window:((typeof WorkerGlobalScope!=='undef...
^

**Comment by Golmote** [comment]
As far as I can tell, current version of Prism does not trigger errors in Google Closure Compiler. I'm closing this issue.
