### ISSUE TITLE
Java syntax number strings rendered with an offset

### ISSUE THREAD

**Issue by andie2019** [PrismJS/prism#3791]
**Information:**
- Prism version: 1.29.0
- Plugins: None
- Environment: Browser, generated using MadCap Flare

**Description**
When using the Java language syntax, number strings not specified inside quotation marks would be rendered off the codeblock, overlapping the left margin.

![Snag_fdf629](https://github.com/PrismJS/prism/assets/58529357/9ddaf6f0-d3ef-4357-98e9-eb5266d80342)

In this example, the first two parameters should be rendered as:
`"accountId": 12345,`
`"workspaceId": [`
`    12345`
`],`

Number strings render correctly when placed inside quotation marks, or when using a different syntax.

Under the section Search Response Attributes > Response:
The first response codeblock is rendered in Java (number strings are offset to the left margin)
The second codeblock is rendered in JavaScript (number strings placed correctly)

**Comment by FIameCaster** [comment]
There's a CSS selector in `perforce.css` that matches number tokens generated by Prism.

```css
span.number
{
	float: left;
	margin-left: -24px;
	position: relative;
	font-family: 'Open Sans';
}
```

Change the selector to something like `span.number:not(.token)` and the problem is fixed.

**Comment by andie2019** [comment]
Thanks you FlameCaster, will try this!
