### ISSUE TITLE
Scrolling over code block with scoll wheel or touch pad scrolls block of code down by one line when last line of code terminates with newline in pre source.

### ISSUE THREAD

**Issue by hmsimha** [PrismJS/prism#382]
If a page author has a block of code such as:

    <pre><code>some.source()
    </code></pre>

The line break at the end of the code block results in a blank line at the end of the processed block (that gets a line number), but which the code block doesn't expand to show. This results in a scroll bar appearing, and when the block is scrolled over (as when scrolling down the page) causes the code area to scroll down by one line, obscuring the first line of code in a way that can be confusing to the viewer.

See http://www.airpair.com/angularjs for examples.

Note: to replicate this by scrolling over a code block, the mouse pointer must land inside the code block while scrolling (so if you scroll over a code block with a line height of 1 and the mouse 'jumps' over that line of code while scrolling, it won't cause the text inside the code block to scroll)

**Comment by Golmote** [comment]
I think this was fixed in 14f3f80df4d58dd6e556f022f43029fac4ffb1ec. Please reopen if you can still reproduce it.
