### ISSUE TITLE
File Highlight and dynamically loaded content

### ISSUE THREAD

**Issue by morkro** [PrismJS/prism#390]
Hey, 

first of all: great work here!

I got a documentation page where I load some views via AJAX. I know that I must call `Prism.highlightAll();` when I want to get Prism working on dynamically loaded content. But somehow this doesn't work with all the additional plugins like _File Highlight_ or _Line Highlight_. They just don't apply.

Is this on purpose, a bug or what can I do to get them also running on dynamically loaded content? :)

**Comment by hiulit** [comment]
Hey @morkro can you try it? It should be fixed now.

**Comment by Golmote** [comment]
I consider this issue was fixed by #514.
