### ISSUE TITLE
Powershell and Command-line syntax support

### ISSUE THREAD

**Issue by lordofscripts** [PrismJS/prism#398]
I am missing Windows PowerShell syntax highlighting. Same for the command-line syntax (DOS batch, Unix)

**Comment by simeononsecurity** [comment]
This shouldn't be closed. 
Bash highlighting isn't the same as PowerShell highlighting.

**Comment by Welding-Torch** [comment]
+1 This is much needed, everyone uses Command Prompt or Powershell.

**Comment by Psghetti** [comment]
Yeah its weird that Powershell is a supported syntax but there is no highlighting or markup at all.

**Comment by JaimeSilva** [comment]
I thought I would get a windows-prompt.css file, but I can't find it anywhere guys
