### ISSUE TITLE
Website does not explain how to do highlighting for languages listed in download

### ISSUE THREAD

**Issue by lordofscripts** [PrismJS/prism#399]
When I downloaded PrismJS I selected a bunch of extras of other languages like C#, C++, C, but when you look at the documentation on the website it lists languages on the left and the corresponding "language-xxx" class but it does not list a lot of the languages that can be selected prior to downloading thus leaving the (potential) user wondering how to actually use it.

**Comment by sbrl** [comment]
A simple list in the README or on the site would be very helpful.

**Comment by Golmote** [comment]
I think this issue is fixed, isn't it? The list of all the languages, with their associated class, is displayed on the homepage.
Furthermore, the Examples page also specifies for each language the class to use.

**Comment by sbrl** [comment]
Oh I didn't notice that!

I was looking at the download page, not the homepage :)

**Comment by loganfranken** [comment]
Looks like this one can be closed?

**Comment by Golmote** [comment]
Yup. BTW, thanks for pointing out all those fixed issues ;)

**Comment by loganfranken** [comment]
No problem, @Golmote! Thanks for keeping this awesome project going!
