### ISSUE TITLE
Line Highlight Plugin: incorrect height on Internet Explorer 9

### ISSUE THREAD

**Issue by philippkuehn** [PrismJS/prism#41]
The Internet Explorer (9) shows for me incorrect heights. Changing 
```javascript
line.textContent = Array(end - start + 2).join(' \r\n');
```
to
```javascript
line.textContent = Array(end - start + 2).join(' \n');
```
fixed that for me!

**Comment by loganfranken** [comment]
In my tests, @philippkuehn's solution seems to work perfectly for IE9 (tested using IE9 emulation in IE11) and doesn't break the functionality in other browsers (tested in latest Chrome, latest Firefox, latest IE, and emulated IE9/10).

If removing a `\r\n` was going to break anywhere, I would think it would break in Windows/IE, right?

Any gotchas I'm not thinking about or can I move forward with creating a PR with @philippkuehn's fix?

(BTW: thanks for the solution, @philippkuehn!)

**Comment by Golmote** [comment]
> Any gotchas I'm not thinking about or can I move forward with creating a PR with @philippkuehn's fix?

I can't think of any. Feel free to submit a PR. ;)
