### ISSUE TITLE
Issue overload

### ISSUE THREAD

**Issue by Golmote** [PrismJS/prism#425]
There are currently a lot of open issues in this repository. I'll try to give an overview of the current situation.

Dear maintainers, if you could take a look at this and do some clean up, we could have a clear view of the remaining bugs that need to be fixed :)

## Issues that could be closed now

Issues listed here have been fixed already (or will never be as they aren't related to Prism).

* #1 has been fixed thanks to the Show Language plugin.
* ~~#22 has been fixed thanks to the Line Numbers plugin.~~
* ~~#74 has been fixed by PR #63~~
* ~~#108 has been fixed by PR #119~~
* ~~#123 has been fixed by PR #129~~
* ~~#131 is not related to Prism~~
* ~~#163 has been fixed by PR #214~~
* ~~#192 is not a bug~~
* ~~#206 has been fixed by PR #316~~
* ~~#237 has been fixed by commit f81554d~~
* ~~#239 has been fixed by commit d28a9af~~
* ~~#250 has been fixed by PR #258~~
* ~~#283 should be tagged as #wontfix~~
* ~~#339 must have been fixed by PR #338~~
* ~~#340 is not related to Prism~~
* ~~#344 has been fixed by commit cfaf681db9018bd1d6e296b526db3e1467986fb3~~
* ~~#359 has been fixed by PR #360~~
* ~~#379 is not related to Prism~~
* ~~#394 has been fixed by PR #395~~

## Other issues...

Finally, these are issues I'm not sure what to do about :

* ~~#77 looks like a really specific edge case and should probably be tagged as #wontfix~~
* ~~#143 seems to be fixed, but I can't find the exact commit that solved it~~
* #152 I couldn't reproduce the issue
* #181 seems fixed to me (just use "language-none"), but it is closely related to #67 which is not fixed.
* #357 could be fixed by extracting the git language changes from the PR #355

**Comment by vkbansal** [comment]
@Golmote PRs are also overloaded

**Comment by Golmote** [comment]
@vkbansal Yes, I know.

**Comment by LeaVerou** [comment]
@vkbansal Yes they are, but you’re not helping in any way by asking when they will be merged on a dozen PRs and then complaining here that PRs are overloaded. You’re only making everyone feel bad. If you want things to move faster, contribute more, like @Golmote has been doing.

**Comment by vkbansal** [comment]
@LeaVerou I'm sorry if I offended you. I did mean to make you feel bad. As for contributions are considered, I know I've been not helping as much as @Golmoye has been because I'm occupied with my porting project. In the process I've reported couple of issues.

My main motive was to give momentum to PRs. Sorry if you feel offended.

**Comment by LeaVerou** [comment]
I feel offended that what you understood from my message is that I got offended.
Btw, even if I was offended “I’m sorry you were offended” is a non-apology. Keep that in mind for when you actually offend someone. :P

**Comment by vkbansal** [comment]
My bad. Will keep that in mind.

**Comment by Golmote** [comment]
Most of the fixed issues have been closed by now, so I think I can close this one too.
