### ISSUE TITLE
Reordering languages in components.js

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#441]
Ordering them by time added doesn't work: It doesn't help in anything and it causes craploads of merge conflicts (essentially if I merge 1 PR with a new language, all others need to pull & merge conflicts to be merged).
I suggest ordering them either alphabetically or by language popularity. Thoughts?

**Comment by uranusjr** [comment]
To solve the merge conflict problem, the most important part would be the last item in the list, so really this can work by just reversing the order—add new language definitions to the beginning of the list, not last.

But really, the code used to iterate over might need some change anyway. Currently `for .. in` is used to traverse through the language keys, but the ECMAScript spec never promised the ordering of the iteration (although implementations tend to result in ordered keys), so it might not be a good idea (at least I don’t think it is) to depend on it. Maybe it would be better to solve things once and for all by adding a `featured` key in `meta` listing special languages to put in the front, with others sorted alphabetically after them.

**Comment by Golmote** [comment]
> Currently for .. in is used to traverse through the language keys, but the ECMAScript spec never promised the ordering of the iteration (although implementations tend to result in ordered keys), so it might not be a good idea (at least I don’t think it is) to depend on it.

I totally agree with this. But currently, everything in Prism relies on this behaviour... and I don't feel like changing it for now...

I like the idea of adding a `featured` key though. Maybe just order the languages alphabetically and tag those we want in front with this special key. This should not impact that much files.

**Comment by LeaVerou** [comment]
> But really, the code used to iterate over might need some change anyway. Currently for .. in is used to traverse through the language keys, but the ECMAScript spec never promised the ordering of the iteration (although implementations tend to result in ordered keys)

Given that every implementation preserves the order, it’s a de facto standard that I would be extremely surprised if a browser violated. In fact, a few years ago when a certain didn’t preserve the order it was considered a bug and was promptly fixed.

**Comment by mAAdhaTTah** [comment]
Was it IE? I bet it was IE...

**Comment by Golmote** [comment]
Or... https://code.google.com/p/v8/issues/detail?id=164 ? (which does not seem to be fixed, btw)
