### ISSUE TITLE
Add missing examples

### ISSUE THREAD

**Issue by Golmote** [PrismJS/prism#446]
In the last few days, I've been writing as much examples as I could for the existing languages.

Here is the current state :
- [x] Markup
- [x] Twig
- [x] CSS
- [ ] CSS Extras
- [x] C-like
- [x] Eiffel
- [x] JavaScript
- [x] Java
- [x] PHP
- [ ] PHP Extras
- [x] CoffeeScript
- [x] Sass (Scss)
- [x] Bash
- [x] C
- [x] C++
- [x] Python
- [x] SQL
- [x] Groovy
- [x] HTTP
- [x] Ruby
- [x] Rip
- [x] Gherkin
- [x] C#
- [x] Go
- [x] NSIS
- [x] ASP.NET (C#)
- [x] Scala
- [x] Haskell
- [x] Swift
- [ ] Objective-C
- [x] AutoHotkey
- [x] Ini
- [x] LaTeX
- [x] Apache Configuration
- [x] Git
- [x] Scheme
- [x] NASM
- [x] Perl
- [x] Handlebars
- [x] MATLAB
- [x] Less
- [x] R
- [x] LOLCODE
- [x] Fortran
- [x] Erlang
- [x] Haml
- [x] Jade
- [x] Pascal
- [x] AppleScript
- [x] Rust
- [x] Dart

Holidays are coming right now so I won't be able to write more examples until January. If anyone wants to give it a try, please follow the format used in [existing examples](https://github.com/LeaVerou/prism/tree/gh-pages/examples).

Happy end-of-year celebration !

**Comment by Golmote** [comment]
I'll consider this issue fixed for now. The few missing examples left could be provided someday by anyone willing to.

**Comment by vkbansal** [comment]
@Golmote If you like, you can grab from http://vkbansal.github.io/spectrum/samples

**Comment by Golmote** [comment]
Thx, I'll check this tonight! :)
