### ISSUE TITLE
syntax highlighting for assembly

### ISSUE THREAD

**Issue by aoighost** [PrismJS/prism#482]
Having syntax highlighting for assembly would be useful for those of us working with very low level snippets.

**Comment by vkbansal** [comment]
I'm just curious. Is  `NASM` similar to `Assembly` ?

**Comment by mAAdhaTTah** [comment]
I hope so - I referred to them as the same in my project...

**Comment by javatlacati** [comment]
@aoighost  Wich gramamr you can help with? As far as I know x86 assembly is the most common. To make ithappen you could provide a list of reserved keywords, operators, and special values ( like strings or hexadecimal numbers ).

**Comment by Golmote** [comment]
@aoighost I too thought NASM was somehow similar to Assembly. If it's not and we should add a component, feel free to reopen.
