### ISSUE TITLE
Multi-column on plugins

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#484]
Now we're starting to have many plugins, we should make them be laid out in 3 columns as well in the download page.

**Comment by Golmote** [comment]
"kuba-kubula" would get cut between two columns :(
![plugins](https://cloud.githubusercontent.com/assets/565460/5842843/7ef710da-a1a8-11e4-9146-7c9a9fa91ba8.png)

**Comment by LeaVerou** [comment]
`break-inside: avoid;` on the labels should fix that, but I doubt it's well supported…

**Comment by Golmote** [comment]
Not event close...

![compat](https://cloud.githubusercontent.com/assets/565460/5843106/71c65e6e-a1aa-11e4-869e-999b1f9c1130.png)

**Comment by Golmote** [comment]
Should we put the columns anyway and add `break-inside: avoid;` already for when it'll get implemented?

**Comment by Golmote** [comment]
Fixed in a88936ace2794a7506009f0bef9ef67af975ba82.
