### ISSUE TITLE
Missing versioning/Release information

### ISSUE THREAD

**Issue by aweingarten** [PrismJS/prism#488]
Prism is an awesome library however, it appears that there is no way to download a specific version other than using git commit revisions.  This makes it difficult to use since most people/build systems/wrappers rely on a version.  If possible would be awesome if there could be tagged releases with versions in the JS/CSS files.

**Comment by sergeyt** [comment]
:+1:

**Comment by cookch10** [comment]
+1

**Comment by nazar-pc** [comment]
Must have at least to specify version, so I'll know when new version released and decide whether I have latest one.

**Comment by apfelbox** [comment]
This is fixed now /cc @LeaVerou

**Comment by apfelbox** [comment]
@Golmote this can be closed.
