### ISSUE TITLE
Allow it to live in a worker (maybe?)

### ISSUE THREAD

**Issue by jakearchibald** [PrismJS/prism#492]
I'm using (or about to use) prismjs on https://jakearchibald.github.io/svgomg/. I want it to live in a worker because I'm (potentially) dealing with large bits of markup, but also the worker is a convenient script loader.

Anyway, I didn't want to spin up a new worker for each usage, but prism wants to terminate after handling a message event. I hacked around it by removing `addEventListener` while it initialises, making it think it's in a node environment https://github.com/jakearchibald/svgomg/blob/feature/code-view/src/js/prism-worker/index.js

Dunno if this is something you're interested in making less hacky, but thought I'd bring it up anyway.

**Comment by Golmote** [comment]
Hi, sorry for the delay.
I just added a parameter in the worker message that forces it to close after highlighting. So when you use it directly from the outside, it should not close itself unless you pass the parameter.

```javascript
var worker = new Worker('prism.js');
worker.onmessage = function(evt) {
	console.log(JSON.parse(evt.data));
};
worker.postMessage(JSON.stringify({
	language: 'markup',
	code: '<span>'
}));
// Here, the worker is still open!
worker.postMessage(JSON.stringify({
	language: 'markup',
	code: '<div>'
}));
```

**Comment by jakearchibald** [comment]
Ohh thanks!
