### ISSUE TITLE
List of languages

### ISSUE THREAD

**Issue by cowboycodur** [PrismJS/prism#494]
I have compiled a list of languages from the js files. Can this be added to the website or maybe this wiki?

actionscript
apacheconf
applescript
aspnet
autohotkey
bash
c
clike
coffeescript
core
cpp
csharp
css
dart
eiffel
erlang
fortran
gherkin
git
go
groovy
haml
handlebars
haskell
http
ini
jade
java
javascript
jsx
julia
latex
less
lolcode
markdown
markup
matlab
nasm
nsis
objectivec
pascal
perl
php
powershell
python
r
rip
ruby
rust
scala
scheme
scss
smarty
sql
swift
twig
typescript

**Comment by Golmote** [comment]
Aren't the lists on the [Download](http://prismjs.com/download.html) page and the [Examples](http://prismjs.com/examples.html) page enough?

**Comment by cowboycodur** [comment]
Not really, the names on those pages don't necessarily match the class names. For example, C# is not the class name, it is csharp. While most are very easily guessed, I would rather not guess. Maybe you could put the class name next to the language on the Download and example pages.

**Comment by Golmote** [comment]
Each example starts with a line explaining which alias to use.
Although I do agree that it would be convenient to have them mentionned directly in the list, each item would have a lot of content (especially on the Download page... Which already provides the file size and the name of the maintainer...) I can't think of a way to make it look good.

**Comment by LeaVerou** [comment]
Perhaps we should have a list in the homepage. There we don't need the name of the maintainer or the file size, only the alias.

**Comment by Golmote** [comment]
Do you have any opinion on the appearance it should have? (number of columns, or anything?)

**Comment by LeaVerou** [comment]
Not really. If you want to work on it @Golmote a) I trust your judgement and b) I will be very grateful for whatever you do :)

**Comment by Golmote** [comment]
Here we go, then: 85ec87e4431ad57c337b7f114bc4afc5e2a0e7fc

![http://puu.sh/gQ7re/7959bf7e50.png](http://puu.sh/gQ7re/7959bf7e50.png)

**Comment by LeaVerou** [comment]
This is awesome, thanks so much!!!

**Comment by cowboycodur** [comment]
This is very awesome! This will be very handy! Thank you!!
