### ISSUE TITLE
Superscripts and subscripts (using <sup> and <sub>) are not supported

### ISSUE THREAD

**Issue by zhiayang** [PrismJS/prism#495]
As the title suggests, using \<sup> and \<sub> doesn't work inside code blocks formatted by Prism.js. It works in vanilla \<pre>\<code> blocks, but something in Prism.js seems to disable sup and sub? I'm not sure this behaviour is intentional, but it superscripts and subscripts can still be useful in code (such as in comments)

**Comment by vkbansal** [comment]
see #465
