### ISSUE TITLE
Is there a bower package for prism?

### ISSUE THREAD

**Issue by DelmerGA** [PrismJS/prism#497]
just wondering if there is a bower package or plans to make one?

**Comment by Golmote** [comment]
See #386 and #180 for discussions about it.

**Comment by brunobatista** [comment]
+1

**Comment by pffy** [comment]
+1

**Comment by hason** [comment]
:+1:

**Comment by rwwagner90** [comment]
```bower install prism#gh-pages --save```

Worked for me.

**Comment by pffy** [comment]
works. thanks!
should be noted here: https://github.com/PrismJS/prism/issues/180

**Comment by apfelbox** [comment]
Yes, there is one now: http://bower.io/search/?q=prism

@DelmerGA or @Golmote you can close this now.
