### ISSUE TITLE
CDNjs: No versionless URL, using very old version

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#499]
As the title says, the version of Prism on cdnjs is super old and there’s no versionless URL one: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/prism

Anyone has five minutes to fix this? Thanks!!

**Comment by vkbansal** [comment]
they support auto updating but require an npm package with semver.

**Comment by LeaVerou** [comment]
Damn, I really have to do that at some point :(

**Comment by Golmote** [comment]
It seems to work now! :)
