### ISSUE TITLE
Markup doesn’t play well with empty attribute values

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#500]
Try highlighting: 

```html
<p style="" foo="bar">
```

Once you set the value to anything, even whitespace, it gets highlighted correctly…

**Comment by Golmote** [comment]
This is not related to empty attribute but to the style attribute.

[It should be fixed now.](https://github.com/PrismJS/prism/commit/a1ebf7585e56b2a4001e798d1ffbaa44762b06c3)

**Comment by LeaVerou** [comment]
Thanks man! Have I told you how awesome you are lately? :D
