### ISSUE TITLE
∴ｂａｍＷＡＲ∵·.Com ↗↗ 화정오피↗↗마곡오피↗↗가평오피

### ISSUE THREAD

**Issue by landthompson4** [PrismJS/prism#503]
∴ｂａｍＷＡＲ∵·.Com ↗↗ 화정오피↗↗마곡오피↗↗가평오피∴ｂａｍＷＡＲ∵·.Com ↗↗ 화정오피↗↗마곡오피↗↗가평오피∴ｂａｍＷＡＲ∵·.Com ↗↗ 화정오피↗↗마곡오피↗↗가평오피∴ｂａｍＷＡＲ∵·.Com ↗↗ 화정오피↗↗마곡오피↗↗가평오피∴ｂａｍＷＡＲ∵·.Com ↗↗ 화정오피↗↗마곡오피↗↗가평오피∴ｂａｍＷＡＲ∵·.Com ↗↗ 화정오피↗↗마곡오피↗↗가평오피∴ｂａｍＷＡＲ∵·.Com ↗↗ 화정오피↗↗마곡오피↗↗가평오피∴ｂａｍＷＡＲ∵·.Com ↗↗ 화정오피↗↗마곡오피↗↗가평오피∴ｂａｍＷＡＲ∵·.Com ↗↗ 화정오피↗↗마곡오피↗↗가평오피∴ｂａｍＷＡＲ∵·.Com ↗↗ 화정오피↗↗마곡오피↗↗가평오피∴ｂａｍＷＡＲ∵·.Com ↗↗ 화정오피↗↗마곡오피↗↗가평오피∴ｂａｍＷＡＲ∵·.Com ↗↗ 화정오피↗↗마곡오피↗↗가평오피

**Comment by Golmote** [comment]
Reported to GitHub...

**Comment by fundon** [comment]
WTF?
