### ISSUE TITLE
Add a "Select All" languages checkbox

### ISSUE THREAD

**Issue by hiulit** [PrismJS/prism#513]
I think this would be useful/helpful... At least for me :P.

What do you think?

**Comment by Golmote** [comment]
This could be useful, for sure.

**Comment by LeaVerou** [comment]
Agreed, it would be a nice to have, though not a priority. If anyone wants to do it, I’m up for merging it :)

**Comment by hiulit** [comment]
I'll try and take a look at it, when I have the time.
