### ISSUE TITLE
Could any one create syntax highlighter for SAS?

### ISSUE THREAD

**Issue by huyingjie** [PrismJS/prism#515]
I am a student in statistics and use SAS (http://sas.com) to analyze data. I am trying to write codes for SAS but fail. Could any one create syntax highlighter for SAS? Thank you in advance!

**Comment by Golmote** [comment]
Their [documentation](http://support.sas.com/documentation/onlinedoc/base/index.html) is just... hm... huge. I'm not sure I want to dive into this. Also, I couldn't find any standard grammar defining the language...

If I read correctly the beginning of the [reference](http://support.sas.com/documentation/cdl/en/lrcon/67885/PDF/default/lrcon.pdf), there is no concept of reserved words which makes the matching of the keywords difficult. And I guess highlighting only the numbers and the strings would be quite pointless.

**Comment by huyingjie** [comment]
@Golmote Thank you for your reply. I do not want to read the lengthy documentation, either. I searched online and found some related codes. Could you adapt their codes?  Thank you in advance. 

Someone wrote SAS syntax highlighter for sublime.  The websites are: 

https://github.com/Jiangtang/sas.tmbundle

http://www.jiangtanghu.com/blog/2012/07/13/sublimetext2-sas/

http://implementing-vdw.blogspot.com/2012/10/new-sublime-text-package-available-for.html

GeShi has SAS highlighter, too.

https://github.com/GeSHi/geshi-1.0/blob/master/src/geshi/sas.php

**Comment by Golmote** [comment]
Fine, here it is.

**Comment by huyingjie** [comment]
Thank you very much!!!!

Could you add SAS to the page http://prismjs.com/download.html ?

I use Prism through MacDown (http://macdown.uranusjr.com/features/)

I tried in MacDown

```
~~~sas

~~~
```
but it is not working.

**Comment by vkbansal** [comment]
@huyingjie The syntax definition is a PR and is still not merged. It will be merged and added once @LeaVerou reviews it.

**Comment by huyingjie** [comment]
@vkbansal Thank you for your reply. What is "PR"? I hope that @LeaVerou can review it soon :-)

**Comment by vkbansal** [comment]
@huyingjie PR is short for "Pull Request"

**Comment by Golmote** [comment]
@huyingjie Now it has been merged, you should see it on the download page. Please feel free to report issues as you're using it! ;)
