### ISSUE TITLE
A nodejs/iojs compatible build

### ISSUE THREAD

**Issue by vkbansal** [PrismJS/prism#541]
Similar to `lodash`, What do you think of a `prism-node` repo?

**Comment by Golmote** [comment]
Prism is already compatible with Node, isn't it?

**Comment by vkbansal** [comment]
No it isn't. Just putting `module.exports` at end of the file does not make it node compatable

**Comment by Golmote** [comment]
Can't you be more specific? What does not work in node?

**Comment by vkbansal** [comment]
As I mentioned in #456 

The following code will simply fail:
```js
var prism = require('path/to/prism/components/prism-core');
require('path/to/prism/components/prism-markup');
```

**Comment by Golmote** [comment]
Asynchronous loading of the components (with dependencies) is a feature request that is not limited to node.
IMO, no prism-node should be required if we find a proper way to enable this feature.

**Comment by vkbansal** [comment]
There already exists well known ways for module loading and resolving dependencies. I assume that you are familiar with them.

My motive behind this type of build is to let users use prism with tools like `browserify` and `webpack` which are very popular.

**Comment by vkbansal** [comment]
Closing this for lack of interest

**Comment by Golmote** [comment]
@vkbansal: Note that #754 fixed this issue.
