### ISSUE TITLE
How Prism use in sea.js?

### ISSUE THREAD

**Issue by tangbc** [PrismJS/prism#542]
I try to use Prism in seajs, code like that:
>var prism = require('@plugins/prism/prism');

and it does not work, why? what need to do next?

**Comment by Golmote** [comment]
I don't know seajs. But if the loading of Prism is asynchronous somehow, you'll probably have to call `prism.highlightAll()` to run it.

**Comment by vkbansal** [comment]
After taking a quick look at seajs website, I can say that its a CommonJS module loader similar to that used in NodeJS. And Prism in it's current state is not completely ready for it.

**Comment by tangbc** [comment]
Thanks, it works after use `Prism.highlightAll()` !
