### ISSUE TITLE
Bash File names with periods

### ISSUE THREAD

**Issue by marshmellow1328** [PrismJS/prism#547]
Bash syntax highlighting struggles with files with version numbers. The line below will highlight the .7 as a number.

    sudo dpkg -i vagrant_1.7.2_x86_64.deb

**Comment by marshmellow1328** [comment]
Adding this to bash component seems to work for me, but didn't see a test suite to feel comfortable just submitting pull request.

    number: {
        pattern: /(\s|=)-?(0x[\dA-Fa-f]+|\d*\.?\d+([Ee]-?\d+)?)\b/,
        lookbehind: true
    }

**Comment by Golmote** [comment]
I think your suggestion would not work for expressions like `z=$(($z+3))` (http://tldp.org/LDP/abs/html/arithexp.html).

Maybe we just need to consider the dot `.` as a word-character and do something like:

```javascript
number: {
    pattern: /([^\w\.])-?(0x[\dA-Fa-f]+|\d*\.?\d+([Ee]-?\d+)?)\b/,
    lookbehind: true
}
```

What do you think?

(Regarding test suite, it's a known problem. For now, the closest thing we have is the [Examples page](http://prismjs.com/examples.html)... So I'll add an example for this specific issue once we agree on the way to fix it.)

**Comment by marshmellow1328** [comment]
That's where I started, but wasn't sure on the regex and switched to what I posted. What you posted works for my few brief examples. Would you say this is a clike problem or a bash problem? Let me know if you'd prefer I submit the pull request.

**Comment by Golmote** [comment]
I'll commit this directly. For now, I'll consider this only applies to bash, because I don't think the case can happen in all c-like languages.
