### ISSUE TITLE
.language-git or .lanaguage-bash

### ISSUE THREAD

**Issue by AndyF** [PrismJS/prism#548]
Suggestion for adding Git or Bash highlighting.

**Comment by Golmote** [comment]
Well... both are already supported... aren't they? See the [Examples page](http://prismjs.com/examples.html):

![prism-bash-git](https://cloud.githubusercontent.com/assets/565460/6627340/c50f2d38-c8fd-11e4-9940-5b3b121d049c.png)

**Comment by AndyF** [comment]
Huh, might be something with the default theme not highlighting `language-git`.

**Comment by Golmote** [comment]
Could you be more specific? The screenshot I posted was taken with the default theme... Do you have an online example of your problem?

**Comment by AndyF** [comment]
https://galaxyui.com/docs/tutorial has `.language-git` but does not get highlighted.

Screenshot:

![https://galaxyui.com/docs/tutorial]()

**Comment by Golmote** [comment]
Oh... The site uses `language-git` to highlight `git` usage on the command line. But the `git` component in Prism is for highlighting the messages provided by git, not the `git` command itself.

I think there is currently no component in Prism dedicated to the highlighting of simple commands like this.

**Comment by mAAdhaTTah** [comment]
`git clone <url>` is a shell (Bash) command. I can't imagine trying to shoehorn highlighting for all the different shell commands into the Bash language.

**Comment by AndyF** [comment]
It could be useful then if we could use `<span class="token tag">` for simple commands like these. The span gets over written by the plugin when placed manually.

**Comment by Golmote** [comment]
Does it get overwritten if you use `language-none` instead of `language-git`?

**Comment by AndyF** [comment]
Ah that was the issue. Thanks :+1:

**Comment by Golmote** [comment]
> I can't imagine trying to shoehorn highlighting for all the different shell commands into the Bash language.

However, this might not be a bad idea to highlight some of them. We could start with the ones listed [here](http://ss64.com/bash/), for example, and add some other well-known commands like `git`.

**Comment by Golmote** [comment]
@AndyF I added a bunch of commands to highlight in Bash (551cebc4fea692a441f75410679f0b03ec91c582). So now, using `.git-bash` on your example should render as:

![prism-bash-functions](https://cloud.githubusercontent.com/assets/565460/6634341/16ce9556-c957-11e4-8ae8-f7f1768c22ba.png)
