### ISSUE TITLE
Prism.js Theme Builder

### ISSUE THREAD

**Issue by SandraShklyaeva** [PrismJS/prism#549]
Hi :) I have just pushed a small app to explore and play with themes for Prism.js.

You can explore it here:
http://sandrashklyaeva.github.io/prism-theme-builder/
https://github.com/SandraShklyaeva/prism-theme-builder

And somehow I didn't notice the prism-themes repository with additional themes before... well, I'll add them shortly.

**Comment by vkbansal** [comment]
@SandraShklyaeva AWESOME STUFF!

**Comment by Golmote** [comment]
Wow, this looks really great! Congrats!

**Comment by SandraShklyaeva** [comment]
Thank you very much, guys! I hope it can be useful for the community :)

**Comment by Golmote** [comment]
I'm closing this issue, since it is not really one.
