### ISSUE TITLE
Download Page Burning CPU

### ISSUE THREAD

**Issue by marshmellow1328** [PrismJS/prism#550]
I just started noticing today my CPU burns up when sitting on the Download page. I'm running in Chrome v41 on Ubuntu 14.04 if that helps.

**Comment by marshmellow1328** [comment]
It only seems to occur after checking/unchecking a number of options. I have yet to find a consistent pattern to it.

**Comment by Golmote** [comment]
Is this the same as #346?

**Comment by marshmellow1328** [comment]
Yep, sounds like it. Don't know how I didn't encounter the past few days, but looks like the same issue.

**Comment by Golmote** [comment]
Closed as duplicate, then.
