### ISSUE TITLE
Weird indentation issue

### ISSUE THREAD

**Issue by rwwagner90** [PrismJS/prism#554]
I've got syntax highlighting working, but all of my code gets indented. See here for what I mean: http://rwwagner90.github.io/ember-shepherd/

Has anyone seen this before and is there a fix?

**Comment by Golmote** [comment]
The `<code>` element must not be indented inside the `<pre>` element.

**Comment by rwwagner90** [comment]
My IDE literally won't allow me to do this. I just put it all on one line, and it works, but that is not very good. It would be nice to ignore the indentation of the ```<code>``` tag and just look at the content inside. Is there a reason to not do that?

**Comment by uranusjr** [comment]
This really isn’t Prism’s problem, if I am not mistaken. Prism works by replacing the `<code>` block with highlighted content, and does not touch anything outside it. That includes newlines and white-spaces between the `<pre>` and `<code>` tags.

The best “solution” here might be some custom JavaScript to strip the extra content yourself, outside Prism. Or it can be done as a Prism plugin, I think.

**Comment by uranusjr** [comment]
Just made a quick hack of a plugin, available [here](https://github.com/uranusjr/prism-strip-indent). Should be straightforward to use.

**Comment by vkbansal** [comment]
@rwwagner90 @uranusjr There's already a well-tested script for that
https://github.com/leeoniya/preCode.js

**Comment by Golmote** [comment]
@vkbansal I'm not sure preCode handles the spaces between the opening `<pre>` and the opening `<code>` by default, though.

**Comment by Golmote** [comment]
Since this issue is not a problem with Prism, but the normal behaviour of `<pre>` tags, I'm closing it.

**Comment by 0ctobat** [comment]
THANKS @vkbansal , you made my day !!

**Comment by esr360** [comment]
May not be a problem with Prism, but it's certainly a problem that Prism could solve, right? Seems like a pretty common use-case to expect code's whitespace to be formatted relative to it's wrapper div.

**Comment by Golmote** [comment]
@esr360 Hi! We built the [Normalize Whitespace plugin](http://prismjs.com/plugins/normalize-whitespace/) to fixes this issue, indeed.
