### ISSUE TITLE
blank block of code

### ISSUE THREAD

**Issue by vlrprbttst** [PrismJS/prism#555]
Sometimes, I just get blank code blocks. For example here:

```
<pre class="language-markup"><code class="language-markup">
<style type="text/css">
<?php include 'css/critical.css.php';?>
</style></code>
</pre>
```

the result is this 
![screenshot_1](https://cloud.githubusercontent.com/assets/4832752/6729974/0023e1e0-ce38-11e4-86cd-fd9a4afe9d3f.png)

it's not the first time and I'm wondering why this is happening. I'm on wordpress

**Comment by vkbansal** [comment]
What's in your `css/crtitical.css.php` file?

**Comment by vlrprbttst** [comment]
some css, why? that should not be incorporated, just shown and syntax highlighted

**Comment by vkbansal** [comment]
Try this
```
<pre class="language-markup"><code class="language-markup">
&lt;style type="text/css"&gt;
<?php include 'css/critical.css.php';?>
&lt;/style&gt;</code>
</pre>
```

**Comment by vlrprbttst** [comment]
works now! thanks, i added &lt and &gt to the php line as well
```
<pre class="language-markup"><code class="language-markup">&lt;style type="text/css"&gt;
  &lt;?php include 'css/critical.css.php';?&gt;
&lt;/style&gt;</code>
</pre>
```

is this a bug? it just happens sometimes

**Comment by vkbansal** [comment]
If you want to include the file and show the file contents: DO NOT add `&lt;` and `&gt;` to the php line

**Comment by vlrprbttst** [comment]
i don't want to, i just need to show the codeblock. shouldn't anything in a pre or code tag be rendered as code by default?

**Comment by vkbansal** [comment]
Yes it should, but you have to escape some special chars like `<` and `>`

http://www.sitepoint.com/everything-need-know-html-pre-element/

**Comment by valtlait** [comment]
@vkbansal There’s no need to escape `>`.

**Comment by vkbansal** [comment]
@valtlait I know but It's just my choice.

**Comment by vlrprbttst** [comment]
that was the work-around, what about the solution? :)

**Comment by vkbansal** [comment]
@vlrprbttst that is not a workaround its the solution! Please read the article I linked carefully.

**Comment by vlrprbttst** [comment]
@vkbansal i opened this issue on prismjs repo and prism doesn't need escaping to show code blocks and highlight the syntax inside it. that's why i called your solution a work-around and not a permanent solution to the problem.

**Comment by vkbansal** [comment]
@vlrprbttst you have a misunderstanding.
That's how HTML works and prism can't do anything about it.

Even prism's own examples are escaped
https://github.com/PrismJS/prism/blob/gh-pages/examples/prism-markup.html

**Comment by Golmote** [comment]
@vlrprbttst : @vkbansal is right. `<pre>` tags may contain HTML that is to be interpreted. So `<` needs to be escaped as `&lt;` inside `<pre>` tags if you want the content to be displayed without being interpreted.

**Comment by valtlait** [comment]
@vlrprbttst, you can create a PHP function like this:

```php
function code($lang, $str) {
    echo "<pre><code class=\"lang-{$lang}\">" . htmlspecialchars($str) . "</code></pre>\n";
}
```

Using it:

```php
<?php code('html',
'<p>HTML code here...</p>'); ?>
```

**Comment by vlrprbttst** [comment]
ok , thanks y'all
