### ISSUE TITLE
Ignore some html tags

### ISSUE THREAD

**Issue by moshmage** [PrismJS/prism#558]
Is it possible to have prism ignore an array of tags while it's doing the syntax?
I need this because I have a file-differences generator, which spawns the html à lá `&lt;tag&gt;` but relies on other html-tags for css, such as `<strike>`;    
    
This is totally possible in my case, `&lt;tag<strike> class="hello"</strike>&gt;` (it means I removed `class="hello"` from `<tag>`), but I cannot seem to find a way for that to work with Prism - as it just straight up ignores my `<strike>` tag.

Am I just being way too crazy, or is this actually possible?

**Comment by Golmote** [comment]
I think a plugin could probably be made for this.

The way I see it, it could use the same principle used by the PHP component, that is: replace all the desired tags by placeholders during highlighting and reinject them once it's done. But I'm pretty sure this would break somewhere (just like the PHP component does).

**Comment by Golmote** [comment]
I just did a quick-n-dirty gist to illustrate the idea: https://gist.github.com/Golmote/c532812e88c6234c48b3

**Comment by moshmage** [comment]
@Golmote You're a godsend :)
