### ISSUE TITLE
"//" Gets token operator instead of token comment 

### ISSUE THREAD

**Issue by andreaslarsen** [PrismJS/prism#564]
![screen shot 2015-04-09 at 12 55 08](https://cloud.githubusercontent.com/assets/3859425/7065424/d5176018-deb7-11e4-9134-cea8f807c16b.png)

The html is this:
```<span class="token operator">/</span><span class="token operator">/</span>```
When it should have been this
```<span class="token comment">//</span>```
or ?
```<span class="token comment" spellcheck="true">//</span>```

My prism js is this:
css+clike+javascript+c+csharp+css-extras+objectivec+php+php-extras+python+ruby+scss+swift

**Comment by LeaVerou** [comment]
Oops, sorry! Which language does the issue happen in? Swift, I guess (judging by the comment)?

**Comment by andreaslarsen** [comment]
That is correctly guessed - sorry, forgot to mention that :)

**Comment by LeaVerou** [comment]
ping @chrischares

**Comment by Golmote** [comment]
Actually, this might be a problem in C-like.
Do all C-like languages allow empty single-line comments? If so, it should definitely use `.*` instead of `.+` in the regex...
https://github.com/PrismJS/prism/blob/gh-pages/components/prism-clike.js#L8

**Comment by mAAdhaTTah** [comment]
I can say PHP does. You know JS does, obv. Dunno about the rest but probably?

**Comment by Golmote** [comment]
I guess we can assume all of them do, then. I'll make the change right now. We'll make exceptions for those that don't allow empty single-line comments, if any. It seems more natural to me this way.

**Comment by andreaslarsen** [comment]
great
