### ISSUE TITLE
Trimming ClassName

### ISSUE THREAD

**Issue by anio** [PrismJS/prism#565]
Please add a trim() at the end of 174 and 180 lines (in prism.js) to trimming className, to fix something like it:
    <pre class=" language-javascript">

**Comment by vkbansal** [comment]
see #478

**Comment by LeaVerou** [comment]
Closing as duplicate. If you have any follow-ups, please post on #478 .

**Comment by anio** [comment]
OK, Thanks.

**Comment by LeaVerou** [comment]
We can probably use `classList` instead of `className`, which is the proper way to modify classes and the only reason it wasn’t done like that in the first place was IE9 support. However, IE9 is not quite significant anymore (and those who care about it can always use a `classList` polyfill).

**Comment by Golmote** [comment]
We might want to ask ourselves if removing an unneeded space in an attribute is worth losing the compatibility with IE9, though.

**Comment by vkbansal** [comment]
I agree with @Golmote

**Comment by LeaVerou** [comment]
Also, there’s no pragmatic reason to trim that attribute. It causes absolutely no issues in any use case I can think of. It’s entirely cosmetic.
