### ISSUE TITLE
Scrollbar didn't show on any piece of my code.

### ISSUE THREAD

**Issue by Draveness** [PrismJS/prism#568]
http://123.56.94.228/ios-yuan-dai-ma-jie-xi-sdwebimage/

**Comment by Golmote** [comment]
I can't reproduce the problem you're describing. The scrollbars are visible whenever needed:

![http://puu.sh/hcvnu/f311222f34.png](http://puu.sh/hcvnu/f311222f34.png)

![http://puu.sh/hcvqL/2ccaee648b.png](http://puu.sh/hcvqL/2ccaee648b.png)

**Comment by Draveness** [comment]
I don't know why, but on my Mac 

![dfb7108b-e4d0-4811-bb1e-b70c2b258527](https://cloud.githubusercontent.com/assets/6493255/7120947/985031e8-e243-11e4-9a2a-f79063f3952d.png)

**Comment by uranusjr** [comment]
The problem is in your own CSS; your `.post` rule contains `word-wrap: break-word;` that is inherited by the code blocks and makes the lines break. Didn’t dig into why this only happens on Safari (probably all WebKit and Blink browsers?), but this is just browser quirk, I guess.

Just add this to your CSS and things will work correctly:

~~~css
code {
    word-wrap: normal;
}
~~~

**Comment by Draveness** [comment]
@uranusjr  Thanks this really works, and I have another question about the `line-number` plugin, I write markdown like this

```
```objectivec line-numbers
[self.imageView sd_setImageWithURL:[NSURL URLWithString:@"url"]
                  placeholderImage:[UIImage imageNamed:@"placeholder.png"]];
```
```

And html

```
<pre><code class="language-objectivec line-numbers">[self.imageView sd_setImageWithURL:[NSURL URLWithString:@"url"]
                  placeholderImage:[UIImage imageNamed:@"placeholder.png"]];
</code></pre>
```

But the line-number doesn't display correctly. Could you help me with this, thank you so much~

(I'm really not goot at such things, and I searched for help, but useless  :-(

**Comment by Golmote** [comment]
The "line-numbers" class is not supported on the `<code>` tag, indeed.
https://github.com/PrismJS/prism/blob/gh-pages/plugins/line-numbers/prism-line-numbers.js#L2

**Comment by Draveness** [comment]
I know that, but how to solve it. Do I need to add linenumber class to pre tag after I wrote a blog with markdown? That's terrible.

**Comment by Golmote** [comment]
Well, as markdown supports raw HTML, I guess you could write directly the needed tags instead of the convenient shortcut <code>```</code>.

Also, you could modify the code of the plugin to move the class from the `<code>` tag to the `<pre>` tag, though I'm not sure this is something we want to do on the official release.
For example, you could change the beginning of the plugin to this:

```javascript
Prism.hooks.add('after-highlight', function (env) {
	// works only for <code> wrapped inside <pre data-line-numbers> (not inline)
	var pre = env.element.parentNode;

	if (
		!pre || !/pre/i.test(pre.nodeName) ||
		// Abort only if nor the <pre> nor the <code> have the class
		(pre.className.indexOf('line-numbers') === -1 && env.element.className.indexOf('line-numbers') === -1)
	) {
		return;
	}

	if (env.element.className.indexOf('line-numbers') > -1) {
		// Remove the class "line-numbers" from the <code>
		env.element.className = env.element.className.replace(/\s*\bline-numbers\b\s*/, '');
	}
	if (pre.className.indexOf('line-numbers') === -1) {
		// Add the class "line-numbers" to the <pre>
		pre.className += ' line-numbers';
	}

	var linesNum = (1 + env.code.split('\n').length);
	// ...
```

**Comment by Draveness** [comment]
I tried this but not work.

**Comment by LeaVerou** [comment]
@Golmote Ideally, we should support both on the official release! :)

**Comment by Golmote** [comment]
Ok, I'll look into it tonight.

**Comment by Golmote** [comment]
@LeaVerou Done. Tested with the following snippets:

```html
<pre class="line-numbers language-javascript"><code>(function(foo) {
do_something(foo, 'bar');
}(bar + 3));</code></pre>

<pre class="line-numbers"><code class="language-javascript">(function(foo) {
do_something(foo, 'bar');
}(bar + 3));</code></pre>

<pre class="language-javascript"><code class="line-numbers">(function(foo) {
do_something(foo, 'bar');
}(bar + 3));</code></pre>

<pre><code class="line-numbers language-javascript">(function(foo) {
do_something(foo, 'bar');
}(bar + 3));</code></pre>
```
