### ISSUE TITLE
Accessibility issue with line numbers plugin

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#574]
Currently, all numbers are read in the beginning, which makes Prism + line-numbers horrible for accessibility.

As a quick fix, we should add an ARIA attribute to not speak the line numbers element (I’m forgetting which attribute is used for this). In the future, we could examine how to have the line numbers properly announced in the beginning of each line without having to create as many DOM elements as loc, which would be inefficient for everyone.

**Comment by calvinjuarez** [comment]
There's [`aria-hidden`], which has this note/caveat:

> Authors **MAY**, with caution, use aria-hidden to hide visibly rendered content from assistive technologies _only_ if the act of hiding this content is intended to improve the experience for users of assistive technologies by removing redundant or extraneous content. Authors using aria-hidden to hide visible content from screen readers **MUST** ensure that identical or equivalent meaning and functionality is exposed to assistive technologies.

[`aria-hidden`]: http://www.w3.org/TR/wai-aria/states_and_properties#aria-hidden "`aria-hidden` on w3.org"

**Comment by LeaVerou** [comment]
Ah yeah, `aria-hidden`!
