### ISSUE TITLE
BUG: tags in comment  with PHP

### ISSUE THREAD

**Issue by ghost** [PrismJS/prism#577]
``` html
<pre><code class="language-php">
func();// normal comment to show
func();// &lt;img src='' /&gt; a little wrong here</code></pre>
```

**Comment by Golmote** [comment]
Sadly this is more or less a known issue. Markup is handled first during highlighting and it may break it when it appears inside PHP code (instead of the opposite: PHP embedded inside HTML)...
As far as I know, nobody has found a solution so far.

**Comment by foo123** [comment]
Check [prism-grammar](https://github.com/foo123/prism-grammar) external parsing add-on for Prism, which uses a grammar to highlight solving all these issues (and more)

**Comment by Golmote** [comment]
I can't reproduce this issue anymore on the Test drive page.
