### ISSUE TITLE
Best way to italicize?

### ISSUE THREAD

**Issue by scho66** [PrismJS/prism#579]
Hi, sorry not really an issue, but I'm looking for an easy way to italicize keywords within my code. I tried embedding <i> tags, but they just get ignored (don't even show in document tree once loaded). 

Anyone know hot to italicize within the code? thanks

**Comment by uranusjr** [comment]
See #558.

**Comment by LeaVerou** [comment]
If you mean existing keywords. you can just do `.token.keyword { font-style: italic; }` in your CSS.
If you mean keywords that are not highlighted in the language, you can use the API, but I will need more details to provide a code example (e.g. what language are you using?)
