### ISSUE TITLE
HTML encoded characters in markup-tag

### ISSUE THREAD

**Issue by oliverschneider** [PrismJS/prism#585]
I have some xml-tags with html encoded characters:

```
<pre>
<code class="language-markup">
<Springer>c6</Springer>
<Läufer>e5</Läufer>
</code>
</pre>
```

```
<pre>
<code class="language-markup">
&lt;Springer&gt;c6&lt;/Springer&gt;
&lt;L&auml;ufer&gt;e5&lt;/L&auml;ufer&gt;
</code>
</pre>
```

Prism doesn't recognize the second tags (Läufer) correctly and highlight them. Is there a way to add all german umlauts to the markup-plugin?

**Comment by uranusjr** [comment]
This happens because Prism uses `\w+` to [match a tag name](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-markup.js#L10), but in JavaScript this matches only ASCII characters. There’s no easy solution here; to override this you will need to explicitly specify what you want to match, which is [doable but far from pretty](http://stackoverflow.com/questions/280712/javascript-unicode-regexes). If all you want are characters with umlauts, you can only include what you want—for example, changing line 10 in the above file from

~~~js
pattern: /^<\/?[\w:-]+/i,
~~~

to 

~~~js
pattern: /^<\/?[\w\u00e4:-]+/i,
~~~

and Prism will correctly highlight the above snippet. I am not sure how a more general fix is reasonable though. Would something like `/^<\/?[^ >]/` work?

**Comment by apfelbox** [comment]
HTML and XML don't share the same grammar, as [XML allows additional characters](http://www.w3.org/TR/xml11/#sec-common-syn) while HTML only allows [alphanumeric ASCII characters](http://www.w3.org/TR/html5/syntax.html#syntax-tag-name) as tag names.

We could either create a separate XML language, that relaxes some of the rules of HTML or in the spirit of ("highlighter, not a linter") allow some invalid HTML.

**Comment by oliverschneider** [comment]
Thank you for your comments. If I change line 10 as suggested by @uranusjr it doesn't change anything. If I add the characters to line 7, the syntax gets highlighted but the highlighter thinks that after the Umlaut the attr-name starts (see the picture below). Can I address that?

Line 7 now looks like this:
```
pattern:/&lt;\/?[\w\u00c4\u00d6\u00dc\u00e4\u00f6\u00fc:-]+\s*(?:\s+[\w\u00c4\u00d6\u00dc\u00e4\u00f6\u00fc:-]+(?:=(?:("|')(\\?[\w\W])*?\1|[^\s'">=]+))?\s*)*\/?>/gi,
```
![bildschirmfoto 2015-06-01 um 16 40 16](https://cloud.githubusercontent.com/assets/1078065/7915350/457e6128-087d-11e5-83b7-559cab37281f.png)

**Comment by apfelbox** [comment]
You could try something like this `[^\s>\/]+` instead of `[\w:-]+`:

```js
'tag': {
	           // ↓-------↓ here   
	pattern: /<\/?[^\s>\/]+\s*(?:\s+[\w:-]+(?:=(?:("|')(\\?[\w\W])*?\1|[^\s'">=]+))?\s*)*\/?>/i,
	inside: {
		'tag': {
			            // ↓-------↓ and here   
			pattern: /^<\/?[^\s>\/]+/i,
			inside: {
				'punctuation': /^<\/?/,
				'namespace': /^[\w-]+?:/
			}
		},
		// ...
```


Which translates to "a tag name is anything that is not a whitespace character, a closing bracket `>` or a slash `/`". Not sure whether this produces other weird special cases (by being too greedy), but it solves your issue.

**Comment by LeaVerou** [comment]
@apfelbox is right. We should relax the markup grammar a bit, as long as it doesn’t result in incorrect highlighting of HTML examples.

**Comment by oliverschneider** [comment]
So, I used @apfelbox' solution and came up with this (masked < with &lt;), which seems to work pretty great:

```javascript
Prism.languages.markup = {
	'comment': /&lt;!--[\w\W]*?-->/g,
	'prolog':/&lt;\?.+?\?>/,
	'doctype': /&lt;!DOCTYPE.+?>/,
	'cdata': /&lt;!\[CDATA\[[\w\W]*?]]>/i,
	'tag': {
		pattern: /&lt;\/?[^\s>\/]+\s*(?:\s+[\w:-]+(?:=(?:("|')(\\?[\w\W])*?\1|[^\s'">=]+))?\s*)*\/?>/i,
		inside: {
			'tag': {
				pattern: /^&lt;\/?[^\s&>\/]+/i,
				inside: {
					'punctuation': /^&lt;\/?/,
					'namespace': /^[\w-]+?:/
				}
			},
			'attr-value': {
				pattern: /=(?:('|")[\w\W]*?(\1)|[^\s>]+)/i,
				inside: {
					'punctuation': /=|>|"/
				}
			},
			'punctuation': /\/?>/,
			'attr-name': {
				pattern: /[\w:-]+/,
				inside: {
					'namespace': /^[\w-]+?:/
				}
			}

		}
	},
	'entity': /&#?[\da-z]{1,8};/i
};
```

**Comment by Golmote** [comment]
Fixed and added in the examples:
![http://puu.sh/imjG2/296a063039.png](http://puu.sh/imjG2/296a063039.png)
