### ISSUE TITLE
Unterminated <div causes regex infinite loop

### ISSUE THREAD

**Issue by miketaylr** [PrismJS/prism#589]
STR:

1) Visit http://prismjs.com/test.html
2) Paste the following code:

```
<div id="jsDataContainer"
    data-watch_api_url="http://www.nicovideo.jp/watch/sm26143171?mode=sp_web_html5&amp;playlist_token=sm26143171_1431552568_77407a919760db308ee0b2e3451e5c8c57d4d8a4"
    data-flapi_url="http://flapi.nicovideo.jp/"
    data-spweb_url="http://sp.nicovideo.jp/"
    data-watch_id="sm26143171"
    data-video_id="sm26143171"
    data-thread_id="1430365146"
    data-default_thread_id="1430365146"
    data-is_channel="false"
    data-video_author_id="22957480"
    data-has_owner_thread="false"
    data-csrf_token="48291828_1431552568_3f21a0e77936a17d7d72187bb731382be301722"
    data-inline_playable="false">
```

Then, delete the closing `>`.

:bomb: :warning: :skull: 
Fair warning, your browser tab will then be hosed. Eventually Firefox and Chrome will let you kill the page/script.

Originally reported by @hallvors at https://github.com/webcompat/webcompat.com/issues/614#issuecomment-102390612.

**Comment by Golmote** [comment]
I think I managed to optimize the regexp somehow (see 75452ba11b3b1c6074b99f54b7a7a592e2adb0f1). Can you confirm this issue is fixed now?

**Comment by apfelbox** [comment]
The test on regex101 confirmed it as fixed.

**Comment by miketaylr** [comment]
I can no longer reproduce on http://prismjs.com/test.html, so assuming that page was updated--lgtm! Thanks!
