### ISSUE TITLE
Ruby: %Q{} string syntax displays incorrectly

### ISSUE THREAD

**Issue by kytrinyx** [PrismJS/prism#590]
The `%q`/`%Q` syntax for quoting strings doesn't get highlighted as strings:

![prism](https://cloud.githubusercontent.com/assets/276834/8010379/0a170f48-0b6d-11e5-9bc3-4eb6c7b4a2e8.png)

This, by contrast, is how GitHub highlights them:

```ruby
def quote
  %Q{She said: "We'll sup before we go."}
end
```

And my editor:

![editor](https://cloud.githubusercontent.com/assets/276834/8010359/d808ab42-0b6c-11e5-8c55-2db29d4b32c2.png)

**Comment by Golmote** [comment]
Thanks for reporting and sorry for the delay. This should be fixed now.

**Comment by kytrinyx** [comment]
Thanks!
