### ISSUE TITLE
[Website] Test drive page has bad usability

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#591]
http://prismjs.com/test.html

With all the languages, one has to scroll to see the result. Result should be moved to be right below the code area. Should be pretty quick to fix if someone has the time.

**Comment by VitaliyR** [comment]
@LeaVerou, @Golmote 
In the scope of PR https://github.com/PrismJS/prism/pull/584 there are updates to the test page which is adding support of testing the plugins.

In the same PR we can push this one too.

**Comment by Golmote** [comment]
@VitaliyR I chose to fix it separately. You'll probably need to update your PR to allow automatic merge to work.
