### ISSUE TITLE
JSON highlighting

### ISSUE THREAD

**Issue by drodil** [PrismJS/prism#605]
Hi,

It would be nice for Prism to support also JSON highlighting. For example we use Prism to highlight code in developer documentation but it would be nice to highlight also API documentation for JSON.

**Comment by vkbansal** [comment]
see #370

**Comment by Golmote** [comment]
The JS component should also work quite well.

**Comment by foo123** [comment]
Check [prism-grammar](https://github.com/foo123/prism-grammar) external parsing add-on for Prism, which uses a grammar to highlight solving all these issues (and more)

You can use the json grammar from [here](https://github.com/foo123/codemirror-grammar/blob/master/test/grammars/json.js) (just change the style model to use prism styling) that's all!

**Comment by javadoug** [comment]
+1 for json highlight grammar to be built-in out of the box.

**Comment by Golmote** [comment]
This issue was fixed by #370. I'm closing it.
