### ISSUE TITLE
Language detection and the File Highlight plugin

### ISSUE THREAD

**Issue by trombonehero** [PrismJS/prism#607]
Thanks very much for Prism: it looks like it might be exactly what I need for including external code snippets on assignment pages for a course I'm teaching. Except for this one issue. :)

When I try to fetch a C++ header file, I use something like this:

```html
<pre class="language-cpp" data-src="some-header.h"/>
```

After the File Highlight plugin runs, however, what I see in my Web Inspector is:

```html
<pre class="language-cpp data-src="some-header.h"
    <code class="language-h">
        "/* ... */"
    </code>
</pre>
```

So, it looks like the language that I've specified on the `pre` isn't getting propagated to the dynamically-generated `code` element within it.

**Comment by trombonehero** [comment]
Maybe somewhere around line 25 the plugin should check "if my `pre` has a class that includes `language-`, let me copy that rather than using the extension"?

**Comment by Golmote** [comment]
Yes, I totally agree with you. I'll see if I can make the change.

**Comment by trombonehero** [comment]
The new version works perfectly. Thank you!

**Comment by Golmote** [comment]
Thank you for reporting!
