### ISSUE TITLE
Swift try, catch, throw not highlighted

### ISSUE THREAD

**Issue by kylebegeman** [PrismJS/prism#625]
I have combed through the open and closed issues but can't seem to find an existing issue for this. 

As the title suggests, keywords such as "try" "catch" and "throws" are not being highlighted properly.

**Comment by Golmote** [comment]
You're right. In fact, it seems they aren't even reserved words according to [the documentation](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/LexicalStructure.html#//apple_ref/doc/uid/TP40014097-CH30-ID413)!
