### ISSUE TITLE
Padding not correct

### ISSUE THREAD

**Issue by TheZoker** [PrismJS/prism#634]
Hey guys,

I have another issue:
The padding is not correct.

![img_2015 07 09_13h19m41s_013_](https://cloud.githubusercontent.com/assets/1368405/8593993/3409b25c-263d-11e5-9165-0a21cb1db680.png)

Here is the demo link:
http://demo.comboot.io/3.1/viewtopic.php?f=2&t=1&sid=eaf36993129832aec8fd611dadd3855d#p16

**Comment by loganfranken** [comment]
Hey @TheZoker, what do you mean exactly by the padding isn't correct? Are you talking about how the "4" is cut off in your picture? Or something else?

**Comment by javatlacati** [comment]
It should be changed from:
pre.line-numbers::before, pre.line-numbers::after {
    display: block !important;
}
to:
pre.line-numbers::before, pre.line-numbers::after {
    display: inline !important;
}
To avoid the line showing upper extar space.
Since the inspector says that the css for that is inline, it should be generated from a js.

**Comment by TheZoker** [comment]
Fixed! Thank you :)
