### ISSUE TITLE
Add autocomplete feature

### ISSUE THREAD

**Issue by javatlacati** [PrismJS/prism#635]
I think the code completion suggestions could be addeded as a plugin.

I think the easiest way could be rewrite keyword property in language definition files y transforming

    Prism.languages.actionscript = Prism.languages.extend('javascript',  {
	'keyword': /\b(?:as|break|case|catch|class|const|default|delete|do|else|extends|finally)\b/,
	'operator': /\+\+|--|(?:[+\-*\/%^]|&&?|\|\|?|<<?|>>?>?|[!=]=?)=?|[~?@]/
    });

to something like

    keywords=['as','break','case','catch','class','const','default','delete','do','else',''extends,'finally'];
    keywordstring="";
    
    for( var i=0;i<keywords.length;i++ ){
     keywordstring+="|"+keywords[i];
    }
    Prism.languages.actionscript = Prism.languages.extend('javascript',  {
	'keyword': /\b(?:keywordstring)\b/,
	'operator': /\+\+|--|(?:[+\-*\/%^]|&&?|\|\|?|<<?|>>?>?|[!=]=?)=?|[~?@]/
    });

this way the ´.token.keyword´ could remain intact.

**Comment by Golmote** [comment]
Apart from the keywords being provided as arrays, there is still the huge work of creating an actual editor with real-time highlighting.

**Comment by javatlacati** [comment]
Well... concerning that please check that [Fiddle] (http://jsfiddle.net/javatlacati/nu4ywjd8/5/).

 is there a function for highlight without replacing everything?
As you can see as you type DOM gets regenerated and cursor moves position.

**Comment by Golmote** [comment]
You're right. And [Dabblet](http://dabblet.com/) uses Prism for the highlighting, so I have no doubt this is doable. But should it really be included in Prism itself? I feel like it should be another project. Prism focuses on highlighting only, and that other project could use it to provide highlighting in an editor.

**Comment by LeaVerou** [comment]
FWIW I always wanted to make PrismEdit, as a separate project. I was planning to clean up & release Dabblet's editor code, but recently someone made a really cool demo that overlays a textarea on top of a pre, which simplifies the code quite a lot, so ideally I would adapt that and then use it in Dabblet too.

**Comment by javatlacati** [comment]
Please keep us updated :D

**Comment by Golmote** [comment]
We agreed that it would be done as a different project, so I'm closing the issue.
