### ISSUE TITLE
Support for mutiple languages and pre failing

### ISSUE THREAD

**Issue by javatlacati** [PrismJS/prism#639]
In some languages you can write code in some other language to enhace functionality, i.e. asm blocks in ANSI C, Java code in Matlab code, and HTML markup in Java, HTML in markdown, etc.

Is it possible to have more then one language at the same time recognized with for example the tag `<code class="language-matlab language-java">`?

BTW, sometimes the  `<pre>` tag let us write formatted html if we use the `html` tag.
Please run the example and see how it does some crazy things.

    <pre class="line-numbers">
    <code class="language-java language-markup">
    b2 = new JButton("middle button", middleButtonIcon);
    b2.setFont(font);
    b2.setForeground(new Color(0xffffdd));
    b3 = new JButton("<html><center><b><u>E</u>nable</b><br>"
                 + "<font color=#ffffdd>middle button</font>",
                 rightButtonIcon);
      b1 = new JButton("<html><center><b><u>D</u>isable</b><br>"
                 + "<font color=#ffffdd>middle button</font>",
                 leftButtonIcon);
        Font font = b1.getFont().deriveFont(Font.PLAIN);
        b1.setFont(font);        
        b3.setFont(font);
        }
        </code>
    </pre>

**Comment by Golmote** [comment]
No, there is no way to provide multiple languages on a single code block.
But some languages already allow to embed other languages inside themselves, with the `inside` feature. So the inclusions you mention could probably be added in the grammars. Take a look at the CSS, JS, HAML, Jade or ActionScript components for examples.

Regarding the `<pre>` tag that interpretes HTML code, yes, this is its normal behaviour.
To highlight the code you provided with Prism, you need to write it like this:

```html
<pre class="line-numbers">
<code class="language-java language-markup">
b2 = new JButton("middle button", middleButtonIcon);
b2.setFont(font);
b2.setForeground(new Color(0xffffdd));
b3 = new JButton("&lt;html>&lt;center>&lt;b>&lt;u>E&lt;/u>nable&lt;/b>&lt;br>"
             + "&lt;font color=#ffffdd>middle button&lt;/font>",
             rightButtonIcon);
  b1 = new JButton("&lt;html>&lt;center>&lt;b>&lt;u>D&lt;/u>isable&lt;/b>&lt;br>"
             + "&lt;font color=#ffffdd>middle button&lt;/font>",
             leftButtonIcon);
    Font font = b1.getFont().deriveFont(Font.PLAIN);
    b1.setFont(font);        
    b3.setFont(font);
    }
    </code>
</pre>
```

**Comment by Golmote** [comment]
I don't see any reason to keep this issue open. We won't add support for multiple languages on a single block. Language inclusion should be handled inside the components themselves.
