### ISSUE TITLE
Add as bower package

### ISSUE THREAD

**Issue by ronilaukkarinen** [PrismJS/prism#641]
Didn't find prism when searched http://bower.io/search/
Can you add it?

**Comment by Golmote** [comment]
Hm?

![http://puu.sh/j5gHh/fb1d7fb4f2.png](http://puu.sh/j5gHh/fb1d7fb4f2.png)

**Comment by ronilaukkarinen** [comment]
Hmm, weird.

![](http://i.imgur.com/9yguKXA.png "Screenshot")

**Comment by loganfranken** [comment]
Hmm, it comes up for me too!

**Comment by Golmote** [comment]
That is weird, indeed.
I suggest you submit an issue on [Bower](https://github.com/bower/bower).
