### ISSUE TITLE
Require Prism as a dependency in the other languages

### ISSUE THREAD

**Issue by XVincentX** [PrismJS/prism#642]
Actually, [Prism languages definition](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-actionscript.js) are just assuming that Prism is already loaded. This does not let me load language components on demand in a modular way.

**Comment by Golmote** [comment]
True.

**Comment by XVincentX** [comment]
@Golmote Cool, can we do something for that?

**Comment by mAAdhaTTah** [comment]
Related: #456

**Comment by Golmote** [comment]
Oh thanks! I was looking for this issue and couldn't find it.

@XVincentX Yes, we can do something about that, but it's not a small change. See https://github.com/PrismJS/prism/issues/456#issuecomment-74967426.
I'd love to see Prism going asynchronous but this will require quite some work!

**Comment by apfelbox** [comment]
UMD would be really nice, but that would be quite a massive rewrite with touching nearly every file in the repository.

**Comment by mAAdhaTTah** [comment]
@Golmote Yeah, I have it bookmarked because I'd like to tackle it at some point, but I haven't had the time nor the approach yet. @apfelbox is probably right, that asynchronously loading Prism's languages would probably be a major undertaking.

**Comment by SummerWish** [comment]
+1 for this feature. in fact you only need to add something like `var prism = require('./prism-core.js')` in each file

**Comment by mAAdhaTTah** [comment]
This should be resolved as part of #1359.
