### ISSUE TITLE
support for multiple themes in one session

### ISSUE THREAD

**Issue by SirZach** [PrismJS/prism#643]
I would like to have a code block decorated with one prism theme and another code block with a different theme. My reason for wanting to do this is my entire app can switch themes and I'd like to be able to switch the code blocks change themes as well. 

One thought that comes to mind is make the CSS selectors optionally look for a <code>data-theme</code> attribute. I'm not sure if this functionality already exists or is not desired by the owners so I'm looking to get some feedback to see if it's possible. Thanks!

**Comment by Golmote** [comment]
You say your entire app can switch themes. Doesn't this mean that all code blocks should switch theme at the same time?
To answer you question, no, the functionality of setting a theme on a specific instance of Prism does not exist. But as you already guessed, you can easily modify the themes to look for a specific attribute on the instance.

**Comment by SirZach** [comment]
The code blocks should switch themes but without a page refresh to grab different CSS. I'll probably end up supplying my own theme that can flip back and forth based on attributes. Thanks!

**Comment by mAAdhaTTah** [comment]
You can swap out the `link` tag with JavaScript, and when you do, the browser will repaint the page with the new CSS. I did this on a settings page I used Prism on so people can see the different themes before selecting one.

**Comment by Golmote** [comment]
This is also what is done on [Prism website](http://prismjs.com/)
