### ISSUE TITLE
go lang highlighting selector

### ISSUE THREAD

**Issue by darul75** [PrismJS/prism#644]
Hi all,

thank you for this amazing tool.

would it be possible to get go language highlighted with this selector:

```css
class=" language-go"
```

as today it only works for me with

```css
class=" language-clike"
```

ot both working, thx

**Comment by Golmote** [comment]
`language-go` should work perfectly fine.

Did you make sure the Go component was included?

**Comment by darul75** [comment]
Hi, yes go is there but when I look intonm code or debug it I only get a clike grammat mmr matching. I will check it again

**Comment by Golmote** [comment]
Maybe provide an online example.

**Comment by darul75** [comment]
Sure I will need to make some checks before and send it back to you then, thanks for quick answer

**Comment by darul75** [comment]
I am calling manually highlight function

```javascript
prism.highlightAll()
```

when debugging it I got something like in highlightElement function

```javascript
highlightElement: function(element, async, callback) {
...
if (parent) {
			language = (parent.className.match(lang) || [,''])[1];
                        // language: "go"
                       //
			grammar = _.languages[language];
		}
```

then can not retrieve grammar because grammar looks like 

Object {markup: Object, css: Object, clike: Object, javascript: Object}DFS: (o, callback, type) {clike: Objectcss: Objectextend: (id, redef) {insertBefore: (inside, before, insert, root) {javascript: Objectmarkup: Object__proto__: Object

even if go extends clike, I do not see how it could work.

**Comment by Golmote** [comment]
May you provide an online example of the problem, so that I can look into it?

**Comment by darul75** [comment]
Hi,

Everything is bundled with webpack but content rendered is here.

example with go
http://www.darul.io/post/2015-07-22_go-lang-simple-reverse-proxy

example with js
http://www.darul.io/post/2015-07-06_immutablejs-overview

Using React, Prism call is made in componentDidMount() event cycle method.

prism.highlightAll(() => {};

I think I make something wrong but do not know why it works with language-clike or language-javascript but not for language-go

**Comment by Golmote** [comment]
On the page with `go` examples, the component for Go is not loaded. Only are those ones: "markup", "css", "clike", "javascript".

**Comment by darul75** [comment]
Ok I have missed something somewhere, thx a lot. Prism is so great, really good job.

**Comment by javatlacati** [comment]
when I open the page can't see the imports of the js, and css in the head O.o
Hipe this fiddle can help u: http://jsfiddle.net/javatlacati/d56xhoc4/3/

**Comment by darul75** [comment]
thx both @javatlacati @Golmote 

well, I have downloaded the right prism library distribution by hand...but my code is using npm dependency instead, my mistake.

if I want to continue to use my npm dependency, is it a way to force loading of some languages (components folder) 

today, I naively do:

let prism = require('prismjs');

would it be possible to get something like

let prism = require('prismjs');
prims.load(["go"], "...");...

**Comment by Golmote** [comment]
Currently no, this is not possible.

**Comment by kuchaguangjie** [comment]
include the go support, e.g :

`<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/components/prism-go.min.js"></script>`
