### ISSUE TITLE
Need to preserve markup inside of prism-highlighted code

### ISSUE THREAD

**Issue by StanBPublic** [PrismJS/prism#651]
I need to highlight certain words inside prism-highlighted block:

&lt;pre class="language-sql"&gt;
    &lt;code class="language-sql"&gt;
    CREATE PROCEDURE [dbo].[SalesByCategory]
    AS
    IF OrdYear != '1996' &lt;kbd&gt;AND&lt;/kbd&gt; OrdYear != '1997'
    BEGIN
	    SELECT TOP(1) FROM Orders
    END
    &lt;/code&gt;
&lt;/pre&gt;

Prism however replaces markup with &lt;span&gt; tag. These are the things that I have tried:

1. Replacing &lt;kbd&gt; to &lt;span&gt; with class attribute
2. Escaping opening or closing tags

This is NOT Html &lt;code&gt; behavior, since if I remove prism "language" class I do get my tags inside of &lt;code&gt;.

I cannot use prism highlight plugins because highlighting should work based on starting and ending indexes in the input file and not line numbers.

**Comment by Golmote** [comment]
See [here](http://prismjs.com/faq.html#if-pre-existing-html-is-stripped-off-how-can-i-highlight) and also [there](https://github.com/PrismJS/prism/issues/558)

**Comment by StanBPublic** [comment]
Golmote, still cannot make it work. Can somebody point out to an example of how to prevent HTML markup from being stripped off by Prism?

**Comment by Golmote** [comment]
Well, if you follow the links in the second link I gave you, you'll find a small quick'n'dirty plugin for Prism that does what you want. I may eventually take the time to write it officially, but for now it's just a gist. https://gist.github.com/Golmote/c532812e88c6234c48b3

**Comment by StanBPublic** [comment]
So, the only way to achieve that it is by writing a custom Prism plugin (Golmote, thank you very much for sharing).  Perhaps documentation should be updated, because there doesn't seem to be a way to strip off markup by using just configuration or tag escaping.

**Comment by Golmote** [comment]
There might be other ways to do it. See the source code of the [Basic Usage section](http://prismjs.com/index.html#basic-usage) on Prism website for example.

But I thought a plugin would make it easier for everyone. I'll definitely ask for an update in the FAQ when I release it.

So, did you manage to make your code work with the plugin?

**Comment by StanBPublic** [comment]
@Golmote I discovered that prism blows up with "TypeError: Cannot read property 'nodeName' of null" at _self.Prism.highlightElement @ prism.js:2 as soon as add nested code block (this isn't related to your plugin):

&lt;pre class="language-sql">
    &lt;code class="language-sql">
    CREATE PROCEDURE [dbo].[SalesByCategory]
    AS
    IF OrdYear != '1996&lt;pre class="language-markup">&lt;code class="language-markup">AND&lt;/code>&lt;/pre>OrdYear != '1997'
    BEGIN
	    SELECT TOP(1) FROM Orders
    END
    &lt;/code>
&lt;/pre>

I don't see what's wrong with this markup..

**Comment by nauzilus** [comment]
@StanBPublic The markup is fine, but Prism highlights by retrieving all elements to be highlighted (e.g. your `<code class="language-sql">` and `<code class="language-markup">`) and then highlights them one by one. As all markup is stripped during highlighting, the second `<code>` no longer exists in the DOM thus has no `parent` will end up as `null` ([prism-core.js#L57](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-core.js#L157)), which later explodes when Prism tries to highlight it.

The plugin may restore nested tags after highlighting, but the DOM nodes Prism has already fetched will be stale.

I don't have a solution, that's just what is happening :)

Though, why would you have "AND" highlighted as markup inside of SQL? Doesn't that plugin allow you to use the `<kbd>` tag you wanted to use initially?

**Comment by StanBPublic** [comment]
@nauzilus thanks for explanation. Here's why I need to highlight "AND". Part of my code search utility is to highlight search term in the source files (SQL, C#, JavaScript). I know the start and end indexes of the search term hits and insert html tag before and after the hit. These tags are <kbd> but can be <span> or anything. That all works fine, but I want the source files syntax-highlighted with Prism and I also need the search hit highlighted at the same time...

**Comment by nauzilus** [comment]
Have a look at this: http://jsfiddle.net/nauzilus/aek8udvr/1/
Note the plugin Golmote linked to only works for simple tags (e.g. of the form `<tag>...</tag>`, class names or other attributes will stop it working).

I had to do some hackery with adding the `language-sql` classes with JavaScript, because of the way Prism auto-highlights it was running before the plugin ran, and I can't use the `data-manual` trick on jsfiddle. So ignore that bit. If it's all bundled together in one file it should be fine.

Hope that helps otherwise :)

**Comment by StanBPublic** [comment]
@nauzilus that's fantastic, exactly what I need. Thank you very much!
