### ISSUE TITLE
Question: unable to make line-numbers work

### ISSUE THREAD

**Issue by manfer** [PrismJS/prism#654]
I downloaded the library with core, default theme, all languages selected, line-highlight, line-numbers, file highlight, show language and highlight keywords plugins.

Then I include the js and the css on a page and I add the following html code:
```html
<pre class="line-numbers"><code class="language-javascript">
Some javascript code here
</code></pre>
```
And the code is highlighted correctly, the language is shown at the top-right corner (so that plugin is working correctly) but I don't get line numbers.

Am I doing something wrong?

**Comment by javatlacati** [comment]
Do you have any running code? i.e. jsfiddle, codepen, plnkr, etc

**Comment by manfer** [comment]
@javatlacati No, I'm developing on a private server. I was now trying to make a jsfiddle but there is no build of the prism library (with all those components) that I know so I could load it on jsfiddle. So I suppose I will have to upload it myself somewhere. Unless I can use the download link from the "Customize your download" prism page.

I forgot to mention. There are no errors on the console at all.

**Comment by manfer** [comment]
http://codepen.io/anon/pen/LVqGoj

**Comment by manfer** [comment]
This is really annoying. If I create in customize your download one with just core, default theme, the 4 default languages and line numbers plugin. It still doesn't work.

If on the other hand I load individually the core `prism.js`, the javascript language component, and the line numbers plugin from the tag 1.0.1, it works fine.

If I try to genere that combination with the customize download I'm forced to selec c-like too. And it doesn't work. Don't know if it would work without the c-like because it can't be deselected and have javascript selected at the same time.

I'm going to create a last customize one with only css language to test. My last attempt. If it still fails I will need to try to join the files myself and see what happens.

**Comment by manfer** [comment]
I found the problem. The generated js and css files are fully dependant. You can't build a css with a group of components selected and then change components and download only the js file because it won't work.

**Comment by SergeyPodgornyy** [comment]
I also had the same problem, that plugin `line-numbers` was not displayed. The problem was, that I had a custom css for `pre` tag, that overwrites `padding` from plugin css. So, line numbers were not displayed because of the wrong `padding`.
