### ISSUE TITLE
line numbers click to highlight the line

### ISSUE THREAD

**Issue by manfer** [PrismJS/prism#655]
I'm trying to implement dynamic highlight on clicking on line numbers with no luck. I have just one `pre` tag on the page.

First I have relaxed the CSS to allow mouse events on the line numbers and then I use the following code.

```
(function dynamicHighlight() {
  $(".line-numbers-rows > span").on("click", function() {
    $("pre").attr("data-line", $(this).index() + 1);
    Prism.highlightAll( true, dynamicHighlight );
  });
})();
```

When I click a line it is highlighted properly (it is a little slow but works). But it triggers an error on the console:

> ReferenceError: window is not defined prism.js (line 73)

If I don't call dynamicHighlight on the callback of highlightAll then it will do nothing the second time as the `.line-number-rows > span` are totally new ones so they don't have the onclick even binded to them.

But the callback is not working because of that error so I don't know what to do.

**Comment by manfer** [comment]
```
(function(){

if(!window.Prism) {
	return;
}
```
This is the prism code were it fails. I can't provide a line number as it is from a generated prism.js from the prism download page and will be different depending on what you choose.

I will try to find out to what plugin or component that code belongs to.

**Comment by manfer** [comment]
Ok. That looks a bug in Highlight Lines. Looking into other plugins they use
```
if(!self.Prism) {
```
Anyway, even changing that line my code is still not working because when highlightAll callback is triggered highlight lines hasn't been triggered yet. I will need to extend Prism in some way. I read you were thinking on adding an onComplete even to Prism. I suppose that would be a place to put my code. And I could forget about the callback.

**Comment by manfer** [comment]
Ok. I have done it by editing the line numbers plugin and adding at the end of its hook callback the onclick binding.

**Comment by Golmote** [comment]
I'll take a closer look at this next week, to see what can be done.

**Comment by mAAdhaTTah** [comment]
I could see this being pretty neat as a separate plugin with a dependency on `line-highlight`.

**Comment by RunDevelopment** [comment]
Line highlight now supports [clickable line numbers](https://prismjs.com/plugins/line-highlight/#linkable.20).
