### ISSUE TITLE
Set up travis

### ISSUE THREAD

**Issue by apfelbox** [PrismJS/prism#661]
Follow up for #588.

Somebody with access to the prism repository should set up a [travis account](https://travis-ci.org/). As I already created the `.travis.yml` everything should be prepared, so we just need somebody to actually link this repo to travis.

You only have to add the repository to your travis account and everything should automagically be set up by travis and Github, so no further configuration needed.

@LeaVerou can you look into this? Should only be a matter of minutes.

PS: I already have successfully set it up [for my fork](https://travis-ci.org/apfelbox/prism).

**Comment by LeaVerou** [comment]
On it.

**Comment by LeaVerou** [comment]
So I enabled Travis on this repo, but nothing seems to trigger a build. Any ideas?

**Comment by apfelbox** [comment]
Was fixed in the meantime 🎉
