### ISSUE TITLE
Highlight wrong in Coy theme (C#)

### ISSUE THREAD

**Issue by DeNelo** [PrismJS/prism#664]
Try this in the tester (http://prismjs.com/test.html):
Choose C# (or C-like)
Choose Default theme
Paste this into the tester:

    private static Regex foo = new Regeх(@"^@font-face");

Looks fine.
Now switch to the Coy theme.
Note that now "x" in "new Regex(@" is not colored. That must be wrong..!
In fact, "Regex" (in "new Regex") should not be colored at all, like in the other themes and indeed in Visual Studio (see image below:

![coythemeregex](https://cloud.githubusercontent.com/assets/2869982/9269330/c2f7c9b2-4268-11e5-8add-d2380e7ffecf.png)

I didn't realize there could be differences between the themes, but there you are.
BTW it would be cool to make a Visual Studio-theme...

**Comment by apfelbox** [comment]
This is no issue with the theme, but the x is just not matched. In the default theme unmatched tokens and the token for the classname looks the same:

![2015-08-14 at 10 07](https://cloud.githubusercontent.com/assets/1032411/9269691/4109a872-426c-11e5-8322-5f07ed29251c.png)

**Comment by DeNelo** [comment]
Oh I see. Would that be covered by another bug report?

**Comment by apfelbox** [comment]
@DeNelo this is actually not directly a bug with Prism.

Your "x" in `new Regex` is not the default ASCII "x", as you can see here: http://jsbin.com/robohonohi/edit?html,css,js,console,output

Your first Regex prints
```
"x -> 120"
```

but the second one prints
```
"х -> 1093"
```

So this is a unicode character, that *looks* like an "x", but isn't really a "x".

We could argue whether we should allow everything (except whitespace) in classnames, but for now only a-z (the *real* a-z :wink:), 0-9, "-" and "\" are allowed, as you can see [here](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-clike.js#L14).

**Comment by DeNelo** [comment]
I see! Thanks for enlightening me. Wow, this is complex... :)
I suppose that ideally prism should accept whatever the owner of the format accepts, in this case Microsoft, in classnames. But I can see that would defeat the purpose of keeping prism very light-weight. So I'll be more careful with my x's another time..! Thanks!

**Comment by Golmote** [comment]
Thanks for looking into this @apfelbox! I consider the issue can be closed.
