### ISSUE TITLE
line height produces floating number for top which cause issues

### ISSUE THREAD

**Issue by ryanzec** [PrismJS/prism#665]
right now the line highlight plugin is use `parseFloat` to generate the value for top however this will often be a floating number which means for even slightly high highlighted line (20+) you can notice that it is not where it should be.  I have a local modified version that does this:

```javascript
var lineHeight = parseInt(getComputedStyle(pre).lineHeight);
```

This seems to work even when highlighting lines in the 1000's, would this be a welcomed PR?

**Comment by Golmote** [comment]
Are you seeing this issue on a specific browser? I can't reproduce it with Firefox or Chrome. I made a quick JSFiddle to test: http://jsfiddle.net/au6yu4kv/

**Comment by ryanzec** [comment]
This is because I have a differently default font size of 13px, check this fiddle out:

http://jsfiddle.net/g50keua0/

I have tested the `parseInt` locally with a font size of 13px, 23px, and 33px and all of them have proper line highlighting.

**Comment by apfelbox** [comment]
Rounding pixels is always ugly and ultimately up to every single browser. So I am :+1: on trying to fix this problem by just rounding and applying the rounded line-height to the element

**Comment by Golmote** [comment]
Alright, I reproduce it with your fiddle under Chrome. Please feel free to submit a PR. ;)

**Comment by ryanzec** [comment]
#668

**Comment by Golmote** [comment]
Well. It looks like it fixed the bug on Chrome... and it created it on Firefox. :(

**Comment by Golmote** [comment]
Damn I can't find any obvious solution for this!

It looks like Firefox and Chrome just don't behave the same...
Take a look at this really simple fiddle: http://jsfiddle.net/p5283dtv/

Firefox result: ![](http://puu.sh/jComa/c0df2189ad.png)
Chrome result: ![](http://puu.sh/jCon7/27a466fc5e.png)
IE 11 to 9 seems to behave the same way Firefox does.

Does anyone have an awesome idea to fix this?

**Comment by uranusjr** [comment]
FWIW, all of Safari, Chrome, and Opera on OS X behave the same as Chrome on Windows. I guess this is a WebKit/Blink thing.

**Comment by Golmote** [comment]
So... I added a test to check if browser rounds the line-height, so that we can use `parseInt` or `parseFloat` depending on the result: 8ed7ce3a6d11d68d6c65801459d4aed78455baad

This is quite ugly, but I don't have any better idea.

Tested with [this fiddle](http://jsfiddle.net/g50keua0/) under Firefox, Chrome and IE 11 to 9 on Windows.
