### ISSUE TITLE
Bad display for line numbers plugin when the code block is empty

### ISSUE THREAD

**Issue by uranusjr** [PrismJS/prism#669]
The line numbers plugin shows one empty line, even if the code block is empty. And the line number partially overflows the code block (because an empty code block is slightly shorter than one with content).

Example markup:

    <pre class="language-none line-numbers"><code></code></pre>

Result:
    
![screen shot 2015-08-15 at 23 14 59](https://cloud.githubusercontent.com/assets/605277/9289473/9dfb8658-43a3-11e5-91c5-48a82d997a8e.png)

**Comment by Golmote** [comment]
Arf! I made a typo in the commit message. ><
Anyway, thanks for reporting!
