### ISSUE TITLE
Regex should be working but not in PrismJS?

### ISSUE THREAD

**Issue by vimxts** [PrismJS/prism#670]
I have this:
```
Prism.languages.insertBefore("javascript", "comment", {
    "def": {
        pattern: /(var\s+|(?!^),\s*|(?!^),\s*^|[^\\:]\/\/.*\n\s*)((?!\d)[a-z0-9_$]+)(?= *[=,;])/,
        lookbehind: !0
    }
})
```

This should highlight all variable identifiers in the declaration code block.

It works on Regex101: https://regex101.com/r/uF4oY4/46

Why doesn't it work with this? The `y` in `var x, y` and `y = undefined` aren't highlighted.

```
var x;
var y;
//or
var x, y; //with multiple variables declared

var x,
    y = undefined;
```

![capture](https://cloud.githubusercontent.com/assets/5255292/9292623/22369046-4437-11e5-999c-871d4fbffe38.PNG)

The `y` isn't wrapped in any class.

---

P.S. I know, it falsely highlights this, but that's not the point:

```
x, y;
```

**Comment by Golmote** [comment]
The problem is related to the parts `(?!^)` in your regexp. Prism breaks the string into pieces progressively as it matches patterns, so here are the strings that are tested, in order:

<ol><li>First, Prism will test the entire text for your `def` pattern:
```javascript
var x;
var y;
//or
var x, y; //with multiple variables declared

var x,
    y = undefined;
```
This will match `var x`
</li><li>Then Prism will test the following string. Notice how the first match has been removed.
```javascript
;
var y;
//or
var x, y; //with multiple variables declared

var x,
    y = undefined;
```
It will match `var y`
</li><li>Then we have this:
```javascript
;
//or
var x, y; //with multiple variables declared

var x,
    y = undefined;
```
It will match `var x`
</li><li>Then we have this:
```javascript
, y; //with multiple variables declared

var x,
    y = undefined;
```
And here is the problem: your regexp can't match because of the `(?!^)` clauses that fail. Indeed, the way Prism works, the comma is actually at the beginning of the string.
</li>
</ul>

I hope it is more clear.

**Comment by vimxts** [comment]
@Golmote Oh darn! I wanted to avoid highlighting:

```
x , y;

y,
x
```

**Comment by Golmote** [comment]
What you're trying to achieve won't be easy, given the various things that can appear on the right side of the variable.

```javascript
var a = "var b",
    b = function() { var c, d; },
    e = [a, b = 5];
```

I can't think of a way of matching only the newly declared variables with just regexps. :/

**Comment by vimxts** [comment]
@Golmote Actually, I want to achieve this: http://brackets.io It is definitely using some kind of JS regex highlighter. But, oh well~

**Comment by Golmote** [comment]
It seems Brackets uses the code from CodeMirror to do the highlighting. CodeMirror uses parsers, not regexps... https://github.com/adobe/brackets/wiki/Language-Support

**Comment by vimxts** [comment]
@Golmote I'm sorry for my stupidity. But I don't quite sure what is regex vs parser type of highlighting. I've seen CodeMirror, can you point me to a page for explaining?

**Comment by Golmote** [comment]
Well... CodeMirror reads the code character by character to determine the tokens. This way of doing things allows it to *understand* the code. See the code source of the JS mode in CodeMirror: http://codemirror.net/mode/javascript/javascript.js.

Prism, on the other side, uses regexps to determine the tokens. So it is not aware of the actual meaning of the code. This was a design choice made by @LeaVerou, to allow for easier addition of new languages and small code size. See the code source of the JS component in Prism: https://github.com/PrismJS/prism/blob/gh-pages/components/prism-javascript.js
