### ISSUE TITLE
Why not return JSON in components.js.

### ISSUE THREAD

**Issue by malash** [PrismJS/prism#672]
The components.js set a global var "components" instead of returning a JSON format data which makes it no possible to real-time analyze requires and load .js file in components dir.
I meet this problem while trying to program a Angular module for Prism.

**Comment by malash** [comment]
I made a PR here https://github.com/PrismJS/prism/pull/673

**Comment by apfelbox** [comment]
See my comments in #674.

You should use a build tool that can load arbitrary files and transform them to AMD or CommonJS.

**Comment by Golmote** [comment]
I'm closing this issue. As discussed in #674, the `components.js` file can easily be parsed as JSON. The annoying comment in the middle has be removed in #679.
