### ISSUE TITLE
Scheme's number is missing lookbehind

### ISSUE THREAD

**Issue by zot** [PrismJS/prism#702]
Scheme's number def needs lookbehind: true -- it begins with a preceding space or close paren

**Comment by Golmote** [comment]
Can you please provide examples that are not highlighted properly now and would be fixed with this change?

**Comment by zot** [comment]
The highlighting shows properly if you don't use the CSS classes for anything other than the default setup.  The problem comes when you want to use the CSS class for something like drawing a box around the numbers on hover.  This expression:

(+ 3 4)

generates this markup:

<div class="code-text" data-org-src="" data-contain="" contenteditable="true"><span class="token punctuation">(</span><span class="token operator">+</span><span class="token number"> 3</span><span class="token number"> 4</span><span class="token punctuation">)</span>
</div>

Single preceding spaces are included in the "token number" class spans because the regexp has a (\s|\)) group at the beginning which matches a single space or close paren.  Adding lookbehind: true fixes the problem.

**Comment by Golmote** [comment]
Thanks for reporting! :wink:

**Comment by zot** [comment]
Thanks for the timely fix!  I fell asleep before I put in a better example, since GitHub stripped the HTML out of the one I gave.  Guess you didn't need it :).

**Comment by Golmote** [comment]
I understood the problem when I saw the actual code ^^
