### ISSUE TITLE
Tests for hooks

### ISSUE THREAD

**Issue by Golmote** [PrismJS/prism#705]
It would be great if some tests could test the result of hooks.

For example, the [Groovy component](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-groovy.js) currently uses the `wrap` hook to handle string interpolation. Right now, we are unable to test its correct behaviour.

I'm not sure how we could handle it. I guess it could be enough to provide a hook name and an `env` object in input, and the expected result for the `env` object after the hook has been called. But how to allow this kind of test considering the current strict test syntax?

(Poke @apfelbox)

**Comment by apfelbox** [comment]
I am not sure whether we should/could test hooks with the currently used test syntax.

I think we should use the test case syntax strictly for unit testing the produced tokenstream. 

In this case I would manually write regular, asynchronous test using the test framework directly. 

I would propose adding a second directory, in which all `.test.js` are discovered, loaded and executed. 

This way we can keep the token stream tests as simple as they currently are but in the same time can use the full power of the test framework for the more elaborate and complicated tests.

**Comment by Golmote** [comment]
You're right, separating the two things sounds like a good idea. I'll see how this can be done once all token stream tests will be written.

**Comment by Golmote** [comment]
Closed by c1a0c1b.
We support two kinds of tests now, `.test` files using the special syntax for token stream, and `.js` ones comparing code to actual rendered HTML.
