### ISSUE TITLE
HTTP: Misplaced Content-type header stops headers from highlighting

### ISSUE THREAD

**Issue by codemedic** [PrismJS/prism#712]
When highlighting HTTP, the highlighter seems to stop looking for headers, once it finds the `Content-Type` header.

Can this be modified in such a way that it will continue highlighting the headers till end of string or `\n\n` ( `\r\n\r\n` for windows ) is found. Then look for the content to apply the different highlighting for the request / response body.

    Date: Mon, 24 Aug 2015 13:36:36 GMT
    Cache-Control: no-cache
    Content-Length: 47
    Content-Type: application/json
    X-RequestId: Vdsd5KweYhcAAD@F18wAAAAA
    Connection: close

The above example will leave `X-RequestId` and `Connection` not highlighted.

As a work around, I had to move the `Content-Type` header down as the last one, before invoking the `highlightElement()` method on the content.

**Comment by Golmote** [comment]
Can you reproduce the bug on the [Test drive page](http://prismjs.com/test.html)?
Do you have the last version of the component?

**Comment by codemedic** [comment]
I do have the version downloaded yesterday from the webiste; I presume that is the latest version.

I must say, I couldn't reproduce the issue on the Test Drive page. :(

**Comment by Golmote** [comment]
Can you provide a link to an online page reproducing the issue please?

**Comment by codemedic** [comment]
I can, but unfortunately this website is still in development and would
only be available in a couple of weeks.
I will update the ticket, when it comes out.

d i n o    k o r a h

**Comment by Golmote** [comment]
Alright, feel free to reopen the issue then.
