### ISSUE TITLE
jsx - Colors are wrong when JS is inside jsx

### ISSUE THREAD

**Issue by tleunen** [PrismJS/prism#717]
Looks like the colors are wrong when JS is inside a JSX tag.

<img width="561" alt="screen shot 2015-08-25 at 7 06 42 pm" src="https://cloud.githubusercontent.com/assets/1972567/9481905/75ae5bba-4b5c-11e5-84eb-7c42870286ee.png">

Every token is considered as `attr-name`, except for the first object of the array.

**Comment by Golmote** [comment]
Should be ok now.
Please note that if you add another object inside, it will break again, though.
