### ISSUE TITLE
Uncaught line error in line 1111 in prism.js

### ISSUE THREAD

**Issue by EpicTimoZz** [PrismJS/prism#721]
this is an issue that i dont know the exact reason for but it accurs usually when there are spaces at the end before the </pre> and </code> tags

http://puu.sh/jPkLp/552c0fa444.png

thats how it looks in chrome and it breaks all highlighting before it.

this was not broken some time ago so insight on this would be appreciated

**Comment by EpicTimoZz** [comment]
i was able to reproduce the issue outside of the website. 
http://pastebin.com/1kuiqGid

im aware that the code above the not highlighted code has the span tags already apply to it. but this is what happens when the js error accures. so i think i isolated it properly.

**Comment by Golmote** [comment]
Thanks for reporting. It should be fixed now.

**Comment by EpicTimoZz** [comment]
i really found an issue? wow! how do i get the fixed version now? :) (wow i cant believe it wasnt my code that broke something that worked before)

**Comment by Golmote** [comment]
lol! Yes you did. :)

You can use the builder on the [Download page](http://prismjs.com/download.html) to get an updated JS file. (Pro-tip: if you originally used this builder to get Prism, you should have a URL at the very top of your JS file. Open it in your browser and all your themes/languages/plugins should be pre-checked)

**Comment by EpicTimoZz** [comment]
thank you! everything is fixed. open source is truely awsome. thanks for making my forum possible!
http://altpalace.com/thread.php?id=1
if you want to see how i integrated prism into my site!
