### ISSUE TITLE
not autoloading and pre tag not getting class

### ISSUE THREAD

**Issue by markcarver** [PrismJS/prism#734]
I cannot, for the life of me, figure out how to get this to "auto" work. From the homepage:

> If you use that pattern, the `<pre>` will automatically get the `language-xxxx` class (if it doesn’t already have it) and will be styled as a code block.

So I put that example on a page:
`<pre><code class="language-css">p { color: red }</code></pre>`

It doesn't run the highlighting automatically and it doesn't add the class to the pre tag.... am I missing something here?

**Comment by LeaVerou** [comment]
Why did you close? Is the issue fixed? What was it?

**Comment by markcarver** [comment]
Sorry. I was being a space head and this was totally my mistake. I am trying to integrate this into a Drupal subtheme and just copied and pasted the CSS info to the JS array without changing the extension to js. Spent a good 10-20 minutes trying to figure out why it wasn't "loading"... Go figure, user error :)


Typos courteous of Siri

**Comment by markcarver** [comment]
http://drupal-bootstrap.org/api/bootstrap/templates%21menu%21menu-tree.func.php/7.x-3.x-dev#code.14-26
