### ISSUE TITLE
Doesn't work if prism is asynchronously loaded

### ISSUE THREAD

**Issue by WickyNilliams** [PrismJS/prism#75]
If prism is loaded asynchronously then it doesn't highlight any code. It appears because it is being loaded *after* `DOMContentLoaded` event has already fired. 

* Example loading async: http://jsfiddle.net/5QPNN/3/
* Same example loading sync : http://jsfiddle.net/5QPNN/1/

Damn shame this does not work out of the box as I would definitely like this kind of thing loaded asynchronously as it's (technically) non-essential and a discrete piece of functionality.

Any help much appreciated

**Comment by aykevl** [comment]
Can I make a pull request for that? I would really like prism to support async. I don't know how to test it though - is there any documentation how to build the prism.js file?

**Comment by Golmote** [comment]
Sure. To build the prism.js file, you just need to run `gulp`.

**Comment by Golmote** [comment]
#959 fixed this issue. First JSFiddle is working as expected.
