### ISSUE TITLE
Support for jinja

### ISSUE THREAD

**Issue by thetutlage** [PrismJS/prism#759]
Jinja in python and nunjucks in node is quite popular , any recommendations on how to have highlighting for these ?

**Comment by Golmote** [comment]
I'll try to implement them tomorrow if I have time.

**Comment by Golmote** [comment]
In the meantime, you can still use the Twig component. It should do a pretty decent job highlighting Django's templates, jinja and nunjucks.

**Comment by thetutlage** [comment]
Yes twig does a good job :-)

**Comment by Golmote** [comment]
And this leads me to the conclusion that those templating languages should share a common dependency. I'll think about how to do this properly.

**Comment by uranusjr** [comment]
Might want to take [Handlebars] and [Mustache] into account. They use very similar syntaxes, too.

[Handlebars]: http://handlebarsjs.com
[Mustache]: https://mustache.github.io

**Comment by thetutlage** [comment]
Closing as twig works great
