### ISSUE TITLE
Community Themes on Website

### ISSUE THREAD

**Issue by gibsjose** [PrismJS/prism#763]
Do you have plans to add the themes from [`prism-themes`](https://github.com/PrismJS/prism-themes) to the official https://prismjs.com website?

**Comment by Golmote** [comment]
You can read the discussion about the prism-themes repo [here](https://github.com/PrismJS/prism/pull/293). The short answer is no, those themes probably won't be added to the official website, but they could have their own mini-website, someday.

**Comment by gibsjose** [comment]
Interesting discussion! Thanks for the link.

**Comment by nauzilus** [comment]
FYI, I've created a simple [gist](https://gist.github.com/nauzilus/a216f6a5e5e74eec0fde) to inject community themes on the Prism site.

It works OK (although it doesn't handle long them names well :wink:), and of course it just affects the page you're on, so each time you load a new page you have to re-run the bookmarklet, but it might be useful to see how community themes look under various plugins or the test page for example.

**Comment by gibsjose** [comment]
Very nice! I'll give it a shot!
