### ISSUE TITLE
Dollar ($) char followed by a single quote makes incorrect output

### ISSUE THREAD

**Issue by dvdmarchetti** [PrismJS/prism#772]
Hi,
I noticed that if I write a block code which contains a single quote next to a $ sign, the highlighted output will be uncorrect.

Example:
```php
<pre><code class="language-php">
&lt;?php echo 'Test variable$'; ?&gt;
</code></pre>
```

The resulting output will be:
```php
<?php echo 'Test variable
; ?>
```
---
Also, when there's other text: the output it's even worse:
Example:
```php
<pre><code class="language-php">
&lt;?php echo 'Test variable$$'; ?&gt;
&lt;?php echo 'Test 2'; &gt;
</code></pre>
```

Output:
```php
<?php echo 'Test variable
&lt;?php echo 'Test 2'; >
; ?>
&lt;?php echo 'Test 2'; >
```
---
To solve this I tried to add another dollar sign so it becomes:
Example:
```php
<pre><code class="language-php">
&lt;?php echo 'Test variable$'; ?&gt;
</code></pre>
```

The resulting output will be correct:
```php
<?php echo 'Test variable'; ?>
```

Anyone noticed this behavior?

Have a good day!

**Comment by Golmote** [comment]
Wow! That was a nasty bug and it also impacted Handlebars and Smarty. Thank you so much for reporting this. It should be fixed now.
