### ISSUE TITLE
[website] Include US government web design standards in the list of websites using Prism!

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#785]
Woohoo!!!!

https://playbook.cio.gov/designstandards/

**Comment by loganfranken** [comment]
How exciting! :tada:

**Comment by Golmote** [comment]
That's awesome!
Do they have any logo, though? Also, which of the existing websites will we remove? (Or we can add a third line by displaying back Typeplate and adding [Raspberry Pi](https://www.raspberrypi.org/learning/kids-ruby-quiz/worksheet/) for example. What do you think?

**Comment by LeaVerou** [comment]
We could include a small screenshot or something. It’s a government website, this is big! We won't let a lack of logo stop us in including it :D 
I’m afraid TypePlate is a bit small compared to the other websites in the list, which affects the impression the whole list makes. I’m on the fence re:raspberry pi, it's well known, but not as well known as e.g. sitepoint or MDN. We can remove WebPlatform, since they're not using it everywhere, and it's also smaller than the rest of them. Or just add a third row with 1 item. Up to you, both are fine with me!

**Comment by Golmote** [comment]
Here we go!

**Comment by LeaVerou** [comment]
If we’re not gonna use a screenshot, perhaps we could just have styled text instead of an image of styled text?

**Comment by Golmote** [comment]
I'm not sure I wanna add the Merriweather font just for 4 words on the homepage... Can't we just consider this a logo?

**Comment by LeaVerou** [comment]
Oh, I didn’t realize you were using the font from the website! Of course then.

Another option would be to use a screenshot like this:
![image](https://cloud.githubusercontent.com/assets/175836/10468447/1d594014-71cd-11e5-8cbd-c46c3132596c.png)

with `background-size: cover;`

**Comment by Golmote** [comment]
I'll give it a try tomorrow ;)

**Comment by LeaVerou** [comment]
Thanks!

**Comment by Golmote** [comment]
Nice idea, it is still readable and it looks great IMO. If you want us to use backgrounds instead of image tags for the other logos too (I made a special case of this one), just tell me ;)

**Comment by LeaVerou** [comment]
I like it too, thanks!

Image tags are more semantic, but we'd need object-fit support to do this with image tags, which is not supported by IE/Edge :/

**Comment by Golmote** [comment]
Ok, let's leave it that way for now! ;)
