### ISSUE TITLE
Line Numbers don't show with Prism.highlightElement

### ISSUE THREAD

**Issue by dagilleland** [PrismJS/prism#794]
I've been experimenting with Prism, and discovered that this line will **not** generate the actual line numbers (the `<span class="line-numbers-rows">...</span>`)

```
Prism.highlightElement(myElement);
```

However, the `Prism.highlightAll();` does generate the line numbers.

**Comment by Golmote** [comment]
I guess `myElement` is a `<pre>` tag in your example. Please try referencing the `<code>` tag instead.
