### ISSUE TITLE
Line numbers missing last two lines

### ISSUE THREAD

**Issue by fladd** [PrismJS/prism#798]
The last two line numbers are not indicated for some reason. See also attached screenshot.

![prism_line_numbers_bug](https://cloud.githubusercontent.com/assets/2971539/10338291/96563a34-6d05-11e5-9aed-e2638cfb8526.png)

**Comment by Golmote** [comment]
Could you provide on online example reproducing this issue? Also, which browser are you using to reproduce it?

**Comment by fladd** [comment]
http://ghost.fladd.de/welcome-to-ghost/

Safari and Chrome.

**Comment by Golmote** [comment]
@fladd Thanks. The issue is due to the `white-space: pre-wrap` that is applied to code blocks in your `screen.css` stylesheet. Please use `white-space: pre` for code blocks highlighted with Prism.

**Comment by Golmote** [comment]
Or if you really want to preserve the soft wrapping, you can take a look at [this pending PR](https://github.com/PrismJS/prism/pull/584).

**Comment by fladd** [comment]
@Golmote Unfortunately, `white-space: pre` does not solve the problem.
I just added this to my prism.css (which is loaded after the screen.css). But the problem still persists.
Anything else wrong with my setup?

**Comment by Golmote** [comment]
@fladd Did you update the online example? I can't see the change in [prism.css](http://ghost.fladd.de/assets/css/prism.css?v=74a80b5162)

**Comment by Golmote** [comment]
EDIT: @fladd Sorry, you might need to uncomment `word-wrap: normal` too.

**Comment by fladd** [comment]
@Golmote Indeed, word wrap was it.

To fix the issue of line numbers not lining up with the code: `pre.line-numbers > code` needs a `padding-top: 6px`. No clue why. But now it is lined up. Maybe this can be fixed in your default code?

**Comment by Golmote** [comment]
I think it might have to do with other styles too. I'll check this out though.
For now, this issue is fixed ;)
