### ISSUE TITLE
Fix for clike negative number styling

### ISSUE THREAD

**Issue by zot** [PrismJS/prism#810]
The number definition starts with \b- but - is not a word boundary and digits are, so the - is not getting styled as part of the number for negative numbers surrounded by spaces or start/end of the string.  Try these matches and see.  This match against the current number definition returns `["1"]`:
``` js
'-1'.match(/\b-?(?:0x[\da-f]+|\d*\.?\d+(?:e[+-]?\d+)?)\b/i)
```
but this match against a slightly modified definition returns `["-1"]`
``` js
'-1'.match(/-?\b(?:0x[\da-f]+|\d*\.?\d+(?:e[+-]?\d+)?)\b/i)
```
When matched against `"x-1"` both regular expressions return the same match, so I think you'll have the correct match if you just move the leading \b after the -?

**Comment by zot** [comment]
javascript's number definition (which is what I'm actually using) also begins with \b-? and should probably be changed to -?\b

**Comment by Golmote** [comment]
Hi! I already noticed this, though I'm quite satisfied with the current behaviour where the `-` symbol is highlighted as operator (furthermore, AFAIK, most languages actually implement it as an unary minus operator, so it makes sense).

The solution you propose will indeed highlight `-1` as a number, but it will also highlight `4-1` as a whole number...

I definitely think the best move here would be to remove all intents to include the minus operator in the number regexes.

**Comment by zot** [comment]
The current def works fine for for people who only want pretty colors (probably most users of prism).  I, however, am using prism for both pretty colors and tokenization in my playground, so that I can find numbers to change with value sliders.  I'll just make my own def.

**Comment by Golmote** [comment]
I understand your use case. However, as I said, I think negative numbers should precisely be tokenized as an unary minus operator followed by a number, at least in most languages. :)

The specific usage you want would indeed require some customization.
