### ISSUE TITLE
Python highlight triple-quote string with hash

### ISSUE THREAD

**Issue by stormandco** [PrismJS/prism#815]
I tried to highlight some python code with prism, and looks like it has a bug with triple-quote python strings with hash. Prism highlights it like comment:
![screen shot 2015-10-23 at 3 30 00 pm](https://cloud.githubusercontent.com/assets/8763181/10692839/c84dcebe-799c-11e5-85a6-46d4c8dc65ca.png)
when i removed hash from string - everything was fine:
![screen shot 2015-10-23 at 3 31 18 pm](https://cloud.githubusercontent.com/assets/8763181/10692873/12458804-799d-11e5-8f7d-04be32b80b4c.png)

**Comment by Golmote** [comment]
Hi. Comment-like substrings are a known issue. But I think we could prioritize triple-quoted strings over single-line comments in Python.
I'll look into it tonight.
