### ISSUE TITLE
Unpublish broken versions on npm

### ISSUE THREAD

**Issue by RobLoach** [PrismJS/prism#819]
There are a few versions on [the npm package](http://npm.im/prismjs) that don't really make sense:

```
npm view prismjs
```

``` json
{ "name": "prismjs",
  "dist-tags": { "latest": "1.3.0" },
  "versions": [ "0.0.1", "1.1.0", "1.2.0", "1.3.0", "9000.0.1" ],
  "time": 
   {
    "9000.0.1": "2015-05-12T23:54:40.643Z",
     "9000.0.2": "2015-05-12T23:56:14.033Z",
     "0.0.1": "2015-05-13T00:37:38.541Z",
     "1.1.0": "2015-10-06T00:03:04.995Z",
     "1.2.0": "2015-10-07T17:35:20.776Z",
     "1.3.0": "2015-10-27T02:35:27.738Z" }
 }
```

The following should remove the versions....

```
npm unpublish prismjs@9000.0.1
npm unpublish prismjs@9000.0.2
```

**Comment by LeaVerou** [comment]
@Golmote any ideas where the 9000 came from? Is it safe to remove?

**Comment by Golmote** [comment]
@LeaVerou Hey, sorry for not answering that before! I missed this issue somehow.
I don't know where those weird versions come from. They are dated at the time of the creation of the NPM package... so I guess they may have been mistakes, or automatically created maybe?
Anyway, I'm pretty sure they are safe to remove.

**Comment by mAAdhaTTah** [comment]
@Golmote I still see `'9000.0.1'` in `npm view prismjs`. Can we unpub that too?

**Comment by Golmote** [comment]
I do not have access to our npm repo. Only @LeaVerou can do this at the moment.

**Comment by xxczaki** [comment]
@LeaVerou ping

**Comment by nezhar** [comment]
Removing this would be great as it will help to keep a consistent versioning.

Currently this is causing also confusion in services such as https://stackblitz.com/.
Updating to the latest version of the dependencies causes it to take `9000.0.1`

![Selection_001](https://user-images.githubusercontent.com/4420927/66597201-c0971e00-eb9e-11e9-957d-2bceac346545.jpg)

Can be tested here: https://stackblitz.com/edit/ngx-documentary

**Comment by mAAdhaTTah** [comment]
I may be able to handle this now. Let me look at it this evening.

**Comment by mAAdhaTTah** [comment]
```
± |master ✓| → npm unpublish prismjs@9000.0.1
- prismjs@9000.0.1
```

Seems to have worked? Although I still see the version here: https://www.npmjs.com/package/prismjs

Dunno if that's a caching thing; will recheck in a bit.

**Comment by mAAdhaTTah** [comment]
Doesn't seem to be going–sent in a support ticket. Will update here with latest.

**Comment by mAAdhaTTah** [comment]
This is being handled by npm support and should be fixed shortly.

**Comment by RunDevelopment** [comment]
@joskuijpers [They are no longer listed](https://www.npmjs.com/package/prismjs).

<details><summary><code>npm view prismjs versions</code></summary>

```bash
$ npm view prismjs versions
[
  '0.0.1',  '1.1.0',  '1.2.0',  '1.3.0',
  '1.4.1',  '1.5.0',  '1.5.1',  '1.6.0',
  '1.7.0',  '1.8.0',  '1.8.1',  '1.8.3',
  '1.8.4',  '1.9.0',  '1.10.0', '1.11.0',
  '1.12.0', '1.12.2', '1.13.0', '1.14.0',
  '1.15.0', '1.16.0', '1.17.0', '1.17.1',
  '1.18.0', '1.19.0', '1.20.0', '1.21.0',
  '1.22.0', '1.23.0', '1.24.0', '1.24.1',
  '1.25.0', '1.26.0', '1.27.0', '1.28.0'
]
```

</details>

My guess is that Renovate uses an internal database, and that this database is outdated. You might want to report this bug.

**Comment by joskuijpers** [comment]
this shows for me:

```
% npm view prismjs --json  
{
...
  "versions": [
    "0.0.1",
    "1.1.0",
    "1.2.0",
    "1.3.0",
    "1.4.1",
    "1.5.0",
    "1.5.1",
    "1.6.0",
    "1.7.0",
    "1.8.0",
    "1.8.1",
    "1.8.3",
    "1.8.4",
    "1.9.0",
    "1.10.0",
    "1.11.0",
    "1.12.0",
    "1.12.2",
    "1.13.0",
    "1.14.0",
    "1.15.0",
    "1.16.0",
    "1.17.0",
    "1.17.1",
    "1.18.0",
    "1.19.0",
    "1.20.0",
    "1.21.0",
    "1.22.0",
    "1.23.0",
    "1.24.0",
    "1.24.1",
    "1.25.0",
    "1.26.0",
    "1.27.0",
    "1.28.0"
  ],
  "time": {
    "modified": "2022-06-24T16:22:04.447Z",
    "created": "2015-05-12T23:54:40.643Z",
    "9000.0.1": "2015-05-12T23:54:40.643Z",
    "9000.0.2": "2015-05-12T23:56:14.033Z",
```

So maybe it indeed looks at 'time'. I'll contact Renovate. Thank you!

**Comment by joskuijpers** [comment]
Ah I found the trouble.... I am not actually using NPM but a CDN:

https://cdnjs.com/libraries/prism still knows of version 9000

**Comment by RunDevelopment** [comment]
I've asked them if it's possible to remove the v9000.0.1 (https://github.com/cdnjs/cdnjs/discussions/14145). Let's see how this goes.
