### ISSUE TITLE
Why isn't my code getting highlighted?

### ISSUE THREAD

**Issue by AJ-Santos** [PrismJS/prism#820]
Hello, 

I've been using Prism since I created my blog, but recently I reinstalled my server and part of that included reinstalling Ghost. I redownloaded and edited my theme to include PrismJS, and as you can see if you inspect the page, Prism is being loaded. Why aren't my code blocks getting styled?

[Here's](http://antoniojsantos.me/new-quest-learning-c/) one of my posts that should be getting highlighted.

**Comment by Golmote** [comment]
This file http://antoniojsantos.me/assets/js/prism.js?v=184a49e805 is supposed to contain JS, not CSS.
