### ISSUE TITLE
prism breaks css of my page

### ISSUE THREAD

**Issue by amr66** [PrismJS/prism#821]
Not a big bug, but i use a simple "Back to Top" element in my page, that ignores some css-Attributes, given in a linked css file. My back to top looks like this:
```<a id="ScrollTop" href="#" title="Click to go to top">To Top</a>```
and css has:
```
#ScrollTop {
  position: fixed; bottom:5px;left:5px;
  padding: 5 10 5 10px;
  font-size: 130%;
  letter-spacing: -1px;
  text-align: center;
  color: #FFF;
  text-decoration: none;
  background: #004080;
  border: 1px solid #AAA;} 

#ScrollTop:hover
{ text-decoration: underline;}
}
```
but the values for padding are ignored. If i comment out prism, it works fine...

**Comment by Golmote** [comment]
Hi. Could you please provide a link to an online example reproducing the issue please? Your CSS looks quite wrong to me. You have to specify the unit for every value in your padding declaration.

**Comment by amr66** [comment]
Yes, that's it! It worked after i changed that! Courious that prism "detects" the error. So thank you very much!

**Comment by Golmote** [comment]
I'm not sure I understand how it could work without Prism either. But I'm convinced there is a logical explanation! 
Glad I could help ;)
