### ISSUE TITLE
Prism with AngularJS and UI-Router

### ISSUE THREAD

**Issue by Gusbenz** [PrismJS/prism#823]
Not too sure this is a bug or not, probably not.

I'm using ui-router ("AngularUI Router is a routing framework for AngularJS, which allows you to organize the parts of your interface into a state machine..blah, blah") 

Here's the issue:

Prism works on my main index.html (it's loaded and highlights and displays color, it's amazing, love it!), but when I change state it no longer highlights code in that state correctly, which isn't to say it doesn't see Prism anymore, but the code blocks are colorless. Very odd.

and! anything in my state changes includes the correctly highlighted code in index, but any code within that new state isn't rendered properly. 

I will try to add some images later this afternoon to help anyone better understand the issue, but does it make sense?

**Comment by Golmote** [comment]
Hi! Could you provide an online example reproducing the issue please? 
I guess the router loads your changes dynamically. You might have to trigger the highlighting yourself by calling `Prism.highlightAll()` once they are added into the DOM.

**Comment by Gusbenz** [comment]
That did it! Thanks so much!

**Comment by bobsilon** [comment]
:+1:
