### ISSUE TITLE
How to Highlight syntax of html??

### ISSUE THREAD

**Issue by GaneshKandu** [PrismJS/prism#824]
How to Highlight syntax of html??

**Comment by Golmote** [comment]
You have to use the component named "markup" which is a common highlighter for all XML-based languages

**Comment by GaneshKandu** [comment]
thanks a lot ! its working

**Comment by LeaVerou** [comment]
This seems to be a very common point of confusion. @Golmote perhaps we should add aliases? (html, xml, svg)

**Comment by Golmote** [comment]
We already have: https://github.com/PrismJS/prism/blob/gh-pages/components/prism-markup.js#L44

**Comment by GaneshKandu** [comment]
&lt;pre&gt;
&lt;code class="markup" &gt;
&amp;lt;html&amp;gt;
&nbsp;&nbsp;&amp;lt;head&amp;gt;
&nbsp;&nbsp;&nbsp;&nbsp;&amp;lt;title&amp;gt;title&amp;lt;/title&amp;gt;
&nbsp;&nbsp;&amp;lt;/head&amp;gt;
&nbsp;&nbsp;&amp;lt;body&amp;gt;
&nbsp;&nbsp;&nbsp;&nbsp;&amp;lt;p&amp;gt;MyBody&amp;lt;/p&amp;gt;
&nbsp;&nbsp;&amp;lt;/body&amp;gt;
&lt;/code&gt;
&lt;/pre&gt;

Works

**Comment by GitHub-Yann** [comment]
So , it must replace "<"/ ">" as "&lt;" / "&gt;" ?

**Comment by GaneshKandu** [comment]
yes!
