### ISSUE TITLE
SCSS parser fails lots of common declarations

### ISSUE THREAD

**Issue by Snugug** [PrismJS/prism#83]
I'm finding that the SCSS parser is failing on lots of fairly standard declarations. For instance, media queries with a media type (`@media screen…` fails to highlight the `@media`), lots of sibling selectors fail to highlight the first half of the selector (`.foo > .bar` fails to highlight `.foo`), and absolutely no numbers (or their units) get properly highlighted.

**Comment by Golmote** [comment]
This should be fixed now.

**Comment by grayghostvisuals** [comment]
\o/
