### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nerogit** [PrismJS/prism#833]
match	@	(program):111
_self.Prism.util.type	@	prism.js:2
_self.Prism.languages.DFS	@	prism.js:2
_self.Prism.languages.DFS	@	prism.js:2
_self.Prism.languages.DFS	@	prism.js:2
_self.Prism.languages.DFS	@	prism.js:2
_self.Prism.languages.DFS	@	prism.js:2
_self.Prism.languages.DFS	@	prism.js:2
_self.Prism.languages.DFS	@	prism.js:2
_self.Prism.languages.DFS	@	prism.js:2

My code:
```html
          <pre class="language-c"><code >
          </code>
          </pre>
```

**Comment by Golmote** [comment]
See #818
