### ISSUE TITLE
command-line folder

### ISSUE THREAD

**Issue by maruilian11** [PrismJS/prism#850]
hi, recently we want to add your lib to https://cdnjs.com
i found `command-line` folder doesn't in plugins in npm package.
could you please help us determine which file should be hosted on cdnjs if you have free time.
thank you very much!

https://github.com/cdnjs/cdnjs/pull/6617

**Comment by zeitgeist87** [comment]
Hi @maruilian11,

Unfortunately I am not very familiar with the npm package for Prism, but maybe I can help anyway.

The website `prismjs.com` is generated from the `gh-pages` branch of this project. We use the `gh-pages` branch as our development branch. So the website contains the latest version of Prism.

The npm package is generated from the `master` branch as far as I know. The `master` branch contains our stable releases. The last release is version 1.3.0 from the 26. Oct 2015. The `command-line` plugin is a new development and was added quite recently. Therefore it is present on the website and in the `gh-pages` branch, but not in the `master` branch. Maybe we should do another release soon...

I hope this answers your question.

**Comment by jimaek** [comment]
Its already hosted on jsDelivr with auto-updates based on Github tags if you are interested http://www.jsdelivr.com/projects/prism

**Comment by maruilian11** [comment]
thank you! guys

**Comment by LeaVerou** [comment]
Also, plugins should probably not be included in the cdnjs release.
