### ISSUE TITLE
Create Typescript definition file and host on DefinitelyTyped

### ISSUE THREAD

**Issue by romiem** [PrismJS/prism#852]
This would allow us to use Prism in a Typescript project and get auto-complete goodness.

https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by LeaVerou** [comment]
If someone wants to submit a PR for this, I wouldn't be opposed :)

**Comment by eriklieben** [comment]
Created a PR on the DefinitelyTyped repo https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8674
