### ISSUE TITLE
What’s the point of `(?!\*)`?

### ISSUE THREAD

**Issue by valtlait** [PrismJS/prism#853]
I’m trying to understand the Prism source code. What’s the point of `(?!\*)` in the following line:

```js
var lang = /\blang(?:uage)?-(?!\*)(\w+)\b/i;
```

I know it’s a negative lookahead. In this regex it means that an asterisk doesn’t follow the hyphen.

But where is it needed?

**Comment by kylekatarnls** [comment]
`foo(?!bar)` mean "take foo if it's not followed with bar". \* is the * symbol. So it takes - if it's not followed with * then a word. So lang-php, language-html, but not lang-*php.

**Comment by valtlait** [comment]
But how that regex differs from one without `(?!\*)`?

```js
/\blang(?:uage)?-(?!\*)(\w+)\b/i.test('lang-*php');  // returns `false`
/\blang(?:uage)?-(\w+)\b/i.test('lang-*php');  // returns `false`
```

**Comment by kylekatarnls** [comment]
Ho, indeed, \w exclude *, you're right it's redundant. What's the line and file? With them we could know who wrote this and ask him/her if there is a reason.

**Comment by valtlait** [comment]
It’s here: [/components/prism-core.js:18](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-core.js#L18)

**Comment by kylekatarnls** [comment]
It seems @LeaVerou added this piece of the RegExp specifically: cfaf681
But there are no differences when I test with examples.html classes.

**Comment by LeaVerou** [comment]
Yeah, I have no idea why I added that, since as you pointed out, `\w` doesn't include `*` anyway. It can be safely removed.

**Comment by valtlait** [comment]
Thanks!
