### ISSUE TITLE
How to add titles to the code block?

### ISSUE THREAD

**Issue by DevExchanges** [PrismJS/prism#858]
Using Prism with COY theme, I create a code block with  a &lt;pre&gt; tag:
<pre>
&lt;pre class="line-numbers" >&lt;code class="language-java" >
  public class Test {

    private final static String TAG = PrintUtils.class.getSimpleName();
    public static byte[] NEW_LINE = {0x0A};
    public static byte[] POWER_OFF = {0x1B, 0x3D, 0x02};
}
&lt;/code>
&lt;/pre>
</pre>
And my result will like this:
<div class="separator" style="clear: both; text-align: center;">
<a href="http://i.imgur.com/GFV0eAI.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" src="http://i.imgur.com/GFV0eAI.png" height="100" width="320" /></a></div>

So, my question is: How to make a title for this code block? I would like it actualy like this:
<a href="http://i.imgur.com/xNFs6ln.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" src="http://i.imgur.com/xNFs6ln.png" height="100" width="320" /></a></div>

Please help! I don't see this trick in API doc!

**Comment by zeitgeist87** [comment]
You could use the recently added `data-language` àttribute of the [`show-language` plugin](http://prismjs.com/plugins/show-language/), but that's not what it was designed for.

Anyway what's wrong with this:
```html
<h3>Test.java</h3>
<pre class="line-numbers" ><code class="language-java" >
  public class Test {

    private final static String TAG = PrintUtils.class.getSimpleName();
    public static byte[] NEW_LINE = {0x0A};
    public static byte[] POWER_OFF = {0x1B, 0x3D, 0x02};
}
</code>
</pre>
```

**Comment by garretwilson** [comment]
IMHO, this is better semantically---it's what I use:

````html
<figure><figcaption>Test.java</figcaption>
<pre class="line-numbers" ><code class="language-java" >
  public class Test {

    private final static String TAG = PrintUtils.class.getSimpleName();
    public static byte[] NEW_LINE = {0x0A};
    public static byte[] POWER_OFF = {0x1B, 0x3D, 0x02};
}
</code>
</pre>
<figure>
````

**Comment by LeaVerou** [comment]
Yeah not sure why this should be something that Prism addresses tbh.

**Comment by DevExchanges** [comment]
Thank you, garretwilson and zeitgeist87! both ways are very useful.
Author can close this issue now! :dancer:
