### ISSUE TITLE
doesn't format XML when attributes are on a separate line

### ISSUE THREAD

**Issue by garretwilson** [PrismJS/prism#860]
If I have the following:

    <pre><code class="language-xml"><![CDATA[<project xmlns="http://maven.apache.org/POM/4.0.0"
      ...

That formats fine. But if I change that to:

    <pre><code class="language-xml"><![CDATA[<project
      xmlns="http://maven.apache.org/POM/4.0.0"
      ...

Prism doesn't format the `<project` part of the tag correctly. It only recognizes multi-line tags if the first attribute is on the same line, apparently.

**Comment by LeaVerou** [comment]
Cannot reproduce on the http://prismjs.com/test.html page. It seems to format just fine with the first attribute being on a separate line...

**Comment by Golmote** [comment]
Couldn't reproduce, I'm closing this issue.
