### ISSUE TITLE
line highlight plugin not working

### ISSUE THREAD

**Issue by garretwilson** [PrismJS/prism#861]
I'm following the directions at http://prismjs.com/plugins/line-highlight/ , but I can't get this to work:

``` html
<figure>
  <figcaption>pom.xml</figcaption>
  <pre data-line="5"><code  class="language-xml"><![CDATA[<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
    http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  ...
```

Note that code highlighting is working. I can even get the line number plugin to work. But the line highlight plugin doesn't work.

When I add the `data-line="5"` attribute above, the entire source code is shifted to the right as if to make room for line numbers, but nothing appears on line 5.

**Comment by jwp** [comment]
The highlight and numbering plugins seem a bit fragile. (Misdocumented or misreadable.)
I "fixed" the problem by setting the documented attributes on both the <pre/> and <code/> elements. (My context may be different than yours. I was creating the elements with DOM interfaces)

**Comment by mAAdhaTTah** [comment]
If either of you are still having problems and can provide a reproducible test case, we'd be happy to take a closer look, but I'm going to close this for now.
