### ISSUE TITLE
support for <kbd> and <samp>

### ISSUE THREAD

**Issue by garretwilson** [PrismJS/prism#867]
Hey, I really like Prism---you've done a good job and making it simple and "just work" (for the most part, which is must more than I can say about most software out there nowadays).

I had a thought, and I'm not 100% of my opinion on this, but... currently you only support `<code>`, which is completely correct for source code blocks. I was already using `<pre><code>` in fact.

But to be pedantic, HTML5 says we should use `<kbd>` for user input (such as the command-line stuff) and `<samp>` for program output. So for for programming language source code, we're good, but for the command-line or sample output... HTML5 wants us to use other tags. See:
- https://www.w3.org/TR/html5/text-level-semantics.html
- http://www.iandevlin.com/blog/2012/07/html5/using-html-kbd-samp-and-pre-elements

I know that `<kbd>` and `<samp>` aren't widespread, and that everybody tries to cram everything like this into `<code>` (as I used to do), but what are your thoughts on supporting `<kbd>` and `<samp>` when it's semantically appropriate?

Cheers,

Garret

**Comment by LeaVerou** [comment]
To collaborators: We should have a config option on the `<script>` element for the selector used. This is a variation of a very frequent request.

**Comment by zeitgeist87** [comment]
> To collaborators: We should have a config option on the script element for the selector used. This is a variation of a very frequent request.

@LeaVerou I've created to versions of this. A simple attribute to provide the selector directly #868 and another version where the user can specify the tag names of the code blocks #869.

In any case the user has to modify the prism theme to support the selected elements.

**Comment by garretwilson** [comment]
Ack, no---that's hideous! We don't need more `data-*` attributes. Plus it defeats the whole purpose of semantic tags! The whole point of HTML5's recommendations is for people to use `<code>` for source code, `<kbd>` for keyboard input, and `<samp>` for sample output. That's what they say, not me.

But if you're going to add all these weird extra kludge things, I withdraw my suggestion. I'd rather just continue using `<code>` everywhere the way it is now that to dirty up my markup with this stuff.

Are you forgetting what the Prism page itself [says](http://prismjs.com/#basic-usage)? "Prism does its best to encourage good authoring practices. Therefore, it only works with `<code>` elements, since marking up code without a `<code>` element is semantically invalid." And that's the way it should be!

I was only suggesting that things like `language-bash` and the command-line plugin should work with `<kbd>`---automatically, not with an ugly hack. And maybe things like `language-git` should apply to `<samp>`, since it applies to sample output from Git.

But I completely withdraw my suggestion. I pointed out at the beginning of this issue that "you've done a good job and making it simple and 'just work'". I should have left well enough alone---please don't ruin things.

**Comment by garretwilson** [comment]
Oh, I see you're talking about adding things to the `<script>` tag, not to my source code, but still---I don't want to choose between `<code>` and `<kbd>`. Each has its purpose. I was just opening this up for discussion. Please don't ruin Prism. I can live with just `<code>`.

**Comment by zeitgeist87** [comment]
> I don't want to choose between `<code>` and `<kbd>`

You don't have to choose. You can use a comma separated list of tags like so:

```html
<script src="prism.js" data-tags="code, kbd, samp"></script>
```

I probably should have included an example in my PR to make the usage clearer.

> Each has its purpose. I was just opening this up for discussion. Please don't ruin Prism. I can live with just `<code>`.

Don't worry. The PRs are just my contribution to the discussion.

**Comment by LeaVerou** [comment]
Sigh. Maybe we should not add this then (and reverse the PR already merged). No point bloating the code if nobody is interested in the functionality.

Bloating the code and themes by default to include elements extremely few people use though is also **not** going to happen. If at some point enough people start requesting support for these elements, sure, but not at this point.

@garretwilson, your call. `data-tags` and `data-selector` attributes on the `<script>` element or nothing?

**Comment by zeitgeist87** [comment]
> Sigh. Maybe we should not add this then (and reverse the PR already merged). No point bloating the code if nobody is interested in the functionality.

I've reversed the merge for now. If we add this feature I would prefer the `data-tags` attribute. It is much nicer and easier to use.

**Comment by garretwilson** [comment]
Sorry for all the confusion, amigos. I opened this to start a discussion. I'm still not sure which way I would go---I was only expressing that it would be nice to be able to use `<kbd>` and `<samp>` with certain types of content so that we can stay with best practices. But I also don't want to bloat Prism.

Let me do some more thinking on this and maybe I can come up wit a better approach.

**Comment by mAAdhaTTah** [comment]
Maybe this is more appropriate as a plugin?

**Comment by LeaVerou** [comment]
Good idea. If we merge in support for `Prism.selector` again, the tags one can easily be a plugin, I think.
We would need to expose the `script` variable in a hook though.

**Comment by Golmote** [comment]
So the official way to do this is something along the lines of:

```js
Prism.hooks.add('before-highlightall', function (env) {
	env.selector += ", [class*='lang-'] kbd, [class*='language-'] kbd" +
		", kbd[class*='lang-'], kbd[class*='language-']" +
		", [class*='lang-'] samp, [class*='language-'] samp" +
		", samp[class*='lang-'], samp[class*='language-']";
});
```

Alternatively, `env.elements` can be set directly to the set of elements that are to be highlighted.
