### ISSUE TITLE
Expanding code block?

### ISSUE THREAD

**Issue by hongthaiis** [PrismJS/prism#871]
Hi authors,
As I can see at your home page, by default, Prism can show only 20 first lines of a long code block and the vertical scroll bar will appear. User must scroll to see the hidden lines.
So, my question is: How to expand the code block height to see all of lines (do not need the vertical scroll bar)? 
Thanks for any help! :D

**Comment by zeitgeist87** [comment]
Hi @hongthaiis,

Until recently the `Coy` theme limited the height of the code block, but the other themes didn't. We have just removed that limit a few days ago. If you try the latest version from http://prismjs.com you shouldn't get any scrollbars.

**Comment by hongthaiis** [comment]
Thank you, Zeitgeist87!

Changing to default theme, my code blocks height is not limited!
I hope you fix Coy theme soon!
The issue can be closed!
