### ISSUE TITLE
Add spaces to show-invisibles

### ISSUE THREAD

**Issue by mAAdhaTTah** [PrismJS/prism#873]
The show invisibles shows tabs and line endings. Is it possible to add support for displaying spaces as well? Was there a technical reason for not including them? Otherwise, I'd be interested in adding support, if this is something the project would accept.

**Comment by zeitgeist87** [comment]
> The show invisibles shows tabs and line endings. Is it possible to add support for displaying spaces as well? Was there a technical reason for not including them?

I am not the author of that plugin, so I can only guess. The only reason I can think of is performance, but we can easily test that.

> Otherwise, I'd be interested in adding support, if this is something the project would accept.

If you implement this, we would surely accept it.

**Comment by zeitgeist87** [comment]
@mAAdhaTTah I've already implemented it #876. The main problem was, that a naive implementation would make the space character twice as wide, which looks weird. I solved this by a few simple css position attributes. It would be nice if you could test it. I personally don't use the `show-invisibles` plugin and don't know what people expect of it.

**Comment by mAAdhaTTah** [comment]
Will test it this evening. Thanks!

**Comment by Golmote** [comment]
Implemented in #876. I'm closing this issue.
