### ISSUE TITLE
SCRIPT5007 issue with internet explorer 10 / 11 

### ISSUE THREAD

**Issue by losocreativ** [PrismJS/prism#878]
Hi there,

I'm building a website including PrismJS. Work very well on browsers like Chrome but,
some time on firefox and evrytime on IE 10 / 11 my Prism Slider doesn't work.

The console detect an SCRIPT5007 error. It means that my 'Object' is not initialized
It seem come to this part of code : 
 
 /** Set of images to be used.
   * @type {Array} **/
  var slides = [
    $('#img-prism-1').attr('src'),
    $('#img-prism-2').attr('src'),
    $('#img-prism-3').attr('src'),
    $('#img-prism-4').attr('src')
  ];

have someone the same probleme ?! 

Thk

**Comment by zeitgeist87** [comment]
Hi @losocreativ,

Are you sure you posted this to the right project? This is Prism.js the syntax highlighter. Maybe you are looking for [Prism Slider](https://github.com/claudiocalautti/prism-slider).

**Comment by losocreativ** [comment]
Oups ! sorry :S thanke you ! ;)
