### ISSUE TITLE
allow HTML <mark> tags

### ISSUE THREAD

**Issue by garretwilson** [PrismJS/prism#879]
I love Prism, but I'm a little confused about why it is mutually exclusive with my own highlighting. Let's say I want to highlight an annotation in Java:

````html
<pre ><code class="language-java">package com.example;

public class Point
{
 
  …
 
  <mark>@Deprecated</mark>  //NOTE: annotation
  public double calculateSlope(final int x2, final int y2)
````

If I use just plain HTML5, the `<mark>` tag makes a nice highlighted section, e.g. with a yellow background. But Prism makes it as if I had never even used the `<mark>` tag. Why can't I use both? It would _sure_ be useful to use Prism, yet maintain the ability to highlight certain passages.

**Comment by LeaVerou** [comment]
Agreed. We badly need a plugin for highlighting parts of the code on top of the highlighting. I've needed this SO MANY TIMES, the last one in a talk yesterday!
However, every time I look into it, it's nontrivial to implement. Perhaps someone will have a clever idea that will bypass the issues.

**Comment by montogeek** [comment]
This plugin does it: http://prismjs.com/plugins/keep-markup/
Although it does not look good in Chrome: 
![screen shot 2016-02-05 at 22 29 42](https://cloud.githubusercontent.com/assets/1002461/12864435/faa2b8a8-cc57-11e5-8242-d633620afb4d.png)

**Comment by garretwilson** [comment]
@montogeek , what you show in Chrome is what I'm seeing with Firefox 44.0 on Windows. So it must be a bug.

**Comment by montogeek** [comment]
Is Chrome Version 49.0.2623.39 beta (64-bit) on OSX Yosemite, just for the record

**Comment by montogeek** [comment]
Yes, is a bug, the plugin is not _marking_ the correct word, the example source code is correct: https://github.com/PrismJS/prism/blob/gh-pages/plugins/keep-markup/index.html#L59

**Comment by montogeek** [comment]
@garretwilson  I found the bug, its solution but I am not completely sure if it is the correct solution, Can you give me a hand?

**Comment by garretwilson** [comment]
@montogeek how exactly can I help? Are you wanting me to look into the source code? I'm afraid I don't know anything about the Prism source code. Is there some other way I could help? I could look into the source code if you want, but it would have to be another day as it is a bit late where I am now.

**Comment by montogeek** [comment]
Try debugging the plugin source code: https://github.com/PrismJS/prism/blob/gh-pages/plugins/keep-markup/prism-keep-markup.js
I removed a Regex and it solved the problem, but my guess is that the problem is caused by something else.

Is late here too, tomorrow!

**Comment by garretwilson** [comment]
@montogeek , I haven't yet had a chance to look at your change, but I just downloaded the latest version of Prism with the Keep Markup plugin and it seems to work on Chrome and Firefox! Thanks!

> I removed a Regex and it solved the problem, but my guess is that the problem is caused by something else.

That statement worries me a little bit. Could you post the ID of your Git commit so that I can see what you changed? I may not understand it, but I can see how it "smells", as they say.

**Comment by LeaVerou** [comment]
@garretwilson you can see his PR and all its comments too, it’s referenced right above your comment.

**Comment by garretwilson** [comment]
(I'm now seeing that you looked into this more as part of #880, so if you don't have any doubts about it, no problem. It seems to work for me.)

**Comment by garretwilson** [comment]
So I guess you're saying the fix is 704ba4f951418ad8c6680a47a3f0381cb7c06bbd ? If so, it looks like it's doing the incorrect EOL checking, as [you commented elsewhere](https://github.com/PrismJS/prism/pull/880#issuecomment-180697468). I added a comment to the commit.

**Comment by LeaVerou** [comment]
You’re looking at the wrong commit. Just go to "Files changed" in the PR.

**Comment by garretwilson** [comment]
Oh, I see---that's a pull request. Someone had indicated a commit ID, so I thought that was the code. I haven't worked with pull requests on GitHub. So the fix was just to remove the whole thing. OK, if that works.

Sorry for static, and thanks for pointing me in the right direction.

**Comment by garretwilson** [comment]
I just wanted to say that I've been using `<mark>` for a while in Prism, and it's working like a dream! So useful. Thanks for the effort done to get this working.
