### ISSUE TITLE
linear-gradient syntax in CSS

### ISSUE THREAD

**Issue by eximius313** [PrismJS/prism#881]
In these two lines:
https://github.com/PrismJS/prism/blob/gh-pages/themes/prism-twilight.css#L166
https://github.com/PrismJS/prism/blob/gh-pages/plugins/line-highlight/prism-line-highlight.css#L17
```linear-gradient``` attribute should be set according to this guidelines: http://www.w3schools.com/css/css3_gradients.asp#grad3

**Comment by LeaVerou** [comment]
Please don't use w3schools, for your own good. Use MDN or the W3C specs.

However in this case, the point is correct: We need to convert `left` to `to right`. When this code was written, the syntax of `linear-gradient` was different.

**Comment by eximius313** [comment]
good to know - thanks ;)

**Comment by LeaVerou** [comment]
Feel free to send a pull request if you want to fix it yourself btw!
