### ISSUE TITLE
[keep-markup] Check if element actually has children

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#883]
It would be a nice perf improvement if we checked if `env.element.children.length > 0 and returning if not, since if there's no markup to keep there's no point in doing anything out of the ordinary for the current element. 

@Golmote?

**Comment by zeitgeist87** [comment]
> It would be a nice perf improvement if we checked if `env.element.children.length > 0 and returning if not,

This works very well. Browser support shouldn't be a problem either. I used it for #884.

**Comment by Golmote** [comment]
(Fixed in f1c719945d74889757bfd7152763fff7cbb46724)
