### ISSUE TITLE
Line numbers + Readium for Chrome

### ISSUE THREAD

**Issue by ignaciogros** [PrismJS/prism#886]
**Update:**

I think that the problem is not in Prism, but in Readium. I asked their developers: https://github.com/readium/readium-js/issues/135

**The original message** (in case anybody has a similar problem)**:**

Hi.

I know it's not an important issue, but the line numbers are not shown in ePub + Readium for Chrome.

I still don't know if it's a Prism's issue or a Readium's one. Any ideas? I'll submit the solution if I find it before.

Thank you very much for all that work!

**Comment by zeitgeist87** [comment]
It seems to work with the epub-reader that is included with Calibre.

**Comment by ignaciogros** [comment]
Yes. I think it's a Readium's problem. Thanks!

**Comment by LeaVerou** [comment]
Closing then :)
