### ISSUE TITLE
PrismJS lack of documentation

### ISSUE THREAD

**Issue by felixsanz** [PrismJS/prism#895]
I'm saving several problems trying to use every functionality of PrismJS, the documentation is nearly inexistent for both Prism and plugins.

For example, the line-numbers plugin doesn't have any info about how to use the plugin. It just say "drop line-numbers class to pre", and thats all. But how do you import the plugin?

The only example contains this:

```html
<script src="prism.js"></script>
<script src="plugins/line-numbers/prism-line-numbers.js"></script>
<script src="utopia.js"></script>
<script src="components.js"></script>
<script src="code.js"></script>
```

What is utopia.js for? and components.js? and code.js?

Also, Prismjs website lack of menus for navigating, the only menu i see is the left one which is bugged and hides below other elements.

The file https://github.com/PrismJS/prism/blob/gh-pages/README.md is kind of a joke, no offense.

Thats my thoughts about documentation. What i'm really trying to do is use the plugins inside node application. Currently, i have this integration with markdown-it:

```javascript
const md = markdownIt({
  html: true,
  highlight(str, lang) {
    require(`prismjs/plugins/line-numbers/prism-line-numbers.js`) // <-- no way, this doesn't works

    const language = (!lang || lang === 'html') ? 'markup' : lang

    if (!prism.languages[language]) {
      require(`prismjs/components/prism-${language}.js`)
    }

    return prism.highlight(str, prism.languages[language])
  },
})
```

But plugins doesn't work, no matter what i do! :/

**Comment by LeaVerou** [comment]
No offense back at you, but did you actually try visiting the [download page](http://prismjs.com/download.html)? You know, the huge blue download button on the header of every page?

**Comment by felixsanz** [comment]
@LeaVerou  Why would i do that? I'm using node, not browser. So i get everything with `npm install prismjs`. My folder `node_modules/prismjs/plugins/` contains all plugins already, but i just can't use them with node, or i don't know how.

For example, line-numbers plugin starts with:

```
if (typeof self === 'undefined' || !self.Prism || !self.document) {
	return;
}
```

It always return because `self` doesn't exist. I don't want to use it in the browser, i want to pre-process every code block in the server.

**Comment by felixsanz** [comment]
Ok, it's impossible to use plugins in the server. Some plugins also  use `document` var. :(

**Comment by LeaVerou** [comment]
Prism itself works on the server, but most plugins do not.

The takeaway from this is that there should be a notice on each plugin’s page about whether it’s compatible with Node or not, so that people don't have to peek into the code.

However, you might want to tone down the disgruntled customer attitude next time you post an issue at an open source project. Nobody here is being paid to serve you, we're all working on Prism on our spare time, for free. By using this kind of tone, you're putting off everyone from helping you or being polite to you, making Github a worse place for everyone.

**Comment by felixsanz** [comment]
I wasn't trying to sound rude, i'm sorry it seems so. I was just trying to say that the website lacks heavily on documentation, i know it's an open-source project, but i can't contribute/help much if the core features are not well explained. Things like `callback is a function that accepts one parameter: an object with various variables that can be modified` doesn't help :(

**Comment by LeaVerou** [comment]
Not sure where that part is from, but plugins are often contributed via pull requests from outside contributors (i.e. non team members), and thus documentation is of variable quality. We still think it's best to include them anyway, than reject the PR on the grounds of insufficient documentation.

**Comment by felixsanz** [comment]
thats from PrismJS API Docs page, which is only accesible from a link on the footer

**Comment by LeaVerou** [comment]
Yeah, it’s from [here](http://prismjs.com/extending.html#writing-plugins).
Apart from changing "variables" to "properties", I’m not quite sure how to best explain that. The properties on `env` depend on the hook used, so there's no more specific description that we're withholding.
If you have any suggestions about how that paragraph could be made more clear, be my guest.
Also, this section is intended for people who want to write their own plugins, not just use Prism. To write your own plugins, a basic level of familiarity with the codebase is required.

**Comment by felixsanz** [comment]
Yup, i was not trying to write my own plugin, just trying to use existing ones outside the browser scope. Would be awesome if that worked btw, but can't complain on that, thats how it is :sweat_smile: 

Thanks
