### ISSUE TITLE
Xojo (past aka. REALBasic) Language

### ISSUE THREAD

**Issue by neu1886** [PrismJS/prism#898]
Hi, could you please add the [Xojo (Language Reference)](http://developer.xojo.com/language) Syntax as new language?

**Comment by zeitgeist87** [comment]
We already have the language Basic. How much difference is there between Xojo and normal Basic? Maybe you could try `prism-basic.js` and give us a concrete list of things, that are missing?

**Comment by neu1886** [comment]
Know...there arme a löst of differences. I can sent you a list with all keywords, functions etc.

**Comment by neu1886** [comment]
To be continued

# Commands	

#Bad
#Else
#ElseIf
#If
#EndIf
#Pragma
#Tag
AddHandler
App
Array
As
Assigns
ByRef
ByVal
Break
Call
Case
Catch
Const
Continue
End
CurrentMethodName
Declare
Dim
Do
Do...Loop
DownTo
Each
Else
ElseIf
End
Enum
Exit
Extends
False
Finally
For
For...Next
For Each...Next
Global
If
If...Then...Else
In
Lib
Line Continuation
Loop
Me
Next
Nil
Optional
ParamArray
Raise
RaiseEvent
ReDim
Rem
RemoveHandler
Return
Select
Select...Case
Self
Soft
Static
Step
Super
Then
To
True
Try
Try..Catch
Ubound
Until
Using
Wend
While
While...Wend


# Data Types
Auto
Variant
Boolean
Colors: &cRRGGBBAA
Currency
Double
Integer
Int8
Short
Int16
Int32
Int64
UInteger
UInt8
UInt16
UInt32
UInt64
Byte
Single
Text
String
Dictionary
DictionaryEntry
Collection
Date
DateInterval
MemoryBlock
MuteableMemoryBlock
Point
Rect
Size
BinaryStream
FolderItem
TextInputStream
TextOutputStream

# Literals

"" (String/Text)
&b (Binary Literal)
&h (Hexdecimal Literal)
&o (Octal Literal)
&u (Unicode Literal)

# Operators

+
AddressOf
And
CType
/
^
\>
\>=
Is
IsA
<
<=
Mod
*
New
Not
<>
Or
\-
Xor
WeakAddressOf

# Methods

Abs
ACos
ASin
ATan
ATan2
Ceil
Cos
Exp
Floor
Log
Max
Min
RandomInt
Round
Sign
Sin
Sqrt
Tan
