### ISSUE TITLE
finding CSS style codes used by a theme

### ISSUE THREAD

**Issue by garretwilson** [PrismJS/prism#900]
I love the coy theme. I'm wanting to make some other things on my page to use the same styles as the coy theme so that everything will look uniform.

What's the easiest way for me to find out some of the CSS definitions/colors used by the coy theme? Specifically I'd like to know the background color used for the even rows.

(Since I'm here, I might as well ask: is there any easy way to override the colors used by a Prism theme?)

Thanks!

**Comment by lukasoppermann** [comment]
All themes can be found here: https://github.com/PrismJS/prism/tree/gh-pages/themes you can also easily overwrite anything. Just create a new css file based on one of the themes and load this instead of the default prism.css

**Comment by Golmote** [comment]
I consider the question answered. I'm closing the issue ;)
