### ISSUE TITLE
Prism can't be used with EPUB due to `direction: ltr` in CSS

### ISSUE THREAD

**Issue by dauwhe** [PrismJS/prism#902]
Ric Wright of Readium just [posted a question](https://groups.google.com/forum/#!topic/epubcheck/x8gx3PV1SZY) to the EPUBCheck mailing list. EPUB doesn't allow the `direction` property in CSS, as the writing modes spec says it should not be used with HTML. Thus, when using the library, EPUBs fail validation, which prevents them from being distributed or sold through most commercial channels.

Is there significant risk in removing `direction: ltr` from Prism's stylesheets?

Thanks,

Dave

**Comment by Golmote** [comment]
According to the spec, authors should use the "dir" HTML attribute rather than the "direction" CSS property. So I guess it should be fine.

Users who need to force code direction will still be able to set the attribute directly on their tags.

**Comment by LeaVerou** [comment]
Yeah, let's remove it.
Didn't know epub even supported JS. Cool!

**Comment by zeitgeist87** [comment]
I've removed it from all themes.

**Comment by strgg** [comment]
you could parse it through prism's javascript and then just use the created code (with span's etc) to inlcude it with html and css only. so there is no need for javascript in your ebbok
