### ISSUE TITLE
Whitespace Normalizer doesn’t work with Unescaped Markup

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#903]
CC @zeitgeist87 

I tried to debug it and if I add this to my plugin it works:

```js
if (Prism.plugins.NormalizeWhitespace) {
	env.code = Prism.plugins.NormalizeWhitespace.normalize(env.code);
}
```

However, I was wondering if there's any more elegant way to fix it, as this is basically duplicating what your plugin does...

**Comment by zeitgeist87** [comment]
The problem is, that `normalize-whitespace` forces itself to the top of the callback list for the `before-highlight` hook:

```js
// Make sure our callback runs first
var hooks = Prism.hooks.all['before-highlight'];
hooks.unshift(hooks.pop());
```

But it only runs if the parent node is a `pre` tag, which fails for `script` tags before the `unescaped-markup` plugin is run:

```js
var pre = env.element.parentNode;
if (!env.code || !pre || pre.nodeName.toLowerCase() !== 'pre' ||
		(env.settings && env.settings['whitespace-normalization'] === false))
	return;
```

So if I remove the forcing to the top of the callback list, and ensure that `unescaped-markup` is loaded before `normalize-whitespace`, everything works. I think that is the best option. I will continue my work on the `"after"` property in `components.js`, so that the download page adds them in the right order.

**Comment by zeitgeist87** [comment]
A lot of plugins check for the `pre` tag to determine if it is a code block. So `unescaped-markup` has to run before all other plugins, to make sure the `script` tags are converted.

**Comment by zeitgeist87** [comment]
We could also add a new earlier hook to solve this problem. A new hook would also be nice for #893. I am not sure, what's the best approach here. What do you think?

**Comment by LeaVerou** [comment]
All three :)

1. Yes, we should have a reasonable order in components.js
2. That can be achieved by putting Unescaped Markup first.
3. A new hook would be nice regardless.

I tend to be opposed to things like anything forcing itself to be first or last, unless it's really a last resort. This is why in CSS we end up with unmaintainable websites with `z-index: 99999999999999`. Because every element thought it had the right to be first.

**Comment by zeitgeist87** [comment]
I've just removed the force-to-the-top hack from `normalize-whitespace` and I added a new hook to #893. I'll work on the order in `components.js` later...

**Comment by Golmote** [comment]
@zeitgeist87 @LeaVerou So... did #893 fix this issue?

**Comment by zeitgeist87** [comment]
Yes everything here has been implemented:
 
* Remove force-to-top for `normalize-whitespace`
* Add new hook `before-sanity-check`
* Add `"after"` property for components, so the downloader can put them in the right order, `"after"` is a weak version of `"require"`. It means that the component does not require anything, but if the target is loaded the component has to be loaded after it.
