### ISSUE TITLE
How to apply style to dom generated after page initially loaded

### ISSUE THREAD

**Issue by elgs** [PrismJS/prism#907]
I have no problem styling code already existed while the page is initially loaded. However, if the code was inserted by an ajax callback which is dynamically generated after the initial page load. The prism style doesn't not apply to the new code. Is there any javascript I need to run manually in order to apply prism style to the dynamic code? Thanks.

**Comment by LeaVerou** [comment]
Prism only runs on DOMContentLoaded and highlights what's there. To highlight any other element, use `Prism.highlightElement()`. If there are many, use `Prism.highlightAll()`, but keep in mind that will also go over already highlighted elements and re-highlight them.
For more info on Prism's JS API, look here: http://prismjs.com/extending.html#api

**Comment by elgs** [comment]
Thanks @LeaVerou it works.
