### ISSUE TITLE
Does not seems to support markdown

### ISSUE THREAD

**Issue by elgs** [PrismJS/prism#908]
PrismJS is said to support markdown. However, when I have the following code in my html:

    <pre><code class="language-markdown">
        `df` to show result.
        # title
        `hello` world
    </code></pre>

The result looks the same as the code. Back ticks do not seems to be effective.

**Comment by LeaVerou** [comment]
ping @Golmote

**Comment by Golmote** [comment]
You must not use indentation inside the tag. Indented text in markdown is interpreted as code.

If you don't indent it, it should be fine, as you can see on the [test page](http://prismjs.com/test.html):

![http://puu.sh/nIZDC/4ed58c7145.png](http://puu.sh/nIZDC/4ed58c7145.png)

**Comment by elgs** [comment]
I see. It's not evaluating markdown, instead it highlights it. Thanks.
