### ISSUE TITLE
data-src not importing file (same domain)

### ISSUE THREAD

**Issue by JRCrawford** [PrismJS/prism#909]
This library looks great. I did however notice that the `data-src` tag is not working.  I have the following code:

```
<pre class="language-none line-numbers">
    <code>aaaa
     bbbb
     cccc
    </code>
</pre>
    
<pre class="line-numbers" data-src="http://www.wbpractices.com/prism-line-numbers.js"></pre>
    
<pre class="command-line" data-user="root" data-host="localhost">
    <code class="language-bash">
        cd   /usr/local/etc
        cp php.ini php.ini.bak
        vi php.ini
    </code>
</pre>
```

All of it works except the "data-src" part.  That looks [just like this](http://i.imgur.com/b8l0bq7.png)

Note this is all running on the same domain which can be seen here: http://www.wbpractices.com/development/

**Comment by LeaVerou** [comment]
You don’t seem to have the file highlight plugin loaded.

**Comment by JRCrawford** [comment]
Ah, I thought that this was part of the core library. This was indeed the issue.
