### ISSUE TITLE
Add file-name info to code block

### ISSUE THREAD

**Issue by lukasoppermann** [PrismJS/prism#910]
Hey, it would be awesome to be able to say state which file one is working on, like so:

```html
<pre><code data-file="prism.js">
   ... code
</pre></code>
```

This would add something like http://prismjs.com/plugins/show-language/ with the filename in it. 
Although I think it would be nice if it was within the `<pre>` tag so that it is all group within a main container.

I am writing some posts with lots of code, so for this it would be very nice to be able to add the filenames.

**Comment by mAAdhaTTah** [comment]
This could be achieved with the Toolbar plugin I'm working on in #891. We're still working out questions about how to handle the Clipboard.js dependency, but you can definitely use it now to add your own label if you want. I'm using it in a WordPress to do exactly that.

**Comment by lukasoppermann** [comment]
Hmm, interesting. But it seems a little overkill for this small thing. Wouldn't it make more sense to change the `show language` plugin to pickup all `data-label-xyz` attributes and put them into a a div within the `<pre>`? 

Your toolbar plugin could than require this plugin and add buttons to this div.

**Comment by mAAdhaTTah** [comment]
I would be the opposite. You pull in the toolbar plugin which just makes a function available to you to register your own buttons with. You could then register a function that will check that data attribute and add the file name label.

**Comment by mAAdhaTTah** [comment]
If we needed an HTML API for the toolbar plugin, that's definitely possible, but hasn't been implemented yet, since I don't know what that would look like.

**Comment by lukasoppermann** [comment]
Hmm, sounds like a good idea, but didn't you say it has a `Clipboard.js` dependency? If it is a basis for many plugins and such, it should be as slim as possible.

**Comment by mAAdhaTTah** [comment]
Toolbar plugin doesn't. Copy to Clipboard plugin does, as well as having a dependency on the toolbar plugin itself.

**Comment by lukasoppermann** [comment]
Ahh, then it was a misunderstanding. So how would I go ahead adding this functionality?

**Comment by mAAdhaTTah** [comment]
No worries, there are two plugins in that PR, so the confusion is understandable.

To use it, add `prism-toolbar.js` from the PR and its matching CSS to your project (which could be different depending on how you're developing) and check the `index.html` file in that plugin's folder for how to register a new button. If the documentation is confusing or unclear, let me know so I can update it for others.

**Comment by lukasoppermann** [comment]
Hey @mAAdhaTTah thank, this worked fine like so:

```javascript
Prism.plugins.toolbar.registerButton(function(env) {
	var button = document.createElement('span');
	button.innerHTML = env.element.parentNode.getAttribute('data-label-file');
	return button;
});
```

But would it not make sense to merge your toolbar with the language plugin and extend the language plugin to pick up everything with a data-label-x attribute?

**Comment by mAAdhaTTah** [comment]
I'd be open to that. Would be up to the maintainers whether they'd want the Toolbar plugin to supersede the language plugin like that though, given whatever BC issues may arise.

**Comment by LeaVerou** [comment]
@lukasoppermann You can just add a pseudoelement, like so:

```css
pre[data-file] {
  content: attr(data-file);
  position: absolute;
  top: 0;
  right: 0;
}
```

**Comment by lukasoppermann** [comment]
Hey @LeaVerou ,

I guess you mean:

pre[data-file]:before {
```
  content: attr(data-file);
  position: absolute;
  top: 0;
  right: 0;
}
```

Which is very true, thank you for the tip. The only "issue" I have with it, is that it makes it hard to add more content. If I wanted to add an icon to this I am more limited, etc. because I am already using one of the two pseudo elements.

**Comment by LeaVerou** [comment]
Oops, yes! Thanks, edited.

You're limited when using an attribute as well. How would you put the icon there? Would you put HTML in an attribute? Ewwww. :P

**Comment by mAAdhaTTah** [comment]
With the toolbar plugin, you could process it in js first.

**Comment by lukasoppermann** [comment]
Yes, that was the idea:

`data-label-file` would be turned into something like:

```html
<span data-label-file="file.php">file.php</span>
```

So this way you could via css add a pseudo-element for the icon (but you have more options, for multiple attributes as well, since every attribute adds a span element e.g. to the toolbar).

Anyway, I think it could be pretty neat, maybe just by extending/generalising the language plugin to a label-plugin or something.

However, with your css idea and the toolbar plugin, I do have enough options available for my current use-case.

**Comment by LeaVerou** [comment]
Note that it's super easy to roll your own plugin, by modifying the Show Language one.

At this point, I don't think it's wise to address individual use cases, but it's clear the use cases extend to more than simply showing the language, so we should make the Show Language plugin more generic, IMO.

**Comment by lukasoppermann** [comment]
Hey @LeaVerou I am totally with you on this, maybe we should open a new ticket to discuss how the language plugin could be extended / replaced with a more generic plugin that serves the old purpose, but also the new?
