### ISSUE TITLE
Extend / replace "show language" to be more generic 

### ISSUE THREAD

**Issue by lukasoppermann** [PrismJS/prism#914]
As discussed in https://github.com/PrismJS/prism/issues/910 it would be helpful if the [show language](http://prismjs.com/plugins/show-language/) plugin would be replaced by a more generic version that can add different custom labels to a prism instance.

Some features could be:
- add multiple custom labels
- auto-add language (if desired)
- add a div to collect all labels (could be used as a bar on top or bottom, but could also be ignored, so that individual items can be styled, whatever a user wants)
- if something like the `config` from https://github.com/PrismJS/prism/issues/912 should be implemented, this plugin could use a config option to receive all items it should grab

There could be some overlap with the toolbar plugin from https://github.com/PrismJS/prism/pull/891
The question is, if it would make sense to combine it with the toolbar or if they are to different in the idea. I think we should still try to keep it as small and simple as possible.

**Comment by mAAdhaTTah** [comment]
I think the main difference between the `show-language` plugin & the `toolbar` plugin is the styles, honestly. I do know, for now, they don't play well together, so perhaps one should supersede the other. #

**Comment by mAAdhaTTah** [comment]
These have been combined now, so this is resolved.
