### ISSUE TITLE
Blogger mode

### ISSUE THREAD

**Issue by VahidN** [PrismJS/prism#915]
Blogger adds `<br/>` instead of `\n` to posted codes automatically. It needs this fix to work:

``` javascript
/** Blogger mode flag. */
bloggerMode : false,

var br = /<br\s*\/?>/gi;    
if (config.bloggerMode == true){
    str = str.replace(br, '\n');
}

```

It's taken from `alexgorbatchev.com/SyntaxHighlighter`.

**Comment by Golmote** [comment]
I'll close this issue as a duplicate of #832. Hopefully the same solutions apply.
