### ISSUE TITLE
Used By "Drupal.org"

### ISSUE THREAD

**Issue by darol100** [PrismJS/prism#920]
### Something to consider
Drupal.org just recently implement this library in their website. See more at - https://www.drupal.org/node/2689337 Drupal is pretty big open source project and I think it will be worth it to mention it like is another website that uses prismjs.

**Comment by LeaVerou** [comment]
Yes, we should!
Anyone willing to add it?

**Comment by zeitgeist87** [comment]
> Yes, we should!
> Anyone willing to add it?

I've created a PR #924
