### ISSUE TITLE
Support HTTPS on prismjs.com

### ISSUE THREAD

**Issue by fuzzyroddis** [PrismJS/prism#926]
To prevent a man-in-the-middle messing with downloaded code, could you please support HTTPS?

https://letsencrypt.org/
https://startssl.com

**Comment by zeitgeist87** [comment]
The Prism website is hosted by Github Pages https://pages.github.com/. Is it possible to use HTTPS with that?

**Comment by fuzzyroddis** [comment]
Sadly not directly :( But it is possible to put Cloudflare in front of it using it's "Universal SSL"

https://support.cloudflare.com/hc/en-us/articles/203663694-How-do-I-enable-free-Universal-SSL-with-Github-

**Comment by LeaVerou** [comment]
Given that Cloudflare is not free, if you want to pay for it @fuzzyroddis, I'm game. Otherwise, I'm not sure how that would work, given that Prism is a non-profit project with no funds.
(Hmm, I wonder if there's a good service to use that is easy to set up, to let people donate to the project. It would be useful for things like this)

**Comment by fuzzyroddis** [comment]
@LeaVerou totally understand about costs. https://www.cloudflare.com/plans/ has a free plan, which is probably just burning through their vc money at this point :P

**Comment by mAAdhaTTah** [comment]
[GitHub has enabled this for free for custom domains with LetsEncrypt](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/). @LeaVerou I think an admin needs to make the changes to turn this on.

**Comment by LeaVerou** [comment]
When I go to do that, it's not enabled 😕 

![image](https://user-images.githubusercontent.com/175836/40669642-15c9d8b2-6370-11e8-8919-5039247d705f.png)

**Comment by Golmote** [comment]
> Unavailable for you site because your domain is not properly configured to support HTTPS.

I guess there is some action to perform on the domain to enable/configure a LetsEncrypt certificate first, before we can enforce HTTPS.

**Comment by mAAdhaTTah** [comment]
Sweet! Happy to help.
