### ISSUE TITLE
Highlighting doesn't work in Chrome

### ISSUE THREAD

**Issue by mastertinner** [PrismJS/prism#934]
I'm using PrismJS on my [Ghost](https://ghost.org/) blog: https://berndsgn.ch/

The syntax highlighting works well in any browser (even Chrome on mobile) except for Chrome on desktop where it doesn't show at all. I'm using the latest Chrome (Version 50.0.2661.75 (64-bit)).

**Comment by mAAdhaTTah** [comment]
FWIW, I looked at your site on both Chrome & FF, and neither of them highlight. I also see an error in the console in Chrome from an unrelated script.

**Comment by mastertinner** [comment]
thanks, @mAAdhaTTah. i didn't know that i had the same problem with FF... i have no idea where it comes from though...

**Comment by LeaVerou** [comment]
Interestingly, it works if I call `Prism.highlightAll()` from the console, so it looks like some sort of race condition. Perhaps you're loading the posts asynchronously?

**Comment by Golmote** [comment]
This issue did not appear to be due to Prism itself, so I'm closing it.
