### ISSUE TITLE
Problem prismjs and tinymce

### ISSUE THREAD

**Issue by viriis** [PrismJS/prism#936]
Hi,

I would like to know how to do for have 2 tinymce with "prismjs" in the same page

Exemple: [](http://www.viriis.com/testTynimce.php)

The first it's ok but the seconde doesn't work

Thank you very much for your help

**Comment by Golmote** [comment]
Please provide a link to an online page reproducing the issue.

**Comment by viriis** [comment]
Sorry

http://www.viriis.com/testTynimce.php

Thank you

**Comment by Golmote** [comment]
As far as I can tell, the plugin works properly, except the Prism stylesheet is not included in the second editor. This is probably an issue you should file directly on the [TinyMCE repo](https://github.com/tinymce/tinymce).

**Comment by viriis** [comment]
Ok Thank you very much for your help :)
