### ISSUE TITLE
Problem with language-apacheconf

### ISSUE THREAD

**Issue by KhanMaytok** [PrismJS/prism#951]
When I type:

```
<pre>
<code class="language-apacheconf">
<Directory "/var/www/html">
    AuthType Basic
    AuthName "Restricted Content"
    AuthUserFile /etc/apache2/.htpasswd
    Require valid-user
</Directory>
</code>
</pre>
```

The render that I get is 

```
<Directory "/var/www/html">
    AuthType Basic
    AuthName "Restricted Content"
    AuthUserFile /etc/apache2/.htpasswd
    Require valid-user
```

Last line `</Directory>` is not displayed

**Comment by Golmote** [comment]
Hi. I think you need to escape the chars `<` and `>` (as `&lt;` and `&gt;` respectively) inside the `<code>` tag. Otherwise they might be awkwardly interpreted by your browser.

**Comment by LeaVerou** [comment]
Actually, only `<` needs escaping, not `>`.

**Comment by KhanMaytok** [comment]
Many thanks, problem done
