### ISSUE TITLE
Provide option to download minified CSS

### ISSUE THREAD

**Issue by CITguy** [PrismJS/prism#956]
The download page includes the option to get a full development vs minified source, but this option does not extend to the CSS (see gif below). 

![prismjs-download-minified-no-css](https://cloud.githubusercontent.com/assets/545605/15304218/a8ffe9a2-1b81-11e6-8d6b-12b881722254.gif)

Is it possible to add minification to the CSS source?

**Comment by LeaVerou** [comment]
The reason is that most people modify the CSS at least to a degree, but don't modify the JS. Also the CSS is much smaller, so it's not really worth it to minify.

**Comment by hc-codersatlas** [comment]
Useful to provide this for users using prism via cdn, e.g. jsdelivr and unpkg? We override the css after including the CDN file.
