### ISSUE TITLE
Dynamic language-definitions load - documentation needed

### ISSUE THREAD

**Issue by soar** [PrismJS/prism#960]
[Download page](http://prismjs.com/download.html) offers to download All-In-One JS file. With all available languages (what if I need them all?) this file weights about 250 KB and it will slow page loading and processing.

But [here](http://prismjs.com/plugins/autoloader/) is some information about "Autoloader" plugin, which should take care about language processing. This sounds good, but where is documentation about this feature? Where should I download "core" version of Prism? Where should I download language-definitions? Where should I place them?

**Comment by LeaVerou** [comment]
I think if you're using the autoloader the easiest way is to just clone the repo and take the components folder from there. You can then download Prism core & any plugins from the Download page, without checking any languages (or just check the languages you want to load by default, e.g. if you're using a language a lot, then you probably want to save the extra HTTP request).

@Golmote, perhaps we can add something like the above to the plugin's documentation? Is there an easy way to provide a download of the components folder as a zip without having to manually update it?

**Comment by Golmote** [comment]
Hi! Sorry for the late answer. I updated the plugin documentation to include info on how to get the grammars.

We could also add a "Download all languages grammars" button on the plugin page, that would generate a zip file automatically in JS. I gave it a try and it seems to work pretty well, using [JSZip](https://github.com/Stuk/jszip) and [FileSaver](https://github.com/eligrey/FileSaver.js). I will make a PR so you can take a look.
