### ISSUE TITLE
Help needed: Layout not being prettified again when content being updated

### ISSUE THREAD

**Issue by rmhrisk** [PrismJS/prism#961]
First thanks for the library, it is great.

I have a demo for a library we created here - https://xadesjs.com/

It loads external XML file into an element, it is then made pretty by prism.

Then the user clicks "sign" I update the element, run highlightElement and it is made highlighted by the layout of the XML is not made pretty.

(search for the ds:signature element in the end of the pre to see what I am referring to)

Source : https://github.com/PeculiarVentures/xadesjs/blob/gh-pages/index.html

I searched past issues and the web but had no luck in finding an answer, help is appreciated.

**Comment by LeaVerou** [comment]
What do you mean by "it's not made pretty"? It seems fine to me. Is the first line break stripped? Perhaps that's the problem?
Which plugins do you have loaded?

**Comment by rmhrisk** [comment]
My issue, please forgive.
