### ISSUE TITLE
JavaScript highlighting should be improved

### ISSUE THREAD

**Issue by felixsanz** [PrismJS/prism#963]
JS highlighting fails too much, even at simple use cases. Example:

![Examle](http://i.imgur.com/x0vxPHf.png)

Most of it it's wrong. I wish i could provide a patch but i can just report it.

**Comment by Golmote** [comment]
Please provide the entirety of the code you're trying to highlight. It seems to me that the initial highlighting problem occurs before this snippet.

**Comment by felixsanz** [comment]
You're right. That single piece works better as standalone.

```
import cluster from 'cluster'
import os from 'os'
 
const workers = os.cpus().length
 
cluster.setupMaster({ exec: 'app.js' })
 
function log(msg) {
  console.log(`[SERVER] ${new Date().toISOString().replace(/T/, ' ').replace(/\..+/, '')} ${msg}`)
}
 
log(`Master with pid ${process.pid} starting...`)
 
for (let i = 0; i < workers; i++) {
  cluster.fork()
}
 
cluster.on('exit', (worker, code, signal) => {
  log(`worker with pid ${worker.process.pid} died. Restarting...`)
  cluster.fork()
})
 
cluster.on('online', worker => {
  log(`Worker with pid ${worker.process.pid} started`)
})
```

**Comment by Golmote** [comment]
@LeaVerou @zeitgeist87 Does it look safe to you to move up the template string pattern in the language definition of JS so that it's processed before normal strings? IMO it is much more common to encounter quotes inside template strings than backticks inside normal strings. What do you think?

**Comment by LeaVerou** [comment]
Agreed.

**Comment by zeitgeist87** [comment]
If we move the `template-string` before `string`, then one of the tests for `coffeescript` fails, because `coffeescript` uses backticks for inline javascript. However this is easily fixed by adding the following line to the `coffeescript` language:

```js
delete Prism.languages.coffeescript['template-string'];
```

Shall I commit my changes?

**Comment by LeaVerou** [comment]
Sounds good to me!

**Comment by Golmote** [comment]
Yup, agreed!

**Comment by zeitgeist87** [comment]
Should be fixed with [[`1158e46`](https://github.com/PrismJS/prism/commit/1158e46)]

**Comment by felixsanz** [comment]
I was about to test this (even if it's already a closed issue...) to report the status and how that code renders now, but i don't know how to install this with npm since this versions are published into gh-pages branch (uh?), and that is not released into npm, right?

How i do install it then?

**Comment by zeitgeist87** [comment]
For a quick test you can use http://prismjs.com/test.html or check out the gh-pages branch manually. The fix will be published to npm with the next release, which should be soon.

**Comment by felixsanz** [comment]
Can we have a `@next` tag in npm that downloads the gh-pages version? Releasing this way is a pain. Last release is more than a month ago, i think faster releases would be better, for bugs or features.

**Comment by felixsanz** [comment]
this look much better now, thanks

**Comment by exander77** [comment]
It still seems to be broken for backticks:
```
var a = [
    '`a',
    '`b'
];
```
