### ISSUE TITLE
Whitespace normalizer has no way to opt out

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#964]
@zeitgeist87 could you please add a class or something so that people can opt out of normalization? Ideally it should support inheritance, but we can add that later, once we flesh out the settings plugin.
I was using it today, and realized I can't seem to be able to turn it off for certain `<pre>`s.
If it's already possible, it needs to he added to the docs. Though I looked at the code and didn't find anything.

**Comment by zeitgeist87** [comment]
Yes it was supposed to use the settings plugin. I've implemented your suggestions a month ago #851 and it works very nicely. I've implemented specs, type casting and default values. Unfortunately it is too much code to include it into `prism-core.js`. @LeaVerou Do you have any suggestions to make it smaller?

**Comment by zeitgeist87** [comment]
I can of course add a simple class to opt out of the normalize-whitespace plugin, but I would prefer it if we could merge the parse-settings plugin.

**Comment by LeaVerou** [comment]
Oops, I completely missed that you implemented specs. Will try to find time to review soon, I'm really swamped with preparing a talk right now :(
