### ISSUE TITLE
Npm beta version

### ISSUE THREAD

**Issue by felixsanz** [PrismJS/prism#966]
Can we have a `@next` tag in npm that downloads the gh-pages version? Releasing this way is a pain. Last release is more than a month ago, i think faster releases would be better. faster bugs fixes and features that we can test and provide feedback before published into master.

**Comment by Golmote** [comment]
That's a nice idea.
I guess it would still require publishing to npm, right? We do not have automated publishing at this time, and I think @LeaVerou is the only one who currently has the rights to publish...

**Comment by larshp** [comment]
Does anyone know when the next release is planned?

**Comment by QuantumInformation** [comment]
Where are the npm installation instructions?

**Comment by Golmote** [comment]
@QuantumInformation npm installation instructions are on [the homepage of the website](http://prismjs.com/#basic-usage).
@felixsanz I realized that if you really want to use the `gh-pages` version in your projects, you can already use a direct link to github ([see this SO answer](https://stackoverflow.com/questions/39732397/install-specific-branch-from-github-using-npm)). So I don't think we need this `@next` tag. Also, I'm trying to set up regular releases, based on the change activity.
