### ISSUE TITLE
support for .properties file syntax

### ISSUE THREAD

**Issue by garretwilson** [PrismJS/prism#970]
Surprisingly I just noticed that there seems to be no support for the ubiquitous Java [properties file format](https://en.wikipedia.org/wiki/.properties). Am I missing it under a different name?

**Comment by mAAdhaTTah** [comment]
It's similar to `.ini`, right?

**Comment by garretwilson** [comment]
It's similar, yes, but but not identical.

**Comment by garretwilson** [comment]
I just had an idea, based upon @mAAdhaTTah 's comment. If someone could simply copy the `language-ini` plugin to make an identical `language-properties` plugin, that would be helpful. The greatest benefit would be that it would allow us to include `language-properties` in our content and let the plugin be improved later. This would be better than putting an artificial `language-ini` identifier in our source code that would need to be changed later.

**Comment by LeaVerou** [comment]
You could run:

```js
Prism.languages.properties = Prism.languages.ini
```

right after including Prism. Once eventually there is a proper definition for this language, you remove the line. Would that work for you?

**Comment by garretwilson** [comment]
You mean insert some sort of custom JavaScript every time I include `prism.js`? That's a little unwieldy, especially since I have so much content that already includes `prism.js` I'd have to add an extra `<script>` tag, right? And then go through and remove them all once Prism got the `properties` language type?

**Comment by LeaVerou** [comment]
Or you can just insert it at the end of prism.js, but that means it's more of a hassle to update Prism.

**Comment by garretwilson** [comment]
Oooh! So can I fork Prism and make a pull request with `prism.js` updated with `Prism.languages.properties = Prism.languages.ini` at the end ... for the time being? Or is there a better approach?

**Comment by Golmote** [comment]
If you can wait til the end of the week, I will merge PR #980

**Comment by garretwilson** [comment]
Oh, sure, that would be awesome! There's no emergency on my part---I was just wanting to register the issue so it could be addressed.

Let me know when it is merged so that I can update my documents with the correct Prism language ID.

Thanks!!

**Comment by Golmote** [comment]
@garretwilson It is merged. ;)

**Comment by garretwilson** [comment]
It seems to work great, @Golmote ! Thank you so much for your work on this.

In the next month or two I plan on trying to build my own Prism language plugin for another format, so maybe I'll send you a private note later for you to give me some pointers.

All the best.
