### ISSUE TITLE
PHP comment block is not highlighted

### ISSUE THREAD

**Issue by felixsanz** [PrismJS/prism#973]
This comment:

```php
  /**
   * Create a new command instance.
   *
   * @return void
   */
```

Renders as:

```html
<span class="token comment" spellcheck="true">/**</span>
   * Create a new command instance.
   *
   * @return void
   */
```

So only first line is part of comment.

**Comment by Golmote** [comment]
I do not reproduce this issue on the [Test drive page](http://prismjs.com/test.html)...

**Comment by felixsanz** [comment]
Sorry i should have test that page first. It's a problem on my own :)
