### ISSUE TITLE
Line number shown incorrectly

### ISSUE THREAD

**Issue by anirudhb** [PrismJS/prism#975]
Hello. I have been using Prism for a few code examples. I have included the "Line Numbers" plugin. However, even with the JS and CSS, the line numbers do not appear. I have found a workaround, however.

Simply include the following CSS:
```
pre.line-numbers {
  padding-left: 3.8em;
}
```

However, I would like to merge this as a pull request (now #976). I will submit one shortly. Thanks!

**Comment by Golmote** [comment]
The line-numbers plugin is meant to be used with [its associated CSS file](https://github.com/PrismJS/prism/blob/gh-pages/plugins/line-numbers/prism-line-numbers.css), which already includes this padding.
