### ISSUE TITLE
Is it possible to push the anchor further with line highlight links ? (e.g, with persistent navigation header)

### ISSUE THREAD

**Issue by dmsimard** [PrismJS/prism#979]
I have a persistent navigation bar at the top of my web application.

The links, as per documented in http://prismjs.com/plugins/line-highlight/ will scroll down to that specific line. However, since I have a persistent top navigation bar, that line is hidden behind it and then I have to scroll up to actually see the line.

Is there a way to offset the anchor by a couple pixels (say 50 or so) so that the highlighted line(s) don't show behind my header ?

**Comment by dmsimard** [comment]
So I worked around the "scrollIntoView" function to "false" so the anchor would be at the bottom of the screen, not at the top.

**Comment by mAAdhaTTah** [comment]
There are a couple of techniques to solve this. I've used [this one](https://stackoverflow.com/a/13138463) before, but there are other suggestions in that SO thread. I don't think there's anything we can do in Prism to work around this.
