### ISSUE TITLE
Problem of rendering "<>"

### ISSUE THREAD

**Issue by MaherJendoubi** [PrismJS/prism#984]
Hi,

I wrote this : 
<pre class="line-numbers"><code class="language-csharp">public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
{
	app.UseMiddleware< LoggerMiddleware>(loggerFactory);
}

but I got this :
public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)  
{
    app.UseMiddleware(loggerFactory);
}

How to fix it please?

Thanks,
Maher

**Comment by Golmote** [comment]
You need to escape the opening `<` using `&lt;`. This is required to prevent your browser from interpreting this as a tag.

**Comment by MaherJendoubi** [comment]
@Golmote Thanks a lot!

**Comment by Golmote** [comment]
You're welcome ;)
