### ISSUE TITLE
Feature Request: vba and/or vbscript support

### ISSUE THREAD

**Issue by skftn** [PrismJS/prism#985]
:+1:

**Comment by kleerkoat** [comment]
would be nice!

**Comment by n1crack** [comment]
👍  yes please

**Comment by tfryman** [comment]
:+1: Please!

**Comment by the-wazz** [comment]
So there's no confusion, VBA is NOT VB. Maybe they can use the same scheme, I don't know, but VBA is the coding language of MS Office products. Open an Excel doc, then Alt-F11.
