### ISSUE TITLE
requestAnimationFrame

### ISSUE THREAD

**Issue by isglass** [PrismJS/prism#987]
Hi,

Some of our visitors seem to use browsers lacking support for requestAnimationFrame. We highlight on demand so it is not needed for them. Propose the following fix:

`requestAnimationFrame(_.highlightAll, 0);`

Changed to:

`if (window.requestAnimationFrame) window.requestAnimationFrame(_.highlightAll, 0);`

Regards,
Johan

**Comment by Golmote** [comment]
I'd rather fallback on setTimeout since we're supposed to support IE9.

**Comment by zeitgeist87** [comment]
Do we really have to support IE9? We could also simply add a polyfill for `requestAnimationFrame` to the `ie8` plugin, or create an `ie9` plugin with the polyfill...
