### ISSUE TITLE
Expose unminified JS files in the jspm config?

### ISSUE THREAD

**Issue by diagramatics** [PrismJS/prism#995]
Hi there. I'm not sure about the decision to expose the JS files in `components` as minified files in JSPM.

``` json
"jspm": {
    "main": "prism",
    "registry": "jspm",
    "jspmPackage": true,
    "format": "global",
    "files": [
      "components/**/*.min.js",
      "plugins/**/*",
      "themes/*.css",
      "prism.js"
    ]
}
```

Considering that JSPM is often used alongside the SystemJS module bundler, which takes care of minification as well, this could cause issues like a difficult source to read. I know Bower adopts this approach of exposing an unminified code for the sake of giving developers the control they might need, and I'm pretty sure this approach can be applied here.

Happy to make a PR if there's an agreement. Thanks in advance!

**Comment by Golmote** [comment]
@eriklieben, since [you originally added](https://github.com/PrismJS/prism/pull/918) special configuration for JSPM, do you have any opinion on this?

**Comment by eriklieben** [comment]
I must honestly say that I haven't been using JSPM/SystemJS in the last year or so and that knowledge faded away. It sounds like a good thing to do, so the dev using it is in charge of the way to do minification to the files.

**Comment by Golmote** [comment]
@eriklieben Ok, thanks!
