### ISSUE TITLE
Line number not working when using prism in Ghost blog platform.

### ISSUE THREAD

**Issue by jaggerwang** [PrismJS/prism#999]
When download prism, I selected all languages and plugins including "Line Highlight", "Line Number" and "Show Language". Everything is work fine, just except "Line Highlight" and "Line Number". The page is here, https://blog.zaiqiuchang.com/develop-and-deploy-api-service-with-go-and-docker-deploy/.

![image](https://cloud.githubusercontent.com/assets/1255011/16795863/2ecebe42-4912-11e6-8b2b-67ba8ad5ec04.png)

![image](https://cloud.githubusercontent.com/assets/1255011/16795890/4e2a699e-4912-11e6-97ee-e4ed3cd2575b.png)

**Comment by Flynxify** [comment]
Check the plugin-pages to get additional information about how to use them. Line numbering only works if you add an additional class to your desired pre: http://prismjs.com/plugins/line-numbers/ and line highlighting needs a data-line-attribute http://prismjs.com/plugins/line-highlight/

**Comment by jaggerwang** [comment]
ok，Thanks！
